### ISSUE TITLE
DuckieTV doesn't report the torrent download status correctly

### ISSUE THREAD

**Issue by Primeey** [SchizoDuckie/DuckieTV#1001]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Stable 1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows

**Describe the problem you are having and steps to reproduce if available**
DuckieTV gets stuck on "Connecting to peers... please wait" and the download progress bar does nothing even though the torrent is going fine in qBittorrent. When the torrent finishes DuckieTV still reports as if the torrent never started and isn't marked as downloaded until I manually mark it.

![untitled](https://user-images.githubusercontent.com/8511642/33482574-980a4846-d691-11e7-8d72-656aa384b5bb.png)

**Comment by garfield69** [comment]
I have tested this on my win7 x32 development platform with the latest source and qBt 4.0.2 and I cannot replicate your problem.

*Progress 6.9%*
![image](https://user-images.githubusercontent.com/6933240/33498164-3e6a87ac-d735-11e7-8e06-acad1687b291.png)
*Completed and auto-stopped*
![image](https://user-images.githubusercontent.com/6933240/33498246-864c7cec-d735-11e7-9e7a-8fc93933da30.png)

So I suggest the following:    
- make a backup using the *DuckieTV > Settings > Backup* side panel
- download and install the latest Nightly from https://github.com/DuckieTV/Nightlies/releases
- repeat your test
- if you still see the same problem, press the **F12** key to open the *Development Tools* page
- click on the **console** tab to view the log
- and look for any error messages related to qBt
