### ISSUE TITLE
TorrentDownloads SE paired with uTorrent WEBUI unable to sent torrents to client

### ISSUE THREAD

**Issue by lehcim1973** [SchizoDuckie/DuckieTV#1003]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Nightly v201712020130

**What is your Operating System (Windows, Mac, Linux, Android)**
Mac

**Describe the problem you are having and steps to reproduce if available**
Autodownload won't work anymore (used to work fine). At launch, Duckie detects shows that are not downloaded and launch the download (I can see the notification popping up), but they do not show up in the torrent client. I tried upgrading to the release 1.1.5 and the latest nightly. I also tried with several torrent clients (deluge, utorrent, vuze).

**Attach any DuckieTV statistics or Developer Console logs if available**
When I open the console, this is the message that keeps popping up in red : 
app.js:378 POST http://uid:pwd@localhost:8080/gui/?token=4KZrTXwCP1whWULz5K2kTwE91b1Ly6ctdMVJG-P5e3FI3FdpBELjCUynIloAAAAA&action=add-url 400 (ERROR)

**Comment by garfield69** [comment]
could you click on the DuckieTV *About* icon near the bottom left of the main DuckieTV page, and scroll down to the statistics section. Click on the *Statistics* header (which should copy the stats to your clipboard). Then paste the contents here please.
![image](https://user-images.githubusercontent.com/6933240/33517744-44c0ce86-d7ee-11e7-916e-73dd84a61dc6.png)

**Comment by lehcim1973** [comment]
Here it is. Thank you for your help Garfield.

[
  {
    "name": "DuckieTV Web Based",
    "data": "201712020130"
  },
  {
    "name": "Current Date and Time",
    "data": "Sat, 02 Dec 2017 18:40:20 GMT"
  },
  {
    "name": "NWJS, Chromium",
    "data": "0.26.6 , 62.0.3202.94"
  },
  {
    "name": "UserAgent",
    "data": "DuckieTV-Standalone  Nightly v201712020130 Macintosh; Intel Mac OS X 10_13_1"
  },
  {
    "name": "Platform, Vendor",
    "data": "MacIntel, Google Inc."
  },
  {
    "name": "Screen (width x height)",
    "data": "2560 x 1440"
  },
  {
    "name": "Default Search Engine",
    "data": "TorrentDownloads (Enabled)"
  },
  {
    "name": "Default Torrent Client",
    "data": "uTorrent Web UI (Enabled and Connected to Host)"
  },
  {
    "name": "Auto Download Service",
    "data": "(Enabled but Inactive)"
  },
  {
    "name": "Last checked TraktTV for DB updates on",
    "data": "Sat, 02 Dec 2017 12:26:46 GMT"
  },
  {
    "name": "User Preferences on Local Storage",
    "data": "{\n  \"ThePirateBay.mirror\": \"https://thepiratebay.org\",\n  \"application.language\": \"en_us\",\n  \"application.locale\": \"en_us\",\n  \"autobackup.period\": \"monthly\",\n  \"autodownload.delay\": 15,\n  \"autodownload.multiSE\": {\n    \"ThePirateBay\": true,\n    \"1337x\": true,\n    \"IsoHunt\": true,\n    \"KATcr\": true,\n    \"Nyaa\": true,\n    \"RarBG\": true,\n    \"ShowRSS\": true,\n    \"TorrentDownloads\": true,\n    \"TorrentZ2\": true,\n    \"Zooqle\": true,\n    \"EzTV.ag\": true,\n    \"Idope\": true,\n    \"LimeTorrents\": true,\n    \"SkyTorrents\": true\n  },\n  \"autodownload.multiSE.enabled\": false,\n  \"autodownload.period\": 7,\n  \"background-rotator.opacity\": \"0.4\",\n  \"calendar.mode\": \"date\",\n  \"calendar.show-downloaded\": true,\n  \"calendar.show-episode-numbers\": false,\n  \"calendar.show-specials\": true,\n  \"calendar.startSunday\": true,\n  \"client.determinedlocale\": \"en_uk\",\n  \"download.ratings\": true,\n  \"episode.watched-downloaded.pairing\": true,\n  \"kc.always\": false,\n  \"lastSync\": -1,\n  \"library.order.by\": \"getSortName()\",\n  \"library.order.reverseList\": [\n    true,\n    false,\n    true,\n    true\n  ],\n  \"library.seriesgrid\": true,\n  \"library.smallposters\": true,\n  \"main.viewmode\": \"todo\",\n  \"notifications.enabled\": true,\n  \"series.displaymode\": \"poster\",\n  \"series.not-watched-eps-btn\": false,\n  \"storage.sync\": false,\n  \"subtitles.languages\": [\n    \"eng\"\n  ],\n  \"sync.progress\": true,\n  \"synology.enabled\": true,\n  \"synology.username\": \"admin\",\n  \"synology.password\": \"*****\",\n  \"synology.port\": 5000,\n  \"synology.protocol\": \"http\",\n  \"synology.ip\": \"192.168.x.x\",\n  \"synology.playback_devices\": {},\n  \"topSites.enabled\": false,\n  \"topSites.mode\": \"onhover\",\n  \"torrentDialog.2.activeSE\": {\n    \"ThePirateBay\": true,\n    \"1337x\": true,\n    \"IsoHunt\": true,\n    \"KATcr\": true,\n    \"Nyaa\": true,\n    \"RarBG\": true,\n    \"ShowRSS\": true,\n    \"TorrentDownloads\": true,\n    \"TorrentZ2\": true,\n    \"Zooqle\": true\n  },\n  \"torrentDialog.2.enabled\": false,\n  \"torrentDialog.2.sortBy\": \"+engine\",\n  \"torrentDialog.showAdvanced.enabled\": true,\n  \"torrenting.autodownload\": true,\n  \"torrenting.autostop\": true,\n  \"torrenting.autostop_all\": false,\n  \"torrenting.client\": \"uTorrent Web UI\",\n  \"torrenting.directory\": true,\n  \"torrenting.enabled\": true,\n  \"torrenting.ignore_keywords\": \"\",\n  \"torrenting.ignore_keywords_enabled\": true,\n  \"torrenting.min_seeders_enabled\": false,\n  \"torrenting.min_seeders\": 50,\n  \"torrenting.require_keywords\": \"\",\n  \"torrenting.require_keywords_mode_or\": true,\n  \"torrenting.require_keywords_enabled\": true,\n  \"torrenting.global_size_max\": null,\n  \"torrenting.global_size_max_enabled\": true,\n  \"torrenting.global_size_min\": null,\n  \"torrenting.global_size_min_enabled\": true,\n  \"torrenting.label\": false,\n  \"torrenting.launch_via_chromium\": false,\n  \"torrenting.progress\": true,\n  \"torrenting.searchprovider\": \"TorrentDownloads\",\n  \"torrenting.searchquality\": \"\",\n  \"torrenting.searchqualitylist\": [\n    \"480p\",\n    \"HDTV\",\n    \"720p\",\n    \"1080p\",\n    \"2160p\"\n  ],\n  \"torrenting.streaming\": true,\n  \"trakt-update.period\": 12,\n  \"trakttv.passwordHash\": \"*****\",\n  \"trakttv.sync\": false,\n  \"trakttv.username\": null,\n  \"utorrentwebui.password\": \"*****\",\n  \"utorrentwebui.port\": 8080,\n  \"utorrentwebui.server\": \"http://localhost\",\n  \"utorrentwebui.use_auth\": true,\n  \"utorrentwebui.username\": \"michel\",\n  \"autodownload.lastrun\": 1512220502277\n}"
  },
  {
    "name": "Other significant Local Storage keys",
    "data": "{\n  \"1.1.4TorrentHashListCleanup\": \"Sat Dec 02 2017 13:26:34 GMT+0100 (CET)\",\n  \"1.1.4cleanupOrphanedEpisodes\": \"Sat Dec 02 2017 13:26:32 GMT+0100 (CET)\",\n  \"1.1.4cleanupOrphanedSeasons\": \"Sat Dec 02 2017 13:26:33 GMT+0100 (CET)\",\n  \"1.1.4qBittorrentPre32\": \"Sat Dec 02 2017 13:26:28 GMT+0100 (CET)\",\n  \"1.1.4refresh\": \"Sat Dec 02 2017 13:26:48 GMT+0100 (CET)\",\n  \"1.1.4refreshTrendingCache\": \"Sat Dec 02 2017 13:26:28 GMT+0100 (CET)\",\n  \"1.1.4updateTransmissionPath\": \"Sat Dec 02 2017 13:26:28 GMT+0100 (CET)\",\n  \"1.1.5FetchFirstXemAliasMap\": \"Sat Dec 02 2017 13:45:13 GMT+0100 (CET)\",\n  \"1.1.5deleteSearchEngines\": \"Sat Dec 02 2017 13:26:28 GMT+0100 (CET)\",\n  \"1.1.5fanartCleanup\": \"Sat Dec 02 2017 13:27:08 GMT+0100 (CET)\",\n  \"1.1.5updateDelugeAuth\": \"Sat Dec 02 2017 13:26:28 GMT+0100 (CET)\",\n  \"1.1.5updateTorrenting.min_seeders\": \"Sat Dec 02 2017 13:26:28 GMT+0100 (CET)\",\n  \"1.1.6deleteWatchList\": \"Sat Dec 02 2017 14:06:27 GMT+0100 (CET)\",\n  \"1.1migration\": \"Sat Dec 02 2017 13:26:31 GMT+0100 (CET)\",\n  \"autobackup.lastrun\": \"1512217588133\",\n  \"database.version.Episodes\": \"14\",\n  \"database.version.Fanart\": \"1\",\n  \"database.version.Jackett\": \"2\",\n  \"database.version.Seasons\": \"6\",\n  \"database.version.Series\": \"16\",\n  \"database.version.WatchList\": \"1\",\n  \"database.version.WatchListObject\": \"1\",\n  \"fanart.bootstrapped\": \"1\",\n  \"github.lastupdatecheck\": \"1512217588853\",\n  \"snr.lastFetched\": \"1512217588369\",\n  \"standalone.position\": \"{\\\"width\\\":1000,\\\"height\\\":750,\\\"x\\\":780,\\\"y\\\":345,\\\"state\\\":\\\"normal\\\"}\",\n  \"standalone.zoomlevel\": \"6\",\n  \"torrenting.client\": \"uTorrent Web UI\",\n  \"trackers.lastFetched\": \"1512217588858\",\n  \"trakttv.lastupdated\": \"1512217606719\",\n  \"trakttv.lastupdated.trending\": \"1512217927953\",\n  \"trakttv.refresh_token\": \"f0b52c40bebc83f8b55ab9e63f2bc5b2be554417d7938a5e8541dfe044e9f212\",\n  \"uniqueId\": \"9f3d8fd5-3ebb-abe7-d673-edbf39bd8c25\",\n  \"upgrade.notify\": \"1.1.5\",\n  \"xem.lastFetched\": \"1512218713723\"\n}"
  },
  {
    "name": "DB Series",
    "data": 84
  },
  {
    "name": "DB Series Hidden From Calendar",
    "data": 0
  },
  {
    "name": "DB Seasons",
    "data": 424
  },
  {
    "name": "DB Episodes",
    "data": 5858
  },
  {
    "name": "DB Fanart",
    "data": 2634
  },
  {
    "name": "DB Jackett",
    "data": 0
  }
]

**Comment by garfield69** [comment]
The problem seems to be with the combination of using the *TorrentDownloads* search engine paired with using the uTorrent WEBUI client.

If I connect to uTorrent via the API client instead of the WEBUI, or if I use the qBitTorrent32+ client, then I can get torrents from TorrentDownloads sent to those clients just fine, and if I switch the Search Engine to TPB or Zooqle then I can use those search engines with the uTorrent WEBUI client as well.     

So while I dig deeper into what it is about pairing TorrentDownloads and uTorrent WEBUI that does not  combine, I suggest you try out one of the other Search Engines and see how you go.

**Comment by lehcim1973** [comment]
Thank you Garfield. I switched my preferred search engine to Zoogle and everything now works fine. Thank you very much.
