### ISSUE TITLE
[Bug] some Jackett Downloads Not Working

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#1008]
Sometimes when downloading using Jacket search engine and qBittorrent, downloads don’t always work.

The notification in the bottom corner pops up although the torrent hasn’t actually been added and nothing else changes. 

Although, this problem is intermittent and only seems to be occurring with Jackett, I have attached the errors below.

![capture](https://user-images.githubusercontent.com/16563034/33880958-3627b396-df2b-11e7-9774-dcfb96149d9a.JPG)

**Comment by garfield69** [comment]
which indexer from jackett are you using when you get the unknown_url_scheme/xhr error on duckietv?     

as an aside, you can probably fix the err_address_unreachable error for the TPB by going to the duckietv *settings > torrent search engines > the pirate bay* and updating the *piratebay main mirror* address to `https://thepiratebay.org/` followed by clicking on the *validate and save* button.

**Comment by zero77** [comment]
Thanks I updated the TPB Domain and its ok now.

Also, I am using multiple search engines in one entry ‘http://127.0.0.1:9117/api/v2.0/indexers/all/results/torznab/’ 
so, I will test different entries to see if one or multiple of them is the problem.

**Comment by garfield69** [comment]
I suspect this problem has more to do with Jackett than with DuckieTV.     
There are some Jackett indexers whose download links fail occasionally. (see https://github.com/Jackett/Jackett/issues/2299 as an example).
And there is nothing DuckieTV can do about that.
I'm going to close this ticket.
However, if you can prove that a download link works on the Jackett Dashboard, but does not work when used by DuckieTV through its Jackett interface, then we can re-open this ticket and look deeper.

**Comment by zero77** [comment]
Yes, I think you may be right, thanks any way.
