### ISSUE TITLE
[Bug] qBittorrent Unauthorised Error

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#1009]
DuckieTV has stopped being able to connect to qBittorrent, I keep getting these error messages.
I have double checked the username and password also, I tried using no username and password with the no authentication for localhost option checked in qBittorrent. At a guess something may have changed in a recent nightly qBittorrent update though, I could be wrong.
Thanks

![capture](https://user-images.githubusercontent.com/16563034/34070094-11ddfc3c-e257-11e7-9660-83988c71fc9a.JPG)
![capture2](https://user-images.githubusercontent.com/16563034/34070095-16f49d66-e257-11e7-957a-8008888239f1.JPG)
![capture3](https://user-images.githubusercontent.com/16563034/34070100-33b55832-e257-11e7-9103-ea6a094a5ab4.JPG)

**Comment by garfield69** [comment]
I've no problem connecting DuckieTV Standalone 1.1.5 Win7 32bit with qBitTorrent Stable 4.0.2 using authentication over localhost http port 8085.
![image](https://user-images.githubusercontent.com/6933240/34072954-29236776-e2f5-11e7-8144-46b94e4d77d2.png)

Which version of qBt are you using, and where did you source the installer from?
Also which version of DuckieTV are you using, and on which platform?
This is my qBt webui setup
![image](https://user-images.githubusercontent.com/6933240/34073031-ff12f0c2-e2f5-11e7-8651-e42d07df1c21.png)
what does yours look like?

**Comment by zero77** [comment]
Sorry I should have said, I am using Ubuntu with qbi nightly from the official repository on the qbi website and Duckie nightly.
I am using the webui and I have tried both no authentication for localhost option checked and unchecked.

**Comment by garfield69** [comment]
can you post the link to the qBt nightly you are using so I can try it on my Ubuntu 17 devbox ?     
Also, once you have enabled the qBt nightly's webui with authorisation, have you checked that you can access it from your chrome browser directly, to prove that everything on the qBt side is set up properly?
usually `localhost:8080` at the chrome browser address should get you the qBt login challenge, and the correct user and pswd should return the webui.

**Comment by zero77** [comment]
You may need to remove the old repository and uninstall qBt `sudo add-apt-repository ppa:qbittorrent-team/qbittorrent-unstable` 
Yes it works correctly when you login with a web browser on localhost.

**Comment by garfield69** [comment]
and what command are you using to install qBt?

**Comment by zero77** [comment]
After I removed the stable repository and then added the unstable repository. I ran `sudo apt-get purge qbittorrent` and `sudo apt-get purge qbittorrent-nox` then `sudo apt-get install qbittorrent` and `sudo apt-get install qbittorrent-nox`

**Comment by garfield69** [comment]
and are you using the headless qBt (qbitttorrent-nox) or the GUI qBt (qbittorrent) with the DuckieTV nightly ?

**Comment by zero77** [comment]
Normally the headless qBt

**Comment by garfield69** [comment]
raised https://github.com/qbittorrent/qBittorrent/issues/8057

**Comment by zero77** [comment]
Thanks

**Comment by garfield69** [comment]
qBt team have fixed the issue with commit https://github.com/qbittorrent/qBittorrent/commit/b8277614ecf719e5ec1f710aa1ef68407f587577

**Comment by zero77** [comment]
thank you

**Comment by jmconde** [comment]
The best solution is to downgrade to a previous version of qBittorrent at:

https://sourceforge.net/projects/qbittorrent/files/?source=navbar
