### ISSUE TITLE
All 100% downloaded Transmission torrents set to Stopped even though TORRENT AUTO-STOP ALL is disabled

### ISSUE THREAD

**Issue by marcelpaulo** [SchizoDuckie/DuckieTV#1010]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Stable 1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
Xubuntu 17.10

**Describe the problem you are having and steps to reproduce if available**
I've just installed DuckieTV for the very first time, and followed exactly these steps:

1. Connected to trakt.tv and imported my shows
1. Chose my torrent client: Transmission
1. Downloaded an episode: Madam Secretary S04E10

Everything worked fine, but as a side effect, after the episode finished downloading, DuckieTV changed its status to Stopped, **and also** of all torrents that were 100% downloaded. I've seen that config option `TORRENT AUTO-STOP` is enabled by default, which would explain why the episode torrent was set to Stopped when it finished downloading. However, option `TORRENT AUTO-STOP ALL` is disabled by default, so my other torrents that were 100% downloaded shouldn't have had their status changed to Stopped. So, it looks like option `TORRENT AUTO-STOP ALL` is not being honored.

Here are the `TORRENT AUTO-STOP` config options:
![image](https://user-images.githubusercontent.com/10074769/34087164-5bc45828-e388-11e7-895d-0f71413684a7.png)

Not sure if this is relevant, but I run _Transmission_ daemon version **2.92-2ubuntu3**.

Please let me know how I can help debug this further.

**Attach any DuckieTV statistics or Developer Console logs if available**

**EDIT:** Not sure what command DuckieTV sends to Transmission to stop the torrents, but I can't make them go back seeding. I tried to start, tried to resume them, but they go back to Stopped. 

**EDIT 2:** I've just discovered that, if I disable `Torrent Auto-Stop`, then neither the episodes nor my other completed torrents are changed to Stopped.

**Comment by garfield69** [comment]
Thanks for reporting.
Clearly the the auto-stop-all function is not behaving when used with the transmission client.     
When I get some free time I will set up my sandbox with transmission and do some debugging to try to figure out what is going on.     
Disabling auto-stop will turn off ALL auto-stopping features, but having auto-stop enabled with auto-stop-all disabled is supposed to allow you to stop torrents submitted via duckietv but leave all other active transmission torrents alone.

**Comment by marcelpaulo** [comment]
Hey, @garfield69, thank you so much for the swift reply ! I've just started using DuckieTV and I'm amazed at 2 things: how incredibly useful DuckieTV is, and how attentive and swift you guys are. As far as my needs go, disabling auto-stop altogether is really what I want, so, even though I accidentally bumped into this bug, it won't affect me.
