### ISSUE TITLE
Series hidden in trakt.tv calendar and watched progress sections appear on DuckieTV calendar

### ISSUE THREAD

**Issue by marcelpaulo** [SchizoDuckie/DuckieTV#1011]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Stable 1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
Xubuntu 17.10

**Describe the problem you are having and steps to reproduce if available**
Series which I have hidden in trakt.tv, both in section _Calendars_ and _Watched Progress & Up Next_, appear in DuckieTV calendar after connecting to trakt.tv and importing. After I installed DuckieTV, all I did was:
1. Connect to trakt.tv and import my series
1. Select my torrent client: Transmission
1. Download an episode: Madam Secretary S04E10

 I'm not sure if this is the expected behaviour, if there's something else I should configure, or if it's a bug.

To give an example, series _Strike Back_ is hidden in both trakt.tv sections:
![image](https://user-images.githubusercontent.com/10074769/34087715-16ec66c4-e38c-11e7-8601-7a6ec02ae715.png)
![image](https://user-images.githubusercontent.com/10074769/34087729-2ea0a73a-e38c-11e7-8c7e-c14e79b0339a.png)
but it appears on DuckieTV calendar:
![screenshot_2017-12-18_00-43-42](https://user-images.githubusercontent.com/10074769/34087784-892c7896-e38c-11e7-806b-f54c29a3944e.png)

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by Js41637** [comment]
DuckieTV currently does not check those things. It will import everything in your collection and watched history.

**Comment by marcelpaulo** [comment]
Thanks for clarifying, @Js41637. What I'd like to do is: to keep the watched history of these hidden series, but don't show them on the calendar nor auto-download the unwatched episodes. I can see that DuckieTV has options `Hide series on calendar` and `Remove from favorites`. Suppose I enable trakt.tv sync and torrent auto-download (I haven't done yet, until I sort these doubts out):
1. If I enable `Hide series on calendar`, will the unwatched episodes be auto-downloaded just the same ?
1. If I enable `Remove from favorites`, will DuckieTV remove the series from my watched list in trakt.tv ?

**Comment by garfield69** [comment]
>If I enable Hide series on calendar, will the unwatched episodes be auto-downloaded just the same ?      

Hidden series on calendar are not auto-downloaded.    
Additional ways to stop auto-downloading:      
1. For active series on the calendar, you can also stop the auto-download service from downloading specials by using the *hide specials* on the calendar via the *Settings > Calendar > specials on calendar* sidepanel.
2. And you can disable auto-downloading for any active series on the calendar by disabling the *Series Details > Settings > Autodownload this show* check box.

>If I enable Remove from favorites, will DuckieTV remove the series from my watched list in trakt.tv ?    

By clicking the *Remove from Favourites* button on the *Series Details* side panel will delete that series and its episodes from DuckieTV's database, but it will leave your Trakt.TV account data alone.     

The DuckieTV's Trakt.TV sync option so far does the following: 
1. When a DuckieTV episode is marked as watched/not watched, an episode history record is sent to your Trakt.TV account
2. When a DuckieTV episode is marked a downloaded / not downloaded, your Trakt.TV episode collection  is added/deleted.
3. DuckeTV does not yet deal with Trakt.TV WatchLists.
4. The Trakt.TV sync is not a true two way sync, changes you make to your Trakt.TV account do not automatically change the DuckieTV database.

**Comment by marcelpaulo** [comment]
Hey, @garfield69, thanks a lot for taking the time and patience to explain this in so much detail: this serves as great reference material. So what I need to do is:
1. Hide from the DuckieTV calendar all my trakt.tv hidden series, to prevent them from being auto-downloaded and at the same time keeping their watched history on the favorites list
1. Activate trakt.tv sync and always mark episodes as watched on DuckieTV, so that DuckieTV and trakt.tv are in sync

All my doubts are resolved !
