### ISSUE TITLE
Nyaa.si slight problem

### ISSUE THREAD

**Issue by cajeiri** [SchizoDuckie/DuckieTV#1012]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Chrome New Tab
**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Latest Nightly
**What is your Operating System (Windows, Mac, Linux, Android)**
Win 7 64bit SP1

**Describe the problem you are having and steps to reproduce if available**
When searching for The Ancient Magus' Bride (Mahoutsukai no Yome), a fairly large part of the torrents from Nyaa.si do not show up. A good example is inputting "Horriblesubs Mahoutsukai no Yome" in both the website and DuckieTV. Some versions of the file are missing. 

**Attach any DuckieTV statistics or Developer Console logs if available**
None available atm, since not at home. Will get some if required.

**Comment by garfield69** [comment]
The next nightly that the buildbot should release in about 7 hours or so from now, should have this fix.
The nyaa..si site changed their search results html, causing our search engine definition to sometimes pick the wrong releasename selector.

**Comment by cajeiri** [comment]
I guessed as much, since they did say the website would get frequent updates to make it work better compared to its predecessor. Thanks for the quick fix, garfield :+1:
