### ISSUE TITLE
Remove Series Doesn’t Remove From Trakt.TV

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#1017]
When you remove a series from your DuckieTV favourites, it still left in your Trakt.Tv favourites.
So, when you import from Trakt.Tv it comes back again.

**Comment by garfield69** [comment]
Not really a *bug*, since there is no current code for this.
But it is something we could implement so I'll flag this as an *enhancement request*.

**Comment by zero77** [comment]
ok, thanks
