### ISSUE TITLE
[Feature Request] If Fail Try Next Entry

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#1021]
Can you please get ducky to try the next search entry if the initial entry tried fails.

Because when using jacket all, search engine option some search engines fail, if ducky automatically tryed the next entry this would fix it at duckys end.

Thanks

**Comment by garfield69** [comment]
DuckieTV assumes that the Jackett **ALL** Search Engine (SE) that you defined on DuckieTV is just another SE like all the other SE that DuckieTV knows about.     
DuckieTV does not know that behind the scenes, Jackett is using all it's Indexers to build a results table.     
All that DuckieTV sees is the results as presented by the SE to DuckieTV's search request.

Once DuckieTV gets the results, it applies it own filter criteria, and for the Torrent Search Dialogue (TSD), presents all the results that pass the filters, or in the case of the Automated-Download-Service (ADS), it uses the download link of the first result that passes the filters.

Once you click on a download link on the TSD, the success or failure of the link is out of DuckieTV's control. 
The same goes for the ADS, once the download is initiated it is out of DuckieTV's control. Success or failure of the download link at this point is not within DuckieTV's ability to manage.

**Comment by zero77** [comment]
Unless I am mistaken I thought, duckie sorts all the entries under the default SE, by seed and chooses the one with the highest seeds.

If so, I was meaning if the first entry with the highest amount of seed fails, that is by not showing up in the torrent client after it's been added, then duckie should try the next entry with the highest amount of seeds automatically.

If that makes sense

**Comment by garfield69** [comment]
If Jackett is passing links that do not work, then the proper way to fix this is to raise a ticket with the  Jackett team and have them fix the problem.     
DuckieTV expects all SE to pass valid download links, and it is not reasonable to ask DuckieTV to have to create special handlers to cater for an SE that does not do the job it's designed for.
