### ISSUE TITLE
Stuck writing to db

### ISSUE THREAD

**Issue by spmilden** [SchizoDuckie/DuckieTV#1023]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...V1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
...Windows 7

**Describe the problem you are having and steps to reproduce if available**
...DuckieTV has been stuck at the same place trying to write to the db for hours. See attached screenshot.
![duckietv](https://user-images.githubusercontent.com/35412880/34912324-ba131822-f8ac-11e7-9e6b-88ac5f26297a.jpg)

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
1. Shut DuckieTV down.
2. locate the DuckieTV data folder at `C:\Users\<username>\AppData\Local\DuckieTV-Standalone` and make a clone of the folder( and all its content) as a precautionary backup, for instance to `C:\Users\<username>\AppData\Local\DuckieTV-Standalone1.1.5`
3. install the latest standalone nightly from https://github.com/DuckieTV/Nightlies/releases (which has development tools including a log)
4. Start the Nightly and check if it is all is working
5. if your DB write get stuck again, then open the log ( **F12** and click on the **console** tab) and look for errors.
6. Also check the background log (right click mouse on the main DuckieTV calendar page, but below the calendar itself, so you get a submenu, and select **inspect background page** )
![image](https://user-images.githubusercontent.com/6933240/34912808-f6176b28-f94e-11e7-8122-63752dcefb89.png)
and check the background log on there for errors.
7. let me know if it is working or if you have problems.

**Comment by spmilden** [comment]
Thanks for the speedy reply to my post. So far so good.
