### ISSUE TITLE
Help connecting utorrent to DuckieTV

### ISSUE THREAD

**Issue by AllinPhil** [SchizoDuckie/DuckieTV#1024]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))** chrome extension
...

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...v 1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
...
mac
**Describe the problem you are having and steps to reproduce if available**
...
the web ui integration has been working forever and last few weeks it seems it can not connect to utorrent so i am unable to auto download torrents. have tried all the troubleshooting but to no avail

**Attach any DuckieTV statistics or Developer Console logs if available**

...Unable to connect to uTorrent Web UI Retry in 15 seconds
token.html Failed to load resource: the server responded with a status of 404 (Client error)
deps.js:2353 uTorrent Web UI Connect call failed.
(anonymous) @ deps.js:2353
(anonymous) @ deps.js:2326
(anonymous) @ deps.js:2367
$eval @ deps.js:2381
$digest @ deps.js:2378
$apply @ deps.js:2381
l @ deps.js:2333
completeRequest @ app.js:401
requestLoaded @ app.js:342
app.js:3946 uTorrent WEBUI connect error! uTorrent Web UI Connect call failed.
(anonymous) @ app.js:3946
(anonymous) @ deps.js:2366
$eval @ deps.js:2381
$digest @ deps.js:2378
$apply @ deps.js:2381
l @ deps.js:2333
completeRequest @ app.js:401
requestLoaded @ app.js:342
token.html Failed to load resource: the server responded with a status of 404 (Client error)
deps.js:2353 uTorrent Web UI Connect call failed.
(anonymous) @ deps.js:2353
(anonymous) @ deps.js:2326
(anonymous) @ deps.js:2367
$eval @ deps.js:2381
$digest @ deps.js:2378
$apply @ deps.js:2381
l @ deps.js:2333
completeRequest @ app.js:401
requestLoaded @ app.js:342
app.js:3946 uTorrent WEBUI connect error! uTorrent Web UI Connect call failed.
(anonymous) @ app.js:3946
(anonymous) @ deps.js:2366
$eval @ deps.js:2381
$digest @ deps.js:2378
$apply @ deps.js:2381
l @ deps.js:2333
completeRequest @ app.js:401
requestLoaded @ app.js:342
app.js:379 GET http://userpswd@localhost:8080/gui/token.html 404 (Client error)
(anonymous) @ app.js:379
n @ deps.js:2334
(anonymous) @ deps.js:2332
(anonymous) @ deps.js:2366
$eval @ deps.js:2381
$digest @ deps.js:2378
(anonymous) @ deps.js:2381
f @ deps.js:2279
(anonymous) @ deps.js:2282
setTimeout (async)
k.defer @ deps.js:2282
$evalAsync @ deps.js:2381
(anonymous) @ deps.js:2365
e @ deps.js:2366
then @ deps.js:2368
m @ deps.js:2331
m.(anonymous function) @ deps.js:2335
BaseHTTPApi.request @ app.js:8328
portscan @ app.js:15351
connect @ app.js:12098
AutoConnect @ app.js:12011
(anonymous) @ app.js:12026
setTimeout (async)
(anonymous) @ app.js:12024
(anonymous) @ deps.js:2366
$eval @ deps.js:2381
$digest @ deps.js:2378
$apply @ deps.js:2381
l @ deps.js:2333
completeRequest @ app.js:401
requestLoaded @ app.js:342
deps.js:2353 uTorrent Web UI Connect call failed.
(anonymous) @ deps.js:2353
(anonymous) @ deps.js:2326
(anonymous) @ deps.js:2367
$eval @ deps.js:2381
$digest @ deps.js:2378
$apply @ deps.js:2381
l @ deps.js:2333
completeRequest @ app.js:401
requestLoaded @ app.js:342
XMLHttpRequest.send (async)
(anonymous) @ app.js:379
n @ deps.js:2334
(anonymous) @ deps.js:2332
(anonymous) @ deps.js:2366
$eval @ deps.js:2381
$digest @ deps.js:2378
(anonymous) @ deps.js:2381
f @ deps.js:2279
(anonymous) @ deps.js:2282
setTimeout (async)
k.defer @ deps.js:2282
$evalAsync @ deps.js:2381
(anonymous) @ deps.js:2365
e @ deps.js:2366
then @ deps.js:2368
m @ deps.js:2331
m.(anonymous function) @ deps.js:2335
BaseHTTPApi.request @ app.js:8328
portscan @ app.js:15351
connect @ app.js:12098
AutoConnect @ app.js:12011
(anonymous) @ app.js:12026
setTimeout (async)
(anonymous) @ app.js:12024
(anonymous) @ deps.js:2366
$eval @ deps.js:2381
$digest @ deps.js:2378
$apply @ deps.js:2381
l @ deps.js:2333
completeRequest @ app.js:401
requestLoaded @ app.js:342
app.js:12028 Unable to connect to uTorrent Web UI Retry in 15 seconds

**Comment by garfield69** [comment]
what version of utorrent are you using?
has there been an update to your utorrent recently? 
can you connect from your chrome browser to your utorrent webui?
does changing `localhost` to `127.0.0.1` make any difference?
