### ISSUE TITLE
[Feature Request] Header Less Device Support

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#1027]
To my knowledge there’s no way to run DuckieTV on any header less device like, a seed box, Linux server or Raspberry Pi.

So, can you please add support for DuckieTV to run on header less devices, unless you can suggest a way to run DuckieTV on a header less device.
Thanks

**Comment by garfield69** [comment]
The situation is that the author has pretty much suspended his contributions, so there is no development of new features.
I have currently just enough free time to do basic problem support and bug fixes, but do not have time to start any new projects.
When I can, I work on finishing existing projects that are partly completed, as long as they are not too complex.
