### ISSUE TITLE
[Feature Request] ruTorrent Support

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#1030]
Can you please add support for ruTorrent which is a web-ui for rtorrent.
Thanks

https://github.com/Novik/ruTorrent

**Comment by garfield69** [comment]
you mean like this https://github.com/SchizoDuckie/DuckieTV/wiki/FAQ#how-to-connect-with-a-rutorrent-seedbox ?

**Comment by zero77** [comment]
Yes thanks although, is it possible with the desktop client.

**Comment by garfield69** [comment]
huh? Please rephrase the question, I'm not sure what you are asking.

**Comment by zero77** [comment]
Sorry what I am trying to say is I am wanting to use a desktop duckietv and connect to a remote ruTorrent panel, outside of LAN. But, I am unable to login because there’s nowhere to enter a username or password.

**Comment by garfield69** [comment]
It's my understanding that ruTorrent does not have any authentication.
See https://github.com/Novik/ruTorrent/wiki#not-implemented
So how are you doing the login in at the moment?

**Comment by zero77** [comment]
I am getting a login box pop up asking for the username and password which I set.
I am not connecting to it by localhost I am using its public IP.


![capture](https://user-images.githubusercontent.com/16563034/35638874-3a3c1fa6-06b0-11e8-8c5c-fbce45444a17.JPG)

**Comment by garfield69** [comment]
Right. My point is that this is not ruTorrent doing the popup, but what ever your webserver chooses to provide as security.
So I not able to support this using the DuckieTV torrent client webui code. Sorry.

**Comment by zero77** [comment]
Ok thanks any way.
