### ISSUE TITLE
Library and calendar data wiped out after upgrade

### ISSUE THREAD

**Issue by Porphyry** [SchizoDuckie/DuckieTV#1032]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Chrome extension

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
I just upgraded to the latest version

**What is your Operating System (Windows, Mac, Linux, Android)**
Mac

**Describe the problem you are having and steps to reproduce if available**
I said yes to the latest upgrade of Duckie. When I opened it none of my shows were in my library or calendar.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
Urg.     
I've seen this before, and with a bit of luck, usually the data is still there but not accessible because of a mismatching version/class.       

See if you can find the database, usually on the Mac at:
- Chrome Browser Extension BrowserAction
`~/Library/Application Support/Google/Chrome/<profile>/databases/chrome-extension_cdfkaloficjmdjbgmckaddgfcghgidei_0`
- Chrome Browser Extension NewTab
`~/Library/Application Support/Google/Chrome/<profile>/databases/chrome-extension_hkbamkappmgfjjahmnlngibomenmbbdf_0`
the filename is usually just a number, like `1` or similar.

Also, if you have a recent backup file take with the DuckieTV *Settings > backup* then that will be useful too.
If you upload those two files to a cloud service like *Google Drive* for instance, and post a share link here, I can take a look at the database and see if I can recover the data.

**Comment by Porphyry** [comment]
OK, I will try to post those files. Forgive my ignorance, but I don't know
where they are. Should I go into More tools --> extensions to find them, or
my applications, or somewhere else?

**Comment by garfield69** [comment]
>Should I go into More tools --> extensions to find them, or my applications, or somewhere else?

I don't own a Mac so I can be certain, but in general I expect you can use the following as a base and adjust as you go along.     
1. start by finding out which extension serial number is being used by Chrome Browser for the DuckieTV extension, so on your Chrome Browser use the *More Tools > Extensions*, tick the *Developer Mode* check box, scroll down to the DuckieTV extension and select and copy the ID
2. then start your *Finder* app or use your *Spotlight* search and paste the ID and see what you find.
3. compare your results with the one of the two folders 
Chrome Browser Extension BrowserAction
`~/Library/Application Support/Google/Chrome/<profile>/databases/chrome-extension_cdfkaloficjmdjbgmckaddgfcghgidei_0`
Chrome Browser Extension NewTab
`~/Library/Application Support/Google/Chrome/<profile>/databases/chrome-extension_hkbamkappmgfjjahmnlngibomenmbbdf_0`
where `<profile>` is usually *default* or your Google Browser username.
4. access that folder and hopefully there will be a file called `1`.
5. As for the Backup, that depends. Did you make a backup or has DuckieTV ever asked you to create one. If not then you are not going to find one. If yes, they only you know where you saved the file, but in most cases the default location is probably in the *Downloads* folder.

**Comment by Porphyry** [comment]
Thank you for your continued help with this. When I go into
Library/Applications Support/Google there is no file called Chrome. The
Google folder is in fact empty, except for a file called Custom Buttons. I
guess this means my databases are gone?

I do have a semi-recent backup of Duckie. When I try to import it though it
just says "Loading, Please Wait" forever. I can see the names of all my
shows, but they never actually load. I haven't left if for hours and hours
though. Is there any chance that if I left it overnight, they would load?

**Comment by garfield69** [comment]
>I guess this means my databases are gone?

No, it most likely means that the path I have given you is no longer valid. It's one I saved from the last time a Mac user had a problem, but it is clearly out of date.

> Is there any chance that if I left it overnight, they would load?

No, I suspect that the DB has been mangled.
Your best approach would be to uninstall the extension by using the trash-bin icon on the extensions management page, shut down (Exit) the Chrome Browser and start a fresh instance (which should clear the data space of any leftover extension settings), and install the extension afresh.
Assuming the restart cleaned up the data space properly, then you should get a fresh database and you can import your backup to repopulate your series/settings.

If that does not work then trash the extension and switch to using the Standalone DuckieTV. It has exactly the same code as the extension, encapsulated into the NWJS run time environment that allows the extension to be run as a separate program from the chrome browser. Grab a copy of the Nightly to get the latest bug fixed version of DuckieTV from https://github.com/DuckieTV/Nightlies/releases

Let me know how you go.

**Comment by Porphyry** [comment]
I uninstalled and reinstalled the extension and successfully imported my
backup. Hurrah! I would not have thought to do that without your help.

Please let me know if there is somewhere I can make a small donation to
support your work.

**Comment by garfield69** [comment]
Glad you have it working again.
Thank you for the offer, but we do not accept donations, DTV is free for all TV addicts ;-)
