### ISSUE TITLE
Cannot connect to (mac) Vuze

### ISSUE THREAD

**Issue by forumguy** [SchizoDuckie/DuckieTV#1034]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...

Standalone: 0.21.3 , 57.0.2987.110
--

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...
DuckieTV-Standalone Nightly v201704220130 Macintosh; Intel Mac OS X 10_13_3
**What is your Operating System (Windows, Mac, Linux, Android)**
...

**Describe the problem you are having and steps to reproduce if available**
...
I cannot connect to Vuze anymore. As an FYI, nothing on the network side has changed.
**Attach any DuckieTV statistics or Developer Console logs if available**
...
[
  {
    "name": "DuckieTV Web Based",
    "data": "201704220130"
  },
  {
    "name": "Current Date and Time",
    "data": "Wed, 07 Feb 2018 19:14:28 GMT"
  },
  {
    "name": "NWJS, Chromium",
    "data": "0.21.3 , 57.0.2987.110"
  },
  {
    "name": "UserAgent",
    "data": "DuckieTV-Standalone  Nightly v201704220130 Macintosh; Intel Mac OS X 10_13_3"
  },
  {
    "name": "Platform, Vendor",
    "data": "MacIntel, Google Inc."
  },
  {
    "name": "Screen (width x height)",
    "data": "1280 x 720"
  },
  {
    "name": "Default Search Engine",
    "data": "TorrentZ2 (Enabled)"
  },
  {
    "name": "Default Torrent Client",
    "data": "Vuze (Enabled but Not Connected to Host)"
  },
  {
    "name": "Auto Download Service",
    "data": "(Enabled and Active)"
  },
  {
    "name": "Last checked TraktTV for DB updates on",
    "data": "Wed, 07 Feb 2018 17:58:07 GMT"
  },
  {
    "name": "User Preferences on Local Storage",
    "data": "{\n  \"KickAssTorrents.mirror\": \"https://kat.cr\",\n  \"ThePirateBay.mirror\": \"https://pirateproxybay.tech/\",\n  \"application.language\": \"en_us\",\n  \"application.locale\": \"en_us\",\n  \"autodownload.minSeeders\": 1,\n  \"autodownload.period\": 7,\n  \"background-rotator.opacity\": \"0.4\",\n  \"main.viewmode\": \"calendar\",\n  \"calendar.mode\": \"week\",\n  \"calendar.show-specials\": true,\n  \"calendar.show-downloaded\": true,\n  \"calendar.show-episode-numbers\": true,\n  \"calendar.startSunday\": true,\n  \"client.determinedlocale\": \"en_us\",\n  \"download.ratings\": true,\n  \"lastSync\": -1,\n  \"library.smallposters\": true,\n  \"library.seriesgrid\": true,\n  \"kc.always\": false,\n  \"qbittorrent.server\": \"http://localhost\",\n  \"qbittorrent.port\": 8080,\n  \"qbittorrent.use_auth\": true,\n  \"qbittorrent.username\": \"admin\",\n  \"qbittorrent.password\": \"*****\",\n  \"qbittorrent32plus.server\": \"http://localhost\",\n  \"qbittorrent32plus.port\": 8181,\n  \"qbittorrent32plus.use_auth\": true,\n  \"qbittorrent32plus.username\": \"admin\",\n  \"qbittorrent32plus.password\": \"*****\",\n  \"series.displaymode\": \"poster\",\n  \"storage.sync\": false,\n  \"sync.progress\": true,\n  \"tixati.server\": \"http://localhost\",\n  \"tixati.use_auth\": true,\n  \"tixati.port\": 8888,\n  \"tixati.username\": \"admin\",\n  \"tixati.password\": \"*****\",\n  \"topSites.enabled\": false,\n  \"topSites.mode\": \"onhover\",\n  \"torrenting.autodownload\": true,\n  \"torrenting.autostop\": true,\n  \"torrenting.autostop_all\": false,\n  \"torrenting.client\": \"Vuze\",\n  \"torrenting.directory\": true,\n  \"torrenting.enabled\": true,\n  \"torrenting.progress\": true,\n  \"torrenting.searchprovider\": \"TorrentZ2\",\n  \"torrenting.searchquality\": \"\",\n  \"torrenting.streaming\": true,\n  \"vuze.server\": \"http://184.75.210.74\",\n  \"vuze.port\": 9091,\n  \"vuze.use_auth\": true,\n  \"vuze.username\": \"vuze\",\n  \"vuze.password\": \"*****\",\n  \"transmission.server\": \"http://localhost\",\n  \"transmission.port\": 9091,\n  \"transmission.use_auth\": true,\n  \"transmission.username\": \"admin\",\n  \"transmission.password\": \"*****\",\n  \"trakttv.passwordHash\": \"*****\",\n  \"trakttv.sync\": true,\n  \"trakttv.username\": null,\n  \"utorrentwebui.server\": \"http://localhost\",\n  \"utorrentwebui.port\": 8080,\n  \"utorrentwebui.username\": \"admin\",\n  \"utorrentwebui.password\": \"*****\",\n  \"utorrentwebui.use_auth\": true,\n  \"deluge.server\": \"http://localhost\",\n  \"deluge.port\": 8112,\n  \"deluge.password\": \"*****\",\n  \"deluge.use_auth\": false,\n  \"subtitles.languages\": [\n    \"eng\"\n  ],\n  \"trakt-update.period\": 1,\n  \"autodownload.lastrun\": 1517293820690,\n  \"vuze.path\": \"/transmission/rpc\",\n  \"torrentDialog.showAdvanced.enabled\": true,\n  \"series.not-watched-eps-btn\": false,\n  \"torrenting.global_size_min_enabled\": true,\n  \"autobackup.period\": \"weekly\",\n  \"torrenting.min_seeders\": 1,\n  \"autodownload.multiSE\": {\n    \"ThePirateBay\": true,\n    \"1337x\": true,\n    \"IsoHunt\": true,\n    \"KATcr\": true,\n    \"Nyaa\": true,\n    \"RarBG\": true,\n    \"ShowRSS\": true,\n    \"TorrentDownloads\": true,\n    \"TorrentZ2\": true,\n    \"Zooqle\": true,\n    \"EzTV.ag\": true,\n    \"Idope\": true,\n    \"LimeTorrents\": true,\n    \"SkyTorrents\": true\n  },\n  \"torrenting.global_size_max\": 1000,\n  \"torrenting.global_size_max_enabled\": true\n}"
  },
  {
    "name": "Other significant Local Storage keys",
    "data": "{\n  \"1.1.4TorrentHashListCleanup\": \"Sat Sep 24 2016 19:41:09 GMT-0400 (EDT)\",\n  \"1.1.4cleanupOrphanedEpisodes\": \"Sat Sep 24 2016 19:41:07 GMT-0400 (EDT)\",\n  \"1.1.4cleanupOrphanedSeasons\": \"Wed May 18 2016 02:53:54 GMT-0400 (EDT)\",\n  \"1.1.4qBittorrentPre32\": \"Sat Sep 24 2016 19:41:03 GMT-0400 (EDT)\",\n  \"1.1.4refresh\": \"Sat Sep 24 2016 19:41:11 GMT-0400 (EDT)\",\n  \"1.1.4refreshTrendingCache\": \"Sat Sep 24 2016 19:41:03 GMT-0400 (EDT)\",\n  \"1.1.4updateDelugeAuth\": \"Sat Sep 24 2016 19:41:03 GMT-0400 (EDT)\",\n  \"1.1.4updateTransmissionPath\": \"Sat Sep 24 2016 19:41:03 GMT-0400 (EDT)\",\n  \"1.1.5fanartCleanup\": \"Sat Apr 22 2017 19:51:54 GMT-0400 (EDT)\",\n  \"1.1.5updateTorrenting.min_seeders\": \"Sat Apr 22 2017 19:51:44 GMT-0400 (EDT)\",\n  \"1.1migration\": \"Fri Mar 25 2016 12:38:13 GMT-0400 (EDT)\",\n  \"autobackup.lastrun\": \"1517384406960\",\n  \"database.version.Episodes\": \"13\",\n  \"database.version.SearchEngines\": \"2\",\n  \"database.version.Seasons\": \"6\",\n  \"database.version.Series\": \"15\",\n  \"database.version.WatchList\": \"1\",\n  \"database.version.WatchListObject\": \"1\",\n  \"fanart.bootstrapped\": \"1\",\n  \"github.lastupdatecheck\": \"1458923892155\",\n  \"optin_error_reporting\": \"true\",\n  \"optin_error_reporting.start_time\": \"1517765414504\",\n  \"snr.lastFetched\": \"1517765415844\",\n  \"standalone.minimizeSystray\": \"N\",\n  \"standalone.position\": \"{\\\"width\\\":1280,\\\"height\\\":693,\\\"x\\\":0,\\\"y\\\":23,\\\"state\\\":\\\"maximized\\\"}\",\n  \"standalone.startupMinimized\": \"Y\",\n  \"standalone.zoomlevel\": \"6\",\n  \"torrenting.client\": \"Vuze\",\n  \"trackers.fallBackList\": \"&tr=udp://tracker.coppersurfer.tk:6969/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://9.rarbg.to:2710/announce&tr=udp://p4p.arenabg.com:1337/announce&tr=http://p4p.arenabg.com:1337/announce&tr=udp://tracker.internetwarriors.net:1337/announce&tr=http://tracker.internetwarriors.net:1337/announce&tr=udp://tracker.skyts.net:6969/announce&tr=udp://tracker.safe.moe:6969/announce&tr=udp://tracker.piratepublic.com:1337/announce&tr=udp://tracker.opentrackr.org:1337/announce&tr=http://tracker.opentrackr.org:1337/announce&tr=udp://tracker2.christianbro.pw:6969/announce&tr=udp://tracker1.wasabii.com.tw:6969/announce&tr=udp://tracker.zer0day.to:1337/announce&tr=udp://public.popcorn-tracker.org:6969/announce&tr=udp://tracker.mg64.net:6969/announce&tr=udp://peerfect.org:6969/announce&tr=udp://open.facedatabg.net:6969/announce&tr=udp://mgtracker.org:6969/announce\",\n  \"trackers.lastFetched\": \"1517075925857\",\n  \"trakttv.lastupdated\": \"1518026287694\",\n  \"trakttv.lastupdated.trending\": \"1517790632766\",\n  \"trakttv.refresh_token\": \"d6b4b94c370b403429a323cbfe84c3991d59d0f3c81a23e53f4deb2753249054\",\n  \"uniqueId\": \"37815815-a64b-0e75-6206-c68e3ffb567a\",\n  \"upgrade.notify\": \"1.1.3\",\n  \"xem.lastFetched\": \"1517765415839\"\n}"
  },
  {
    "name": "DB Series",
    "data": 214
  },
  {
    "name": "DB Series Hidden From Calendar",
    "data": 0
  },
  {
    "name": "DB Seasons",
    "data": 1241
  },
  {
    "name": "DB Episodes",
    "data": 27012
  },
  {
    "name": "DB Fanart",
    "data": 2766
  }
][
  {
    "name": "DuckieTV Web Based",
    "data": "201704220130"
  },
  {
    "name": "Current Date and Time",
    "data": "Wed, 07 Feb 2018 19:14:28 GMT"
  },
  {
    "name": "NWJS, Chromium",
    "data": "0.21.3 , 57.0.2987.110"
  },
  {
    "name": "UserAgent",
    "data": "DuckieTV-Standalone  Nightly v201704220130 Macintosh; Intel Mac OS X 10_13_3"
  },
  {
    "name": "Platform, Vendor",
    "data": "MacIntel, Google Inc."
  },
  {
    "name": "Screen (width x height)",
    "data": "1280 x 720"
  },
  {
    "name": "Default Search Engine",
    "data": "TorrentZ2 (Enabled)"
  },
  {
    "name": "Default Torrent Client",
    "data": "Vuze (Enabled but Not Connected to Host)"
  },
  {
    "name": "Auto Download Service",
    "data": "(Enabled and Active)"
  },
  {
    "name": "Last checked TraktTV for DB updates on",
    "data": "Wed, 07 Feb 2018 17:58:07 GMT"
  },
  {
    "name": "User Preferences on Local Storage",
    "data": "{\n  \"KickAssTorrents.mirror\": \"https://kat.cr\",\n  \"ThePirateBay.mirror\": \"https://pirateproxybay.tech/\",\n  \"application.language\": \"en_us\",\n  \"application.locale\": \"en_us\",\n  \"autodownload.minSeeders\": 1,\n  \"autodownload.period\": 7,\n  \"background-rotator.opacity\": \"0.4\",\n  \"main.viewmode\": \"calendar\",\n  \"calendar.mode\": \"week\",\n  \"calendar.show-specials\": true,\n  \"calendar.show-downloaded\": true,\n  \"calendar.show-episode-numbers\": true,\n  \"calendar.startSunday\": true,\n  \"client.determinedlocale\": \"en_us\",\n  \"download.ratings\": true,\n  \"lastSync\": -1,\n  \"library.smallposters\": true,\n  \"library.seriesgrid\": true,\n  \"kc.always\": false,\n  \"qbittorrent.server\": \"http://localhost\",\n  \"qbittorrent.port\": 8080,\n  \"qbittorrent.use_auth\": true,\n  \"qbittorrent.username\": \"admin\",\n  \"qbittorrent.password\": \"*****\",\n  \"qbittorrent32plus.server\": \"http://localhost\",\n  \"qbittorrent32plus.port\": 8181,\n  \"qbittorrent32plus.use_auth\": true,\n  \"qbittorrent32plus.username\": \"admin\",\n  \"qbittorrent32plus.password\": \"*****\",\n  \"series.displaymode\": \"poster\",\n  \"storage.sync\": false,\n  \"sync.progress\": true,\n  \"tixati.server\": \"http://localhost\",\n  \"tixati.use_auth\": true,\n  \"tixati.port\": 8888,\n  \"tixati.username\": \"admin\",\n  \"tixati.password\": \"*****\",\n  \"topSites.enabled\": false,\n  \"topSites.mode\": \"onhover\",\n  \"torrenting.autodownload\": true,\n  \"torrenting.autostop\": true,\n  \"torrenting.autostop_all\": false,\n  \"torrenting.client\": \"Vuze\",\n  \"torrenting.directory\": true,\n  \"torrenting.enabled\": true,\n  \"torrenting.progress\": true,\n  \"torrenting.searchprovider\": \"TorrentZ2\",\n  \"torrenting.searchquality\": \"\",\n  \"torrenting.streaming\": true,\n  \"vuze.server\": \"http://184.75.210.74\",\n  \"vuze.port\": 9091,\n  \"vuze.use_auth\": true,\n  \"vuze.username\": \"vuze\",\n  \"vuze.password\": \"*****\",\n  \"transmission.server\": \"http://localhost\",\n  \"transmission.port\": 9091,\n  \"transmission.use_auth\": true,\n  \"transmission.username\": \"admin\",\n  \"transmission.password\": \"*****\",\n  \"trakttv.passwordHash\": \"*****\",\n  \"trakttv.sync\": true,\n  \"trakttv.username\": null,\n  \"utorrentwebui.server\": \"http://localhost\",\n  \"utorrentwebui.port\": 8080,\n  \"utorrentwebui.username\": \"admin\",\n  \"utorrentwebui.password\": \"*****\",\n  \"utorrentwebui.use_auth\": true,\n  \"deluge.server\": \"http://localhost\",\n  \"deluge.port\": 8112,\n  \"deluge.password\": \"*****\",\n  \"deluge.use_auth\": false,\n  \"subtitles.languages\": [\n    \"eng\"\n  ],\n  \"trakt-update.period\": 1,\n  \"autodownload.lastrun\": 1517293820690,\n  \"vuze.path\": \"/transmission/rpc\",\n  \"torrentDialog.showAdvanced.enabled\": true,\n  \"series.not-watched-eps-btn\": false,\n  \"torrenting.global_size_min_enabled\": true,\n  \"autobackup.period\": \"weekly\",\n  \"torrenting.min_seeders\": 1,\n  \"autodownload.multiSE\": {\n    \"ThePirateBay\": true,\n    \"1337x\": true,\n    \"IsoHunt\": true,\n    \"KATcr\": true,\n    \"Nyaa\": true,\n    \"RarBG\": true,\n    \"ShowRSS\": true,\n    \"TorrentDownloads\": true,\n    \"TorrentZ2\": true,\n    \"Zooqle\": true,\n    \"EzTV.ag\": true,\n    \"Idope\": true,\n    \"LimeTorrents\": true,\n    \"SkyTorrents\": true\n  },\n  \"torrenting.global_size_max\": 1000,\n  \"torrenting.global_size_max_enabled\": true\n}"
  },
  {
    "name": "Other significant Local Storage keys",
    "data": "{\n  \"1.1.4TorrentHashListCleanup\": \"Sat Sep 24 2016 19:41:09 GMT-0400 (EDT)\",\n  \"1.1.4cleanupOrphanedEpisodes\": \"Sat Sep 24 2016 19:41:07 GMT-0400 (EDT)\",\n  \"1.1.4cleanupOrphanedSeasons\": \"Wed May 18 2016 02:53:54 GMT-0400 (EDT)\",\n  \"1.1.4qBittorrentPre32\": \"Sat Sep 24 2016 19:41:03 GMT-0400 (EDT)\",\n  \"1.1.4refresh\": \"Sat Sep 24 2016 19:41:11 GMT-0400 (EDT)\",\n  \"1.1.4refreshTrendingCache\": \"Sat Sep 24 2016 19:41:03 GMT-0400 (EDT)\",\n  \"1.1.4updateDelugeAuth\": \"Sat Sep 24 2016 19:41:03 GMT-0400 (EDT)\",\n  \"1.1.4updateTransmissionPath\": \"Sat Sep 24 2016 19:41:03 GMT-0400 (EDT)\",\n  \"1.1.5fanartCleanup\": \"Sat Apr 22 2017 19:51:54 GMT-0400 (EDT)\",\n  \"1.1.5updateTorrenting.min_seeders\": \"Sat Apr 22 2017 19:51:44 GMT-0400 (EDT)\",\n  \"1.1migration\": \"Fri Mar 25 2016 12:38:13 GMT-0400 (EDT)\",\n  \"autobackup.lastrun\": \"1517384406960\",\n  \"database.version.Episodes\": \"13\",\n  \"database.version.SearchEngines\": \"2\",\n  \"database.version.Seasons\": \"6\",\n  \"database.version.Series\": \"15\",\n  \"database.version.WatchList\": \"1\",\n  \"database.version.WatchListObject\": \"1\",\n  \"fanart.bootstrapped\": \"1\",\n  \"github.lastupdatecheck\": \"1458923892155\",\n  \"optin_error_reporting\": \"true\",\n  \"optin_error_reporting.start_time\": \"1517765414504\",\n  \"snr.lastFetched\": \"1517765415844\",\n  \"standalone.minimizeSystray\": \"N\",\n  \"standalone.position\": \"{\\\"width\\\":1280,\\\"height\\\":693,\\\"x\\\":0,\\\"y\\\":23,\\\"state\\\":\\\"maximized\\\"}\",\n  \"standalone.startupMinimized\": \"Y\",\n  \"standalone.zoomlevel\": \"6\",\n  \"torrenting.client\": \"Vuze\",\n  \"trackers.fallBackList\": \"&tr=udp://tracker.coppersurfer.tk:6969/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://9.rarbg.to:2710/announce&tr=udp://p4p.arenabg.com:1337/announce&tr=http://p4p.arenabg.com:1337/announce&tr=udp://tracker.internetwarriors.net:1337/announce&tr=http://tracker.internetwarriors.net:1337/announce&tr=udp://tracker.skyts.net:6969/announce&tr=udp://tracker.safe.moe:6969/announce&tr=udp://tracker.piratepublic.com:1337/announce&tr=udp://tracker.opentrackr.org:1337/announce&tr=http://tracker.opentrackr.org:1337/announce&tr=udp://tracker2.christianbro.pw:6969/announce&tr=udp://tracker1.wasabii.com.tw:6969/announce&tr=udp://tracker.zer0day.to:1337/announce&tr=udp://public.popcorn-tracker.org:6969/announce&tr=udp://tracker.mg64.net:6969/announce&tr=udp://peerfect.org:6969/announce&tr=udp://open.facedatabg.net:6969/announce&tr=udp://mgtracker.org:6969/announce\",\n  \"trackers.lastFetched\": \"1517075925857\",\n  \"trakttv.lastupdated\": \"1518026287694\",\n  \"trakttv.lastupdated.trending\": \"1517790632766\",\n  \"trakttv.refresh_token\": \"d6b4b94c370b403429a323cbfe84c3991d59d0f3c81a23e53f4deb2753249054\",\n  \"uniqueId\": \"37815815-a64b-0e75-6206-c68e3ffb567a\",\n  \"upgrade.notify\": \"1.1.3\",\n  \"xem.lastFetched\": \"1517765415839\"\n}"
  },
  {
    "name": "DB Series",
    "data": 214
  },
  {
    "name": "DB Series Hidden From Calendar",
    "data": 0
  },
  {
    "name": "DB Seasons",
    "data": 1241
  },
  {
    "name": "DB Episodes",
    "data": 27012
  },
  {
    "name": "DB Fanart",
    "data": 2766
  }
]

**Comment by garfield69** [comment]
1. shutdown DuckieTV
2. using your chrome browser, can you connect to the vuze webui via `http://127.0.0.1:9091` ?
![image](https://user-images.githubusercontent.com/6933240/35945194-2c145ac8-0cc4-11e8-80c1-7171b79aaeab.png)
3. when you get the login challenge can you login?
![image](https://user-images.githubusercontent.com/6933240/35945234-59ff1ad6-0cc4-11e8-8330-23b9c35ed326.png)
4. if so then logout and start up DuckieTV
5. on DuckieTV access the *Settings > Vuze Integration* panel, what does the *Status* say?
![image](https://user-images.githubusercontent.com/6933240/35945363-da5d1ac0-0cc4-11e8-9184-da7dd1350a12.png)

**Comment by forumguy** [comment]
[Vuze and Duckie setup.docx](https://github.com/SchizoDuckie/DuckieTV/files/1705221/Vuze.and.Duckie.setup.docx)

**Comment by garfield69** [comment]
using your web browser can you connect to the vuze webui via `http://184.75.210.74:9091` ?

**Comment by forumguy** [comment]
Same as before, took too long to connect and timed out.

**Comment by garfield69** [comment]
Then the problem is not with DuckieTV, since it appears that you cannot make any connections work to the Vuze WEBUI, whether it is coming from DuckieTV or a Chrome Browser.
Despite you first assertion that there has been no network changes, something clearly is now blocking your traffic to that IP address/port combination.

Some things you can try out or consider checking: 
- Have you rebooted your Mac since the problem has started?
- Has there been any changes to your firewall software, virus protection software?
- Have you tried setting the Vuze WEBUI to using a different port (pick one above 9999 to get free of any default port allocations), then restarting Vuze (to ensure the old port is released and the new one allocated) and seeing if your chrome browser or DuckieTV (once you've restarted DuckieTV too, before trying to modify it's Vuze Integration page and test&save) can connect?
- What about 184.75.210.74, has your local ISP provider allocated you a new ip address? Use `https://whatismyipaddress.com/` to confirm your address.
- Have you tried switching to another torrent client just in case Vuze has been broken? Shut down Vuze and try out Transmission https://transmissionbt.com/ and see it that works.

Good luck.
