### ISSUE TITLE
DuckieTV problem, help please

### ISSUE THREAD

**Issue by CC7785415** [SchizoDuckie/DuckieTV#1037]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
standalone...

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
1.1.3

**What is your Operating System (Windows, Mac, Linux, Android)**
windows

**Describe the problem you are having and steps to reproduce if available**
it doesn't seem to want to "find a torrent" anymore. 

**Attach any DuckieTV statistics or Developer Console logs if available**

**Comment by Js41637** [comment]
If your using Skytorrents, the site no longer exists.

**Comment by garfield69** [comment]
I would recommend upgrading to the latest DuckieTV.        
1. make a DuckieTV *Settings > Backup* as a precaution and then shutdown DuckieTV.
2. download the latest Standalone DuckieTV Nightly (This include Development tools that may help later on should we need them) from https://github.com/DuckieTV/Nightlies/releases
3. if you still have problems with *find-a-torrent* then let us know and we can dig deeper for you.
