### ISSUE TITLE
utorrent problems

### ISSUE THREAD

**Issue by bbrady5239** [SchizoDuckie/DuckieTV#1038]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
standalone
**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
v201802230130

**What is your Operating System (Windows, Mac, Linux, Android)**
windows 10
**Describe the problem you are having and steps to reproduce if available**
utorrent won't integrate when clicking button screen flashes but popup bubble never appears had worked fine for about a year and then randomly disconnected I have uninstalled and reinstalled duckietv and utorrent both several times utorrent is v3.5.3 build(44358) 

**Attach any DuckieTV statistics or Developer Console logs if available**
![untitled](https://user-images.githubusercontent.com/36815391/36641634-7d162ca8-19f8-11e8-99af-f034760a551c.png)

**Comment by garfield69** [comment]
Have you tried refreshing your authorisation token?     

To force uTorrent to issue a new authorisation token, first go to the DuckieTV *Settings > uTorrent Integration* side panel, and click on the *Clear uTorrent Authorisation* button.
![image](https://user-images.githubusercontent.com/6933240/33848940-fbf74112-df13-11e7-8e61-65bd87c5ac7b.png)

The popup is not produced by DuckieTV, it comes from the uTorrent program.     

Sometimes, the popup does not appear at the front of the screen, but is at the back behind the other windows.     
So after using the *connect to uTorrent* button on DuckieTV, you may need to click on the uTorrent icon on the active programs tray ( or minimise the DuckieTV app) to bring the uTorrent popup to the front.

**Comment by bbrady5239** [comment]
I have tried to refresh the authorisation token and it will never reconnect I have tried minimizing all programs the popup window never appears I have also tried uninstalling both programs and deleting all associated files and reinstalling the latest version and still nothing still no connection to utorrent

**Comment by garfield69** [comment]
OK. I just tried connecting to utorrent 3.5.3 (build 44358 32bit) on my win7 and I also cannot connect via the API anymore.      
So it looks like that interface has been broken, probably as a result of the new security push that utorrent have made with this release https://engineering.bittorrent.com/2018/02/22/httprpc-security-vulnerabilities-resolved-in-utorrent-bittorrent-and-utorrent-web/.     
However, if I enable the WEBUI interface then I can connect and use utorrent this way. :-)
Wiki for setting up the DuckieTV WEBUI integration should you need it can be found at https://github.com/SchizoDuckie/DuckieTV/wiki/Setting-up-uTorrent-Web-UI-with-DuckieTV

**Comment by bbrady5239** [comment]
That worked Thank you very much
