### ISSUE TITLE
The Bachelor Winter Games missing

### ISSUE THREAD

**Issue by Porphyry** [SchizoDuckie/DuckieTV#1040]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Chrome Extension

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Don't know

**What is your Operating System (Windows, Mac, Linux, Android)**
Mac High Sierra

**Describe the problem you are having and steps to reproduce if available**
The show database does not appear to include The Bachelor Winter Games. I checked to see if it is a TVDB issue and they do have an entry for it. 

**Attach any DuckieTV statistics or Developer Console logs if available**
N/A
...

**Comment by garfield69** [comment]
Huh?
![image](https://user-images.githubusercontent.com/6933240/36771702-eecd809c-1cb6-11e8-9472-f14ba4edc5d1.png)

**Comment by Js41637** [comment]
We use Trakt.tv which in turn uses the TVDb. DuckieTV does not have it's own database. I can also find it by searching. It's definitely on Trakt.tv https://trakt.tv/shows/the-bachelor-winter-games

**Comment by Porphyry** [comment]
Thank you. You are right and I was wrong!
