### ISSUE TITLE
A.P. Bio torrent search issue

### ISSUE THREAD

**Issue by bman00311** [SchizoDuckie/DuckieTV#1041]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...standlone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...Stable 1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
...windows 10

**Describe the problem you are having and steps to reproduce if available**
...torrents not auto downloading for the TV show A.P. Bio.  When doing a manual "find a torrent" it searches for AP Bio without the periods and returns no matches.  When I include the periods I am able to see matched torrents.  first image is without periods and second is when I add the periods.

Without periods
![duckietv issue](https://user-images.githubusercontent.com/36926620/36795642-9172444a-1c71-11e8-98da-dd9618f32580.JPG)

With periods
![duckietv issue2](https://user-images.githubusercontent.com/36926620/36795817-fa13697a-1c71-11e8-98ef-018660bd8a51.JPG)

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
I have added `A P BIO` to the sceneNameExceptions table which will resolve this.     
Your DuckieTV fetches the updated sceneNameExceptions table once a day, so within the next 24 hours your DuckieTV should start using this for its torrent searches.
