### ISSUE TITLE
Torrent Connection

### ISSUE THREAD

**Issue by Juhanna** [SchizoDuckie/DuckieTV#1042]
Hello, I'm new here, so i don't know if this should be post here or not.

**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
standlone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows

**Describe the problem you are having and steps to reproduce if available**
I can't make a connection between Duckie and Torrent. Installed a different one and still have the same problem, I now have qBitTorrent. It tries to connect but nothing happens. Always worked until a few days ago.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
#### µTorrent
µTorrent 3.5.3 broke DuckieTV µTorrent API integration.
Either install an earlier version, or switch to using DuckieTV µTorrent WEBUI integration. 
Read this [wiki](https://github.com/SchizoDuckie/DuckieTV/wiki/Setting-up-uTorrent-Web-UI-with-DuckieTV) if you want set up guidance.
#### qBitTorrent 
qBitTorrent  4.0.3 broke the DuckieTV qBt WEBUI integration.
Upgrade to 4.0.4
Read this [wiki](https://github.com/SchizoDuckie/DuckieTV/wiki/Setting-up-qBitTorrent-3.2-with-DuckieTV) if you want set up guidance.
#### Notes
qBt webui uses by default port 8080 which is also the port that µTorrent used to use. So either set up a different port or make sure that µTorrent is shutdown and recycle qBt and DTV to be sure that the port has been released properly and is free. A reboot is recommended.
