### ISSUE TITLE
DuckieTV won't connect to uTorrent

### ISSUE THREAD

**Issue by udt123** [SchizoDuckie/DuckieTV#1045]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...Browser Action

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...   v1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
...   Windows 10

**Describe the problem you are having and steps to reproduce if available**
...   DuckieTv won't connect to uTorrent

**Attach any DuckieTV statistics or Developer Console logs if available**
Statistics
Current Date and Time	Mon, 05 Mar 2018 22:27:45 GMT
DuckieTV - 'Browser Action' mode	1.1.5
UserAgent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
Platform, Vendor	Win32, Google Inc.
Screen (width x height)	1460 x 821
Default Search Engine	RarBG (Enabled)
Default Torrent Client	uTorrent (Enabled but Not Connected to Host)
Auto Download Service	(Enabled and Active)
Last checked TraktTV for DB updates on	Mon, 05 Mar 2018 13:01:19 GMT
User Preferences on Local Storage	
{
  "KickAssTorrents.mirror": "https://kat.cr",
  "ThePirateBay.mirror": "https://thepiratebay.gd",
  "application.language": "en_uk",
  "application.locale": "en_uk",
  "autodownload.minSeeders": 1,
  "autodownload.period": 3,
  "background-rotator.opacity": "0.65",
  "main.viewmode": "calendar",
  "calendar.mode": "date",
  "calendar.show-specials": true,
  "calendar.show-downloaded": true,
  "calendar.show-episode-numbers": true,
  "calendar.startSunday": true,
  "client.determinedlocale": "en_us",
  "download.ratings": false,
  "lastSync": -1,
  "library.smallposters": true,
  "library.seriesgrid": false,
  "kc.always": false,
  "qbittorrent.server": "http://localhost",
  "qbittorrent.port": 8080,
  "qbittorrent.use_auth": true,
  "qbittorrent.username": "admin",
  "qbittorrent.password": "*****",
  "qbittorrent32plus.server": "http://localhost",
  "qbittorrent32plus.port": 8080,
  "qbittorrent32plus.use_auth": true,
  "qbittorrent32plus.username": "admin",
  "qbittorrent32plus.password": "*****",
  "series.displaymode": "poster",
  "storage.sync": false,
  "sync.progress": true,
  "tixati.server": "http://localhost",
  "tixati.use_auth": true,
  "tixati.port": 8888,
  "tixati.username": "admin",
  "tixati.password": "*****",
  "topSites.enabled": false,
  "topSites.mode": "onhover",
  "torrenting.autodownload": true,
  "torrenting.autostop": true,
  "torrenting.autostop_all": true,
  "torrenting.client": "uTorrent",
  "torrenting.directory": true,
  "torrenting.enabled": true,
  "torrenting.progress": true,
  "torrenting.searchprovider": "RarBG",
  "torrenting.searchquality": "",
  "torrenting.streaming": false,
  "vuze.server": "http://localhost",
  "vuze.port": 9091,
  "vuze.use_auth": true,
  "vuze.username": "vuze",
  "vuze.password": "*****",
  "transmission.server": "http://localhost",
  "transmission.port": 9091,
  "transmission.use_auth": true,
  "transmission.username": "admin",
  "transmission.password": "*****",
  "trakttv.passwordHash": "*****",
  "trakttv.sync": false,
  "trakttv.username": null,
  "utorrentwebui.server": "http://localhost",
  "utorrentwebui.port": 8080,
  "utorrentwebui.username": "admin",
  "utorrentwebui.password": "*****",
  "utorrentwebui.use_auth": true,
  "deluge.server": "http://localhost",
  "deluge.port": 8112,
  "deluge.password": "*****",
  "deluge.use_auth": true,
  "subtitles.languages": [
    "eng"
  ],
  "autodownload.lastrun": 1520171927785,
  "transmission.path": "/transmission/rpc",
  "vuze.path": "/transmission/rpc",
  "autodownload.multiSE": {
    "ThePirateBay": true,
    "1337x": true,
    "IsoHunt": true,
    "KATcr": true,
    "Nyaa": true,
    "RarBG": true,
    "ShowRSS": true,
    "TorrentDownloads": true,
    "TorrentZ2": true,
    "Zooqle": true,
    "EzTV.ag": true,
    "Idope": true,
    "LimeTorrents": true,
    "SkyTorrents": true,
    "KickAss": true
  },
  "torrentDialog.2.enabled": true,
  "torrentDialog.2.activeSE": {
    "ThePirateBay": true,
    "1337x": true,
    "IsoHunt": true,
    "KATcr": true,
    "Nyaa": true,
    "RarBG": true,
    "ShowRSS": true,
    "TorrentDownloads": true,
    "TorrentZ2": true,
    "Zooqle": true,
    "EzTV.ag": true,
    "Idope": true,
    "LimeTorrents": true,
    "SkyTorrents": true,
    "KickAss": true
  },
  "torrentDialog.showAdvanced.enabled": true,
  "autodownload.delay": 20,
  "torrenting.global_size_max": null,
  "torrenting.launch_via_chromium": false,
  "torrenting.global_size_max_enabled": false,
  "series.not-watched-eps-btn": true,
  "torrentDialog.2.sortBy": "-seedersInt",
  "torrenting.min_seeders_enabled": false,
  "torrenting.min_seeders": 5
}
Other significant Local Storage keys	
{
  "1.1.4TorrentHashListCleanup": "Sun Feb 19 2017 10:55:52 GMT+0000 (GMT Standard Time)",
  "1.1.4cleanupOrphanedEpisodes": "Sun Feb 19 2017 10:55:50 GMT+0000 (GMT Standard Time)",
  "1.1.4cleanupOrphanedSeasons": "Sun Feb 19 2017 10:55:51 GMT+0000 (GMT Standard Time)",
  "1.1.4qBittorrentPre32": "Sun Feb 19 2017 10:55:46 GMT+0000 (GMT Standard Time)",
  "1.1.4refresh": "Sun Feb 19 2017 10:55:56 GMT+0000 (GMT Standard Time)",
  "1.1.4refreshTrendingCache": "Sun Feb 19 2017 10:55:46 GMT+0000 (GMT Standard Time)",
  "1.1.4updateDelugeAuth": "Sun Feb 19 2017 10:55:46 GMT+0000 (GMT Standard Time)",
  "1.1.4updateTransmissionPath": "Sun Feb 19 2017 10:55:46 GMT+0000 (GMT Standard Time)",
  "1.1.5FetchFirstXemAliasMap": "Fri Oct 06 2017 22:50:12 GMT+0100 (GMT Summer Time)",
  "1.1.5deleteSearchEngines": "Fri Oct 06 2017 22:50:13 GMT+0100 (GMT Summer Time)",
  "1.1.5fanartCleanup": "Fri Oct 06 2017 22:51:07 GMT+0100 (GMT Summer Time)",
  "1.1.5updateDelugeAuth": "Fri Oct 06 2017 22:50:13 GMT+0100 (GMT Summer Time)",
  "1.1.5updateTorrenting.min_seeders": "Fri Oct 06 2017 22:50:13 GMT+0100 (GMT Summer Time)",
  "1.1migration": "Mon Dec 12 2016 22:24:02 GMT+0000 (GMT Standard Time)",
  "autobackup.lastrun": "1520258327000",
  "database.version.Episodes": "14",
  "database.version.Fanart": "1",
  "database.version.Jackett": "2",
  "database.version.Seasons": "6",
  "database.version.Series": "16",
  "database.version.WatchList": "1",
  "database.version.WatchListObject": "1",
  "fanart.bootstrapped": "1",
  "install.notify": "1.1.4",
  "runtime.event": "{\"reason\":\"chrome_update\"}",
  "snr.lastFetched": "1520286849164",
  "torrenting.client": "uTorrent",
  "trackers.lastFetched": "1517752961838",
  "trakttv.lastupdated": "1520254879232",
  "trakttv.lastupdated.trending": "1520208042679",
  "trakttv.refresh_token": "ed5b36ff7da94e08a6418248a34b83422c93767fbaf5ff960a0f5661c4ec081c",
  "upgrade.notify": "1.1.5",
  "utorrent.port": "10000",
  "xem.lastFetched": "1520286849793"
}

**Comment by garfield69** [comment]
The BitTorrent team have just pushed out µTorrent Stable 3.5.3 with some new security fixes.
This has caused the DuckieTV µTorrent API integration to stop working.

However, you can still connect your µTorrent 3.5.3 with DuckieTV via the DuckieTV µTorrent WEBUI integration panel.
See this [wiki](https://github.com/SchizoDuckie/DuckieTV/wiki/Setting-up-uTorrent-Web-UI-with-DuckieTV) for set-up details.
