### ISSUE TITLE
The "Search for a download" feature on episodes of a show is acting weird.

### ISSUE THREAD

**Issue by Infallibleman** [SchizoDuckie/DuckieTV#1046]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone mac

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
DuckieTV v1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
Mac

**Describe the problem you are having and steps to reproduce if available**
The "Search for a download" feature on episodes of a show is acting weird.

 **Please see attached screenshots**

![2018-03-06_06-53-47](https://user-images.githubusercontent.com/36009107/37033455-b4864a32-210b-11e8-9e26-26cd568fe11a.png)

![2018-03-06_07-00-39](https://user-images.githubusercontent.com/36009107/37033905-1cf4b38c-210d-11e8-8c32-ef22b6cbd172.png)

![2018-03-06_07-09-12](https://user-images.githubusercontent.com/36009107/37034208-2695cfec-210e-11e8-8f16-098490f6336d.png)

**Attach any DuckieTV statistics or Developer Console logs if available**

**Comment by garfield69** [comment]
it looks like your series *custom search string* has been loaded with *madam.secretary.s03* at some point.
### access the *series details* panel and then click on the series *settings* for madam secretary
![image](https://user-images.githubusercontent.com/6933240/37050585-1e1acea0-21d9-11e8-9b54-f20bc9fe027d.png)
### OR from any of the *episode details* panels
![image](https://user-images.githubusercontent.com/6933240/37050538-fac212c4-21d8-11e8-9f78-32e8a29b2071.png)
### and clear the *custom search string* field
![image](https://user-images.githubusercontent.com/6933240/37050427-bbdbc3ac-21d8-11e8-921e-2061d402253e.png)

**Comment by Infallibleman** [comment]
Hi garfield69, Thank you, that was it.!! My issue is resolved :)
