### ISSUE TITLE
µTorrent Stable(3.5.3 build 44358) cant connect 

### ISSUE THREAD

**Issue by kocka68785602** [SchizoDuckie/DuckieTV#1048]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...browser action
**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...latest 

**What is your Operating System (Windows, Mac, Linux, Android)**
...win 10 

**Describe the problem you are having and steps to reproduce if available**
...cant connect to torrent client

**Attach any DuckieTV statistics or Developer Console logs if available**
...

side not i downloaded utorrent 2.2.1 and that cant connect i can go to 3.5.2 cuz tha is blacklisted on one of my favorit tracker pls help 

Thanks

**Comment by garfield69** [comment]
The BitTorrent team have just pushed out µTorrent Stable 3.5.3 with some new security fixes.
This has caused the DuckieTV µTorrent API integration to stop working.

However, you can still connect your µTorrent 3.5.3 with DuckieTV via the DuckieTV µTorrent WEBUI integration panel.
See this [wiki](https://github.com/SchizoDuckie/DuckieTV/wiki/Setting-up-uTorrent-Web-UI-with-DuckieTV) for set-up details.

**Comment by kocka68785602** [comment]
but that is where the bug or security flaw  is as far as i know

**Comment by garfield69** [comment]
There were two ways to connect to uTorrent with DuckieTV. 
![image](https://user-images.githubusercontent.com/6933240/37077401-be257ca4-223f-11e8-8cf1-1d3cd45e72ba.png)
The method via the uTorrent API (marked as 3 in the pic above) was the default way to connect to uTorrent, but starting with 3.5.3 that is now broken.
But you can still use the uTorrent WEBUI, (marked as 4 in the pic above).

are you telling me you are having problems setting up and connecting to uTorrent 3.5.3 via the WEBUI?

**Comment by kocka68785602** [comment]
no im saying that the security flaw is in the web UI so using it is no recommended

**Comment by garfield69** [comment]
post me a link to where ever you got this information please.

**Comment by garfield69** [comment]
info on uTorrent 3.5.3 security fixes https://forum.utorrent.com/announcement/2-security-vulnerabilities-fixed-in-the-latest-utorrent-bittorrent-and-utorrent-web/

**Comment by garfield69** [comment]
more pertinent details about the fixes for WEBUI security in 3.5.3
https://engineering.bittorrent.com/2018/02/22/httprpc-security-vulnerabilities-resolved-in-utorrent-bittorrent-and-utorrent-web/

**Comment by kocka68785602** [comment]
thank you for your help i though its not fixed
