### ISSUE TITLE
Why does duckie tv randomly keep losing Show artwork

### ISSUE THREAD

**Issue by Infallibleman** [SchizoDuckie/DuckieTV#1053]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone mac

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
DuckieTV v1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
Mac

**Describe the problem you are having and steps to reproduce if available**
Why does duckie tv randomly keep losing Show artwork

**Please see attached screenshots**

<img width="400" alt="missing artwork" src="https://user-images.githubusercontent.com/36009107/37257439-6b691002-2537-11e8-8cfa-c5a3c3a06424.png">

**Comment by garfield69** [comment]
DuckieTV gets it art from fanart.tv, a free site supported by volunteers. It has pics for many series, but generally only for the most popular series, and for new series the art can take time to be uploaded by volunteers.

DuckieTV stores the url links to art in its DB, but the pictures themselves are cached only locally in temp space that expires and self cleans just like the chrome browser does for all its web pictures when you are browsing any html page. This is managed by the run time environment and not by DuckieTV directly.

But the fanart servers have been responding poorly for some time now, probably getting overloaded by DDOS attacks or over-subscription or something.

So when DuckieTV posts a http request to fetch a pic that is not in the cache, it is not unusual for the request to fail, hence the white Duckie filler.
