### ISSUE TITLE
Autodownload subtitle feature?

### ISSUE THREAD

**Issue by arbel** [SchizoDuckie/DuckieTV#1055]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
stable 1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
windows

**Describe the problem you are having and steps to reproduce if available**
would be great if I could auto download subtitles..or am I missing something and its already avaialble

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
There are no plans to add an auto-download option for subtitles. 
It's a lot of work and there are currently no resources available to research, code and test such a feature.

Basically, no one in the team is contributing significant code projects anymore. I personally only have time to do bug fixes and responses to problem solving. Sorry.
