### ISSUE TITLE
Unable to Load Torrent to Remote Torrent Client.

### ISSUE THREAD

**Issue by arjunmaan2011** [SchizoDuckie/DuckieTV#1056]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
... Chrome Extension (Browser Action)/Standlone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
... Stable

**What is your Operating System (Windows, Mac, Linux, Android)**
... Windows

**Describe the problem you are having and steps to reproduce if available**
... Unable to load Torrent to Remote uTorrent WebUI like From Local PC to example.com:8080 Here.It Always Open my Local Client.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
check that the *torrent parameters* option is disabled. 
you'll find it on the  *settings > torrent* side panel, and scrolling to the bottom.
If this setting is enabled, it will bypass your webui and pass the torrent request via the Chromium/OS interface, which is always local. So disable it.
let me know what you find.
