### ISSUE TITLE
uTorrent keeps requiring authorisation to be cleared and re-accepted

### ISSUE THREAD

**Issue by Eds1989** [SchizoDuckie/DuckieTV#1057]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone/Chome Extension (New Tab)

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Nightly 20180311/Stable latest

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows Server 2016

**Describe the problem you are having and steps to reproduce if available**
After authorising uTorrent access on the same machine, several days later, torrents are "added" but do not appear in uTorrent. I have to clear authorisation, at which point uTorrent immediately prompts to approve access. This happens over and over every few days or so.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
Sorry but there is nothing we can do about this.
It has something to do with the chromium cache. So if the Chrome Browser has an update/upgrade and clears the cache, or if you manually clear the cache via Chrome Browser settings, or run the Chrome Browser  in incognito mode (which clears the cache when the Chrome Browser is exited), or if you run any kind of cache clearing tool (CCleaner for instance) then the uTorrent token gets wiped and uTorrent requires a new one before allowing a connection.

An alternate to using the DuckieTV uTorrent API, is to use the DuckieTV uTorrent WEBUI instead.
This is an alternate way to access uTorrent from DuckieTV. See this wiki for details: https://github.com/SchizoDuckie/DuckieTV/wiki/Setting-up-uTorrent-Web-UI-with-DuckieTV

**Comment by Eds1989** [comment]
Is this true for the standalone app too? Does it use Chromium for rendering the app or something like that?

Might just switch to webui as I have that set up already.

**Comment by garfield69** [comment]
Yes. DuckieTV is a chromium extension  written in AngularJS.
The standalone is the run time environment NWJS which uses the chromium engine to execute the same DuckieTV code.
Use the WEBUI. ;-)

**Comment by Eds1989** [comment]
Will do, ta 👍
