### ISSUE TITLE
Unable to connect it to my torrent client for over a month, I have even installed windows again...

### ISSUE THREAD

**Issue by ZerkerEOD** [SchizoDuckie/DuckieTV#1059]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...V201803190130 Desktop application nightly build

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
....V201803190130 Desktop application nightly build

**What is your Operating System (Windows, Mac, Linux, Android)**
...Windows 10

**Describe the problem you are having and steps to reproduce if available**
...It will not connect to my utorrent application. I have updated, downgraded. Deleted my antivirus. I have done everything I can think of to get this to work. Reinstalled both also.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
Duplicate of #1048
The BitTorrent team pushed out µTorrent Stable 3.5.3 with some new security fixes.
This has caused the DuckieTV µTorrent API integration to stop working.

However, you can still connect your µTorrent 3.5.3 with DuckieTV via the DuckieTV µTorrent WEBUI integration panel.
See this [wiki](https://github.com/SchizoDuckie/DuckieTV/wiki/Setting-up-uTorrent-Web-UI-with-DuckieTV) for set-up details.
