### ISSUE TITLE
DuckieTv keeps opening a different Torrent client even though I use Deluge

### ISSUE THREAD

**Issue by dbeczuk** [SchizoDuckie/DuckieTV#1060]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 10 Professional

**Describe the problem you are having and steps to reproduce if available**
I had uTorrent installed and running with DuckieTv but because the auto downloads will work 30% of the time I decided to replace the torrent client with Deluge. It worked the first time I tried it and magnet links were added to Deluge. However the second day when the auto download fired up DuckieTv keeps opening the uTorrent client instead of adding them to Deluge even though Deluge is configured as a client inside DuckieTv.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by dbeczuk** [comment]
I think I solved it and its not an Issue with DuckieTv its with Magnet link association.

I used the following registry script to fix the issue.

Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Classes\magnet]
@="URL:MAGNET URI"
"URL Protocol"=""

[HKEY_CURRENT_USER\Software\Classes\magnet\DefaultIcon]
@="C:\\Program Files (x86)\\Deluge\\deluge.exe"

[HKEY_CURRENT_USER\Software\Classes\magnet\shell]

[HKEY_CURRENT_USER\Software\Classes\magnet\shell\open]

[HKEY_CURRENT_USER\Software\Classes\magnet\shell\open\command]
@="C:\\Program Files (x86)\\Deluge\\deluge.exe \"%1\""

**Comment by garfield69** [comment]
Also check that the DuckieTV *torrent parameters* option is *disabled*.
You'll find it on the **Settings > Torrent** side panel, and scrolling to the bottom.
If this setting is *enabled*, it will bypass your webui client and pass the torrent request via the Chromium/OS interface. So disable it to be sure that DuckieTV passes the torrents through its deluge webui client interface.
Let me know what you find.
