### ISSUE TITLE
"Close Series Details" "x" button does nothing

### ISSUE THREAD

**Issue by CollinChaffin** [SchizoDuckie/DuckieTV#1061]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone
...
**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Windows desktop nightly v201803200130
...
**What is your Operating System (Windows, Mac, Linux, Android)**
Windows
...

**Describe the problem you are having and steps to reproduce if available**
1.  Open any show's "series detail" pane.
2.  Click the rightmost "x" button that shows hover text as "close series details"
3.  Nothing happens and pane does not close properly like all others do.  Only option is to close the parent pane.
...

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
Thanks for reporting.
fix should be available starting from the next nightly due to be published in about 6 hours.

**Comment by CollinChaffin** [comment]
Awesome, thanks!  Certainly was not anything critical...off topic are there any plans on the roadmap to ever consider implementing the very same awesome Duckie front-end to the very same (or similar) trakt backend API for movies?  I ask because it would sure be awesome to put movies that most do have release dates but more importantly all my movies be tracked and tagged collected/watched in trakt and do it all in my favorite interface!

**Comment by garfield69** [comment]
There are no plans to expand into movies. Too big a project and no resources available.
