### ISSUE TITLE
You denied the uTorrent/BitTorrent Client request.

### ISSUE THREAD

**Issue by ovaar** [SchizoDuckie/DuckieTV#1064]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone / Chrome Extension (Browser Action)

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows

**Describe the problem you are having and steps to reproduce if available**
I'm trying to connect to uTorrent 3.1.4 (build 31227) and getting a Popup message "DuckieTV has requested access to uTorrent" as expected. But than when I click YES, I receive the following message

"You denied the uTorrent/BitTorrent Client request.
Do you wish to prevent any connection attempt?"

I'm guessing this is some setting that is related to a browser, but failed to find it.

**Attach any DuckieTV statistics or Developer Console logs if available**
```
PAIR_DENIED
deps.js:2353 
(anonymous) @ deps.js:2353
(anonymous) @ deps.js:2326
(anonymous) @ deps.js:2367
$eval @ deps.js:2381
$digest @ deps.js:2378
$apply @ deps.js:2381
l @ deps.js:2333
completeRequest @ app.js:401
(anonymous) @ app.js:305
callback @ app.js:435
```

**Comment by garfield69** [comment]
I suggest you try exiting uTorrent and closing the duckietv chrome browser tab, and exiting the chrome browser.
Then start uTorrent, start the browser, start duckietv.
Then make the uTorrent the active window so it is at the front.
wait for the uTorrent popup to appear, which should happen since DuckieTV will try to auto-connect soon after startup.

Sometimes the popup can be buried behind the current window, and if it is not replied to in a timely manner, uTorrent can give up, making subsequent connection attempts an out-of-sequence game of click-yes-too-late loop.

if you cant solve it this way, then I recommend switching from using the duckietv uTorrent API to using the DuckieTV uTorrent WEBUI, which is another way of connecting duckietv with uTorrent.
See this wiki for set-up details: https://github.com/SchizoDuckie/DuckieTV/wiki/Setting-up-uTorrent-Web-UI-with-DuckieTV

Let me know how you go.

**Comment by ovaar** [comment]
@garfield69 The uTorrent web UI works.

About the error: It seems that it is not only DuckyTV that is affected. Also the PimpMyuTorrent website that requests utorrent permission seems te be affected in the same way.

**Comment by garfield69** [comment]
sounds like the chrome browser has recorded a previous deny attempt.
the question is where that denial record is kept...
Perhaps clearing the browser cache ( *settings > advanced > clear browsing data* ) or examining the browser *settings > advanced > content settings >
cookies,notifications,javascript,popups* for any disable/deny entries for uTorrent ?
Other than that I am out of ideas for now.

**Comment by ovaar** [comment]
Where thinking in the same right direction here I guess.
I've cleared the browsing data, and checked all content settings without any success.

**Comment by ovaar** [comment]
If you inspect the sources of PimpMyuTorrent, the popup message comes from duckietorrent.torrent.js line 308.

```js
methods.Scan().then(function() {
    methods.Pair().then(function() {
        methods.connect(localStorage.getItem('utorrent.token')).then(function(result) {
            if (!self.isPolling) {
                self.isPolling = true;
                methods.Update();
            }
            self.isConnecting = false;
            self.connectPromise.resolve(methods.getRemote());
        });
    }, function(error) {
        if (error == "PAIR_DENIED" && confirm("You denied the uTorrent/BitTorrent Client request. \r\nDo you wish to prevent any future connection attempt?")) {
            localStorage.setItem('utorrent.preventconnecting', true);
        }
    });
});
```

**Comment by garfield69** [comment]
I just tried this out on my own browser, by replying *no* to the utorrent *accept popup* the first time it came up. then i closed and started the duckietv tab again.
when the browser produced the *prevent attempt popup*  and I answered *cancel*. then when utorent generated the *accept popup* and answered *yes* and connection was established.
So I can get it to work.

**Comment by garfield69** [comment]
you can delete the localstorage record.
from the pipmytorrent webpage tab,  use the **F12** key to open the *development tools* page.
click on the **application** tab, navigate to the **storage** > **local storage** and expand the list by clicking on the little arrow.
then right click on the *http://schizoduckie.github.io and click the **clear** submenu to blow away any records.
code the tabs and try again.
![image](https://user-images.githubusercontent.com/6933240/37879830-314c7760-30db-11e8-8223-8d34fc25b691.png)

**Comment by ovaar** [comment]
You're right about that. Only, the localstorage item is set when you confirm the alert. It is used to prevent pairing at startup with uTorrent.

**Comment by garfield69** [comment]
Looking at the DuckieTV uTorrent API wiki (https://github.com/SchizoDuckie/DuckieTV/wiki/Setting-up-uTorrent-API-with-DuckieTV) I see that the API client that both DuckieTV and  pimpmytorrent use, supports only connecting from uTorrent version 3.3.0 through 3.5.1
so I suspect you will not be able to get pimpytorrent to work with 3.1.4.

**Comment by ovaar** [comment]
My bad, I made a typo. The uTorrent version is 3.4.1.

This does not solve my problem yet.

**Comment by garfield69** [comment]
which problem? I thought you were using WEBUI now to connect DuckieTV to uTorrent.
or are you still trying to get pimpmytorrent working?
in which case you can just set the flags yourself in the uTorrent preferences.
```
            'gui.pro_installed': true,
            'offers.left_rail_offer_enabled': false,
            'offers.sponsored_torrent_offer_enabled': false,
            'show_bundles_tab': false,
            'offers.featured_content_badge_enabled': false,
            'gui.show_plus_upsell_nodes': false,
            'gui.show_gate_notify': false,
            'gui.show_plus_upsell': false,
            'gui.show_plus_av_upsell': false,
            'offers.content_offer_autoexec': false,
            'offers.featured_content_notifications_enabled': false,
            'offers.featured_content_rss_enabled': false,
            'offers.upgrade_panel': false,
            'offers.upgrade_toolbar': false,
            'gui.show_plus_conv_upsell': false,
            'offers.content_offer_url': '',
            'bt.enable_pulse': false,
            'distributed_share.enable': false,
            'gui.show_notorrents_node': false,
            'sponsored_torrent_offer_enabled': false,
            'left_rail_offer': false
```
![image](https://user-images.githubusercontent.com/6933240/37893971-12c52ba8-3139-11e8-94dd-c0e4b0cb7136.png)
