### ISSUE TITLE
New series start date moved, now calendar shows first episodes on 2 dates

### ISSUE THREAD

**Issue by geekman** [SchizoDuckie/DuckieTV#1065]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Browser Action

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows

**Describe the problem you are having and steps to reproduce if available**
New series start date moved, now calendar shows first episode on 2 dates, one is earlier by one week of the actual start date.

- I added a show when I saw news about it some time ago (so that I would remember)
- The series first episode appeared on the calendar as March 14
- Just 2 weeks ago, two first episodes appeared on the calendar, one for 14th (original entry) and one for 21st. Actual series start date is 21st.

DuckieTV should be able to cope when start dates of shows move (either later or earlier).
Incorrect first episode entries should be removed from the calendar.

**Comment by garfield69** [comment]
usually this is the case.
unless there are actually two separate episode entries in the series provided by trakt.tv (our source for data).
if you examine the episodes list from the series season panel are there the corresponding entries for the ones that show in the calendar?
Does exiting DuckieTV and starting a fresh one make a difference?
what about using the series *refresh* button... does it fix things?
if not, please specify which series you are referring to, so I can take a closer look.

**Comment by geekman** [comment]
It's the Browser Action, so I'm not sure how to "exit DuckieTV", but restarting Chrome does not help.

I have just tried hitting the Series Refresh button, but both first episodes are still on the calendar. There is a message in the console that says `Not performing TraktTV update check. Already done within the last 3 hour(s)`, so I'm not sure if the Refresh button overrides that.

On the episodes list, there is only one S01E01 and the air date is 21st Mar. The series in question is [Krypton](https://www.trakt.tv/shows/119064).

Let me know what other details I can provide you with from my installation for debugging.

**Comment by geekman** [comment]
Oh wait... the "first" episode I was talking about is actually S**00**E01. It is some "making of" episode.

So I don't think there is a bug here. Sorry.

**Comment by garfield69** [comment]
:laughing:
