### ISSUE TITLE
UTorrent Integration 

### ISSUE THREAD

**Issue by Paul7559** [SchizoDuckie/DuckieTV#1067]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...
Standlone
**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
v1.1.5
**What is your Operating System (Windows, Mac, Linux, Android)**
...
Windows 10 64bit
**Describe the problem you are having and steps to reproduce if available**
...
When I click in the uTorrent Integration button, nothing happens but a flicker on my screen. Normally it would pop up on my uTorrent screen asking for permission to connect, but now I get nothing! I can still download with uTorrent, but not automatically when I start DuckieTV.  
**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
Duplicate of #1048
The BitTorrent team pushed out µTorrent Stable 3.5.3 with some new security fixes.
This has caused the DuckieTV µTorrent API integration to stop working.

However, you can still connect your µTorrent 3.5.3 with DuckieTV via the DuckieTV µTorrent WEBUI integration panel.
See this [wiki](https://github.com/SchizoDuckie/DuckieTV/wiki/Setting-up-uTorrent-Web-UI-with-DuckieTV) for set-up details.
