### ISSUE TITLE
Auto Downloading 

### ISSUE THREAD

**Issue by wuguba** [SchizoDuckie/DuckieTV#1073]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...
Standalone 
**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...
1.1.5
**What is your Operating System (Windows, Mac, Linux, Android)**
...
Windows
**Describe the problem you are having and steps to reproduce if available**
...I have tried to setup auto download with both utorrent and vuze. in both cases it says they are connected but nothing automatically downloads. 

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
have you read the following wiki https://github.com/SchizoDuckie/DuckieTV/wiki/Auto-Download-FAQs ?

**Comment by wuguba** [comment]
Hi, Yes that is the guide i followed to set it up.

**Comment by garfield69** [comment]
So when you look at the AutoDownload Service Monitor what do you see? provide a screen-capture so I can take a look.

**Comment by wuguba** [comment]
![duckie](https://user-images.githubusercontent.com/37994878/38184699-d022d06c-368c-11e8-89b0-b11ff440bc02.PNG)

**Comment by garfield69** [comment]
Hmm. If the ADSM is stuck in this mode, then it is likely that there is a problem someplace. The most common cause is that while DuckieTV may be connected with your torrent client, it may not be authorised. We need to check the console log for errors.
However, the Standalone 1.1.5 does not come with the *Development Tools* package included, so to progress this further you are going to need to install the latest standalone Nightly.
So,
1. first as a precaution, make a DuckieTV backup using the *Settings > Backup > createa a Database Backup*, just in case. 
2. then install the latest Nightly from https://github.com/DuckieTV/Nightlies/releases
3. once it is running then check the ADSM to see if it is still displaying what you showed me previously 
4. and if this is the case then press **F12** to open the *Development Tools* page
5. click on the **console** tab to view the log
6. click on the **console settings** (the cog icon) and set *show timestamps*
![image](https://user-images.githubusercontent.com/6933240/37791109-374bad7c-2e6d-11e8-83a7-7bf3e48a78ef.png)
7. click on the cog to close the settings
8. scroll to the top of the log and on the left on a blank spot *right click* to open the submenu and select **save as...**
![image](https://user-images.githubusercontent.com/6933240/37791249-99b99ffa-2e6d-11e8-8fec-0d0c046eb65e.png)
9. once you have saved it, *drag drop* the log file here so I can take a look.

**Comment by wuguba** [comment]
removed for security.

**Comment by garfield69** [comment]
Urg.
It looks like you are having problems accessing TPB.

`16:05:29.162 thepiratebay.org/search/Brooklyn%20Nine%20Nine%20s05e14%201080p/0/99/0 Failed to load resource: net::ERR_CERT_COMMON_NAME_INVALID
`
this probably means that DuckieTV ADS will not be able to find any torrents when searching with TPB.

lets test that you can access TPB from your Chrome Browser:

at the browser address bar paste the following
`https://thepiratebay.org/search/Brooklyn%20Nine%20Nine%20s05e14%201080p/0/99/0` and press enter
2. what do you get? Provide a screen capture if that is easier than a description.

**Comment by wuguba** [comment]
![tpb](https://user-images.githubusercontent.com/37994878/38186177-f551caa2-3694-11e8-8d4f-748fce093bc0.PNG)
Yes that seems to be the issue

**Comment by garfield69** [comment]
Ahh. so your ISP is blocking your access to TPB.
- Probably the simplest way to fix this is to change your DNS from the one that your ISP provides, to another such as from Google, see https://developers.google.com/speed/public-dns/ for details.
Let me know how you go.

**Comment by garfield69** [comment]
better dns info from google directly: https://developers.google.com/speed/public-dns/
