### ISSUE TITLE
Duckie TV Sets "Finished" flag in uTorrent

### ISSUE THREAD

**Issue by ASHinnovations** [SchizoDuckie/DuckieTV#1074]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Stable 1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 10 Pro (1709 16299.309)

**Describe the problem you are having and steps to reproduce if available**
While any version of uTorrent is up (I use 3.2.2 and 3.5.3), run Duckie TV with uTorrent WebUI Integration active. 
For some reason, Duckie TV is not only 'reporting' torrents (not just TV episodes, but ALL torrents) as finished, but it is somehow actively setting the status of each torrent to "Finished". 
The result is none of my torrents will continue to seed after the download is finished. 
Restarting the torrents will very briefly start them, but go quickly back to "Finished" and stop. 
The only way I've found to get the torrents to restart and continue seeding is to shut down Duckie TV completely. 
If I start the application, it will immediately intercede and reset all my torrents to "Finished" again.
I can live with this situation, but it is a pain to have to run DuckieTV every time I want to download TV shows and then shut it down when I am finished for a day's worth of episodes.
I really like DuckieTV and will continue to use it, but it seems like this could be a relatively simple fix.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
This is the **auto-stop** feature in action. 
to turn it off, navigate DuckieTV to *Settings > torrent*, scroll down to the *torrent auto-stop* section, and set it to disable.
![image](https://user-images.githubusercontent.com/6933240/38596339-089ce6de-3da5-11e8-82c7-e53eb0146063.png)

**Comment by ASHinnovations** [comment]
OK. Thanks! Sounds like a weird "feature" does this really serve a purpose to stop all torrents even if they are not DuckieTV originated?

**Comment by garfield69** [comment]
>OK. Thanks! Sounds like a weird "feature" does this really serve a purpose to stop all torrents even if they are not DuckieTV originated?      

there are two auto-stop settings, the first just stops torrents started from DuckieTV, and the second stops all torrents.
However a bug in 1.1.5 caused stop-all to be actioned even when disabled, this was fixed in 743b044da7e079283c373abee84c6a8a5e1b9ef3 and is available from any of the DuckieTV Nightly's at https://github.com/DuckieTV/Nightlies/releases

The options are intended for those that do not want to seed and for those that want to make their episodes available to their media-manager as soon as its downloaded.
