### ISSUE TITLE
Duckie Tv keeps coming unresponsive in debian 9

### ISSUE THREAD

**Issue by b660av** [SchizoDuckie/DuckieTV#1075]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**

stand alone 1.1.5

** side note isthe chrome extension i'st own version and you do not need the stand alone app, or does it just access the stand alone app so you need that installed as well?

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...
Stable
**What is your Operating System (Windows, Mac, Linux, Android)**
debian 9

**Describe the problem you are having and steps to reproduce if available**
I start to use it and then it locks up and becomes un responsive, rest of machine is fine, I have to reboot, then it happens again a few minutes of use and it locks up.

**Attach any DuckieTV statistics or Developer Console logs if available**
How do I get the logs?

Also If I do reboot and clos the window

**Comment by garfield69** [comment]
DuckieTV is written in AngularJS as a chrome browser extension. The standalone app is the same code encapsulated in the NWJS run time environment, which uses the chromium engine to support running the chrome extension JS.

>How do I get the logs?

The *Stable* standalone does not come with the development package included.
So best to:
1. as a precaution, make a backup using the DuckieTV *Settings > Backup > create a database backup*, just in case.
2. install the latest DuckieTV Nightly from https://github.com/DuckieTV/Nightlies/releases, which includes the *Development Tools* package. (This also has the latest fixes, plus the latest NWJS run time environment).
3. Start the nightly, press **F12** to open the *Development Tools* page, and click on the **console** tab to view the log.

>Also If I do reboot and clos the window

Ah, then the logs are lost as the chrome extension devtools do not save the logs to a file. 

>side note is the chrome extension i'st own version and you do not need the stand alone app, or does it just access the stand alone app so you need that installed as well?

The standalone and the browser extension are independent, using separate data spaces and environments.
Generally, install one or the other ;-)

**Comment by b660av** [comment]
Ok, Thanks, so lets start simple.  I am running vmware esxi.

I built a new debian9 virtual machine, then I installed chrome and then I installed the duckietv browser action mode.

When I click it, the window starts to load then crashes and disappears. I have to re enable the extension.


Any ideas?

**Comment by garfield69** [comment]
>I built a new debian9 virtual machine, then I installed chrome and then I installed the duckietv browser action mode.
>When I click it, the window starts to load then crashes and disappears. I have to re enable the extension.

Urg. 
never come across something like that before.
Alternative: 
1. download and extract https://github.com/DuckieTV/Nightlies/releases/download/nightly-201804150130/DuckieTV-201804150130-chrome-browseraction.zip to your favourite working folder.
2. then open the chrome extensions page `chrome://extensions/`,
3.  tick the *developer mode* switch, 
4. click on the *load unpacked* button and point it to your nightly folder
5. start it up and see if that runs or not

[edit] PS you may want to disable the other duckie extension, so you don't confuse the start icons

**Comment by SloS13** [comment]
Running Ubuntu 16 on Virtualbox (Win10 host).  Sounds like I'm having the same issue.

**Comment by b660av** [comment]
This nightly build is working!!!!!!!

Thanks
