### ISSUE TITLE
Future episodes downloaded via DuckieTV are later changed to not downloaded

### ISSUE THREAD

**Issue by marcelpaulo** [SchizoDuckie/DuckieTV#1076]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Browser Action

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Cloned git repository, latest commit b0ada73ce0f19aea45736dab460acfcb4587df3c

**What is your Operating System (Windows, Mac, Linux, Android)**
Linux (Xubuntu 17.10)

**Describe the problem you are having and steps to reproduce if available**
If I download episodes yet to be aired using DuckieTV, they're later marked as not downloaded. It's easier to explain this error through a concrete example:

- Series *The City & The City* has right now torrents available for all its 4 episodes, even though S01E03 through S01E04 are scheduled to be aired on 04/20/2018 and 04/27/2018, respectively (today is 04/16/2018).
- I downloaded these future episodes using DuckieTV on the 04/14/2018, and DuckieTV marked them both as downloaded.
- Some moments ago today, after the db was updated, those 2 episodes were shown as not downloaded, and I had to manually mark them again as downloaded.

Initially, I suspected that DuckieTV changed the episodes to not downloaded because I had deleted the torrents, so I set up a test with a future episode of *The Terror*: started to download it with DuckieTV, waited for it to be marked as downloaded, deleted the torrent, and checked whether DuckieTV changed it to not downloaded. However, DuckieTV didn't change it to not downloaded.

Unfortunately, I can't reproduce the issue because I have no series with downloadable episodes yet to be aired. The only series which fell in this category were *The City & The City* and *The Terror*, but I have already manually marked all future episodes as downloaded. Another difficulty to reproduce this issue is the timing: when DuckieTV marks the downloaded future episodes as not downloaded. In the case of those 2 _The City & The City_ future episodes, DuckieTV took 2 days to change them to not downloaded, but then again, I don't keep DuckieTV running all the time, I only open the tab when I need to download something or mark something as watched. Roughly, this would be the sequence to reproduce the error:

1. Download an episode which has not yet been aired, scheduled to be aired on a future date. Wait for DuckieTV to mark it as downloaded.
1. Observe this episode before its air date is reached: at some point, DuckieTV will change its status to not downloaded.

As I could not determine when DuckieTV would change the episode status to not downloaded, I could not get an error tracking trace or developer console logs.

Let me know what else could I provide to aid in debugging this issue.

**Attach any DuckieTV statistics or Developer Console logs if available**

**Comment by marcelpaulo** [comment]
I know what I'll do to try to pinpoint this issue:

1. Enable the opt-in error tracking
1. Mark the S01E04 episode of *The City & The City* as not downloaded
1. Put that episode to download again, using DuckieTV
1. Wait for DuckieTV to mark it as downloaded
1. Leave the tab opened (the standalone version used practically 100% of a CPU core even without any activity, but the Browser Action version doesn't) until DuckieTV changes the episode to not downloaded
1. Post the console log

Here's the tracking id:

![image](https://user-images.githubusercontent.com/10074769/38844151-9f2b708a-41c8-11e8-96b5-bf2ab944b3c7.png)

I'll post the console log as soon as this test is completed. I've started it just now.

**Comment by garfield69** [comment]
Strange.
I also have *the city and the city*.
On Sat 7th April, I used the *click here if the episode has leaked online* link for episodes 2, 3 and 4 (in order to make available the *mark as* buttons, and the *torrent search* for those episode's respective details panels, and then proceeded to download all four episodes of that series.
DuckieTV dutifully marked all episodes as downloaded when the torrents were completed, and my video management system has subsequently moved the videos to my player's drive for later playback.
I then removed the torrents from my client.
As a point of difference to your report, I have yet to see any change on the *downloaded* status of all four episodes of that series on my DuckieTV.

things to note: The only time that the DB data for series and episodes changes is when: 
- updates from Trakt.tv override existing information
- the user manually sets the mark as downloaded or mark as watched states

I have come across situations where Trakt.TV update the trakt.tv ID for a series, making all associated episodes orphans (from a DB series-episodes connection tree point of view), such that, subsequently, when DuckieTV fetched updates from Trakt.TV the following day, it imports all the episodes for the series afresh and deletes the orphans.
This also happens if an episode's trakt.TV id changes. Then that episode is refreshed under a new id, and the old one is deleted as an orphan that is not attached to a series.
These are the only two events that should cause the mark-as-downloaded flag to be reset, as new records were added and the old ones were deleted.

I'll poke around and revew the code to see if there are any undiscovered logic bombs.

**Comment by marcelpaulo** [comment]
Hey, thanks for the detailed explanation, @garfield69 !

Really weird issue. I hesitated before reporting. If the _downloaded_ status changed for me, because of any _trakt.tv_ updates, it should have changed for you too, but it didn't, so it might be something else.

S01E04 has finished downloading, and DuckieTV marked it as downloaded, so fingers crossed that it changes it to not downloaded, and the error/console logs may shed some light on what happened.

**Comment by marcelpaulo** [comment]
I changed the `Track.TV Update period` to **1h**, perhaps to increase the chance of an earlier db update.

**Comment by garfield69** [comment]
just as a cross reference, which of the two *city* series that show up in the *Add a Show* panel do you have with the tick mark?
![image](https://user-images.githubusercontent.com/6933240/38845142-804bc200-424a-11e8-87af-564bbbf7f3da.png)
or
![image](https://user-images.githubusercontent.com/6933240/38845160-9118be9e-424a-11e8-8d0b-f0dcb5b270c7.png)

**Comment by marcelpaulo** [comment]
The same as you:

![image](https://user-images.githubusercontent.com/10074769/38845341-6dfe311e-41cd-11e8-9e6e-1cba0bdc179a.png)

**Comment by garfield69** [comment]
Oh, just remembered a point about the console log:
if you are going to leave duckietv active overnight, then just after midnight DuckieTV does a reset in order to adjust for the new day and reload the calendar etc. 
The console log will also get cleared at this time, *unless* you activate the *Preserve log* switch.
so, on the console, 
1. click on the cog, 
2. set the *preserve log* and 
3. click the cog again to close the settings.
![image](https://user-images.githubusercontent.com/6933240/38847385-67b5b8f8-4255-11e8-9689-19d843749e38.png)
Note: despite the *preserve log* settings, if you shutdown DuckieTV then the logs are lost since they are not stored on disk.

**Comment by marcelpaulo** [comment]
Oh, it's already past midnight here, so the console log will be gone :-(

I'll start over then, with a clean slate.

**Comment by marcelpaulo** [comment]
![image](https://user-images.githubusercontent.com/10074769/38848421-7560f882-41dd-11e8-8f20-eca03459c157.png)

Now waiting for it to be marked as not downloaded ...

**Comment by marcelpaulo** [comment]
It hasn't been marked as not downloaded, but ... weirder, there are duplicate entries now:

![image](https://user-images.githubusercontent.com/10074769/38893879-00d9e07a-4262-11e8-9c34-d77c4d1241f0.png)

and these are the only messages from `TorrentMonitor.js`:

![image](https://user-images.githubusercontent.com/10074769/38893957-39d88a8e-4262-11e8-8262-07d39eab4454.png)

**Comment by marcelpaulo** [comment]
Not sure if it helps, I've pasted the full console log [here](https://pastebin.com/THiwQC6h)

**Comment by garfield69** [comment]
I see this too, this morning. The dates for episode 3 and 4 have been changed.
The calendar temporarily reflects these date changes, but will correct its self on the next refresh. There is no cause for concern about that.

I took a DB snap shot yesterday and compared it with one taken this morning, and can see that the air-date is the only significant data that changed this time in my DB records.
![image](https://user-images.githubusercontent.com/6933240/38899338-a86bafc4-42eb-11e8-8309-6de46cf1f792.png)

What it does show is that trakt.tv is still actively updating significant parts of this series' records.

I still maintain that the most likely explanation for what you have seen with your download flags is a result of tratk.tv having changed the ID's of the episodes, which would cause DuckieTV to build new records and eventually delete the old orphaned ones.
There is nothing that DuckieTV can do about this, it not something it can control.

I took a look at your log, but there is nothing related to this issue there.
If you spot your download flags reset again let me know, I'll do the same if it happens to me.

**Comment by marcelpaulo** [comment]
Thanks for the detailed and patient explanation and analysis !

> I still maintain that the most likely explanation for what you have seen with your download flags is a result of tratk.tv having changed the ID's of the episodes, which would cause DuckieTV to build new records and eventually delete the old orphaned ones.

This makes perfect sense to me. I guess we could wrap this up, and reopen in case we see the download flags reset for a reason other than a change in the trakt episode ID (which seems unlikely, as you explained).

**Comment by garfield69** [comment]
Hah. just checked *the city and the city* this morning, and the dates for ep 3 and 4 have been changed by trakt.tv again!
However, on top of that, the leaked flags have been reset and so has the downloaded flag.
comparing the DB snapshot from yesterday, I see that the trakt.tv id has not changed.
So this demonstrates that during the refresh, DuckieTV's update logic is indeed faulty, so I am reopening this ticket, and when I next have time I will start examining the code for the bug.

**Comment by marcelpaulo** [comment]
Oh ... It hasn't happened to me, but ... I know why: I changed the trakt.tv update interval back to 12h, and the console log says:

![image](https://user-images.githubusercontent.com/10074769/38959478-30549982-4337-11e8-865a-7476739e75ca.png)

I'll change it back to 1h, and observe what happens after the next update.

**EDIT:** Indeed, you're right, the update has just happened, and those episodes' downloaded flags have been reset.

**Comment by garfield69** [comment]
should be fixed with d2f64a3.
now when a user sets the leaked flag on an episode, it does not get reset when the date of an episode is set to the past.
this in turn means that the downloaded flag will not be reset when a future date is set on an episode that has been marked as leaked.

**Comment by garfield69** [comment]
P.S. you can force a refresh on a series any time, by using the *series side panel*'s  **refresh** button.

**Comment by marcelpaulo** [comment]
Wow, that was instant-quick !

Please forgive me for my ignorance: I've installed Browser Action from the cloned git repo. I've just git-pulled it right now, do I have to delete the chrome extension and install it again so that it picks up the update ?

**Comment by marcelpaulo** [comment]
> you can force a refresh on a series any time, by using the series side panel's refresh button

Thanks for the tip, I didn't know that !

**Comment by garfield69** [comment]
>do I have to delete the chrome extension and install it again so that it picks up the update ?

no. simply closing and opening a new duckietv tab should pickup any changes.
But if you want to be extra certain, then go to the extensions page and click on refresh button
![image](https://user-images.githubusercontent.com/6933240/38960173-99652114-43b7-11e8-9dcb-dc311b70a0a1.png)
This will reload the entire extension code and perform the validation.
and before you ask, this should  not impact the state of the DB, unless there is a problem, of course ;-)

**Comment by marcelpaulo** [comment]
Thanks for clarifying it, @garfield69 ! I had just done that but wasn't sure if it would be enough.
