### ISSUE TITLE
Dot (.) removed from series name on Torrent Search

### ISSUE THREAD

**Issue by marcelpaulo** [SchizoDuckie/DuckieTV#1077]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Browser Action

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Angular b0ada73ce0f19aea45736dab460acfcb4587df3c

**What is your Operating System (Windows, Mac, Linux, Android)**
Linux (Xubuntu 17.10)

**Describe the problem you are having and steps to reproduce if available**
When the series name contains dots (**.**), such as **The Last O.G.**:
![image](https://user-images.githubusercontent.com/10074769/38935327-795c3bbe-42f4-11e8-8821-fcb34ffa7ff2.png)
the dots are removed from the name in the `Torrent Search` box:
![image](https://user-images.githubusercontent.com/10074769/38936015-299507e4-42f6-11e8-966f-d9316addcb45.png)
and when I manually search with the dots, the search engine `ThePirateBay` fails:
![image](https://user-images.githubusercontent.com/10074769/38935606-1f119266-42f5-11e8-8654-5263ab6586aa.png)
This is the related error message on the console:
![image](https://user-images.githubusercontent.com/10074769/38935676-4e7d8262-42f5-11e8-8a78-dad15792e559.png)

Just to make sure everything was OK with _The Pirate Bay_ site itself, I repeated the search with Jackett:
![image](https://user-images.githubusercontent.com/10074769/38936330-ed867994-42f6-11e8-879e-dbb6e8beaff1.png)
and also directly on the site:
![image](https://user-images.githubusercontent.com/10074769/38936363-f8d3b456-42f6-11e8-8e91-595c64b67e62.png)

I wasn't sure whether I should open a separate issue for this, please let me know if it's the case, and I'll do it.

**EDIT:** As a workaround, I enabled the Jackett indexer for _The Pirate Bay_.

I tried searching other series with punctuation characters in the name, and noticed that dashes (**-**) are not removed (*9-1-1*), but colons (**:**) are removed too (*Troy: Fall of a City*).

**Attach any DuckieTV statistics or Developer Console logs if available**
I enabled Opt-in error Tracking before reproducing the issue (Unique Tracker ID **fcc4c833-d67f-849d-4a18-5daec48c91cf**), and here's the [console log](https://pastebin.com/k4fKCz6z)

**Comment by garfield69** [comment]
The torrent scene often do not use the full broadcast series name for the titles of the most popular torrents, and punctuation and other special characters are often left out by the scene uploaders in their torrent titles.
DuckieTV strips most special characters apart from the dash, as the removal of these characters usually generates more search hits for the majority of the torrent sites that you can search on.

But there are exceptions.

When this happens, DuckieTV uses a sceneNameExceptions table to cope.
I have added *The Last O G* as an exception, and your DuckieTV will update itself within 24 hours when it updates its local sceneNameExceptions table as part of it's daily refresh from the sceneNameExceptions server.

If you come across other similar clashes, just raise a sceneNameException ticket here, or on [Reddit](https://www.reddit.com/r/duckietv/), specifying the broadcast series name, and the most popular torrent scene name,  and I will amend the table on the server.

As for the SPDY PROTOCOL http error, this is something that occurs occasionally (and sometimes regularly in waves) on chromium engines (which is used by the Chrome Browser and NWJS), and is not under DuckieTV's control.

As it happens, I also personally use Jackett to proxy all my DuckieTV search engines. Jackett's http requests either does not get this error or has better recovery/retry logic :-)

**Comment by marcelpaulo** [comment]
> DuckieTV strips most special characters apart from the dash, as the removal of these characters usually generates more search hits for the majority of the torrent sites

It makes perfect sense. I have a script to rename srt files to match the corresponding video files, and I strip all non alphanumeric characters before trying a match.

> DuckieTV strips most special characters apart from the dash, as the removal of these characters usually generates more search hits for the majority of the torrent sites

It's the first time I hit this, but I'll do if it happens again. Good to know

> I also personally use Jackett to proxy all my DuckieTV search engines

I'll follow your lead.

Thanks, @garfield69, for another detailed and patient explanation !
