### ISSUE TITLE
Redirect blocked by CORS policy: can't download torrents from 1337x and ETTV through Jackett proxy

### ISSUE THREAD

**Issue by marcelpaulo** [SchizoDuckie/DuckieTV#1078]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Browser Action

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
angular d2f64a314e94fd002043eaface5bcbb7ea1f385e

**What is your Operating System (Windows, Mac, Linux, Android)**
Linux (Xubuntu 17.10)

**Describe the problem you are having and steps to reproduce if available**
I was configuring DuckieTV to prox all search engines through Jackett, and hit an issue with 1337x. The magnet link for all 1337x seemed disabled, so I clicked on the `Download torrent` icon:
![image](https://user-images.githubusercontent.com/10074769/38961800-9d605a9e-4340-11e8-8dbb-2401c1b86d2f.png)
Checked transmission and the torrent hadn't been added. I cleared the console log and repeated the operation, here it is (I've also pasted it [here](https://pastebin.com/5g1seKwE) in case it's more practical to look at):
```
19:37:57.105 tab.html#/episode/1208:1 Failed to load http://localhost:9117/dl/1337x/?jackett_apikey=ej32pk6qjir7f7nzh0rru8l2j2cgjy1g&path=b3l2ZGRTWmphQmRkUjNpSlROOEpFbSswcjhjcXJrQXhSM0xYOC92cnFpTXNJUjBGaU5JR0ZQRmdTVmp4QWZaZ3EydG9uSDVDRjI4WEhNZWhGZTZJQlUyUEowNGxuMkJDUkluM3lwWjBrZ0ZxNTB1V3VyQVJSekZUaUNnSXNOZDlDUER5OWlEaUFlZnRPVXRFQllxdkszSGdFYkRHNXVSOTR4TzhXRVIrRXBmaGRjaldPYmhnZTNycnFYUDNyN1RSa1h0ckNtcGozVytoemhTbUZuNlpucGU0aStFd1cvZHRyMlRleGhzTFRTdllsN2o3U1IyLzBaWGJoaVVLbERyelFHQ1gvZzFwd1pzREpkZGtSeDNhY1NFVFhURXBicGc4MUpFMUhmcmlmQXROdUJlcGdHZWkvMHZvM0tTa2VqdFZ5bXErL0FPZkRWQS9HZXFKZVYxQzB5R1YvRkM1Si9NVlZXMngvaVdPYkRrRXEraDlZeCtlU04zWlJMNlU1MDc0Z1pnbzZTNHRDQ3lDWEE0MXlwL2FpUT090&file=The+City+And+The+City+S01E03+(720p+HD%2C+soft+Eng+subs): Redirect from 'http://localhost:9117/dl/1337x/?jackett_apikey=ej32pk6qjir7f7nzh0rru8l2j2cgjy1g&path=b3l2ZGRTWmphQmRkUjNpSlROOEpFbSswcjhjcXJrQXhSM0xYOC92cnFpTXNJUjBGaU5JR0ZQRmdTVmp4QWZaZ3EydG9uSDVDRjI4WEhNZWhGZTZJQlUyUEowNGxuMkJDUkluM3lwWjBrZ0ZxNTB1V3VyQVJSekZUaUNnSXNOZDlDUER5OWlEaUFlZnRPVXRFQllxdkszSGdFYkRHNXVSOTR4TzhXRVIrRXBmaGRjaldPYmhnZTNycnFYUDNyN1RSa1h0ckNtcGozVytoemhTbUZuNlpucGU0aStFd1cvZHRyMlRleGhzTFRTdllsN2o3U1IyLzBaWGJoaVVLbERyelFHQ1gvZzFwd1pzREpkZGtSeDNhY1NFVFhURXBicGc4MUpFMUhmcmlmQXROdUJlcGdHZWkvMHZvM0tTa2VqdFZ5bXErL0FPZkRWQS9HZXFKZVYxQzB5R1YvRkM1Si9NVlZXMngvaVdPYkRrRXEraDlZeCtlU04zWlJMNlU1MDc0Z1pnbzZTNHRDQ3lDWEE0MXlwL2FpUT090&file=The+City+And+The+City+S01E03+(720p+HD%2C+soft+Eng+subs)' to 'magnet:?xt=urn:btih:54811404466C3E4BC97FF925C5C984361696F8B2&dn=The+City+And+The+City+S01E03+(720p+HD%2C+soft+Eng+subs)+&tr=udp:%2F%2Ftracker.coppersurfer.tk:6969%2Fannounce&tr=udp:%2F%2Ftracker.zer0day.to:1337%2Fannounce&tr=udp:%2F%2Ftracker.leechers-paradise.org:6969%2Fannounce&tr=udp:%2F%2Fcoppersurfer.tk:6969%2Fannounce' has been blocked by CORS policy: Redirect location 'magnet:?xt=urn:btih:54811404466C3E4BC97FF925C5C984361696F8B2&dn=The+City+And+The+City+S01E03+(720p+HD%2C+soft+Eng+subs)+&tr=udp:%2F%2Ftracker.coppersurfer.tk:6969%2Fannounce&tr=udp:%2F%2Ftracker.zer0day.to:1337%2Fannounce&tr=udp:%2F%2Ftracker.leechers-paradise.org:6969%2Fannounce&tr=udp:%2F%2Fcoppersurfer.tk:6969%2Fannounce' has a disallowed scheme for cross-origin requests.
19:37:57.136 utility.js:169 Arguments(3)
console.error @ utility.js:169
19:37:57.183 torrentDialog2.js:323 Uncaught Error: Error downloading torrent: XHR error
    at parse-torrent.js:8484
    at module.exports.<anonymous> (parse-torrent.js:9995)
    at module.exports.f (parse-torrent.js:9098)
    at module.exports.EventEmitter.emit (parse-torrent.js:2325)
    at XMLHttpRequest.xhr.onerror (parse-torrent.js:6844)
```

I tried to search/download exactly the same torrent (I had tried through DuckieTV) directly on Jackett, and it was correctly downloaded/added to transmission. From looking at the console log, I get the impression DuckieTV got the torrent but didn't parse it, but couldn't decypher why.

I tried to download other episodes from 1337x but they all failed with the same parsing error.

**Attach any DuckieTV statistics or Developer Console logs if available**
Opt-in error tracking was enabled for ID **fcc4c833-d67f-849d-4a18-5daec48c91cf**.

**Comment by marcelpaulo** [comment]
I noticed that the magnet link icon for Demonoid was also disabled, so I clicked on the `Download torrent` icon, and the torrent was correctly downloaded/added to transmission. So it looks like it's something specific about torrents from 1337x.

**Comment by marcelpaulo** [comment]
In case it helps, here's the 1337x torrent that DuckieTV didn't parse, which I later downloaded directly through Jackett:

[1337x-torrent.zip](https://github.com/SchizoDuckie/DuckieTV/files/1926061/1337x-torrent.zip)

**Comment by marcelpaulo** [comment]
I've just discovered that the issue also happens with ETTV torrents, with exactly the same error messages in the console log:
![image](https://user-images.githubusercontent.com/10074769/38967643-6b7d47c6-435e-11e8-9f1a-4a352c6dbe3d.png)
I downloaded the torrent directly from ETTV, here it is:
[ettv-torrent.zip](https://github.com/SchizoDuckie/DuckieTV/files/1926409/ettv-torrent.zip)
Here are the console messages:
```
23:08:07.594 designated-survivor-58e499bad94d7.jpg:1 Failed to load resource: the server responded with a status of 500 ()
23:08:07.596 designated-survivor-580dc2089f939.jpg:1 Failed to load resource: the server responded with a status of 500 ()
23:08:08.445 SceneXemResolver.js:92 Xem does not have series Designated Survivor (311876), using default format.
23:08:25.462 tab.html#/episode/4986:1 Failed to load http://localhost:9117/dl/ettv/?jackett_apikey=ej32pk6qjir7f7nzh0rru8l2j2cgjy1g&path=SURKNXBqVjJEOGhzdDdzdEphd2tzVWVuTzV6RXpRRnpBbnlsZUFFMzJ6TGNocVMwU2NXV0hpT3E3dDNmckcyOHJsMWU1WDlwL1EyQ091ZHYvSEg5TW5PYy8zdVNrRHp1ZTdSWStET1hRL3RJY1orL0lqZU9PdW5Lakd3eTd6c2F2NkR1aVQ2bzRNcXkwVlJtN2lMQkVSYnBpRlgrSzI1eUZXOTQ0MGdWYjdaMUNrMFBnV2w4bm5kSWhpa0ZKYTNQdmxPVjNIMm9ORlBSSDBNSTBrQThTeEw3bU9BSURpeVFocnVIVFpiV3JEVk9wNytFeWZJdU9uSzNSdUtuS3NmdVRYVFJ2OHNkZzdGUkk0d3lRZkY4dnRQM3JxT25uenFtdDAzVGJUeWh3WEN5aFdhQkpxMnprM3RTWFpGT0xZUGdQRXhWVkROMnM5QXR6SEQ4M3ZJTzQ2NEZ5dkZXc0RucXkwZWhYZEVTOGl6RkZ0c2dvVWEwZWxpNW9OZWwzaSs2NHcweFdONG9kbnJGejFMczFycCtRZz090&file=Designated.Survivor.S02E18.HDTV.x264-KILLERS%5Bettv%5D: Redirect from 'http://localhost:9117/dl/ettv/?jackett_apikey=ej32pk6qjir7f7nzh0rru8l2j2cgjy1g&path=SURKNXBqVjJEOGhzdDdzdEphd2tzVWVuTzV6RXpRRnpBbnlsZUFFMzJ6TGNocVMwU2NXV0hpT3E3dDNmckcyOHJsMWU1WDlwL1EyQ091ZHYvSEg5TW5PYy8zdVNrRHp1ZTdSWStET1hRL3RJY1orL0lqZU9PdW5Lakd3eTd6c2F2NkR1aVQ2bzRNcXkwVlJtN2lMQkVSYnBpRlgrSzI1eUZXOTQ0MGdWYjdaMUNrMFBnV2w4bm5kSWhpa0ZKYTNQdmxPVjNIMm9ORlBSSDBNSTBrQThTeEw3bU9BSURpeVFocnVIVFpiV3JEVk9wNytFeWZJdU9uSzNSdUtuS3NmdVRYVFJ2OHNkZzdGUkk0d3lRZkY4dnRQM3JxT25uenFtdDAzVGJUeWh3WEN5aFdhQkpxMnprM3RTWFpGT0xZUGdQRXhWVkROMnM5QXR6SEQ4M3ZJTzQ2NEZ5dkZXc0RucXkwZWhYZEVTOGl6RkZ0c2dvVWEwZWxpNW9OZWwzaSs2NHcweFdONG9kbnJGejFMczFycCtRZz090&file=Designated.Survivor.S02E18.HDTV.x264-KILLERS%5Bettv%5D' to 'magnet:?xt=urn:btih:5422f8570cfa675ee24ff8b2964f4e2f08640250&dn=Designated.Survivor.S02E18.HDTV.x264-KILLERS[ettv]&xl=220649231&tr=udp:%2F%2Ftracker.coppersurfer.tk:6969/announce&tr=udp:%2F%2F9.rarbg.to:2710/announce&tr=udp:%2F%2F9.rarbg.me:2710/announce&tr=udp:%2F%2Ftracker.internetwarriors.net:1337/announce&tr=udp:%2F%2Ftracker.opentrackr.org:1337/announce&tr=udp:%2F%2Fp4p.arenabg.com:1337/announce&tr=udp:%2F%2Feddie4.nl:6969/announce&tr=udp:%2F%2Fshadowshq.yi.org:6969/announce&tr=udp:%2F%2Ftracker.leechers-paradise.org:6969/announce&tr=udp:%2F%2Fexplodie.org:6969/announce&tr=udp:%2F%2Ftracker.tiny-vps.com:6969/announce&tr=udp:%2F%2Finferno.demonoid.pw:3391/announce&tr=udp:%2F%2Fipv4.tracker.harry.lu:80/announce&tr=udp:%2F%2Fpeerfect.org:6969/announce&tr=udp:%2F%2Ftracker.pirateparty.gr:6969/announce&tr=udp:%2F%2Ftracker.vanitycore.co:6969/announce&tr=udp:%2F%2Fopen.stealth.si:80/announce&tr=udp:%2F%2Ftracker.torrent.eu.org:451&tr=udp:%2F%2Ftracker.open-internet.nl:6969/announce' has been blocked by CORS policy: Redirect location 'magnet:?xt=urn:btih:5422f8570cfa675ee24ff8b2964f4e2f08640250&dn=Designated.Survivor.S02E18.HDTV.x264-KILLERS[ettv]&xl=220649231&tr=udp:%2F%2Ftracker.coppersurfer.tk:6969/announce&tr=udp:%2F%2F9.rarbg.to:2710/announce&tr=udp:%2F%2F9.rarbg.me:2710/announce&tr=udp:%2F%2Ftracker.internetwarriors.net:1337/announce&tr=udp:%2F%2Ftracker.opentrackr.org:1337/announce&tr=udp:%2F%2Fp4p.arenabg.com:1337/announce&tr=udp:%2F%2Feddie4.nl:6969/announce&tr=udp:%2F%2Fshadowshq.yi.org:6969/announce&tr=udp:%2F%2Ftracker.leechers-paradise.org:6969/announce&tr=udp:%2F%2Fexplodie.org:6969/announce&tr=udp:%2F%2Ftracker.tiny-vps.com:6969/announce&tr=udp:%2F%2Finferno.demonoid.pw:3391/announce&tr=udp:%2F%2Fipv4.tracker.harry.lu:80/announce&tr=udp:%2F%2Fpeerfect.org:6969/announce&tr=udp:%2F%2Ftracker.pirateparty.gr:6969/announce&tr=udp:%2F%2Ftracker.vanitycore.co:6969/announce&tr=udp:%2F%2Fopen.stealth.si:80/announce&tr=udp:%2F%2Ftracker.torrent.eu.org:451&tr=udp:%2F%2Ftracker.open-internet.nl:6969/announce' has a disallowed scheme for cross-origin requests.
23:08:25.501 utility.js:169 Arguments(3)
console.error @ utility.js:169
23:08:25.538 torrentDialog2.js:323 Uncaught Error: Error downloading torrent: XHR error
    at parse-torrent.js:8484
    at module.exports.<anonymous> (parse-torrent.js:9995)
    at module.exports.f (parse-torrent.js:9098)
    at module.exports.EventEmitter.emit (parse-torrent.js:2325)
    at XMLHttpRequest.xhr.onerror (parse-torrent.js:6844)
```

**Comment by marcelpaulo** [comment]
I can see that the error messages have this structure:

`Failed to load` *jackett-url*: `Redirect from` *jackett-url* `to` *magnet-link* `has been blocked by CORS policy`: `Redirect location` *magnet-link* `has a disallowed scheme for cross-origin requests`.

I googled it, got many hits, but I confess I couldn't understand it. This article seemed to be the most detailed one:

<https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS>

**Comment by 2635599** [comment]
just remove ettv altogether, cause they nothing but a bunch of racist / bigoted BASTARD.

**Comment by garfield69** [comment]
@marcelpaulo  thanks for reporting. I shall investigate.

**Comment by garfield69** [comment]
hmm. the CORS issue seems to be something new, introduced with chrome browser 66.   

But the basic issue with jackett's version of the 1337x indexer is that jackett has to navigate to the torrent details page to fetch the magnet, however in its presentation to duckietv of the results, it classifies it as a download link (which from jackett implies a .torrent file link and not a magnet).
DuckieTV expects a .torrent and gets confused when presented with a magnet.

In versions of Duckietv running on chromium 65, the clicking of the duckietv download torrent button results in a no-response (the request gets lost in a black hole with no errors posted anywhere %-/ ).

Jackett does not have the ability to flag a magnet as a magnet from the details page, like it does if the magnet comes from a results page.

A circumvention for this, is to use the itorrents option on jackett.
Try the following: 
1. on your jackett dashboard edit the 1337x indexer and set the download link to `iTorrents.org` instead of the default `magnet`.
2. then retry your download from duckietv.

it should work as it did for me during testing. the caveat is that sometimes, especially for very new torrents, the magnet is not converted to a .torrent by itorrents.org because they don't have it in their database yet. this results in a no-response black-hole as well. retrying some time later usually returns a result.

I'll take a look at the ettv indexer in jackett and see if there is the possibility to add that option there as well., so that duckietv can use that SE.
if I cant add it there, then you will have to use the duckietv native ettv SE instead. I'll post an update on this when I time to take a look.

**Comment by garfield69** [comment]
I've added a similar option for jackett's ettv via https://github.com/Jackett/Jackett/commit/13e14f3e62e754f6b410a6a3e99b2c2366a651bf . 
once this gets included in the next (pre)release of jackett you'll be able to use it with duckietv.

if you came across any other jackett indexers that give you that cors error let me know and i'll see if they also can be amended to work.

**Comment by marcelpaulo** [comment]
> on your jackett dashboard edit the 1337x indexer and set the download link to iTorrents.org instead of the default magnet

It works, exactly as you described ! 

> if I cant add it there, then you will have to use the duckietv native ettv SE instead

That's how I was circumventing for both 1337x and ETTV.

> I've added a similar option for jackett's ettv via Jackett/Jackett@13e14f3 .
once this gets included in the next (pre)release of jackett you'll be able to use it with duckietv.

I'll test it right away as soon as the next (pre)release is available.

> if you came across any other jackett indexers that give you that cors error let me know and i'll see if they also can be amended to work

I tested all indexers I'm currently using, and 1337x and ETTV were the only ones that hit this issue. But in case it happens with some other one, should I open the issue here or at Jackett ?

Once again, thanks for your patient and detailed explanations, @garfield69 !

**Comment by garfield69** [comment]
>I tested all indexers I'm currently using, and 1337x and ETTV were the only ones that hit this issue. But in case it happens with some other one, should I open the issue here or at Jackett ?

It may be simpler to open the ticket here, as I know what the circumstances are for raising the request.

**Comment by marcelpaulo** [comment]
Indeed, I've just upgraded Jackett to 0.8.913.0, tested ETTV with `eTorrent.click` and it's working flawlessly. Once again, thanks for your patience and diligence, @garfield69 !

**Comment by marcelpaulo** [comment]
Just to leave it documented, this issue has just happened with **LimeTorrents**:
![image](https://user-images.githubusercontent.com/10074769/39407139-f0d4a9a0-4b97-11e8-83ac-32ff9ac2f9b5.png)
but Jackett already had the option of changing the `Download link` to **iTorrents.org**, so all is good.
