### ISSUE TITLE
Transmission Integration Broken

### ISSUE THREAD

**Issue by scollonp** [SchizoDuckie/DuckieTV#1079]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**

Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**

Always Latest Nightly Build (nightly-201804190130)

**What is your Operating System (Windows, Mac, Linux, Android)**

GNU/Linux (Ubuntu 16.04.4 LTS)

**Describe the problem you are having and steps to reproduce if available**

While using Transmission as the torrent client in the last few nightly builds, the torrent does not get started in Transmission, even though it is configured correctly (connected to API @ http://localhost@9091 - same as always was, works in last stable release) and DuckieTV announces the torrent has been sent ("Download started on Transmission"). Transmission has nothing in the queue, but it works fine when clicking magnet links in my browser and does it's thing. The exact same process with Deluge or any other client integrated with DuckieTV results in the torrent being sent to the client correctly, as you would expect. There is definitely something broken with the Transmission integration, at least for the client version I have. I am using transmission version 2.84 and deluge version 1.3.15.

**Update:**  On another machine with transmission 2.92, the torrent download DOES kick off. The issue could be incompatibility of recent DuckieTV builds with older Transmission client in the Ubuntu LTS repositories....

**Attach any DuckieTV statistics or Developer Console logs if available**

[
  {
    "name": "DuckieTV Web Based",
    "data": "201804190130"
  },
  {
    "name": "Current Date and Time",
    "data": "Thu, 19 Apr 2018 06:44:08 GMT"
  },
  {
    "name": "NWJS, Chromium",
    "data": "0.29.2 , 65.0.3325.181"
  },
  {
    "name": "UserAgent",
    "data": "DuckieTV-Standalone  Nightly v201804190130 X11; Linux x86_64"
  },
  {
    "name": "Platform, Vendor",
    "data": "Linux x86_64, Google Inc."
  },
  {
    "name": "Screen (width x height)",
    "data": "1440 x 900"
  },
  {
    "name": "Default Search Engine",
    "data": "EzTV.ag (Enabled)"
  },
  {
    "name": "Default Torrent Client",
    "data": "Transmission (Enabled and Connected to Host)"
  },
  {
    "name": "Auto Download Service",
    "data": "(Enabled but Inactive)"
  },
  {
    "name": "Last checked TraktTV for DB updates on",
    "data": "Thu, 19 Apr 2018 06:34:19 GMT"
  },
  {
    "name": "User Preferences on Local Storage",
    "data": "{\n  \"ThePirateBay.mirror\": \"https://thepiratebay.org\",\n  \"application.language\": \"en_us\",\n  \"application.locale\": \"en_us\",\n  \"autobackup.period\": \"monthly\",\n  \"autodownload.delay\": 360,\n  \"autodownload.multiSE\": {\n    \"ThePirateBay\": true,\n    \"1337x\": true,\n    \"IsoHunt\": true,\n    \"KATcr\": true,\n    \"Nyaa\": true,\n    \"RarBG\": true,\n    \"ShowRSS\": true,\n    \"TorrentDownloads\": true,\n    \"TorrentZ2\": true,\n    \"Zooqle\": true,\n    \"EzTV.ag\": true,\n    \"Idope\": true,\n    \"LimeTorrents\": true,\n    \"SkyTorrents\": true,\n    \"ETag\": true,\n    \"ETTV\": true,\n    \"IsoHunt2\": true\n  },\n  \"autodownload.multiSE.enabled\": false,\n  \"autodownload.period\": 3,\n  \"background-rotator.opacity\": \"0.4\",\n  \"calendar.mode\": \"date\",\n  \"calendar.show-downloaded\": true,\n  \"calendar.show-episode-numbers\": false,\n  \"calendar.show-specials\": true,\n  \"calendar.startSunday\": true,\n  \"client.determinedlocale\": \"en_uk\",\n  \"download.ratings\": true,\n  \"episode.watched-downloaded.pairing\": true,\n  \"kc.always\": false,\n  \"lastSync\": -1,\n  \"library.order.by\": \"getSortName()\",\n  \"library.order.reverseList\": [\n    true,\n    false,\n    true,\n    true\n  ],\n  \"library.seriesgrid\": true,\n  \"library.smallposters\": true,\n  \"main.viewmode\": \"calendar\",\n  \"notifications.enabled\": true,\n  \"series.displaymode\": \"poster\",\n  \"series.not-watched-eps-btn\": false,\n  \"storage.sync\": false,\n  \"subtitles.languages\": [\n    \"eng\"\n  ],\n  \"sync.progress\": true,\n  \"synology.enabled\": true,\n  \"synology.ip\": \"192.168.x.x\",\n  \"synology.password\": \"*****\",\n  \"synology.playback_devices\": {},\n  \"synology.port\": 5000,\n  \"synology.protocol\": \"http\",\n  \"synology.username\": \"admin\",\n  \"topSites.enabled\": false,\n  \"topSites.mode\": \"onhover\",\n  \"torrentDialog.2.activeSE\": {\n    \"ThePirateBay\": true,\n    \"1337x\": true,\n    \"IsoHunt\": true,\n    \"KATcr\": true,\n    \"Nyaa\": true,\n    \"RarBG\": true,\n    \"ShowRSS\": true,\n    \"TorrentDownloads\": true,\n    \"TorrentZ2\": true,\n    \"Zooqle\": true,\n    \"ETag\": true,\n    \"ETTV\": true,\n    \"EzTV.ag\": true,\n    \"Idope\": true,\n    \"IsoHunt2\": true,\n    \"LimeTorrents\": true\n  },\n  \"torrentDialog.2.enabled\": true,\n  \"torrentDialog.2.sortBy\": \"-seedersInt\",\n  \"torrentDialog.showAdvanced.enabled\": true,\n  \"torrenting.autodownload\": true,\n  \"torrenting.autostop\": true,\n  \"torrenting.autostop_all\": false,\n  \"torrenting.client\": \"Transmission\",\n  \"torrenting.directory\": true,\n  \"torrenting.enabled\": true,\n  \"torrenting.global_size_max\": 1024,\n  \"torrenting.global_size_max_enabled\": true,\n  \"torrenting.global_size_min\": null,\n  \"torrenting.global_size_min_enabled\": true,\n  \"torrenting.ignore_keywords\": \"\",\n  \"torrenting.ignore_keywords_enabled\": true,\n  \"torrenting.label\": false,\n  \"torrenting.launch_via_chromium\": false,\n  \"torrenting.min_seeders\": 50,\n  \"torrenting.min_seeders_enabled\": false,\n  \"torrenting.progress\": true,\n  \"torrenting.require_keywords\": \"\",\n  \"torrenting.require_keywords_enabled\": true,\n  \"torrenting.require_keywords_mode_or\": true,\n  \"torrenting.searchprovider\": \"EzTV.ag\",\n  \"torrenting.searchquality\": \"\",\n  \"torrenting.searchqualitylist\": [\n    \"480p\",\n    \"HDTV\",\n    \"720p\",\n    \"1080p\",\n    \"2160p\"\n  ],\n  \"torrenting.streaming\": true,\n  \"trakt-update.period\": 12,\n  \"trakttv.passwordHash\": \"*****\",\n  \"trakttv.sync\": false,\n  \"trakttv.username\": null,\n  \"transmission.password\": \"*****\",\n  \"transmission.path\": \"/usr/bin/transmission-gtk\",\n  \"transmission.port\": 9091,\n  \"transmission.progressX100\": true,\n  \"transmission.server\": \"http://localhost\",\n  \"transmission.use_auth\": false,\n  \"transmission.username\": \"admin\",\n  \"autodownload.lastrun\": 1524120232618,\n  \"proxy.allowUnsafe\": true\n}"
  },
  {
    "name": "Other significant Local Storage keys",
    "data": "{\n  \"1.1.4TorrentHashListCleanup\": \"Tue Mar 27 2018 06:19:48 GMT+0100 (IST)\",\n  \"1.1.4cleanupOrphanedEpisodes\": \"Tue Mar 27 2018 06:19:35 GMT+0100 (IST)\",\n  \"1.1.4cleanupOrphanedSeasons\": \"Tue Mar 27 2018 06:19:35 GMT+0100 (IST)\",\n  \"1.1.4qBittorrentPre32\": \"Tue Mar 27 2018 06:19:29 GMT+0100 (IST)\",\n  \"1.1.4refresh\": \"Tue Mar 27 2018 06:19:39 GMT+0100 (IST)\",\n  \"1.1.4refreshTrendingCache\": \"Tue Mar 27 2018 06:19:29 GMT+0100 (IST)\",\n  \"1.1.4updateTransmissionPath\": \"Tue Mar 27 2018 06:19:29 GMT+0100 (IST)\",\n  \"1.1.5FetchFirstXemAliasMap\": \"Tue Mar 27 2018 06:19:29 GMT+0100 (IST)\",\n  \"1.1.5deleteSearchEngines\": \"Tue Mar 27 2018 06:19:29 GMT+0100 (IST)\",\n  \"1.1.5fanartCleanup\": \"Tue Mar 27 2018 06:19:59 GMT+0100 (IST)\",\n  \"1.1.5updateDelugeAuth\": \"Tue Mar 27 2018 06:19:29 GMT+0100 (IST)\",\n  \"1.1.5updateTorrenting.min_seeders\": \"Tue Mar 27 2018 06:19:29 GMT+0100 (IST)\",\n  \"1.1.6deleteWatchList\": \"Wed Apr 18 2018 06:24:48 GMT+0100 (IST)\",\n  \"1.1migration\": \"Tue Mar 27 2018 06:19:33 GMT+0100 (IST)\",\n  \"autobackup.lastrun\": \"1522127969802\",\n  \"database.version.Episodes\": \"14\",\n  \"database.version.Fanart\": \"1\",\n  \"database.version.Jackett\": \"2\",\n  \"database.version.Seasons\": \"6\",\n  \"database.version.Series\": \"16\",\n  \"database.version.WatchList\": \"1\",\n  \"database.version.WatchListObject\": \"1\",\n  \"fanart.bootstrapped\": \"1\",\n  \"github.lastupdatecheck\": \"1522127971839\",\n  \"install.notify\": \"1.1.5\",\n  \"runtime.event\": \"{\\\"reason\\\":\\\"install\\\"}\",\n  \"snr.lastFetched\": \"1524119633701\",\n  \"standalone.alwaysShowTray\": \"Y\",\n  \"standalone.closeSystray\": \"Y\",\n  \"standalone.minimizeSystray\": \"Y\",\n  \"standalone.position\": \"{\\\"width\\\":1440,\\\"height\\\":848,\\\"x\\\":0,\\\"y\\\":28,\\\"state\\\":\\\"normal\\\"}\",\n  \"standalone.trayColor\": \"-inverted\",\n  \"standalone.zoomlevel\": \"6\",\n  \"torrenting.client\": \"Transmission\",\n  \"trackers.lastFetched\": \"1522127971244\",\n  \"trakttv.lastupdated\": \"1524119659983\",\n  \"trakttv.lastupdated.trending\": \"1524029826014\",\n  \"uniqueId\": \"8c67d3d8-69b3-3bcb-9770-558127e57e0e\",\n  \"upgrade.notify\": \"1.1.5\",\n  \"xem.lastFetched\": \"1524119633655\"\n}"
  },
  {
    "name": "DB Series",
    "data": 23
  },
  {
    "name": "DB Series Hidden From Calendar",
    "data": 0
  },
  {
    "name": "DB Seasons",
    "data": 71
  },
  {
    "name": "DB Episodes",
    "data": 758
  },
  {
    "name": "DB Fanart",
    "data": 2015
  },
  {
    "name": "DB Jackett",
    "data": 0
  }
]

**Comment by scollonp** [comment]
After much, much testing, I cannot recreate this on another machine with the same software versions. Therefore issue must be specific to my system. Closing.

**Comment by garfield69** [comment]
did you ever figure this one out?

**Comment by scollonp** [comment]
Seemed to be completely local to my Ubuntu 16.04 laptop - could not
recreate it with same software on other systems, so assuming something
broken in my OS (but I'm stumped as to what). I switched my torrent client
to Deluge and everything works as expected, thank you for asking. I closed
the ticket shortly afterwards.

Paul
