### ISSUE TITLE
"Mark all downloaded" on a series season not pushing updates to trakt.tv

### ISSUE THREAD

**Issue by marcelpaulo** [SchizoDuckie/DuckieTV#1081]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Browser action

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
9751fb520d3f4140c791b72f30ff2877f204ea10

**What is your Operating System (Windows, Mac, Linux, Android)**
Linux (Xubuntu 17.10)

**Describe the problem you are having and steps to reproduce if available**
I had to wipe out my Chrome config. I rebuilt my DuckieTV config like this:

1. Added the unpacked extension directly from the git repo
1. Loaded an (outdated) backup
1. Imported all shows from trakt.tv, to update everything
1. I noticed that the 6 episodes of the season 1 of series *Save Me* were not marked as downloaded, as they were before I wiped the Chrome config. So I opened the series, then the season, and clicked on `Mark all downloaded`:
![image](https://user-images.githubusercontent.com/10074769/39077674-1745d542-44da-11e8-9e04-70d702d03965.png)
1. Checking the series on trakt.tv, I noticed that the episodes had not been marked as collected:
![image](https://user-images.githubusercontent.com/10074769/39077727-63391b58-44da-11e8-801f-558c148e5af4.png)
1. Checked the console log, and no message was logged
1. I then marked each episode, individually, as downloaded
1. The episodes were marked as collected on trakt.tv

**Attach any DuckieTV statistics or Developer Console logs if available**
Not sure it it helps, but I had enabled opt-in error tracking before doing anything,, and my tracker ID is **fcc4c833-d67f-849d-4a18-5daec48c91cf**

**Comment by marcelpaulo** [comment]
I think I discovered why those 6 episodes were not marked as downloaded when I loaded my outdated backup and updated the config importing all shows from trakt.tv:

1. I went backards on my trakt.tv collection, and those episodes had not been marked as collected
1. I had downloaded all episodes in a single torrent, so most likely at the time I did what I had just done right now: I opened the series, the season, and then clicked on `Mark all downloaded`. As the episodes appeared as downloaded on DuckieTV, I didn't bother to check them on trakt.tv
1. When I loaded the outdated backup and imported all shows from trakt.tv, those episodes were not marked as collected, so they were not marked as downloaded on DuckieTV

I think this explains it.

**Comment by marcelpaulo** [comment]
Just to make sure that this issue is not related to that specific series (*Save Me*), I added another series to `Favorites`, just for testing, opened the series, then the season, and then `Mark all downloaded`: the 6 available episodes were not marked as collected on trakt.tv. And also, as before, no messages were logged on the console.

So it seems that there's a generic issue with `Mark all downloaded`.

**Comment by garfield69** [comment]
thank you for reporting.
I can confirm that the season mark-all-downloaded button does not trigger the trakt.tv collected event.
I shall examine the code and figure out what is missing or broken.

**Comment by marcelpaulo** [comment]
Working flawlessly, have just tested it ! Thanks, @garfield69 !
