### ISSUE TITLE
sidepanel close buttons not clickable

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#1085]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
1.1.6

**What is your Operating System (Windows, Mac, Linux, Android)**
win7

**Describe the problem you are having and steps to reproduce if available**
since the latest round of graphical updates, the close buttons for the sidepanels seem to be positioned too near the top, such that If I click on them I end up clicking the app close button.

**Attach any DuckieTV statistics or Developer Console logs if available**
![image](https://user-images.githubusercontent.com/6933240/39404264-41aff4aa-4be4-11e8-815c-8b103eb3947c.png)
the pic above shows that despite hovering the mouse over the *series details* sidepanel **close** button, the active button is in fact the *windows* close button, as shown by the tooltip that reads *close*.
If that sidepanel button was active then the tooltip would read *close series details*.
Also in the above pic, the *series overview* close button is also not clickable, the tooltip if the button was active would read *close riverdale*.

**Comment by Js41637** [comment]
Couldn't really test if this was fixed but this should have fixed this issue @garfield69 ?

**Comment by garfield69** [comment]
sweet. works perfectly now.
