### ISSUE TITLE
[Feature Request] Select different quality levels for each show

### ISSUE THREAD

**Issue by faprobst** [SchizoDuckie/DuckieTV#1087]
This is a great app but it desperately needs to be able to pick different quality levels for each show. Some shows do not usually have 1080p available which makes this unuseable for them unless you go with 720p for everything. Also often older episodes are not seeded in 1080p so if you try and use the bulk autodownload on a new show it will either find nothing or a bunch of torrents with no seeds depending what you set minimum seeds to. Some shows I would typically not bother getting in 1080p either, just do save space. Also it would be good to be able to pick as many quality levels as you want and it will try to download the highest first and move down the list every X minutes until it finds an episode, that way you can try and get 1080p but get 720p if one does not come out fast enough.

**Comment by garfield69** [comment]
# Easily done. 
1. click on the series settings button, 
![image](https://user-images.githubusercontent.com/6933240/39562234-a139d1a8-4efe-11e8-89c9-0447b1e54a11.png)
# OR
![image](https://user-images.githubusercontent.com/6933240/39562249-b87c3dce-4efe-11e8-82f0-ed1e8e37d410.png)
# AND
2. and switch **on** the *do not used preferred quality for this show*, 
3. and load in the *custom search string field* whatever quality you want for that series.
![image](https://user-images.githubusercontent.com/6933240/39562197-77186204-4efe-11e8-9304-46de66715c76.png)

**Comment by garfield69** [comment]
>Also it would be good to be able to pick as many quality levels as you want and it will try to download the highest first and move down the list every X minutes until it finds an episode, that way you can try and get 1080p but get 720p if one does not come out fast enough.

Most users prefer to wait for the quality they want to watch.
I do not think there will be much demand for what you are suggesting, and I think I will decline this request.
