### ISSUE TITLE
investigate ETTV 

### ISSUE THREAD

**Issue by 2635599** [SchizoDuckie/DuckieTV#1088]
ETTV has bigoted staff so needs to be removed from duckietv. go to their forum and checkout "the age of the living dead thread" in the request section.

https://www.ettv.tv/forum/view/topic/age-of-the-living-dead--207

**Comment by SchizoDuckie** [comment]
I have no idea how DuckieTV has anything to do with this. Please keep your sexual orientation discussions away from our software.
