### ISSUE TITLE
ETTV torrent is fired but downloaded status is not updated: Invalid torrent identifier

### ISSUE THREAD

**Issue by marcelpaulo** [SchizoDuckie/DuckieTV#1090]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Browser Action

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
a3db7ce6

**What is your Operating System (Windows, Mac, Linux, Android)**
Linux (Xubuntu 18.04)

**Describe the problem you are having and steps to reproduce if available**
I've just donwloaded an ETTV torrent (through Jackett proxy **0.8.953.0**) for `Sweetbitter.S01E01.WEB.H264-DEFLATE[ettv]`:
![image](https://user-images.githubusercontent.com/10074769/39683002-72b49402-5189-11e8-9463-165d1aa366cd.png)

Although the torrent was fired and finished downloading:
![image](https://user-images.githubusercontent.com/10074769/39683054-c72c2f0e-5189-11e8-9537-c9bc93e9da4c.png)

DuckieTV didn't update its downloaded status:
![image](https://user-images.githubusercontent.com/10074769/39683069-e2257d6a-5189-11e8-942a-848c0cb4001f.png)

The only messages logged on the console related to this download were:

```
parse-torrent.js:8447 Invalid torrent identifier
parseTorrent @ parse-torrent.js:8447
TorrentSearchEngines.js:257 Firing Torrent By data upload!  6459112 F16172CFAAF843E41DC2226E88E4B7EAF4E1A11E Sweetbitter.S01E01.WEB.H264-DEFLATE[ettv] null null
```

**Comment by garfield69** [comment]
ETTV on Jackett requires it's config changed so it can be used with DuckieTV. 
see https://github.com/SchizoDuckie/DuckieTV/wiki/Using-Jackett-with-DuckieTV#duckietv-jackett-problems-and-solutions for a list of Jackett Indexers that we have found and fixes so far.

**Comment by marcelpaulo** [comment]
I already had Jackett configured to return torrents instead of magnets, since #1084:
![image](https://user-images.githubusercontent.com/10074769/39683942-f1cba500-518e-11e8-93c5-863451c4d99b.png)

**Comment by garfield69** [comment]
Then the problem was probably with ETTV's etorrent.click.
perhaps that service did not have a .torrent yet, always possible if the torrent is fresh out of the oven.
I have just tried both ETTV torrents that come up on the search you made, and the downloads are working for me now. 
have another go.

**Comment by marcelpaulo** [comment]
You're absolutely right: not only the torrent is fired, but now DuckieTV is updating the progress bar.

The weird thing is: it fired the torrent before, so I imagine ETTV handed over the .torrent to DuckieTV, and DuckieTV acknowledged that it had fired the torrent (logging on the console), but it didn't update the progress bar. Now it did, and also updated the downloaded status.

Thanks, @garfield69 !

**Comment by garfield69** [comment]
yeah. from DuckieTV's point of view, it had been given a link, and passed it to its torrent client for processing, so duckie was happy. 
However the link did not resolve into a .torrent so the download never happened.

**Comment by marcelpaulo** [comment]
Oh, I see, so DuckieTV fired the magnet link it received from Jackett, but it was expecting a .torrent file. But then... If Jackett is configured to return torrents, shouldn't it just return nothing if the torrent was still not available?

**Comment by garfield69** [comment]
no.  the event it your original problem went something like this:
1. duckietv was given the following link from jackett's ettv indexer: `https://etorrent.click/torrents/3cab-Sweetbitter.S01E01.720p.WEB.H264-DEFLATE[ettv].torrent`.
2. duckie then used the parse-torrent javascript (3rd party script not maintained by us) to try to get the hashkey, so that duckie can later track the progress of the torrent on the client.
3. but the etorrent.click did not return a .torrent file
4. parse-torrent fails to return a hashkey
5. duckie next does a load-torrent-by-data-upload using that link, and this time the link is resolved, and the .torrent is passed to the client
6. the client downloads the torrent and starts seeding
7. however since duckie does not have the hashkey it cant track the progress or stop the torrent on the client when its finished, or mark the episode as downloaded when the download was complete.

**Comment by marcelpaulo** [comment]
Wow, that was detailed and clear ! Very delicate timing. It may happen that

> perhaps that service did not have a .torrent yet, always possible if the torrent is fresh out of the oven

and then **(5)** would fail. I guess it would be safer, as a general rule of thumb, to avoid those torrent-only indexers (1337x, ETTV, ...) for torrents published too recently.
