### ISSUE TITLE
Can't add/read favorites since the 1.1.5 update

### ISSUE THREAD

**Issue by samuelkdavis** [SchizoDuckie/DuckieTV#1093]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
DuckieTV Windows x64

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 10

**Describe the problem you are having and steps to reproduce if available**
Since updating the favorites were lost, and I'm unable to add new favorites. When clicking add to favorites the spinner wont disappear.

**Attach any DuckieTV statistics or Developer Console logs if available**
Can't find logs

**Comment by Js41637** [comment]
1.1.5 has been out for ages? Did you only just update?

**Comment by samuelkdavis** [comment]
I didn't manually update. The update screen popped up today when opening it, when the issue occurred - so I assumed that it had auto-updated. There is a chance that an issue occurred which caused both the issues with adding/viewing favorites also caused the update changelog popup to display. I've only been using DuckieTV for about a week so I likely was always on this version. It was working fine until today.

**Comment by Js41637** [comment]
Something must have happened that caused it to reset. 1.1.5 was released in September 2017 and DuckieTV doesn't have auto updating (it will notify you about new versions).

Tbh i'm not really the person who handles bugs but I think @garfield69 is away for a couple days.

You can follow this wiki which has a lot of infomation about submitting bug reports and how to find any logs and such. https://github.com/SchizoDuckie/DuckieTV/wiki/How-to-raise-a-Bug-Report

**Comment by Js41637** [comment]
However seeing as the problem seems to be that it reset everything I doubt you will find anything. Honestly I don't know of any bug that could cause this. It just randomly happened? Did you do any PC cleaning or something that could have resulted in some files being deleted?

**Comment by samuelkdavis** [comment]
Since the version likely hasn't changed since I initially downloaded, it does sound environmental. I'm not aware of anything I've done which could have caused this.

Here's a dump of the information I've got access to.
Tracking ID: 313ee066-99ef-7e04-5106-7c5affada41f
[statistics.txt](https://github.com/SchizoDuckie/DuckieTV/files/2008141/statistics.txt)
![loader never finishes](https://user-images.githubusercontent.com/6887841/40105288-a3581c04-5946-11e8-810f-abf7375ee8b9.PNG)

Since running into this issue I have reinstalled twice. Once to the default location (AppData) and once to Program Files. The hasn't resolved itself. I've also ran "Wipe database and settings" which hasn't resolved the issue.

**Comment by garfield69** [comment]
The location of the installed programs is not the same as the dataspace for the database  and settings.
Locate the `C:\Users\<username>\AppData\Local\DuckieTV-Standalone` folder and delete it.
This will reset your duckietv and allow you to complete its first time initialisation.

**Comment by faprobst** [comment]
I had the same thing, also win10 standalone x64 forced update to 1.1.5 but I only installed Duckie a month ago so I thought I was on 1.1.5 already... It appears to have wiped my data I had to set up the torrent connection again and I readded a couple shows to favourites but I also can not open the favourites so not sure if they are all gone or what. The calendar also looks different in appearance, kind of smaller or something...

**Comment by faprobst** [comment]
Oh, also I ran out of disk space on my C drive where it was installed which I am wondering if that somehow triggered this unfortunately it happened while I was away for the weekend and I don't know if it happened at the same time or not.

**Comment by samuelkdavis** [comment]
That worked @garfield69, I knew it'd be something simple like that. Hope it worked for you too @faprobst
