### ISSUE TITLE
ducky tv removal MACOSX or settings location

### ISSUE THREAD

**Issue by wayneward** [SchizoDuckie/DuckieTV#1095]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
... standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
... nightly latest - can't get into software rot see build 

**What is your Operating System (Windows, Mac, Linux, Android)**
... Mac

**Describe the problem you are having and steps to reproduce if available**
... it wasn't putting the path in to the torrent so every new show it would just sit asking for the path but I did import my shows from my previous Mac which had different folder path so now I just want to start again

**Attach any DuckieTV statistics or Developer Console logs if available**
... can't get in to it its just sat there so want to remove the settings but dont know were they are on a Mac!

**Comment by garfield69** [comment]
Duckietv on OSX should keep its settings and data in the folder called `~/Library/Application Support/DuckieTV-Standalone`. Deleting this folder should reset duckietv.    
But I see from reddit that you already used an app cleaner to solve this, so well done.

**Comment by wayneward** [comment]
yes that was location - I couldn't wait I was in a need to fix this mood yesterday and just moved back to Mac from linux so just getting used to were stuff is !!
after zapping it down its working 100% now I can just sit back and enjoy it!! thank you
