### ISSUE TITLE
[Browser Action] High CPU usage even when extension is apparently inactive

### ISSUE THREAD

**Issue by marcelpaulo** [SchizoDuckie/DuckieTV#1096]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Browser Action

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
b85acdc98707864416a38c71b7894267c62408df

**What is your Operating System (Windows, Mac, Linux, Android)**
Linux (Xubuntu 18.04)

**Describe the problem you are having and steps to reproduce if available**
I have been noticing that, whenever I have the DuckieTV tab open, my laptop fan is always working. Checking CPU usage with `htop` or chrome's `Task Manager`, I see that the DuckieTV extension is using what seems to be way too much CPU, even when there's no apparent activity. Right now, for instance, I'm not downloading any episodes, so there's no apparent activity, but even so this is a typical CPU usage, taken from Chrome's `Task Manager`:
![image](https://user-images.githubusercontent.com/10074769/40542099-095f4f04-5ff5-11e8-87d9-65ff455dd09c.png)
The actual value oscillates around 150%.

I'm running vanilla Chrome 66.0.3359.181 with the default experimental flags.

Is this magnitude of CPU usage to be expected or is there something that needs tweaking with Chrome or the operating system ? I haven't found any bug reports about cpu usage so I presume I may be the only one experiencing it, which would indicate that my environment may need to be customized.

**Attach any DuckieTV statistics or Developer Console logs if available**
I enabled error-tracking, my tracking ID is fcc4c833-d67f-849d-4a18-5daec48c91cf. I can't see a way of copy-paste `Statistics`. Let me know where I can get more useful/necessary info to attach to this issue.

**Comment by garfield69** [comment]
If you have duckietv connected to a torrent client that is actively seeding or downloading  torrents launched from duckietv, then the calendar view can be a place that consumes a lot of CPU.     
You can reduce significant CPU  this by going to the *settings > torrent* side panel, and scrolling down to the *torrent progress bar* and disabling this option.

**Comment by marcelpaulo** [comment]
So, even if all torrents launched by DuckieTV have finished downloading and are just seeding, DuckieTV still tracks them, thus eating CPU ? I thought that DuckieTV would be hungry for CPU updating the progress bars while the torrents were downloading, but once all torrents finished downloading, there would be no progress bars to update, so DuckieTV would stop eating CPU. If that's not the scenario, shouldn't it be so ? I mean, if there are no progress bars to update, shouldn't DuckieTV stop eating CPU ?

I had already played with disabling `Torrent Progress Bar`, and indeed it's dramatic how CPU usage falls.

**Comment by garfield69** [comment]
>So, even if all torrents launched by DuckieTV have finished downloading and are just seeding, DuckieTV still tracks them, thus eating CPU ? 

that is correct. DuckieTV requests from the client a list of all its torrents, then processes each one to determine which have been deleted, added, in progress, completed, seeding etc.
any of the torrents that are under duckietv's control then have their progress bar updated, green for complete, yellow/orange/red for the other states.
then duckietv calls the progress bar service from angularjs to present the display.
it is the display service, not duckietv that is using the cpu when building the graph.
it does not matter if the progress bar is 0% or 100%, the display is refreshed every cycle.
the higher the  number of torrents on the client the more cpu required to display their status collectively within the refresh cycle.

**Comment by marcelpaulo** [comment]
> it does not matter if the progress bar is 0% or 100%, the display is refreshed every cycle

Got it, thanks, @garfield69, for your patient and detailed answer.
