### ISSUE TITLE
Auto Download All - ignore previously downloaded episodes

### ISSUE THREAD

**Issue by knowair** [SchizoDuckie/DuckieTV#1099]
I Saw the request #1098 for Auto download all to change to download in the "correct" order, and thought that maybe if you do find some time at some point to make that change you could also add an option to Ignore any that are already marked as downloaded when clicking the option.

Often when using this function for older series, especially kids shows that often have 30-40 or even 50 episodes, i'll run it once with one search engine, and it'll find some of the episodes but not all. I then go though individually searching for the remaining ones, using different Search engines, and then if required reducing the quality and trying again.

It'd be great if there was a tick box option to "Ignore previously downloaded episodes" or "Only Download Missing Episodes" this way i can click it once, it'll find all it can, then I can switch the search engine for the show and just click it again, and then rinse and repeat, i don't need to go though each episode individually.

**Comment by garfield69** [comment]
Agreed. If episodes have already been marked as downloaded, then there is no need for the autodownload to process those episode again.
When we fix 1098 we will also implement this. Shant bother with a switch, this behaviour should be the defacto routine.

**Comment by knowair** [comment]
thanksmuchly
