### ISSUE TITLE
Use torrents from other website

### ISSUE THREAD

**Issue by DiukarevSergii** [SchizoDuckie/DuckieTV#1101]
Hi. Is it possible to use that web site ( http://www.lostfilm.tv ) to keep a track and auto download with your app?

**Comment by garfield69** [comment]
Yes. Duckietv can connect to the jackett proxy which in turn allows you to access other torrent search engines. I believe jackett supports access to lostfilm, so this should be possible.
For more details see https://github.com/SchizoDuckie/DuckieTV/wiki/Using-Jackett-with-DuckieTV
