### ISSUE TITLE
back up won't load

### ISSUE THREAD

**Issue by nazza08** [SchizoDuckie/DuckieTV#1105]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...standalone nightly build 20180809

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...nightly build 20180809

**What is your Operating System (Windows, Mac, Linux, Android)**
...Mac

**Describe the problem you are having and steps to reproduce if available**
...all of my tv shows disappeared. So i installed the nightly build and tried to load a previous back up. all that happens is the shows get stuck with a hello circle and don't load. I tried to manually add the shows back but they to get stuck with the yellow circle and don't load. 

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
Try the following:
1. Shutdown your standalone duckietv (or kill it with a task manager)
2. See if you can find the folder `~/Library/Application Support/DuckieTV-Standalone` and either rename it or delete it.
3. Start duckietv, wait a couple of minutes for the app to finish its reset/set up, then import your backup.

**Comment by nazza08** [comment]
Hello 

thanks for helping. I don't have the folder DuckieTV-Standalone in ~/Library/Application Support/

I have uninstalled and reinstalled and still no joy? Strange because it was fine one day and stopped working the next.

**Comment by garfield69** [comment]
Ok. So my notes for the mac are clearly out of date.
Could you start duckietv, then press the key combination of **cmd-alt-i** to open the *development tools* page. Click on the **console** tab and at the `>` prompt, type the following:
`nw.process.env` and press enter.
You may need to click on the little down arrow to expand the results.
If you either take a screendump and paste it here, or copy paste the text so I can take a look. Thanks.
I think the path you want is the **APPDATA** variable.

**Comment by garfield69** [comment]
Oops, that should be **LOCALAPPDATA**. It should have the *duckietv-standalone* folder for the data, which is what we want to  delete.
The *APPDATA* path with the same *dtv* foldername should have the programs, but you don't want  to delete this one.

**Comment by nazza08** [comment]
Hello

Not sure if I have done this properly but when i type nw.process.env nothing shows up. I have included 2 screenshots showing what I see under the console tab. also I can't find the LOCALAPPDATA folder either. I am OS10.13.6. 
![2018-08-13_07-43-42](https://user-images.githubusercontent.com/42233247/44016374-9e1c036a-9ecc-11e8-8ac5-c93496d11315.png)
![2018-08-13_07-43-42 1](https://user-images.githubusercontent.com/42233247/44016377-a0a9dbe8-9ecc-11e8-9e7e-463d7baeb4fb.png)

**Comment by nazza08** [comment]
this is the console text:

DuckieTV quack!






app.js:8400 Registering torrent client: Aria2
app.js:8400 Registering torrent client: BiglyBT
app.js:8400 Registering torrent client: Deluge
app.js:8400 Registering torrent client: qBittorrent (pre3.2)
app.js:8400 Registering torrent client: qBittorrent 3.2+
app.js:8400 Registering torrent client: Ktorrent
app.js:8400 Registering torrent client: rTorrent
app.js:8400 Registering torrent client: Tixati
app.js:8400 Registering torrent client: Transmission
app.js:8400 Registering torrent client: tTorrent
app.js:8400 Registering torrent client: uTorrent Web UI
app.js:8400 Registering torrent client: Vuze
app.js:11054 SettingsService.changeLanguage en_us en_uk
app.js:8330 The next autoBackup is scheduled for Thu Sep 13 2018 17:29:23 GMT+0100 (British Summer Time)
app.js:10550 Fetched SNR name and date exceptions from localStorage.
app.js:10687 Initializing Xross Entity Mapping (http://thexem.de/) service for Scene Name episode format.
app.js:10619 Fetched localstorage Xem series list:  Array(576)
app.js:10621 Fetched localstorage Xem series alias map: Object
app.js:11475 Enabling torrent auto-stop!
app.js:15925 Fetched trackers fall back list from localStorage.
app.js:15716 Updating torrent search engine ThePirateBay
app.js:15716 Updating torrent search engine 1337x
app.js:15716 Updating torrent search engine ETag
app.js:15716 Updating torrent search engine ETTV
app.js:15716 Updating torrent search engine EzTV.ag
app.js:15716 Updating torrent search engine Idope
app.js:15716 Updating torrent search engine IsoHunt2
app.js:15716 Updating torrent search engine KATcr
app.js:15716 Updating torrent search engine LimeTorrents
app.js:15716 Updating torrent search engine Nyaa
app.js:15716 Updating torrent search engine RarBG
app.js:15716 Updating torrent search engine ShowRSS
app.js:15716 Updating torrent search engine TorrentDownloads
app.js:15716 Updating torrent search engine TorrentZ2
app.js:15716 Updating torrent search engine Zooqle
app.js:11194 Register new storage sync target! TraktTVStorageSyncTarget
app.js:18707 TraktTV storage sync target initialized!
app.js:11680 uTorrent Web UI connected!
app.js:11194 Register new storage sync target! ChromeStorageSyncTarget
app.js:18837 ChromeStorageSyncTarget initialized
app.js:9146 Initializing AutoDownload Service!
app.js:18638 Not performing TraktTV update check. Already done within the last 5 hour(s).
deps.js:2373 Possibly unhandled rejection: Could not load fanart
(anonymous) @ deps.js:2373
(anonymous) @ deps.js:2345
g @ deps.js:2385
$digest @ deps.js:2397
$apply @ deps.js:2400
l @ deps.js:2352
completeRequest @ app.js:399
requestLoaded @ app.js:340
load (async)
(anonymous) @ app.js:323
n @ deps.js:2354
(anonymous) @ deps.js:2351
(anonymous) @ deps.js:2386
$digest @ deps.js:2397
(anonymous) @ deps.js:2400
e @ deps.js:2297
(anonymous) @ deps.js:2300
setTimeout (async)
k.defer @ deps.js:2300
$evalAsync @ deps.js:2400
(anonymous) @ deps.js:2384
h @ deps.js:2386
then @ deps.js:2388
p @ deps.js:2351
p.(anonymous function) @ deps.js:2355
promiseRequest @ app.js:18041
trending @ app.js:18176
updateCachedTrending @ app.js:18588
updateFunc @ app.js:18645

**Comment by garfield69** [comment]
Looks like the output from your query is hidden. Try clicking on the *default levels* drop down box to the right of the filter box, and tick (select) the *verbose* option.
Then scroll to the bottom of the console log until you see the `>` prompt and try the `nw.process.env` command again please.

**Comment by nazza08** [comment]
hello
here is what was returned from the nw.process.env.

[nw.process.env.pdf](https://github.com/SchizoDuckie/DuckieTV/files/2284424/nw.process.env.pdf)

**Comment by garfield69** [comment]
Darn. Those environment variables you provided do not appear to show any of the paths I was expecting.
As you can tell, I don't have a mac so I cant do the research myself.
Are you able to use your filemanager to search and list any folders named `DuckieTV-Standalone` ?
I'm expecting to see two, one will have the programs, the other the data.
If you cant find them, then I will have to ask the nwjs support people what the paths are on the mac, as clearly they are quite different that for windows.

**Comment by garfield69** [comment]
#1095 shows the last time someone asked for the data path on  the mac on osx. I dont understand why your mac would be that much different.

**Comment by nazza08** [comment]
Hello unfortunately I can't find a folder named DuckieTV-Standalone. I have attached a screenshot of the items that come up when i search DuckieTV through finder. The first item is the actual application. 
![image](https://user-images.githubusercontent.com/42233247/44114744-fd239f70-a003-11e8-9abf-d5e161160207.png)

**Comment by garfield69** [comment]
@wayneward do you remember #1095 on May 23rd, where you had to find and delete on your mac the 
 duckietv data folder so that you could reset duckietv ?
Another mac user has run into a similar  problem, but is unable to find the folder. I was hoping as a fellow mac user more familiar with the platform than I, that you could  guide @nazza08 in finding and deleting the  `~/Library/Application Support/DuckieTV-Standalone` folder?
Cheers.

**Comment by garfield69** [comment]
@nazza08 does your current logon have administration access? You may need admin access to see the content of the library/application support folder?

**Comment by nazza08** [comment]
Hello. Yes I have administrative rights. 
There is not a DuckieTV-Standalone folder in the application folder

**Comment by nazza08** [comment]
*application support folder

**Comment by garfield69** [comment]
I've posted a question at the nwjs-general google+ group to see if they can help us out.

**Comment by nazza08** [comment]
thanks a lot for helping out

**Comment by garfield69** [comment]
@nazza08  i've started a virtual mac on my windows system and installed the latest DuckieTV nightly.
Then I went looking for the folder you need to delete in order to reset DuckieTV.
and it is at the location that I expected to see. 
However the rub is that you cannot use the *Finder* app to locate it.
1. You need to start a *terminal* from your *launchpad*
![image](https://user-images.githubusercontent.com/6933240/46275517-d18b7780-c5b9-11e8-95ae-b25f38a2f838.png)
2. access the *~/Library/Application Support* folder using `cd "Library/Application Support"`
3. check with the `ls` that the folder *DuckieTV-Standalone* is there
4. delete it with `rm -rf DuckieTV-Standalone`
5. check it is gone `ls`
![image](https://user-images.githubusercontent.com/6933240/46275886-e3214f00-c5ba-11e8-9ade-910e4abc8ab0.png)

The next time you start up DuckieTV it should be reset.

**Comment by nazza08** [comment]
Hello

Sorry the delayed response. Thanks so much for your help that worked a charm!!!!!!


Cheers

On 1 Oct 2018, at 8:46 am, garfield69 <notifications@github.com<mailto:notifications@github.com>> wrote:


@nazza08<https://github.com/nazza08> i've started a virtual mac on my windows system and installed the latest DuckieTV nightly.
Then I went looking for the folder you need to delete in order to reset DuckieTV.
and it is at the location that I expected to see.
However the rub is that you cannot use the Finder app to locate it.

  1.  You need to start a terminal from your launchpad
[image]<https://user-images.githubusercontent.com/6933240/46275517-d18b7780-c5b9-11e8-95ae-b25f38a2f838.png>
  2.  access the ~/Library/Application Support folder using cd "Library/Application Support"
  3.  check with the ls that the folder DuckieTV-Standalone is there
  4.  delete it with rm -rf DuckieTV-Standalone
  5.  check it is gone ls
[image]<https://user-images.githubusercontent.com/6933240/46275886-e3214f00-c5ba-11e8-9ade-910e4abc8ab0.png>

The next time you start up DuckieTV it should be reset.
