### ISSUE TITLE
Question / Request: Linux Repository

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#1113]
Is there a Linux repository for DuckieTV if not could one be set up.

**Comment by garfield69** [comment]
Duckietv is written in javascript using the angularjs framework. This makes it platform independent and therefore there is only the one repository needed.
If you are asking where the linux flavoured standalone packages are, see https://github.com/DuckieTV/Nightlies/releases  or https://github.com/SchizoDuckie/DuckieTV/releases/latest
