### ISSUE TITLE
DuckieTV not showing some torrents in Search

### ISSUE THREAD

**Issue by GrPK** [SchizoDuckie/DuckieTV#1118]
What build of DuckieTV are you using (Standlone)

What version of DuckieTV are you using (Last Nightly)

What is your Operating System (Windows

Describe the problem you are having and steps to reproduce if available

Hello! I use DuckieTV with Jackett. I imported Filelist and Blutopia using Jackett but when I search these 2 for. for example, Hotel Transylvania, it will show only 2 torrents, both 1080p. I selected to show all, but it won't show anything else. Also, while using Filelist, it won't search 1080p torrents which are rodubbed. Using Sonarr/Radarr without this problem, so maybe there is something which I must set-up?
Also, how do I clean install DuckieTV? (I want a fresh start).
Thanks in advance!
Rodubbed= Voice of Romanian actors over original voices (kids party)

![firefox_2018-09-17_23-04-27](https://user-images.githubusercontent.com/31523635/45647349-56f92d00-bace-11e8-8550-06694b5ee6d4.png)
![duckietv_2018-09-17_23-03-48](https://user-images.githubusercontent.com/31523635/45647352-58c2f080-bace-11e8-99dc-d393bdbb9c1c.png)
![firefox_2018-09-17_23-32-03](https://user-images.githubusercontent.com/31523635/45648678-f370fe80-bad1-11e8-83bf-15801f988774.png)
As you can see, IncludeRomanianReleases is selected

Photos to understand my problem

**Comment by garfield69** [comment]
lots of questions :-)

> standalone stable 1.1.5

I would recommend you upgrade to the latest nightly from https://github.com/DuckieTV/Nightlies/releases to pick up the latest fixes and improvements.

>I imported Filelist and Blutopia using Jackett but when I search these 2 for. for example, Hotel Transylvania, it will show only 2 torrents, both 1080p. I selected to show all, but it won't show anything else

difficult to help with this since I don't have logons for either of these private sites to try to recreate the problem.
so what may be helpful is if you could provide the following:
1. take a screen capture of the jackett dashboard of the search results from blutopia of Hotel Transylvania so I can see what is available there.
2. then a screen capture of the duckietv manual search results for the same.
3. and navigate to the duckietv *about* page, (click on the (i) info icon near the bottom left), and scroll down to the *Statistics* section.
4. click on the *statistics* header which will copy the stats to your clipboard.
5. paste the results into a plain text file and drag-drop it here. Don't paste the clipboard directly here because GitHub can sometimes think you are spamming, and lock you out ;-)

>Also, while using Filelist, it won't 1080p torrents which are rodubbed

not sure what you mean. a screen shot of the filelist search on jackett's dashboard would help, followed by one of the duckietv search.

>how to I clean install DuckieTV?  (I want a fresh start)

you can delete the data folder `C:\Users\<username>\AppData\Local\DuckieTV-Standalone` which will blow away your database and settings. the next time you start DuckieTV it will create an empty db and reset the settings to default. (note you will also loose your duckietv jackett definitions).

**Comment by GrPK** [comment]
@garfield69 
[Hopethisfixmyproblem.txt](https://github.com/SchizoDuckie/DuckieTV/files/2390152/Hopethisfixmyproblem.txt)
Also I edited the main text. Hope I made it clear.
Also, same behaviour on Blutopia, showing only a few torrents

**Comment by garfield69** [comment]
well, nothing in the settings appears to slap me in the face, so we will tackle this the old fashion way, with some debug statements via the log. Hopefully it will help me understand a bit better what might be going on.

I took too long to code and test my debug routines, so I missed out on the Nightly Build window for today. But after the build tomorrow, please download that day's Nightly and then prepare the following before conducting a test:
1. press **F12** to open the *Development Tools* page, and click on the **console** tab.
2.  click on the *menu* and select *settings*
![image](https://user-images.githubusercontent.com/6933240/45657777-d7a44180-bb3f-11e8-8912-c9bdf3a7c69e.png)
3. and click on *show timestamps* and close settings.
![image](https://user-images.githubusercontent.com/6933240/45657956-aa0bc800-bb40-11e8-9502-f7cb833e58c8.png)
4. now select *log Levels* and tick *verbose*
![image](https://user-images.githubusercontent.com/6933240/45658060-1b4b7b00-bb41-11e8-9946-c0ff0319dc2f.png)
5. at the console prompt `>` at the bottom of the log, paste the following command and press the *enter* key
`localStorage.setItem('debugSE', 'true')`
6. a response of *undefined* is normal.
![image](https://user-images.githubusercontent.com/6933240/45658185-bf352680-bb41-11e8-90d9-971da4c62c26.png)
7. shutdown and startup DuckieTV to pick up the localstorage setting.
8. perform your manual search for *hotel transylvania* using the *FileList* SE and then visit the console log to look at the results.
9. near the top of the log in a clear place use the *right* mouse button to open a submenu, and select **save as**, and save your log as a text file
![image](https://user-images.githubusercontent.com/6933240/45658373-b8f37a00-bb42-11e8-825f-d15dd0c7629b.png)
10. and drag-drop it here so I can take a look.
11. to turn off the search debugging, use the following command and restart duckietv.
`localStorage.removeItem('debugSE')` 
Cheers.

**Comment by GrPK** [comment]
@garfield69 
[bagblfnohpiddokbpaacecffdboomafe-1537294546399.log](https://github.com/SchizoDuckie/DuckieTV/files/2394036/bagblfnohpiddokbpaacecffdboomafe-1537294546399.log)
After a clean install on both Jackett and DuckieTV, it shows more torrents than the first time. However, when searching Filielist/Jackett, there are near 5 pages of torrents, but in DuckieTV there is, let's say, near one.
Also, writiing Hotel Tra won't bring any search results until I write Hotel T/Hotel Tr or Hotel Transylvania. I will post some screenshots

![duckietv_2018-09-18_21-13-17](https://user-images.githubusercontent.com/31523635/45707838-97b57c80-bb88-11e8-925a-48f00ec6f50c.png)
![duckietv_2018-09-18_21-19-31](https://user-images.githubusercontent.com/31523635/45707839-984e1300-bb88-11e8-8c80-6ff444b9d933.png)
![duckietv_2018-09-18_21-19-40](https://user-images.githubusercontent.com/31523635/45707840-984e1300-bb88-11e8-8a0c-bdf7fed6fb3f.png)
![duckietv_2018-09-18_21-19-46](https://user-images.githubusercontent.com/31523635/45707843-984e1300-bb88-11e8-98f5-60a3dc9db5ca.png)
![duckietv_2018-09-18_21-19-54](https://user-images.githubusercontent.com/31523635/45707844-984e1300-bb88-11e8-9f01-6382a4c883a5.png)
Also, a log error

**Comment by garfield69** [comment]
the nightly build with my debug code has not been published yet, the buildbot schedule s due in about 5 hours or so.

as for the log you have provided so far, the *404 not found* messages from fanart are common, the FanArt site does not always have pictures until art-fans upload them onto the site ;-)
and the *possible unhandled rejection* is common too, not of concern in this case.

BTW, just to be clear, DuckieTV is designed to track **TV** shows.
While you can use the manual search to look for movies, or anything else for that matter, you should know that this is not what DuckieTV is intended for.

So install the Nightly when it comes out and lets see if the debug code I wrote sheds any light on what is going on.
