### ISSUE TITLE
auto download for new show Magnum PI not working

### ISSUE THREAD

**Issue by TimMaietta** [SchizoDuckie/DuckieTV#1119]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
...Windows 7

**Describe the problem you are having and steps to reproduce if available**
... The auto torrent is not working because aparently all the torrents list it as "Magnum P.I." with the periods and the auto search discludes them.
(sorry if this is the wrong forum to ask, i am fairly new.)
**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
this is the right place to ask, thank you for reporting.
I have amended our sceneNameExceptions table ,and your duckietv should fetch the updated table within the next 24 hours, after which it should start finding episodes for magnum.
