### ISSUE TITLE
nightly on chrome store not getting updated

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#1120]
@SchizoDuckie  the nightly for browser extensions have not been updated since 06-sep-2018
the duckietv-builder is happily generating and publishing for all other platforms, and pushing to the nightly github repo.
I suspect a problem with your google store account?
Please investigate.
Thanks.

**Comment by SchizoDuckie** [comment]
Fixed. they wanted a screenshot.

**Comment by Js41637** [comment]
lol

**Comment by garfield69** [comment]
@SchizoDuckie  you fixed the nightly action mode extension, but the new tab extension is still buggered.
do you need to load a screenshot there as well?

**Comment by Js41637** [comment]
rip new tab extension

**Comment by SchizoDuckie** [comment]
done
