### ISSUE TITLE
Auto-Download Service Monitor - torrents sometimes drop from list and are not downloaded...

### ISSUE THREAD

**Issue by Jynx2120** [SchizoDuckie/DuckieTV#1121]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Stable 1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 10 Home

**Describe the problem you are having and steps to reproduce if available**
Torrents that are suppose to download show up in the Auto-Download Service Monitor for a few hours then drop from the list (as in not on the list suddenly) and aren't downloaded. I then need to close DuckieTV and restart it and suddenly the torrents will appear again, and if they are available for download they will start to download if not the torrents will sit on the list and eventually disappear again, then I repeating the process of restarting DuckieTV.

Auto-Download Service Monitor Settings......
Status -active
Min Seeders - 10
Scan Period - 1 day
Other fields - I have nothing in them.
Search Engine - RarBG

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
Hmm. perhaps you should upgrade to the latest DuckieTV Nightly from https://github.com/DuckieTV/Nightlies/releases which has the latest fixes.
Also, this will enable the console logs viewer, which we may need to use to dig deeper if the problem continues.
Also, try adjusting your scan period to 2 days and see if that helps.
I should note that I use duckietv daily and have **never** seen this issue before, so this is puzzling.

**Comment by garfield69** [comment]
also, can you provide a screen capture of the ADSM that shows the list of episodes you are talking about, and one later when the episodes *disappear* from the list.
I wonder if it has to do with the trakt.tv update/refresh cycle, and the particular series that you are following....

**Comment by Jynx2120** [comment]
Hey thanks for the reply, perhaps I will try the nightly release. As for the scan period I have adjusted it a few times already and the same result. In terms of the shows/episodes I'm watching everything is affected, all shows but it's on and off, sometimes there isn't a problem. I have trakt.tv update period set to 12 hours. Maybe I'll get some screenshots but that may take some time but basically the way it looks is they are on the list and waiting for a torrent then I'll check later and the are just gone, torrent that have been downloaded prior are still listed.

**Comment by garfield69** [comment]
From what you are saying it seems likely that the Auto-download server may be crashing while it is using  the rarbg Search Engine. A look at the logs may yield an explanation. And the Nightly may cope better with rarbg than 1.1.5

as a test on 1.1.5, consider switching to an alternate default search engine (if you can find one that works), and see if that makes any difference.

There are more working SE available on the nightly than with 1.1.5, as some SE on 1.1.5 have closed, or changed domains.

**Comment by Jynx2120** [comment]
Thank you garfield69! It was the search engine. Once I changed it shows now stay on the list.

**Comment by garfield69** [comment]
ok that's good news.
I will try to set up a test on my devbox to see if I can replicate your discovery about rarbg.
I may be able to then generate a fix.

**Comment by Jynx2120** [comment]
That would be great! I prefer to use rarbg but for now this will do. Good luck, and if you do find a fix let me know.

**Comment by garfield69** [comment]
I am unable to replicate your results.
I set my dev duckietv to run the ADS ever couple minutes and it scanned and found 11 torrents to check against rarbg and every run successfully got results from rarbg over the space of an hour.

would you be willing to switch back to rarbg and once you get your fault then:
1. press **F12** to open the *Development Tools* page, and click on the **console** tab.
2.  click on the *menu* and select *settings*
![image](https://user-images.githubusercontent.com/6933240/45657777-d7a44180-bb3f-11e8-8912-c9bdf3a7c69e.png)
3. and click on *show timestamps* and close settings.
![image](https://user-images.githubusercontent.com/6933240/45657956-aa0bc800-bb40-11e8-9502-f7cb833e58c8.png)
4. now select *log Levels* and tick *verbose*
![image](https://user-images.githubusercontent.com/6933240/45658060-1b4b7b00-bb41-11e8-9946-c0ff0319dc2f.png)
5. near the top of the log in a clear place use the *right* mouse button to open a submenu, and select **save as**, and save your log as a text file
![image](https://user-images.githubusercontent.com/6933240/45658373-b8f37a00-bb42-11e8-825f-d15dd0c7629b.png)
10. and drag-drop it here so I can take a look.
Thanks.
