### ISSUE TITLE
Add miscellaneous option to disable the resetting of the download flag

### ISSUE THREAD

**Issue by cajeiri** [SchizoDuckie/DuckieTV#1122]
When an episode is marked as downloaded, whether manually or not, if a user decides to download the torrent again for any sort of reason (bugged torrent, better quality becoming available), the download flag is reset and the episode loses its 'downloaded' flag.

A miscellaneous settings option to turn off this behavior would be nice for people that haven't linked DuckieTV to their torrent program.

**Comment by garfield69** [comment]
When the next nightly is published in a couple hours, try this experimental enhancement.
set your duckietv torrent client to **none**.

this dummy torrent client submits your magnets and torrent-url's via the OS interface, and then tells DuckieTV that the torrents have been downloaded (despite what ever is going on in the real world with your torrent host activities).

This should enable all the DuckieTV torrent dependent processes to complete successfully. 

Please report any problems.

**Comment by cajeiri** [comment]
Doing that ends in a multitude of "Torrent finished ... followed by random numbers and letter".

**Comment by garfield69** [comment]
Are you talking about the notifications? you can turn them off since you don't need them. 
Settings > Display > Notifications.
