### ISSUE TITLE
Profile error occured

### ISSUE THREAD

**Issue by Jynx2120** [SchizoDuckie/DuckieTV#1123]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
... Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
... 1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
... Windows 10 Pro

**Describe the problem you are having and steps to reproduce if available**
... Start DuckieTV and get a "Profile error occurred" popup, and in that it says, "Your profile can not be used because it is from a newer version of NW.js. Some features may be unavailable. Please specify a different profile directory or use a newer version of NW.js.". Keeps happening every time Duckie starts up.

This started happening after installing a nightly version then uninstalling that and reinstalling a stable version of Duckie. I'm not sure on how to stop the error.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
is there a particular reason you wanted to go back to using 1.1.5?

the latest nightly has all the latest fixes, new search engines, features,  etc. it is essentially version 1.1.6 before it is officially published.

 when you upgrade forward to a new release, updates to the database and profiles etc are made which are generally not backward compatible.
there is a way to go back, but it is complicated.
so let me know what you want to do, go back to 1.1.5 o stay on the nghtly.

**Comment by Jynx2120** [comment]
Well this particular instance of Duckie is running on a computer that is mostly automated, the reason why I wanted to revert back to version 1.1.5 is because the nightly version would suddenly disappear and Duckie wouldn't run. Since this computer is automated, me having to correct issues with Duckie is unacceptable. I just want something that is low maintenance and version 1.1.5 was doing that for me prior to installing the nightly version. Now I get this profile error. I guess I'll just wait for version 1.1.6. I hope that's soon. Thanks for the reply.

**Comment by garfield69** [comment]
the only reason i can think off for your nightly to dissapear would be if your anti virus is disposing of it because of a false positive hit on the latest nwjs executable... have you checked if this applies to you? AVAST for instance can silently move programs to its virus chest. after checking the file against virustotal.com to confirm its a false hit, you can load an exclusion to prevent a reoccurence.
