### ISSUE TITLE
Database seems wiped after 1.1.5 update - all shows are gone

### ISSUE THREAD

**Issue by clesius1** [SchizoDuckie/DuckieTV#1126]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 10

**Describe the problem you are having and steps to reproduce if available**
After the auto update, all shows and settings are gone

**Attach any DuckieTV statistics or Developer Console logs if available**
Attached
[DuckieStats.txt](https://github.com/SchizoDuckie/DuckieTV/files/2536342/DuckieStats.txt)

**Comment by clesius1** [comment]
Yup settings are definately gone as the uTorrent Web UI config was removed as well.

**Comment by clesius1** [comment]
When trying to add shows it just loops forever

**Comment by garfield69** [comment]
there is no auto-update for the standalone 1.1.5

some other event (clean up tool?) has mangled your working folder at `C:\Users\<username>\AppData\Local\DuckieTV-Standalone`
to recover 
1. shutdown the Duckietv standalone
2. delete that folder
3. startup duckietv
4. import your backup (if you have one) or import from trakt.tv (if you set that up) or start from scratch.

**Comment by clesius1** [comment]
When i first came to my computer, DuckieTV was closed which is already abnormal. So when i started i saw a "DuckieTV was upgraded to 1.1.5 message" on the screen showing the "What's New" and all that good stuff.

I verified everything, no weird thing from antivirus, no quarantine or delete actions, i do not use clean-up tools. Could be that Windows update bug that deletes stuff.

Also had autobackup running however i have no idea where they are or if they were wiped with the rest of the stuff that's been removed. Nothing in the Downloads folder either.

**Comment by garfield69** [comment]
i see.
yes, when duckietv  starts it looks for the environment variable stored in that working folder, and if not there displays the 1.1.5 upgrade popup. 
and if the database version variables are gone then duckietv cant process the db hence the looping data-update cycle.
by completely deleting the working folder you get duckietv to assume a firsrst time install, and it creates all the variables and an empty db to get started properly.
the default location for the backup is usually your downloads folder but of course you can choose a different location and it would have remembered that for the next backup.
try a global search for `*backup*` ?

**Comment by clesius1** [comment]
I did, no luck. I had older backups stashed away. I will restart from those. Thanks for your help!
________________________________
