### ISSUE TITLE
Auto Download suddenly not working

### ISSUE THREAD

**Issue by jamessealey** [SchizoDuckie/DuckieTV#1127]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...v1.1.5 Stable

**What is your Operating System (Windows, Mac, Linux, Android)**
...Windows 10

**Describe the problem you are having and steps to reproduce if available**
...Auto Download not working all of a sudden. Shows that have episodes available, have enough seeders and are available within my timescales are not being added to the queue. They do not appear in the Auto Download Service Monitor.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

I should add I have also tried restoring an earlier Backup, wiping 'all settings', and reinstalling Duckie TV and the problem persists!

The last successful 'auto' download appears to be overnight from Thursday into Friday (see attached screenshots) I can't figure out why Big Bang Theory and Last Man Standing won't download. All previous episodes of these series have downloaded fine.

The only change made to my system is that I uninstalled uTorrent. I had switched to Deluge a while back, but only got round to uninstalling uTorrent last week. Is that connected?

![capture1](https://user-images.githubusercontent.com/44756790/47970686-d643bf80-e080-11e8-9ab4-8fa229763918.PNG)
![capture2](https://user-images.githubusercontent.com/44756790/47970687-d93eb000-e080-11e8-85f7-1856333f2954.PNG)

**Comment by garfield69** [comment]
can you post a screencapture of your ADSM panel ?

**Comment by jamessealey** [comment]
Attached to original post.

**Comment by garfield69** [comment]
it appears that eztv have changed their domain from .ag to .re
3 choices:
1. use one of the other SE (if any of them still work)
2. replace duckietv's eztv with the one from Jackett (see wiki https://github.com/SchizoDuckie/DuckieTV/wiki/Using-Jackett-with-DuckieTV )
3. upgrade to the latest duckietv nightly in about a couple hours, which will have the updated eztv SE address. https://github.com/DuckieTV/Nightlies/releases
