### ISSUE TITLE
Torrents not started on remote Qbittorrent if "Torrent Parameters" enabled

### ISSUE THREAD

**Issue by raf924** [SchizoDuckie/DuckieTV#1129]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Stable 1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows

**Describe the problem you are having and steps to reproduce if available**
The problem I'm having is that even though Duckie TV is connected to my remote QBittorrent client and it can track its downloads and sync their status with the series in my calendar, when I try to start a torrent it tries to download it with my local QBittorrent client instead of my remote one.
While I was writing this, I figured out what caused the issue. In "Torrent Settings" I had "Torrent Parameters" enabled. When I disabled that option, the torrents started on my remote QBittorrent. So, still an issue but a different one than I thought. Unless that's what is supposed to happen ?

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
yeah, the torrent parameters option is a feature only suitable to those requiring manual control of the torrent submission to their local client.
it works by bypassing the duckietv client interface and submitting the torrent via the OS/Chrome browser.
so it will not work for remote clients, and in addition, is not suitable for anyone using the auto-download feature, or wanting duckietv to auto-mark episodes as downloaded when the client has completed task.
