### ISSUE TITLE
BUG: Qbittorrent Not Working

### ISSUE THREAD

**Issue by rebekah65** [SchizoDuckie/DuckieTV#1132]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...Standlone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...nightly-201811120130/DuckieTV-201811120130-ubuntu-x64

**What is your Operating System (Windows, Mac, Linux, Android)**
...Linux

**Describe the problem you are having and steps to reproduce if available**
...when searching I cannot add torrents and magnets to Qbittorrent, although the auto download works.
I am using the newest nightly Qbittorrent via the web ui.

**Attach any DuckieTV statistics or Developer Console logs if available**
![screenshot_1](https://user-images.githubusercontent.com/43880872/48355171-570b4880-e68b-11e8-97bf-fddd0f9f3cf8.jpg)

![screenshot_2](https://user-images.githubusercontent.com/43880872/48355178-5d012980-e68b-11e8-9bcd-ec293c36892e.jpg)

**Comment by garfield69** [comment]
I'm sorry but I cannot replicate your issue.
I started an ubuntu 18 image on my virtualbox,
 loaded qBt 4.1.3 , the latest Jackett and a DuckieTV standalone nightly, set up the YTS indexer on Jackett and connected everything to duckie.
then on duckie i did a manual duckietv search for born-free and clicked on the magnet icons of the YTS search engine results, and duckietv was able to passed them both to the connected qBt without problems.
![virtualbox_ubuntu_13_11_2018_11_20_37](https://user-images.githubusercontent.com/6933240/48379010-942d1480-e737-11e8-823b-082df596080f.png)


whatever the problem it seems related to your linux platform (setup?).
from the first log you posted it seems your system does not recognise the magnet url scheme?
try a google search for ubuntu magnet unknown url scheme` and see if you get anything relevant to your platform.

 if you have the duckietv setting > torrent > torrent parameters option enabled, set it to disabled, to 
prevent confusion while you sort your qBt conection below. having it enabled bypasses the dtv-qBt connection and submits torrents via the OS/chromium interface.

and the second log seems to show 403 forbidden, which suggests that while duckie found an open port on qBt, it may not be authorised to send or receive data to/from qBt.
have you tried using your linux browser to connect to your qBt webui directly, do your get the user/pswd challenge and subsequent qBt torrent panel?

[edit] added parameters sentence.
