### ISSUE TITLE
Cannot restore backup or import from trakt 

### ISSUE THREAD

**Issue by knowair** [SchizoDuckie/DuckieTV#1135]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
... Any!

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
... Either!

**What is your Operating System (Windows, Mac, Linux, Android)**
... Raspbian Stretch on a Raspberry Pi 2

**Describe the problem you are having and steps to reproduce if available**
... not getting past spinny yellow circles for backup restore or trackt import

**Attach any DuckieTV statistics or Developer Console logs if available**
... Please let me know which ones you need (and how to get them!)

I'm Having trouble restoring a backup OR importing a trakt account with either the New Tab or Browser action 1.1.5 OR Nightly! I'm using the default Chromium on a fresh Raspbian stretch install on a pi2 -  The standalone doesn't load (maybe because it's arm not x86??)

If i use it by adding the shows manually it works perfectly and all other aspects seem fine, i've certainly not encountered any other problems.

The backup file is accepted and the trakt account is linked but in either case after the shows are imported they never move past the spinning yellow circle "pending" phase, the page then freezes and it just sits there until chrome pops up and offers to kill the "unresponsive" page.

I've tried surpressing the chrome kill page warning pop up to let it run and left it over night just in case it was just slow but it never comes back to life even after hours and hours!

i've tested different backup file(s) created on android and windows 10, restoring them to each other and they work just fine. 

I've also wiped duckie and re-connected trakt and imported my account data on android and windows and it works fine too.

I've been here before on a different ticket, but that was resolved by giving it more time... 

unfortunately i suspect it's just that there are too many shows being pulled in from Trakt. and the pi doesn't have the juice to handle it...

please let me know what you think because I am now stuck!!

[ikhklcamhmfmjbhckdjoabiepglbhaid-1544628631893.log](https://github.com/SchizoDuckie/DuckieTV/files/2672521/ikhklcamhmfmjbhckdjoabiepglbhaid-1544628631893.log)

**Comment by garfield69** [comment]
yeah, the log ends with the message that 312 series were found  in the collection, and 360 series found in the watched records, (most of the former will probably be duplicates in the latter). Still, that is a lot of shows and episodes (which will probably be in the 10k range) to process.

so if you are able to manually add series from scratch, but the import hangs, then it would appear that the import of so many series (and related episodes)  at one time is consuming too much resources for your rasp to handle.

do you have a resource monitor/task manager you can  activate that measures cpu, memory, network, etc  usage? 
Alternatively, I think chrome has a internal processes monitor you can access from the menu someplace that shows each chrome task resources usage.
i suspect you may be running out of memory. The monitor may highlight the shortage.

it may be possible to split your duckietv.backup file into two or three parts.
so you could do several imports in smaller doses. Each import adds to what is already there, unless you explicidly turn on the pre-clear switch.
so if you post the file to the cloud and supply a share link, or zip it and drag/drop here, i can try building a three part backup set of say 100 series in each.

**Comment by knowair** [comment]
no worries G, i can split up the backup file, great idea thanks.

though... if i do that and import smaller backups, will the "update all" or the "data refresh" ever work properly??

thanks again for all your help

**Comment by garfield69** [comment]
>i can split up the backup file, great idea thanks.

* The backup format is a simple JSON file that has the following structure:
 ```
*
 * {
 * "settings": {
 *   // serialized settings
 * },
 * "series": {
 *  <SHOW_TVDB_ID> : [ // array of objects
 *      {
 *          "displaycalendar": 1||0,
 *          "autoDownload": 1||0,
 *          "customSearchString": <string>||null,
 *          "ignoreGlobalQuality": 1||0,
 *          "ignoreGlobalIncludes": 1||0,
 *          "ignoreGlobalExcludes": 1||0,
 *          "searchProvider": <string>||null,
 *          "ignoreHideSpecials": 1||0,
 *          "customSearchSizeMin": <integer>||null,
 *          "customSearchSizeMax": <integer>||null,
 *          "dlPath": <string>||null,
 *          "customDelay": <integer>||null,
 *          "alias": <string>||null,
 *          "customFormat": <string>||null,
 *      },
 *      {
 *          "TVDB_ID": <Episode_TVDB_ID>,
 *          "watchedAt": <timestamp watchedAt>||null,
 *          "downloaded": 1
 *      },
 *      // repeat
 *    ],
 *    // repeat
 *  }
 */
```
>if i do that and import smaller backups, will the "update all" or the "data refresh" ever work properly??

the import will populate your database by fetching from trak.tv the latest series and episode records. then the  import  overlays those records with any info from the backup that have matching trakt.tv ids, so thats the downloaded and watched status, and other user generted series and episode settings.
you do not need to perform a refresh-all afterwards.

**Comment by knowair** [comment]
Thanks, I needed to break it down 6 times! 
 
Thinking of the future,  I can't be the only one with "collections" and Trakt history getting ever more un-weildy as time goes on!! 

Have you thought of having an option for to restrict the amount needed to import, therefore NOT importing the whole history of every single show!

for example you could have an option in the trakt import settings to do a "Active shows Only" sync, where Duckie would get shows from the api equivalent of the "Up Next" section 

i.e. get the shows from    / Calendar / My Shows

rather than from    / Shows / Watched   or   / Shows / Collected

just a thought!

Thanks again for your help, keep up the great work!

**Comment by garfield69** [comment]
nah, you're the first, and if your rasp has more memory you'd probably be fine. I tested  duckietv on a samsung tablet with 4GB memory and imported 284 series without problems.
