### ISSUE TITLE
[req] make downloaded sync trakt collection optional

### ISSUE THREAD

**Issue by Sunabubus** [SchizoDuckie/DuckieTV#1136]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Nightly 20181205130 

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows10

**Describe the problem you are having and steps to reproduce if available**
I've noticed that sometimes when I log in to trakt I have - seemingly - random episodes and shows in my collection. Last week I purged everything out, and now I have shows there that I haven't even marked as watched yet. First I thought it's the "mark as watched feature" acting up, but now seeing my unwatched episodes in my collection, I'm not sure.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by Sunabubus** [comment]
Just checked the trakt options in duckietv, and it has the trakt tv sync option, which reads "duckietv can automatically push your downloaded and watched episodes to trakt.tv now that you're authenticated." 

Does this mean "downloaded" in duckie = "collected" in trakt? It wasn't like this before, all my old (~6 months +) shows are just watched. Hm. Maybe if so, could we get own options for them?

**Comment by garfield69** [comment]
Yes, DuckieTV pre 1.1.5 only sync'd the watched flag with Trakt.tv's watched history state.
Then DuckieTV 1.1.5 in Aug 2017 introduced syncs of the DuckieTV downloaded flag with the Trakt.tv collected state, which completes the downloaded/watched pairing. 
If your DuckieTV favourites was started before 1.1.5 then your Trakt.TV collection would be missing the earlier episodes.

If you really needed to, I suppose you could use the DuckieTV settings > Trakt.TV > push to Trakt.TV , which would send all your favourites episodes current DuckieTV states to Trakt.TV and should bring your Trakt.TV collection up to date.

**Comment by Sunabubus** [comment]
Well the problem is, I prefer duckietv not adding anything I download to my collection on its own. Watching something on tv doesn't mean I own it. Or that I would want to own everything I downloaded in my life.

**Comment by garfield69** [comment]
ok, so we turn this  into an enhancement request to make the collection sync optional.

**Comment by Sunabubus** [comment]
thanks!

**Comment by garfield69** [comment]
https://github.com/DuckieTV/Nightlies/releases/tag/nightly-202308122012
