### ISSUE TITLE
Tidy up stuff

### ISSUE THREAD

**Issue by Js41637** [SchizoDuckie/DuckieTV#1137]
Making an issue so we can better track this.

I've made a lot of changes recently to the code style. I updated our ESLint configuration to be a lot stricter so that there can be a mostly consistent code style throughout the app. At the moment it's kind of all over the place.

I updated the eslint configuration then ran eslint over all the Javascript files and had it fix all the small things that i can (over 15,000 changes) and I've been going over all the files as well to fix some things it can't fix as as well as do some general tidying such as adding some white space in large functions and removing 'dependencies' from controllers/services that aren't used.

It's not ideal because it kind of ruins our git history a little bit but, I think it'll be worth it.

I've been testing as i go and haven't run into any actual errors yet, 99% of the changes are just code style only so theoretically there should be no issues but I obviously can't test everything such as every torrent client, search engine, etc.

So put any issues you might find in this issue?

**Comment by Js41637** [comment]
Latest nightly has also just built with all the changes as well and so far so good for me.

@garfield69 just makin sure you see this issue.

**Comment by garfield69** [comment]
### testing: 
#### torrent clients:
- [x] aria2
- [x] biglybt
- [x] deluge
- [ ] ~~ktorrent~~ v5 has no webui plugin, v4 wont install on my ubuntu 18
- [x] tixati
- [x] transmission
- [x] vuze
- [x] qBt
- [x] rtorrent
- [x] ttorrent
- [x] utorrent api
- [x] utorrent webui
#### Search Engines
- [x] (the manual multi SE search panel invokes them all)
