### ISSUE TITLE
Switch to using TMDB for images instead of Fanart.tv and improve image loading

### ISSUE THREAD

**Issue by Js41637** [SchizoDuckie/DuckieTV#1140]
DuckieTV currently uses Fanart.tv for it's artwork which quite frankly is absolutely terrible. They lack artwork for so many shows and in general their API is terrible.

TMDB has a much higher quality range of posters and are almost guaranteed to have a poster in 99% of cases unlike Fanart.tv.

I think something is also broken in DuckieTV where it is not loading images correctly, 60% of my shows in DuckieTV constantly have no posters and when adding shows hardly any posters load making it very hard to tell what a show is.

TMDB has a very simple to use API, the only restriction they have is 40 requests every 10 seconds which we could easily exceed if loading a heap of results for trending or searching but this is nothing some smart queue management would solve. The restriction is per IP not API key.

**Comment by Js41637** [comment]
I plan on looking into this soon, dunno if i'll implement it or not though.

**Comment by Js41637** [comment]
TMDB no longer has any rate limits which will make this a lot easier. I will look into it soon.

**Comment by Js41637** [comment]
I improved how images are loading so it ideally no longer makes requests for every image at once, now it'll only load images that are in view which should improve things if you have a large amount of series. Does require some testing though to make sure everything still works. It seemed alright for me but, i only tested the favorites stuff mainly and I just tested the adding series page which did have some issues, i had to disable the poster transitions as it makes it too hard to load the images properly and the stuff isnt really needed on that page anyway.

**Comment by garfield69** [comment]
Hmm. There are times when the favourites posters will not load, seeing lots of spinning posters on the first page
![image](https://user-images.githubusercontent.com/6933240/99198518-ff65c180-27fd-11eb-8acf-c36a27eba5ae.png)
But as soon as I started scrolling down past the first 4 rows, the rest loaded and going backup to the top the first 4 rows started loading too. 
Its intermittent, and most time it works, but while going in and out of the favourites, and doing other activity like viewing trending, or side panels, when I go back to the favourites, it will get stuck like the image above.
But only if I'm at the top of the favourites, and only occasionally. So maybe not a big deal.

**Comment by garfield69** [comment]
The latest personal builds for anyone interested in trying this out can be found at https://github.com/SchizoDuckie/DuckieTV/issues/1273#issuecomment-720350100

**Comment by ilike2burnthing** [comment]
> Hmm. There are times when the favourites posters will not load, seeing lots of spinning posters on the first page
> But as soon as I started scrolling down past the first 4 rows, the rest loaded and going backup to the top the first 4 rows started loading too.

ditto

**Comment by Js41637** [comment]
Weird, I assume this is using the standalone versions? I only tested in Chrome and it seems to work fine...

I don't remember but how can you dev on the standalone versions? Is there an easy way to run nw.js from source?

**Comment by garfield69** [comment]
@Js41637 https://github.com/SchizoDuckie/DuckieTV/wiki/How-to-Install-a-Development-version-of-the-Windows-DuckieTV-Standalone-SOURCE

**Comment by garfield69** [comment]
I get instances of the loading of poster failing on my chrome extensions too, mostly when I am scrolling down faster that then posters that are being updated, a point at which they all fail for that segment.
![image](https://user-images.githubusercontent.com/6933240/99889033-73004680-2cb6-11eb-93ab-45f19e3a1294.png)

its possible that the zoom level has an impact on this, may get more miss-shits when at 80% than at 120% for instance?

**Comment by garfield69** [comment]
@Js41637  Had a user on Reddit that was on the latest Nightly on a Mac and noticed High CPU and GPU.
Found that the dtv > settings > display > sexy poster transitions was disabled.
Performance improved when enabled.
Do you think we should force everyone on enabled and drop that option on the settings?
We could leave the switch in the user-preferences, but just hide that part of the settings panel, in case we want to restore it at a later time.

**Comment by Js41637** [comment]
I'm just going to revert for now, might look into again later.

**Comment by Js41637** [comment]
Dun

**Comment by Js41637** [comment]
I have refactored all the image loading to use TMDB which lets us get show, season and episode images once again.

The changes I made does not migrate any existing data, theoretically nothing should immeidately change! In order to get new images you either have to wait for the show to update, manually refresh the show, or create a back up and then restore it. 
[edit] OR Dtv>Settings>Backup>Refresh all series>Refresh all Series now
The images on the Trending page will also not update until the trending data updates unless it never had an image.

It basically works the same as the original fanart code I think? Basically there is a FanartService that will get the images for a show from TMDB and will cache it in a table so it won't fetch the images again. TMDB also returns season images when you fetch a show so it also caches those as well. 

Adding a show will use whatever images it has already loaded from when you viewed the trending page or searched for it. If no images exist (for some reason) it will request them.
When adding seasons it will use the cached images that were added when you got the show images
When adding episodes it it gets images for all episodes in a season at once. Episodes are added by iterating over each season you only need a single request to get all episode images for a season.

Previously, images for the trakt.tv trending were fetched as the data was loaded and then cached in the trending json, I removed this logic as it is not needed. When displaying the trending results, the serieHeader will attempt to load the image of any serie that doesn't have a poster stored which will always be true when viewing trending results or searching.
Its also possible some of your added favorites might not have a poster set in which case it will also attempt to fetch them from TMDB but it does not update any serie data.
Because the images requested from TMDB are cached in the fanart table, any series without a poster (from trending or favorites) will only require loading once and then will use the cache going forward. Any 404s are also cached so theoretically images for a TMDB show are only ever going to be fetched once.

Cached image data for a show and season is only updated if you manually refresh the show, if there is a trakt.tv update for the show or if you import a backup. No episode image data is cached in the Fanart table so images for episodes will always be updated/fetched whenever the show updates.

I did a decent amount of testing, should be fine. Didn't test standalone though.

Thoughts @garfield69

**Comment by garfield69** [comment]
Wow!
Monumental effort.

I can build a standalone Nightly set, but leave it in draft and you (and I) can use it for a bit first. 
Then once you declare yourself content I can publish.
How does that sound?

**Comment by Js41637** [comment]
Sure ok. Btw would you be interested in adding me on Discord?

**Comment by garfield69** [comment]
Sorry, I don't use discord for anything. Don't have an account, never been interested in participating in online chat forums.

**Comment by garfield69** [comment]
https://github.com/DuckieTV/Nightlies/releases/tag/untagged-7b54909bc2c5b3e33f96

**Comment by garfield69** [comment]
what does the trash icon next to the fanart and tmdbart stats do?

**Comment by garfield69** [comment]
LGTM. ready to publish on your word ;-)

**Comment by Js41637** [comment]
> what does the trash icon next to the fanart and tmdbart stats do?

Just kind of added it for testing, just clears the fanart caches from the DB, figured might as well keep it, they're onyl ever going to get bigger and a bit worse now because getting show images also stores season images so it'll get pretty big after a while. Deleting the cache is fine, it'll just refetch anything as needed again.

> LGTM. ready to publish on your word ;-)

Thanks, I only use the chrome new tab version from source directly so uh there's nothing to do on that front. I guess you manually publish the builds now? Not really sure what the current state of things is, I remember something about builds and stuff not working?

> Discord

Fair enough, just wanted to see if we could chat about some dtv stuff but it's fine.

**Comment by garfield69** [comment]
> just wanted to see if we could chat about some dtv stuff

I've tried setting up a discussion area for maintainers, https://github.com/orgs/DuckieTV/discussions
