### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by phd21** [SchizoDuckie/DuckieTV#1142]
Hi SchizoDuckie,

I just wanted to say Thank You for this excellent application. 

I help out on the Linux Mint forums and one of the people there was using this. So, I decided to try it out. As an ex-software developer (programmer) who also watches TV, it takes a lot to impress me. But, I am impressed very well done.

Best regards,
Phil (phd21)

**Comment by garfield69** [comment]
Cheers.
