### ISSUE TITLE
Schedule seems slightly buggy Label: Bug

### ISSUE THREAD

**Issue by sjrandel** [SchizoDuckie/DuckieTV#1144]
In the chrome new tab version being used on windows 8 PC recently Victoria was in my schedule as appropriate, then it was reverted to next air date unknown. Why is that? it did in fact start on January 13th as it originally showed.  This is quite irksome as it suggests an issue regarding how start dates of series are being tracked. I would Recommend checking the coding therein or changing the source point for this information. Also it would be really great if there was the capability to disable specials show by show as opposed to across the board :)

An example of that would be that the series signed sealed delivered has been split into two categories. the movies are considered to be specials rather than episodes in the series. So if I have all specials disabled i can't re-enable them currently just for that one show.

**Comment by garfield69** [comment]
DuckieTV gets all its data from Trakt.tv and the accuracy of the information is out of our control.
see https://github.com/SchizoDuckie/DuckieTV/wiki/How-to-make-corrections-to-shows-on-DuckieTV for in depth details.

you can disable/enable specials by individual series by visiting the series details panel, and clicking on its settings button. you will find a *display specials on the calendar* check box.

**Comment by sjrandel** [comment]
I assure you in the version I am using there is not an option to make that
change for each series individually. But thank you for the information
regarding who is responsible for the airdates.


*Thank you,*

*~~Sara Randel~~*

**Comment by sjrandel** [comment]
Apparently I'm using browser action and not new tab.


*Thank you,*

*~~Sara Randel~~*

**Comment by garfield69** [comment]
you might like to upgrade to the latest DTV nightly from https://github.com/DuckieTV/Nightlies/releases
which has the latest features and fixes.
I would recommend the standalone version, but the browser extensions flavours are available as well. https://chrome.google.com/webstore/detail/duckietv-browser-action-m/ikhklcamhmfmjbhckdjoabiepglbhaid
