### ISSUE TITLE
Shows missing from calendar

### ISSUE THREAD

**Issue by janat08** [SchizoDuckie/DuckieTV#1145]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...stable

**What is your Operating System (Windows, Mac, Linux, Android)**
...linux

**Describe the problem you are having and steps to reproduce if available**
...adding victoria to shows won't have it show up in calendar (its running now)

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
Are you talking about victoria 2016 https://www.thetvdb.com/series/victoria/seasons/3 ?
DuckieTV gets all its data from trakt.tv and the accuracy of the show details is out of our control.
See https://github.com/SchizoDuckie/DuckieTV/wiki/How-to-make-corrections-to-shows-on-DuckieTV for more details.

**Comment by janat08** [comment]
Have you considered rarbg, as I imagine the DB is constantly updated by release groups? showrss.info uses that and some other DBs.

**Comment by garfield69** [comment]
Are you are confusing torrent sites (rarbg, showrRSS, zooqle, all of which dtv use as torrent search engines)  with show episode info sites , such as trakt.tv, thetvdb, tmdb, etc.which provide series, season and episode info, such as broadcast date, descriptions, etc?

**Comment by janat08** [comment]
RARBG (thanks!), ETTV, VTV and TvTeam
Is what they use, and victoria shows up on upcoming calendar.
