### ISSUE TITLE
Minimal version/daemon for autodownloads

### ISSUE THREAD

**Issue by janat08** [SchizoDuckie/DuckieTV#1146]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...stadalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
... stable

**What is your Operating System (Windows, Mac, Linux, Android)**
...linux

**Describe the problem you are having and steps to reproduce if available**
...cut down version that handles autodownloads since the client eats half a gig of ram on linux.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
SORRY, Nope.
 Dtv is written in angularjs as a chrome extension.
The standalone dtv uses nwjs run  time environment to allow the same angularjs code to run apart from the chrome browser.
There is no plans to develop any unique flavors of dtv for specific tasks or in different languages.
There just isn't enough time, developers or interest for such a project.
