### ISSUE TITLE
DuckieTV Stand alone stuck and won't display or add favourite shows / MacOS

### ISSUE THREAD

**Issue by lehcim1973** [SchizoDuckie/DuckieTV#1147]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Stand Alone
**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Nightly v201901200130 but problem occured when I was using an older version

**What is your Operating System (Windows, Mac, Linux, Android)**
Mac 10.14.2

**Describe the problem you are having and steps to reproduce if available**
all shows that I had previously added as favourite disappeared - this occurred when I tried to add a new show. I cannot seem to be able to add a new show anymore, I just have the yellow dot zooming in and out when I click on a new show when I am trying to add it as a favourite - nothing happens after that. I tried to uninstall / reinstall, delete settings, import a backup, nothing happens and no show appear on the calendar.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

Statistics
DuckieTV Web Based	201901200130
Current Date and Time	Tue, 22 Jan 2019 19:30:39 GMT
NWJS, Chromium	0.35.1 , 71.0.3578.80
UserAgent	DuckieTV-Standalone Nightly v201901200130 Macintosh; Intel Mac OS X 10_14_2
Platform, Vendor	MacIntel, Google Inc.
Screen (width x height)	2560 x 1440
Default Search Engine	Zooqle (Enabled)
Default Torrent Client	uTorrent Web UI (Enabled but Not Connected to Host)
Auto Download Service	(Disabled)
Last checked TraktTV for DB updates on	Tue, 22 Jan 2019 18:54:08 GMT
User Preferences on Local Storage	
{  "ThePirateBay.mirror": "https://thepiratebay.org",
  "application.language": "en_us",
  "application.locale": "en_us",
  "autobackup.period": "monthly",
  "autodownload.delay": 15,
  "autodownload.multiSE": {
    "ThePirateBay": true,
    "1337x": true,
    "IsoHunt": true,
    "KATcr": true,
    "Nyaa": true,
    "RarBG": true,
    "ShowRSS": true,
    "TorrentDownloads": true,
    "TorrentZ2": true,
    "Zooqle": true,
    "ETag": true,
    "ETTV": true,
    "EzTV.ag": true,
    "IdopeClone": true,
    "IsoHunt2": true,
    "LimeTorrents": true,
    "TGx": true
  },
  "autodownload.multiSE.enabled": false,
  "autodownload.period": 1,
  "background-rotator.opacity": 0.4,
  "calendar.mode": "date",
  "calendar.show-downloaded": true,
  "calendar.show-episode-numbers": false,
  "calendar.show-specials": true,
  "calendar.startSunday": true,
  "client.determinedlocale": "en_uk",
  "download.ratings": true,
  "episode.watched-downloaded.pairing": true,
  "font.bebas.enabled": true,
  "kc.always": false,
  "lastSync": -1,
  "library.order.by": "getSortName()",
  "library.order.reverseList": [
    true,
    false,
    true,
    true
  ],
  "library.seriesgrid": true,
  "library.smallposters": true,
  "main.viewmode": "calendar",
  "notifications.enabled": true,
  "series.displaymode": "poster",
  "series.not-watched-eps-btn": false,
  "storage.sync": false,
  "subtitles.languages": [
    "eng"
  ],
  "sync.progress": true,
  "synology.enabled": false,
  "synology.ip": "192.168.x.x",
  "synology.password": "*****",
  "synology.playback_devices": {},
  "synology.port": 5000,
  "synology.protocol": "http",
  "synology.username": "admin",
  "topSites.enabled": false,
  "topSites.mode": "onhover",
  "torrentDialog.2.activeSE": {
    "ThePirateBay": true,
    "1337x": true,
    "IsoHunt": true,
    "KATcr": true,
    "Nyaa": true,
    "RarBG": true,
    "ShowRSS": true,
    "TorrentDownloads": true,
    "TorrentZ2": true,
    "Zooqle": true
  },
  "torrentDialog.2.enabled": false,
  "torrentDialog.2.sortBy": "+engine",
  "torrentDialog.showAdvanced.enabled": true,
  "torrenting.autodownload": false,
  "torrenting.autostop": true,
  "torrenting.autostop_all": false,
  "torrenting.client": "uTorrent Web UI",
  "torrenting.directory": true,
  "torrenting.enabled": true,
  "torrenting.global_size_max": null,
  "torrenting.global_size_max_enabled": true,
  "torrenting.global_size_min": null,
  "torrenting.global_size_min_enabled": true,
  "torrenting.ignore_keywords": "",
  "torrenting.ignore_keywords_enabled": true,
  "torrenting.label": false,
  "torrenting.launch_via_chromium": false,
  "torrenting.min_seeders": 50,
  "torrenting.min_seeders_enabled": false,
  "torrenting.progress": true,
  "torrenting.require_keywords": "",
  "torrenting.require_keywords_enabled": true,
  "torrenting.require_keywords_mode_or": true,
  "torrenting.searchprovider": "Zooqle",
  "torrenting.searchquality": "",
  "torrenting.searchqualitylist": [
    "480p",
    "HDTV",
    "720p",
    "1080p",
    "2160p"
  ],
  "torrenting.streaming": true,
  "trakt-update.period": 12,
  "trakttv.passwordHash": "*****",
  "trakttv.sync": false,
  "trakttv.username": null,
  "ttorrent.password": "*****",
  "ttorrent.port": 1080,
  "ttorrent.server": "http://localhost",
  "ttorrent.use_auth": true,
  "ttorrent.username": "admin",
  "utorrentwebui.password": "*****",
  "utorrentwebui.port": 8080,
  "utorrentwebui.server": "http://localhost",
  "utorrentwebui.use_auth": true,
  "utorrentwebui.username": "michel"
}
Other significant Local Storage keys	
{
  "1.1.5FetchFirstXemAliasMap": "Mon Jan 21 2019 23:05:59 GMT+0100 (Central European Standard Time)",
  "1.1.6deleteWatchList": "Mon Jan 21 2019 23:05:59 GMT+0100 (Central European Standard Time)",
  "autobackup.lastrun": "1548108359147",
  "database.version.Jackett": "2",
  "database.version.Seasons": "6",
  "fanart.bootstrapped": "1",
  "github.lastupdatecheck": "1548108360786",
  "optin_error_reporting": "true",
  "optin_error_reporting.start_time": "1548183414607",
  "snr.lastFetched": "1548108360961",
  "standalone.position": "{\"width\":1000,\"height\":750,\"x\":780,\"y\":172,\"state\":\"normal\"}",
  "standalone.zoomlevel": "6",
  "torrenting.client": "uTorrent Web UI",
  "trackers.lastFetched": "1548108360747",
  "trakttv.lastupdated": "1548183248487",
  "trakttv.lastupdated.trending": "0",
  "uniqueId": "1ef25b3e-f45b-f5f9-19e4-3afb22d630db",
  "xem.lastFetched": "1548108360954"
}
DB Series	0
DB Series Hidden From Calendar	0
DB Seasons	0
DB Episodes	0
DB Fanart	8513
DB Jackett	0
Opt-In error Tracking
If you have a problem with DuckieTV, we can ask you to enable this functionality temporarily and repeat the scenario that lead to your error. This will help us get to the core of your problems more easily. Please don't enable this unless asked to. We don't want your data!

When you do enable this functionality, please report the Unique Tracking ID to us so we can find your error logs.

current setting: Enabled

Unique tracking id: 1ef25b3e-f45b-f5f9-19e4-3afb22d630db

Opt-In error Tracking
Writing to db

**Comment by garfield69** [comment]
urg. seen this before. 
some process (mac osx security update, app cleaner, malware protector) has nobbled your duckietv data folder, and you will need to delete it so that you can start dtv afresh.

1. You need to start a *terminal* from your *launchpad*
![image](https://user-images.githubusercontent.com/6933240/46275517-d18b7780-c5b9-11e8-95ae-b25f38a2f838.png)
2. access the *~/Library/Application Support* folder using `cd "Library/Application Support"`
3. check with the `ls` that the folder *DuckieTV-Standalone* is there
4. delete it with `rm -rf DuckieTV-Standalone`
5. check it is gone `ls`
![image](https://user-images.githubusercontent.com/6933240/46275886-e3214f00-c5ba-11e8-9ade-910e4abc8ab0.png)

The next time you start up DuckieTV it should be reset.

let me know how you go.

**Comment by lehcim1973** [comment]
Hello Garfield

Thank you so much for your help, it worked !

Have a great day
