### ISSUE TITLE
Nightly Release building broken?

### ISSUE THREAD

**Issue by JourneyOver** [SchizoDuckie/DuckieTV#1148]
*not following template due to it not being a duckietv issue

Completely forgot how I got in contact with you last time about this since it's been a good while, but I think your builder for the nightly releases is broken again. Hasn't been a release in the nightly repo, for a couple days now. Just thought I'd let ya know about it, unless you of course manually disabled nightly builds?

**Comment by garfield69** [comment]
we are aware of this thanks.
the build bot server has limited disk space, but it does have a clean up step which kicks in once a week so we will wait and see if it resumes.

**Comment by JourneyOver** [comment]
not a problem and got it haha, didn't know if it was like last time where the bot just decided to break or what had happened xD

not a big deal by any means either way, just mainly was wanting to test if my updater script (https://github.com/JourneyOver/chocolatey-packages/tree/master/automatic/duckietv) was going to be working correctly or not when a new release came out (and the changelog information had been changed or not) so was just waiting on some new releases to come xD

**Comment by garfield69** [comment]
Nightly bot  built successfully just now,

**Comment by JourneyOver** [comment]
Great :D I at least know so far that it's not going to push any updates to chocolatey if nothing has actually changed between nightly releases. Now to wait for an actual change to happen and see if it'll push that up or not.

**Comment by garfield69** [comment]
If your script is working you should have fetched an update today.

**Comment by JourneyOver** [comment]
@garfield69 yep, looks like my updated update script for the choco package is working perfectly :) ignored all updates that was the same as the last release I did and then since the changelog thing changed for todays release, it seen it as an actual update and grabbed it up and pushed it on up to chocolatey ^^
