### ISSUE TITLE
Mac download link does nothing but move the page, Windows and Linux download fine

### ISSUE THREAD

**Issue by recoi1er** [SchizoDuckie/DuckieTV#1149]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
... trying to get the current build on fresh Mac install

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
... none...trying to download it

**What is your Operating System (Windows, Mac, Linux, Android)**
... Mac

**Describe the problem you are having and steps to reproduce if available**
... go to https://schizoduckie.github.io/DuckieTV/ on a browser and try to download the Mac version, the page moves but nothing happens. Windows and Linux download as intended

**Attach any DuckieTV statistics or Developer Console logs if available**
... need to be able to download it first

**Comment by Js41637** [comment]
Works for me.

**Comment by recoi1er** [comment]
It doesn't for me on Safari, Firefox and Chrome. Can you please post the download link here so I can get downloaded and going again?

**Comment by Js41637** [comment]
All the releases are on Github. https://github.com/SchizoDuckie/DuckieTV/releases

**Comment by recoi1er** [comment]
Perfect thank you

**Comment by Js41637** [comment]
Are you on a 32bit mac? There is only a 64bit mac download, if you were on 32bit the download link for mac wouldn't work because it doesn't check if one actually exists.

**Comment by recoi1er** [comment]
Oh no its 64bit, been 64bit for many many years now.

Come to think of it, this happened to me the first time I tried to get this app before (like 5-6 months ago) and I must have found the releases section but forgot about it.

**Comment by garfield69** [comment]
fixed with https://github.com/SchizoDuckie/DuckieTV/commit/95370f56ee995d9cd6ce8607caa0e3e0f9f6891b
