### ISSUE TITLE
Autodownload and search not finding available torrents

### ISSUE THREAD

**Issue by lonelyfairie** [SchizoDuckie/DuckieTV#1151]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone
**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Nightly release for 01-02-2019

**What is your Operating System (Windows, Mac, Linux, Android)**
Mac

**Describe the problem you are having and steps to reproduce if available**
Autodownloads not working and manual search isn't either for some torrents
**Attach any DuckieTV statistics or Developer Console logs if available**

Since a couple of weeks I noticed some shows didn't autodownload, manual search would find correct versions of the show for some cases others I had to download directly from rarbg or 1337x website. 

Example: 
- Gordon Ramsays 24 Hours to Hell and Back S02E05
Show aired on the 29th, hasn't auto download as of Friday midday , default search engine was set to rarbg, changed it to 1337x still no auto download, manual search with no quality selected and multiple torrent sites returns nothing.

Manual web search returns that both 1337x and rarbg have torrents with ample seeds posted as of the 30th in the preferred 720p quality, web and 1080p as well. 

https://rarbggo.org/torrent/v9hdfz7
http://www.1337x.one/torrent/3558631/Gordon-Ramsays-24-Hours-to-Hell-and-Back-S02E05-720p-WEB-x264-TBS-eztv/

I am using this show as my example as it is the one I noticed today, due to lack of time for reporting I have been doing this for other shows as well like Hell's Kitchen for about 2/3 weeks at least.

**Comment by dzogas** [comment]
I have the same problem with manual search but with all the shows I have in my favourites, not only in rarbg and 1337x but with all sites....

**Comment by garfield69** [comment]
RarBG provides an API service at https://torrentapi.org/ for apps to fetch search results. (The RarBG.to web site actively prevents apps web scraping the site).

The RARBG API server appears to have no new results since the start of Feb 01.

I can get search results for episodes prior to this date (Arrow s07e11, Black Lightning s02e11, Magnum P I s01e14) but not for (The Flash s05e12, Riverdale s03e11, The Magicians s04e02, Vikings s05e20) although I can get previous episodes (The Flash s05e11, Riverdale s03e10, The Magicians s04e01, Vikings s05e19)

Nothing to do but wait to see if it gets fixed. In the mean time you can try switching to another DuckieTV search engine.

I've sent an email to support@rarbg.to but I dont know if this will get a response.

**Comment by garfield69** [comment]
@dzogas  please open a separate ticket so we can track and resolve your issue individually. your problem is not similar to lonelyfairie and sharing the ticket complicates things. thanks.

**Comment by garfield69** [comment]
@lonelyfairie  support@rarbg.to have responded and solved the issue, your DuckieTV RarBG searches should be back to normal now.

You may need to restart DuckieTV to ensure any caching is flushed.

**Comment by lonelyfairie** [comment]
I restarted duckie, still having the same issue, this time show is Hells Kitchen US S18E14 not being found in any site after manual search but it was posted to rarbg since yesterday.
It seems like the manual search isn't pulling results for rarbg and other sites as well. 

https://rarbggo.org/torrents.php?search=Hells+Kitchen+US+S18E14
https://1337x.st/search/Hells+Kitchen+US+S18E14/1/

The only site that brings back anything is zooqle:

![image](https://user-images.githubusercontent.com/13501166/52185652-73d59900-2800-11e9-9fee-dca5310065c5.png)

Which I have normally disabled since magnets from that site don't work on Mac OS using uTorrent (previously reported).

**Comment by garfield69** [comment]
nope, cannot replicate your report.
![image](https://user-images.githubusercontent.com/6933240/52185757-9363d480-2887-11e9-9984-a84e1eda7900.png)
if you are on a nightly, then just after your search for rarbg that fails, use the **Cmd-Alt-I** to open the *Development Tools* page, and then clicking on the **console** tab.
look for http network errors accessing rarbg's API at https://torrentapi.org because that is the only reason I can think you're not getting a result.

**Comment by garfield69** [comment]
Also, test your network access to RarBG's API .
From your mac browser use this address
https://torrentapi.org/pubapi_v2.php?app_id=DuckieTV
and you should get back 
```
{"error":"No token set!","error_code":1}
```
without any other intermediate pages or interference.
What do you get?

**Comment by lonelyfairie** [comment]
This is what I get on a search for Schitts Creek S05E05: 
![image](https://user-images.githubusercontent.com/13501166/52354431-3135db80-2a0f-11e9-91e0-68fc2940fea0.png)

No errors for rarbg or 1337x which are the ones that fail to bring torrents for other shows when they are already uploaded. 
https://rarbggo.org/torrents.php?search=Schitts+Creek+S05E05
https://1337x.st/search/Schitts+Creek+S05E05/1/

I do get the {"error":"No token set!","error_code":1} when accessing that URL you gave me.
Let me know what other tests I can do to try and give you more info.

**Comment by lonelyfairie** [comment]
On the Network tab of the developer tools I get this cancelled requests I don't know if it helps:

![image](https://user-images.githubusercontent.com/13501166/52355326-ea48e580-2a10-11e9-854a-48a5878043ef.png)

**Comment by garfield69** [comment]
wow, your log is a sea of red.
the first thing i notice is that you are using a lot of out of date search engines....
www.nyaa.se is now nyaa.si, www.idope.se is gone,  extratorrent.cc is now extratorrent.ag etc
but some of the others are legitimately unavailable, for example karcr.co have db issues currently, and your TPB proxy you are using is a dead end address using an invalid certificate.

so I suspect you are running dtv 1.1.5 chrome extension?
I thought you were using dtv standalone nightly 01-02-2019? 

torrentz2.eu returning 503 is because of its cloudflare ddos protection, but you can reset that most times by clicking on the link in the log and letting cloudflare do its validation. then the next time you search you should get results.

as for rarbg, the cancel you see in the network tab is normal, it happens when you are using the manual search. when you have a search going, and you change the search parameters, the current search is cancelled in order to issue the new search.

my point is that I don't see any issues with what you presented to me so far, other than the fact that you are not using the latest nightly so most of your search engines are out of date.

**Comment by garfield69** [comment]
debugging rarbg.
enable the **development tools** panel and switch to the **Network** tab.
click on the **filters** icon and type `pubapi` to filter only rarbg entries.
use your dtv torrent-search panel then look at each pubapi entry in the network tab by clicking on the entry name.
click on the **headers** tab and check the **status code** which should be 200. anything else is usually an error.
the **request url** will show what was posted by DTV to the API, such as the search string
then click on the **Response** tab to see what rarbg returned.
below is an example of a search that returned not-found
![image](https://user-images.githubusercontent.com/6933240/52397538-cb367a80-2b1a-11e9-9ae5-3d6d39abe779.png)
![image](https://user-images.githubusercontent.com/6933240/52397553-d38eb580-2b1a-11e9-97d1-610cc5c24a1a.png)

see what you get and report back anything interesting.

**Comment by lonelyfairie** [comment]
Hi Garfield, I am using the nightly version:
![image](https://user-images.githubusercontent.com/13501166/52427741-4c701c00-2adf-11e9-9344-f91bc4ce1022.png)

I enabled all the searches in the manual search a long time ago, when this became available, I usually don't touch it since I rather get as many results as posible if a torrent wasn't found on the default search (which used to be 1337x and now is rarbg in my case) instead of having to enable disable each one till I get results. I had no idea this sites where out of order since I just use whatever duckie has there I don't add any providers manually. 

I did what you asked in the developer tools and this is what I got:

![image](https://user-images.githubusercontent.com/13501166/52428140-24cd8380-2ae0-11e9-8c9a-87966fa73697.png)

This is the response:

{"torrent_results":[{"title":"Schitts.Creek.S05E05.720p.WEBRip.x264-TBS[rartv]","category":"TV HD Episodes","download":"magnet:?xt=urn:btih:fd69b28bd8701695b3b89628660fd4d8e531a78a&dn=Schitts.Creek.S05E05.720p.WEBRip.x264-TBS%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710&tr=udp%3A%2F%2F9.rarbg.to%3A2710&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce","seeders":90,"leechers":2,"size":526576518,"pubdate":"2019-02-06 01:28:55 +0000","episode_info":{"imdb":"tt3526078","tvrage":"43194","tvdb":"287247","themoviedb":"61662","airdate":"2019-02-05","epnum":"5","seasonnum":"5","title":"Housewarming"},"ranked":1,"info_page":"https:\/\/torrentapi.org\/redirect_to_info.php?token=3zyiknup74&p=1_7_5_8_3_0_0__fd69b28bd8"},{"title":"Schitts.Creek.S05E05.1080p.WEBRip.x264-TBS[rartv]","category":"TV HD Episodes","download":"magnet:?xt=urn:btih:ba51e31377d8bfd90d991c82c1f07e95f4039b5c&dn=Schitts.Creek.S05E05.1080p.WEBRip.x264-TBS%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710&tr=udp%3A%2F%2F9.rarbg.to%3A2710&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce","seeders":64,"leechers":3,"size":1037716777,"pubdate":"2019-02-06 01:48:53 +0000","episode_info":{"imdb":"tt3526078","tvrage":"43194","tvdb":"287247","themoviedb":"61662","airdate":"2019-02-05","epnum":"5","seasonnum":"5","title":"Housewarming"},"ranked":1,"info_page":"https:\/\/torrentapi.org\/redirect_to_info.php?token=3zyiknup74&p=1_7_5_8_3_0_9__ba51e31377"},{"title":"Schitts.Creek.S05E05.WEBRip.x264-TBS[rartv]","category":"TV Episodes","download":"magnet:?xt=urn:btih:a59046fe3e0013c6e2dd31484e9b6a0b1f0eaf27&dn=Schitts.Creek.S05E05.WEBRip.x264-TBS%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710&tr=udp%3A%2F%2F9.rarbg.to%3A2710&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce","seeders":36,"leechers":3,"size":175896647,"pubdate":"2019-02-06 01:26:27 +0000","episode_info":{"imdb":"tt3526078","tvrage":"43194","tvdb":"287247","themoviedb":"61662","airdate":"2019-02-05","epnum":"5","seasonnum":"5","title":"Housewarming"},"ranked":1,"info_page":"https:\/\/torrentapi.org\/redirect_to_info.php?token=3zyiknup74&p=1_7_5_8_2_9_8__a59046fe3e"}]}

I see there are results coming in that response but I still see nothing on the search:

![image](https://user-images.githubusercontent.com/13501166/52428300-6fe79680-2ae0-11e9-8cbf-74b115ba4f12.png)

I only enabled 1337x as an additional source this time on the manual search but the connections tab seems to only show it is trying the search in rarbg it seems:

![image](https://user-images.githubusercontent.com/13501166/52428511-e1bfe000-2ae0-11e9-8098-d857dbc39dc6.png)

Just thought it might be useful for you to know that as well. 

After the search I did go to the console tab again and found some rarbg errors not sure if they are from the search or an automated search for missing episodes:

![image](https://user-images.githubusercontent.com/13501166/52428598-0f0c8e00-2ae1-11e9-9d74-157f3335359c.png)

Let me know If I can give you any more info.

**Comment by garfield69** [comment]
your version of the nightly is **20170126** which is why the search engines are all out of date.
updgrade to the latest nightly from https://github.com/DuckieTV/Nightlies/releases and check the ABOUT page to be sure it has upgraded. 
See if that make any difference to your searches, and if not, at least you will be on the same code version as me and I can be sure any comparisons/parallel tests on my dev machine are valid ;-)

**Comment by garfield69** [comment]
Also, found the reason your rarbg search for *schitts creek s05e05* is not showing hits...
you have set the global exclude list to include **TBS** and the three rarbg torrents for that episode all include **-TBS[rartv]** in their titles. :-D

**Comment by garfield69** [comment]
on my virtual box mojave image, running the installer does not apparently overwrite the previous version of the app 
I first had to open the finder and visit the application folder and move the duckietv app to the bin, then when I ran the installer the new nightly was upgraded (without loosing my data).

**Comment by lonelyfairie** [comment]
> Also, found the reason your rarbg search for _schitts creek s05e05_ is not showing hits...
> you have set the global exclude list to include **TBS** and the three rarbg torrents for that episode all include **-TBS[rartv]** in their titles. :-D

That makes sense, I had forgotten about that list. 
Regarding the updates I've been installing the latests nightly's forever I am not sure why it is showing that in the about, I also just checked the duckie tv version in the apps folder and it also shows that, is it possible the nightly installer is pointing somewhere else?
I always run the installer and then tell it to delete the pkg file... so I wonder where it is installing...

**Comment by lonelyfairie** [comment]
![image](https://user-images.githubusercontent.com/13501166/52441084-8a306d00-2afe-11e9-9c00-3d45020537f6.png)

![image](https://user-images.githubusercontent.com/13501166/52441096-95839880-2afe-11e9-9906-310313ced57a.png)

![image](https://user-images.githubusercontent.com/13501166/52441209-d8de0700-2afe-11e9-8568-89b29190864d.png)

I've been running this installers for at least a year thinking it was updating the app... should I remove the app and re load it using a backup?

**Comment by garfield69** [comment]
READ https://github.com/SchizoDuckie/DuckieTV/issues/1151#issuecomment-461547354

**Comment by lonelyfairie** [comment]
> READ [#1151 (comment)](https://github.com/SchizoDuckie/DuckieTV/issues/1151#issuecomment-461547354)

Sorry I skipped that for some reason, will this be changed soon or should I always have to move the .app file before running the installer?
It seems pointless that the installer only works on "new" installations, or is there an autoupdate feature coming soon to avoid manual upgrades?

**Comment by garfield69** [comment]
I don't know why the mac app installer does what it does, its a 3rd party thing we plug into that schizoduckie set up.
none of the installers for the other platforms do this.

**Comment by lonelyfairie** [comment]
![image](https://user-images.githubusercontent.com/13501166/52441881-9e756980-2b00-11e9-873c-1d5f86e7efb4.png)
Thanks for your help Garfield! hopefully I won't have any issues now that everything is updated and sorry for forgetting I had TBS in the exclude list (those releases used to be really awful some time back) :)
