### ISSUE TITLE
Just noticed option for Synology DS-Video and DLNA how to use this and add folders and files?

### ISSUE THREAD

**Issue by phd21** [SchizoDuckie/DuckieTV#1153]
Hi SchizoDuckie,

Using Nightly desktop Duckie TV (DTV) app from 02-11-2019 on Linux KDE Neon (Ubuntu 18.04). 

Just noticed option for Synology DS-Video and DLNA how can we use this and add folders and files? Does this mean that Duckie TV (DTV) now has a built-in DLNA server? Or does this require the Synology DS-Video software? I do not know much about Synology or the DS-Video software yet. Will this work in Linux without a NAS drive? I assume that if this works with Synology NAS then it should work with any folders and files I have on my system? How can we set this up? If yes, how do we add folders and files locations to DTV?

Best regards,
Phil (phd21)

**Comment by garfield69** [comment]
>Does this mean that Duckie TV (DTV) now has a built-in DLNA server? 

no, it just uses the DLNA interface to issue remote commands to the Synology Disk Station Video Manager.

>does this require the Synology DS-Video software?

Yes

>Will this work in Linux without a NAS drive?

No

>I assume that if this works with Synology NAS then it should work with any folders and files I have on my system? 

No, the Dtv DLNA service is specifically coded for the Synology Disk Station Video Manager.

>How can we set this up? 
>If yes, how do we add folders and files locations to DTV?

You don't.  Dtv does not need to know about the file locations and pathways to the video.
Dtv issues a get.video.library command to the SynoDS, then when you hit play on a Dtv episode, it tries to match the Dtv series.name and episode.name with the play list it got from the SynoDS.
If a match is found, a play.video request is sent.
