### ISSUE TITLE
Zooqle search error

### ISSUE THREAD

**Issue by skaa** [SchizoDuckie/DuckieTV#1154]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standlone 

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Stable 1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows

**Describe the problem you are having and steps to reproduce if available**
Torrent search on Zooqle returns error:
TYPEERROR: CANNOT READ PROPERTY '0' OF NULL

**Attach any DuckieTV statistics or Developer Console logs if available**
[
  {
    "name": "DuckieTV Web Based",
    "data": "1.1.5"
  },
  {
    "name": "Current Date and Time",
    "data": "Thu, 14 Feb 2019 03:49:07 GMT"
  },
  {
    "name": "NWJS, Chromium",
    "data": "0.25.0 , 61.0.3163.79"
  },
  {
    "name": "UserAgent",
    "data": "DuckieTV-Standalone  v1.1.5 Windows NT 6.3; Win64; x64"
  },
  {
    "name": "Platform, Vendor",
    "data": "Win32, Google Inc."
  },
  {
    "name": "Screen (width x height)",
    "data": "1920 x 1080"
  },
  {
    "name": "Default Search Engine",
    "data": "Zooqle (Enabled)"
  },
  {
    "name": "Default Torrent Client",
    "data": "Transmission (Enabled but Not Connected to Host)"
  },
  {
    "name": "Auto Download Service",
    "data": "(Disabled)"
  },
  {
    "name": "Last checked TraktTV for DB updates on",
    "data": "Thu, 14 Feb 2019 03:25:54 GMT"
  },
  {
    "name": "User Preferences on Local Storage",
    "data": "{\n  \"ThePirateBay.mirror\": \"https://thepiratebay.org\",\n  \"application.language\": \"en_us\",\n  \"application.locale\": \"en_us\",\n  \"aria2.port\": 6800,\n  \"aria2.server\": \"http://localhost\",\n  \"aria2.token\": \"\",\n  \"autobackup.period\": \"monthly\",\n  \"autodownload.delay\": 15,\n  \"autodownload.multiSE\": {\n    \"ThePirateBay\": true,\n    \"1337x\": true,\n    \"IsoHunt\": true,\n    \"KATcr\": true,\n    \"Nyaa\": true,\n    \"RarBG\": true,\n    \"ShowRSS\": true,\n    \"TorrentDownloads\": true,\n    \"TorrentZ2\": true,\n    \"Zooqle\": true,\n    \"EzTV.ag\": true,\n    \"Idope\": true,\n    \"LimeTorrents\": true,\n    \"SkyTorrents\": true\n  },\n  \"autodownload.multiSE.enabled\": false,\n  \"autodownload.period\": 1,\n  \"background-rotator.opacity\": \"0.4\",\n  \"biglybt.password\": \"*****\",\n  \"biglybt.path\": \"/transmission/rpc\",\n  \"biglybt.port\": 9091,\n  \"biglybt.progressX100\": true,\n  \"biglybt.server\": \"http://localhost\",\n  \"biglybt.use_auth\": true,\n  \"biglybt.username\": \"biglybt\",\n  \"calendar.mode\": \"date\",\n  \"calendar.show-downloaded\": true,\n  \"calendar.show-episode-numbers\": false,\n  \"calendar.show-specials\": true,\n  \"calendar.startSunday\": false,\n  \"client.determinedlocale\": \"ru_ru\",\n  \"deluge.password\": \"*****\",\n  \"deluge.port\": 8112,\n  \"deluge.server\": \"http://localhost\",\n  \"deluge.use_auth\": true,\n  \"download.ratings\": false,\n  \"episode.watched-downloaded.pairing\": true,\n  \"kc.always\": false,\n  \"ktorrent.password\": \"*****\",\n  \"ktorrent.port\": 8080,\n  \"ktorrent.server\": \"http://localhost\",\n  \"ktorrent.use_auth\": true,\n  \"ktorrent.username\": \"ktorrent\",\n  \"lastSync\": -1,\n  \"library.order.by\": \"getSortName()\",\n  \"library.order.reverseList\": [\n    true,\n    false,\n    true,\n    true\n  ],\n  \"library.seriesgrid\": true,\n  \"library.smallposters\": true,\n  \"main.viewmode\": \"calendar\",\n  \"notifications.enabled\": true,\n  \"qbittorrent.password\": \"*****\",\n  \"qbittorrent.port\": 8080,\n  \"qbittorrent.server\": \"http://localhost\",\n  \"qbittorrent.use_auth\": true,\n  \"qbittorrent.username\": \"admin\",\n  \"qbittorrent32plus.password\": \"*****\",\n  \"qbittorrent32plus.port\": 8080,\n  \"qbittorrent32plus.server\": \"http://localhost\",\n  \"qbittorrent32plus.use_auth\": true,\n  \"qbittorrent32plus.username\": \"admin\",\n  \"rtorrent.path\": \"/RPC2\",\n  \"rtorrent.port\": 80,\n  \"rtorrent.server\": \"http://localhost\",\n  \"rtorrent.use_auth\": false,\n  \"series.displaymode\": \"poster\",\n  \"series.not-watched-eps-btn\": false,\n  \"storage.sync\": false,\n  \"subtitles.languages\": [\n    \"eng\"\n  ],\n  \"sync.progress\": true,\n  \"synology.enabled\": true,\n  \"synology.ip\": \"192.168.x.x\",\n  \"synology.password\": \"*****\",\n  \"synology.playback_devices\": {},\n  \"synology.port\": 5000,\n  \"synology.protocol\": \"http\",\n  \"synology.username\": \"admin\",\n  \"tixati.password\": \"*****\",\n  \"tixati.port\": 8888,\n  \"tixati.server\": \"http://localhost\",\n  \"tixati.use_auth\": true,\n  \"tixati.username\": \"admin\",\n  \"topSites.enabled\": false,\n  \"topSites.mode\": \"onhover\",\n  \"torrentDialog.2.activeSE\": {\n    \"ThePirateBay\": true,\n    \"1337x\": true,\n    \"IsoHunt\": true,\n    \"KATcr\": true,\n    \"Nyaa\": true,\n    \"RarBG\": true,\n    \"ShowRSS\": true,\n    \"TorrentDownloads\": true,\n    \"TorrentZ2\": true,\n    \"Zooqle\": true\n  },\n  \"torrentDialog.2.enabled\": false,\n  \"torrentDialog.2.sortBy\": \"+engine\",\n  \"torrentDialog.showAdvanced.enabled\": true,\n  \"torrenting.autodownload\": false,\n  \"torrenting.autostop\": true,\n  \"torrenting.autostop_all\": false,\n  \"torrenting.client\": \"Transmission\",\n  \"torrenting.directory\": true,\n  \"torrenting.enabled\": true,\n  \"torrenting.global_size_max\": null,\n  \"torrenting.global_size_max_enabled\": true,\n  \"torrenting.global_size_min\": null,\n  \"torrenting.global_size_min_enabled\": true,\n  \"torrenting.ignore_keywords\": \"\",\n  \"torrenting.ignore_keywords_enabled\": true,\n  \"torrenting.label\": false,\n  \"torrenting.launch_via_chromium\": false,\n  \"torrenting.min_seeders\": 50,\n  \"torrenting.min_seeders_enabled\": false,\n  \"torrenting.progress\": true,\n  \"torrenting.require_keywords\": \"\",\n  \"torrenting.require_keywords_enabled\": true,\n  \"torrenting.require_keywords_mode_or\": true,\n  \"torrenting.searchprovider\": \"Zooqle\",\n  \"torrenting.searchquality\": \"\",\n  \"torrenting.searchqualitylist\": [\n    \"480p\",\n    \"HDTV\",\n    \"720p\",\n    \"1080p\",\n    \"2160p\"\n  ],\n  \"torrenting.streaming\": true,\n  \"trakt-update.period\": 12,\n  \"trakttv.passwordHash\": \"*****\",\n  \"trakttv.sync\": false,\n  \"trakttv.username\": null,\n  \"transmission.password\": \"*****\",\n  \"transmission.path\": \"/transmission/rpc\",\n  \"transmission.port\": 9091,\n  \"transmission.progressX100\": true,\n  \"transmission.server\": \"http://localhost\",\n  \"transmission.use_auth\": true,\n  \"transmission.username\": \"admin\",\n  \"utorrentwebui.password\": \"*****\",\n  \"utorrentwebui.port\": 8080,\n  \"utorrentwebui.server\": \"http://localhost\",\n  \"utorrentwebui.use_auth\": true,\n  \"utorrentwebui.username\": \"admin\",\n  \"vuze.password\": \"*****\",\n  \"vuze.path\": \"/transmission/rpc\",\n  \"vuze.port\": 9091,\n  \"vuze.progressX100\": true,\n  \"vuze.server\": \"http://localhost\",\n  \"vuze.use_auth\": true,\n  \"vuze.username\": \"vuze\"\n}"
  },
  {
    "name": "Other significant Local Storage keys",
    "data": "{\n  \"1.1.4TorrentHashListCleanup\": \"Thu Feb 14 2019 08:25:52 GMT+0500 (RTZ 4 (зима))\",\n  \"1.1.4cleanupOrphanedEpisodes\": \"Thu Feb 14 2019 08:25:50 GMT+0500 (RTZ 4 (зима))\",\n  \"1.1.4cleanupOrphanedSeasons\": \"Thu Feb 14 2019 08:25:51 GMT+0500 (RTZ 4 (зима))\",\n  \"1.1.4qBittorrentPre32\": \"Thu Feb 14 2019 08:25:46 GMT+0500 (RTZ 4 (зима))\",\n  \"1.1.4refresh\": \"Thu Feb 14 2019 08:25:56 GMT+0500 (RTZ 4 (зима))\",\n  \"1.1.4refreshTrendingCache\": \"Thu Feb 14 2019 08:25:46 GMT+0500 (RTZ 4 (зима))\",\n  \"1.1.4updateTransmissionPath\": \"Thu Feb 14 2019 08:25:46 GMT+0500 (RTZ 4 (зима))\",\n  \"1.1.5FetchFirstXemAliasMap\": \"Thu Feb 14 2019 08:25:46 GMT+0500 (RTZ 4 (зима))\",\n  \"1.1.5deleteSearchEngines\": \"Thu Feb 14 2019 08:25:46 GMT+0500 (RTZ 4 (зима))\",\n  \"1.1.5fanartCleanup\": \"Thu Feb 14 2019 08:26:16 GMT+0500 (RTZ 4 (зима))\",\n  \"1.1.5updateDelugeAuth\": \"Thu Feb 14 2019 08:25:46 GMT+0500 (RTZ 4 (зима))\",\n  \"1.1.5updateTorrenting.min_seeders\": \"Thu Feb 14 2019 08:25:46 GMT+0500 (RTZ 4 (зима))\",\n  \"1.1migration\": \"Thu Feb 14 2019 08:25:49 GMT+0500 (RTZ 4 (зима))\",\n  \"autobackup.lastrun\": \"1550114746839\",\n  \"database.version.Episodes\": \"14\",\n  \"database.version.Fanart\": \"1\",\n  \"database.version.Jackett\": \"2\",\n  \"database.version.Seasons\": \"6\",\n  \"database.version.Series\": \"16\",\n  \"database.version.WatchList\": \"1\",\n  \"database.version.WatchListObject\": \"1\",\n  \"fanart.bootstrapped\": \"1\",\n  \"github.lastupdatecheck\": \"1550114749093\",\n  \"install.notify\": \"1.1.5\",\n  \"runtime.event\": \"{\\\"reason\\\":\\\"install\\\"}\",\n  \"snr.lastFetched\": \"1550114748966\",\n  \"standalone.position\": \"{\\\"width\\\":1739,\\\"height\\\":750,\\\"x\\\":-1876,\\\"y\\\":158,\\\"state\\\":\\\"normal\\\"}\",\n  \"standalone.zoomlevel\": \"6\",\n  \"torrenting.client\": \"Transmission\",\n  \"trackers.lastFetched\": \"1550114748934\",\n  \"trakttv.lastupdated\": \"1550114754889\",\n  \"trakttv.lastupdated.trending\": \"1550115756169\",\n  \"uniqueId\": \"1111e6a5-1a99-5f2a-f048-a0a798da3b02\",\n  \"upgrade.notify\": \"1.1.5\",\n  \"xem.lastFetched\": \"1550114748957\"\n}"
  },
  {
    "name": "DB Series",
    "data": 2
  },
  {
    "name": "DB Series Hidden From Calendar",
    "data": 0
  },
  {
    "name": "DB Seasons",
    "data": 21
  },
  {
    "name": "DB Episodes",
    "data": 430
  },
  {
    "name": "DB Fanart",
    "data": 1848
  },
  {
    "name": "DB Jackett",
    "data": 0
  }
]

**Comment by garfield69** [comment]
this type of error usually occurs if zooqle is performing database maintenance or has some other outage that is not network (http/https) related, when the site sends some form of text notice on the search results web page instead of the usual torrent results list.

I note that Zooqle is running normally at the moment, and I don't have any problems searching it with dtv.

I suggest you try again.

if it is still not working for you, then access a browser on the same system you run dtv on, and see what you get when you use https://zooqle.com/search?q=test&ssz&sd=d&v=t

report back what you find.
