### ISSUE TITLE
Profile error occurred.... still!

### ISSUE THREAD

**Issue by Jynx2120** [SchizoDuckie/DuckieTV#1155]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...Both / all

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
... 1.1.5 and nightly (current)

**What is your Operating System (Windows, Mac, Linux, Android)**
...Windows 10 Pro

**Describe the problem you are having and steps to reproduce if available**
... Start Duckie TV and immediately get this popup (jpeg attached). It doesn't matter what version of Duckie I have installed (stable or nightly) this issue persists and is now starting to drive me crazy lol. Everything works fine in Duckie, I just keep getting this annoying popup and I need it to stop now.

![profile-error-duckie](https://user-images.githubusercontent.com/29512724/52818061-b3f41180-3073-11e9-87b0-be1628b50a37.jpg)

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
this can occurs when you upgrade your standalone 1.1.5 to a nightly and then re-install 1.1.5 back again, or re-install an older nightly over the top of a more recent version.

The upgrades are forward only, (especially when we upgrade the nwjs engine as part of the standalone nightly build), as the nwjs engine will add new environment settings which the older nwjs recognises as unknown, hence the popup.
(Also, the new nightly could have new dtv database keys which are not backward compatible).

The popup should vanish if you install the latest nightly ... 

if it does not, then the only way I know to get rid of it, is this wipe and start afresh method:
1. take a backup using the dtv>settings>backup sidepanel, create-a-backup option.
2. shutdown the standalone
3. rename the standalone data folder (usually at `C:\Users\<username>\AppData\Local\DuckieTV-Standalone` to something else (suggest appending .backup)
4. start the standalone and wait for the pre-install activity to settle (a couple minutes)
5. import your dtv.backup which contains your settings and series keys (this will fetch from Trakt.tv all the series/episodes/season data, then apply and personal changes over the top).

[edit] updated the steps

**Comment by Jynx2120** [comment]
Thank you garfield69, I did the latter and that solved the issue. Thanks again!
