### ISSUE TITLE
Torrent Client integration keeps breaking

### ISSUE THREAD

**Issue by ggervais5** [SchizoDuckie/DuckieTV#1159]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
1.15

**What is your Operating System (Windows, Mac, Linux, Android)**
Mac OS High Sierra

**Describe the problem you are having and steps to reproduce if available**
When a torrent client is first integrated (I've tried 5 different ones), connection is established, and downloads work fine.  The next day or so, attempted downloads cause the message "Torrent not found in client."  The deterioration continues, until Duckie TV will no longer communicate with the torrent client.  I have been able to re-establish connection by changing the port (8081, 8082, etc.) on both ends.  Torrent clients I have tried:  uTorrent, qBittorrent, Deluge, and Transmission.  All exhibit the same behavior.

**Attach any DuckieTV statistics or Developer Console logs if available**
Unsure where to find these.

**Comment by garfield69** [comment]
Urg. Well this is a unique issue, I've never come across it before. 
Must have something to do about your system setup, but the trick will be find out out what it could be.

Do you run dtv and the torrent client on the mac 24/7 ?

the standalone dtv 1.1.5 does not have logs, so it might be useful to upgrade to the latest dtv Nightly from https://github.com/DuckieTV/Nightlies/releases
then the log can be access using **Cmd-Alt-I** to open the Development Tools page, and then clicking on the **console** tab. 

on my virtual box mojave image, running the installer does not apparently overwrite the previous version of the app, the same may apply on your High Sierra.
I first had to open the finder and visit the application folder and move the duckietv app to the bin, then when I ran the installer the new nightly was upgraded (without loosing my data).

**Comment by ggervais5** [comment]
Here was my initial set up: 




Duckie Tv on the Mac.  UTorrent on the Mac.  Issues arose when I left it running over 24 hours.  Current downloads stop.  Next symptom is that torrent downloads do not appear in the torrent client. I tried other torrent clients...same deal.  I plugged in my Mac to the switch to rule out wireless drops.  Could it be that Mac goes to sleep and dtvis  not re-establashing communicationsm with the torrent client when the Mac wakes up?  Should I be preventing Mac from going to sleep?




I uninstalled all Mac torrents and connected Mac version of dtv to a torrent client (first utorrent and now qbittorrent) on a Windows PC I have.  Same symptoms.




I want to autoupdate, so yes, I want to run it 24/7. I am using a socks5 proxy from PIA in the torrent clients.




Are you thinking there might be a memory leak, or something in how the port is being managed between dtv and a torrent client?  Maybe I should disable sleep mode on the Mac, or try the Windows version?  I want to update downloads of tv shows.  Once they land in a folder, I have an automated process to load them into a media library in an organized manner.




Get Outlook for Android







On Tue, Feb 19, 2019 at 12:13 PM -0600, "garfield69" <notifications@github.com> wrote:












Urg. Well this is a unique issue, I've never come across it before.

Must have something to do about your system setup, but the trick will be find out out what it could be.


Do you run dtv and the torrent client on the mac 24/7 ?


the standalone dtv 1.1.5 does not have logs, so it might be useful to upgrade to the latest dtv Nightly from https://github.com/DuckieTV/Nightlies/releases

then the log can be access using Cmd-Alt-I to open the Development Tools page, and then clicking on the console tab.


on my virtual box mojave image, running the installer does not apparently overwrite the previous version of the app, the same may apply on your High Sierra.

I first had to open the finder and visit the application folder and move the duckietv app to the bin, then when I ran the installer the new nightly was upgraded (without loosing my data).



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.






Urg. Well this is a unique issue, I've never come across it before. 
Must have something to do about your system setup, but the trick will be find out out what it could be.

Do you run dtv and the torrent client on the mac 24/7 ?

the standalone dtv 1.1.5 does not have logs, so it might be useful to upgrade to the latest dtv Nightly from https://github.com/DuckieTV/Nightlies/releases
then the log can be access using **Cmd-Alt-I** to open the Development Tools page, and then clicking on the **console** tab. 

on my virtual box mojave image, running the installer does not apparently overwrite the previous version of the app, the same may apply on your High Sierra.
I first had to open the finder and visit the application folder and move the duckietv app to the bin, then when I ran the installer the new nightly was upgraded (without loosing my data).

**Comment by garfield69** [comment]
Ah. Yes, you've put your finger on it. If you are leaving Dtv running 24/7 then the Mac going to sleep would cause Dtv trouble, as it does not handle connection drop outs since it does not have a heart-beat lost/recover capability. 
Try disabling sleep mode and see if that makes a difference. 
Let me know how it goes.

**Comment by ggervais5** [comment]
I am a former software developer..now a project manager.




If disabling sleep does the trick, any plans on adding heartbeat/recovery into the product?  Turning off sleep mode permanently is probably not a good thing.




Get Outlook for Android







On Tue, Feb 19, 2019 at 4:01 PM -0600, "garfield69" <notifications@github.com> wrote:












Ah. Yes, you've put your finger on it. If you are leaving Dtv running 24/7 then the Mac going to sleep would cause Dtv trouble, as it does not handle connection drop outs since it does not have a heart-beat lost/recover capability.

Try disabling sleep mode and see if that makes a difference.

Let me know how it goes.



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.






Ah. Yes, you've put your finger on it. If you are leaving Dtv running 24/7 then the Mac going to sleep would cause Dtv trouble, as it does not handle connection drop outs since it does not have a heart-beat lost/recover capability. 
Try disabling sleep mode and see if that makes a difference. 
Let me know how it goes.

**Comment by ggervais5** [comment]
That was it.  I disabled Sleep and dtv stays connected.




Clicking on a show and downloading it work, but it doesn't seem to want to auto download.  I'm going to have to play with the settings.




Get Outlook for Android







On Tue, Feb 19, 2019 at 4:05 PM -0600, "Greg Gervais" <ggervais5@shaw.ca> wrote:










I am a former software developer..now a project manager.




If disabling sleep does the trick, any plans on adding heartbeat/recovery into the product?  Turning off sleep mode permanently is probably not a good thing.




Get Outlook for Android







On Tue, Feb 19, 2019 at 4:01 PM -0600, "garfield69" <notifications@github.com> wrote:












Ah. Yes, you've put your finger on it. If you are leaving Dtv running 24/7 then the Mac going to sleep would cause Dtv trouble, as it does not handle connection drop outs since it does not have a heart-beat lost/recover capability.

Try disabling sleep mode and see if that makes a difference.

Let me know how it goes.



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.









Ah. Yes, you've put your finger on it. If you are leaving Dtv running 24/7 then the Mac going to sleep would cause Dtv trouble, as it does not handle connection drop outs since it does not have a heart-beat lost/recover capability.

Try disabling sleep mode and see if that makes a difference.

Let me know how it goes.



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.






I am a former software developer..now a project manager.




If disabling sleep does the trick, any plans on adding heartbeat/recovery into the product?  Turning off sleep mode permanently is probably not a good thing.




Get Outlook for Android







On Tue, Feb 19, 2019 at 4:01 PM -0600, "garfield69" <notifications@github.com> wrote:












Ah. Yes, you've put your finger on it. If you are leaving Dtv running 24/7 then the Mac going to sleep would cause Dtv trouble, as it does not handle connection drop outs since it does not have a heart-beat lost/recover capability.

Try disabling sleep mode and see if that makes a difference.

Let me know how it goes.



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.






Ah. Yes, you've put your finger on it. If you are leaving Dtv running 24/7 then the Mac going to sleep would cause Dtv trouble, as it does not handle connection drop outs since it does not have a heart-beat lost/recover capability. 
Try disabling sleep mode and see if that makes a difference. 
Let me know how it goes.

**Comment by garfield69** [comment]
Good. I had a feeling, glad it panned out.

As for heartbeat, I looked at this three or more years ago, but I could not fathom how to implement it, the AngularJS code for this project has gotten quite complex over the years.
The author has stopped contributing after Dtv 1.1.3, but I try to keep the lights on as best as I can.

I may have another crack at it, lots of water under the bridge since I last looked at it, and I may get a fresh insight since the last time I tackled this.

**Comment by ggervais5** [comment]
Rather than a heartbeat, you might consider closing down the webui connection when the os sends out Sleep notification and re-establishing the webui connection when the os sends out the Wakeup notification. You could also have the app prevent sleep if auto downloading is selected.




Heartbeats are only useful while the computer is fully awake, in case the webui connection goes down.  Then, the connection can be destroyed and redone.




Just a thought.




Get Outlook for Android







On Wed, Feb 20, 2019 at 9:05 PM -0600, "garfield69" <notifications@github.com> wrote:












Good. I had a feeling, glad it panned out.


As for heartbeat, I looked at this three or more years ago, but I could not fathom how to implement it, the AngularJS code for this project has gotten quite complex over the years.

The author has stopped contributing after Dtv 1.1.3, but I try to keep the lights on as best as I can.


I may have another crack at it, lots of water under the bridge since I last looked at it, and I may get a fresh insight since the last time I tackled this.



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.






Good. I had a feeling, glad it panned out.

As for heartbeat, I looked at this three or more years ago, but I could not fathom how to implement it, the AngularJS code for this project has gotten quite complex over the years.
The author has stopped contributing after Dtv 1.1.3, but I try to keep the lights on as best as I can.

I may have another crack at it, lots of water under the bridge since I last looked at it, and I may get a fresh insight since the last time I tackled this.
