### ISSUE TITLE
build-bot server down? no nightly or xem-cache updates since 23rd Feb.

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#1160]
@SchizoDuckie 
It's been over a week since any nightly runs were created, and looking at the xem-cache I see there have not been any updates during the same period either.
I fear the build-bot server is down, so would you please investigate?
Thanks.

**Comment by 2635599** [comment]
7 days a WE BIT long to have the server down

**Comment by SchizoDuckie** [comment]
Disk was full. fixed.
