### ISSUE TITLE
Unable to login to trakt.tv

### ISSUE THREAD

**Issue by uhlhosting** [SchizoDuckie/DuckieTV#1161]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
DuckieTV-Standalone v1.1.5 Macintosh; Intel Mac OS X 10_14_4
--

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**

1.1.5
--

**What is your Operating System (Windows, Mac, Linux, Android)**
Mac

**Describe the problem you are having and steps to reproduce if available**
Unable to use Trakt.tv

**Attach any DuckieTV statistics or Developer Console logs if available**
Unique tracking id: aa88370e-4868-fda1-e541-0150218ef237

**Comment by garfield69** [comment]
not seeing anything with your tag in the loggr logs.
can you describe what the problem is in more detail?

**Comment by Js41637** [comment]
Trakt is just having issues. This has nothing to do with DuckieTV

**Comment by uhlhosting** [comment]
it remediated itself.
