### ISSUE TITLE
Can't add Favourites anymore

### ISSUE THREAD

**Issue by TheFacelessOne** [SchizoDuckie/DuckieTV#1162]
DuckieTV-Standalone v1.1.5 Windows NT 10.0; Win64; x64

**Describe the problem you are having and steps to reproduce if available**
I left my pc for a few days and when I came back all my favourites were gone. I tried syncing from trakt, importing a backup and just adding them manually. I can't add any favourites through any of these means. I tried uninstalling and reinstalling. I tried resarting my pc.

**Attach any DuckieTV statistics or Developer Console logs if available**
when I hit f12 it gives me a blank window

**Comment by garfield69** [comment]
Urg. sounds like something has nobbled your Dtv data folder.
To reset, 
1. shutdown Dtv
2. find and delete the folder `C:\Users\<username>\AppData\Local\DuckieTV-Standalone`
3. start Dtv

after all the pre-init activity has settled down (wait a minute or two) you then should be able to import from either Trakt.tv or from a Dtv-Backup if you have saved one previously.

Also, you might consider upgrading to the latest Nightly from https://github.com/DuckieTV/Nightlies/releases, which has all the latest fixes, including updates for obsolete/'out of date search engines.  

Regarding the **F12** key, the Dtv Standalone 1.1.5 release does not include the *Development Tools* pack.
But the Nightly does, so you can see the logs with the **F12** and **console** tab sequence.
