### ISSUE TITLE
Duckietv connеcted to uTorrent webUI says downloading but doesnt load in uTorrent

### ISSUE THREAD

**Issue by lapd87** [SchizoDuckie/DuckieTV#1163]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standlone and Browser

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
DuckieTV v1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
windows 7 x64

**Describe the problem you are having and steps to reproduce if available**
I am connecting to uTorrent 2.2.1 build 25302 webUI with ng-torrent-ui 0.7.1. The green dot appears but when searching for torrent in tracker from Jackett Version 0.11.36.0 it says "Download started on uTorrent webUI" but in reality there is nothing happening. 
Errors from chrome console :
------------------------------------------
Access to XMLHttpRequest at 'magnet:?xt=urn:btih:f9e22e03feb487d423521350be892152289b6624&dn=Lethal.Weapon.S03E15.REPACK.WEB.h264-TBS[ArenaBG]-ArenaBG' (redirected from 'http://127.0.0.1:9117/dl/arenabg/?jackett_apikey=............................&path=Q2ZESjhLX2traU1mZWhKSnM4ekxJWWtBVXY5Zmo2bDZOQnpERjN2NkpCOGY3RmpDX0lBT1M5R2pUQXNTNkVYTzJsS0FrZHo3YWdXSkM2em4zRHhKekxVOThnNURCVkxmV0sycC1ES3FnRGpmdmd3eWVEUFhkWTVvS2t6TFVRdzV0NVhtX1BzbVRjT29ZTjBtTmlMWUpVYWJjNXhSMXVWVVpCUDBGcUdnQWIxTlpwRDk4TXdpTTd6cG1FenlEWjNKaVdFbWhFZFVTdkNSZzU0Rm0tTVd0OExvcEU0&file=Lethal.Weapon.S03E15.REPACK.WEB.h264-TBS%5BArenaBG%5D') from origin 'chrome-extension://cdfkaloficjmdjbgmckaddgfcghgidei' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
app.js:7284 Uncaught Error: Error downloading torrent: XHR error
    at deps.js:19327
    at module.exports.<anonymous> (deps.js:20838)
    at module.exports.f (deps.js:19941)
    at module.exports.EventEmitter.emit (deps.js:13168)
    at XMLHttpRequest.xhr.onerror (deps.js:17687)
---------------------------------------
and another one with no result :
-------------------------------------------
Firing magnet URI!  magnet:?xt=urn:btih:B45A71C0BC4650C01AADCC9194314682E2F4DA53 7021565 null null
-----------------------------------------
from piratebay:
-------------------------------
Firing magnet URI!  magnet:?xt=urn:btih:079ccfc20158c03e72d7697e2f51326eb053cd20&dn=Lethal.Weapon.S03E15.REPACK.WEB.h264-TBS%5Bettv%5D&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Fzer0day.ch%3A1337&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Fexodus.desync.com%3A6969 7043355 null null
----------------------------------------
if I click 3rd button - magnet link it works but not all trackers has it.

**Attach any DuckieTV statistics or Developer Console logs if available**
added console errors

**Comment by garfield69** [comment]
The issue with Jackett's ArenaBG is one that can occur on Dtv with some Jackett Indexers.
Details if you are interested are in this [wiki](https://github.com/SchizoDuckie/DuckieTV/wiki/Using-Jackett-with-DuckieTV#duckietv-jackett-problems-and-solutions)

The good news is that this should be fixable. But it will take a couple steps for you to perform first.
1. upgrade to Jackett pre-release 0.11.45 which contain a fix for ArenaBG Indexer.
2. then from the Jackett Dashboard edit the ArenaBG indexer using the wrench icon, and select the **.torrent** option in the *Download Link* dropdown box.
You may also need to re-enter your username and password and click OKAY.
3. Now try downloading from Dtv and see how it goes.

Regarding the TPB magnet, I cannot replicate this on my Dtv using either the Jackett TPB indexer or the native Dtv TPB SE. 
I can download that particular magnet fine using the magnet button on the search torrent panel using either SE.
Mind you, I'm using the latest Dtv Standalone Nightly on my win10, with utorrent 3.5.5 via the Dtv webui interface.
I would suggest upgrading your standalone 1.1.5 to The latest Nightly from https://github.com/DuckieTV/Nightlies/releases and see if that makes a difference for you.
The Nightly is essentially Dtv 1.1.6 in development, and contains all the latest updates and enhancements.
(note the Nightly standalone has access to the log that the 1.1.5 did not, using the same key sequence you used for the chrome browser).
I would suggest you take a Dtv Backup from the 1.1.5 settings>Backup panel as a precaution before upgrading to the Nightly. (Belts and braces safety first ;-) )

**Comment by lapd87** [comment]
Thank you for the fast reply!
So updating Jackett fixed arenaBG problem.
Updated to night release too but unfortunately it didn't help. Tested with zelka.org from standalone:
-----------------------------
Xem does not have series Chicago P.D. (269641), using default format.
app.js:16029 Firing magnet URI!  magnet:?xt=urn:btih:9A62F2A28535E4E5207C949E0F810722CF4FF22D 7036830 null null
-----------------------------
it does not add torrent to the list in uTorrent!
from piratebay:
---------------------------
Firing magnet URI!  magnet:?xt=urn:btih:68422eea48af45a63d232536f1de7235d4bbb275&dn=Chicago.Fire.S07E16.1080p.HDTV.x264-LucidTV%5BTGx%5D&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Fzer0day.ch%3A1337&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Fexodus.desync.com%3A6969 7036827 null null
--------------------------------
also no adding to list.
Third option "magnet link" works but uTorrent says it has been added already and ask to add the trackers (I assume some double opening is happening with the link).
some more logs:
---------------------------------------
deps.js:2378 Possibly unhandled rejection: Canceled
(anonymous) @ deps.js:2378
(anonymous) @ deps.js:2349
g @ deps.js:2390
$digest @ deps.js:2402
$apply @ deps.js:2406
(anonymous) @ deps.js:2448
og @ deps.js:2291
d @ deps.js:2291
app.js:10671 Xem does not have series NCIS: Los Angeles (95441), using default format.
2deps.js:2378 Possibly unhandled rejection: escape key press
(anonymous) @ deps.js:2378
(anonymous) @ deps.js:2349
g @ deps.js:2390
$digest @ deps.js:2402
$apply @ deps.js:2406
g @ deps.js:2706
og @ deps.js:2291
d @ deps.js:2291
-----------------------------------------------
Also found problem with zamunda.net which can't find torrents although it has them (manually removed series, episodes and tried other names but it shows no result).
Also backup has a problem - when selecting daily/monthly/weekly backup it starts the schedule from the date it has been installed on the PC, and keeps asking for backup every time you start duckieTV until it schedule is future date.

**Comment by garfield69** [comment]
which piratebay are you using? the native one from Dtv or the Jackett one?
I don't have a problem downloading chicago fire s07e16 68422eea48af45a63d232536f1de7235d4bbb275 as you can see below
![image](https://user-images.githubusercontent.com/6933240/54341703-5b7a5900-469f-11e9-8014-626a89f88856.png)
using either the jackett TPB or the native DTV one.

Zelka and Zamunda are a problem for me to test since I don't have a bulgarian IP and can't login.
I don't have a VPN (don't need it) and don't intend to pay for one so I can't help you there.

When you say zamundanet cant find torrents, you mean the Dtv torrent search using your jackett zamundanet indexer is not showing results?
Have you used the Jackett Dashboard directly to do the search on zamundanet, does it present results? 


But the zelka issue is odd, I took a look at the zelka jackett indexer and the magnet is on the main results page so I expect that to work from Dtv.

so I have to wonder what is it about your set up that is preventing this from working ?

Wonder if it is the utorrent 2.2.1 webui? 
I'll set up a virtual machine and load up this old utorrent and the latest Dtv nightly and see if I can replicate your problem with TPB. I'll report in a few days when I can make the time to set it up and test.

I'm not sure I understand about the backup. You set it to weekly, and it asks you to make a backup. if you perform the backup it should then not ask you again until a week later. the backup panel should tell you when the next backup is scheduled to take place. if you don't perform the backup then the next time you start Dtv it asks you to make a backup. Isn't this how its working?

**Comment by lapd87** [comment]
zamunda.net -> zamunda.ch
zelka.org -> zamunda.se
try those ones they are the same (logins too) but should work from non bulgarian IPs. Maybe Tor browser can help too if it hides you or incognito mode?

zamunda.net doesnt show result from Jackett either. I suppose the problem is with Jackett?

I use the native piratebay. But I cant really download from anywhere but arenaBG... All of them are showing download started but no torrent in list. Have tried multiple torrents and trackers. Only option 3 works if it is available for the tracker.

The backup problem is as follows:
I have installed duckie few weeks ago (don't ask how I lived without it before)
I have set backup schedule yesterday. Also made manual backup.
The next time I started the app it asked for backup and I rejected (maybe few times).
Today looked and it was saying next schedule March 7th. (this I am 100% sure)
After backing couple times or because of the install of nightly now its March 21st.
I can't be 100% when and if I have confirmed backups when prompted but this is the general idea hope it helps. My opinion is that it start backup schedule not from the day it is set to do backups but from installation date and if I have installed it 10 weeks ago it will ask me for 10 consecutive backups so it can catch up. Also I am suspecting that if I don't backup for more than 2 weeks it will again need multiple backups to catch up.

**Comment by garfield69** [comment]
Nah, zelka and the alternate time out for me, and the zamunda and alternate redirect me to ad sites.
incognito mode made no diff. haven't tried tor yet.

yes, if the jackett zamundanet indexer is not returning results, enable enhanced logging on the dashboard, repeat the test, then raise a ticket on https://github.com/Jackett/Jackett/issues/new and include the log.txt so the devs take a look. Likely the row selector or the fields selectors are out of date.

OK. did some tests with utorrent 2.2.1 and found the problem. 
the Dtv webui interface is not 100% compatible with utorrent 2.2.1, and is silently discarding magnet requests. Only .torrent uploads are accepted.
I guess I shouldn't be surprised, the Dtv Webui interface was developed and added to Dtv using utorrent 3.4.2 as the base.

I'll see if I can compare https://github.com/psychowood/ng-torrent-ui magnet upload code with Dtv's webui and spot the difference.

**Comment by garfield69** [comment]
I think I have sorted the webui 221 compatibility. 
when the buildbot published the next nightly-201903150130 in about 6 hours, try it out and confirm its working for you as it did in my test.

**Comment by lapd87** [comment]
So I don't know what they have changed but just as I have enabled enhanced logging and started the search and its all good. I suspect they have updated something or zamunda have changed and reverted... Anyway its all good and working with zamunda searching.

Now after updating DuckieTv I can download from both zamunda and zelka, also from piratebay and 1337. Unfortunately now arenaBG is again broken.
----------------------------------------------------------
Xem does not have series The Big Bang Theory (80379), using default format.
deps.js:17987 Invalid torrent identifier
parseTorrent @ deps.js:17987
parseTorrentRemote @ deps.js:17999
urlSelect @ app.js:7300
$scope.select @ app.js:7331
(anonymous) @ deps.js:2517
e @ deps.js:2448
$eval @ deps.js:2405
$apply @ deps.js:2405
(anonymous) @ deps.js:2448
og @ deps.js:2291
d @ deps.js:2291
app.js:7302 Uncaught Error: Error downloading torrent: XHR error
    at deps.js:18025
    at module.exports.<anonymous> (deps.js:19536)
    at module.exports.f (deps.js:18639)
    at module.exports.EventEmitter.emit (deps.js:11865)
    at XMLHttpRequest.xhr.onerror (deps.js:16384)
(anonymous) @ deps.js:18025
(anonymous) @ deps.js:19536
f @ deps.js:18639
EventEmitter.emit @ deps.js:11865
xhr.onerror @ deps.js:16384
--------------------------------------------------

Also about the backup bug. I have just noticed that if you make manual backing the schedule date doesn't change. So if I set backing up weekly but sometimes I backup on the 6th day manually I will have to backup again the next day too because of the schedule not updating.

**Comment by garfield69** [comment]
I've just manually searched and downloaded from arenaBG on my Dtv series TBBT episode s12e16 torrents `The.Big.Bang.Theory.S12E16.720p.HDTV.x264-...` and `The.Big.Bang.Theory.S12E16.HDTV.x264-SVA[A...` without any problems.
I have the jackett arenabg indexer download link option set to .torrent 

check that your jackett arenabg is still set to `.torrent`, and if either of the above torrents is not the one you are trying to dl then specify the full torrent name so i can test.

the key error message is `deps.js:17987 Invalid torrent identifier` which indicates that Dtv was given something other than what was expected (such as a magnet instead of a .torrent file), or a link to a secondary page instead of a .torrent file).


Ah, good spotting re: the backup. I'll take a good look at all that code sometime and see if I can make it behave.

**Comment by lapd87** [comment]
Ok just checked and I dont know how but Jackett was the old version (36).... Removed completly and installed the newest (from few hours). Now arenaBG is working again :)
Tested again with all trackers that matter to me and they are all working now.
I appreciate the good work and fast replies!
THANK YOU!!

If you don't mind wait until the week end and close the issue if I haven't got problems until then.

**Comment by lapd87** [comment]
thank you again!  I am closing the issue now :)
