### ISSUE TITLE
Clicking Torrent Details causes Error!

### ISSUE THREAD

**Issue by Jayshua83** [SchizoDuckie/DuckieTV#1164]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
... Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
... 1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
... Windows 10

**Describe the problem you are having and steps to reproduce if available**
... Clicking the (!) for Torrent Details shows a 403 Forbidden page.

https://torrentapi.org/redirect_to_info.php?token=3itse214hq&p=1_7_9_2_4_7_2__dba52dc563

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
This applies to the Dtv RARBG Search Engine, inside which we use the provided rarbg API at torrentapi.org.
I've tested this an can confirm it also happens with the Jackett RARBG indexer, so It is clearly an issue with the RARBG API server. 
I've contacted support@rarbg.to and we shall see if they can help sort the problem out at their end.

**Comment by garfield69** [comment]
the next Nightly in a couple hours at https://github.com/DuckieTV/Nightlies/releases should contain the fix for this..
apparently a change on the RarBG API server means we have to use an app_id for every request we make.
