### ISSUE TITLE
QBitronnet 3.2+  chrome broswer extension issue

### ISSUE THREAD

**Issue by gilimel** [SchizoDuckie/DuckieTV#1167]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Browser Action

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
mac

**Describe the problem you are having and steps to reproduce if available**
the qbittorent integration stoped working for me. it is connected but when i click download i get and exception (can see it from F12 ...) - it is failing in the http://localhost:8080/command/upload command (although i can connect to http://localhost:8080/) and then it fails on http://localhost:8080/query/torrents , when i run it manually it retrives the json of the torrents.
its a new issue, everything worked fine till today.
i also removed the old qbittorent and installed new one but issue persists.

**Attach any DuckieTV statistics or Developer Console logs if available**
...
please see attached image
thanks in advance

[Screen Shot 2019-04-03 at 1 06 24 AM](redacted for security)

**Comment by garfield69** [comment]
you are getting the 403 forbidden error.
Please check that your qBt settings for enabling CSRF protection is **unchecked**
https://github.com/SchizoDuckie/DuckieTV/wiki/Setting-up-qBitTorrent-3.2-with-DuckieTV#note
and then after saving the change, shutdown both qBt and Dtv completely and start qBt first then a little later Dtv, and see if that solve your problem.
Report results please. Thanks.

**Comment by gilimel** [comment]
Hi thank you
It helped
I noticed there are issues with limetorrent specifically
Other source worked great

Is there a known issue with limetorrent?

Thanks!
Gili

**Comment by garfield69** [comment]
yes, limetorrents changed domains from .cc to .info back in Oct 2018
two choices:
1. Replace Dtv's limetorrents with the one from Jackett  https://github.com/SchizoDuckie/DuckieTV/wiki/Using-Jackett-with-DuckieTV
2. OR switch to using the Standalone Dtv Nightly (essentially Dtv 1.1.6 beta) to get the latest enhancements and native Search Engine updates https://github.com/DuckieTV/Nightlies/releases

**Comment by gilimel** [comment]
Hi
thank you for the support
I installed the latest nightly build from 2019-04-05
still getting issues with LimeTorrents (other sources are fine i believe )
- FYI
see screenshot attached

i will also try Jackett soon.
Gili

**Comment by garfield69** [comment]
there is no screenshot attached in your last post.
but no matter, I have checked out the Dtv native limetorrents search engine for myself, and see that the magnet link needs updating. I'll post a fix shortly, and when the next Nightly is published in about 6 hours or so, you should be good to go.

**Comment by garfield69** [comment]
Seems the buildbot has gone into a funk and did not publish today. That can happen occasionally when it runs of of hd space. Usually the disk cleanup that kicks off once a week will free up enough space for it to kick back into life sooner or later, so for now we just have to wait.

**Comment by gilimel** [comment]
Thank you for all the support!
I will get the latest version tomorrow and update,
I really appreciate the support and the app
It’s great
Gili

**Comment by garfield69** [comment]
build-bot is working again. https://github.com/DuckieTV/Nightlies/releases/tag/nightly-201904110130
