### ISSUE TITLE
build-bot in trouble again

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#1169]
It's been 5 days since the build-bot published a nightly.
I suspect it may be in trouble again.
@SchizoDuckie  could you please take a look?
thanks.

**Comment by garfield69** [comment]
\o/
https://github.com/DuckieTV/Nightlies/releases/tag/nightly-201904110130

**Comment by SchizoDuckie** [comment]
Yeah those nwms upgtades eat *a lot* of disk space when there is still a cached version.

**Comment by garfield69** [comment]
So I guess I need to time my nwjs update just after the disk cleanup and before the next build.
what day does the clean up happen and at what time UTC?

**Comment by SchizoDuckie** [comment]
I'll see if i can fit in some code that cleans up the nwjs download cache
when changing versions

**Comment by garfield69** [comment]
It's been 6 days since the build-bot published a nightly.
I suspect it may be in trouble again.
@SchizoDuckie could you please take a look?
thanks.

**Comment by garfield69** [comment]
\o/ buildbot has just generated a build.

**Comment by Js41637** [comment]
The chrome webstore version of the nightly hasn't been updated for several weeks?
https://chrome.google.com/webstore/detail/duckietv-new-tab-mode-nig/jndkngpbgmnkbhbjafmjhabcjmgeogfc
