### ISSUE TITLE
libGLESv2.so and libEGL.so missing from "Linux" download

### ISSUE THREAD

**Issue by UMLAUTaxl** [SchizoDuckie/DuckieTV#1170]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Stable 1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
Linux (Debian 9.8 (stable))

**Describe the problem you are having and steps to reproduce if available**
Download automatically selected DuckieTV-1.1.5-ubuntu-x64.deb from http://schizoduckie.github.io/DuckieTV/#welcome
Install (no dependency problems) and click icon
DuckieTV doesn't start. CPU usage goes up.
When started from command line it says "Failed to load /opt/DuckieTV/swiftshader/libGLESv2.so"
Which I can fix by creating /opt/DuckieTV/swiftshader/
And copy over the file from a Google Chrome installation (/opt/google/chrome/swiftshader/)
With the next start it says "Failed to load /opt/DuckieTV/swiftshader/libEGL.so"
So I copy over that file too from Chrome.
Now it starts.

**Attach any DuckieTV statistics or Developer Console logs if available**
(How to start Developer Console mode?)

**Comment by garfield69** [comment]
as you may know, the standalone Dtv makes use of [nwjs](https://nwjs.io/) for its run time chromium environment support.
the [nwjs version](https://dl.nwjs.io/v0.25.0/) included with the Dtv 1.1.5 package did not have the swiftshader lib included, this was added to nwjs later with https://github.com/nwjs/nw.js/issues/6142

you are the first to report this, obviously this lib is not used by the majority of Dtv standalone users.

However, future releases of Dtv include this lib, and you may like to upgrade your Dtv 1.1.5 to the latest Nightly version which has all the latest fixes and enhancements from https://github.com/DuckieTV/Nightlies/releases

**Comment by UMLAUTaxl** [comment]
Well, maybe you could just symlink those?

**Comment by garfield69** [comment]
We are not compiling nwjs, we run our javascript using the nwjs runtime environment.
