### ISSUE TITLE
DuckieTV Connected to Transmission BT, magnet links not being added to transmission client

### ISSUE THREAD

**Issue by Infallibleman** [SchizoDuckie/DuckieTV#1172]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**

macOS 1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
high Sierra

**Describe the problem you are having and steps to reproduce if available**
click on the episode to auto download in Duckie tv, get the notification that its being added to the transmission bt client, but nothing happens.

**Attach any DuckieTV statistics or Developer Console logs if available**

DuckieTV Web Based | 1.1.5
-- | --
Current Date and Time | Sun, 12 May 2019 02:59:33 GMT
NWJS, Chromium | 0.25.0 , 61.0.3163.79
UserAgent | DuckieTV-Standalone v1.1.5 Macintosh; Intel Mac OS X 10_13_6
Platform, Vendor | MacIntel, Google Inc.
Screen (width x height) | 1280 x 800
Default Search Engine | LimeTorrents (Enabled)
Default Torrent Client | Transmission (Enabled and Connected to Host)
Auto Download Service | (Enabled and Active)
Last checked TraktTV for DB updates on | Sun, 12 May 2019 00:13:43 GMT
User Preferences on Local Storage | {   "ThePirateBay.mirror": "https://thepiratebay.org",   "application.language": "en_us",   "application.locale": "en_us",   "aria2.port": 6800,   "aria2.server": "http://localhost",   "aria2.token": "",   "autobackup.period": "never",   "autodownload.delay": 15,   "autodownload.multiSE": {     "ThePirateBay": true,     "1337x": true,     "IsoHunt": true,     "KATcr": true,     "Nyaa": true,     "RarBG": true,     "ShowRSS": true,     "TorrentDownloads": true,     "TorrentZ2": true,     "Zooqle": true,     "EzTV.ag": true,     "Idope": true,     "LimeTorrents": true,     "SkyTorrents": true   },   "autodownload.multiSE.enabled": false,   "autodownload.period": 3,   "background-rotator.opacity": "0.8",   "biglybt.password": "*****",   "biglybt.path": "/transmission/rpc",   "biglybt.port": 9091,   "biglybt.progressX100": true,   "biglybt.server": "http://localhost",   "biglybt.use_auth": true,   "biglybt.username": "biglybt",   "calendar.mode": "date",   "calendar.show-downloaded": true,   "calendar.show-episode-numbers": true,   "calendar.show-specials": false,   "calendar.startSunday": true,   "client.determinedlocale": "en_us",   "deluge.password": "*****",   "deluge.port": 8112,   "deluge.server": "http://localhost",   "deluge.use_auth": true,   "download.ratings": true,   "episode.watched-downloaded.pairing": true,   "kc.always": false,   "ktorrent.password": "*****",   "ktorrent.port": 8080,   "ktorrent.server": "http://localhost",   "ktorrent.use_auth": true,   "ktorrent.username": "ktorrent",   "lastSync": -1,   "library.order.by": "getSortName()",   "library.order.reverseList": [     true,     false,     true,     true   ],   "library.seriesgrid": false,   "library.smallposters": true,   "main.viewmode": "calendar",   "notifications.enabled": true,   "qbittorrent.password": "*****",   "qbittorrent.port": 8080,   "qbittorrent.server": "http://localhost",   "qbittorrent.use_auth": true,   "qbittorrent.username": "admin",   "qbittorrent32plus.password": "*****",   "qbittorrent32plus.port": 8080,   "qbittorrent32plus.server": "http://localhost",   "qbittorrent32plus.use_auth": true,   "qbittorrent32plus.username": "admin",   "rtorrent.path": "/RPC2",   "rtorrent.port": 80,   "rtorrent.server": "http://localhost",   "rtorrent.use_auth": false,   "series.displaymode": "poster",   "series.not-watched-eps-btn": false,   "storage.sync": false,   "subtitles.languages": [     "eng"   ],   "sync.progress": true,   "synology.enabled": true,   "synology.ip": "192.168.x.x",   "synology.password": "*****",   "synology.playback_devices": {},   "synology.port": 5000,   "synology.protocol": "http",   "synology.username": "admin",   "tixati.password": "*****",   "tixati.port": 8888,   "tixati.server": "http://localhost",   "tixati.use_auth": true,   "tixati.username": "admin",   "topSites.enabled": false,   "topSites.mode": "onhover",   "torrentDialog.2.activeSE": {     "ThePirateBay": true,     "1337x": true,     "IsoHunt": true,     "KATcr": true,     "Nyaa": true,     "RarBG": true,     "ShowRSS": true,     "TorrentDownloads": true,     "TorrentZ2": true,     "Zooqle": true   },   "torrentDialog.2.enabled": false,   "torrentDialog.2.sortBy": "+engine",   "torrentDialog.showAdvanced.enabled": true,   "torrenting.autodownload": true,   "torrenting.autostop": true,   "torrenting.autostop_all": false,   "torrenting.client": "Transmission",   "torrenting.directory": true,   "torrenting.enabled": true,   "torrenting.global_size_max": null,   "torrenting.global_size_max_enabled": true,   "torrenting.global_size_min": null,   "torrenting.global_size_min_enabled": true,   "torrenting.ignore_keywords": "",   "torrenting.ignore_keywords_enabled": true,   "torrenting.label": false,   "torrenting.launch_via_chromium": true,   "torrenting.min_seeders": 50,   "torrenting.min_seeders_enabled": false,   "torrenting.progress": true,   "torrenting.require_keywords": "",   "torrenting.require_keywords_enabled": true,   "torrenting.require_keywords_mode_or": true,   "torrenting.searchprovider": "LimeTorrents",   "torrenting.searchquality": "1080p",   "torrenting.searchqualitylist": [     "480p",     "HDTV",     "720p",     "1080p",     "2160p"   ],   "torrenting.streaming": true,   "trakt-update.period": 12,   "trakttv.passwordHash": "*****",   "trakttv.sync": false,   "trakttv.username": null,   "transmission.password": "*****",   "transmission.path": "/transmission/rpc",   "transmission.port": 9091,   "transmission.progressX100": true,   "transmission.server": "http://127.0.0.1",   "transmission.use_auth": true,   "transmission.username": "admin",   "utorrentwebui.password": "*****",   "utorrentwebui.port": 8080,   "utorrentwebui.server": "http://localhost",   "utorrentwebui.use_auth": true,   "utorrentwebui.username": "admin",   "vuze.password": "*****",   "vuze.path": "/transmission/rpc",   "vuze.port": 9091,   "vuze.progressX100": true,   "vuze.server": "http://localhost",   "vuze.use_auth": true,   "vuze.username": "vuze",   "autodownload.lastrun": 1557629570529 }
Other significant Local Storage keys | {   "1.1.4TorrentHashListCleanup": "Sat May 11 2019 19:13:41 GMT-0500 (CDT)",   "1.1.4cleanupOrphanedEpisodes": "Sat May 11 2019 19:13:39 GMT-0500 (CDT)",   "1.1.4cleanupOrphanedSeasons": "Sat May 11 2019 19:13:40 GMT-0500 (CDT)",   "1.1.4qBittorrentPre32": "Sat May 11 2019 19:13:34 GMT-0500 (CDT)",   "1.1.4refresh": "Sat May 11 2019 19:13:45 GMT-0500 (CDT)",   "1.1.4refreshTrendingCache": "Sat May 11 2019 19:13:34 GMT-0500 (CDT)",   "1.1.4updateTransmissionPath": "Sat May 11 2019 19:13:34 GMT-0500 (CDT)",   "1.1.5FetchFirstXemAliasMap": "Sat May 11 2019 19:13:34 GMT-0500 (CDT)",   "1.1.5deleteSearchEngines": "Sat May 11 2019 19:13:34 GMT-0500 (CDT)",   "1.1.5fanartCleanup": "Sat May 11 2019 19:14:05 GMT-0500 (CDT)",   "1.1.5updateDelugeAuth": "Sat May 11 2019 19:13:34 GMT-0500 (CDT)",   "1.1.5updateTorrenting.min_seeders": "Sat May 11 2019 19:13:34 GMT-0500 (CDT)",   "1.1migration": "Sat May 11 2019 19:13:39 GMT-0500 (CDT)",   "autobackup.lastrun": "1557620014799",   "database.version.Episodes": "14",   "database.version.Fanart": "1",   "database.version.Jackett": "2",   "database.version.Seasons": "6",   "database.version.Series": "16",   "database.version.WatchList": "1",   "database.version.WatchListObject": "1",   "fanart.bootstrapped": "1",   "github.lastupdatecheck": "1557620017579",   "install.notify": "1.1.5",   "runtime.event": "{\"reason\":\"install\"}",   "snr.lastFetched": "1557620016836",   "standalone.alwaysShowTray": "Y",   "standalone.closeSystray": "Y",   "standalone.minimizeSystray": "Y",   "standalone.position": "{\"width\":1000,\"height\":709,\"x\":140,\"y\":23,\"state\":\"normal\"}",   "standalone.zoomlevel": "6",   "torrenting.client": "Transmission",   "trackers.lastFetched": "1557620016840",   "trakttv.lastupdated": "1557620023274",   "trakttv.lastupdated.trending": "1557628395553",   "upgrade.notify": "1.1.5",   "xem.lastFetched": "1557620016846" }
DB Series | 3
DB Series Hidden From Calendar | 0
DB Seasons | 20
DB Episodes | 230
DB Fanart | 1926
DB Jackett | 0

**Comment by Infallibleman** [comment]
have tried complelety uninstalling and reinstalling Duckie TV. will randomly work. please assist.

**Comment by Zap123** [comment]
I don't know if it's the same issue but to me it only happens for certain torrent, not all of them.

**Comment by x8machina8x** [comment]
Mine having the same issue.
ISSUE: Searched the Torrent and clicking Download magnet, Download .torrent, Magnet Link does nothing. Clicking the (i) open the website.

Setup:
macOS 10.15.4
DuckieTV 1.1.5
Transmission 2.8 and 3.0.0 both didn't work.
Transmission Integration is green and connected.

Anybody found the solution yet?

**Comment by garfield69** [comment]
First thing to try is upgrade **Dtv 1.1.5** to the _Nightly_ Dtv from https://github.com/DuckieTV/Nightlies/releases
Note: on MacOs you first need to trashbin the Dtv app from your applications folder, otherwise the installer will silently fail to upgrade. Dont ask my why, I didn't write the thing.

Second thing to do is double check that **Dtv > Settings > Torrent > Torrent Parameters** is set to _disabled_ (there should be a red X to the right of the title).

The latest nightly should have working Search Engines and up to date torrent clients.
Also comes with the Development Toolpack, which will let us look at the logs and do more diagnostics if you still end up with a problem.

**Comment by garfield69** [comment]
Make sure you fetch the latest Nightly Dtv from https://github.com/DuckieTV/Nightlies/releases
and remember to first bin the DuckieTV app from your applications folder so that the Nightly Installer can work. (Check the About side panel for the correct version in the Title).
