### ISSUE TITLE
DuckiTV Not Parsing qBittorrent Magnet Links For Vers. 4.1.5 And 4.1.6

### ISSUE THREAD

**Issue by lynxstrike** [SchizoDuckie/DuckieTV#1173]
DuckieTV Ver.     DuckieTV-201904170130-windows-x64
Windows 10 Pro 1809    Build 17763.503

DuckieTV do not parse magnetic links for qBittorrent versions 4.1.5 and 4.1.6.
Works fine with versions 4.1.4 and older.

Thanks!

**Comment by garfield69** [comment]
have you read and apllied https://github.com/SchizoDuckie/DuckieTV/wiki/Setting-up-qBitTorrent-3.2-with-DuckieTV#note ?

**Comment by lynxstrike** [comment]
> have you read and apllied https://github.com/SchizoDuckie/DuckieTV/wiki/Setting-up-qBitTorrent-3.2-with-DuckieTV#note ?

Thanks for your help. Applying your suggestion resolved the issue.
