### ISSUE TITLE
Current day on calendar not updated when resuming laptop after midnight

### ISSUE THREAD

**Issue by marcelpaulo** [SchizoDuckie/DuckieTV#1177]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Latest angular (260d8494)

**What is your Operating System (Windows, Mac, Linux, Android)**
Linux (Xubuntu 18.04.02)

**Describe the problem you are having and steps to reproduce if available**
This is really low priority, I stumbled across it by accident, and today it happend again because I went to bed really early yesterday, around 10 pm, suspended my laptop before I did, while DuckieTV was running, and resumed it around 2 am today.
1. Run DuckieTV
2. Suspend the computer before midnight
3. Resume the computer after midnight
The current day on the calendar doesn't change:
![image](https://user-images.githubusercontent.com/10074769/59008361-bcc64a00-8800-11e9-88d6-b4eebff16624.png)

This issue looks like #378.

**Attach any DuckieTV statistics or Developer Console logs if available**
[
  {
    "name": "DuckieTV Web Based",
    "data": "1.1.6"
  },
  {
    "name": "Current Date and Time",
    "data": "Thu, 06 Jun 2019 05:16:02 GMT"
  },
  {
    "name": "NWJS, Chromium",
    "data": "0.31.3 , 67.0.3396.87"
  },
  {
    "name": "UserAgent",
    "data": "DuckieTV-Standalone v1.1.6 X11; Linux x86_64"
  },
  {
    "name": "Platform, Vendor",
    "data": "Linux x86_64, Google Inc."
  },
  {
    "name": "Screen (width x height)",
    "data": "1366 x 768"
  },
  {
    "name": "Default Search Engine",
    "data": "RarBG [Jackett] (Enabled)"
  },
  {
    "name": "Default Torrent Client",
    "data": "Transmission (Enabled and Connected to Host)"
  },
  {
    "name": "Auto Download Service",
    "data": "(Disabled)"
  },
  {
    "name": "Last checked TraktTV for DB updates on",
    "data": "Wed, 05 Jun 2019 23:29:32 GMT"
  },
  {
    "name": "User Preferences on Local Storage",
    "data": "{\n  \"ThePirateBay.mirror\": \"https://thepiratebay.org\",\n  \"application.language\": \"en_us\",\n  \"application.locale\": \"en_us\",\n  \"autobackup.period\": \"weekly\",\n  \"autodownload.delay\": 15,\n  \"autodownload.multiSE\": {\n    \"ThePirateBay\": true,\n    \"1337x\": true,\n    \"IsoHunt\": true,\n    \"KATcr\": true,\n    \"Nyaa\": true,\n    \"RarBG\": true,\n    \"ShowRSS\": true,\n    \"TorrentDownloads\": true,\n    \"TorrentZ2\": true,\n    \"Zooqle\": true,\n    \"EzTV.ag\": true,\n    \"Idope\": true,\n    \"LimeTorrents\": true,\n    \"SkyTorrents\": true,\n    \"ETTV\": true,\n    \"ETag\": true,\n    \"IsoHunt2\": true,\n    \"Demonoid\": true,\n    \"bj-share\": true,\n    \"BJ-Share\": true,\n    \"KickAssTorrent\": true,\n    \"TGx\": true\n  },\n  \"autodownload.multiSE.enabled\": false,\n  \"autodownload.period\": 1,\n  \"background-rotator.opacity\": \"0.4\",\n  \"calendar.mode\": \"date\",\n  \"calendar.show-downloaded\": true,\n  \"calendar.show-episode-numbers\": true,\n  \"calendar.show-specials\": false,\n  \"calendar.startSunday\": false,\n  \"client.determinedlocale\": \"en_us\",\n  \"download.ratings\": true,\n  \"episode.watched-downloaded.pairing\": true,\n  \"kc.always\": false,\n  \"lastSync\": -1,\n  \"library.order.by\": \"getSortName()\",\n  \"library.order.reverseList\": [\n    true,\n    false,\n    true,\n    true\n  ],\n  \"library.seriesgrid\": false,\n  \"library.smallposters\": true,\n  \"main.viewmode\": \"calendar\",\n  \"notifications.enabled\": false,\n  \"series.displaymode\": \"poster\",\n  \"series.not-watched-eps-btn\": true,\n  \"storage.sync\": false,\n  \"subtitles.languages\": [\n    \"eng\"\n  ],\n  \"sync.progress\": true,\n  \"synology.enabled\": true,\n  \"synology.ip\": \"192.168.x.x\",\n  \"synology.password\": \"*****\",\n  \"synology.playback_devices\": {},\n  \"synology.port\": 5000,\n  \"synology.protocol\": \"http\",\n  \"synology.username\": \"admin\",\n  \"topSites.enabled\": false,\n  \"topSites.mode\": \"onhover\",\n  \"torrentDialog.2.activeSE\": {\n    \"ThePirateBay\": true,\n    \"1337x\": true,\n    \"IsoHunt\": true,\n    \"KATcr\": false,\n    \"Nyaa\": false,\n    \"RarBG\": true,\n    \"ShowRSS\": false,\n    \"TorrentDownloads\": false,\n    \"TorrentZ2\": true,\n    \"Zooqle\": false,\n    \"ETag\": false,\n    \"ETTV\": true,\n    \"EzTV.ag\": true,\n    \"Idope\": false,\n    \"IsoHunt2\": false,\n    \"LimeTorrents\": true,\n    \"Demonoid\": true,\n    \"bj-share\": true,\n    \"BJ-Share\": true,\n    \"KickAssTorrent\": true,\n    \"IdopeClone\": true,\n    \"TGx\": true\n  },\n  \"torrentDialog.2.enabled\": true,\n  \"torrentDialog.2.sortBy\": \"-seedersInt\",\n  \"torrentDialog.showAdvanced.enabled\": true,\n  \"torrenting.autodownload\": false,\n  \"torrenting.autostop\": false,\n  \"torrenting.autostop_all\": false,\n  \"torrenting.client\": \"Transmission\",\n  \"torrenting.directory\": true,\n  \"torrenting.enabled\": true,\n  \"torrenting.global_size_max\": null,\n  \"torrenting.global_size_max_enabled\": true,\n  \"torrenting.global_size_min\": null,\n  \"torrenting.global_size_min_enabled\": true,\n  \"torrenting.ignore_keywords\": \"\",\n  \"torrenting.ignore_keywords_enabled\": true,\n  \"torrenting.label\": false,\n  \"torrenting.launch_via_chromium\": false,\n  \"torrenting.min_seeders\": 50,\n  \"torrenting.min_seeders_enabled\": false,\n  \"torrenting.progress\": false,\n  \"torrenting.require_keywords\": \"\",\n  \"torrenting.require_keywords_enabled\": true,\n  \"torrenting.require_keywords_mode_or\": true,\n  \"torrenting.searchprovider\": \"RarBG\",\n  \"torrenting.searchquality\": \"\",\n  \"torrenting.searchqualitylist\": [\n    \"480p\",\n    \"HDTV\",\n    \"720p\",\n    \"1080p\",\n    \"2160p\"\n  ],\n  \"torrenting.streaming\": true,\n  \"trakt-update.period\": 6,\n  \"trakttv.passwordHash\": \"*****\",\n  \"trakttv.sync\": true,\n  \"trakttv.username\": null,\n  \"transmission.password\": \"*****\",\n  \"transmission.path\": \"/transmission/rpc\",\n  \"transmission.port\": 9091,\n  \"transmission.progressX100\": true,\n  \"transmission.server\": \"http://localhost\",\n  \"transmission.use_auth\": false,\n  \"transmission.username\": \"admin\",\n  \"font.bebas.enabled\": false,\n  \"autodownload.lastrun\": 1530399938569\n}"
  },
  {
    "name": "Other significant Local Storage keys",
    "data": "{\n  \"1.1.4TorrentHashListCleanup\": \"Sun Dec 17 2017 23:22:52 GMT-0200 (-02)\",\n  \"1.1.4cleanupOrphanedEpisodes\": \"Sun Dec 17 2017 23:22:36 GMT-0200 (-02)\",\n  \"1.1.4cleanupOrphanedSeasons\": \"Sun Dec 17 2017 23:22:37 GMT-0200 (-02)\",\n  \"1.1.4qBittorrentPre32\": \"Sun Dec 17 2017 23:22:32 GMT-0200 (-02)\",\n  \"1.1.4refresh\": \"Sun Dec 17 2017 23:22:42 GMT-0200 (-02)\",\n  \"1.1.4refreshTrendingCache\": \"Sun Dec 17 2017 23:22:32 GMT-0200 (-02)\",\n  \"1.1.4updateTransmissionPath\": \"Sun Dec 17 2017 23:22:32 GMT-0200 (-02)\",\n  \"1.1.5FetchFirstXemAliasMap\": \"Sun Dec 17 2017 23:22:32 GMT-0200 (-02)\",\n  \"1.1.5deleteSearchEngines\": \"Sun Dec 17 2017 23:22:32 GMT-0200 (-02)\",\n  \"1.1.5fanartCleanup\": \"Sat Apr 28 2018 13:08:27 GMT-0300 (-03)\",\n  \"1.1.5updateDelugeAuth\": \"Sun Dec 17 2017 23:22:32 GMT-0200 (-02)\",\n  \"1.1.5updateTorrenting.min_seeders\": \"Sun Dec 17 2017 23:22:32 GMT-0200 (-02)\",\n  \"1.1.6deleteWatchList\": \"Thu Dec 21 2017 23:25:26 GMT-0200 (-02)\",\n  \"1.1migration\": \"Sun Dec 17 2017 23:22:35 GMT-0200 (-02)\",\n  \"CRUD.DEBUG\": \"false\",\n  \"autobackup.lastrun\": \"1559650546285\",\n  \"database.version.Episodes\": \"14\",\n  \"database.version.Fanart\": \"1\",\n  \"database.version.Jackett\": \"2\",\n  \"database.version.Seasons\": \"6\",\n  \"database.version.Series\": \"16\",\n  \"fanart.bootstrapped\": \"1\",\n  \"font.bebas.disabled\": \"true\",\n  \"github.lastupdatecheck\": \"1513560156988\",\n  \"install.notify\": \"1.1.5\",\n  \"runtime.event\": \"{\\\"reason\\\":\\\"chrome_update\\\"}\",\n  \"snr.lastFetched\": \"1559681091078\",\n  \"standalone.position\": \"{\\\"width\\\":1366,\\\"height\\\":743,\\\"x\\\":0,\\\"y\\\":25,\\\"state\\\":\\\"maximized\\\"}\",\n  \"standalone.zoomlevel\": \"6\",\n  \"torrenting.client\": \"Transmission\",\n  \"trackers.lastFetched\": \"1559330489133\",\n  \"trakttv.lastupdated\": \"1559777372982\",\n  \"trakttv.lastupdated.trending\": \"1559601841203\",\n  \"trakttv.refresh_token\": \"00f6a57021b0f02ee8775b3e439cebfb4e3c7a7a303b174c966a88f6c1b6484b\",\n  \"uniqueId\": \"fcc4c833-d67f-849d-4a18-5daec48c91cf\",\n  \"upgrade.notify\": \"1.1.6\",\n  \"xem.lastFetched\": \"1559681091069\"\n}"
  },
  {
    "name": "DB Series",
    "data": 282
  },
  {
    "name": "DB Series Hidden From Calendar",
    "data": 22
  },
  {
    "name": "DB Seasons",
    "data": 705
  },
  {
    "name": "DB Episodes",
    "data": 6645
  },
  {
    "name": "DB Fanart",
    "data": 4443
  },
  {
    "name": "DB Jackett",
    "data": 8
  }

**Comment by garfield69** [comment]
not likely to be fixed. the browser does not post a "I've just come out of hibernation' event, so the Dtv chrome extension angularjs does not know it needs to refresh the calendar or reset timers.
the standalone version is the same code running under nwjs runtime environment using the chromium engine so same thing applies.
