### ISSUE TITLE
DuckieTV + QBT 4.1.4 Connected But Not Downloading

### ISSUE THREAD

**Issue by speeddemon007** [SchizoDuckie/DuckieTV#1178]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
1.1.5
**What is your Operating System (Windows, Mac, Linux, Android)**
Windows

**Describe the problem you are having and steps to reproduce if available**
DuckieTV connects to QBT version 4.1.4, the pop up in DT says a download has begun in QBT but nothing is downloading.

Even if I hit the magnet link, only the popup shows but nothing really downloads in QBT.

The issue only started about 5 days ago. I changed nothing for this to happen. Everything worked perfectly previously.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
what Dtv search engine (SE) are you using as the default for your torrent searches?

about 5 days ago _1337x_ changed their web site's torrent download links. 
if you are using this SE then that would cause the symptoms you described.
You will need to either:
* use a different SE (TPB for instance) if you can find one that still works on 1.1.5

or
* upgrade to the latest **Dtv Nightly** from https://github.com/DuckieTV/Nightlies/releases which has a fixed _1337x_ SE

**Comment by speeddemon007** [comment]
Yes, I was using 1337x. Changed to TPB, all good now :) Thanks!

I'll upgrade to the latest nightly version as a more permanent fix. 

Thanks again.
