### ISSUE TITLE
linux and transmission

### ISSUE THREAD

**Issue by pjhalsli** [SchizoDuckie/DuckieTV#1179]
I'm using duckieTv v1.15 and it has been working fine exept the last three days. When I click on a magnet link it dont get added to transmission. I have also tried to download torrentswitout success- they just don't download

...

**What is your Operating System (Windows, Mac, Linux, Android)**
...

**Describe the problem you are having and steps to reproduce if available**
...try to download anything magnetlink or torrent and it won't appear in the transmission and the torrent file won't appear in the download folder

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
are you by any chance using the 1337x Search Engine (SE) ?

about 5 days ago _1337x_ changed their web site's torrent download links. 
if you are using this SE then that would cause the symptoms you described.
You will need to either:
* use a different SE (TPB for instance) if you can find one that still works on 1.1.5

or
* upgrade to the latest **Dtv Nightly** from https://github.com/DuckieTV/Nightlies/releases which has a fixed _1337x_ SE

**Comment by pjhalsli** [comment]
thanks  I was using 1337x actually

problem solved so I close it now
