### ISSUE TITLE
"TypeError: Cannot read property '0' of null" error

### ISSUE THREAD

**Issue by codestool7** [SchizoDuckie/DuckieTV#1181]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 7

**Describe the problem you are having and steps to reproduce if available**
When I search for torrents for Big Little Lies S02E04 in 1080p I get a "TypeError: Cannot read property '0' of null" error and a frowny face.

**Attach any DuckieTV statistics or Developer Console logs if available**
Statistics:
[
  {
    "name": "DuckieTV Web Based",
    "data": "1.1.5"
  },
  {
    "name": "Current Date and Time",
    "data": "Wed, 03 Jul 2019 02:31:41 GMT"
  },
  {
    "name": "NWJS, Chromium",
    "data": "0.25.0 , 61.0.3163.79"
  },
  {
    "name": "UserAgent",
    "data": "DuckieTV-Standalone  v1.1.5 Windows NT 6.1; Win64; x64"
  },
  {
    "name": "Platform, Vendor",
    "data": "Win32, Google Inc."
  },
  {
    "name": "Screen (width x height)",
    "data": "1920 x 1080"
  },
  {
    "name": "Default Search Engine",
    "data": "ThePirateBay (Enabled)"
  },
  {
    "name": "Default Torrent Client",
    "data": "uTorrent (Enabled but Not Connected to Host)"
  },
  {
    "name": "Auto Download Service",
    "data": "(Enabled and Active)"
  },
  {
    "name": "Last checked TraktTV for DB updates on",
    "data": "Tue, 02 Jul 2019 04:00:12 GMT"
  },
  {
    "name": "User Preferences on Local Storage",
    "data": "{\n  \"ThePirateBay.mirror\": \"https://thepiratebay.org\",\n  \"application.language\": \"en_us\",\n  \"application.locale\": \"en_us\",\n  \"aria2.port\": 6800,\n  \"aria2.server\": \"http://localhost\",\n  \"aria2.token\": \"\",\n  \"autobackup.period\": \"monthly\",\n  \"autodownload.delay\": 15,\n  \"autodownload.multiSE\": {\n    \"ThePirateBay\": true,\n    \"1337x\": true,\n    \"IsoHunt\": true,\n    \"KATcr\": true,\n    \"Nyaa\": true,\n    \"RarBG\": true,\n    \"ShowRSS\": true,\n    \"TorrentDownloads\": true,\n    \"TorrentZ2\": true,\n    \"Zooqle\": true,\n    \"EzTV.ag\": true,\n    \"Idope\": true,\n    \"LimeTorrents\": true,\n    \"SkyTorrents\": true\n  },\n  \"autodownload.multiSE.enabled\": false,\n  \"autodownload.period\": 1,\n  \"background-rotator.opacity\": \"0.5\",\n  \"biglybt.password\": \"*****\",\n  \"biglybt.path\": \"/transmission/rpc\",\n  \"biglybt.port\": 9091,\n  \"biglybt.progressX100\": true,\n  \"biglybt.server\": \"http://localhost\",\n  \"biglybt.use_auth\": true,\n  \"biglybt.username\": \"biglybt\",\n  \"calendar.mode\": \"date\",\n  \"calendar.show-downloaded\": true,\n  \"calendar.show-episode-numbers\": false,\n  \"calendar.show-specials\": true,\n  \"calendar.startSunday\": true,\n  \"client.determinedlocale\": \"en_us\",\n  \"deluge.password\": \"*****\",\n  \"deluge.port\": 8112,\n  \"deluge.server\": \"http://localhost\",\n  \"deluge.use_auth\": true,\n  \"download.ratings\": true,\n  \"episode.watched-downloaded.pairing\": true,\n  \"kc.always\": false,\n  \"ktorrent.password\": \"*****\",\n  \"ktorrent.port\": 8080,\n  \"ktorrent.server\": \"http://localhost\",\n  \"ktorrent.use_auth\": true,\n  \"ktorrent.username\": \"ktorrent\",\n  \"lastSync\": -1,\n  \"library.order.by\": \"getSortName()\",\n  \"library.order.reverseList\": [\n    true,\n    false,\n    true,\n    true\n  ],\n  \"library.seriesgrid\": true,\n  \"library.smallposters\": true,\n  \"main.viewmode\": \"calendar\",\n  \"notifications.enabled\": true,\n  \"qbittorrent.password\": \"*****\",\n  \"qbittorrent.port\": 8080,\n  \"qbittorrent.server\": \"http://localhost\",\n  \"qbittorrent.use_auth\": true,\n  \"qbittorrent.username\": \"admin\",\n  \"qbittorrent32plus.password\": \"*****\",\n  \"qbittorrent32plus.port\": 8080,\n  \"qbittorrent32plus.server\": \"http://localhost\",\n  \"qbittorrent32plus.use_auth\": true,\n  \"qbittorrent32plus.username\": \"admin\",\n  \"rtorrent.path\": \"/RPC2\",\n  \"rtorrent.port\": 80,\n  \"rtorrent.server\": \"http://localhost\",\n  \"rtorrent.use_auth\": false,\n  \"series.displaymode\": \"poster\",\n  \"series.not-watched-eps-btn\": false,\n  \"storage.sync\": false,\n  \"subtitles.languages\": [\n    \"eng\"\n  ],\n  \"sync.progress\": true,\n  \"synology.enabled\": true,\n  \"synology.ip\": \"192.168.x.x\",\n  \"synology.password\": \"*****\",\n  \"synology.playback_devices\": {},\n  \"synology.port\": 5000,\n  \"synology.protocol\": \"http\",\n  \"synology.username\": \"admin\",\n  \"tixati.password\": \"*****\",\n  \"tixati.port\": 8888,\n  \"tixati.server\": \"http://localhost\",\n  \"tixati.use_auth\": true,\n  \"tixati.username\": \"admin\",\n  \"topSites.enabled\": false,\n  \"topSites.mode\": \"onhover\",\n  \"torrentDialog.2.activeSE\": {\n    \"ThePirateBay\": true,\n    \"1337x\": true,\n    \"IsoHunt\": true,\n    \"KATcr\": true,\n    \"Nyaa\": true,\n    \"RarBG\": true,\n    \"ShowRSS\": true,\n    \"TorrentDownloads\": true,\n    \"TorrentZ2\": true,\n    \"Zooqle\": true\n  },\n  \"torrentDialog.2.enabled\": false,\n  \"torrentDialog.2.sortBy\": \"+engine\",\n  \"torrentDialog.showAdvanced.enabled\": true,\n  \"torrenting.autodownload\": true,\n  \"torrenting.autostop\": true,\n  \"torrenting.autostop_all\": false,\n  \"torrenting.client\": \"uTorrent\",\n  \"torrenting.directory\": true,\n  \"torrenting.enabled\": true,\n  \"torrenting.global_size_max\": null,\n  \"torrenting.global_size_max_enabled\": true,\n  \"torrenting.global_size_min\": null,\n  \"torrenting.global_size_min_enabled\": true,\n  \"torrenting.ignore_keywords\": \"\",\n  \"torrenting.ignore_keywords_enabled\": true,\n  \"torrenting.label\": false,\n  \"torrenting.launch_via_chromium\": false,\n  \"torrenting.min_seeders\": 50,\n  \"torrenting.min_seeders_enabled\": false,\n  \"torrenting.progress\": true,\n  \"torrenting.require_keywords\": \"\",\n  \"torrenting.require_keywords_enabled\": true,\n  \"torrenting.require_keywords_mode_or\": true,\n  \"torrenting.searchprovider\": \"ThePirateBay\",\n  \"torrenting.searchquality\": \"1080p\",\n  \"torrenting.searchqualitylist\": [\n    \"480p\",\n    \"HDTV\",\n    \"720p\",\n    \"1080p\",\n    \"2160p\"\n  ],\n  \"torrenting.streaming\": false,\n  \"trakt-update.period\": 12,\n  \"trakttv.passwordHash\": \"*****\",\n  \"trakttv.sync\": false,\n  \"trakttv.username\": null,\n  \"transmission.password\": \"*****\",\n  \"transmission.path\": \"/transmission/rpc\",\n  \"transmission.port\": 9091,\n  \"transmission.progressX100\": true,\n  \"transmission.server\": \"http://localhost\",\n  \"transmission.use_auth\": true,\n  \"transmission.username\": \"admin\",\n  \"utorrentwebui.password\": \"*****\",\n  \"utorrentwebui.port\": 8080,\n  \"utorrentwebui.server\": \"http://localhost\",\n  \"utorrentwebui.use_auth\": true,\n  \"utorrentwebui.username\": \"admin\",\n  \"vuze.password\": \"*****\",\n  \"vuze.path\": \"/transmission/rpc\",\n  \"vuze.port\": 9091,\n  \"vuze.progressX100\": true,\n  \"vuze.server\": \"http://localhost\",\n  \"vuze.use_auth\": true,\n  \"vuze.username\": \"vuze\"\n}"
  },
  {
    "name": "Other significant Local Storage keys",
    "data": "{\n  \"1.1.4TorrentHashListCleanup\": \"Sun Mar 31 2019 20:51:21 GMT-0400 (Eastern Daylight Time)\",\n  \"1.1.4cleanupOrphanedEpisodes\": \"Sun Mar 31 2019 20:51:19 GMT-0400 (Eastern Daylight Time)\",\n  \"1.1.4cleanupOrphanedSeasons\": \"Sun Mar 31 2019 20:51:20 GMT-0400 (Eastern Daylight Time)\",\n  \"1.1.4qBittorrentPre32\": \"Sun Mar 31 2019 20:51:15 GMT-0400 (Eastern Daylight Time)\",\n  \"1.1.4refresh\": \"Sun Mar 31 2019 20:51:25 GMT-0400 (Eastern Daylight Time)\",\n  \"1.1.4refreshTrendingCache\": \"Sun Mar 31 2019 20:51:15 GMT-0400 (Eastern Daylight Time)\",\n  \"1.1.4updateTransmissionPath\": \"Sun Mar 31 2019 20:51:15 GMT-0400 (Eastern Daylight Time)\",\n  \"1.1.5FetchFirstXemAliasMap\": \"Sun Mar 31 2019 20:51:15 GMT-0400 (Eastern Daylight Time)\",\n  \"1.1.5deleteSearchEngines\": \"Sun Mar 31 2019 20:51:15 GMT-0400 (Eastern Daylight Time)\",\n  \"1.1.5fanartCleanup\": \"Sun Mar 31 2019 20:51:45 GMT-0400 (Eastern Daylight Time)\",\n  \"1.1.5updateDelugeAuth\": \"Sun Mar 31 2019 20:51:15 GMT-0400 (Eastern Daylight Time)\",\n  \"1.1.5updateTorrenting.min_seeders\": \"Sun Mar 31 2019 20:51:15 GMT-0400 (Eastern Daylight Time)\",\n  \"1.1migration\": \"Sun Mar 31 2019 20:51:18 GMT-0400 (Eastern Daylight Time)\",\n  \"autobackup.lastrun\": \"1554079875369\",\n  \"database.version.Episodes\": \"14\",\n  \"database.version.Fanart\": \"1\",\n  \"database.version.Jackett\": \"2\",\n  \"database.version.Seasons\": \"6\",\n  \"database.version.Series\": \"16\",\n  \"database.version.WatchList\": \"1\",\n  \"database.version.WatchListObject\": \"1\",\n  \"fanart.bootstrapped\": \"1\",\n  \"github.lastupdatecheck\": \"1554079876221\",\n  \"install.notify\": \"1.1.5\",\n  \"runtime.event\": \"{\\\"reason\\\":\\\"install\\\"}\",\n  \"snr.lastFetched\": \"1562040003745\",\n  \"standalone.alwaysShowTray\": \"N\",\n  \"standalone.closeSystray\": \"Y\",\n  \"standalone.minimizeSystray\": \"N\",\n  \"standalone.position\": \"{\\\"width\\\":1922,\\\"height\\\":1042,\\\"x\\\":0,\\\"y\\\":0,\\\"state\\\":\\\"maximized\\\"}\",\n  \"standalone.startupMinimized\": \"Y\",\n  \"standalone.zoomlevel\": \"6\",\n  \"torrenting.client\": \"uTorrent\",\n  \"trackers.lastFetched\": \"1559709794084\",\n  \"trakttv.lastupdated\": \"1562040012360\",\n  \"trakttv.lastupdated.trending\": \"1561953611782\",\n  \"upgrade.notify\": \"1.1.5\",\n  \"xem.lastFetched\": \"1562040003747\"\n}"
  },
  {
    "name": "DB Series",
    "data": 20
  },
  {
    "name": "DB Series Hidden From Calendar",
    "data": 0
  },
  {
    "name": "DB Seasons",
    "data": 74
  },
  {
    "name": "DB Episodes",
    "data": 909
  },
  {
    "name": "DB Fanart",
    "data": 2174
  },
  {
    "name": "DB Jackett",
    "data": 0
  }
]

**Comment by codestool7** [comment]
trying to add a screenshot but it won't let me

**Comment by garfield69** [comment]
this is a problem at TPB, which is currently going through some hiccups.
![image](https://user-images.githubusercontent.com/6933240/60559382-55b89880-9da0-11e9-8031-fa5a0b5a208f.png)
nothing we can do about this. 
You could switch to using another Search Engine if you can find one that works, or upgrade to the latest Dtv Nightly from https://github.com/DuckieTV/Nightlies/releases which has more _working_ SE to choose, while you wait for TPB to sort things out.

**Comment by garfield69** [comment]
Oh, an additional thought occurred to me.
Sometimes when TPB is not working properly, Dtv switches to trying one of the alternate TPB proxies. But many of them are broken these days.
To get Dtv to get back to trying the official site you may need to restart Dtv. 
So this is another thing you can try if your searches keep returning sad faces.

Once you are on a Nightly, you can take a look at the log (press F12 and click on the Console tab to view) and this will at least give you the error message that occurs when the search using TPB fails, which may be useful.
