### ISSUE TITLE
1337 SE

### ISSUE THREAD

**Issue by ekko20six** [SchizoDuckie/DuckieTV#1182]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...Standalone on macOS 

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...Nightly release for 05-07-2019 01:55:47

**What is your Operating System (Windows, Mac, Linux, Android)**
...Mac OS latest (not testing the beta)

**Describe the problem you are having and steps to reproduce if available**
...1337 search stopped working as others have reported, a reddit post suggested trying the nightly which had fixed it but it is still not working, rarbg still works though

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
works for me on my win10 VB mojave image.
startup your Dtv, and click on the (i) Info icon to view details.
Does the app title reflect the 20190705... or is it still saying DuckieTV 1.1.5 ?
if it has not changed, then open the applications folder and move the DuckieTV.app to the bin, then rerun the Nightly install.
and try your test again.

**Comment by ekko20six** [comment]
aha, it would seem the installer did not update to the nightly, delete from applications, ran it again and as you said all is working now.
I could see immediately it was a new version s there was a play button that the old one didn't have but also check the (i) as well to confirm and all good.

Cheers
