### ISSUE TITLE
Downloading Wrong Episode / Previous Season But Correct Episode Number

### ISSUE THREAD

**Issue by roshurwill** [SchizoDuckie/DuckieTV#1183]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
windows 7 64bit

**Describe the problem you are having and steps to reproduce if available**
I go to search for an episode of american dad to download for example s16e09 and i click manual search it will come up with s15e09, same goes with auto download, i believe it only does it for this program

**Attach any DuckieTV statistics or Developer Console logs if available**

**Comment by lonelyfairie** [comment]
Please refer to: https://github.com/SchizoDuckie/DuckieTV/issues/1043#issuecomment-370164186

**Comment by garfield69** [comment]
sometimes [thexem](http://thexem.de) fall behind in keeping the cross reference up to date and the latest few episodes of American Dad do not have a cross reference.
when that happens, Dtv uses the s/e provided by [Trakt.tv](https://trakt.tv)
