### ISSUE TITLE
DuckieTV utorrent Limetorrents doesn't start torrents

### ISSUE THREAD

**Issue by Mike45900** [SchizoDuckie/DuckieTV#1185]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))** 
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Nightly 201907230130

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 7

**Describe the problem you are having and steps to reproduce if available**
When I try to download using Limetorrents as the search engine I get a DuckieTV popup saying 
Download started on uTorrent WebUI, however that torrent never shows up in uTorrent. Everything works fine if I use ThePirateBay as the search engine. BTW I am using uTorrent 3.5.5 using webui 

**Attach any DuckieTV statistics or Developer Console logs if available**
I'd attach logs if I knew where they were. I get no other messages.

**Comment by garfield69** [comment]
Hmm. Odd.
Take a look at the log. you'll find it by pressing the **F12** key, which opens the *development Tools* page, and clicking on the **Console** tab.
see if there are any messages related to limetorrents.

Also, on the main Dtv page, click on the *(i) About* icon to open that side panel, scroll down to the *Statistics* section and click on the *Statistics* title.
this should copy the stats to your clipboard. 
Paste the stats here in a code-block so I can take a look.

Finally, can you give me an example of the series and episode that you are trying to download, so I can try it out. I tested https://www.limetorrents.info/Legion-S03E05-720p-HEVC-x265-MeGusta-torrent-13214181.html on my Dtv win10 standalone Nightly without issue.
