### ISSUE TITLE
Billy goodall

### ISSUE THREAD

**Issue by borisbean** [SchizoDuckie/DuckieTV#1186]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standlone...

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Stable...

*windows*What is your Operating System (Windows, Mac, Linux, Android)**
...

**Describe the problem you are having and steps to reproduce if available**
...

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
Huh?
unless you provide more information I will just close this ticket as I've got nothing to work with here.
