### ISSUE TITLE
[Feature Request] Custom torrent clients / Let the system handle magnet: links

### ISSUE THREAD

**Issue by McKenzieRilley** [SchizoDuckie/DuckieTV#1187]
I created a simple little Node.JS based app, to handle `magnet:` links. Which will add the torrent to an online based torrent client, namely, Seedr.cc using their API.

But there doesn't seem to be an option in Duckie where I can de-select the any of the Torrent clients. And just have Duckie attempt to open the `magnet:` links with my system default.

Another pro to having such a feature would be that you can support pretty much every Torrent client out there, that handles `magnet:` links, with the trade off that you can't track the torrents with them.

Which for me, is fine anyway. As I'm not using Duckie for that purpose.

Sorry if this is already possible. And I just haven't found it yet. :P

**Comment by garfield69** [comment]
It's true that with the Dtv 1.1.5 suite you cant just send the magnet to the OS.
But if you switched to a Dtv Nightly standalone then it should be possble to do as you suggest.
1. download the latest Dtv Standalone Nightly from https://github.com/DuckieTV/Nightlies/releases
2. from the settings panel select the torrent button to open the side panel and scroll down and set the torrent client to None.
3. scroll further down to the bottom and enable the torrent parameters option.

in theory, when you now launch a magnet from Dtv this will pass the magnet to the OS which should invoke whatever OS defaults are in place for handling magnets.
It's untested and there will probably be a surprise gotcha, but I'd be interested to know if it works for you.

**Comment by McKenzieRilley** [comment]
Just downloaded, & tested it. It worked like a charm on the first try! :)

Thank you.
I'll close this now. Seeing as it's already implemented for the nightly build.
