### ISSUE TITLE
Ubuntu 18.04 Chrome extension not downloading torrents

### ISSUE THREAD

**Issue by skonrad21** [SchizoDuckie/DuckieTV#1188]
What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))
Chrome Browser Action - Nightly

What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)
Nightly 3019.8.1.91

What is your Operating System (Windows, Mac, Linux, Android)
Linux - Ubuntu 18.04

Describe the problem you are having and steps to reproduce if available
Torrent and Magnet links do not download through the DuckieTV Chrome extension. Clicking 'download' or 'open' shows a notification stating 'download has started' but nothing arrives in Torrent program nor in downloads folder.

Attach any DuckieTV statistics or Developer Console logs if available
...
Using qBittorrent v4.1.6. If I go to the Torrent website and manually click 'download', the download works.

**Comment by garfield69** [comment]
which Search Engine are you using?

**Comment by skonrad21** [comment]
Feel free to close this thread. I abandoned the idea of the Linux DuckieTV implementation.
