### ISSUE TITLE
Download doesn't start when it says it does

### ISSUE THREAD

**Issue by bjoern89** [SchizoDuckie/DuckieTV#1189]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
... Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
... Stable last version

**What is your Operating System (Windows, Mac, Linux, Android)**
... Windows 10

**Describe the problem you are having and steps to reproduce if available**
... I've tried Qbittorrent 3.2+, Utorrent, Bittorent and Vuze, and even when they connect and setup seem confirmed, nothing happens in any of the clients when the app stays download started :/

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
The most likely reason for this is that it has nothing to do with which torrent client you are using, and everything to do with which Search Engine you are using.

Are you by any chance using 1337x as your default Search Engine?
1337x altered their download links a month ago, so the Dtv 1.1.5 1337x SE will no longer work.
In fact Dtv 1.1.5 SE are getting quite out of date, with many SE now pointing to obsolete domains or closed sites, or sites that have changes their search results HTML. 
Likely only TPB SE is still working. Have you tried switching to TPB SE to test?

I suggest you upgrade your Dtv Standalone 1.1.5 to the latest Dtv Nightly Standalone from https://github.com/DuckieTV/Nightlies/releases and see if this help.

At the very minimum, should you still have issues, the Nightly includes the *Development Tools* module that allows you to access the logs using the **F12** key followed by clicking on the **console** tab, so you can look for errors or messages that might explain what is going on.

Let me know how you go.

**Comment by bjoern89** [comment]
Thepiratebay.se is blocked by the ISP, so I use proxy if searching there. I did however change to RARBG and can confirm the download started working. 

Thank you for the help, Garfield69 :)
