### ISSUE TITLE
DuckieTV 1.1.5 with Transmission hangs at 100% cpu

### ISSUE THREAD

**Issue by Zxurian** [SchizoDuckie/DuckieTV#1190]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 10 (VM)

**Describe the problem you are having and steps to reproduce if available**
Have Torrent set to use Transmission on a different computer. Transmission settings are verified correct. As soon as I add a torrent, it causes DuckieTV to stop responding and CPU usage to peg at 100%. (using Task Manager, ntoskrnl.exe is what is consuming high CPU).
Right clicking on system tray icon for DuckieTV and selecting exit doesn't do anything.
The only thing that works is right clicking on Task Manager and ending process of DuckieTV. When I do that, I get an error message
Unable to terminate process.
- The operation could not be completed.
- The operation is not valid for this process.

Checking the transmission server afterwards, the torrent was added to the transmission server.

After I force quit, if I go back into DuckieTV, it will respond normally again for a minute or two, before it locks up with 100% cpu. The specific episode added will also not show that the torrent was added, nor will it show any progress.

**Attach any DuckieTV statistics or Developer Console logs if available**
debug file in %AppData%\Roaming\DuckieTV just shows the following
```
[0803/205941.090:ERROR:registration_protocol_win.cc(84)] TransactNamedPipe: The pipe has been ended. (0x6D)
[0803/220451.731:ERROR:registration_protocol_win.cc(56)] CreateFile: The system cannot find the file specified. (0x2)
[0803/220452.178:ERROR:registration_protocol_win.cc(56)] CreateFile: The system cannot find the file specified. (0x2)
```

**Comment by garfield69** [comment]
The first thing to try is to upgrade your Dtv 1.1.5 to the latest Dtv Nightly standalone from https://github.com/DuckieTV/Nightlies/releases

the latest nightly runs under the newest NWJS run time environment, which may help.

Also, the Nightly comes with the *Development Tools* module so you can open the page with the **F12** key and click the **console** tab and view the log.
I would open the console and leave it open while you do a test and see if there are any messages that relate to the problem pop up.

If you are running thing under VM, then the most likely cause is a memory full condition.... ensure you have allocated sufficient storage for the VM image to use.
The NWJS environment can use a surprising amount of storage which could hang the image if there is not enough allocated.

**Comment by Zxurian** [comment]
upgrading to the 04-08-2019 nightly did indeed solve the issue. Whatever was wrong with 1.1.5 stable is fixed in the nightly when talking to transmission server. Everything's back to normal.

**Comment by garfield69** [comment]
fantastic.
