### ISSUE TITLE
Duckietv connects but won't send download to qbittorrent 4.1.7

### ISSUE THREAD

**Issue by pinnz** [SchizoDuckie/DuckieTV#1191]
**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
1.1.5
**What is your Operating System (Windows, Mac, Linux, Android)**
Windows
**What version of qbittorent are you using
4.1.7
**Describe the problem you are having and steps to reproduce if available**
Since I updated from 4.1.5, the last version that worked. I haven't been able to download any more torrents. However, now even downgraded to 4.1.5 doesn't seem to work. It connects fine as seen here https://snag.gy/HAVyOu.jpg but when I go to download it, I'll get the notification that the download started. However, it is not actually downloading anything.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
qBt 4.1.7 works with Dtv, I've tested this on my win10

Most likely your Dtv Search engines (SE) on Dtv 1.1.5 are the problem.

The SE on that build are getting out of date with current sites' changed domains, changed search result html, or site closures, etc. I have been fielding quite a few questions like yours recently.

Your best bet is to upgrade to the latest Dtv Standalone Nightly from https://github.com/DuckieTV/Nightlies/releases

try it out and let me know how it goes.

**Comment by pinnz** [comment]
I’ll give it a shot. It finds torrents when I go to manually find them, but it won’t download either via auto download or manually downloading the magnet link. If there is no reply, then the nightly release worked

Thanks, it worked and all the downloads are working as normal. Thanks for making me aware of this change to the nightlies realeases.


Sent from Mail for Windows 10
