### ISSUE TITLE
FR: set label of torrent in deluge add

### ISSUE THREAD

**Issue by mgaulton** [SchizoDuckie/DuckieTV#1193]
Just wondering if it would be possible to add labels, as this is supported in deluge. I found the previous history of issues that it was marked as unsupported.

keep up the awesome work!

**Comment by garfield69** [comment]
deluge is a mess right now.  deluge 2.+ is only available on linux platforms, not available for macOSx or windows. :-(
And the documentation library is mostly empty, with nothing useful!

this makes reverse engeneering the ui the only way to find the appropriate parms, and testing is going to be a pain in the arse with just linux to work on.

so no, I'm not going near it for now. If/when the windows version comes out post another reminder here and I'll re-open and take another look.

**Comment by mgaulton** [comment]
That's fair. Thanks for the quick response.
