### ISSUE TITLE
DuckieTV does not use current rtorrent 0.9.7/0.13.7 XML-RPC API calls

### ISSUE THREAD

**Issue by talios** [SchizoDuckie/DuckieTV#1194]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**

* Standalone and Chrome Extension - New Tab

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**

Using DuckieTV v1.1.5 and nightlies.

**What is your Operating System (Windows, Mac, Linux, Android)**

OSX

**Describe the problem you are having and steps to reproduce if available**

After updating to rtorrent 0.9.7/0.13.7 (switched Debian Jessie to Buster) torrents no longer start.

Using the chrome debug tools I see responses:

```
<value><string>Method 'load_start' not defined</string></value></member>
```

But when using an XML-RPC extension to introspec the API, I see `load.start` is available - this seems in line with a lot of the API/config changes I had to make to my `rtorrent.rc` after updating.

It seems that `system.listMethods` appears to be a standard method for discovering methods (at least, it seems mentioned in a lot of APIs), so maybe DuckieTV could use that to detect the version of API to use.

**Comment by garfield69** [comment]
the latest Dtv Nightly works with rTorrent 0.9.6, I just tested it on my win10 VB Ubuntu image.
0.9.6 is the latest stable release, and Dtv uses the XMLRPC with all the 0.9.x versions so far.

where did you get 0.9.7 from ? if you provide a link and I will check it out.

**Comment by talios** [comment]
@garfield69 From the standard Debian buster repos - https://packages.debian.org/buster/rtorrent

I sure hope torrent didn't break API in a patch release version! That would make me cry.

**Comment by talios** [comment]
Looks like 0.9.8 is the current release as well - https://github.com/rakshasa/rtorrent/releases/tag/v0.9.8

**Comment by garfield69** [comment]
no, 0.9.7 and 0.9.8 are beta versions.
https://github.com/rakshasa/rtorrent/wiki#download-links

**Comment by talios** [comment]
@garfield69 doh - so I see (it makes me cry still that they've broken major API in an unstable release, under a patch versioning scheme).

I'll guess I'll raise a bug with Debian to downgrade rtorrent somehow.

**Comment by talios** [comment]
@garfield69 I see on https://github.com/rakshasa/rtorrent/wiki/RPC-Migration-0.9 that 0.9.7 _removed_ the deprecated methods that shouldn't be used in the 0.9 series.

So maybe updating DuckieTV to not use deprecated methods might be a good idea regardless.

> Deprecated aliases are not added when you pass rTorrent 0.9.6 the options -D -I on startup.

Looks like you could use that to test against 0.9.6 as part of testing deprecation fixes.

Happy to try make a PR, have cloned the repo and doesn't look too hard.

**Comment by talios** [comment]
There's even a sed script on that page to automate the migration/changes as well.

**Comment by talios** [comment]
So I have a set of changes that _look_ like it should work - `load.start` now returns with an error about missing `info-hash` on any download's I initiate.

**Comment by garfield69** [comment]
excellent. 
I'll try to make time to test this against my rtorrent 0.9.6 (with and without -D -I) and test all the functions out.

**Comment by talios** [comment]
I just noticed that torrent download list doesn't show any details, I'm not sure if that's related to this change or not tho.

**Comment by garfield69** [comment]
screenshot?

**Comment by talios** [comment]
@garfield69 just noticed this comment - it works fine in the standalone I pulled from the nightly build with your ammendments, but not in the new-tab version of my original changes, will update my git checkout and re-enable the new-tab version when I get home and see if your changes resolved that.  I'll report back with a screen shot if needed.

**Comment by talios** [comment]
@garfield69 all seems to be working ok in new-tab now as well.  I do get the odd downloads that just seem to want to download .meta files, but I think that's an rtorrent weirdness which I've seen sporadically over previous versions as well - so nothing that's introduced.

**Comment by garfield69** [comment]
Yes. when you start a magnet torrent, there is a first phase, where you have to contact a peer who will provide the file content details and other such data, (because it is not contains in the magnet url) before downloading can properly begin. Perfectly normal.
