### ISSUE TITLE
Enhancement: Background poster with TV Show logo

### ISSUE THREAD

**Issue by miraclx** [SchizoDuckie/DuckieTV#1196]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
... Chrome Extension: Browser Action
..... Although, this content affects all builds

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
... Nightly 3019.08.19.91
..... Although, this content affects all versions

**What is your Operating System (Windows, Mac, Linux, Android)**
... Linux
..... Although, this content affects all platforms

**Enhancement**: Sometimes, a random poster comes up and it trying to recollect the name could be a problem.

For instance

**THE AMERICANS (2013)**

Background:
![Background](https://fanart.tv/fanart/tv/261690/tvposter/the-americans-534055df7b337.jpg)
Logo:
![Logo](https://fanart.tv/fanart/tv/261690/hdtvlogo/the-americans-2013-51019deb5b075.png)

The Logo, in Duckie, could appear as a watermark at, the bottom right.

Something like this you see at the top tight of Emby.
![Emby Server](https://emby.media/community/uploads/inline/2/5d3b3f60acdd1_Untitled.png)

Would've coded this in a PR but I'm very busy atm.
Maybe still would, depending on how this issue is handled.

**Comment by garfield69** [comment]
no one is spending any time on enhancements. Myself I just manage to fix bugs when they crop up with either the search engines or the torrent clients.
a PR would be very welcome as would progress on #1140

**Comment by Js41637** [comment]
yeah the current provider of images we use is shit, we'd have to switch over to TMDB which would require some work to operate within their rate limits.

**Comment by garfield69** [comment]
https://github.com/DuckieTV/Nightlies/releases/tag/nightly-202406120803 implements a show title(year) to the background image on the bottom right, created by Js41637.
Closing as completed.
