### ISSUE TITLE
Does not auto download shows anymore

### ISSUE THREAD

**Issue by recoi1er** [SchizoDuckie/DuckieTV#1197]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
... Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...DuckieTV-Standalone v1.1.5 Macintosh
--

**What is your Operating System (Windows, Mac, Linux, Android)**
... Intel Mac OS X 10_14_6

**Describe the problem you are having and steps to reproduce if available**
... Have shows set to download, settings are enabled for auto download. Shows are listed on the calendar but are never downloaded. The "Auto Download" button next to "Find a Torrent" also does nothing

**Attach any DuckieTV statistics or Developer Console logs if available**
...Not sure where to get those

**Comment by garfield69** [comment]
Most likely your Dtv Search engines (SE) on Dtv 1.1.5 are the problem.

The SE on that build are getting out of date with current sites' changed domains, changed search result html, or site closures, etc. I have been fielding quite a few questions like yours recently.

Your best bet is to upgrade to the latest Dtv Standalone Nightly from https://github.com/DuckieTV/Nightlies/releases

try it out and let me know how it goes.

**Comment by garfield69** [comment]
Note that on the Mac, for the installer to work properly, you will first need to drag the DuckieTV app from your Applications folder to the bin, and then run the installer. Failing to do so will make it appear that the installer worked but the app will not be upgraded.

**Comment by recoi1er** [comment]
Thanks for your reply! 

So if I click on the “Find a Torrent”, it seems to work perfectly. Does the auto download portion use a different search mechanism?

I’ll try it out now, thanks! (I got your other email as well about deleting first)

**Comment by tedztar** [comment]
The auto-download has a "minimum seeders" option, see what number that is set at and if the seeders of the shows you want are higher then that. I personally have an issue that most of the shows I watch only ever get 30 seeders when the default is 50 so I have reduced that option to 20.

**Comment by garfield69** [comment]
closing ticket, on the assumption the OP has got it working now. Can always reopen if issue is outstanding.
