### ISSUE TITLE
The show Good Eats, The Return 

### ISSUE THREAD

**Issue by TimMaietta** [SchizoDuckie/DuckieTV#1198]
Good eats the return will not auto download because the toeernts just list it as season 15 of the original good eats show.
...

**Comment by garfield69** [comment]
Sorry, absolutely nothing Dtv can do about this. 
Dtv gets all its data from Trakt.tv which in turn aggregates info from tvdb and tmdb
read https://github.com/SchizoDuckie/DuckieTV/wiki/How-to-make-corrections-to-shows-on-DuckieTV for details.
