### ISSUE TITLE
Webserver/Multiclient support

### ISSUE THREAD

**Issue by tedztar** [SchizoDuckie/DuckieTV#1201]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
V1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows

So I know in the past people have requested a server version so you can run multiple clients an be able to link it or use a webserver. And I know it will be alot of work, but I was wondering if this is still not an option could we have the ability to use an external DB so we can link multiple clients that way? or would this cause to many other issues?

**Comment by garfield69** [comment]
Dtv is constrained by the restrictions imposed as a Chrome Browser Extension, by the browser security rules.
This does not allow Dtv access to external files or DB outside of the sandboxed dataspace that the Browser provides.
The Dtv Standalone version is the same chrome browser extension code running within the NWJS run time environment under a chromium engine.

So no, not an option as far as I know.

Besides this, no one has volunteered to work on any enhancement to Dtv for quite some time.
Myself, I do urgent fixes to the Search Engines or the torrent Client interfaces only, and answer questions on reddit or here, help with user issues. And this is all I have time for as far as Dtv is concerned.
