### ISSUE TITLE
All TV series gone from calendar after update, back up not loading

### ISSUE THREAD

**Issue by sietsevanerve** [SchizoDuckie/DuckieTV#1203]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Chrome Extension

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**

Browser Action mode 1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**

Windows 10

**Describe the problem you are having and steps to reproduce if available**

Today i got a message that Ducky TV was updated when opening it, but all TV series I was following are gone. 
The whole calendar is empty.

I tried to upload a backup but this doesn't work either. It tries to load the back up but they importing just continous spinning (now already for 15 minutes). 

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
Urg. We haven't pushed out a Dtv chrome extensions update, so it sounds like chrome has wiped your Dtv settings, and now Dtv cannot figure out how to use the database.
Try using the extensions panel chrome://extensions/ to remove Dtv.
then shutdown Chrome completely and start it up again and add the extension anew.
Hopefully this will allow Dtv to pre-initialise the settings and allow you to do the import.

**Comment by garfield69** [comment]
if that does not work then consider upgrading to the latest Dtv Standalone Nightly. 
it is exactly the same AngularJS code, but running under the NWJS run-time environment using the chromium engine. find it at https://github.com/DuckieTV/Nightlies/releases
the advantage here is that you've got fully working Search engines and you are not dependant on the Chrome Browser.

**Comment by sietsevanerve** [comment]
Problem is solved now. 
Had to remove it and add it again and I could import my latest backup. 

Thanks.
