### ISSUE TITLE
Utorrent connected to Duckie but not opening torrents

### ISSUE THREAD

**Issue by MaiaLara** [SchizoDuckie/DuckieTV#1204]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...
Standalone 1.1.5

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...
1.1.5
**What is your Operating System (Windows, Mac, Linux, Android)**
...
Windows 7
**Describe the problem you are having and steps to reproduce if available**
...
Hi! I was using Duckie tv with the web ui integration smoothly but I think that AVAST CLEANUP PREMIUM closed something because now it´s connected, the notifications on Duckie appear when a new episode is going to download but Utorrent doesn´t open them. I tried opening ports from exxceptions on avast antivirus and from control panel but its not working. I tried the rescue center on the cleanup but I dont find options to undo that step. F12 on Duckie opens a blank page. I opened the utorrent on my browser and it´s ok... Don´t know what else I can do. Utorrent also updated I think, it´s 3.5.5 Build 45341.  Thank you.
**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by 01bradmiller** [comment]
I too have the same problem - it started direct after the latest Utorrent upgrade.
I just get a working cursor and program locks up - I have tried the non UI integration and it to does the same thing. redone setting multiple times still no loading of the new torrent.

**Comment by garfield69** [comment]
I have no problems using &micro;Torrent 3.5.5 with the latest development Dtv.

Most likely your Dtv Search engines (SE) on Dtv 1.1.5 are the problem.

The SE on that build are getting out of date with current sites' changed domains, changed search result html, or site closures, etc. I have been fielding quite a few questions like yours recently.

Your best bet is to upgrade to the latest Dtv Standalone Nightly from https://github.com/DuckieTV/Nightlies/releases

try it out and let me know how it goes.

**Comment by 01bradmiller** [comment]
Legend! – thanks it seems to be working!

**Comment by MaiaLara** [comment]
That solved it for me! Thank you very much!

**Comment by 01bradmiller** [comment]
Hi

 

Any idea why this does not come up when searching for shows?

 

https://rarbgtor.org/torrents.php?search=the+mandalorian <https://rarbgtor.org/torrents.php?search=the+mandalorian&category%5B%5D=18&category%5B%5D=41&category%5B%5D=49> &category%5B%5D=18&category%5B%5D=41&category%5B%5D=49

 

 

 

From: Brad Miller [mailto:01bradmiller@gmail.com] 
Sent: Monday, 16 September 2019 5:11 PM
To: 'SchizoDuckie/DuckieTV' <reply@reply.github.com>; 'SchizoDuckie/DuckieTV' <DuckieTV@noreply.github.com>
Cc: 'Comment' <comment@noreply.github.com>
Subject: RE: [SchizoDuckie/DuckieTV] Utorrent connected to Duckie but not opening torrents (#1204)

 

Legend! – thanks it seems to be working!
