### ISSUE TITLE
BuildBot Server is not working

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#1205]
Hello @SchizoDuckie 
it appears the buildbot server has ground to a halt again and requires your personal attention.
There has not been a Nightly built for 7 days now, and the xem-cache has not been updated for 10 days.

Also the Nightly new-tab extension webstore account may need attention, as that has not had a version update since August 22nd, although oddly, the updated date-stamp reads 18 Sep 2019!?!
![image](https://user-images.githubusercontent.com/6933240/65367255-ae525000-dc82-11e9-87de-6bda8af16f96.png)

Thanks.

**Comment by 2635599** [comment]
garfield this is beyond old duckie not being updated.

**Comment by SchizoDuckie** [comment]
Cleaned up and added a weekly cleanup crontab entry
fixes #1205

**Comment by garfield69** [comment]
Thank you.
