### ISSUE TITLE
[Feature Request] Torrent Client Support - Premiumize.me

### ISSUE THREAD

**Issue by kevinlekiller** [SchizoDuckie/DuckieTV#1206]
Hello, would it be possible to add support for premiumuze.me ; sending magnet links / torrents.

Here's their API documentation: https://app.swaggerhub.com/apis-docs/premiumize.me/api/

Thanks.

**Comment by garfield69** [comment]
sorry no.
Dtv does not support connecting to any site that requires users to pay for services.
