### ISSUE TITLE
DuckieTV Not Working With qBittorrent 4.18

### ISSUE THREAD

**Issue by 2635599** [SchizoDuckie/DuckieTV#1209]
last night qbt updated to 4.18. this morning i went to download a couple of shows through dtv nightly browser mode version and got the below.

Could not find any application or handler for magnet:?xt=urn:btih: 7a514e41546baae750e2f2cbf09a0e69bcce3041&dn=Titans.2018.S02E04.HDTV.x264-MiKEPANTS%5BTGx%5D&xl=252381389&tr=udp%3A%2F%2Ftracker.coppersurfer.tk: 6969/announce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org:6969/ announce&tr=udp%3A%2F%2Fbt.xxx-tracker.com:2710/ announce&tr=udp%3A%2F%2Ftracker.internetwarriors.net:1337/ announce&tr=udp%3A%2F%2Ftracker.openbittorrent.com:80/ announce&tr=udp%3A%2F%2Fexplodie.org:6969/ announce&tr=udp%3A%2F%2Ftracker.opentrackr.org:1337/ announce&tr=udp%3A%2F%2Ftracker.tiny-vps.com:6969/ announce&tr=udp%3A%2F%2Fopen.demonii.si:1337/ announce&tr=udp%3A%2F%2Ftracker.torrent.eu.org:451/ announce&tr=udp%3A%2F%2Ftracker.pirateparty.gr:6969/ announce&tr=udp%3A%2F%2Fipv4.tracker.harry.lu:80/ announce&tr=udp%3A%2F%2Ftracker.cyberia.is:6969/ announce&tr=udp%3A%2F%2F9.rarbg.to:2710/ announce&tr=udp%3A%2F%2Fdenis.stalker.upeer.me:6969/announce

kubuntu 19.04 64 bit kernel 5.3.0, lastest vivaldi stable

**Comment by 2635599** [comment]
just downloaded the stand alone and tested and it sends the links to qbt, so this is a dtv browser issue only.

**Comment by garfield69** [comment]
your browser would appear to have lost its app-to-magnet association.
typically Dtv sends its torrents and magnets directly via its client interface.
the only time it passes them to the browser should be when you have the Dtv Settings > Torrent > Torrent Parameters enabled.
so if you cannot figure out how to get your browser to associate magnets with your qBt 4.1.8 app, then disable the Dtv torrent parameters option and make Dtv send magnets via the interface instead.
But be aware that for this to work you'll need to check that Dtv's qBt 3.2+ interface is set up correctly and that Dtv can connect to qBt Web ui successfully. refer to https://github.com/SchizoDuckie/DuckieTV/wiki/Setting-up-qBitTorrent-3.2-with-DuckieTV if required.

**Comment by garfield69** [comment]
Oh, the other thing might be is simply that you need to restart Dtv.
if qBt auto-upgraded to 4.1.8 while Dtv was active, then this would have disconnected the Dtv-webui-link to qBt.
when Dtv next tried to send a magnet to qBt and couldn't it may have tried to let the browser handle the magnet instead (it's a standby option), and if the browser does not have an magnet-to-app association defined, then this would cause the message you found.
so restart Dtv and see if that solves the issue ;-)

**Comment by 2635599** [comment]
on your first post i think you lost me. as for your second post the browser thus dtv was closed when qbt updated.  first thing i did when i got that message was to check that dtv was still connect to qbt's webui and it was. now i just tried again in the browser action mode version and it sent the link to qbt. i really don't get it based on what you said. still having the issue with clicking a magnet link on a torrent site though. now looks like it's a issue for vivaldi devs to look at. please leave this open just in case one or more of them wants to add info to it. thanks

**Comment by garfield69** [comment]
2635599 wrote:
>you can close that ticket. after trying everything i and others could think of i decided to try a hail mary and point the file association to the qbt shortcut on my desktop, and it worked. so once again magnet links are being grabbed by qbt.
