### ISSUE TITLE
DuckieTV V1.1.5 (Windows 10 x64) - uTorrent 3.5.5 Web UI - not starting download

### ISSUE THREAD

**Issue by ghost** [SchizoDuckie/DuckieTV#1211]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
V1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 10 x64

**Describe the problem you are having and steps to reproduce if available**
Autodownload shows torrent launched, but no torrents are seen in uTorrent or on the downloads directory configured within uTorrent. uTorrent WebUI shows as connected, have tried using localhost as well as 127.0.0.1, I can login to the WebUI using the credentials supplied in the configuration.

**Attach any DuckieTV statistics or Developer Console logs if available**
[
  {
    "name": "DuckieTV Web Based",
    "data": "1.1.5"
  },
  {
    "name": "Current Date and Time",
    "data": "Wed, 02 Oct 2019 22:27:32 GMT"
  },
  {
    "name": "NWJS, Chromium",
    "data": "0.25.0 , 61.0.3163.79"
  },
  {
    "name": "UserAgent",
    "data": "DuckieTV-Standalone  v1.1.5 Windows NT 10.0; Win64; x64"
  },
  {
    "name": "Platform, Vendor",
    "data": "Win32, Google Inc."
  },
  {
    "name": "Screen (width x height)",
    "data": "1400 x 1050"
  },
  {
    "name": "Default Search Engine",
    "data": "1337x (Enabled)"
  },
  {
    "name": "Default Torrent Client",
    "data": "uTorrent Web UI (Enabled and Connected to Host)"
  },
  {
    "name": "Auto Download Service",
    "data": "(Enabled and Active)"
  },
  {
    "name": "Last checked TraktTV for DB updates on",
    "data": "Wed, 02 Oct 2019 19:02:34 GMT"
  },
  {
    "name": "User Preferences on Local Storage",
    "data": "{\n  \"ThePirateBay.mirror\": \"https://thepiratebay.org\",\n  \"application.language\": \"en_us\",\n  \"application.locale\": \"en_us\",\n  \"aria2.port\": 6800,\n  \"aria2.server\": \"http://localhost\",\n  \"aria2.token\": \"\",\n  \"autobackup.period\": \"monthly\",\n  \"autodownload.delay\": 15,\n  \"autodownload.multiSE\": {\n    \"ThePirateBay\": true,\n    \"1337x\": true,\n    \"IsoHunt\": true,\n    \"KATcr\": true,\n    \"Nyaa\": true,\n    \"RarBG\": true,\n    \"ShowRSS\": true,\n    \"TorrentDownloads\": true,\n    \"TorrentZ2\": true,\n    \"Zooqle\": true,\n    \"EzTV.ag\": true,\n    \"Idope\": true,\n    \"LimeTorrents\": true,\n    \"SkyTorrents\": true\n  },\n  \"autodownload.multiSE.enabled\": false,\n  \"autodownload.period\": 4,\n  \"background-rotator.opacity\": \"0.4\",\n  \"biglybt.password\": \"*****\",\n  \"biglybt.path\": \"/transmission/rpc\",\n  \"biglybt.port\": 9091,\n  \"biglybt.progressX100\": true,\n  \"biglybt.server\": \"http://localhost\",\n  \"biglybt.use_auth\": true,\n  \"biglybt.username\": \"biglybt\",\n  \"calendar.mode\": \"date\",\n  \"calendar.show-downloaded\": true,\n  \"calendar.show-episode-numbers\": false,\n  \"calendar.show-specials\": true,\n  \"calendar.startSunday\": true,\n  \"client.determinedlocale\": \"en_us\",\n  \"deluge.password\": \"*****\",\n  \"deluge.port\": 8112,\n  \"deluge.server\": \"http://localhost\",\n  \"deluge.use_auth\": true,\n  \"download.ratings\": true,\n  \"episode.watched-downloaded.pairing\": true,\n  \"kc.always\": false,\n  \"ktorrent.password\": \"*****\",\n  \"ktorrent.port\": 8080,\n  \"ktorrent.server\": \"http://localhost\",\n  \"ktorrent.use_auth\": true,\n  \"ktorrent.username\": \"ktorrent\",\n  \"lastSync\": -1,\n  \"library.order.by\": \"getSortName()\",\n  \"library.order.reverseList\": [\n    true,\n    false,\n    true,\n    true\n  ],\n  \"library.seriesgrid\": true,\n  \"library.smallposters\": true,\n  \"main.viewmode\": \"calendar\",\n  \"notifications.enabled\": true,\n  \"qbittorrent.password\": \"*****\",\n  \"qbittorrent.port\": 8080,\n  \"qbittorrent.server\": \"http://localhost\",\n  \"qbittorrent.use_auth\": true,\n  \"qbittorrent.username\": \"admin\",\n  \"qbittorrent32plus.password\": \"*****\",\n  \"qbittorrent32plus.port\": 8080,\n  \"qbittorrent32plus.server\": \"http://localhost\",\n  \"qbittorrent32plus.use_auth\": true,\n  \"qbittorrent32plus.username\": \"admin\",\n  \"rtorrent.path\": \"/RPC2\",\n  \"rtorrent.port\": 80,\n  \"rtorrent.server\": \"http://localhost\",\n  \"rtorrent.use_auth\": false,\n  \"series.displaymode\": \"poster\",\n  \"series.not-watched-eps-btn\": false,\n  \"storage.sync\": false,\n  \"subtitles.languages\": [\n    \"eng\"\n  ],\n  \"sync.progress\": true,\n  \"synology.enabled\": true,\n  \"synology.ip\": \"192.168.x.x\",\n  \"synology.password\": \"*****\",\n  \"synology.playback_devices\": {},\n  \"synology.port\": 5000,\n  \"synology.protocol\": \"http\",\n  \"synology.username\": \"admin\",\n  \"tixati.password\": \"*****\",\n  \"tixati.port\": 8888,\n  \"tixati.server\": \"http://localhost\",\n  \"tixati.use_auth\": true,\n  \"tixati.username\": \"admin\",\n  \"topSites.enabled\": false,\n  \"topSites.mode\": \"onhover\",\n  \"torrentDialog.2.activeSE\": {\n    \"ThePirateBay\": true,\n    \"1337x\": true,\n    \"IsoHunt\": true,\n    \"KATcr\": true,\n    \"Nyaa\": true,\n    \"RarBG\": true,\n    \"ShowRSS\": true,\n    \"TorrentDownloads\": true,\n    \"TorrentZ2\": true,\n    \"Zooqle\": true,\n    \"EzTV.ag\": true,\n    \"Idope\": true,\n    \"LimeTorrents\": true,\n    \"SkyTorrents\": true\n  },\n  \"torrentDialog.2.enabled\": false,\n  \"torrentDialog.2.sortBy\": \"+engine\",\n  \"torrentDialog.showAdvanced.enabled\": true,\n  \"torrenting.autodownload\": true,\n  \"torrenting.autostop\": true,\n  \"torrenting.autostop_all\": false,\n  \"torrenting.client\": \"uTorrent Web UI\",\n  \"torrenting.directory\": true,\n  \"torrenting.enabled\": true,\n  \"torrenting.global_size_max\": 2000,\n  \"torrenting.global_size_max_enabled\": true,\n  \"torrenting.global_size_min\": 200,\n  \"torrenting.global_size_min_enabled\": true,\n  \"torrenting.ignore_keywords\": \"\",\n  \"torrenting.ignore_keywords_enabled\": true,\n  \"torrenting.label\": false,\n  \"torrenting.launch_via_chromium\": false,\n  \"torrenting.min_seeders\": 20,\n  \"torrenting.min_seeders_enabled\": false,\n  \"torrenting.progress\": true,\n  \"torrenting.require_keywords\": \"\",\n  \"torrenting.require_keywords_enabled\": true,\n  \"torrenting.require_keywords_mode_or\": true,\n  \"torrenting.searchprovider\": \"1337x\",\n  \"torrenting.searchquality\": \"\",\n  \"torrenting.searchqualitylist\": [\n    \"480p\",\n    \"HDTV\",\n    \"720p\",\n    \"1080p\",\n    \"2160p\"\n  ],\n  \"torrenting.streaming\": true,\n  \"trakt-update.period\": 12,\n  \"trakttv.passwordHash\": \"*****\",\n  \"trakttv.sync\": false,\n  \"trakttv.username\": null,\n  \"transmission.password\": \"*****\",\n  \"transmission.path\": \"/transmission/rpc\",\n  \"transmission.port\": 9091,\n  \"transmission.progressX100\": true,\n  \"transmission.server\": \"http://127.0.0.1\",\n  \"transmission.use_auth\": true,\n  \"transmission.username\": \"admin\",\n  \"utorrentwebui.password\": \"*****\",\n  \"utorrentwebui.port\": 8080,\n  \"utorrentwebui.server\": \"http://127.0.0.1\",\n  \"utorrentwebui.use_auth\": true,\n  \"utorrentwebui.username\": \"admin\",\n  \"vuze.password\": \"*****\",\n  \"vuze.path\": \"/transmission/rpc\",\n  \"vuze.port\": 9091,\n  \"vuze.progressX100\": true,\n  \"vuze.server\": \"http://localhost\",\n  \"vuze.use_auth\": true,\n  \"vuze.username\": \"vuze\",\n  \"autodownload.lastrun\": 1570055163769\n}"
  },
  {
    "name": "Other significant Local Storage keys",
    "data": "{\n  \"1.1.4TorrentHashListCleanup\": \"Wed Oct 02 2019 12:02:34 GMT-0700 (Pacific Daylight Time)\",\n  \"1.1.4cleanupOrphanedEpisodes\": \"Wed Oct 02 2019 12:02:30 GMT-0700 (Pacific Daylight Time)\",\n  \"1.1.4cleanupOrphanedSeasons\": \"Wed Oct 02 2019 12:02:31 GMT-0700 (Pacific Daylight Time)\",\n  \"1.1.4qBittorrentPre32\": \"Wed Oct 02 2019 12:02:26 GMT-0700 (Pacific Daylight Time)\",\n  \"1.1.4refresh\": \"Wed Oct 02 2019 12:02:36 GMT-0700 (Pacific Daylight Time)\",\n  \"1.1.4refreshTrendingCache\": \"Wed Oct 02 2019 12:02:26 GMT-0700 (Pacific Daylight Time)\",\n  \"1.1.4updateTransmissionPath\": \"Wed Oct 02 2019 12:02:26 GMT-0700 (Pacific Daylight Time)\",\n  \"1.1.5FetchFirstXemAliasMap\": \"Wed Oct 02 2019 12:02:26 GMT-0700 (Pacific Daylight Time)\",\n  \"1.1.5deleteSearchEngines\": \"Wed Oct 02 2019 12:02:26 GMT-0700 (Pacific Daylight Time)\",\n  \"1.1.5fanartCleanup\": \"Wed Oct 02 2019 12:02:56 GMT-0700 (Pacific Daylight Time)\",\n  \"1.1.5updateDelugeAuth\": \"Wed Oct 02 2019 12:02:26 GMT-0700 (Pacific Daylight Time)\",\n  \"1.1.5updateTorrenting.min_seeders\": \"Wed Oct 02 2019 12:02:26 GMT-0700 (Pacific Daylight Time)\",\n  \"1.1migration\": \"Wed Oct 02 2019 12:02:29 GMT-0700 (Pacific Daylight Time)\",\n  \"autobackup.lastrun\": \"1570042946347\",\n  \"database.version.Episodes\": \"14\",\n  \"database.version.Fanart\": \"1\",\n  \"database.version.Jackett\": \"2\",\n  \"database.version.Seasons\": \"6\",\n  \"database.version.Series\": \"16\",\n  \"database.version.WatchList\": \"1\",\n  \"database.version.WatchListObject\": \"1\",\n  \"fanart.bootstrapped\": \"1\",\n  \"github.lastupdatecheck\": \"1570042948404\",\n  \"install.notify\": \"1.1.5\",\n  \"runtime.event\": \"{\\\"reason\\\":\\\"install\\\"}\",\n  \"snr.lastFetched\": \"1570042951327\",\n  \"standalone.closeSystray\": \"Y\",\n  \"standalone.position\": \"{\\\"width\\\":1402,\\\"height\\\":1012,\\\"x\\\":0,\\\"y\\\":0,\\\"state\\\":\\\"normal\\\"}\",\n  \"standalone.trayColor\": \"\",\n  \"standalone.zoomlevel\": \"6\",\n  \"torrenting.client\": \"uTorrent Web UI\",\n  \"trackers.lastFetched\": \"1570042948140\",\n  \"trakttv.lastupdated\": \"1570042954406\",\n  \"trakttv.lastupdated.trending\": \"1570042965318\",\n  \"upgrade.notify\": \"1.1.5\",\n  \"utorrent.port\": \"10000\",\n  \"utorrent.token\": \"59875F9ECEC27B50FB6590554674441BD49FF079\",\n  \"xem.lastFetched\": \"1570042951348\"\n}"
  },
  {
    "name": "DB Series",
    "data": 14
  },
  {
    "name": "DB Series Hidden From Calendar",
    "data": 0
  },
  {
    "name": "DB Seasons",
    "data": 69
  },
  {
    "name": "DB Episodes",
    "data": 919
  },
  {
    "name": "DB Fanart",
    "data": 1891
  },
  {
    "name": "DB Jackett",
    "data": 0
  }
]

**Comment by garfield69** [comment]
yes, you are using the 1337x Search Engine on Dtv 1.1.5
The 1337x web site changed their download links about 3 months ago and this has broken Dtv 1.1.5 1337x SE.

I recommend upgrading to the latest Dtv Nightly from https://github.com/DuckieTV/Nightlies/releases to get a working 1337x SE
OR
you could continue using Dtv 1.1.5 by choosing another default SE from your Dtv > Settings >Torrent Search Engines side-panel in the *Default Search Provider* section.
