### ISSUE TITLE
Chrome Web Store Link Down For DTV Browser Action Mode Nightly

### ISSUE THREAD

**Issue by 2635599** [SchizoDuckie/DuckieTV#1212]
i just tried to reinstall duckietvbrowser action mode nightly for my roommate in chrome and get a 404 error when navigation to it's chrome web store address. just checked it on my system and also get a 404 error, so it's not something with his system. any idea what's going on? thanks

https://chrome.google.com/webstore/detail/duckietv-browser-action-m/ikhklcamhmfmjbhckdjoabiepglbhaid

**Comment by garfield69** [comment]
looks like the chrome web store has dropped both the new-tab and action-mode Nightly chrome browser extensions.
The DuckieTV chrome browser extensions are still available.

not something I can investigate, it requires the owner of the web store nightly account.
@SchizoDuckie  can you please take a look?

**Comment by 2635599** [comment]
thanks for the quick response. this shouldn't affect the build-bot building and sending out the updates, right?

**Comment by garfield69** [comment]
we shall see in about a couple hours time when the bot builds the next nightly.

**Comment by garfield69** [comment]
well the good news is that it is just the nightly chrome extensions that have gone AWOL.
the bot managed to build all the other packages.

**Comment by 2635599** [comment]
"the bot managed to build all the other packages."  i noticed cause i've been keeping an eye on it. garfield69 till the nightly browser action mode link is fixed how do we package the extension so we can manually unpack it for others to use in their browser? i attempted to package dvt but vivaldi will not let me navigate to it's extension folder.

**Comment by garfield69** [comment]
you can access the extensions page on vivaldi with `vivaldi://extensions` in the address bar.
on that page toggle the `Development mode` switch (top right).
now you should be able to add local extensions.
download the latest DuckieTV-******-chrome-browseraction.zip from https://github.com/DuckieTV/Nightlies/releases and extract to a local folder, for example  `c:/temp/DtvNighty` .
then on the vivaldi extensions page click on the `load unpacked` button and navigate to `c:/temp/DtvNighty`.
and you should be good to go.

**Comment by 2635599** [comment]
thanks worked like a charm.

**Comment by garfield69** [comment]
the nightly links at the chrome web store are working again.
