### ISSUE TITLE
The Daily Show is showing up 2 times 

### ISSUE THREAD

**Issue by killeru13** [SchizoDuckie/DuckieTV#1214]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standlone 

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**

1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows

**Describe the problem you are having and steps to reproduce if available**
The Daily Show is showing up 2 times.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
please provide a screenshot of the calendar and of the series latest season episode list.

**Comment by killeru13** [comment]
Attached!

![DailyShow](https://user-images.githubusercontent.com/56487074/66706474-a6467700-ed3b-11e9-93aa-ac0cf5343b58.jpg)
![DailyShow2](https://user-images.githubusercontent.com/56487074/66706475-a6467700-ed3b-11e9-9e5b-d68f5f6fd115.jpg)

**Comment by garfield69** [comment]
I see.
as you may know, Dtv uses Trakt.TV for all its show data, and each episode has a unique trakt_id.
it looks like trakt.tv did a reorganisation of their DB for the daily show and assigned new trakt for a bunch of episodes. (this is not unknown, I've see it happen before with other tv series in the past).
so right now, your Dtv has two entries for s25e08, one the original trakt_id and the other with the new trakt_id.
So we got to try to clean up the Dtv DB to get rid of the obsolete entries.
try the following: from the series details page of the daily show, click on the **refresh** button and see if that gets rid of the obsolete episode entries.

**Comment by killeru13** [comment]
Had to also remove it and re-add it (did that before posting here but same issue re-occurred). Now it works since yesterday. Thanks and have a good one.
