### ISSUE TITLE
problems with DuckieTv/Utorrent Web UI/ MacOS Catalina

### ISSUE THREAD

**Issue by AllinPhil** [SchizoDuckie/DuckieTV#1215]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
... V201909140130

**What is your Operating System (Windows, Mac, Linux, Android)**
...MacOS Catalina 10.15

**Describe the problem you are having and steps to reproduce if available**
...using duckie tv standalone i can not get utorrent web ui to connect to it. i can not find a place to enter a username and password on the utorrent web ui that can match the duckie tv, so i have tried clearing those two fields in duckie tv but no luck. not sure what to do to connect these two. 
i never had issues using the utorrent app, but now with catalina, and having to switch to web ui, i got nothing.  please help. 

<img width="415" alt="Screen Shot 2019-10-14 at 7 47 00 PM" src="https://user-images.githubusercontent.com/35617717/66749074-70c89780-eebb-11e9-909a-f1d90915a237.png">

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
Unfortunately the uTorrentWeb app for the Catalina MacOS is not compatible with Dtv. :-(
This new web app does not have itself a web API, (or any kind of remote control port) so there is no way for Dtv to talk to it.
See #1199 for more details.

If you want to use Dtv in Catalina you are going to have to use any of the other MacOS torrent clients available.
