### ISSUE TITLE
With this install/work on a Raspberry PI

### ISSUE THREAD

**Issue by dadrepus** [SchizoDuckie/DuckieTV#1216]
**I know the installs on Linux so theoretically it should install with Raspian but no-where does it mention which chips it will work with? So, will this work on the latest Raspberry Pi?

**Comment by garfield69** [comment]
As you may know, Dtv is written as a chrome browser extension with JavaScript using the [AngularJS](https://angular.io/) framework.
so if your Pi can run a chrome browser that supports extensions, then Dtv can run on that browser.

The **standalone** version of Dtv is the same JS code running under the [NWJS](https://nwjs.io/) run-time environment (which includes an internal chromium engine).

looking at the NWJS download page https://nwjs.io/downloads/ they have a separate non-official ARM binary branch provided by the community, which implies that the official NWJS builds for linux are more likely set for the AMD processors.
which probably means that the Dtv pre-build packages from https://github.com/DuckieTV/Nightlies/releases (build using the official NWJS build) will likely not work on your Pi if its an ARM processor.

in theory you could run Dtv on Pi using the ARM NWJS code from https://github.com/LeonardLaszlo/nw.js-armv7-binaries in combination with the Dtv source code using https://github.com/SchizoDuckie/DuckieTV/wiki/How-to-Install-a-Development-version-of-the-Windows-DuckieTV-Standalone-SOURCE

But its never been tested as far as I know.
