### ISSUE TITLE
Backup loading issues on standalone windows app

### ISSUE THREAD

**Issue by Prior81** [SchizoDuckie/DuckieTV#1217]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...Stand alone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
...Windows

**Describe the problem you are having and steps to reproduce if available**
...wont load backup on standalone so i can move away from new tab mode

**Attach any DuckieTV statistics or Developer Console logs if available**
... ??

**Comment by garfield69** [comment]
the Dtv backup is from a chrome extension new-tab from which version ?
1.1.5 or Nightly?

**Comment by garfield69** [comment]
And when you say the backup will not load, what are you seeing.... just spinning wheels that never finish?
or are you getting something else?

**Comment by garfield69** [comment]
The Dtv 1.1.5 Standalone does not come with the Development Tools package that would help us look at the logs and do diagnostics.
And Dtv 1.1.5 is old and out of date with Search Engines and bugs

I recommend the following steps:

1. shutdown Dtv 1.1.5 standalone
2. locate the Dtv 1.1.5 standalone data folder  at `C:\Users\<username>\AppData\Local\DuckieTV-Standalone` and delete it.
3. download and install the latest Dtv Nightly from https://github.com/DuckieTV/Nightlies/releases
4. start the Dtv Standalone
5. wait a couple minutes for all the pre-initialisations activity to complete and settle down
6. at the **you dont have any series yet** page import the Dtv backup

The Nightly has the latest bug fixes, working Search Enigines, and up to date torrent client interfaces, plus comes with the development tools package so we can do diagnostics if it becomes neccessary.

see how you go.

**Comment by Prior81** [comment]
worked a treat thanks mate... and thanks for the quick reply
