### ISSUE TITLE
Integration with qBittorrent not working

### ISSUE THREAD

**Issue by mnhim001** [SchizoDuckie/DuckieTV#1218]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
... StandAlone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...Ver. 1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
...Windows 10 64-bit

**Describe the problem you are having and steps to reproduce if available**
...I have qBittorrent installed and have the green light next to the QB icon in DuckieTV.  Shows pop-up saying that the torrent was sent to qBittorrent, but I don't see the torrent in the qBittorrent client.  I am using qBittorrent version 4.1.8, I have unchecked "Enable Cross-Site Request Forgery (CSRF) Protection".

**Attach any DuckieTV statistics or Developer Console logs if available**
...I would if I knew where the logs are stored.

**Comment by garfield69** [comment]
Most likely your Dtv Search engines (SE) on Dtv 1.1.5 are the problem.

The SE on that build are getting out of date with current sites' changed domains, changed search result html, or site closures, etc. I have been fielding quite a few questions like yours recently.
In particular, the Dtv 1.1.5 1337x SE no longer works because the 1337x web site have changed their download links.

Also, since 1.1.5 does not come with the Development Tools package, there is no access to the logs which makes diagnostics more difficult.

Your best bet is to upgrade to the latest Dtv Standalone Nightly from https://github.com/DuckieTV/Nightlies/releases

This has the latest working SE and torrent client interface updates, as well as including the Development Tools package, so that if it becomes necessary we can start looking at the logs and some some diagnostics. 

try it out and let me know how it goes.

**Comment by 2635599** [comment]
try going into the qbittorrent settings in dtv and pressing test and connect again then try to send a link to qbt. i've noticed that dtv does have a habit of not sending a clicked link from a show search to qbt if the browser has been open over a certain amount of time. i found doing what i suggested above works to fix the issue for me.

garfield i'll say it again pushing peeps to the standalone nightly is not the answer. duckie is only worth it if you have a vpn.  in my case that vpn is ONLY in the browser.

**Comment by mnhim001** [comment]
> try going into the qbittorrent settings in dtv and pressing test and connect again then try to send a link to qbt. i've noticed that dtv does have a habit of not sending a clicked link from a show search to qbt if the browser has been open over a certain amount of time. i found doing what i suggested above works to fix the issue for me.
> 
> garfield i'll say it again pushing peeps to the standalone nightly is not the answer. duckie is only worth it if you have a vpn. in my case that vpn is ONLY in the browser.

I've tried this many times over the past few days with no success.

**Comment by mnhim001** [comment]
> Most likely your Dtv Search engines (SE) on Dtv 1.1.5 are the problem.
> 
> The SE on that build are getting out of date with current sites' changed domains, changed search result html, or site closures, etc. I have been fielding quite a few questions like yours recently.
> In particular, the Dtv 1.1.5 1337x SE no longer works because the 1337x web site have changed their download links.
> 
> Also, since 1.1.5 does not come with the Development Tools package, there is no access to the logs which makes diagnostics more difficult.
> 
> Your best bet is to upgrade to the latest Dtv Standalone Nightly from https://github.com/DuckieTV/Nightlies/releases
> 
> This has the latest working SE and torrent client interface updates, as well as including the Development Tools package, so that if it becomes necessary we can start looking at the logs and some some diagnostics.
> 
> try it out and let me know how it goes.

Yes!!!! This worked, your awesome!

**Comment by mnhim001** [comment]
The integration stopped working again.  I had to test and save again and then disable and enable auto-download.

**Comment by garfield69** [comment]
>The integration stopped working again. I had to test and save again and then disable and enable auto-download. 

Just remember that if you shut down qBt for any reason, and you start it back up, you also need to restart Dtv. 
Its a chink in the client interface that means that Dtv is unaware that qBt is gone until it tries to sent a torrent, and once the torrent fails to be sent it breaks the link. Even if qBt is subsequently restarted, Dtv cannot re-establish connection without manual intervention. It is simplest to just restart Dtv and this usually resolves the problem.
