### ISSUE TITLE
remove isohunt2.net

### ISSUE THREAD

**Issue by 2635599** [SchizoDuckie/DuckieTV#1220]
YEARS ago i loved isohunt, but it went by the wayside. now that it seems to be back as isohunt2.net everytime you click a link it opens a new tab with an add. if you click to download a torrent or open a magnet link you get a page telling to dis able your ad blocker. it's one thing to get this behavior once or twice while visiting a site but on every link i don't f'in think so. time for dtv to drop isohunt2.net.

**Comment by garfield69** [comment]
the isohunt2 SE magnet link was out of date. I've updated it so it works again.
as far as isohunt2 using ads is concerned, I am not concerned.
as long as Dtv can fetch a magnet from the site, then I'll leave the SE there as an option for users.
if they (or you) don't want to use it, pick another default SE.
or, if using the multi-SE torrent dialogue, click on the isohunt2 in the dialogue to toggle its activation.
