### ISSUE TITLE
unable to download torrents

### ISSUE THREAD

**Issue by plex-duckietv** [SchizoDuckie/DuckieTV#1222]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...I have the same problem with all of them

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
...Mac

**Describe the problem you are having and steps to reproduce if available**
...I have been unable to download any torrents from DuckieTV, whether they initiate automatically every time I start DuckieTV, or when I press the "Auto Download" button in a series, or even when I manually search for a torrent and press the 'U' (download magnet) button. Although the status is "connected", and I get a message saying that a download has started, and it appears as "torrent launched" in the 'Auto-Download Service Monitor', no download actually appears on uTorrent or Transmission (tried Transmission because I thought it was uTorrent's fault). I then thought it was because I was using the standalone DuckieTV, but I get the same with the online version. It used to work fine a few months ago, but it suddenly stopped. I face the same issue on both my Mac running Mojave as well as my old MacBook running High Siera (no antivirus is installed).

**Attach any DuckieTV statistics or Developer Console logs if available**
...Sorry, not sure how to do this. Thanks for your help!

**Comment by garfield69** [comment]
Most likely your Dtv Search engines (SE) on Dtv 1.1.5 are the problem.

The SE on that build are getting out of date with current sites' changed domains, changed search result html, or site closures, etc. I have been fielding quite a few questions like yours recently.
Also, Dtv 1.1.5 standalone does not come with the Development Tools package included, so we cant look at the log for clues.

Your best bet is to upgrade to the latest Dtv Standalone Nightly from https://github.com/DuckieTV/Nightlies/releases which has the latest working SE and updated torrent client interfaces plus assorted bug fixes.
Plus, the Nightly comes with the Development Tools pack included, so we can browse to log if it becomes necessary.

Note that on the Mac, for the installer to work properly, you will first need to drag the DuckieTV app from your Applications folder to the bin, and then run the installer. Failing to do so will make it appear that the installer worked but the app will not be upgraded.

try it out and let me know how it goes.

**Comment by plex-duckietv** [comment]
Worked perfectly - thank you!
