### ISSUE TITLE
Long titles of poster-less favorites getting cut off

### ISSUE THREAD

**Issue by rikkdekkard** [SchizoDuckie/DuckieTV#1223]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Nightly v201911020130

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 10 x64

**Describe the problem you are having and steps to reproduce if available**

Hello.
I recently switched from the stable version to nightly, and one thing that bugs me is that if a show has a long title and no poster, Duckie crams the entire title into one line resulting in the title getting cut off in a way it didn't in the last stable version.

Here's how it looks:
![1](https://user-images.githubusercontent.com/16802939/68086043-cef7f300-fe47-11e9-9fdd-d3e80dec07f6.png)

With some shows it can be fixed by turning on the "big poster" mode, but if a title is long enough, it still won't fit.

The same issue occurs on the "add new show" page, and it would be really nice if something could be done about that.

**Comment by garfield69** [comment]
@Js41637  any thoughts on this?

**Comment by Js41637** [comment]
i thought it already did 🤔 

i dunno, i can look into soon
