### ISSUE TITLE
Show that never downloads

### ISSUE THREAD

**Issue by Pretzel40k** [SchizoDuckie/DuckieTV#1226]
Standlone Stable 1.1.5 Windows

The show S.W.A.T. never automatically downloads because DuckieTV searches for "SWAT SxxExx" instead of "S.W.A.T. SxxExx".

**Comment by garfield69** [comment]
Yup, 1.1.5 strips out the dots.
upgrade to the latest Dtv Standalone Nightly from https://github.com/DuckieTV/Nightlies/releases
which allows for S.W.A.T to be found correctly.
