### ISSUE TITLE
DTV Not keeping current  with shows

### ISSUE THREAD

**Issue by webgizmos** [SchizoDuckie/DuckieTV#1228]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...Version.1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
...Windows

**Describe the problem you are having and steps to reproduce if available**
...DTV isn't keeping current with episodes of shows.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
I recommend you upgrade to the latest Dtv Standalone Nightly from https://github.com/DuckieTV/Nightlies/releases

if you still have issue after that, then the Nightly has the *Development Tools* pack included which will let you look at the logs and investigate.
I should mention that I am a daily user of Dtv Nightly and it is working fine for me.
Let me know how it goes.

**Comment by webgizmos** [comment]
Will do...and thanks. Other than that everything works fine.
________________________________

**Comment by garfield69** [comment]
how is it  going with the nightly then?
can I close this ticket?

**Comment by webgizmos** [comment]
So sorry Garfield.....yes you can close this ticket....all seems" to be ok...if it happens again I will just start a new ticket. Thanks again! Web
________________________________
