### ISSUE TITLE
Auto Download Not Working

### ISSUE THREAD

**Issue by silentwitness1** [SchizoDuckie/DuckieTV#1229]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
... Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...Nightly v201911220130

**What is your Operating System (Windows, Mac, Linux, Android)**
... Windows 10

**Describe the problem you are having and steps to reproduce if available**
... Auto download is not working, it shows download started but nothing shows up in UTorrent it was working till friday.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
which search engine have you set as your default?

**Comment by silentwitness1** [comment]
eztv

**Comment by garfield69** [comment]
Hmm. works for me.
click on the **Auto Download Services Monitor** icon and review the list of activity from the last run.
![image](https://user-images.githubusercontent.com/6933240/69607478-304b6480-108a-11ea-90ff-15a5d7dbe9ae.png)
can you spot the series/episode you are expecting to be downloaded, can you show me a screen capture so I can test it on my system to see if it works for me?
thanks.

**Comment by silentwitness1** [comment]
it shows fine there, if i change he default to rarbg it downloaded, think there might be some issue with eztv only. I was trying to download NCIS LA and Hawaii five 0 both of which didnt download. I searched for it and it showed me the show and when i click on the magnet link it would still not show up in UTorrent.

edit
changed the default back to EZTV but it does not auto-download

![image](https://user-images.githubusercontent.com/58183245/69616217-3e828c00-105c-11ea-9277-c69cfd5e7bc4.png)

**Comment by garfield69** [comment]
assuming I have picked the same torrent from eztv then it works for me.
press **F12** to open the *Development Tools* page and click on the **Console** tab to view the *Log*.
any errors related to sending the magnet to utorrent webui?
mine looks like this:
![image](https://user-images.githubusercontent.com/6933240/69656938-5569c280-10de-11ea-9e86-99329a4a9c7e.png)

**Comment by silentwitness1** [comment]
the console shows that my antivirus is blocking it which is strange considering its not blocking the same process for rarbg.

![image](https://user-images.githubusercontent.com/58183245/69661905-4583bb80-10a9-11ea-8ee6-8698278cf1bc.png)

**Comment by garfield69** [comment]
Ah.
are you able to load an exception to your ESET AV to let the eztv through?
try to set ESET to leave http://localhost:7070 traffic alone. its local not WAN, so there is not risk of malware in the http traffic between Dtv and Utorrent WEBUI.

**Comment by silentwitness1** [comment]
yes i asked it to leave *localhost:7070* alone and its working now. Thanks for all your help
