### ISSUE TITLE
google store  nightly (tab and action) stuck on 3019.12.5.91

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#1233]
@SchizoDuckie  could you take a look at the state of both of the google store accounts for the **nightly chrome extensions** please, the build bot appears to have failed to push the latest builds to the chrome store, although it appears it did build all the packages on https://github.com/DuckieTV/Nightlies/releases  and pushed to phonegap successfully.
Thanks.

https://chrome.google.com/webstore/detail/duckietv-new-tab-mode-nig/jndkngpbgmnkbhbjafmjhabcjmgeogfc
https://chrome.google.com/webstore/detail/duckietv-browser-action-m/ikhklcamhmfmjbhckdjoabiepglbhaid

**Comment by GraveDigger1** [comment]
garfield is right cause we wouldn't get the github notifications if they weren't being built.

**Comment by SchizoDuckie** [comment]
Looks like i've missed some notifications from the web store.
Apparently some obfuscated lines in dist/app.js now triggers some
anti-obfuscation scan they do and they boot new uploads from the store.

They won't tell me which lines but i a wild guess would be the cheatcode
stuff being the culprit

**Comment by garfield69** [comment]
Oh well that should not be a problem. I still have the original source for the Easter-egg code so I'll swap that back in and see if the next build gets through.

**Comment by SchizoDuckie** [comment]
excellent thanks

**Comment by Js41637** [comment]
lol

**Comment by GraveDigger1** [comment]
this should of stayed open till we know it's fixed.

**Comment by garfield69** [comment]
if it does not work it gets re-opened.
the build tomorrow will tell the tale, I've missed the BuildBots window for today.

**Comment by garfield69** [comment]
@SchizoDuckie The Nightly release for 14-12-2019 01:55:57 has been published but the google store appears unchanged :-(

**Comment by SchizoDuckie** [comment]
[image: image.png]
[image: image.png]

We'll see what the review does.

**Comment by GraveDigger1** [comment]
so even with that goggle's still can't see straight enough to fix a problem they created.

**Comment by garfield69** [comment]
Update:
looks like the Nightly action-mode extensions is being published on the google store, the release matches the latest buildbot run.
but the nightly tab-mode has not been updated since 15th Dec 2019.

**Comment by garfield69** [comment]
@SchizoDuckie  any news on this?
the buildbot has stopped publishing any builds for 8 days now :-(
the phonegap build are coming through, so I presume its the google web store that is blocking?
could you please take a look?
Thanks.

**Comment by SchizoDuckie** [comment]
Sorry, missed this. buildbot disk was full, gave it a good kick.
As far as i can tell from the webstore there's no more queued items waiting for review so we'll see what happens tonight

**Comment by garfield69** [comment]
@SchizoDuckie  thanks.
So I take it that the cleanup routines you instigated via the scheduler are not enough to clear space?
is there additional file creep going on in other parts of the server that need attention?

**Comment by SchizoDuckie** [comment]
Looks like it's mostly nwjs download cache being the culprit upon changing
versions

**Comment by GraveDigger1** [comment]
ok reinstalled the nightly from the webstore and i'm on the one for jan 2nd. not perfect, but far better than still being on dec 18th. looks like you're slowly ferreting out the issue.

**Comment by garfield69** [comment]
The nightly build are happening, and the GitHub releases are being posted, but the google store still only shows both Nightly action and new-tab versions remaining at 3020.1.2.91.
So something is still presumably pending with these chrome extensions releases?
@SchizoDuckie  perhaps there is something in the buildbot logs that hits at what is going on?

**Comment by GraveDigger1** [comment]
wouldn't be surprised goGGle's is deliberately blocking them, just like they do most video downloading apps.

**Comment by SchizoDuckie** [comment]
I sent another mail to google's webstore address regarding this.

**Comment by SchizoDuckie** [comment]
Ugh.
![image](https://user-images.githubusercontent.com/111710/72376690-b1c88600-370e-11ea-9dae-99d2595e6d37.png)
![image](https://user-images.githubusercontent.com/111710/72376728-c147cf00-370e-11ea-8cb0-74b88e0373c5.png)

**Comment by GraveDigger1** [comment]
OMMFG what the BLEEP BLEEP BLEEP BLEEP is wrong with them? i mean how different can the nightly action mode version be from the new tab version. goGGle's beyond stupid. i feel for you, really do. on a side not i can confirm the browser action nightly's are once again being pushed. i just check here before posting this and i'm on 1 /14.

**Comment by SchizoDuckie** [comment]
I'm guessing this means we're going to have to request permissions for every new URL we access, which is something actually possible these days using the new [permissions API](https://developer.chrome.com/apps/permissions).
I'm not certain I have the time to fix it within a week though

**Comment by garfield69** [comment]
the only difference between the action-mode manifest and the new-tab-mode manifest is the TABS permission.
the other permissions are the same, so presumably if the action-mode passes muster, then its the TABS permission that needs refining?

**Comment by SchizoDuckie** [comment]
I don't think it's the tabs permission, rather the http://*.* permission. They just haven't looked at any of the other extensions but when they do they'll undoubtedly nix it

**Comment by GraveDigger1** [comment]
i'd personally call them out on it cause they have had way more than enough time to inform you that there was a problem.

**Comment by Js41637** [comment]
Anything being done into looking how we can fix this? Seeing as the nightlys are basically the only way to get new updates these days, should just look into removing the permission? Is it only needed for finding random mirrors? If it has to be disabled in the chrome versions then we might as well just do it seeing as the alternative is convincing Google to allow it which seems unlikely or change how the permission stuff works which would require time and figuring out how it works.

**Comment by AlienProber** [comment]
Looks like nightly browsers action mode is now once again not building. 020820 is the latest that I have.

**Comment by AlienProber** [comment]
suggestion publish in the opera store with instruction for installing opera extensions in chrome and chromium based browsers that use the chrome store by default, and then just tell the chrome store to f off.

https://www.google.com/search?source=hp&ei=lg91Xo-fBYGLytMPo8aPoAM&q=install+opera+extensions+in+chrome&oq=install+opera+extensions&gs_l=psy-ab.1.0.0l2j0i22i30l4j0i333.18.7970..11753...0.0..1.714.4488.0j16j3j5-1j1......0....1..gws-wiz.......0i131j0i22i10i30.Ykt2a5BkJvo

**Comment by garfield69** [comment]
https://github.com/SchizoDuckie/DuckieTV/issues/1248#issuecomment-621127554

**Comment by SchizoDuckie** [comment]
![image](https://user-images.githubusercontent.com/111710/81170827-a0e0a080-8f9b-11ea-90f0-759ae1547228.png)
Looks like we're back being updated properly.
I'm not going to send chrome users to the opera store if I can. i don't feel like that's a very user friendly solution.

**Comment by AlienProber** [comment]
First we will not know for sure if we are being updated until they actually get piushed to the browsers. Second if push comes to shove the Opera store may be the only recourse you have, I think most of us using DTV would have no issue have to go to the Opera store if needed, so claiming using the Opera store isn't very user friendly is only your opinion.

**Comment by garfield69** [comment]
I think you meant to close #1248

**Comment by SchizoDuckie** [comment]
think they're both resolved? 

![image](https://user-images.githubusercontent.com/111710/81397033-d2d23e00-9126-11ea-8ba3-b101e7436da0.png)

**Comment by SchizoDuckie** [comment]
I see. the chrome dashboard is displaying something different from the webstore. will ping them again.

**Comment by garfield69** [comment]
closing as wontfix.
