### ISSUE TITLE
DTV Browser Action mode 3019.12.18.91 installed but with errors

### ISSUE THREAD

**Issue by GraveDigger1** [SchizoDuckie/DuckieTV#1236]
got tire of goGGle's games with their web store, so i downloaded the latest nightly and loaded / installed it yesterday. seems to work great except it has a few errors. need to know if they need to be addressed or can be ignored.  thanks

Optional permission 'http://*/*' is redundant with the required permissions;this permission will be omitted.

Optional permission 'https://*/*' is redundant with the required permissions;this permission will be omitted.

autoBackup is set to never be scheduled

Could not load fanart for tvdb_id= 365172 [object Object]

Could not load fanart for tvdb_id= 365480 [object Object]

Could not load fanart for tvdb_id= 365832 [object Object]

Could not load fanart for tvdb_id= 3716610 [object Object]

Could not load fanart for tvdb_id= 361868 [object Object]

vivaldi and vivaldi-snapshot on manjaro 18.1.4 rc2 kde 64 bit

**Comment by garfield69** [comment]
> Optional permission 'http:///' is redundant

ignore.

> autoBackup is set to never be scheduled

comes from the Dtv scheduler routine that is reporting that you chose not to schedule a data backup. your choice, your risk.

>Could not load fanart

unfortunately very common. But this simply means that Dtv failed to fetch a picture to display for a series or episode poster. you will get the default Dtv duck image instead.
The fanart web site is run by volunteers, and does not provide images for every tv series ever made.
But also they run on a shoe string budget so their server is often overloaded. little that can be done, other than switching to another provider, which may eventually happen if #1140 is ever completed.

**Comment by GraveDigger1** [comment]
thanks and i see what you mean about the fan art. just clicked the error button again and this time nothing about fan art, and i never cleared the errors. one last thing will this auto update once the issue with google is resolved? thanks again.

**Comment by garfield69** [comment]
No, the auto update applied only to the extension installed from the store.
Since you manually installed an extension using the local **load unpacked** option, its up to you to update it when ever you feel you need to. (Once in a blue moon, or whenever something is broken and we've provided a fix).
