### ISSUE TITLE
synology nas, deluge won't pickup duckietv torrents

### ISSUE THREAD

**Issue by oebie1** [SchizoDuckie/DuckieTV#1237]
i use the duckie 1.1.5 and deluge 1.3.15. duckie on windows 10 en deluge on the sunology nas dsm 5.2
the problem is that duckie is connected to deluge (green) and says connected. 
deluge setup on the nas is /volume1/kodi/torrentfiles as autoad.torrentfiles location.

but when i use duckie he said download on deluge but on deluge nothing started.
...

**Comment by garfield69** [comment]
I recommend you upgrade to the latest Dtv Standalone Nightly from  https://github.com/DuckieTV/Nightlies/releases which contains the latest updates to the Search Engines and torrent Client Interfaces.
If you still cannot get it to work once you have upgraded, then we can help you dig deeper into your configuration and see if we can figure out what could be going on.

Dtv 1.1.5 was published back on July 2017 and is just too out of date to make it worth while using. The latest Dtv Nightly is your best bet to get things working.
Let me know how it goes for you.

**Comment by garfield69** [comment]
presumed solved.
