### ISSUE TITLE
Torrentday not working Jackett Indexer

### ISSUE THREAD

**Issue by carlosealinares** [SchizoDuckie/DuckieTV#1241]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
chrome extension

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
stable 1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
Win 10

**Describe the problem you are having and steps to reproduce if available**
Torrentday (tday.love) not reaching host. tday.love is unavailable, please change host

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
this has nothing to do with DuckieTV.
Jackett provides the indexers, https://github.com/Jackett/Jackett
as it happens, that indexer has already been adjusted, it is only pending a full jackett release being published, when ever that happens next.
