### ISSUE TITLE
Some Downloads Start Others Dont

### ISSUE THREAD

**Issue by szereka** [SchizoDuckie/DuckieTV#1244]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
 1.1.5 Reinstalled all settings wiped

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 10 (I know Its Junk but its what the Laptop Came With)...

**Describe the problem you are having and steps to reproduce if available**
When auto download some start in BiglyBt but Others Dont.

**Attach any DuckieTV statistics or Developer Console logs if available**
Dev Console Show Nothing ...
Have added 3 Pictures allsow
![Duck1](https://user-images.githubusercontent.com/43613232/73451214-64cbed00-4367-11ea-9bf1-41cc10392bd1.JPG)
![Duck2](https://user-images.githubusercontent.com/43613232/73451217-68f80a80-4367-11ea-9a96-05e67a3fe156.JPG)
![Duck3](https://user-images.githubusercontent.com/43613232/73451222-6bf2fb00-4367-11ea-8ac0-80b0e9e4db0f.JPG)

Here is Statistics Page_______________
[
  {
    "name": "DuckieTV Web Based",
    "data": "1.1.5"
  },
  {
    "name": "Current Date and Time",
    "data": "Thu, 30 Jan 2020 12:29:23 GMT"
  },
  {
    "name": "NWJS, Chromium",
    "data": "0.25.0 , 61.0.3163.79"
  },
  {
    "name": "UserAgent",
    "data": "DuckieTV-Standalone  v1.1.5 Windows NT 10.0; Win64; x64"
  },
  {
    "name": "Platform, Vendor",
    "data": "Win32, Google Inc."
  },
  {
    "name": "Screen (width x height)",
    "data": "1600 x 900"
  },
  {
    "name": "Default Search Engine",
    "data": "1337x (Enabled)"
  },
  {
    "name": "Default Torrent Client",
    "data": "BiglyBT (Enabled and Connected to Host)"
  },
  {
    "name": "Auto Download Service",
    "data": "(Enabled and Active)"
  },
  {
    "name": "Last checked TraktTV for DB updates on",
    "data": "Thu, 30 Jan 2020 11:25:36 GMT"
  },
  {
    "name": "User Preferences on Local Storage",
    "data": "{\n  \"ThePirateBay.mirror\": \"https://thehiddenbay.com/\",\n  \"application.language\": \"en_us\",\n  \"application.locale\": \"en_us\",\n  \"aria2.port\": 6800,\n  \"aria2.server\": \"http://localhost\",\n  \"aria2.token\": \"\",\n  \"autobackup.period\": \"monthly\",\n  \"autodownload.delay\": 5,\n  \"autodownload.multiSE\": {\n    \"ThePirateBay\": true,\n    \"1337x\": true,\n    \"IsoHunt\": true,\n    \"KATcr\": true,\n    \"Nyaa\": true,\n    \"RarBG\": true,\n    \"ShowRSS\": true,\n    \"TorrentDownloads\": true,\n    \"TorrentZ2\": true,\n    \"Zooqle\": true,\n    \"EzTV.ag\": true,\n    \"Idope\": true,\n    \"LimeTorrents\": true,\n    \"SkyTorrents\": true\n  },\n  \"autodownload.multiSE.enabled\": false,\n  \"autodownload.period\": 21,\n  \"background-rotator.opacity\": \"0.4\",\n  \"biglybt.password\": \"*****\",\n  \"biglybt.path\": \"/transmission/rpc\",\n  \"biglybt.port\": 8888,\n  \"biglybt.progressX100\": true,\n  \"biglybt.server\": \"http://localhost\",\n  \"biglybt.use_auth\": true,\n  \"biglybt.username\": \"Annon\",\n  \"calendar.mode\": \"date\",\n  \"calendar.show-downloaded\": true,\n  \"calendar.show-episode-numbers\": true,\n  \"calendar.show-specials\": true,\n  \"calendar.startSunday\": false,\n  \"client.determinedlocale\": \"en_us\",\n  \"deluge.password\": \"*****\",\n  \"deluge.port\": 8112,\n  \"deluge.server\": \"http://localhost\",\n  \"deluge.use_auth\": true,\n  \"download.ratings\": true,\n  \"episode.watched-downloaded.pairing\": true,\n  \"kc.always\": false,\n  \"ktorrent.password\": \"*****\",\n  \"ktorrent.port\": 8080,\n  \"ktorrent.server\": \"http://localhost\",\n  \"ktorrent.use_auth\": true,\n  \"ktorrent.username\": \"ktorrent\",\n  \"lastSync\": -1,\n  \"library.order.by\": \"getSortName()\",\n  \"library.order.reverseList\": [\n    true,\n    false,\n    true,\n    true\n  ],\n  \"library.seriesgrid\": true,\n  \"library.smallposters\": true,\n  \"main.viewmode\": \"calendar\",\n  \"notifications.enabled\": true,\n  \"qbittorrent.password\": \"*****\",\n  \"qbittorrent.port\": 8080,\n  \"qbittorrent.server\": \"http://localhost\",\n  \"qbittorrent.use_auth\": true,\n  \"qbittorrent.username\": \"admin\",\n  \"qbittorrent32plus.password\": \"*****\",\n  \"qbittorrent32plus.port\": 8080,\n  \"qbittorrent32plus.server\": \"http://localhost\",\n  \"qbittorrent32plus.use_auth\": true,\n  \"qbittorrent32plus.username\": \"admin\",\n  \"rtorrent.path\": \"/RPC2\",\n  \"rtorrent.port\": 80,\n  \"rtorrent.server\": \"http://localhost\",\n  \"rtorrent.use_auth\": false,\n  \"series.displaymode\": \"poster\",\n  \"series.not-watched-eps-btn\": false,\n  \"storage.sync\": false,\n  \"subtitles.languages\": [\n    \"eng\"\n  ],\n  \"sync.progress\": true,\n  \"synology.enabled\": true,\n  \"synology.ip\": \"192.168.x.x\",\n  \"synology.password\": \"*****\",\n  \"synology.playback_devices\": {},\n  \"synology.port\": 5000,\n  \"synology.protocol\": \"http\",\n  \"synology.username\": \"admin\",\n  \"tixati.password\": \"*****\",\n  \"tixati.port\": 8888,\n  \"tixati.server\": \"http://localhost\",\n  \"tixati.use_auth\": true,\n  \"tixati.username\": \"admin\",\n  \"topSites.enabled\": false,\n  \"topSites.mode\": \"onhover\",\n  \"torrentDialog.2.activeSE\": {\n    \"ThePirateBay\": false,\n    \"1337x\": true,\n    \"IsoHunt\": true,\n    \"KATcr\": false,\n    \"Nyaa\": false,\n    \"RarBG\": false,\n    \"ShowRSS\": false,\n    \"TorrentDownloads\": false,\n    \"TorrentZ2\": false,\n    \"Zooqle\": false,\n    \"EzTV.ag\": true,\n    \"Idope\": false,\n    \"LimeTorrents\": false,\n    \"SkyTorrents\": false\n  },\n  \"torrentDialog.2.enabled\": true,\n  \"torrentDialog.2.sortBy\": \"+engine\",\n  \"torrentDialog.showAdvanced.enabled\": true,\n  \"torrenting.autodownload\": true,\n  \"torrenting.autostop\": true,\n  \"torrenting.autostop_all\": false,\n  \"torrenting.client\": \"BiglyBT\",\n  \"torrenting.directory\": true,\n  \"torrenting.enabled\": true,\n  \"torrenting.global_size_max\": 800,\n  \"torrenting.global_size_max_enabled\": true,\n  \"torrenting.global_size_min\": null,\n  \"torrenting.global_size_min_enabled\": true,\n  \"torrenting.ignore_keywords\": \"\",\n  \"torrenting.ignore_keywords_enabled\": true,\n  \"torrenting.label\": false,\n  \"torrenting.launch_via_chromium\": false,\n  \"torrenting.min_seeders\": 5,\n  \"torrenting.min_seeders_enabled\": false,\n  \"torrenting.progress\": true,\n  \"torrenting.require_keywords\": \"WEB 720p HDTV\",\n  \"torrenting.require_keywords_enabled\": true,\n  \"torrenting.require_keywords_mode_or\": true,\n  \"torrenting.searchprovider\": \"1337x\",\n  \"torrenting.searchquality\": \"HDTV\",\n  \"torrenting.searchqualitylist\": [\n    \"480p\",\n    \"HDTV\",\n    \"720p\",\n    \"1080p\",\n    \"2160p\"\n  ],\n  \"torrenting.streaming\": true,\n  \"trakt-update.period\": 1,\n  \"trakttv.passwordHash\": \"*****\",\n  \"trakttv.sync\": true,\n  \"trakttv.username\": null,\n  \"transmission.password\": \"*****\",\n  \"transmission.path\": \"/transmission/rpc\",\n  \"transmission.port\": 9091,\n  \"transmission.progressX100\": true,\n  \"transmission.server\": \"http://localhost\",\n  \"transmission.use_auth\": true,\n  \"transmission.username\": \"admin\",\n  \"utorrentwebui.password\": \"*****\",\n  \"utorrentwebui.port\": 8080,\n  \"utorrentwebui.server\": \"http://localhost\",\n  \"utorrentwebui.use_auth\": true,\n  \"utorrentwebui.username\": \"admin\",\n  \"vuze.password\": \"*****\",\n  \"vuze.path\": \"/transmission/rpc\",\n  \"vuze.port\": 9091,\n  \"vuze.progressX100\": true,\n  \"vuze.server\": \"http://localhost\",\n  \"vuze.use_auth\": true,\n  \"vuze.username\": \"vuze\",\n  \"autodownload.lastrun\": 1580386967360\n}"
  },
  {
    "name": "Other significant Local Storage keys",
    "data": "{\n  \"1.1.4TorrentHashListCleanup\": \"Thu Jan 30 2020 10:10:12 GMT+0100 (W. Europe Standard Time)\",\n  \"1.1.4cleanupOrphanedEpisodes\": \"Thu Jan 30 2020 10:10:10 GMT+0100 (W. Europe Standard Time)\",\n  \"1.1.4cleanupOrphanedSeasons\": \"Thu Jan 30 2020 10:10:11 GMT+0100 (W. Europe Standard Time)\",\n  \"1.1.4qBittorrentPre32\": \"Thu Jan 30 2020 10:10:06 GMT+0100 (W. Europe Standard Time)\",\n  \"1.1.4refresh\": \"Thu Jan 30 2020 10:10:16 GMT+0100 (W. Europe Standard Time)\",\n  \"1.1.4refreshTrendingCache\": \"Thu Jan 30 2020 10:10:06 GMT+0100 (W. Europe Standard Time)\",\n  \"1.1.4updateTransmissionPath\": \"Thu Jan 30 2020 10:10:06 GMT+0100 (W. Europe Standard Time)\",\n  \"1.1.5FetchFirstXemAliasMap\": \"Thu Jan 30 2020 10:10:06 GMT+0100 (W. Europe Standard Time)\",\n  \"1.1.5deleteSearchEngines\": \"Thu Jan 30 2020 10:10:06 GMT+0100 (W. Europe Standard Time)\",\n  \"1.1.5fanartCleanup\": \"Thu Jan 30 2020 10:10:32 GMT+0100 (W. Europe Standard Time)\",\n  \"1.1.5updateDelugeAuth\": \"Thu Jan 30 2020 10:10:06 GMT+0100 (W. Europe Standard Time)\",\n  \"1.1.5updateTorrenting.min_seeders\": \"Thu Jan 30 2020 10:10:06 GMT+0100 (W. Europe Standard Time)\",\n  \"1.1migration\": \"Thu Jan 30 2020 10:10:09 GMT+0100 (W. Europe Standard Time)\",\n  \"autobackup.lastrun\": \"1580375406882\",\n  \"database.version.Episodes\": \"14\",\n  \"database.version.Fanart\": \"1\",\n  \"database.version.Jackett\": \"2\",\n  \"database.version.Seasons\": \"6\",\n  \"database.version.Series\": \"16\",\n  \"database.version.WatchList\": \"1\",\n  \"database.version.WatchListObject\": \"1\",\n  \"fanart.bootstrapped\": \"1\",\n  \"github.lastupdatecheck\": \"1580375408142\",\n  \"snr.lastFetched\": \"1580375407389\",\n  \"standalone.position\": \"{\\\"width\\\":1602,\\\"height\\\":862,\\\"x\\\":0,\\\"y\\\":0,\\\"state\\\":\\\"normal\\\"}\",\n  \"standalone.zoomlevel\": \"6\",\n  \"torrenting.client\": \"BiglyBT\",\n  \"trackers.lastFetched\": \"1580375407760\",\n  \"trakttv.lastupdated\": \"1580383536098\",\n  \"trakttv.lastupdated.trending\": \"1580375419385\",\n  \"trakttv.refresh_token\": \"25619b430b152db8d7a76228ee22dbf57747e7cb72ecf99a0d2d4813ca676588\",\n  \"upgrade.notify\": \"1.1.5\",\n  \"xem.lastFetched\": \"1580375407392\"\n}"
  },
  {
    "name": "DB Series",
    "data": 143
  },
  {
    "name": "DB Series Hidden From Calendar",
    "data": 0
  },
  {
    "name": "DB Seasons",
    "data": 873
  },
  {
    "name": "DB Episodes",
    "data": 15192
  },
  {
    "name": "DB Fanart",
    "data": 1955
  },
  {
    "name": "DB Jackett",
    "data": 0
  }
]

here Is From BiglyBT Remote Log__________________

-> {"method":"session-get"}
<- 2223
<- {"result":"success","arguments":{"download-queue-enabled":true,"port":51186,"config-dir":"","peer-limit-global":1500,"encryption":"preferred","alt-speed-up":50,"idle-seeding-limit":30,"alt-speed-time-day":127,"download-dir-free-space":2109199171584,"peer-port":51186,"alt-speed-down":50,"incomplete-dir-enabled":false,"alt-speed-time-begin":540,"queue-stalled-minutes":30,"cache-size-mb":0,"rpc-tor-address":"","pex-enabled":true,"seed-queue-size":-9,"alt-speed-enabled":false,"incomplete-dir":"T:\\BIGLY_TORRENT\\OTHERS","blocklist-enabled":true,"seedRatioLimited":false,"download-queue-size":33,"peer-limit-per-torrent":150,"utp-enabled":true,"speed-limit-up-enabled":true,"seed-queue-enabled":true,"biglybt-version":"2.2.0.2","alt-speed-time-enabled":false,"speed-limit-down-enabled":false,"rpc-version-minimum":6,"trash-original-torrent-files":false,"speed-limit-up":79186,"speed-limit-down":0,"port-forwarding-enabled":false,"seedRatioLimit":0.0,"az-version":"5.7.5.0","alt-speed-time-end":1020,"download-dir":"T:\\BIGLY_TORRENT\\OTHERS","blocklist-url":"","lpd-enabled":false,"script-torrent-done-enabled":false,"version":"0.8.6","start-added-torrents":true,"rename-partial-files":false,"az-rpc-version":7,"blocklist-size":0,"dht-enabled":true,"active-queue-size":42,"rpc-i2p-address":"","az-content-port":58979,"rpc-supports":["rpc:receive-gzip","field:files-hc","method:tags-get-list","field:torrent-set-name","method:subscription-get","method:subscription-add","method:subscription-remove","method:subscription-set","method:vuze-plugin-get-list","method:tags-lookup-start","method:tags-lookup-get-results","method:vuze-search-start","method:vuze-search-get-results","torrent-add:torrent-duplicate","field:session:active-queue-size","method:rcm-get-list","method:rcm-create-subscription","method:rcm-set-read","method:rcm-is-enabled","method:vuze-subs-list","method:rcm-lookup-start","method:rcm-lookup-remove","method:rcm-remove","method:rcm-lookup-get-results","method:rcm-set-enabled"],"ratio-limit-enabled":false,"rpc-version":15,"script-torrent-done-filename":"","queue-stalled-enabled":true,"ratio-limit":2.0,"idle-seeding-limit-enabled":false,"upload-slots-per-torrent":14,"peer-port-random-on-start":false}}

Access denied: Incorrect user name: 

Header:
POST /transmission/rpc HTTP/1.1
Host: localhost:8888
connection: keep-alive
Content-Length: 24
Accept: application/json, text/plain, */*
Origin: chrome-extension://bagblfnohpiddokbpaacecffdboomafe
User-Agent: DuckieTV-Standalone  v1.1.5 Windows NT 10.0; Win64; x64
X-Transmission-Session-Id: null
Content-Type: application/json;charset=UTF-8
Accept-Encoding: gzip,deflate,br,identity
Accept-Language: en-US,en;q=0.8
Cookie: vuze_pairing_sc=AIPKLB3D3B3YCVW7ULCDIU5IWOEXYGDF; X-Transmission-Session-Id=0x1.d57a969ef5ccp-4

409: {"method":"session-get"}
Access denied: Incorrect user name: 
-> {"method":"session-get"}
<- 2223
<- {"result":"success","arguments":{"download-queue-enabled":true,"port":51186,"config-dir":"","peer-limit-global":1500,"encryption":"preferred","alt-speed-up":50,"idle-seeding-limit":30,"alt-speed-time-day":127,"download-dir-free-space":2109199171584,"peer-port":51186,"alt-speed-down":50,"incomplete-dir-enabled":false,"alt-speed-time-begin":540,"queue-stalled-minutes":30,"cache-size-mb":0,"rpc-tor-address":"","pex-enabled":true,"seed-queue-size":-9,"alt-speed-enabled":false,"incomplete-dir":"T:\\BIGLY_TORRENT\\OTHERS","blocklist-enabled":true,"seedRatioLimited":false,"download-queue-size":33,"peer-limit-per-torrent":150,"utp-enabled":true,"speed-limit-up-enabled":true,"seed-queue-enabled":true,"biglybt-version":"2.2.0.2","alt-speed-time-enabled":false,"speed-limit-down-enabled":false,"rpc-version-minimum":6,"trash-original-torrent-files":false,"speed-limit-up":79186,"speed-limit-down":0,"port-forwarding-enabled":false,"seedRatioLimit":0.0,"az-version":"5.7.5.0","alt-speed-time-end":1020,"download-dir":"T:\\BIGLY_TORRENT\\OTHERS","blocklist-url":"","lpd-enabled":false,"script-torrent-done-enabled":false,"version":"0.8.6","start-added-torrents":true,"rename-partial-files":false,"az-rpc-version":7,"blocklist-size":0,"dht-enabled":true,"active-queue-size":42,"rpc-i2p-address":"","az-content-port":58979,"rpc-supports":["rpc:receive-gzip","field:files-hc","method:tags-get-list","field:torrent-set-name","method:subscription-get","method:subscription-add","method:subscription-remove","method:subscription-set","method:vuze-plugin-get-list","method:tags-lookup-start","method:tags-lookup-get-results","method:vuze-search-start","method:vuze-search-get-results","torrent-add:torrent-duplicate","field:session:active-queue-size","method:rcm-get-list","method:rcm-create-subscription","method:rcm-set-read","method:rcm-is-enabled","method:vuze-subs-list","method:rcm-lookup-start","method:rcm-lookup-remove","method:rcm-remove","method:rcm-lookup-get-results","method:rcm-set-enabled"],"ratio-limit-enabled":false,"rpc-version":15,"script-torrent-done-filename":"","queue-stalled-enabled":true,"ratio-limit":2.0,"idle-seeding-limit-enabled":false,"upload-slots-per-torrent":14,"peer-port-random-on-start":false}}
Access denied: Incorrect user name: 
-> {"method":"torrent-get","arguments":{"fields":["id","name","hashString","status","error","errorString","eta","isFinished","isStalled","leftUntilDone","metadataPercentComplete","percentDone","sizeWhenDone","files","rateDownload","rateUpload","downloadDir"]}}
<- 48
<- {"result":"success","arguments":{"torrents":[]}}

**Comment by garfield69** [comment]
Dtv 1.1.5 has out of date Search Engines (SE) and Client Interfaces (CI).
the 1337x web site changed their download links back in June 2019 and the Dtv 1337x SE is broken.

I recommend upgrading your Dtv to the latest Dtv Nightly Standalone from https://github.com/DuckieTV/Nightlies/releases
this has all the latest bug fixes and improvements, including working SE and CI.
In addition, it comes with the *Development Tools* pack, which allows you to look at the log via the **F12** key to open the DT page, and clicking on the **Console** tab to view to log messages.

Try it out and let me know how it goes.

**Comment by szereka** [comment]
**Bingo**  **_Have A Big :cookie:_**

 For the Help now it Works =)

**Comment by garfield69** [comment]
\o/
