### ISSUE TITLE
ver. 1.15 has major issues on Chrome / Browser Action Mode

### ISSUE THREAD

**Issue by packetpuzzler** [SchizoDuckie/DuckieTV#1247]
Chrome Extension
...

**What version of DuckieTV are you using (Stable 1.1.5)
...

**What is your Operating System (Windows 8.1)

Chrome ver. 80.0.3987.122 (Official Build) (64-bit)
...

Opening Duckie via Chrome Extension button. 

There are *no* TV shows displayed at all. 

Selecting Add A Show: When clicking on the show to add it, I get the spinner but nothing else happens.

When I try to restore a database, I get the spinners but nothing else happens.
...

**Attach any DuckieTV statistics or Developer Console logs if available**

Note: I have restarted Chrome but the above problems still persist.
...

**Comment by garfield69** [comment]
Looks like chrome (or some clean up tool from windows/google/anti-malware) has deleted your Dtv settings (including the database stamps), so DuckieTV does not know what version of the DB it is using and cannot access the data.

In any case  Dtv 1.1.5 was published back in 2017 and is using out of date Search Engines (for sites that have changed their web pages, or closed down, or moved to new domains), and out of date    Torrent client interface (that have changed with new torrent client versions).

I recommend switching to the DuckieTV Nightly Standalone from https://github.com/DuckieTV/Nightlies/releases to be on the latest supported Dtv.

But if you really want to continue using the 1.1.5 chrome extension, then I suggest 
1. accessing the extensions page chrome://extensions/ , 
2. remove the Dtv 1.1.5, 
3.  completely shutdown the browser and start it up again 
4. add the extension anew https://chrome.google.com/webstore/detail/duckietv-browser-action-m/cdfkaloficjmdjbgmckaddgfcghgidei

hopefully that will build the settings anew. If you have a Dtv-backup you can import it and be almost up to date.

let me know how it goes.

**Comment by garfield69** [comment]
presumed resolved.

**Comment by packetpuzzler** [comment]
Yes, resolved. Thanks!
