### ISSUE TITLE
Nightly buildbot needs a kick again

### ISSUE THREAD

**Issue by ilike2burnthing** [SchizoDuckie/DuckieTV#1248]
9 days without a new release

**Comment by garfield69** [comment]
@SchizoDuckie  the bot finally ran a build today ( the first since Feb 21) for March 1. \o/
However, only 10 assets were attached. :-(
Comparing the assets list with the previous build, it appears the linux-x64 package is missing.

**Comment by AlienProber** [comment]
More than 9 days here. The 8th is the last update I got in Vivaldi on Manjaro.

**Comment by garfield69** [comment]
@SecretAgentAgentX  we are not counting the nightly chrome extensing in this ticket, that is covered in #1233 and is a separate issue with the Google Chrome Web Store. ;-) 
This ticket deals with the build bot that published the Nightly releases, which apparently regularly runs out of disk space, and prevents even the Standalone Nightly from being published.

**Comment by garfield69** [comment]
looking back over the last 6 releases it appears assorted platform builds got left out, 1 or 2 assets of the usual 12. No particular asset, linux64, windows32, android, chrome-action, ubuntu32 are amoung the randomly missing.
possibly related to how much space is available?
first signs of trouble started on Feb 12. the build for Mar 05 is back up to 12 assets.

**Comment by AlienProber** [comment]
It's more than 9 days here. I have V3020 2-8-91.

**Comment by ilike2burnthing** [comment]
4 days with no new build, preceded by another dropped asset (OSX x64). Not a big deal, but just made me wonder if there is a more long term solution to this recurring issue? If the problem is one of space, would wiping out everything pre-2019 (or something along those lines) resolve it? Or is there a way to do a rolling deletion of the oldest files when new ones are uploaded (with a decent enough buffer of free space)?

Apologies if any or all of that is ignorant, I just don't want to seem like I'm nagging each time the updates get interrupted.

Thanks for all the work! 👍

**Comment by AlienProber** [comment]
still on 2.8.91 for the nightly

**Comment by garfield69** [comment]
@SecretAgentAgentX 
re: still on 2.8.91 for the nightly

Again, your comment has nothing to do with this ticket.  refer my prior comment
https://github.com/SchizoDuckie/DuckieTV/issues/1248#issuecomment-593049929

**Comment by AlienProber** [comment]
@garfield69 next time ask if someone saw your previous post and or forgot about you previous post. thanks

**Comment by ilike2burnthing** [comment]
10 days with no new build

**Comment by ilike2burnthing** [comment]
@SchizoDuckie ping

**Comment by garfield69** [comment]
@SchizoDuckie  I've got a few minor SE updates to ship out, (domain changes), and it would be nice if the buildbot could release a Dtv Nightly Standalone, as the last build was back on March 18th.
Since the Web Store is preventing publishing of the chrome extensions, would preventing the build of those two free up a little more working room, or are the nwjs builds so dam large it wont make a difference?

**Comment by SchizoDuckie** [comment]
the webstore output is negligible.
the biggest problem is all the variations of nwjs with the binaries they
produce.

I created a more rigorous nightly cleanup cronjob that i hope fill finally
fix this.

**Comment by AlienProber** [comment]
How about doing what I suggested and port these over to the Opera store and give those running Chrome, Vivaldi, Brave, etc.... instructions for installing stall the DVT extensions from the Opera store.

**Comment by garfield69** [comment]
@SchizoDuckie  Sorry, but it does not look like the buildbot has managed to publish anything since your cronjob update 2 days ago. Please investigate when you are able. Thanks.

**Comment by AlienProber** [comment]
Nightly browser action mode is stuck at 3020.2.8.91 not 3019.12.5.91.

**Comment by garfield69** [comment]
@SchizoDuckie 
https://www.reddit.com/r/duckietv/comments/gdqdju/search_engines/ hightlights the first person to ask for a Search Engine update, which I cannot provide via the Standalone Nightly until the Buildbot is working again.

**Comment by SchizoDuckie** [comment]
looking into it again now. sorry for the delay.

**Comment by SchizoDuckie** [comment]
x-server had locked up. Triggering build manually and will monitor the current days

**Comment by garfield69** [comment]
Thank you @SchizoDuckie , so far so good. Nightly release for 06-05-2020 01:55:36 just got built.

**Comment by Js41637** [comment]
Haven't been following for a while, are both the nightly webstore versions still upgrading? I use new tab but I don't think it's updated for a while.

**Comment by garfield69** [comment]
@Js41637 wrote:
>are both the nightly webstore versions still upgrading? 

no, store publishing is broken, tracked separately on #1233

**Comment by garfield69** [comment]
Oops. Its been 8 days since the buildbot created a Nightly release.
This coincides with a update I did to bump NWJS  to 47.1 on 29 july.
@SchizoDuckie  would you please service the buildbot server to free up the required disk space?
Thanks.

**Comment by SchizoDuckie** [comment]
buildbot thoroughly kicked.

![kicked](https://user-images.githubusercontent.com/111710/89464411-b74ff100-d770-11ea-91e4-24148dab7bde.gif)

**Comment by garfield69** [comment]
@SchizoDuckie  wrote:
>buildbot thoroughly kicked.

Does not seem to have solved the issue. The buildbot has not released anything on https://github.com/DuckieTV/Nightlies/releases so far :-(

**Comment by garfield69** [comment]
@SchizoDuckie  Its been nearly a month since the bot has published a Nightly on https://github.com/DuckieTV/Nightlies/releases.
Could you please make time to try get it working again.
Thanks.

**Comment by SchizoDuckie** [comment]
I built it manually yesterday and tried to kick it well enough to get it
going again, but it doesn't seem to have worked.
No idea why, still, logs tell nothing.

>

**Comment by garfield69** [comment]
Schizoduckie wrote:
> I built it manually yesterday and tried to kick it well enough to get it going again, but it doesn't seem to have worked. No idea why, still, logs tell nothing.

Seems odd that your manual build works but the automated one fails...
I presume you are using a scheduler to launch each of the four build step and run them one after the other, (prepare, make-binaries, package-binaries, publish)... if that is the case, could perhaps the steps be running into each other now, if it now takes longer to complete each step than you previously allowed?

**Comment by SchizoDuckie** [comment]
yeah they're running using just regular crontab scheduling and they're
already well apart.
i'll try to space them out some more and hope to have some more time for
investigation over the weekend

**Comment by SchizoDuckie** [comment]
That's a lead at least.

```
Pushing new release
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
100 2209 100 1992 100 217 1994 217 0:00:01 --:--:-- 0:00:01 1993
/var/www/deploy/binaries/DuckieTV-20200911-android.apk: No such file or
directory
Warning: Couldn't read data from file
Warning: "/var/www/deploy/binaries/DuckieTV-20200911-Windows-ia32.exe", this
Warning: makes an empty POST.
{"message":"Validation
Failed","request_id":"DC57:60E2:527B07F:57A07CC:5F5B2DA1","documentation_url":"
https://docs.github.com/rest","errors":[{"resource":"Relea
seAsset","code":"custom","field":"size","message":"size is not included in
the list"}]}Warning: Couldn't read data from file
Warning: "/var/www/deploy/binaries/DuckieTV-20200911-Windows-x64.exe", this
Warning: makes an empty POST.
{"message":"Validation
Failed","request_id":"DC58:B484:1F3D4C6:211F762:5F5B2DA2","documentation_url":"
https://docs.github.com/rest","errors":[{"resource":"Relea
seAsset","code":"custom","field":"size","message":"size is not included in
the list"}]}Warning: Couldn't read data from file
Warning: "/var/www/deploy/binaries/DuckieTV-20200911-OSX-x64.pkg", this
makes
Warning: an empty POST.
```` 

to be continued!

**Comment by garfield69** [comment]
is the crontab  schedules disc clean up job that you set up a little while back getting launched in the middle of the build?

**Comment by SchizoDuckie** [comment]
nope it's not. but there's a base path there that's incorrect. will work
more on this tomorrow.

**Comment by garfield69** [comment]
@SchizoDuckie  any news on the state of the buildbot server and the finding you reported earlier in https://github.com/SchizoDuckie/DuckieTV/issues/1248#issuecomment-690940373 ?

Also of note: https://blog.phonegap.com/update-for-customers-using-phonegap-and-phonegap-build-cc701c77502c
this will impact on the DEMO duckietv as well as the android builds.

Since the buildbot has not generated any Nightlys unaided to date, and since we've recently made some changes to Dtv, can you run a manual build so the nightlys can get an updated build generated?
Thanks.

**Comment by AlienProber** [comment]
@SchizoDuckie we are stuck at the 09082020 build.

**Comment by talios** [comment]
Can we bump nightlies again?  I'm not seeing any search results so no downloads

**Comment by ilike2burnthing** [comment]
Until the buildbot is given another loving nudge, garfield69's builds are where the updates are coming from at the moment - https://github.com/SchizoDuckie/DuckieTV/issues/1273#issuecomment-720350100

**Comment by talios** [comment]
Sweet - I just pulled down the nwjs SDK and set it up to run from angular/HEAD as well. Looks like the search might be rar.bg specific - need to investigate and possibly raise a separate issue.

**Comment by garfield69** [comment]
RarBG's API server is very dodgy ATM, failing to return results 3 out of 4 requests. 
Seeing this with Jackett users that have the RarBG indexer configured as well. Been that way for nearly a month.
Nothing can be done about this, other than to hope the RarBG support can sort it out.

**Comment by AlienProber** [comment]
Noticed the behavior with RarBG under Sonarr and Radarr as well.

**Comment by SchizoDuckie** [comment]
I think I just fixed the buildbot. It was failing hard on the chrome webstore upload.
Disabled the webstore upload for now and i'm pulling DuckieTV off of it, as we're not going to be complying with all those permission requests they require as per their new regulations.

One of the nightly builds has status 'taken down'already and as this is all still running under my private account I need to get these migrated somehow. I don't want to have them eventually lock my entire account.
![image](https://user-images.githubusercontent.com/111710/99851626-a096a400-2b7f-11eb-9163-798d0ee54948.png)

**Comment by garfield69** [comment]
>I think I just fixed the buildbot. It was failing hard on the chrome webstore upload.

Good job. 
Glad to have the Nightly back, even if it is only the Standalone packages.

**Comment by AlienProber** [comment]
I can confirm that it seems to be backup and running. Just got the email for the 11/20 release. Great job.
