### ISSUE TITLE
Wrong series: How to correct?

### ISSUE THREAD

**Issue by whtv** [SchizoDuckie/DuckieTV#1250]
I have the show [Maniac (2018)](https://trakt.tv/shows/maniac-2018) in my trakt collection, but DuckieTV puts [Maniac](https://trakt.tv/shows/maniac) in my favorites. So somewhere between fetching the collection info from trakt and fetiching the series info from TVDB something goes wrong. How can I manually correct the series entry in my favorites?

**Comment by garfield69** [comment]
Strange. 
Are you using DuckieTV Standalone 1.1.5?

If so then I recommend upgrading to the Dtv Standalone Nightly from https://github.com/DuckieTV/Nightlies/releases which contains all the latest fixes and working Search Engines and torrent client interfaces.

If the Nightly still imports the wrong series from Trakt.TV then the only way forward that I can see for you, would be to:
- Use your Browser and ensure that your Trakt.tv account does not have the Maniac 2015 in your collection, and history. Remove them if found. 
- Navigate to the **maniac** series details page on Dtv and click on the **remove-from-favourites**.
- Access the Dtv **add-a-show** page and search for maniac. 
- Add the correct maniac series.

Let me know how you go.

**Comment by whtv** [comment]
Even more strange, when I checked again today there were both series in my favorites. The 2015 show I have never watched and it is not in any of my trakt lists. Anyway, I just deleted it from my dtv favorites. Thanks for your help!
