### ISSUE TITLE
Logging for qbittorrent errors

### ISSUE THREAD

**Issue by lmgutman** [SchizoDuckie/DuckieTV#1251]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...StandAlone 

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...DuckieTV-202003050130-OSX-x64

**What is your Operating System (Windows, Mac, Linux, Android)**
...Mac

**Describe the problem you are having and steps to reproduce if available**
...Trying to connect to qBittorrent 3.2+ on the same mac

**Attach any DuckieTV statistics or Developer Console logs if available**
... I have tested the http://localhost:8080/ locally and it works just fine.

**Comment by garfield69** [comment]
Works for me on my Mojave image using qBt 4.2.2 and Dtv Nightly.
Have a look at https://github.com/SchizoDuckie/DuckieTV/wiki/Setting-up-qBitTorrent-3.2-with-DuckieTV and see if that helps you out.
Report back if you still have a problem, and we can take a deeper look at your setup to see if we can figure out whats is amiss.

**Comment by garfield69** [comment]
presumed fixed by OP using wiki.

**Comment by lmgutman** [comment]
sorry my reply must of gotten lost.

**Comment by lmgutman** [comment]
do you think utorrent web might be getting in the way?

**Comment by garfield69** [comment]
Dtv cannot connect with uTorrent WEB, this is a different app to the uTorrent classic.
The uTorrent WEB app does not have an API for Dtv to interface with. It cannot be supported by Dtv.

**Comment by garfield69** [comment]
however, if you are using multiple torrent clients, then make sure that the ports they are both using are different. Otherwise which ever app starts first grabs the port and Dtv may be trying to talk to the wrong app via the port you have set in the Dtv torrent client settings.

**Comment by garfield69** [comment]
And if you are changing ports, then after changing the torrent app settings, reboot the machine to free up the old port.
And before starting Dtv, bring up only the torrent app you plan to connect Dtv to, at least until you manage to complete the Dtv Torrent client settings and connect and save. 
This only applies during the period you are setting up Dtv for connection.
After that,  you should be good and reboots or apps restart should not be an issue later.
