### ISSUE TITLE
1080p/1080i searching problem with ArenaBG tracker

### ISSUE THREAD

**Issue by lapd87** [SchizoDuckie/DuckieTV#1258]
As title it searches for 1080p but lately they add torrents with 1080i tags.

**Comment by garfield69** [comment]
https://github.com/SchizoDuckie/DuckieTV/wiki/FAQ#how-do-i-set-the-quality-for-an-individual-series

**Comment by lapd87** [comment]
thank you! I have added just 1080 will see how it works for me. If you have the option it will be good if there is no result in any search with 1080p to search for 1080i also for 720p/i and so on or just 1080/720 -> default 1080p if no result 1080.
