### ISSUE TITLE
Episode gets redownload repeatedly

### ISSUE THREAD

**Issue by janlofredy** [SchizoDuckie/DuckieTV#1259]
DuckieTV Standalone v1.1.5
Windows 10
Rick and Morty S04E07 Automatically gets unmarked as downloaded. Then it automatically redownloads the episode.

**Comment by garfield69** [comment]
the first thing I suggest you do is upgrade to Dtv Nightly Standalone from https://github.com/DuckieTV/Nightlies/releases
does any other episode from this or any other series behave this way?

**Comment by janlofredy** [comment]
i've only noticed this one. I dont follow a lot of series.

**Comment by garfield69** [comment]
ok. 
have you changed or upgraded your torrent client recently?

Also, check the **Dtv > Settings > Torrents**, scroll to the bottom and check that the **Torrent Parameters** is **disabled** (there will be a red **X** to the right of the title

Then access the Dtv **About** page, its the (i) icon on the bottom left), scroll down to the **Statistics** section and **PrintScreen** and paste here the first 10 rows or so

then access the ADSM ( list Icon labelled AutoDownload Service Monitor) and screenprint and paste that page too.

**Comment by janlofredy** [comment]
I updated to nightly build, and the bug wont replicate.
