### ISSUE TITLE
DuckieTV does not reconnect to QbTorrent WebUI after computer wakes up from sleep

### ISSUE THREAD

**Issue by mymainmandeebo** [SchizoDuckie/DuckieTV#1261]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Nightly 202002040130

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 10

**Describe the problem you are having and steps to reproduce if available**
DuckieTV does not reconnect to QbTorrent WebUI after computer wakes up from sleep. To fix, I have to go back into QBtorrent integration screen and hit "test and save" to re-establish the connection.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
Yes this is a know quirk that will not be fixed.
Dtv has no way to be made aware that the system was put to sleep and woken back up, and does not have any way to detect that the link to qBt needs to be re-established.
You either do what you are doing, or shut down Dtv before sleep and start it up when you wake it up.
