### ISSUE TITLE
uTorrent - Popups saying Download started but it has not

### ISSUE THREAD

**Issue by RipStever** [SchizoDuckie/DuckieTV#1264]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...
Standlone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...
Stable v1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
...
Windows 10

**Describe the problem you are having and steps to reproduce if available**
...
I get a DuckieTV popup saying that the download started in uTorrent, but nothing happens in uTorrent. 

uTorrent Classic v 3.5.5 
uTorrent is open.

1337x is set as my search engine. 

**Attach any DuckieTV statistics or Developer Console logs if available**
...
In the Auto-Download Service Monitor it says "torrent launched."

**Comment by garfield69** [comment]
Dtv 1.1.5 is well out of date with Search Engines and Torrent Client interfaces.
Recommend you upgrade to the Dtv Standalone Nightly from https://github.com/DuckieTV/Nightlies/releases and see if that sorts out your.problem.
Let me know how you go.

**Comment by RipStever** [comment]
That did the trick! You are amazing!!
