### ISSUE TITLE
Favorite shows wont load

### ISSUE THREAD

**Issue by jfmoly** [SchizoDuckie/DuckieTV#1265]
When I go to view my favorite shows it wont load at all.  It wont even show up on the calendar nor will it let me add new shows.

Here's the statics of DuckieTV, screenshots, and the unique tracking id.

[
  {
    "name": "DuckieTV Web Based",
    "data": "1.1.5"
  },
  {
    "name": "Current Date and Time",
    "data": "Tue, 30 Jun 2020 15:27:22 GMT"
  },
  {
    "name": "NWJS, Chromium",
    "data": "0.25.0 , 61.0.3163.79"
  },
  {
    "name": "UserAgent",
    "data": "DuckieTV-Standalone  v1.1.5 X11; Linux x86_64"
  },
  {
    "name": "Platform, Vendor",
    "data": "Linux x86_64, Google Inc."
  },
  {
    "name": "Screen (width x height)",
    "data": "1920 x 1080"
  },
  {
    "name": "Default Search Engine",
    "data": "RarBG (Enabled)"
  },
  {
    "name": "Default Torrent Client",
    "data": "Deluge (Enabled and Connected to Host)"
  },
  {
    "name": "Auto Download Service",
    "data": "(Enabled and Active)"
  },
  {
    "name": "Last checked TraktTV for DB updates on",
    "data": "Tue, 30 Jun 2020 13:58:41 GMT"
  },
  {
    "name": "User Preferences on Local Storage",
    "data": "{\n  \"ThePirateBay.mirror\": \"https://thepiratebay.org\",\n  \"application.language\": \"en_us\",\n  \"application.locale\": \"en_us\",\n  \"aria2.port\": 6800,\n  \"aria2.server\": \"http://localhost\",\n  \"aria2.token\": \"\",\n  \"autobackup.period\": \"monthly\",\n  \"autodownload.delay\": 1,\n  \"autodownload.multiSE\": {\n    \"ThePirateBay\": true,\n    \"1337x\": true,\n    \"IsoHunt\": true,\n    \"KATcr\": true,\n    \"Nyaa\": true,\n    \"RarBG\": true,\n    \"ShowRSS\": true,\n    \"TorrentDownloads\": true,\n    \"TorrentZ2\": true,\n    \"Zooqle\": true,\n    \"ETag\": true,\n    \"ETTV\": true,\n    \"EXT\": true,\n    \"EzTV.ag\": true,\n    \"Idope\": true,\n    \"IsoHunt2\": true,\n    \"LimeTorrents\": true,\n    \"TGx\": true\n  },\n  \"autodownload.multiSE.enabled\": false,\n  \"autodownload.period\": 21,\n  \"background-rotator.opacity\": 0.4,\n  \"biglybt.password\": \"*****\",\n  \"biglybt.path\": \"/transmission/rpc\",\n  \"biglybt.port\": 9091,\n  \"biglybt.progressX100\": true,\n  \"biglybt.server\": \"http://localhost\",\n  \"biglybt.use_auth\": true,\n  \"biglybt.username\": \"biglybt\",\n  \"calendar.mode\": \"date\",\n  \"calendar.show-downloaded\": true,\n  \"calendar.show-episode-numbers\": false,\n  \"calendar.show-specials\": true,\n  \"calendar.startSunday\": true,\n  \"client.determinedlocale\": \"en_us\",\n  \"deluge.password\": \"*****\",\n  \"deluge.port\": 8112,\n  \"deluge.server\": \"http://localhost\",\n  \"deluge.use_auth\": true,\n  \"download.ratings\": true,\n  \"episode.watched-downloaded.pairing\": true,\n  \"font.bebas.enabled\": true,\n  \"kc.always\": false,\n  \"ktorrent.password\": \"*****\",\n  \"ktorrent.port\": 8080,\n  \"ktorrent.server\": \"http://localhost\",\n  \"ktorrent.use_auth\": true,\n  \"ktorrent.username\": \"ktorrent\",\n  \"lastSync\": -1,\n  \"library.order.by\": \"getSortName()\",\n  \"library.order.reverseList\": [\n    true,\n    false,\n    true,\n    true\n  ],\n  \"library.seriesgrid\": true,\n  \"library.smallposters\": true,\n  \"main.viewmode\": \"calendar\",\n  \"notifications.enabled\": true,\n  \"qbittorrent.password\": \"*****\",\n  \"qbittorrent.port\": 8080,\n  \"qbittorrent.server\": \"http://localhost\",\n  \"qbittorrent.use_auth\": true,\n  \"qbittorrent.username\": \"admin\",\n  \"qbittorrent32plus.password\": \"*****\",\n  \"qbittorrent32plus.port\": 8080,\n  \"qbittorrent32plus.server\": \"http://localhost\",\n  \"qbittorrent32plus.use_auth\": true,\n  \"qbittorrent32plus.username\": \"admin\",\n  \"rtorrent.path\": \"/RPC2\",\n  \"rtorrent.port\": 80,\n  \"rtorrent.server\": \"http://localhost\",\n  \"rtorrent.use_auth\": false,\n  \"series.displaymode\": \"poster\",\n  \"series.not-watched-eps-btn\": false,\n  \"storage.sync\": false,\n  \"subtitles.languages\": [\n    \"eng\"\n  ],\n  \"sync.progress\": true,\n  \"synology.enabled\": false,\n  \"synology.ip\": \"192.168.x.x\",\n  \"synology.password\": \"*****\",\n  \"synology.playback_devices\": {},\n  \"synology.port\": 5000,\n  \"synology.protocol\": \"http\",\n  \"synology.username\": \"admin\",\n  \"tixati.password\": \"*****\",\n  \"tixati.port\": 8888,\n  \"tixati.server\": \"http://localhost\",\n  \"tixati.use_auth\": true,\n  \"tixati.username\": \"admin\",\n  \"topSites.enabled\": false,\n  \"topSites.mode\": \"onhover\",\n  \"torrentDialog.2.activeSE\": {\n    \"ThePirateBay\": true,\n    \"1337x\": true,\n    \"IsoHunt\": true,\n    \"KATcr\": true,\n    \"Nyaa\": true,\n    \"RarBG\": true,\n    \"ShowRSS\": true,\n    \"TorrentDownloads\": true,\n    \"TorrentZ2\": true,\n    \"Zooqle\": true\n  },\n  \"torrentDialog.2.enabled\": false,\n  \"torrentDialog.2.sortBy\": \"+engine\",\n  \"torrentDialog.showAdvanced.enabled\": true,\n  \"torrenting.autodownload\": true,\n  \"torrenting.autostop\": true,\n  \"torrenting.autostop_all\": false,\n  \"torrenting.client\": \"Deluge\",\n  \"torrenting.directory\": true,\n  \"torrenting.enabled\": true,\n  \"torrenting.global_size_max\": null,\n  \"torrenting.global_size_max_enabled\": true,\n  \"torrenting.global_size_min\": null,\n  \"torrenting.global_size_min_enabled\": true,\n  \"torrenting.ignore_keywords\": \"\",\n  \"torrenting.ignore_keywords_enabled\": true,\n  \"torrenting.label\": false,\n  \"torrenting.launch_via_chromium\": false,\n  \"torrenting.min_seeders\": 50,\n  \"torrenting.min_seeders_enabled\": false,\n  \"torrenting.progress\": true,\n  \"torrenting.require_keywords\": \"\",\n  \"torrenting.require_keywords_enabled\": true,\n  \"torrenting.require_keywords_mode_or\": true,\n  \"torrenting.searchprovider\": \"RarBG\",\n  \"torrenting.searchquality\": \"\",\n  \"torrenting.searchqualitylist\": [\n    \"HDTV\",\n    \"720p\",\n    \"1080p\",\n    \"2160p\",\n    \"x265\"\n  ],\n  \"torrenting.streaming\": true,\n  \"trakt-update.period\": 12,\n  \"trakttv.passwordHash\": \"*****\",\n  \"trakttv.sync\": false,\n  \"trakttv.username\": null,\n  \"transmission.password\": \"*****\",\n  \"transmission.path\": \"/transmission/rpc\",\n  \"transmission.port\": 9091,\n  \"transmission.progressX100\": true,\n  \"transmission.server\": \"http://localhost\",\n  \"transmission.use_auth\": true,\n  \"transmission.username\": \"admin\",\n  \"ttorrent.password\": \"*****\",\n  \"ttorrent.port\": 1080,\n  \"ttorrent.server\": \"http://localhost\",\n  \"ttorrent.use_auth\": true,\n  \"ttorrent.username\": \"admin\",\n  \"utorrentwebui.password\": \"*****\",\n  \"utorrentwebui.port\": 8080,\n  \"utorrentwebui.server\": \"http://localhost\",\n  \"utorrentwebui.use_auth\": true,\n  \"utorrentwebui.username\": \"admin\",\n  \"vuze.password\": \"*****\",\n  \"vuze.path\": \"/transmission/rpc\",\n  \"vuze.port\": 9091,\n  \"vuze.progressX100\": true,\n  \"vuze.server\": \"http://localhost\",\n  \"vuze.use_auth\": true,\n  \"vuze.username\": \"vuze\",\n  \"autodownload.lastrun\": 1593457339773\n}"
  },
  {
    "name": "Other significant Local Storage keys",
    "data": "{\n  \"1.1.4TorrentHashListCleanup\": \"Tue Jun 30 2020 10:54:24 GMT-0400 (EDT)\",\n  \"1.1.4cleanupOrphanedEpisodes\": \"Tue Jun 30 2020 10:54:22 GMT-0400 (EDT)\",\n  \"1.1.4cleanupOrphanedSeasons\": \"Tue Jun 30 2020 10:54:23 GMT-0400 (EDT)\",\n  \"1.1.4qBittorrentPre32\": \"Tue Jun 30 2020 10:54:18 GMT-0400 (EDT)\",\n  \"1.1.4refresh\": \"Tue Jun 30 2020 10:54:28 GMT-0400 (EDT)\",\n  \"1.1.4refreshTrendingCache\": \"Tue Jun 30 2020 10:54:18 GMT-0400 (EDT)\",\n  \"1.1.4updateTransmissionPath\": \"Tue Jun 30 2020 10:54:18 GMT-0400 (EDT)\",\n  \"1.1.5FetchFirstXemAliasMap\": \"Fri Jan 10 2020 17:54:29 GMT-0500 (Eastern Standard Time)\",\n  \"1.1.5deleteSearchEngines\": \"Tue Jun 30 2020 10:54:18 GMT-0400 (EDT)\",\n  \"1.1.5fanartCleanup\": \"Tue Jun 30 2020 10:54:48 GMT-0400 (EDT)\",\n  \"1.1.5updateDelugeAuth\": \"Tue Jun 30 2020 10:54:18 GMT-0400 (EDT)\",\n  \"1.1.5updateTorrenting.min_seeders\": \"Tue Jun 30 2020 10:54:18 GMT-0400 (EDT)\",\n  \"1.1.6deleteWatchList\": \"Fri Jan 10 2020 17:54:29 GMT-0500 (Eastern Standard Time)\",\n  \"1.1.6updateQualityList\": \"Fri Jan 10 2020 17:54:29 GMT-0500 (Eastern Standard Time)\",\n  \"1.1migration\": \"Tue Jun 30 2020 10:54:21 GMT-0400 (EDT)\",\n  \"autobackup.lastrun\": \"1593543739000\",\n  \"database.version.Jackett\": \"2\",\n  \"database.version.Seasons\": \"6\",\n  \"database.version.WatchList\": \"1\",\n  \"database.version.WatchListObject\": \"1\",\n  \"fanart.bootstrapped\": \"1\",\n  \"github.lastupdatecheck\": \"1578696872092\",\n  \"install.notify\": \"202001020130\",\n  \"optin_error_reporting\": \"true\",\n  \"optin_error_reporting.start_time\": \"1593530504757\",\n  \"runtime.event\": \"{\\\"reason\\\":\\\"install\\\"}\",\n  \"snr.lastFetched\": \"1593457385966\",\n  \"standalone.position\": \"{\\\"width\\\":1920,\\\"height\\\":1000,\\\"x\\\":0,\\\"y\\\":31,\\\"state\\\":\\\"normal\\\"}\",\n  \"standalone.zoomlevel\": \"6\",\n  \"torrenting.client\": \"Deluge\",\n  \"trackers.lastFetched\": \"1593457386923\",\n  \"trakttv.lastupdated\": \"1593525521356\",\n  \"trakttv.lastupdated.trending\": \"0\",\n  \"uniqueId\": \"a2f2a4ad-194e-e28e-599f-7efef757f63e\",\n  \"upgrade.notify\": \"1.1.5\",\n  \"xem.lastFetched\": \"1593457386700\"\n}"
  },
  {
    "name": "DB Series",
    "data": 0
  },
  {
    "name": "DB Series Hidden From Calendar",
    "data": 0
  },
  {
    "name": "DB Seasons",
    "data": 0
  },
  {
    "name": "DB Episodes",
    "data": 0
  },
  {
    "name": "DB Fanart",
    "data": 2584
  },
  {
    "name": "DB Jackett",
    "data": 0
  }
]

Unique tracking id: a2f2a4ad-194e-e28e-599f-7efef757f63e

![DuckieTV](https://user-images.githubusercontent.com/67646883/86145065-7b1bd780-bac4-11ea-97d4-1bbbe6ea022c.png)
![DuckieTV1](https://user-images.githubusercontent.com/67646883/86145082-7e16c800-bac4-11ea-95dc-f72a5de65e59.png)
![DuckieTV2](https://user-images.githubusercontent.com/67646883/86145180-9dadf080-bac4-11ea-8047-201d50e46bc5.png)

**Comment by ilike2burnthing** [comment]
Update to the 1.1.6 nightlies, as 1.1.5 is massively out of date - https://github.com/DuckieTV/Nightlies/releases

**Comment by jfmoly** [comment]
That worked.  Thank you!
