### ISSUE TITLE
Searching for American Dad Season 17 episodes result in Season 16 episodes

### ISSUE THREAD

**Issue by ggervais5** [SchizoDuckie/DuckieTV#1266]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
V202001290130

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 10

**Describe the problem you are having and steps to reproduce if available**
Go to American Dad, Season 17.  Click on Find Torrent.  Season 16 episodes appear

**Attach any DuckieTV statistics or Developer Console logs if available**
Screen shot:
![image](https://user-images.githubusercontent.com/47781789/86593738-65daf900-bf5b-11ea-9e88-3583344cefa0.png)

**Comment by garfield69** [comment]
American Dad season and episodes naming is a mess.
There is a huge discrepancy between the TVDB/Trakt.tv series list and the corresponding torrent scene torrent names for this series.
Dtv uses TheXem.de http://thexem.de/xem/show/4917 to attempt to keep up to date with the season episode tree, but obviously, that is only as good as the volunteers on theXem are at maintaining their conversion table for this series.

In any case there is little else that Dtv can do about it.

Usually the table is fairly up to date, but if you feel it is falling behind or out of date then consider joining  #xem on irc.freenode.net and see if you can get someone to correct it.

**Comment by ggervais5** [comment]
Thanks, I thought maybe an internal table was corrupted.  I guess not.
