### ISSUE TITLE
DTV not sending torrent to qBittorrent

### ISSUE THREAD

**Issue by AlienProber** [SchizoDuckie/DuckieTV#1267]
This morning I went to download Good Witch and Stargirl and DVT never sent the link to qbittorrent no matter what I tried. Last night I did what I normally do and downloaded Snowpiercer without any issue.

Steps taken:
Opened Vivaldi
Went to DTV's tab
Clicked the qb button on the leftside of DTV
Clicked qBittorrent 3.2+ Settings
Clicked Test And Save twice
Clicked a blank area in the calendar window to get rid of the settings page
Clicked on Stargirl
Clicked on find a torrent, waited 20 seconds and selected one for download
Got the notification from the Plasma desktop that it had been added to QBT but no spinning horseshoe on DTV
Check QBT and no torrent added
Did all of the above for Good Witch as well and got the same

Manjaro KDE 20.0.3 testing build
OBT 4.2.5 64 bit
DTV  hand loaded by me from the 3020.7.3.91 nightly posted on github

```
{
	"manifest_version": 2,
	"name": "__MSG_appNameBrowserAction__",
	"short_name": "__MSG_appShortNameBrowserAction__",
	"description": "__MSG_appDescBrowserAction__",
	"default_locale": "en",
	"version": "3020.7.3.91",
	"offline_enabled": true,
	"permissions": [
		"http://*/*",
		"https://*/*",
		"tabs",
		"topSites",
		"notifications",
		"unlimitedStorage"
	],
	"optional_permissions": [
		"storage",
		"cookies",
		"http://*/",
		"https://*/"
	],
	"background": {
		"scripts": [
			"dist/CRUD.js",
			"dist/CRUD.SqliteAdapter.js",
			"dist/CRUD.entities.js",
			"dist/CRUD.background.bootstrap.js",
			"dist/background.js",
			"dist/launch.js"
		],
		"persistent": false
	},
	"content_security_policy": "script-src 'self' https://api.loggr.net https://post.loggr.net 'unsafe-eval' http://localhost:10000 http://localhost:10015 http://localhost:10078 http://localhost:10231 http://localhost:10516 http://localhost:10975 http://localhost:11650 http://localhost:12583 http://localhost:13816 http://localhost:15391 http://localhost:17350 http://localhost:19735 http://localhost:22588 http://localhost:25951 http://localhost:29866 http://localhost:34375 http://localhost:39520 http://localhost:45343 http://localhost:51886 http://localhost:59191; object-src 'self';",
	"icons": {
		"16": "img/logo/icon16.png",
		"32": "img/logo/icon32.png",
		"48": "img/logo/icon48.png",
		"128": "img/logo/icon128.png",
		"256": "img/logo/icon256.png"
	},
	"browser_action": {
		"default_title": "",
		"default_icon": "img/logo/icon48.png"
	},
	"homepage_url": "http://duckie.tv/"
}
```

**Comment by garfield69** [comment]
which Dtv search engine are you using? have you tried temporarily switching to another SE to see if that makes a difference?

**Comment by AlienProber** [comment]
I have it set to check all of them. Thing is even when I forget to follow the steps above I always get the horseshoe for downloads, but it doesn't start spinning. Now I don't even get the horseshoe. My roommates machine is pretty close in setup to mine and he got the below. The location for the downloads has no issues what so ever. All downloads torrent or otherwise go to that folder and no other apps is saying that partition has issues. I would say it's updates pushed by Manjaro but the last updates were on the 4th and as I said I downloaded snowpiercer without any issue last night.

```
Failed to load the torrent: magnet:?xt=urn:btih:6054b23c694cc57197300fdcb503286fe4258bf&tr=udp://tracker.coppersurfer.tk:6969/announce&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://tracker.internetwarriors.net:1337/announce&tr=udp://p4p.arenabg.com:1337/announce&tr=udp://9.rarbg.to:2710/announce&tr=udp://9.rarbg.me:2710/announce&tr=udp://exodus.desync.com:6969/announce&tr=udp://tracker.cyberia.is:6969/announce&tr=udp://open.stealth.si:80/announce&tr=udp://tracker.tiny-vps.com:6969/announce&tr=udp://retracker.lanta-net.ru:2710/announce&tr=udp://tracker.torrent.eu.org:451/announce&tr=udp://tracker.moeking.me:6969/announce&tr=http://tracker4.itzmx.com:2710/announce&tr=udp://tracker3.itzmx.com:6961/announce&tr=http://tracker1.itzmx.com:8080/announce&tr=udp://ipv4.tracker.harry.lu:80/announce&tr=udp://zephir.monocul.us:6969/announce&tr=udp://valakas.rollo.dnsabr.com:2710/announce.
Error: No such file or directory
```

**Comment by garfield69** [comment]
There is something wrong with that magnet URI you just posted.
My uTorrent does not like it.
Which explains why qBt also rejected it.
Looking closer at the magnet hashkey, `6054b23c694cc57197300fdcb503286fe4258bf` is 39 characters... it should be 40! 
So where ever you got that magnet from, it appears to be generating invalid magnets.

**Comment by AlienProber** [comment]
Let me try one more thing and that is to download the version from the chrome web store, and my last backup, and see if I get the same issue.

**Comment by AlienProber** [comment]
OK installed the one version, added my backup, and it won't even connect to QBT. Just got the below when I tried to test in Vivaldi-Snapshot.

https://i.imgur.com/MGk0vHI.png

**Comment by garfield69** [comment]
the problems you are having appears to me external to Dtv.
tell me the series and episode and any quality or other search parms you are using, and which Dtv search engine you selected when you clicked on the download magnet button, and I will check on mine to see if I can replicate your issue on my dev platform.

BTW that last issue you reported in not Dtv but a browser popup.

**Comment by AlienProber** [comment]
I know the second error I posted is from the browser, but I don't believe in coincidences. As for the file it was Sundays Stargirl and we tried half a dozen different ones of different sizes, different formats, different sites all behaved the same. Just tested the nightly stand alone and no issue what so ever. I ask that you please not suggest that I continue to use the stand alone, cause I do not have a VPN for the desktop just the browsers. I only downloaded the one Stargirl file as a test.

**Comment by AlienProber** [comment]
I made a video, maybe it'll help. As you can see on some I have the one dialog bow while on others I don't.

https://vimeo.com/436076560

**Comment by garfield69** [comment]
I have set up vivaldi on my win10 dev platform, and loaded the Dtv Nightly chrome extension v3020.7.6.91, connected it to qBt 4.2.5, searched stargirl s01e08, clicked on a magnet from SE 1337x, and Dtv fetched the magnet, passed it to qBt and qBT started downloading without problems.
![image](https://user-images.githubusercontent.com/6933240/86836646-e7fd2600-c0f1-11ea-8b12-cb3d0c613e43.png)

So the issue, what ever it is, is restricted to your particular setup. The problem, what ever it is, has nothing to do with the code on Dtv.

I am not sure how I can help with this one.
