### ISSUE TITLE
Transmission & Mac - unable to download magnet

### ISSUE THREAD

**Issue by x8machina8x** [SchizoDuckie/DuckieTV#1269]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
[edit]
~~Nightly DuckieTV-202007290130-OSX-x64~~
DuckieTV Standalone 1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
macOS 10.15.5 (Catalina) AND OS X Yosemite 10.10.5

**Describe the problem you are having and steps to reproduce if available**
I am using Transmission 3.00. When I press "Download Magnet"  through DuckieTV, I get a notification stating that download started on transmission but I do not see any torrent on transmission and it does not download anything.
First I've tried #1168 (https://github.com/SchizoDuckie/DuckieTV/issues/1168)
I followed your recommendation about the Nightly Release and Installing Jacket. I did both - issue still persist
When I tried to do F12 on DuckieTV, a blank window pop up with title as: chrome-devtools://devtools/bundled/inspector.html?remoteBase=https://chrome-devtools-frontend.appspot.com/serve_file/@c1cff1(longstrings)/&docSide=undocked.

Also, when I installed Jacket, I followed: https://github.com/SchizoDuckie/DuckieTV/wiki/Using-Jackett-with-DuckieTV.
When press Test on the DuckieTV's Jackett Search Engine it says: "Status: 405 Reason: Method Not Allowed". When I test it in the Jackett Dashboard is successful. When I search the TV Series using the Jackett method, it works too, but issue persist when I click "Download Magnet"

I thought this is a macOS Catalina 10.15.5 issue, but the exact same issue is happening on Yosemite too. 
Can you help me?

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
I've just completed testing Dtv Standalone Nightly with Transmission 3.00 on my Mojave image and successfully downloaded a magnet from the Dtv native SE  1337x without any problems.
So I know in principal this works, which means we are dealing with something specific to your setup.
Peculiar title on your devtools window, mine reads `DevTools - chome-extension://bagblfnohpiddokbpaacecffdboomafe/tab.html`

**Comment by garfield69** [comment]
can you access your Dtv standalone, and click on the (i) icon [near bottom left of main page] and scroll down to the **statistics** section and screen-capture the first 10 lines or so.
Thanks.

**Comment by garfield69** [comment]
Just finished setting up Jackett on my Mojave image, and added MagnetDL as a Jackett indexer to the Dtv Nightly Standalone, and successfully downloaded a magnet to Transmission.
Usually a `Status: 405 Reason: Method Not Allowed` during test is caused by having the incorrect Jackett API key being used.

**Comment by x8machina8x** [comment]
Hi garfield69, 
Thanks for looking into it.
Yeah, it's pretty weird, it used to work before (Mojave and before), then I got busy and never used it again and upgraded to Catalina. I thought it's a Catalina issue.
But then I tried in Mojave and then Yosemite, same issue. It's feels like: When I click the "Download magnet"/"Download .torrent" it's like not communicating with Transmission 3.0. Because we got the notification from DuckieTV on macOS notifications that's it's downloading with Transmission...but it isn't. Something is broken in between DuckieTV and Transmission on my machine.
Also, don't worry about the Jackett thing, I was just following your instruction on issue #1168 which I don't really need/want.

Here's the first 10 lines of the statistics...you also asked of it in screencapture. 
So I'm attaching the screenshot as 

Statistics
--
DuckieTV Web Based | 1.1.5
Current Date and Time | Sat, 01 Aug 2020 04:29:02 GMT
NWJS, Chromium | 0.25.0 , 61.0.3163.79
UserAgent | DuckieTV-Standalone v1.1.5 Macintosh; Intel Mac OS X 10_15_5
Platform, Vendor | MacIntel, Google Inc.
Screen (width x height) | 2560 x 1440
Default Search Engine | 1337x (Enabled)
Default Torrent Client | Transmission (Enabled and Connected to Host)
Auto Download Service | (Disabled)
Last checked TraktTV for DB updates on | Sat, 01 Aug 2020 04:28:40 GMT

![Screen Shot 2020-08-01 at 12 32 17 pm](https://user-images.githubusercontent.com/20927235/89094109-449ee880-d3f3-11ea-907a-4b27a0531567.png)

**Comment by x8machina8x** [comment]
And this is from the Mojave:

![Screen Shot 2020-08-01 at 12 38 15 pm](https://user-images.githubusercontent.com/20927235/89094235-5339cf80-d3f4-11ea-9bef-caa7de218fb2.png)

![Screen Shot 2020-08-01 at 12 38 45 pm](https://user-images.githubusercontent.com/20927235/89094237-57fe8380-d3f4-11ea-929b-9b4944352360.png)

**Comment by garfield69** [comment]
Ahh. I see the issue.
You are still running Dtv 1.1.5!
You have run into a MacOS issue where the Nightly installer silently fails to install when the DuckieTV app is still in the applications folder. Don't ask me why, I did not write the installer app.

So move the DuckieTV app in the applications folder to the trashbin, then run the Nightly installer again.

If you have successfully installed the Nightly, you should see in the **About** side panel the title  `DuckieTV v202007290130` instead of `DuckieTV v1.1.5`

Then test your Dtv Native 1337x Search  engine again (the one in Dtv 1.1.5 is out of date and uses the wrong download links).

Also, I do not recommend using the Jackett 1337x indexer with Dtv any longer. The web site is using randomly active click bait advertisements instead of .torrent downloads links, which make this unreliable.
The Native Dtv 1337x SE works good on the Nightly.

If you want a useful magnet Jackett indexer then set up magnetDL.

**Comment by garfield69** [comment]
now I understand why you got a blank screen when you used **F12** or **Cmd-Alt-I**
The Dtv 1.1.5 package does not come with the development tools pack, hence the blank screen.
The nightly does have the DevTools pack, so that should be working to view the console log.

**Comment by x8machina8x** [comment]
PERFECTION!

It works both on Catalina and Mojave.
So the issue was the DuckieTV v1.1.5 itself. Moving to DuckieTV-Standalone Nightly v202007290130 seems to have fixed it.
Thanks!
(Also the F12/devtools work too now)

> TL:DR for others:
> ISSUE: Transmission 3.0 and DuckieTV v1.1.5 isn't downloading the magnet/.torrent.

> RESOLUTION: 
> - Delete DuckieTV v1.1.5 from Applications folder. (important!)
> - Download the Nightly build from https://github.com/DuckieTV/Nightlies/releases
> - Install it. (if you still have the v1.1.5, the Nightly build will have a silent fail where it doesn't install the nightly build without error. That's why DELETE the v1.1.5 from the Applications folder BEFORE installing the nightly build.
> 

Thank you garfield69!

![Screen Shot 2020-08-01 at 1 57 41 pm](https://user-images.githubusercontent.com/20927235/89095308-3f479b00-d3ff-11ea-9584-09ec4767ad5b.png)
![Screen Shot 2020-08-01 at 1 54 26 pm](https://user-images.githubusercontent.com/20927235/89095309-44a4e580-d3ff-11ea-968a-c5e44aaf7bde.png)
