### ISSUE TITLE
Added Spitting Image and it's not listing on calendar nor opening episode list

### ISSUE THREAD

**Issue by AlienProber** [SchizoDuckie/DuckieTV#1275]
As the title says I added Spitting Image which aired on the 2nd and it's not listing on on the calendar, nor will the episode list for it open. If I select another show and click to open it's episode list it opens without issue.

DTV nightly browser action mode 3020.9.8.1321 in Vivaldi 3.3.2022.47

**Comment by garfield69** [comment]
answered in https://www.reddit.com/r/duckietv/comments/j51uc8/added_spitting_image_and_its_not_listing_on/
