### ISSUE TITLE
After reinstalling and re-syncing from Trakt, all my shows are duplicated in the calendar.

### ISSUE THREAD

**Issue by syphondog3** [SchizoDuckie/DuckieTV#1279]
How to fix this? Do I need to uninstall again and reinstall?

![image](https://user-images.githubusercontent.com/32645908/97807549-7b251300-1c2f-11eb-8067-383135484614.png)

**Comment by garfield69** [comment]
Its not possible for the DB to store duplicates, so just restart Dtv  to refresh the calendar. Close that tab and start a new Dtv.
Your calendar will look much better after that ;-)

**Comment by syphondog3** [comment]
Hi Garfield. 

Thanks for your response.

I tried your suggestion but it did not work. I use github across 3 Windows 10 PCs on Chrome. The one PC which has duplicates, it  has not gone away. The other two PCs were fine...

More suggestions?

**Comment by garfield69** [comment]
Really?
Makes no sense. You cannot be restarting the tab, is it some Chrome setting that resumes closed tabs or something?

Try this: 
- press **F12** to open the chrome _development tools_ page 
- and click on the **console** tab to access the log/command line.
- at the `>` prompt paste `window.location.reload()` and press enter.

Does the calendar look better now?

**Comment by syphondog3** [comment]
Did that, still looks the same. I can uninstall and reinstall. Looks like I should do that with the nightDTV version you mentioned in the other thread....

**Comment by syphondog3** [comment]
![image](https://user-images.githubusercontent.com/32645908/97835360-f9250080-1ca7-11eb-8d1e-0eef29fbd35f.png)

**Comment by garfield69** [comment]
I guess so. Maybe the Dtv 1.1.5 does not have the DB features I thought it had, that code is 3 years old and I've been maintaining the Nightly.
Use the Dtv > Settings > Backup to take a backup (it will only copy the series IDs and episode states, and use it to import when you have the nightly installed. The import will fetch the latest shows' episodes so it should give you a good result.

**Comment by syphondog3** [comment]
Just had time to do the install of: *.chrome-newtab.zip (newtab mode) from https://github.com/DuckieTV/Nightlies/releases

One thing is that I have to download/extract the zip to every local PC routinely, correct? Chrome doesn't sync the extension across all of the platforms.

Thank you Garfield! Happy Thanksgiving!

Raj
