### ISSUE TITLE
DuckieTV Nightly (2020-09) doesn't connect to qBittorrent 4.3.0.1

### ISSUE THREAD

**Issue by VulcanTourist** [SchizoDuckie/DuckieTV#1280]
**What build of DuckieTV are you using (Standalone / Chrome Extension (New Tab / Browser Action))**
(?)

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
v202009082200 (Nightly)

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 10 x64 v2004

**Describe the problem you are having and steps to reproduce if available**
DuckieTV does not connect to qBittorrent v4.3.0.1.  I can connect to it via Firefox with ease.  In fact I have not once ever succeeded in getting any version of DuckieTV to integrate with any version of qBittorrent that I have tried.

**Attach any DuckieTV statistics or Developer Console logs if available**
I would provide this, but I'm an idiot and don't know where/how to access it.

I would very much like to finally abandon uTorrent, so help would be welcomed.

**Comment by garfield69** [comment]
I have just completed testing Dtv Standalone Nightly 202009082200 with qBt 4.3.0.1 and I can connect, send magnets and so forth without issue.

I suggest you have a read of https://github.com/SchizoDuckie/DuckieTV/wiki/Setting-up-qBitTorrent-3.2-with-DuckieTV 
 (top to bottom) which should help you with your set up.

Report back success or failure, and if you have any problems let me know, and we will dig deeper with you to try figure out what's going on.

**Comment by VulcanTourist** [comment]
Garfield69: Yes, I was following that wiki guide and still got this
result.  At this point I need to understand precisely how it's failing so
that I can know or theorize what needs to be fixed.

**Comment by garfield69** [comment]
Ok. the most common cause of problems is that users do not wait long enough at the Dtv integration panel, to wait for the connection.
Dtv first tries to use the old API to determine the qBt version, so you always get a failure notice the first time.
then a little later it tries the new API and connects. This should happen within the first 30 seconds.
If after that it still does not connect, then you have an issue.
have you taken a look at the dtv log yet?

**Comment by VulcanTourist** [comment]
I just now went back to Settings to re-enter the details (because it
forgets them after a failure), only to find that it was already connected
and apparently had been since shortly after my last attempt!  I didn't know
it was a multi-stage process and so took the initial failure as being a
permanent one.  I somehow missed the very first bullet point under
Problems....

Thanks for your perseverance.

**Comment by garfield69** [comment]
no problem. glad its working.
