### ISSUE TITLE
New episodes of some existing shows are not showing on the calendar

### ISSUE THREAD

**Issue by Falgn0n** [SchizoDuckie/DuckieTV#1283]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Chrome Extension Browser Action (in *Chromium)

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
latest from chrome store

**What is your Operating System (Windows, Mac, Linux, Android)**
Linuxmint 19

**Describe the problem you are having and steps to reproduce if available**
New episodes of existing shows are not showing up.
Example: the first episode of a new season shows on the calendar, but no subsequent episodes are there. However, if I enter the showname + SxxExx into the torrent search, it is found and I can download it.
This is not all shows, only a few.

**Attach any DuckieTV statistics or Developer Console logs if available**
I don't know how to access console logs

I have flushed browser cache and local data and started with a new installation (but importing DTV backup - because wow, so many shows to have to re-enter manually otherwise).

This issue is present on 2 different computers (both using Chromium Browser action)

In the example below, I have already found and downloaded at least 3 additional episodes (through DTV), even though it thinks there are no more.

![2020-11-12_22-11](https://user-images.githubusercontent.com/15193343/98991136-17a2bb80-2534-11eb-84ac-b72100586240.png)
![2020-11-12_22-15](https://user-images.githubusercontent.com/15193343/98991506-95ff5d80-2534-11eb-9be8-df442cde979a.png)

**Comment by Falgn0n** [comment]
NOTE:
Same issue in the Standalone version (V1.1.5)

**Comment by garfield69** [comment]
Please access the Dtv About page and scroll down to the statistics section and screen capture that page of the first 10 rows
![image](https://user-images.githubusercontent.com/6933240/98994996-97ad3d80-2595-11eb-9c39-7d5abc821ab3.png)

So I can be sure exactly which version of the Dtv Chrome extension you are using
Thanks.

**Comment by Falgn0n** [comment]
Here it is:

![2020-11-12_23-07](https://user-images.githubusercontent.com/15193343/98996709-fb0a8180-253b-11eb-995a-e4900ef95899.png)

BY THE WAY
I went to Settings -> Backup -> Referesh all TV shows and now every upcoming episode shows *twice* on the calender
![2020-11-12_23-08](https://user-images.githubusercontent.com/15193343/98996788-21302180-253c-11eb-87a2-ed53777ffe5f.png)

Another thing that's worth noting, is that I started over with a brand new 'Standalone' installation, adding each (current) show one by one, and so far that is working properly - so it may just have been something that went screwy with an imported backup or something like that.

**Comment by garfield69** [comment]
OK. Thanks.

So, several things.
- Trakt.tv recently added rate limiting to their API which causes Dtv 1.1.5 to fail to fetch updates.
See ticket #1273 for progress on this.
- The Google Chrome Web store is not accepting code updates from the Dtv Buildbot.
See #1233 for progress on this
- The Dtv buildbot is not building updated packages
See #1248 for progress on this

For now, the best source of working Dtv is https://github.com/SchizoDuckie/DuckieTV/issues/1273#issuecomment-720350100

**Comment by garfield69** [comment]
Closing, presumed resolved. Can always re-open if OP reports issue unresolved.
