### ISSUE TITLE
Favorites are not refreshing

### ISSUE THREAD

**Issue by SolSol14** [SchizoDuckie/DuckieTV#1287]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standlone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
0.40.2 Nightly V20192310130 Windows NT 10.0; Win 64; x 64
Win 32, Google Inc

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows

**Describe the problem you are having and steps to reproduce if available**
Favorites are not refreshing.  I am manually doing it and then it is finding new episodes.

**Attach any DuckieTV statistics or Developer Console logs if available**
[
  {
    "name": "Current Date and Time",
    "data": "Sat, 05 Dec 2020 23:12:47 GMT"
  },
  {
    "name": "DuckieTV-Standalone",
    "data": "201912310130"
  },
  {
    "name": "NWJS, Chromium",
    "data": "0.40.2 , 76.0.3809.132"
  },
  {
    "name": "UserAgent",
    "data": "DuckieTV-Standalone  Nightly v201912310130 Windows NT 10.0; Win64; x64"
  },
  {
    "name": "Platform, Vendor",
    "data": "Win32, Google Inc."
  },
  {
    "name": "Screen (width x height)",
    "data": "1920 x 1080"
  },
  {
    "name": "Default Search Engine",
    "data": "1337x (Enabled)"
  },
  {
    "name": "Default Torrent Client",
    "data": "qBittorrent 3.2+ (Enabled but Not Connected to Host)"
  },
  {
    "name": "Auto Download Service",
    "data": "(Enabled but Inactive)"
  },
  {
    "name": "Last checked TraktTV for DB updates on",
    "data": "Sat, 05 Dec 2020 16:15:00 GMT"
  },
  {
    "name": "User Preferences on Local Storage",
    "data": "{\n  \"ThePirateBay.mirror\": \"https://thepiratebay.org\",\n  \"application.language\": \"en_us\",\n  \"application.locale\": \"en_us\",\n  \"autobackup.period\": \"never\",\n  \"autodownload.delay\": 15,\n  \"autodownload.multiSE\": {\n    \"ThePirateBay\": true,\n    \"1337x\": true,\n    \"IsoHunt\": true,\n    \"KATcr\": true,\n    \"Nyaa\": true,\n    \"RarBG\": true,\n    \"ShowRSS\": true,\n    \"TorrentDownloads\": true,\n    \"TorrentZ2\": true,\n    \"Zooqle\": true,\n    \"EzTV.ag\": true,\n    \"Idope\": true,\n    \"LimeTorrents\": true,\n    \"SkyTorrents\": true,\n    \"ETag\": true,\n    \"ETTV\": true,\n    \"EXT\": true,\n    \"IsoHunt2\": true,\n    \"TGx\": true\n  },\n  \"autodownload.multiSE.enabled\": false,\n  \"autodownload.period\": 21,\n  \"background-rotator.opacity\": \"0.4\",\n  \"calendar.mode\": \"date\",\n  \"calendar.show-downloaded\": true,\n  \"calendar.show-episode-numbers\": true,\n  \"calendar.show-specials\": true,\n  \"calendar.startSunday\": true,\n  \"client.determinedlocale\": \"en_us\",\n  \"download.ratings\": true,\n  \"episode.watched-downloaded.pairing\": true,\n  \"kc.always\": false,\n  \"lastSync\": -1,\n  \"library.order.by\": \"notWatchedCount\",\n  \"library.order.reverseList\": [\n    true,\n    false,\n    true,\n    false\n  ],\n  \"library.seriesgrid\": true,\n  \"library.smallposters\": true,\n  \"main.viewmode\": \"calendar\",\n  \"notifications.enabled\": true,\n  \"qbittorrent32plus.password\": \"*****\",\n  \"qbittorrent32plus.port\": 8080,\n  \"qbittorrent32plus.server\": \"http://localhost\",\n  \"qbittorrent32plus.use_auth\": true,\n  \"qbittorrent32plus.username\": \"adminadmin\",\n  \"series.displaymode\": \"poster\",\n  \"series.not-watched-eps-btn\": true,\n  \"storage.sync\": false,\n  \"subtitles.languages\": [\n    \"eng\"\n  ],\n  \"sync.progress\": true,\n  \"synology.enabled\": true,\n  \"synology.ip\": \"192.168.x.x\",\n  \"synology.password\": \"*****\",\n  \"synology.playback_devices\": {},\n  \"synology.port\": 5000,\n  \"synology.protocol\": \"http\",\n  \"synology.username\": \"admin\",\n  \"topSites.enabled\": false,\n  \"topSites.mode\": \"onclick\",\n  \"torrentDialog.2.activeSE\": {\n    \"ThePirateBay\": true,\n    \"1337x\": true,\n    \"IsoHunt\": true,\n    \"KATcr\": true,\n    \"Nyaa\": true,\n    \"RarBG\": true,\n    \"ShowRSS\": true,\n    \"TorrentDownloads\": true,\n    \"TorrentZ2\": true,\n    \"Zooqle\": true,\n    \"EzTV.ag\": true,\n    \"Idope\": true,\n    \"LimeTorrents\": true,\n    \"SkyTorrents\": true,\n    \"ETag\": true,\n    \"ETTV\": true,\n    \"EXT\": true,\n    \"IsoHunt2\": true,\n    \"TGx\": true\n  },\n  \"torrentDialog.2.enabled\": true,\n  \"torrentDialog.2.sortBy\": \"-seedersInt\",\n  \"torrentDialog.showAdvanced.enabled\": true,\n  \"torrenting.autodownload\": true,\n  \"torrenting.autostop\": true,\n  \"torrenting.autostop_all\": false,\n  \"torrenting.client\": \"qBittorrent 3.2+\",\n  \"torrenting.directory\": true,\n  \"torrenting.enabled\": true,\n  \"torrenting.global_size_max\": null,\n  \"torrenting.global_size_max_enabled\": false,\n  \"torrenting.global_size_min\": null,\n  \"torrenting.global_size_min_enabled\": true,\n  \"torrenting.ignore_keywords\": \"Celebrity\",\n  \"torrenting.ignore_keywords_enabled\": false,\n  \"torrenting.label\": false,\n  \"torrenting.launch_via_chromium\": false,\n  \"torrenting.min_seeders\": 2,\n  \"torrenting.min_seeders_enabled\": false,\n  \"torrenting.progress\": true,\n  \"torrenting.require_keywords\": \"\",\n  \"torrenting.require_keywords_enabled\": true,\n  \"torrenting.require_keywords_mode_or\": true,\n  \"torrenting.searchprovider\": \"1337x\",\n  \"torrenting.searchquality\": \"\",\n  \"torrenting.searchqualitylist\": [\n    \"HDTV\",\n    \"720p\",\n    \"1080p\",\n    \"2160p\",\n    \"x265\"\n  ],\n  \"torrenting.streaming\": true,\n  \"trakt-update.period\": 12,\n  \"trakttv.passwordHash\": \"*****\",\n  \"trakttv.sync\": false,\n  \"trakttv.username\": null,\n  \"autodownload.lastrun\": 1607209461761,\n  \"font.bebas.enabled\": true\n}"
  },
  {
    "name": "Other significant Local Storage keys",
    "data": "{\n  \"standalone.position\": \"{\\\"width\\\":1922,\\\"height\\\":1052,\\\"x\\\":0,\\\"y\\\":0,\\\"state\\\":\\\"maximized\\\"}\",\n  \"1.1.4TorrentHashListCleanup\": \"Tue Nov 07 2017 18:43:37 GMT-0800 (Pacific Standard Time)\",\n  \"trakttv.lastupdated.trending\": \"1606666518892\",\n  \"1.1.4refreshTrendingCache\": \"Tue Nov 07 2017 18:43:31 GMT-0800 (Pacific Standard Time)\",\n  \"standalone.zoomlevel\": \"6\",\n  \"1.1.5updateDelugeAuth\": \"Tue Nov 07 2017 18:43:31 GMT-0800 (Pacific Standard Time)\",\n  \"1.1.5updateTorrenting.min_seeders\": \"Tue Nov 07 2017 18:43:31 GMT-0800 (Pacific Standard Time)\",\n  \"1.1.6updateQualityList\": \"Tue Dec 31 2019 15:45:01 GMT-0800 (Pacific Standard Time)\",\n  \"uniqueId\": \"85a051a4-89cb-0d48-226a-d7d0f663050a\",\n  \"database.version.Series\": \"16\",\n  \"1.1.4refresh\": \"Tue Nov 07 2017 18:43:41 GMT-0800 (Pacific Standard Time)\",\n  \"standalone.alwaysShowTray\": \"Y\",\n  \"trakttv.lastupdated\": \"1607184900125\",\n  \"database.version.Seasons\": \"6\",\n  \"database.version.WatchListObject\": \"1\",\n  \"runtime.event\": \"{\\\"reason\\\":\\\"install\\\"}\",\n  \"database.version.Episodes\": \"14\",\n  \"optin_error_reporting\": \"true\",\n  \"1.1.5deleteSearchEngines\": \"Tue Nov 07 2017 18:43:31 GMT-0800 (Pacific Standard Time)\",\n  \"fanart.bootstrapped\": \"1\",\n  \"standalone.trayColor\": \"-violet\",\n  \"database.version.Fanart\": \"1\",\n  \"install.notify\": \"1.1.5\",\n  \"1.1.4cleanupOrphanedEpisodes\": \"Tue Nov 07 2017 18:43:35 GMT-0800 (Pacific Standard Time)\",\n  \"optin_error_reporting.start_time\": \"1607209796696\",\n  \"upgrade.notify\": \"1.1.5\",\n  \"autobackup.lastrun\": \"1597594451797\",\n  \"database.version.WatchList\": \"1\",\n  \"1.1.4updateTransmissionPath\": \"Tue Nov 07 2017 18:43:31 GMT-0800 (Pacific Standard Time)\",\n  \"1.1.5FetchFirstXemAliasMap\": \"Tue Nov 07 2017 18:43:31 GMT-0800 (Pacific Standard Time)\",\n  \"1.1.4qBittorrentPre32\": \"Tue Nov 07 2017 18:43:31 GMT-0800 (Pacific Standard Time)\",\n  \"xem.lastFetched\": \"1607202119326\",\n  \"database.version.Jackett\": \"2\",\n  \"snr.lastFetched\": \"1607202119343\",\n  \"1.1.5fanartCleanup\": \"Tue Nov 07 2017 18:44:01 GMT-0800 (Pacific Standard Time)\",\n  \"trackers.lastFetched\": \"1605427195687\",\n  \"standalone.startupMinimized\": \"N\",\n  \"1.1migration\": \"Tue Nov 07 2017 18:43:34 GMT-0800 (Pacific Standard Time)\",\n  \"1.1.6deleteWatchList\": \"Tue Dec 31 2019 15:45:01 GMT-0800 (Pacific Standard Time)\",\n  \"torrenting.client\": \"qBittorrent 3.2+\",\n  \"github.lastupdatecheck\": \"1510109013734\",\n  \"1.1.4cleanupOrphanedSeasons\": \"Tue Nov 07 2017 18:43:36 GMT-0800 (Pacific Standard Time)\"\n}"
  },
  {
    "name": "DB Series",
    "data": 138
  },
  {
    "name": "DB Series Hidden From Calendar",
    "data": 26
  },
  {
    "name": "DB Seasons",
    "data": 918
  },
  {
    "name": "DB Episodes",
    "data": 22058
  },
  {
    "name": "DB Fanart",
    "data": 4257
  },
  {
    "name": "DB Jackett",
    "data": 0
  }
]

**Comment by lgmorand** [comment]
the reason is here : https://github.com/SchizoDuckie/DuckieTV/issues/1273
the solution is to take a nightly which is not one year old :)

**Comment by garfield69** [comment]
Darn, did not get the email notice so missed spotting this. Sorry.
Presuming you have not given up on Dtv and if this is still a problem post here and I will re-open the ticket and provide more direct help.
But as lgmorand commented previously, fetch the latest Nightly from https://github.com/DuckieTV/Nightlies/releases/tag/nightly-202104302304 to get a version that is up to dat with the latest Trakt.tv API server changes for fetching updates.
