### ISSUE TITLE
After update, Blank calendar and backup import stay loading

### ISSUE THREAD

**Issue by fokeiro2020** [SchizoDuckie/DuckieTV#1289]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**

windows

**Describe the problem you are having and steps to reproduce if available**
had a popup to update so i did, after update calendar was blank. tried importing a backup and just stay at loading backup. Uninstalled and same issue. importing backup all shows a yellow square with white circle loading and doesn't go anywhere,

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
Nah, the popup is a symptom of your DuckieTV settings having been blown away and fooling Dtv into thinking an upgrade is required.

You may find this wiki useful: https://github.com/SchizoDuckie/DuckieTV/wiki/FAQ#i-cant-add-a-series-and-there-is-nothing-in-the-calendar

Once you have got everything working again, I recommend upgrading your 1.1.5 to the latest Nightly to take advantage of the improvements to the episode update process, which will help keep your calendar up to date with the new episodes.
Install the Standalone from https://github.com/DuckieTV/Nightlies/releases

Let me know how you go, or if you need additional help.

**Comment by fokeiro2020** [comment]
did update to newest version but when i import a backup just stay like this

https://gyazo.com/6c7161f50992f4bbe8d113aa13bd81fa
and wont import

now on the browser version imported without issues

**Comment by garfield69** [comment]
Let me understand this.
You started with a Standalone Dtv 1.1.5 which used to have series, but stopped working, with nothing in the calendar.
Then you followed the recovery wiki to get your settings working so that 1.1.5 could use the DB and show series again.
Then you upgraded by installing the Standalone Nightly, which goes straight over the top of the old standalone 1.1.5
At this point you should not need to import anything, it should all be there.
So did you deviate and do something else or what happened?

**Comment by garfield69** [comment]
Also, is the browser version a Nightly?

**Comment by fokeiro2020** [comment]
> Also, is the browser version a Nightly?

yes. im just going to wipe it again and retry it. will report back

**Comment by garfield69** [comment]
yeah, no.
try this. 
- delete the duckietv-standalone data folder,
- start it up and wait for the pre-init to complete, -
- add a single series just to check it is all good, then
- shut it down, and find the DB from your chrome nightly and copy that over to the standalone
- and start it up. This way you have a full DB at the same level as the chrome one and it all good to go.

**Comment by fokeiro2020** [comment]
same issue after fresh install and removed appdata folder

https://gyazo.com/be83f4c527f43ac21037e0aec4cad7ce

**Comment by pjhalsli** [comment]
> did update to newest version but when i import a backup just stay like this
> 
> [gyazo.com/6c7161f50992f4bbe8d113aa13bd81fa](https://gyazo.com/6c7161f50992f4bbe8d113aa13bd81fa)
> and wont import
> 
> now on the browser version imported without issues

been having the same problem since I installed the latest nightly - it's been trying to import the backup file for over 2 days now but nothing really happens - something is obv broken

**Comment by garfield69** [comment]
@pjhalsli  something may have blown away your Dtv settings and now Dtv does not know the structure of its DB.
what platform are you on (windows, mac or linux), and you are on Nightly Standalone?
need that info to tell you which folder to delete to fix...

**Comment by pjhalsli** [comment]
linux nightly standalone - can't even add new shows 

I tried to uninstall and reinstall several times. But as soon as I install it starts loading a backup file that I removed days ago.When I try to add a new show it doesn't work either

**Comment by garfield69** [comment]
@pjhalsli  
1. shutdown Dtv
2. delete the folder `~/.config/DuckieTV-Standalone`
3. start up Dtv
4. wait for the pre-init to complete then add a single show to prove it is working
5. import your Dtv backup
6. restart Dtv to load settings and you should be good to go

let me know how you go!

**Comment by pjhalsli** [comment]
You're the man!!!   Thank you so much. Was able to add a single show now - so will try to add the backup later as I removed it from the computer to gitlab

**Comment by pjhalsli** [comment]
one thing tho - the backup import still stay loading even tho there is no file to load from

**Comment by garfield69** [comment]
ignore it, its a false hit. It is really only loading when you give it a file to use.

**Comment by garfield69** [comment]
@Js41637  can you sort out the false loading tag being reported https://github.com/SchizoDuckie/DuckieTV/issues/1289#issuecomment-842692886 ?

**Comment by garfield69** [comment]
@Js41637 
![image](https://user-images.githubusercontent.com/6933240/118575971-ba860c00-b7db-11eb-8090-abc37d15ce2b.png)

**Comment by garfield69** [comment]
@Js41637  never mind, turned out to be simple fix. 82e5174
