### ISSUE TITLE
qBitTorrent - integration does not work if qBittorent is started after duckieTV

### ISSUE THREAD

**Issue by lgmorand** [SchizoDuckie/DuckieTV#1293]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Nighty 202011202304

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows up to date

**Describe the problem you are having and steps to reproduce if available**
After each computer wake up, duckieTv doesn't integrate anymore with qBittorent. when I **test** the integration in the settings, the call fails, even if in parallel through a browser I can access the WebUI of qBit.

I tried several steps
1- rebooting qBittorent only => KO
2- rebooting DuckieTV => OK, integration works fine
3- killing qBittorrent process => the integration screens says that integration is still OK while it shouldn't since the process doesn't exist anymore
4- starting qBittorent again => KO in duckieTV even if the WebUI works in a browser

it looks like there is some caching issue or something weird in the integration process. 
That's boring to have to kill and relaunchs duckietv everytime, especially after each wake up (not start, sleep). I cannot say I had the same issue with utorrent

and the weirdest part, duckieTV opens the notification to say that the torrent is sent to qBittorent, while it's not sent to it (or not received)

ps: when integration is fine, everything works perfectly.

**Comment by cajeiri** [comment]
Can confirm, using qBit 4.3.2 and DuckieTV v202011161248.

**Comment by garfield69** [comment]
From the beginning if Dtv's life, it has always been the case that Dtv needs to be started after the torrent client activates the port, and if the client goes down and up, Dtv is unable to re-establish the connection in most cases. 
Dtv was written in angularJS as a chrome browser extensions. As such, from the top down, its designed to be started and stopped as any other chrome browser tab page would typically do, and not really designed to run 24/7
The standalone version of Dtv is the exact same code, running under NWJS, a run time environment that provides a headless chromium browser internally, thus allowing the Dtv chrome extension to run as an executable app.
And given that no one is coding for this app anymore (other than urgent everything is broken events), there will not be any solutions forth coming for this topic.
