### ISSUE TITLE
Aria2 integration with aria2c 1.35 assumes download complete on Metadata download

### ISSUE THREAD

**Issue by manishbhatias** [SchizoDuckie/DuckieTV#1294]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Nightly 202102172304

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 10

**Describe the problem you are having and steps to reproduce if available**
Aria2 integration with aria2c 1.35 assumes download complete on Metadata download.

**Attach any DuckieTV statistics or Developer Console logs if available**
JSON RPC call from Aria2c 1.35 returns bitfield as 80 for metadata download completion. I see that in the codebase, we have a conditional check based on aria2c version > 1.32 for bitfield where the issue might be.
I think it could be better if we use `followedBy` field instead of relying on `bitfield`. The followedBy field will have list of GIDs which are generated as the result of the current download.

**Comment by garfield69** [comment]
Why did you close this ticket?

**Comment by manishbhatias** [comment]
@garfield69 I was not able to replicate this behaviour properly. It happens in some cases where I see DuckieTV showing download complete on metadata download but at other times it works.

**Comment by garfield69** [comment]
Please access the **About** page on your Dtv Nightly and report the version at the top of that page.

**Comment by garfield69** [comment]
I've been experimenting with aria2c 1.35 on windows, and I see that the metadata bit field can be either 80 or c0 so I will update the service to look for either so that dtv does not think the download is complete when the medatafile is downloaded.
