### ISSUE TITLE
1000 Series Limit

### ISSUE THREAD

**Issue by ianwday** [SchizoDuckie/DuckieTV#1295]
Is there a limit of number of series you can have in DuckieTV?  In my About DuckieTV v202101052304 section, it says DB Series 1245 but, whenever DuckieTV updates, the total number of shows it's updating is always 1000.  As a result, series that I've recently added are not on the calendar.  I can add the show as a favourite but when I close and re-open DuckieTV, it is gone.

**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Nightly 202101052304

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 10 20H2

**Describe the problem you are having and steps to reproduce if available**
see above

**Attach any DuckieTV statistics or Developer Console logs if available**
...

_Originally posted by @ianwday in https://github.com/SchizoDuckie/DuckieTV/issues/1273#issuecomment-757275349_

**Comment by ianwday** [comment]
![image](https://user-images.githubusercontent.com/59399078/104752877-3b959f80-5725-11eb-8c45-a38e44403743.png)
![image](https://user-images.githubusercontent.com/59399078/104752927-4a7c5200-5725-11eb-9e73-4a4718ed90f3.png)

Add The Serpent to favourites

![image](https://user-images.githubusercontent.com/59399078/104753021-6da70180-5725-11eb-8d65-00336f2326ff.png)
![image](https://user-images.githubusercontent.com/59399078/104753056-78fa2d00-5725-11eb-8f9b-5c50ebfc3beb.png)

Close and re-open DuckieTV and The Serpent is gone.

![image](https://user-images.githubusercontent.com/59399078/104753124-90391a80-5725-11eb-8ee5-8c7cda2ac186.png)

...and the number of shows is back to 1000.

![image](https://user-images.githubusercontent.com/59399078/104753192-a5ae4480-5725-11eb-8342-9de1657cb24a.png)

![image](https://user-images.githubusercontent.com/59399078/104753221-ae9f1600-5725-11eb-8815-a25e47479a03.png)

**Comment by garfield69** [comment]
@Js41637  is the Trakt.tv api restricting your shows update process to a total of 1000 shows? 10 pages of 100 items?
Or is something else at play here? Thanks.

**Comment by Js41637** [comment]
Where even is that `Loading, please wait` screen? That has nothing to do with the trakt.tv updater, i assume there some internal limit on the size of the SQL selects that caps at 1000 somewhere. All the updater does is get all shows and update them all individually and I just reuse existing methods to get all shows, so there must be something limiting it somewhere.

Also it's likely you won't even be able to update 1000 shows at once due to API rate limits but that's a different issue.

**Comment by garfield69** [comment]
found this limit in the adapter, L411
[edit] removed pasted text error 
https://github.com/SchizoDuckie/DuckieTV/blob/d1feb54418b395a28fea91edf505215aab032f26/js/vendor/CRUD.SqliteAdapter.js#L378-L416

I suppose we could bump it up to 2000 and see if that makes a difference to the user?

**Comment by ianwday** [comment]
> Where even is that `Loading, please wait` screen? That has nothing to do with the trakt.tv updater, i assume there some internal limit on the size of the SQL selects that caps at 1000 somewhere. All the updater does is get all shows and update them all individually and I just reuse existing methods to get all shows, so there must be something limiting it somewhere.
> 
> Also it's likely you won't even be able to update 1000 shows at once due to API rate limits but that's a different issue.

The "Loading, please wait" screen is when you Backup - Refresh all series now, which is the recommended solution to the problems with the trakt.tv API limits.

What I've ended up doing because I hadn't heard anything was to just reduce my number of shows in trakt.tv by deleting the watched and collected information and then removing the corresponding favourites in DTV.

**Comment by garfield69** [comment]
>The "Loading, please wait" screen is when you Backup - Refresh all series now, which is the recommended solution to the problems with the trakt.tv API limits.

This has not been required since after 16th Nov 2020 approx. As long as you are on a Nightly newer that 20201116xxxx you should not need to use the global refresh to get updates for all shows.

I've bumped the global default limit for SQLite queries from 1000 to 2000, so the next nightly should start to allow fetching of more shows.
