### ISSUE TITLE
Links from 1337x don't work

### ISSUE THREAD

**Issue by mybadstudios** [SchizoDuckie/DuckieTV#1297]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 10

**Describe the problem you are having and steps to reproduce if available**
Sometimes something doesn't appear to be found on EZTV (which is set as my default). If I then click on that item and select 'Find a torrent' and actually DO find a torrent on the other sites then non of the three download links on 1337x do anything. Click them a few dozen times each and .... nothing. 

Don't change the search but click on another site, wait for the torrent to show up, click the magnet or the download icons and it works just fine. This issue only seems to happen when trying to download from 1337x and ONLY if my default search failed to find a torrent. 

If I find the current torrent is 2Gb+ in size, ignoring my max file size limit of 650Mb) and I stop the torrent, click on 'Find a torrent' and do a search on 1337x, downloading from the site works perfectly.

**Comment by ilike2burnthing** [comment]
For this and #1296 switch to the nightly builds, 1.1.5 is years out of date - https://github.com/DuckieTV/Nightlies/releases
