### ISSUE TITLE
I need help please. my previous version of DuckieTV started giving me hassels so I downloaded version V1.1.2. now everything is buggered. It doesn't show all the new episodes that was released and also doesnt show the episode numbers and for some reason it doesn't want to link to my Utorrent. Is there another version that works? I love my DuckieTV (if it works correctly). Please assist.  ;-(

### ISSUE THREAD

**Issue by CC7785415** [SchizoDuckie/DuckieTV#1298]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...

**What is your Operating System (Windows, Mac, Linux, Android)**
...

**Describe the problem you are having and steps to reproduce if available**
...

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
Please fill in the blanks below
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
1.1.2
**What is your Operating System (Windows, Mac, Linux, Android)**

**Comment by CC7785415** [comment]
See below answers  :-) thank youSent from my Galaxy
-------- Original message --------From: garfield69 <notifications@github.com> Date: 2021/02/01  8:26 pm  (GMT+02:00) To: SchizoDuckie/DuckieTV <DuckieTV@noreply.github.com> Cc: CC7785415 <c.j.ceronio@gmail.com>, Author <author@noreply.github.com> Subject: Re: [SchizoDuckie/DuckieTV] I need help please. my previous version of DuckieTV started giving me hassels so I downloaded version V1.1.2. now everything is buggered. It doesn't show all the new episodes that was released and also doesnt show the episode numbers and for some reason it doesn't want to link to my Utorrent. Is there another version that works? I love my DuckieTV (if it works correctly). Please assist.  ;-( (#1298) 
Please fill in the blanks below
What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action)) - not sure, I suspect standlone. App downloaded for desktop. Where do I check?
What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)
1.1.2- 1.1.2
What is your Operating System (Windows, Mac, Linux, Android)- Windows

**Comment by garfield69** [comment]
So the Dtv database (DB) is specific to each version, with each newer version able to update the database to bring it up to the newer version's requirements. But it not backward compatible, so for instance, you cannot use a DB from 1.1.5 with a version of 1.1.2 Dtv, as 1.1.2 does not know how to handle a 1.1.5 DB.

The first thing you can try is upgrading to the latest Dtv from https://github.com/DuckieTV/Nightlies/releases
and install this right over the top of the old one.

However, if the Dtv Nightly refuses to use the existing DB (you will see a empty calendar and loading shows returns spinning wheels that never resolve), then its likely that the DB and settings are broken (1.1.2 or some other event may have clobbered the data folder).
In which case you will need to delete the data folder so you can start from scratch.
So if you need to do that then 
1. shutdown Dtv
2. locate `C:\Users\<username>\AppData\Local\DuckieTV-Standalone` and rename or delete
3. startup Dtv
4. wait for the pre-init to complete and add a show.

Good luck.

**Comment by CC7785415** [comment]
Thank you, I'll definitely try that And thanx a million, great program :-)Sent from my Galaxy
-------- Original message --------From: garfield69 <notifications@github.com> Date: 2021/02/01  9:05 pm  (GMT+02:00) To: SchizoDuckie/DuckieTV <DuckieTV@noreply.github.com> Cc: CC7785415 <c.j.ceronio@gmail.com>, Author <author@noreply.github.com> Subject: Re: [SchizoDuckie/DuckieTV] I need help please. my previous version of DuckieTV started giving me hassels so I downloaded version V1.1.2. now everything is buggered. It doesn't show all the new episodes that was released and also doesnt show the episode numbers and for some reason it doesn't want to link to my Utorrent. Is there another version that works? I love my DuckieTV (if it works correctly). Please assist.  ;-( (#1298) 
So the Dtv database (DB) is specific to each version, with each newer version able to update the database to bring it up to the newer version's requirements. But it not backward compatible, so for instance, you cannot use a DB from 1.1.5 with a version of 1.1.2 Dtv, as 1.1.2 does not know how to handle a 1.1.5 DB.
The first thing you can try is upgrading to the latest Dtv from https://github.com/DuckieTV/Nightlies/releases
and install this right over the top of the old one.
However, if the Dtv Nightly refuses to use the existing DB (you will see a empty calendar and loading shows returns spinning wheels that never resolve), then its likely that the DB and settings are broken (1.1.2 or some other event may have clobbered the data folder).
In which case you will need to delete the data folder so you can start from scratch.
So if you need to do that then

shutdown Dtv
locate C:\Users\<username>\AppData\Local\DuckieTV-Standalone and rename or delete
startup Dtv
wait for the pre-init to complete and add a show.

Good luck.
