### ISSUE TITLE
Remove TVDBID dependency from Dtv due to Trakt.tv switching to TMDB for primary data source.

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#1299]
Currently, Dtv still has a heavy dependency on using the TVDBID to track episodes, especially with the Dtv.Backup which uses the TVDBID to track the episode downloaded/watched states during backup/restore,
and the favoritesService which drops any episode records from being stored in the Database if those records do not have a TVDBID.

Now that Trakt.tv have announced that they are switching to using TMDB as their primary data source, more and more records from the Trakt.tv API servers are being returned without a TVDBID.

Some shows already contain a partial mixture of episode records that don't have a TVDBID, such as Mr Mayor, a single season show, where the first four episodes have a TVDBID, but the next three (and presumably the rest when they are broadcast) do not have a TVDBID in the episode record.
This means that Dtv is only storing the first four episodes of this series!

**Comment by garfield69** [comment]
The more I dig into this the more my head hurts. Preliminary thoughts, in an attempt to lay out the issues:
1. fix Dtv so it can handle episodes that do not have a tvdb_id
ok. first thing is to identify where in the favoriteServices is the code that prevents saving an episode if there is no tvdb_id, and remove it so that the record can be saved in CRUD.
Next, identify the ramifications of saving CRUD episode records without a tvdb_id (from a Dtv perspective), which is to say, list all the routines that will break in Dtv when the tvdb_id is missing in an episode CRUD record.
2. Switch to using TRAKT_ID for all internal Dtv processes
This will be a headache. Dtv uses tvdb_id internally to track the state of many processes throughout the code, including things like spinning process wheels, fanart, torrent dialogues, sceneNameExceptions, just about everything.
3. Add TRAKT_ID to the Dtv backup, and somehow recognise which version of the backup we are dealing with (the old one using TVDB_ID) or the new one with TRAKT_ID, as ideally we want to keep backward compatibility if possible.

there is probably more.

**Comment by garfield69** [comment]
note: when Trakt drops the tvdb_id from their series records (possibly as early as March 2021) then Dtv will no longer be able to use FanArt for fetching images (which use the same tvdb_id for their series poster tagging), unless we find some way to provide a cross-reference of tvdb_id with trakt_id, or something.

**Comment by garfield69** [comment]
note: same applies for theXem.de lookups, as the site uses the tvdbid for its scene episodes cross reference, and does not have a traktid service.

**Comment by SchizoDuckie** [comment]
Ugh. what a massive P.I.T.A. this.
How will we cope with the XEM data not being mappable? That will introduce a lot of headaches

**Comment by garfield69** [comment]
>How will we cope with the XEM data not being mappable? That will introduce a lot of headaches

I'm open to suggestions, but for now, in a better than nothing plan, in the event that in March Trakt.tv removes the tvdbid's from their serie records, (which as of this post all the trakt shows still have a tvdbid data point), and presuming that we can't find any API or web service that will provide a traktid-to-tvdbid show-cross-reference, I've already prepared my own table and routine to provide the needed xref, which should tie us over until a better solution becomes available.

Of course the down side of this custom table will be the need to maintain it manually, the frequency of which will depend on just how often trakt.tv adds new shows.

**Comment by flydoggy** [comment]
Ran series refresh using 0221 nightly.  Update went well, but stopped at series 575 of 684.  Found several missing shows.  Progress.

**Comment by garfield69** [comment]
@flydoggy  raise a new problem ticket if you want help investigating what you reported. this ticket is not for use in following refresh/update problems. Thanks.

**Comment by garfield69** [comment]
Well its mid April and its clear that while Trakt.tv is now using TMDB as the primary source of data for their own DB, they are continuing to provide the tvdb_id in serie title records, as shown by examining new series that are being added.
I've completed switching Dtv over to using the trakt_id as the primary key so I'm closing this ticket.
