### ISSUE TITLE
Dtv Nightly not being generated, the BuildBot server needs attention again

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#1301]
@SchizoDuckie  the BuildBot server has not generated a DuckieTV Nightly build for 9 days now.
Can you please investigate and correct the issue?
I've got a Fix for Dtv #1299 which I would like to publish.
Thanks.

**Comment by SchizoDuckie** [comment]
Looks like this time nsjs.io upgraded some SSL stuff and curl is no longer downloading the upgraded nwjs distro.

Receiving several errors like `curl: (18) transfer closed with 60138176 bytes remaining to read` and `curl: (56) GnuTLS recv error (-9): A TLS packet with unexpected length was received.`

I'll attempt to dist-upgrade the box from xenial to something newer. Cross your fingers.

**Comment by jagre77** [comment]
So if you had to grade this situation somewhere on a scale between "It's not a big deal; it'll be fixed soon." and "Doom!  DuckieTV is over forever!" how would you score it?  ;)

Just checking in, no pressure.  It's a bummer that garfield has a fix for the problem plaguing DTV right now but we can't access it.  Any news is appreciated.  Thanks!

**Comment by garfield69** [comment]
While SchizoDuckie works on the server, I have managed (just before this post) to upload a personal build of the latest Nightly which I hope will provide the fixes to get users going again (tested on my Win10 and Ubuntu18).

**Comment by jagre77** [comment]
Win10x64 here and it seems to be working perfectly.  "Refresh all series" caught everything that was missing on my calendar (even a couple that I didn't realize had been missing).  Thanks much for the update!

**Comment by cajeiri** [comment]
Win7 64bit - refreshing all series fixed the issues on my side too!

**Comment by SchizoDuckie** [comment]
I think the buildbot should work again, at least after I can get NWJS to fix their file server. It consistently crashes curl on downloading one of the packages. Is there another nwjs version we can go to or rollback to to test?

**Comment by garfield69** [comment]
@SchizoDuckie  6 days ago I bumped forward in the buildbot script the version of NWJS from 49.1 to 50.3.     
For comparison, my windows VirtualBox unbuntu18 image has no problem fetching any of the NWJS packages using the buildbot scripts.      
50.3 is in the personal release I uploaded to https://github.com/DuckieTV/Nightlies yesterday. I generally tend to keep a version or two behind the NWJS releases, which is currently on 51.1.

**Comment by SchizoDuckie** [comment]
Did more digging.
Opened https://github.com/nwjs/nw.js/issues/7678

**Comment by SchizoDuckie** [comment]
nwjs server problems resolved, and I got the buildbot building again.
Only now there's a problem that seems to originate from the last published release being done manually. No idea what the solution there will be yet, it looks like the previous build has no proper parent commit hash due to being built by @garfield69.

Will check further tonight or tomorrow depending on time available.

**Comment by garfield69** [comment]
I could just delete the custom release and tags entries for that custom build I posted?

**Comment by SchizoDuckie** [comment]
yeah, try that if you will. the regular cron will kick in tonight as
scheduled.

**Comment by garfield69** [comment]
Okely Dokely. I've removed the custom nightly from https://github.com/DuckieTV/Nightlies/releases

Did you have to make any changes to the duckietv-buildbot scripts to fix the problem with the nwjs downloads?
I ask because https://github.com/DuckieTV/duckietv-builder is not showing any changes, and if memory recalls correctly, any such change you made to the scripts directly on the buildbot server may get overwritten by whatever pushes the buildbot github source to the server daily.

**Comment by SchizoDuckie** [comment]
The build was basically borking on nwjs.io throwing errors. I upgraded the
server's ubuntu version to make sure it wasn't anything in openssl or
anything conflicting. It should work with exactly the same codebase.

**Comment by garfield69** [comment]
Excellent. Nightly auto published.
