### ISSUE TITLE
DuckieTV not updating new episodes from TraktTV

### ISSUE THREAD

**Issue by syphondog3** [SchizoDuckie/DuckieTV#1302]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone V30.20.11.25.1385 Nightly

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 10

**Describe the problem you are having and steps to reproduce if available**
When I import new episodes by clicking on the button, it doesn't update. Duckie also seems to keep importing the same episodes over and over and i don't know why.

Happening on multiple computers all using Chrome.

Please let me know what documents I can provide for you.

Thank you

**Comment by garfield69** [comment]
if you are using a Dtv Nightly that has a version that begins with v3020 then you are not using the Standalone version of the Nightly, but are using the Chrome extension version of the Nightly that runs in your Chrome Browser.
The Standalone Nightly is a program you can run which does not depend on the Chrome Browser.
Please confirm which of the two Nightly flavours you are running, so I can provide the appropriate advice.
It sounds likely you are talking about the Chrome Browser extension version, but I need to be sure before proceeding. ;-)
Thanks.

**Comment by syphondog3** [comment]
Hi, 

Yes this is what I installed from communication on the last thread I had with you (https://github.com/SchizoDuckie/DuckieTV/issues/1279#issuecomment-720329961)

*.chrome-newtab.zip 

I just went to that same website -- I will install the version that seems to have been uploaded yesterday! I forgot Duckie New Tab version doesn't auto update any more.

Let me update and then report back!

**Comment by syphondog3** [comment]
ok! downloading the latest version you had of chrome-newtab solved everything. All episodes are pulling correctly.

Is there a way to have the newtab extension in chrome notify me when a new update is available? Or will I have to check for new version periodically? I will probably only check if I run into an issue like I did today...

Thank you for your help!

Raj

**Comment by garfield69** [comment]
there is no way to get a notification currently, so manually checking the release site is the only option for now.
