### ISSUE TITLE
Redownloads episode of most shows - shows SHOWNAMES01E01x7

### ISSUE THREAD

**Issue by ilummox** [SchizoDuckie/DuckieTV#1303]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...
Standalone
**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...
DuckieTV-202103022304-OSX-x64 (installed today to make sure)
**What is your Operating System (Windows, Mac, Linux, Android)**
...Mac

**Describe the problem you are having and steps to reproduce if available**
...
Most shows re-download episodes that have already been downloaded. The calendar will show SHOW S01E01x7, but they are all the same episode. A certain Marvel show has been downloaded dozens of times because of this. It seems to be most shows this happens to. A certain SNL castmember who has his own show has 17 of the same one wanting to be downloaded.

ADDITIONALLY - shows aren't showing all available episodes of shows - refreshing sometimes helps, usually doesn't
ADDITIONALLY - the SHOW>EPISODES>AUTODOWNLOAD ALL doesn't queue up new downloads. Even for episodes already aired. Doing a manual search, I can find them, but I want them to auto download...
**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
First thing to do is to start Dtv, and access the **About** page and confirm that the version you are using is indeed the one you installed.
With the OSx installer, if you have not moved the DuckieTV app from the applications folder to the trashbin before running the installer, it will silently fail, not replacing the program.
Once you have confirmed this we can proceed to more in depth analysis of what could be going on.

**Comment by ilummox** [comment]
Thanks. Running v202103022304. I indeed did remove DTV from the Applications folder before reinstalling.

**Comment by garfield69** [comment]
OK then.
From what I can make out of your report, a possible explanation for your symptoms is that Dtv is not recognising that a torrent download has completed, so it does not set the downloaded flag for that episode, which in turn causes the auto-download to try again later.

So the next thing is looking at how you have configured Dtv with your torrent client, and ensure it is connected and getting the feedback from the client that Dtv is expecting.

1. Which torrent client are you using, and what version is it at?
2. Which torrent client integration option have you set Dtv to use?
3. is the torrent client running on the same mac, that is, is it local to Dtv?
4. do you have the torrent-parameters option enabled? (Dtv->Settings->Torrent->torrent parameters? (This needs to be disabled, to ensure that Dtv is using the client interface).

**Comment by garfield69** [comment]
Also, just to visually spot any differences to your calendar entries for a show that appears to have 7 episodes, access dtv->**settings->calendar->episode numbers on calendar**  and **enable** this option.
this will add SxxExx to the titles in the calendar so its easier to check that they are the same.

if they are the same, access that series episodes list on the side panel, and check if there are the same 7 episodes listed there too.

**Comment by garfield69** [comment]
a screen snapshot of the calendar showing those apparent duplicate entries would be helpful too.

**Comment by ilummox** [comment]
Client - Transmission 3.00 (f4489c982e)
Integration option - Transmission with authentication 
Yes - same machine
Torrent parameters are disabled


<img width="789" alt="Screen Shot 2021-03-03 at 1 22 43 PM" src="https://user-images.githubusercontent.com/18153414/109868740-3d5be980-7c25-11eb-893a-0b45f36e8be2.png">
<img width="153" alt="Screen Shot 2021-03-03 at 1 28 37 PM" src="https://user-images.githubusercontent.com/18153414/109868760-451b8e00-7c25-11eb-9b06-75004f00946b.png">
<img width="1027" alt="Screen Shot 2021-03-03 at 1 28 23 PM" src="https://user-images.githubusercontent.com/18153414/109868764-464cbb00-7c25-11eb-96a9-b2c8aefb0249.png">

**Comment by garfield69** [comment]
Hmm. Very strange. At first glance it does appear that you have duplicate entries, which I don't see when I add **Kenan** to my catalogue, I see a single season, with 4 eps
![image](https://user-images.githubusercontent.com/6933240/109870400-eb6f9e00-7cce-11eb-82a4-518a4f19dc96.png)

Do you regularly start Dtv afresh and after using it quit, or are you using it 24/7 or/and do you hibernate regularly and restart from where you left off?

I would like to take a look at your DB.
1. Could you locate the file **1** which should be at the folder `~/Library/Application Support/DuckieTV-Standalone/<profile>/databases/chrome-extension_bagblfnohpiddokbpaacecffdboomafe_0`
2.  and upload it to the cloud (say DropBox or OneDrive or something similar),
3.  and post a share link so I can fetch it. Thanks.

There should be no privacy concerns, the Dtv DB only contains your series, no personal info just data from Trakt.tv.

**Comment by ilummox** [comment]
The machine and DTV are on 24/7. I'll get you the log file - I appreciate your help.

**Comment by ilummox** [comment]
https://www.dropbox.com/s/an1lwbnr6f280g2/1?dl=0

**Comment by garfield69** [comment]
You've somehow ended up with multiple **episode** records for the same traktid/tvdbid in the DataBase.

The first series that begins to have duplicate records is **Young Sheldon season 4**, in November 5th, which is about the time that we had to upgrade Dtv Nightly to handle the new Trakt.TV API changes that were interfering with fetching series and episode updates. I seems possible that you were unlucky to pick up a version of the Dtv Nightly that was allowing duplicate records to be saved into the DB :-( 

**The rookie S3, zoe's extraordinary playlist S2, disenchantment S2, Saturday Night Live S46, Crikey! it's the Irwins S3, For All Mankind S1, Wandavision S1, Young Rock S1, Kenan S1, Debris S1, Aurora Teagarden Mysteries S1**, have all been impacted.

The good news is that it appears that duplicates have stopped happening, which probably coincides with you having upgraded Dtv Nightly to a newer version. :-)

So now we just have to figure out how best to drop the duplicate records with as little impact as possible.

I'll post ASAP the best way to restore some normalcy to your DB, after I do some research and experiments with the DB you provided, and come up with some instructions for you to follow.

**Comment by garfield69** [comment]
OK. I've tried this out and it seems to work best.
1. First, set your torrent client to **none** to release all the duplicate torrent records in memory and prevent issues during the next steps. **dtv->Settings->Torrent->Choose your torrent client** and click on the **None** button. You will get a whole lot of torrent completed activity and Dtv will disconnect from your Transmission Client.
2. Then **Quit** Dtv and start it up again to get a quiet non active session.
3. Wait a minute until you are sure that the trakttv.updates are not in progress. If you see the trakt.tv activity monitor in the bottom right, then wait until its done and gone.
4. Next we take a backup of the DB (which will save your settings, and the traktid of your 72 series, and the states of any episodes that have been downloaded and/or watched). The backup is not a carbon copy of the DB, its an optimised keys only list. Navigate to **dtv->Settings->Backup->Create a Backup of your Series** and click on the **Create Database Backup** button, save the file to your favourite folder.
5. Now, we wipe the DB and restore from the backup. So navigate **dtv->Settings->Backup->Import a Backup** and
6. tick the **wipe before import** checkbox
7. and click on the **Choose a Backup to load**
8. select your backup
9. answer the **do you really want to wipe the database** popup with **yes**
10. and wait for the restore to do its thing.
11. Once that is done, **Quit** Dtv and start it up again to get a fresh calendar view.

If all worked as planned you should see only one entry for every episode.
You will need to tidy up your Transmission torrents on your client, to remove any spurious episodes.
Once you are satisfied, then set your torrent client on Dtv back to the Transmission Interface and you should be good to go.

If it all turns to custard, no problems, we have a backup of the DB so we can try again, or I can send you my copy of the fixed DB I built using the DB you sent me.

Let me know how it goes. Good Luck.

**Comment by ilummox** [comment]
Thank you for your help. It sorta seems to have helped. I had to manually remove some of my "favorites" and re-add them. There's still some weirdness - hopefully a new release of DTV will help. Thanks again!!
