### ISSUE TITLE
APK package 243bytes instead of 2.87MB since 3rd march

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#1305]
@SchizoDuckie  It appears that the APK packages coming out of the BuildBot are no longer valid.
They used to be about 2.87MB in size, but since the 3rd of March they are now just 243bytes.

Since the PhoneGap service was discontinued by Adobe back in October 2020, the Android builds have been frozen at Android 6, but now it appears that something is broken, perhaps adobe have changed something on the servers?

Given that the APK packages will not run on most Android 8 or 9 platforms (My Samsung S3 tablet Installed a Nightly-202103022304 APK from the 2nd March, but when started it just presents a black screen and nothing else, so it must have crashed, but since there is no console I cannot tell why), I think we should just amend your BuildBot scheduler to not publish (upload) the APK package to GitHub any more.
What do you think?

**Comment by garfield69** [comment]
Hah, the current APK contains 
```XML
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>redacted</RequestId><HostId>redacted+redacted=</HostId></Error>
```

**Comment by ohmichael** [comment]
I use a nvidia shield tv pro and it’s not letting me install it either & I really want it

**Comment by garfield69** [comment]
no longer supporting android builds. closing ticket.
