### ISSUE TITLE
Show "Call Me Kat" not updating

### ISSUE THREAD

**Issue by timothymaietta** [SchizoDuckie/DuckieTV#1307]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...Stand alone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...DuckieTV-202103062304-windows-x64

**What is your Operating System (Windows, Mac, Linux, Android)**
...Win 10

**Describe the problem you are having and steps to reproduce if available**
... Only first three episodes appear on calendar even after refresh, 10 episodes have aired

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
please navigate to the Dtv series details page and click on the trakt, tmdb or tvdb link and post the ids of one or more (specify which you used) so I can check if the problem is just you or global.
thanks.

**Comment by garfield69** [comment]
Also useful will be if you take a screenshot of that series episode list.
I get 11 eps
![image](https://user-images.githubusercontent.com/6933240/110918848-7ceea800-8380-11eb-8469-7b9a04d6294c.png)
tmdbid=113627 tvdbid=382185 traktid=162029

**Comment by garfield69** [comment]
how long ago did you add that series?
what is your trakt.tv update period set to (**dtv->Settings->Trakt.tv->update period**) ?

**Comment by timothymaietta** [comment]
When I just checked the problem has resolved. In case my answers still help figure it out. I first added the show before it had ever aired a single episode, and I had re-added it last week when I first noticed a problem. My tract TV update time is it to three hours. And I had done a manual refresh of both that series and my entire calendar.
