### ISSUE TITLE
TV Shows Not updating

### ISSUE THREAD

**Issue by Dmeinder** [SchizoDuckie/DuckieTV#1311]
**What build of DuckieTV are you using:
Standalone

**What version of DuckieTV are you using:
Stable V1.1.5

**What is your Operating System:
Windows 7 SP1

**Describe the problem you are having and steps to reproduce if available**:
Some shows do not update regularly. Then when selecting update via global settings, or series specific, the calendar also doesn't populate. Then when deleting from favorites in efforts to re-create, when selecting the + symbol to add a small sad face is depicted in the lower right hand corner of the series selected to add as favorite. This has occurred in the last 3 installations. (have had to uninstall, wipe, then re-install due to database backup not including all shows.

**Comment by garfield69** [comment]
Trakt.tv have made significant changes to the way their API works, and Dtv 1.1.5 was published in 2017, so is very out of date.

Upgrade your Dtv to the latest Dtv Nightly from https://github.com/DuckieTV/Nightlies/releases

**Comment by Dmeinder** [comment]
Excellent, I believe this has solved the issue. Thank you so much for your
help!
Take Care,
Dave
