### ISSUE TITLE
Some shows won't be saved in the favorites, some have the "wrong" search format database interoperatibility

### ISSUE THREAD

**Issue by ahab666** [SchizoDuckie/DuckieTV#1312]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Both stand alone and in vivaldi with the button extension

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...
standallone:  v2020 11202304
browser        v 1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
...
windows 10 x64 Pro 20H2 19042.867

**Describe the problem you are having and steps to reproduce if available**
...
Not a biggie - some shows just do not show up in the colander view after being found, added and saved, even though they are airing. Best example is Last week tonight with John Oliver, Young Sheldon,Resident Alien, Real time Bill Maher a.s.o.

"Wrong" search format for some shows - show name + air date finds nothing while show name + SxxEyy finds the show - so the search should include both search strings with string 1 or string 2.

Saving the database in the browser and import it to the stand alone version and vice versa does not work as smooth as one might think. Either a bunch of shows become missing (as favorites) or the downloaded/watched flag gets flipped.
 
**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
You might as well give up using Dtv 1.1.5.
this release was published in 2017 and is not capable of interfacing with the new API requirements of Trakt.tv which is where Dtv gets all its data from.
As a result, Dtv 1.1.5 is no longer supported.

Your Standalone Dtv Nightly is also out of date. The November 2020 version you are using is not capable of fetching updates from Trakt.tv reliably, because on February 2021 Trakt.tv introduced API requests rate limiting.
This means your Nightly can fail to fetch updates when it exceeds the rate limit imposed by Trakt.tv

Upgrade to the latest Nightly to get a fully functional version.

**Comment by ahab666** [comment]
Sp just to clarify,
I need both nightly releases of the same version to have it working ? I am just asking because I normally would stable versions instead pf nightly ones. Did the upgrade and at least i can keep both versions in synch now - thx for the help.

**Comment by garfield69** [comment]
>just to clarify, I need both nightly releases of the same version to have it working ?

Like any app, you cannot expect an older version to be aware of how to handle a backup from a future version.
However, the latest app should be able to handle a backup from an earlier version.

**Comment by ahab666** [comment]
Just to refine your statement - the very latest version i use should be the one I import the database into but not the one i export from ....
Just another question - any information about the database per se - like what is stored (or is not stored) in it and if the backup is an incremental one or is it a complete backup of the current (most recent) status ? thx in advance ....

**Comment by garfield69** [comment]
>the very latest version i use should be the one I import the database into but not the one i export from ....

yes

>any information about the database per se

the DB is used to store all the data fetched from Trakt.tv (series details, season details, episode details, plus any series/episode customisations (such as episode downloaded and marked, series name alias, etc). Also in the DB are jackett search engines you have added, and FanArt links.

Everything from the Settings menu (for example calendar mode, language, torrent client interface, etc), data version and structure, etc,  are stored as local environment variables.
The backup file is a json formatted text file, and contains the local environment variables , a list of all the series trakt_ids you have in the DB, and a list of all the episode trakt_ids that have a downloaded or watched setting.

During a restore, the series are fetched fresh from Trakt.tv using the series trakt_id, and once all the series details, season details, and all the episodes that trakt.tv has for the series are stored on the DB, then any episodes trakt_ids in the backup are used to set that episodes status (downloaded, watched).
