### ISSUE TITLE
Quick search or quick download button missing from interface in V202103242304

### ISSUE THREAD

**Issue by vq2bizz** [SchizoDuckie/DuckieTV#1313]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...Stanalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...Nightly V202103242304

**What is your Operating System (Windows, Mac, Linux, Android)**
...Linux Mint 20

**Describe the problem you are having and steps to reproduce if available**
...The quick search or quick download button missing from interface (the down arrow with the circle around it).

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
The only way that this icon would be missing is for the **Torrent** options to be disabled in your dtv->Settings->Torrent->torrent Functionality

is yours enabled?
