### ISSUE TITLE
Build for Apple Silicon (Apple M1)

### ISSUE THREAD

**Issue by thypon** [SchizoDuckie/DuckieTV#1316]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**

Standalone Version on macOS Apple Silicon

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**

Stable

**What is your Operating System (Windows, Mac, Linux, Android)**

macOS latest (big sur0

**Describe the problem you are having and steps to reproduce if available**

DuckieTV is built only for x64 macs, it would be awesome to have a native Apple Silicon (ARM) build.

**Comment by garfield69** [comment]
Dtv is written in JavaScript using the AngularJS framework as a Chrome Browser extension.
The standalone version is the exact same JS code encapsulated by the NWJS run time environment which includes a headless chromium browser.
The NWJS [binaries](https://nwjs.io/downloads/) officially only support Windows, linux on AMD platforms and OSx.
However there is an unofficial community ARM version available, but it is not supported by either the NWJS or Dtv teams.
I don't have any ARM platforms to test with so the following is untested, but maybe this will work for you (love some feedback on this, thanks).
See https://github.com/SchizoDuckie/DuckieTV/wiki/How-to-run-a-DuckieTV-Standalone-for-ARMv7

**Comment by thypon** [comment]
Thanks I will check

**Comment by thypon** [comment]
An issue is already filled in nwjs. I will link it here https://github.com/nwjs/nw.js/issues/7620
