### ISSUE TITLE
nightlies no longer have OSX packages

### ISSUE THREAD

**Issue by ekko20six** [SchizoDuckie/DuckieTV#1317]
hi is there a bug preventing the OSX releases for the nightlies or are they not being made anymore?
Cheers

**Comment by garfield69** [comment]
@SchizoDuckie The Nightly builds since Wed Apr 21 2021 only contain the windows x32 and x64 packages.
The Linux x32 and x64, ubuntu x32 and x64, OSx, chrome action and chrome newtab build are missing.
Please investigate. Thank you.

**Comment by garfield69** [comment]
@SchizoDuckie  I don't know if you did anything, but the latest build today has all the packages so we are good to go again. Thanks.

**Comment by garfield69** [comment]
@SchizoDuckie  todays build is back to just 4 assets again, so this issue still needs investigation please. Thanks.

**Comment by garfield69** [comment]
Hmm. @SchizoDuckie  Despite my having updated the DuckieTV/duckietv-builder source to bump the NWJS to 0.52.2 (which chromium 89) about 5 days ago, the Nightly being built still only show 0.51.1 (with chromium 88) %-/
And the packages coming out of the buildbot are usually only the two windows packs, with the full set of 12 assets only being published twice in the last 12 days :-(
Perhaps the server is out of space again?

**Comment by ilike2burnthing** [comment]
Buildbot has died again

**Comment by garfield69** [comment]
@SchizoDuckie  Do you know why the buildbot is not picking up changes to the https://github.com/DuckieTV/duckietv-builder source?
I have updated shared.js twice over the last two months, but the builds are still using nwjs 0.51

**Comment by garfield69** [comment]
@SchizoDuckie  can you please look into why the buildbot is no longer regularly updating its duckietv-builder program from the source at https://github.com/DuckieTV/duckietv-builder
The Nightly standalone builds are still using NWJS 0.51 which means that my changes in April, May and August to the duckietv-builder source code are not being picked up by the buildbot :-(
Thanks.

**Comment by garfield69** [comment]
@SchizoDuckie  are you still out there?
there has not been a nightly published since 8th September, something appears to be broken. Can you take a look please?
while you are there, the Nightly bot does not appear to be pulling the duckie-builder code from the repo or maybe its not rebuilding the code regularly from source like it use to. Can you fix?
Thank you.
[edit] updated the date since last build.

**Comment by ilike2burnthing** [comment]
New build is out - https://github.com/DuckieTV/Nightlies/releases/tag/nightly-202110140614

**Comment by garfield69** [comment]
that's me. I manually built and uploaded to the nightly repo, using my ubuntu21 and my duckietv-builder clone.
