### ISSUE TITLE
Calendar not updating - even after manual refresh.

### ISSUE THREAD

**Issue by v643179** [SchizoDuckie/DuckieTV#1319]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...Nightly v202009082200  (switched to this version when I started using qBittorrent)

**What is your Operating System (Windows, Mac, Linux, Android)**
...Wnidows 10

**Describe the problem you are having and steps to reproduce if available**
...My shows are not updating on my calendar.  And in some cases even when I manually refresh, they still don't update.  For example - "black-ish" shows the last episode aired was s07e10 - but it was actually s07e19.  Even after a manual refresh it doesn't change.  I basically have to go to eztv or some other tracker site and grab my torrents manually - which kinda defeats the purpose.

**Attach any DuckieTV statistics or Developer Console logs if available**
...
![black1](https://user-images.githubusercontent.com/74112559/117736522-a96e4700-b1ac-11eb-9a6a-374252ed0085.PNG)
![black2](https://user-images.githubusercontent.com/74112559/117736523-aa06dd80-b1ac-11eb-835e-ea11c343b621.PNG)

**Comment by garfield69** [comment]
You need to **update** your Nightly version. You are on 202009082200 so you are missing fixes made this year to cope with Trakt.tv changing the way they support tv update queries, and their introduction of rate limiting queries on their data API servers. 
Upgrade to  https://github.com/DuckieTV/Nightlies/releases/tag/nightly-202104302304

Also change your **dtv>settings>trakt.tv>trakt.tv update period** from the default _12_ hours to **1 hour** to improve chances of getting all the updates for all shows.

If you continue having issues after this then post here and we will re-open this ticket and help you investigate further.
