### ISSUE TITLE
Magnet Downloads for the ETTV SE are not working

### ISSUE THREAD

**Issue by winfij** [SchizoDuckie/DuckieTV#1324]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
DTV nightly V202109022304

**What is your Operating System (Windows, Mac, Linux, Android)**
Win10

(Originally posted on r/duckietv, but it got removed by the spambot for some reason..)

After some experimentation, it appears that Magnet Downloads for the ETTV SE are not working - clicking one gives the DTV popup, but nothing in the torrent client (BiglyBT).

I fired up the debug console and it logged this error on clicking the Download Magnet icon:

```
deps.js:2398 TypeError: Cannot read property 'querySelector' of null
    at getPropertyForSelector (app.js:16359)
    at parseDetails (app.js:16546)
    at app.js:16687
    at deps.js:2411
    at m.$digest (deps.js:2422)
    at b.$apply (deps.js:2426)
    at HTMLAnchorElement.<anonymous> (deps.js:2468)
    at og (deps.js:2311)
    at HTMLAnchorElement.d (deps.js:2311) "Possibly unhandled rejection: {}"
(anonymous) @ deps.js:2398
(anonymous) @ deps.js:2369
g @ deps.js:2410
$digest @ deps.js:2422
$apply @ deps.js:2426
(anonymous) @ deps.js:2468
og @ deps.js:2311
d @ deps.js:2311
```
Trying Magnet Download for another SE (RarBG) worked OK:

`app.js:16156 Firing magnet URI!  magnet:?xt=urn:btih:.....`
I'm assuming ETTV have changed their magnet link format and DTV will need adjusting to cope?

I'm running BiglyBT v2.8.0.0 and DTV nightly V202109022304

**Comment by garfield69** [comment]
Thank you for reporting. 
Yes, it appears that the torrent details page on ETTV has had some HTML changes and I've got to update the Dtv ETTV search engine to use the new selectors. I start work on this shortly.

**Comment by garfield69** [comment]
https://github.com/DuckieTV/Nightlies/releases/tag/nightly-202109072304
