### ISSUE TITLE
Turner and Hooch not showing

### ISSUE THREAD

**Issue by jriker1** [SchizoDuckie/DuckieTV#1326]
On DuckieTV standalone latest nightly.  Turner and Hooch was downloading weekly for the first 5 episodes and now it's not showing in the guide anymore.  When I go to:

https://trakt.tv/shows/turner-hooch/seasons/1

It shows more episodes than the first 5 have aired but not in DuckieTV.

**Comment by garfield69** [comment]
I am seeing 
![image](https://user-images.githubusercontent.com/6933240/133492257-4cd201d4-4cbc-485d-a136-c6b0e1990eae.png)
- Please post the Dtv version you are on by going to the Dtv About page and checking the header.
- Then access the Dtv series detail page for Turner & Hooch and on the links right click over the Trakt link and select inspect
![image](https://user-images.githubusercontent.com/6933240/133492774-af1fef6c-6ea4-49cf-a759-2c3f09b75599.png)
mine states that its traktid is 170691
what does your say?

**Comment by garfield69** [comment]
presumed resolved.
