### ISSUE TITLE
Duckie Standalone not reading from backup.

### ISSUE THREAD

**Issue by Lanvar** [SchizoDuckie/DuckieTV#1327]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...Standlone 

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...Nightly  V202109072304

**What is your Operating System (Windows, Mac, Linux, Android)**
...Windows 10

**Describe the problem you are having and steps to reproduce if available**
...When I try to load the backup nothing happens apart from "Loading, please wait" message. I left it for hours, but nothing happened. I tried doing it from trakt as well. This is a fresh install of windows.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
Have a read of https://github.com/SchizoDuckie/DuckieTV/wiki/FAQ#i-cant-add-a-series-and-there-is-nothing-in-the-calendar
and see if that helps.
Let me know how you go.

**Comment by Lanvar** [comment]
I tried what it suggested, I waited a little longer after clearing the User Data and starting. It did seem to get further, it imported some shows, but not most of them. Some shows it imported, it had not registered the viewing status. I'm going to try again, but it is not looking good ;/

**Comment by garfield69** [comment]
as a comparison for you, I recently (17 days ago) performed a backup import of 235 series which took about 2 minutes.

**Comment by Lanvar** [comment]
I'm giving it way longer than that, I start it up, and take a game up in front of it, to stop my self from "just checking" :)

I have since cleared the User data folder again, and started it, waiting 5 mins, and started an import, it loaded even less this time.

**Comment by garfield69** [comment]
press **F12** to open the _development tools_ page, click on the **console** _tab_ to view the log, and see if there are any signs of errors related to **trakt**.tv. ignore the _fanart_ ones, they are usually 404 not found for posters and not a problem.
also on the main page of Dtv **right click** on a free space and select the **inspect background page**, and check the **console** log there too for any thing.

**Comment by Lanvar** [comment]
Sure, but I had just started it again when I seen the message, I'm going to let it run for another 5 mins, to see if I seems to import the same shows or if it is has already died.

**Comment by garfield69** [comment]
when was the backup taken?

**Comment by Lanvar** [comment]
Backup was taken yeterday.
Errors, there are loads, Trakt is part of it, but also
![image](https://user-images.githubusercontent.com/14298259/133918806-9ec1e9c8-aa8a-4b91-882d-f59e9ae6aeab.png)

**Comment by Lanvar** [comment]
![image](https://user-images.githubusercontent.com/14298259/133918839-d3d8daa7-c69a-4977-bfc5-bc812378ce4a.png)

**Comment by garfield69** [comment]
Ah, the trakt.tv server you are connected to is clearly under severe stress and is rate limiting your requests (429 too many requests).
each delay you are seeing is in 1000th of a sec, so you are getting 6 to 8 seconds delay between each request, extending your restore time.
the backup contains a trakt_id each series name, and Dtv asks trakt.tv to return the full series details as well as a list of each episode and its details.
once the episode records are downloaded, the backup then overlays any downloaded and watched states.

As long as each poster eventually goes from a spinning wheel to a tick then the restore for that series is complete.


IF you like, you could take a copy of the backup, append to the filename `.txt` and drag/drop it here and I can try an import on my dev machine.
IF that goes well for me here, then I can then post back a replacement DB for you.

**Comment by Lanvar** [comment]
Removed backup.txt

That would be cool thanks, I'd be interested to see if you can get it to restore. You will get a giggle out of some of the crap shows on there, they were for my ex, honest! :)

**Comment by Lanvar** [comment]
In the past 25 minutes or so, I have not seen any of the posters get a green tick mark. Nor have any been added to the light blue area at the top.

**Comment by garfield69** [comment]
Nah, I'm being hit with the rate limit too. :-( 
Some of the early request at the start are set with a delay for 169 second!!

IT would appear this is not a good time to do a restore right now. 
Maybe Trakt.tv has been under a DDoS attack recently and are hyper sensitive to multiple requests.

I suggest you shut down your Dtv for now, and try again tomorrow.

**Comment by Lanvar** [comment]
ok, will do thanks. Should I restart the restore, or do a clean one? 

Also, if I hit the problem again, can I apply a change in the polling rate? So I can let it run for a day or whatever?

**Comment by garfield69** [comment]
>Should I restart the restore, or do a clean one?

You can use the **Dtv>settings>backup>import a backup** option, it will override anything already in the DB with the same trakt_id.
After the backup import is completed I recommend restarting Dtv to ensure that all the settings get loaded and applied properly. 

>can I apply a change in the polling rate?

not a simple matter with the packaged version of Dtv you are using. :-(
That's why the delay handler is there. Dtv requeues the request and waits the delay period and tries again.
But I have a feeling that as the requests keep coming the delays get longer and longer to the point where a restore may take longer than 24 hours.
Another complication is that if Dtv is active at midnight then it does an internal reset a few seconds after, so it can prepare for the new day (reload the calendar and perform house keeping), and this will effective abort the import :-(

**Comment by Lanvar** [comment]
OK, thanks. I'll report back if I have any problems. Have a good one 👍

**Comment by garfield69** [comment]
I have managed to restore 616 series so here is the DB
[1.zip](https://github.com/SchizoDuckie/DuckieTV/files/7191746/1.zip)
- shut down Dtv
- replace the db
- startup Dtv

**Comment by Lanvar** [comment]
Thank you Garfield, really appreciate it!

**Comment by garfield69** [comment]
Working ok now?

**Comment by Lanvar** [comment]
I just got to sit down to look at it now, what file is it I'm replacing? I set it in replacing Databases.db, but I'm thinking that may of been wrong.

**Comment by garfield69** [comment]
its the file that should be in a path similar to
`C:\Users\<usename>\AppData\Local\DuckieTV-Standalone\User Data\Default\databases\chrome-extension_bagblfnohpiddokbpaacecffdboomafe_0`

**Comment by Lanvar** [comment]
Yeah, that got it, thanks again! :)
