### ISSUE TITLE
202109072304: reload/restart fails

### ISSUE THREAD

**Issue by ilike2burnthing** [SchizoDuckie/DuckieTV#1331]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Nightly 202110140614 x64

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 10

**Describe the problem you are having and steps to reproduce if available**
`Reload app` and `Simulate browser restart` both close the window but it never reloads. Program remains active and has to be terminated in task manager. Reverting to 202109072304 resolves this.

Trying to replicate it in Windows Sandbox gives a different result, where 202110140614 won't even display at launch and has to be terminated in task manager, but 202109072304 works fine. Doesn't matter what order they're installed in. Not sure if this difference is caused by it being a fresh install or something else.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
I've switch the **latest** tag _back_ to 20210907 for now (which was build using NWJS 0.51.1).
20211014 was built using the latest NWJS 0.57.1, so I'll rebuild going back NWJS versions until its working again. 

Can you tell me how you perform the `reload app` and `simulate browser restart` so I can test each back-version?
Thanks.

**Comment by ilike2burnthing** [comment]
Right-click anywhere on the DuckieTV window and click `Reload app` or `Simulate browser restart`.

**Comment by garfield69** [comment]
tried 0.56.1, 0.56.0, 0.55.0 and this one passes the test so at least I don't have to go all the way back to 0.51.1 ;-D
I'll eventually have to raise a bug with the NWJS support.

**Comment by garfield69** [comment]
try https://github.com/DuckieTV/Nightlies/releases/tag/nightly-202110141941

**Comment by ilike2burnthing** [comment]
Yep, that's working fine, thanks.

**Comment by garfield69** [comment]
https://github.com/nwjs/nw.js/issues/7798

**Comment by garfield69** [comment]
Hmm. Reddit post https://www.reddit.com/r/duckietv/comments/qabu2i/duckie_tv_keeps_crashing/
I will backtrack NWJS to 0.51 and hopefully get a version that works again.

**Comment by ilike2burnthing** [comment]
I've had DuckieTV open through midnight for the last few days and it has refreshed without issue. Only difference I can see from their description is that mine wasn't minimised to tray, just open normally.

**Comment by garfield69** [comment]
Reddit user reports they are still finding Dtv frozen in the morning with 202110181544
I'm getting them to list the Dtv window settings.

**Comment by garfield69** [comment]
Reddit user reports they don't use the system tray.
So gave instructions to try the system tray settings and see if that works, since this is usually the better way of running Dtv 24/7

**Comment by ilike2burnthing** [comment]
~New NWJS nightly builds with the fix have been released, starting a few days ago, in case you want to try it out. Newest of which is https://dl.nwjs.io/live-build/nw60/20220105-021413/b3a2fa01d/v0.60.0/~

Scratch that actually, no need for nightlies, v0.59.1 has the fix as well - https://nwjs.io/blog/v0.59.1/

**Comment by garfield69** [comment]
202201060722
