### ISSUE TITLE
Some torrent websites not working in search engine

### ISSUE THREAD

**Issue by ishy93** [SchizoDuckie/DuckieTV#1333]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...  standalone 

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
... nightly 202110290923

**What is your Operating System (Windows, Mac, Linux, Android)**
... windows 10

**Describe the problem you are having and steps to reproduce if available**
...  I'm in the UK, the following torrent sites do not work in the search engine (not returning any results): 1337x, etag, ext, eztv.ag, idope, isohunt2, katws, nyaa, thepiratebay
the search query was "foundation s01e01" (without quotations)
I'm not using a vpn or proxy. So I'm guessing that it's because the url duckietv is trying to access is blocked because of censorship
Is it possible to change the address of the torrent sites in the search engines myself, if so how do i do it?  

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
Firstly, be aware that even though you have found a domain to a site that appears similar to the original, unless that domain is one of the official alternates for the original site, then it is likely that the new domain is from a different provider.
So while the the new site may appear to show a similar looking page of results, under the skin the HTML used to present the result may be different enough to prevent the Dtv search engine from matching selectors to pull the torrent lists.

For this reason Dtv does not provide a settings page where you can enter replacement domains for its search engines.

Your best bet is to pair Dtv to any of the public indexers available via Jackett. 
Have a read of https://github.com/SchizoDuckie/DuckieTV/wiki/Using-Jackett-with-DuckieTV and see if this helps you out.
