### ISSUE TITLE
Export Functionality

### ISSUE THREAD

**Issue by jlneder** [SchizoDuckie/DuckieTV#1334]
The backup functionality is insufficient if you want to migrate the data to any other series manager like sickchill or alike.
Duckie isn't working for me on Void musl, and I was exploring options but I don't know how to use the json backup and the list of Trakt ids and convert them to series and chapters.

**Comment by garfield69** [comment]
Can not help you with that.
The backup file was created exclusively for use with Dtv.
The series data in the backup file simply consists of the trakt.tv series id of a show, followed by Dtv settings relevant to the show from a Dtv point of view, and then a list of episode trakt.tv ids that reflect the state of the episode (downloaded, watched) for that series on Dtv.
During an import, Dtv uses the show id to fetch the complete current data from trakt.tv about the show and all its episodes, and once loaded to the local Dtv DB, the settings and episode states are overlaid onto the DB records.
And that is all I can tell you.

The only possibility I can think of, is if the apps you are planning to switch to can use your trakt.tv account collection and history. IF you find such an app, then you could use Dtv to push your Dtv collection and history to your Trakt.tv account, and then import that back to your alternate app.
