### ISSUE TITLE
add Time sort to Torrent Search [Enhancement Request]

### ISSUE THREAD

**Issue by drhouse** [SchizoDuckie/DuckieTV#1335]
I started using DuckieTV today, and while using the Torrent Search feature I was surprised that it didn't have a 'Time/Age/Date' column. For example, if I'm looking for the latest episode of a TV show, I usually don't know what episode number is the latest, and usually rely on a most recent time sort. I understand there may be an issue with various torrent sites using different time formats, but I'm pretty sure there should exist some sort of converter or universalizer or 'time normalizer' code.

**Comment by garfield69** [comment]
When you add a series to Dtv, Dtv tracks the episodes available for that series.
All episodes are presented in the calendar. The one closest to todays day will be the latest.
Users usually set up the auto-download service which takes care of searching for the latest episodes automatically and downloading torrents based on whatever selection criteria they (seeders above a number, keywords for their favourite provider, size constraints, etc). 
Alternatively, users can navigate to the episodes list and manually start a torrent search for an episode.
Or click on an episode on the calendar to open the details page and start a torrent search for that episode by clicking the find-a-torrent button.
In all these cases, the torrent search panel is usually loaded with one episode to search for, so sorting by date is redundant. The torrents found for an episode are sorted by most seeders by default, as this is the most common requirement.

Users do not usually start a manual torrent search using just the series name, and expect to get a date sorted list of all the series episodes by age. That seems redundant given that Dtv can provide the latest episode of a series and preload the torrent search with that episode for searching manually.

**Comment by drhouse** [comment]
yeah, I see what you're saying... the thing is the Torrent Search interface is actually quite useful as a meta-searcher for any kind of torrent, I'm not aware of a similar meta/aggregator (or have seen low-quality sites that don't really work)
- searching for an episode was one example, but what if it's a one-off, like something I don't usually watch (not a Favorite), but just want the latest episode, I don't think the auto-download feature would apply (which btw I did set up with my torrent app)
- another example, I put in 'Spiderman No Way Home' as a movie, and I know that the more recent versions are usually better
- or as I was saying as a meta-searcher, what if searched for plugins for software, the latest entries would be useful

I understand if this kind of thing is out of scope for the general purpose of DuckieTV, but if adding a Time sort wouldn't be difficult, I'd find it very useful... maybe, if the time entries were exposed as a column, but weren't even the same format, I'd still be able to visually compare dates

**Comment by garfield69** [comment]
In the seven years the Dtv has been active, you are the first to request such a feature.

Most users gravitate towards apps like Sonarr (for tv) or Radarr (for movies) if looking for alternatives to Dtv.
Dtv is designed for tv only.

IF you are looking for a general torrent search app, that can aggregate results across multiple sites, and present results fairly close to that provided by the torrent web sites themselves, then perhaps Jackett is going to be more useful to you. https://github.com/Jackett/Jackett

ATM, as things stand with Dtv, the author abandoned the project (nearly 5 years ago), and I as a temporary volunteer only have time these days to do emergency fixes to keep the app ticking.
 I'm just keeping the lights on, and will usually only add a feature if there is an overwhelming need by popular request.
Sorry, but your request just does not fit the criteria, either as a useful request within the design of Dtv, or as a feature that anyone else is interested in, for the last 7 years ;-)
