### ISSUE TITLE
DuckieTV not triggering downloads in Vuze

### ISSUE THREAD

**Issue by DevinSmith69** [SchizoDuckie/DuckieTV#1336]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone - Windows

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
DuckieTV Standalone Nightly v202111190950

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 64bit

**Describe the problem you are having and steps to reproduce if available**
On 8th December 2021 I noticed my auto-downloads weren't running between DuckieTV and VUZE (been running with this setup for over a year already) I then attempted to manually download the episodes by navigating to a series and searching for the episode and clicking on the torrent I want to download, the notification pops up to say download started in VUZE, I then check Vuze and nothing is downloading - the auto downloader has these constant notifications that pop up saying download started in Vuze but nothing starts downloading - If i click on download magnet link then it opens up in vuze 100% but this is not what I want as it was working perfectly - please let me know any ideas to test or check

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
Hmm. I just tested Dtv against Vuze 5.7.6 and it appears to be working ok.

- Please confirm which version of Vuze you are using.
- Then access the **Dtv>settings>vuze integration** side panel and confirm that you are seeing **status: connected to vuze api** above the address box.
- Also check that **Dtv>settings>torrent>torrent parameters** is **disabled**.
- Finally, after clicking on a download and getting the notice, press **F12** to open the _development tools_ page, click on the **console** _tab_ to view the session log, and look for messages related to vuze and torrents/magnets and so forth. Any error messages?

**Comment by DevinSmith69** [comment]
Hi there,

Vuze version is 5.7.6.0, all the above tests in Duckie are perfect, Vuze is showing green and showing connected however with the developer tools I am now seeing this error:

![image](https://user-images.githubusercontent.com/33171507/147290149-cc8d3b29-7b55-43b8-9182-51cc964b2550.png)

The problem is the Username and Password and port are configured as per the Vuze web remote and Duckie is showing successful connection - any ideas?

**Comment by garfield69** [comment]
- start by opening your browser and accessing http://localhost:9091/ to get vuze to prompt you for the user and pswd, and confirm that these are indeed the correct credentials.
- if correct, then on the Dtv **vuze integration** side-panel re-enter your credentials and save. check the Dtv log for success or failure.
- if failure, try setting the password again on the vuze plugin web remote page, and restart vuze and dtv again in that order and see if that sort it.
- check that the vuze plugin web remote has mode=full and access=all
- check you are not running any other torrent host apps (utorrent, biglyBT, qBt etc) that are using the same port

let me know how you go.

**Comment by garfield69** [comment]
Something I just remembered, that you may not be aware of, in case its relevant to you.
If you keep Dtv running, and for what ever reason you shutdown Vuze and start it up later, Dtv may not be aware of the disconnect.
In this case you need to also shutdown Dtv, and start it up again after vuze is back up.
Dtv does not have a heartbeat check on connections and so does not try to login again after vuze is shutdown and started up again.

**Comment by DevinSmith69** [comment]
Ahhhh thank you so much it's all fixed, I changed my network setup at home a few weeks back and I think Vuze as a security protocol for web remote reset my vuze web remote mode to view and not full - haven't touched the settings since I set them up months ago! Changed that back to full and up and running! Thank you very much!

**Comment by garfield69** [comment]
\o/
