### ISSUE TITLE
DuckieTV Not Syncing with Trakt.tv w/ New episodes of certain TV Shows.

### ISSUE THREAD

**Issue by geoff-scott** [SchizoDuckie/DuckieTV#1338]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...
Chrome Extension (New Tab / Browser Action)

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...
V3020.12.1385

**What is your Operating System (Windows, Mac, Linux, Android)**
...
LINUX

**Describe the problem you are having and steps to reproduce if available**
...
Synchronisation with Tackt.tv is not pushing updated airings of certain TV shows. 

EG: Law and Order SVU (Special Victims Unit) hasn't updated since Nov 11, 2021 - but there has been at least 4 episodes that have aired on TV since the last reported date on DuckieTV

REF: https://trakt.tv/shows/law-order-special-victims-unit

![Screenshot from 2022-01-21 12-51-05](https://user-images.githubusercontent.com/71340280/150576315-5231d741-0db9-4f01-a3b7-ee84f3e4f806.png)

**Attach any DuckieTV statistics or Developer Console logs if available**
...
![Screenshot from 2022-01-21 12-54-28](https://user-images.githubusercontent.com/71340280/150576728-ca56df8c-1e9f-4521-a6b4-b114c1f19982.png)

**Comment by garfield69** [comment]
the version of Dtv nightly you are using was released back on Dec 2020
Around early Feb 2021 Trakt.tv added data rate limiting to their API servers, which meant that versions of Dtv prior to this date would be prevented from fetching all the shows data before the rate limit kicked in and stopped requests.

You need to upgrade to the latest nightly from https://github.com/DuckieTV/Nightlies/releases/latest so you can use a Dtv version that can manage the rate limiting requests for data from Trakt.tv API servers.

**Comment by geoff-scott** [comment]
Thank you for your quick response. The update has solved the issue I was facing.
