### ISSUE TITLE
Duckie not retrieving any search results with any torrent sites via Mac app

### ISSUE THREAD

**Issue by ftwentytwo** [SchizoDuckie/DuckieTV#1340]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
DuckieTV-202201301134-OSX-x64

**What is your Operating System (Windows, Mac, Linux, Android)**
Mac

**Describe the problem you are having and steps to reproduce if available**
when searching for a torrent, is doesnt retrieve any search results. Not auto downloading either. 

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
what is your default Search Engine?
- ETTV is down, 
- EXT and Idope often use cloudflare DDoS protection so that can prevent Dtv connecting as well.
- IF you are using TPB check the Dtv>Settings>Torrent Search Engines>The Pirate Bay>Main Mirror is set to `https://thepiratebay0.org/` as some of the other mirrors are broken.
- Also, (FYI) on Mac, it pays to check the Dtv About page title, to ensure you are on the version you think you are on, as the Mac installer will silently fail to replace the old version if you did not first move the DuckieTV app to the bin in your Applications folder.

Let me know what you find.

**Comment by ftwentytwo** [comment]
Hi, thanks for the help! 

I changed the default to several different search engines and they all do the same unfortunately. It just says searching, and never finds anything. 

I checked the about page and I am on the version I mentioned. 

When I uninstall Duckie and try to reinstall the app my shows are still there once I reinstall. Is there somewhere that is storing information on the Mac that could be corrupted?

**Comment by garfield69** [comment]
Strange. The Dtv data folder on the mac is located at `~/Library/Application Support/DuckieTV-Standalone`
But you cannot repair this, only delete the folder and start again.

So to confirm some details, you can view the series and episodes data on Dtv using the favourites page, and series details page, but if you manually start a search for an episode you do not get any results returned on the Torrent Search page?
Is that correct?
And you can view the ADSM page, it shows episodes due for downloading, but all of them are tagged as not-found?

Use the `Cmd-Alt-I` key sequence to open the Development Tools page, and click on the Console tab to view the log.
are there any error messages related to the search engines?
You can ignore errors to do with the FanArt not found, or temporary errors from Trakt.tv related to data-limit reached retrying in x seconds messages.

**Comment by ftwentytwo** [comment]
Ok deleted that folder and started over with no luck! 

Yes, I can view series and episodes data. When I manually search for an episode using any of the search engines I get no results. 

I have tried to open the dev tool but nothing happens/opens.

**Comment by garfield69** [comment]
Hmm. OK, well, to open the DevTool you can also use your mouse. Just **Right Click** and select **Inspect**.
Then after doing a torrent search click on the DevTools **console** tab and check the log. The log hold only activity for the current Dtv session.
Also can you post a screenshot of a torrent search, so I can see an example, and also, click on the About page, navigate down to the Statistics section, and click on the statistics header. That should copy the stats to your clipboard. Paste to a plain text txt file and drag/drop the file here so I can take a looksee.

Thanks.

**Comment by ftwentytwo** [comment]
<img width="630" alt="Screenshot 2022-02-02 at 17 48 25" src="https://user-images.githubusercontent.com/98851578/152209160-993518b8-2b9f-4e4c-8046-0bea7464a4b6.png">

**Comment by ftwentytwo** [comment]
<img width="988" alt="Screenshot 2022-02-02 at 17 49 47" src="https://user-images.githubusercontent.com/98851578/152209511-cbc5cb51-efa4-43ec-98e9-2c0f2b539205.png">

**Comment by ftwentytwo** [comment]
[duckie.pdf](https://github.com/SchizoDuckie/DuckieTV/files/7988940/duckie.pdf)

**Comment by garfield69** [comment]
Hmm. In the log I see you using TPB, idope, isohunt, and kickass.
Apart from idope which returned 503 (classic cloudflare anti-DDoS interference), the other 3 returned NET::ERR_CONNECTION_REFUSED which is an indicator that something is blocking your access to these sites.

Can you open the DevTools console again, repeat a search using each SE one at a time, find the connection refused errors on the log, and **right click** on each of the links and select **Copy Link Address**.
Then on a browser running on the same machine as Dtv, paste that address and see if the search completes or if you get more info from the browser as to why the search fails.

**Comment by ftwentytwo** [comment]
<img width="820" alt="Screenshot 2022-02-02 at 21 33 16" src="https://user-images.githubusercontent.com/98851578/152240952-8b4ca7df-4bfa-4e7a-8544-9cfdb051037c.png">

**Comment by ftwentytwo** [comment]
Good news is though that some of the search engines have started working! No idea why now. 

zooqle / tgx / showrss / rarBG all working now. 

Could it be something to do with my router blocking certain sites?

**Comment by garfield69** [comment]
>Could it be something to do with my router blocking certain sites?

that is one possibility. 
Another could be your firewall or anti-malware app.
Also likely is that your ISP is blocking access.
Are you using the DNS provided by your ISP?
if so, consider setting your router to use one of the public DNS services, such as cloudflare's 1.1.1.1 or Google's 8.8.8.8 and see if that opens up access.
