### ISSUE TITLE
What are the steps for a complete removal and clean?

### ISSUE THREAD

**Issue by snblackout** [SchizoDuckie/DuckieTV#1344]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
nightly-202202070745

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 10

**Describe the problem you are having and steps to reproduce if available**
Database got corrupted.  Cannot add favorites.  Cannot import backups.  Tried "wipe data".  Tried uninstall and re-install but cannot get working.

I tried installing on a different computer and works fine.  I have some lingering things messing things up.  I want to totally clean any database/configuration and start over, hopefully from a backup.

**Attach any DuckieTV statistics or Developer Console logs if available**
N/A

**Comment by garfield69** [comment]
- shutdown your standalone Dtv
- locate the data folder at `C:\Users\<username>\AppData\Local\DuckieTV-Standalone` 
- rename or delete it
- start Dtv and wait a few minutes for pre-initialisations to complete before importing your backup
- after import I recommend restarting Dtv to ensure that  the restored settings are applied
