### ISSUE TITLE
Search failing for program with no TVDB ID

### ISSUE THREAD

**Issue by ilike2burnthing** [SchizoDuckie/DuckieTV#1345]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Nightly 202202070745 (verified in About section)

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 10 x64

**Describe the problem you are having and steps to reproduce if available**
- click `Add a show`
- search `Phoenix Rising`
- click second one (2022, HBO)
- click `Add to favourites`
- click `Episodes`
- click first episode
- click `Find a torrent`
- get errors below, no search window appears

Series Details page has working IMDB, TMDB, and Trakt links, just not TVDB. No issue with other programs. Can reproduce with a fresh install in Windows Sandbox.

**Attach any DuckieTV statistics or Developer Console logs if available**
```text
app.js:10108 Could not load fanart for null tvdb_id
```

```text
TypeError: Cannot read properties of null (reading 'toString')
    at Object.getEpisodeMapping (app.js:10702)
    at Object.getSearchStringForEpisode (app.js:10547)
    at Object.findEpisode (app.js:16129)
    at m.$scope.openDialog (app.js:7446)
    at deps.js:2537
    at e (deps.js:2468)
    at m.$eval (deps.js:2425)
    at m.$apply (deps.js:2425)
    at HTMLAnchorElement.<anonymous> (deps.js:2468)
    at og (deps.js:2311)
(anonymous) @ deps.js:2398
(anonymous) @ deps.js:2369
$apply @ deps.js:2426
(anonymous) @ deps.js:2468
og @ deps.js:2311
d @ deps.js:2311
```

**Comment by garfield69** [comment]
I'll add the tvdbid to the [TraktidTvdbidXref.json](https://github.com/DuckieTV/SceneNameExceptions/blob/gh-pages/TraktidTvdbidXref.json) table to provide the missing data from the trakt.tv api server.
Your Dtv should fetch the table within the next 24 hours.
Afterwards, you may need to go to the series details side panel and press the Refresh button to force Dtv to load the tvdbid from the table, if the usual trakt.tv update cycle has not kicked in once the new table is fetched.

**Comment by ilike2burnthing** [comment]
Would it be worth adding an error in the UI for this, directing them to report the series here? Unless the user knows to look at the devtools, they're just clicking a button and it isn't working for seemingly no reason.

**Comment by garfield69** [comment]
I've looked into this back in 2022 when this was raised, and I could not find a way, because once you press the button the dialogue does not get feedback if its worked or not, so I've no way to return a response, or at least, none that my paltry skills at angularjs can code.

**Comment by garfield69** [comment]
aa8711afa6442c49144cb12962d67476d470108c  will at least give the user a clue that the dialogue is not available and link to the relevant WIKI page.
