### ISSUE TITLE
DTV with Tixati 2.86 is not displaying download progress & not setting market as downloaded

### ISSUE THREAD

**Issue by minoglie** [SchizoDuckie/DuckieTV#1346]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
[Nightly release for 28-03-2022 16:20:00 (nightly-202203281620)]

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 11

**Describe the problem you are having and steps to reproduce if available**
DTV not displaying download progress & not setting market as downloaded leading to multiple downloads of the same torrent.

Clicking the magnet on the torrent triggers Tixati to download the torrent but DTV download progress says "Torrent not found in torrent client" and when i click on the torrent client it says torrent found 0.
I just tried reinstalling both DTV and Tixati but the error persists.

**Attach any DuckieTV statistics or Developer Console logs if available**
[
  {
    "name": "Current Date and Time",
    "data": "Wed, 30 Mar 2022 18:18:19 GMT"
  },
  {
    "name": "DuckieTV-Standalone",
    "data": "202203281620"
  },
  {
    "name": "NWJS, Chromium",
    "data": "0.62.2 , 99.0.4844.84"
  },
  {
    "name": "UserAgent",
    "data": "DuckieTV-Standalone  Nightly v202203281620 Windows NT 10.0; Win64; x64"
  },
  {
    "name": "Platform, Vendor",
    "data": "Win32, Google Inc."
  },
  {
    "name": "Screen (width x height)",
    "data": "1366 x 768"
  },
  {
    "name": "Default Search Engine",
    "data": "1337x (Enabled)"
  },
  {
    "name": "Default Torrent Client",
    "data": "Tixati (Enabled and Connected to Host)"
  },
  {
    "name": "Auto Download Service",
    "data": "(Enabled and Active)"
  },
  {
    "name": "Last checked TraktTV for DB updates on",
    "data": "Wed, 30 Mar 2022 10:00:09 GMT"
  },
  {
    "name": "User Preferences on Local Storage",
    "data": "{\n  \"ThePirateBay.mirror\": \"https://thepiratebay0.org/\",\n  \"application.language\": \"en_us\",\n  \"application.locale\": \"en_us\",\n  \"autobackup.period\": \"monthly\",\n  \"autodownload.delay\": 15,\n  \"autodownload.multiSE\": {\n    \"ThePirateBay\": true,\n    \"1337x\": true,\n    \"IsoHunt\": true,\n    \"KATcr\": true,\n    \"Nyaa\": true,\n    \"RarBG\": true,\n    \"ShowRSS\": true,\n    \"TorrentDownloads\": true,\n    \"TorrentZ2\": true,\n    \"Zooqle\": true,\n    \"EzTV.ag\": true,\n    \"Idope\": true,\n    \"LimeTorrents\": true,\n    \"SkyTorrents\": true,\n    \"ETag\": true,\n    \"ETTV\": true,\n    \"EXT\": true,\n    \"IsoHunt2\": true,\n    \"KATws\": true,\n    \"TGx\": true\n  },\n  \"autodownload.multiSE.enabled\": false,\n  \"autodownload.period\": 7,\n  \"background-rotator.opacity\": \"0.4\",\n  \"calendar.mode\": \"week\",\n  \"calendar.show-downloaded\": true,\n  \"calendar.show-episode-numbers\": true,\n  \"calendar.show-specials\": false,\n  \"calendar.startSunday\": false,\n  \"client.determinedlocale\": \"en_us\",\n  \"download.ratings\": true,\n  \"episode.watched-downloaded.pairing\": true,\n  \"kc.always\": false,\n  \"lastSync\": -1,\n  \"library.order.by\": \"getSortName()\",\n  \"library.order.reverseList\": [\n    true,\n    false,\n    true,\n    true\n  ],\n  \"library.seriesgrid\": true,\n  \"library.smallposters\": true,\n  \"main.viewmode\": \"calendar\",\n  \"notifications.enabled\": false,\n  \"series.displaymode\": \"poster\",\n  \"series.not-watched-eps-btn\": false,\n  \"storage.sync\": false,\n  \"subtitles.languages\": [\n    \"eng\"\n  ],\n  \"sync.progress\": true,\n  \"synology.enabled\": true,\n  \"synology.ip\": \"192.168.x.x\",\n  \"synology.password\": \"*****\",\n  \"synology.playback_devices\": {},\n  \"synology.port\": 5000,\n  \"synology.protocol\": \"http\",\n  \"synology.username\": \"admin\",\n  \"tixati.password\": \"*****\",\n  \"tixati.port\": 8888,\n  \"tixati.server\": \"http://localhost\",\n  \"tixati.use_auth\": true,\n  \"tixati.username\": \"admin\",\n  \"topSites.enabled\": false,\n  \"topSites.mode\": \"onhover\",\n  \"torrentDialog.2.activeSE\": {\n    \"ThePirateBay\": true,\n    \"1337x\": true,\n    \"IsoHunt\": true,\n    \"KATcr\": true,\n    \"Nyaa\": true,\n    \"RarBG\": true,\n    \"ShowRSS\": true,\n    \"TorrentDownloads\": true,\n    \"TorrentZ2\": true,\n    \"Zooqle\": true,\n    \"EzTV.ag\": true,\n    \"Idope\": true,\n    \"LimeTorrents\": true,\n    \"SkyTorrents\": true,\n    \"ETTV\": true,\n    \"ETag\": true,\n    \"EXT\": true,\n    \"IsoHunt2\": true,\n    \"KATws\": true,\n    \"TGx\": true\n  },\n  \"torrentDialog.2.enabled\": true,\n  \"torrentDialog.2.sortBy\": \"-seedersInt\",\n  \"torrentDialog.showAdvanced.enabled\": true,\n  \"torrenting.autodownload\": true,\n  \"torrenting.autostop\": false,\n  \"torrenting.autostop_all\": false,\n  \"torrenting.client\": \"Tixati\",\n  \"torrenting.directory\": true,\n  \"torrenting.enabled\": true,\n  \"torrenting.global_size_max\": null,\n  \"torrenting.global_size_max_enabled\": true,\n  \"torrenting.global_size_min\": null,\n  \"torrenting.global_size_min_enabled\": true,\n  \"torrenting.ignore_keywords\": \"\",\n  \"torrenting.ignore_keywords_enabled\": true,\n  \"torrenting.label\": false,\n  \"torrenting.launch_via_chromium\": false,\n  \"torrenting.min_seeders\": 100,\n  \"torrenting.min_seeders_enabled\": false,\n  \"torrenting.progress\": true,\n  \"torrenting.require_keywords\": \"\",\n  \"torrenting.require_keywords_enabled\": true,\n  \"torrenting.require_keywords_mode_or\": true,\n  \"torrenting.searchprovider\": \"1337x\",\n  \"torrenting.searchquality\": \"1080p\",\n  \"torrenting.searchqualitylist\": [\n    \"HDTV\",\n    \"720p\",\n    \"1080p\",\n    \"2160p\",\n    \"x265\"\n  ],\n  \"torrenting.streaming\": true,\n  \"trakt-update.period\": 12,\n  \"trakttv.passwordHash\": \"*****\",\n  \"trakttv.sync\": true,\n  \"trakttv.username\": null,\n  \"autodownload.lastrun\": 1648664025798\n}"
  },
  {
    "name": "Other significant Local Storage keys",
    "data": "{\n  \"1.1.4TorrentHashListCleanup\": \"Mon Mar 12 2018 19:46:48 GMT+0200 (South Africa Standard Time)\",\n  \"trakttv.lastupdated.trending\": \"1648663068283\",\n  \"1.1.4refreshTrendingCache\": \"Mon Mar 12 2018 19:46:17 GMT+0200 (South Africa Standard Time)\",\n  \"1.1.4cleanupOrphanedEpisodes\": \"Mon Mar 12 2018 19:46:21 GMT+0200 (South Africa Standard Time)\",\n  \"1.1.5updateDelugeAuth\": \"Mon Mar 12 2018 19:46:17 GMT+0200 (South Africa Standard Time)\",\n  \"1.1.5updateTorrenting.min_seeders\": \"Mon Mar 12 2018 19:46:17 GMT+0200 (South Africa Standard Time)\",\n  \"1.1.6updateQualityList\": \"Mon May 10 2021 17:26:10 GMT+0200 (South Africa Standard Time)\",\n  \"uniqueId\": \"cc5fa84e-ab55-ac9f-e8dc-b350400bbacc\",\n  \"database.version.Series\": \"17\",\n  \"standalone.position\": \"{\\\"width\\\":1364,\\\"height\\\":726,\\\"x\\\":1,\\\"y\\\":1,\\\"state\\\":\\\"maximized\\\"}\",\n  \"standalone.alwaysShowTray\": \"Y\",\n  \"trakttv.lastupdated\": \"1648634409214\",\n  \"database.version.Seasons\": \"7\",\n  \"1.1.4cleanupOrphanedSeasons\": \"Mon Mar 12 2018 19:46:23 GMT+0200 (South Africa Standard Time)\",\n  \"runtime.event\": \"{\\\"reason\\\":\\\"install\\\"}\",\n  \"database.version.Episodes\": \"15\",\n  \"1.1.4qBittorrentPre32\": \"Mon Mar 12 2018 19:46:17 GMT+0200 (South Africa Standard Time)\",\n  \"1.1.5deleteSearchEngines\": \"Mon Mar 12 2018 19:46:17 GMT+0200 (South Africa Standard Time)\",\n  \"fanart.bootstrapped\": \"1\",\n  \"standalone.trayColor\": \"-inverted\",\n  \"database.version.Fanart\": \"1\",\n  \"install.notify\": \"1.1.5\",\n  \"standalone.closeSystray\": \"Y\",\n  \"standalone.minimizeSystray\": \"Y\",\n  \"upgrade.notify\": \"1.1.5\",\n  \"autobackup.lastrun\": \"1648749514000\",\n  \"1.1.4updateTransmissionPath\": \"Mon Mar 12 2018 19:46:17 GMT+0200 (South Africa Standard Time)\",\n  \"1.1.5FetchFirstXemAliasMap\": \"Mon Mar 12 2018 19:46:17 GMT+0200 (South Africa Standard Time)\",\n  \"standalone.zoomlevel\": \"6\",\n  \"xem.lastFetched\": \"1648660109303\",\n  \"database.version.Jackett\": \"2\",\n  \"github.lastupdatecheck\": \"1520876781528\",\n  \"snrt.lastFetched\": \"1648663055024\",\n  \"1.1.5fanartCleanup\": \"Mon Mar 12 2018 19:46:49 GMT+0200 (South Africa Standard Time)\",\n  \"1.1.6TPBorgto0org\": \"Mon May 10 2021 17:26:10 GMT+0200 (South Africa Standard Time)\",\n  \"trackers.lastFetched\": \"1648072804546\",\n  \"standalone.startupMinimized\": \"Y\",\n  \"1.1migration\": \"Mon Mar 12 2018 19:46:21 GMT+0200 (South Africa Standard Time)\",\n  \"1.1.6TraktSceneTables\": \"Mon May 10 2021 17:26:10 GMT+0200 (South Africa Standard Time)\",\n  \"1.1.6deleteWatchList\": \"Mon May 10 2021 17:26:10 GMT+0200 (South Africa Standard Time)\",\n  \"torrenting.client\": \"Tixati\",\n  \"1.1.4refresh\": \"Mon Mar 12 2018 19:46:27 GMT+0200 (South Africa Standard Time)\",\n  \"trakttv.refresh_token\": \"9ccf5cd926de52ef8eadc4adedc3dad9956d78f1182e75586fd48c2a244c41f1\"\n}"
  },
  {
    "name": "DB Series",
    "data": 103
  },
  {
    "name": "DB Series Hidden From Calendar",
    "data": 0
  },
  {
    "name": "DB Seasons",
    "data": 432
  },
  {
    "name": "DB Episodes",
    "data": 6844
  },
  {
    "name": "DB Fanart",
    "data": 2201
  },
  {
    "name": "DB Jackett",
    "data": 0
  }
]

**Comment by garfield69** [comment]
What version of tixati are you using?
I will test that version on my dev sandbox when I get some free time later today.
Thanks.

**Comment by garfield69** [comment]
Hmmm. just tried out Tixati 2.81 with Dtv and its working OK.
So then I upgraded to Tixati 2.89 and and I see what you reported. The magnet is sent by Dtv to Tixati, and Tixati completed the download. However, as you reported, Dtv does not find the torrent on the Tixati interface and therefore does not report the progress or the completion.
Clearly there has been an update to the Tixati API and I shall now endeavour to figure out what needs to change to help Dtv talk to the new Tixati release.

**Comment by garfield69** [comment]
backtracking Tixati versions, the interface breaks starting with Tixati version 2.86
The changelog for that version includes `major overhaul of WebUI` so this gives me a starting point ;-)

**Comment by garfield69** [comment]
Code amended, testing looks good in the sandbox. I shall now prepare the next release of the nightly and test the new standalone Dtv. If good then I'll publish and post here when its available.

**Comment by garfield69** [comment]
https://github.com/DuckieTV/Nightlies/releases/tag/nightly-202203311736
