### ISSUE TITLE
Chrome Browser v101.* breaks Dtv calendar

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#1350]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Browser Action

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
3022.3.31.1057

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 10 / Ubuntu 21

**Describe the problem you are having and steps to reproduce if available**
As reported by https://www.reddit.com/r/duckietv/comments/ud0cti/clickable_shows/
The calendar page appears to have no focus. You cannot get a response by clicking the calendar date navigations, or the episode links in the calendar day boxes. The Action bar on the left works, as do all the side panels.

I installed and checked the latest browseraction 3022.3.31.1057 with Chrome 100.0.4896.127 and it was working fine.

Then chrome told me a chrome upgrade was available, and after it finished the relaunch I now get the same problem.

So it has something to do with Chrome Browser 101.0.4951.41
The TODO view is similarly affected.
Same from Chrome Browser 101 on Ubuntu 21
Not just 101, I tested ChromeDev 103 and this also breaks Dtv.

But I have absolutely know idea what the issue is. @Js41637 Help!!

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
by editing the tab.html and pulling out directives I have narrowed down the generators of the issue.
I can get the calendar to work by removing the series-list and clicktrap directives.
Put either one or both back in and we break the calendar.
@Js41637  are you available? can you provide some insight as to why these two directives are causing an issue with chromium 101 ?
In the meantime I will continue gnawing away at those two directives' content until something smacks me in the face.

**Comment by garfield69** [comment]
Hmm. the clicktrap directive has a css table that include `z-index: 100`
by removing this I can get the directive to exist with the calendar.
So the question is, what is a z-index, does it need to be there, should its value be higher or lower that some other z-index related to the calendar (and if so which, there are 26 in the main.css file)?
Presumably the series-list directive has a similar z-index value that clashes with the calendar.
investigation and research continues.

**Comment by Js41637** [comment]
Chrome 101 seems to have made some breaking changes to how zindex works, i can easily resolve it but it does break the sidebar closing.

**Comment by garfield69** [comment]
oh good, you're here! :-) I'll step back and let you work your magic. Thanks.

**Comment by Js41637** [comment]
Well, it's a simple fix. Very odd though, couldn't find any info about it, chrome definitely seems to have broken something.
Should be resolved though?

**Comment by Js41637** [comment]
I don't know if this was always the case but, the click trap doesn't work that great when the sidepanel is open. Due to the way the calendar is shrunk when the sidepanel is open the actual display area for the element is still essentially it's original size which means clicking below the calendar won't close the sidebar even though it looks like it should. You need to click considerably lower. 

I tested some stuff for a few minutes but couldn't figure out a quick solution. Still works though so it's not too bad.

**Comment by garfield69** [comment]
works well enough for me so I'll generate a build.
Thank You.

**Comment by IAmHugh001** [comment]
Switch to Vivaldi where you will be much happier. No DTV issues with downloading the nightly builds and loading unpacked extensions.

**Comment by garfield69** [comment]
@Locutus64  Vivaldi is a chromium based browser. While the current release 5.2.2623.41 is using chromium 100 you will continue to have no issues with Dtv, however, when they next push their update to include chromium 101 then you too will have a broken Dtv calendar. 
So no, in this instance, switching to Vivaldi is a temporary fix, without d01e1f556a2cc31b9387febb37931c389e1bb6b to correct the issue.

**Comment by IAmHugh001** [comment]
Thanks for the heads up. I'll create a post on the Vivaldi forums to see if they can address this before they release their update based on Chrome 101. I use Vivaldi cause they go out of their way to remove code google adds to invade your privacy. current next to Tor Vivaldi is probably the most privacy centric browser out there. Vivaldi and Vivaldi - Snapshot are the only browsers that I have DTV in.

**Comment by garfield69** [comment]
@Locutus64  or you could just update Dtv from https://github.com/DuckieTV/Nightlies/releases/latest
