### ISSUE TITLE
rarbg: distinguish "no results" from rate limited

### ISSUE THREAD

**Issue by geekman** [SchizoDuckie/DuckieTV#1355]
DuckieTV browser action V3022.6.8.1030

When using the rarbg search engine, it sometimes returns "No results", even though I know this is not true.

Monitoring the network requests, I can see that response is `{"error":"No results found","error_code":20,"rate_limit":1}`, whereas a _real_ "no results" request would not have the `rate_limit:1` property in the response at all.

Reading the code, it looks like this condition is not handled as rate-limited:
https://github.com/SchizoDuckie/DuckieTV/blob/2331269a83be5dee380eb592d4b636b3c73c0a41/js/services/TorrentSearchEngines/RarBG.js#L34-L45

I haven't looked at the code too deeply, but I believe an additional check for `"rate_limit" in result.data` and returning `5` should kick it into the retry-later logic.

**Comment by garfield69** [comment]
Nice find.  I will add this enhancement in the next build.

**Comment by garfield69** [comment]
https://github.com/DuckieTV/Nightlies/releases/latest 202206090737
