### ISSUE TITLE
TorrentDownloads SE not working.

### ISSUE THREAD

**Issue by dadrepus** [SchizoDuckie/DuckieTV#1356]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...
Standalone build 202206110939
**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...
[DuckieTV/Nightlies] Release nightly-202206110939 - Nightly release for 11-06-2022 09:39:00 (nightly-202206110939
**What is your Operating System (Windows, Mac, Linux, Android)**
...
Mac Mojavi
**Describe the problem you are having and steps to reproduce if available**
...
Click on a link to start download to transmission , pop-up says it is started but nothing shows up in Transmission.
**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
was it working previously or is this a new set up?
what version of transmission are you using, has transmissions been updated recently?

**Comment by garfield69** [comment]
also what is the Dtv search engine you are using?
I want to replicate your test on my sandbox so I can check a few things out.
Thanks.

**Comment by dadrepus** [comment]
Everything was working 2 days ago. Installed the current osx build-nightly, Transmission 3.0 (current), searchengine torrentdownloads. So I do get a lists of torrents available for download but when clicking any of the icon on the left whether it is a magnet link or not, a notification says torrent has been sent to transmission but nothing shows up in transmission’s Q.

**Comment by garfield69** [comment]
Dtv Nightly 202206110939 with Transmission 3.00 on my win10 seems to be working fine. I used 1337x as my SE and downloaded without issues.

I will wait for more info from you before continuing further.

**Comment by garfield69** [comment]
I'm having issues accessing  torrentdownloads with my browser. 
as a test, switch to another SE and see if the problem persists.

**Comment by dadrepus** [comment]
Just changed to your search engine and got a download of “the boys” started. so, that was the problem.

**Comment by garfield69** [comment]
yes torrentdownloads is suffering from Error 520 Web server is returning an unknown error
while the web site returns some search results, when it comes to downloading the torrent/magnet Dtv gets presented with a HTML page instead of the torrent meta file.
I recommend using another SE for now until torrentdownloads is back online again.

**Comment by dadrepus** [comment]
I have no preference so I’ll continue to use your suggestion, thanks. Really quick response from you. I appreciate that. It is 1:15 AM here, I’m an insomniac.
Regards,
Alex
