### ISSUE TITLE
can not add tv show

### ISSUE THREAD

**Issue by lapd87** [SchizoDuckie/DuckieTV#1360]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
**What is your Operating System (Windows, Mac, Linux, Android)**

![image](https://user-images.githubusercontent.com/32339696/186110476-ca46d990-d5ed-445b-878a-87e0b46a8d56.png)

**Describe the problem you are having and steps to reproduce if available**
can not add tv show "I am Groot"

**Attach any DuckieTV statistics or Developer Console logs if available**
api.trakt.tv/shows/170563/seasons?extended=full:1 Failed to load resource: the server responded with a status of 404 ()
app.js:9815 Error adding show! Error 404:
(anonymous) @ app.js:9815
app.js:4639 Uncaught (in promise) TypeError: Cannot read property 'ID_Serie' of undefined
    at app.js:4639
(anonymous) @ app.js:4639
api.trakt.tv/shows/170563/people:1 Failed to load resource: the server responded with a status of 404 ()

**Comment by garfield69** [comment]
Unfortunately this is an issue at the trakt.tv side.
See this:
https://trakt.tv/search?query=i+am+groot
the first three are the tv series that show up in the Dtv add-a-show search panel that you tried to use to add to dtv.

But if you use the web site and click on any of the first 3 shows you get the 404 not found just like Dtv does.
it looks like trakt.tv has also got the first 5 episodes loaded individually as movies ;-( 
However Dtv is TV only, so you cannot load these movies to your Dtv collection.

There is nothing can be done about this on the Dtv side, effectively, there are no active tv shows loaded on trakt.tv  for the `I am Groot` shows.

The TMDB has these 5 eps loaded as individual  movies https://www.themoviedb.org/search?query=i+am+groot and this is the source that trakt.tv uses to start its DB aggregate from.

The tvdb has them as a 5 episode season https://thetvdb.com/series/i-am-groot/seasons/official/1 but trakt.tv is not using this information.

The trakt.tv forum has one topic https://support.trakt.tv/support/search/topics?term=i+am+groot

You might like to raise a query on the trakt.tv help site, https://support.trakt.tv/support/solutions, by login in you could raise a ticket and see if you get someone to load a tv series for the show.
