### ISSUE TITLE
How to set a default download location/folder for episodes for supported clients

### ISSUE THREAD

**Issue by Infallibleman** [SchizoDuckie/DuckieTV#1363]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
v202206262021

**What is your Operating System (Windows, Mac, Linux, Android)**
Mac

**Describe the problem you are having and steps to reproduce if available**
Have to set up a folder location for every single show added to my favorites. Is it possible to provide an option in settings to choose a default location? e.g. (/home/plex/tv_shows).

I have Transmission BT and would love to have the shows drop there by default for plex to sort/parse and present.

**Attach any DuckieTV statistics or Developer Console logs if available**
n/a

**Comment by garfield69** [comment]
Dtv does not readily have a mechanism for this, and implementing it would be a lot of work.

However I can suggest the following commands that you can tailor to suit your needs, if you are looking to bulk change the dlPath or even selectively update the dlPath if one is not already set for future updates.

To run these commands , access the _DevTools_ page ( **Cmd-Alt-I** or if that does not work then **right-click** on the dtv home page and select **inspect** ) and **click** on the _Console_ tab to view the log and at the `>` prompt paste your command and press enter to execute.

- to replace all the dlPath for every series regardless of previous value
`CRUD.executeQuery("update Series set dlPath = '/home/plex/tv_shows' ").then(function(result) { console.log(result); })`

- to erase all the dlPath for every series
`CRUD.executeQuery("update Series set dlPath = null ").then(function(result) { console.log(result); })`

- to only update the dlPath for series that do not have one already set
`CRUD.executeQuery("update Series set dlPath = '/home/plex/tv_shows' where dlPath is null").then(function(result) { console.log(result); })`

- to update the dlPath for series where dlPath is set to a specific value
`CRUD.executeQuery("update Series set dlPath = '/home/plex/tv_shows' where dlPath == '/home/old/tv_shows' ").then(function(result) { console.log(result); })`

I suggest you avoid using these commands while the _updating series dialog_ is active on the main page.

Let me know how you get on.

**Comment by Infallibleman** [comment]
Thank you sooo much.  It worked perfectly!!

Thank you :)

On Sep 3, 2022, at 5:35 PM, garfield69 ***@***.***> wrote:


Dtv does not readily have a mechanism for this, and implementing it would be a lot of work.

However I can suggest the following commands that you can tailor to suit your needs, if you are looking to bulk change the dlPath or even selectively update the dlPath if one is not already set for future updates.

To run these commands , access the DevTools page ( Cmd-Alt-I or if that does not work then right-click on the dtv home page and select inspect ) and click on the Console tab to view the log and at the > prompt paste your command and press enter to execute.

to replace all the dlPath for every series regardless of previous value
CRUD.executeQuery("update Series set dlPath = '/home/plex/tv_shows' ").then(function(result) { console.log(result); })

to erase all the dlPath for every series
CRUD.executeQuery("update Series set dlPath = null ").then(function(result) { console.log(result); })

to only update the dlPath for series that do not have one already set
CRUD.executeQuery("update Series set dlPath = '/home/plex/tv_shows' where dlPath is null").then(function(result) { console.log(result); })

to update the dlPath for series where dlPath is set to a specific value
CRUD.executeQuery("update Series set dlPath = '/home/plex/tv_shows' where dlPath == '/home/old/tv_shows' ").then(function(result) { console.log(result); })

I suggest you avoid using these commands while the updating series dialog is active on the main page.

Let me know how you get on.
