### ISSUE TITLE
Trying to view torrent details from the pirate bay will output a URL that contains the domain twice

### ISSUE THREAD

**Issue by mqjasper** [SchizoDuckie/DuckieTV#1364]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
DuckieTV Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
DuckieTV Nightly V202209031611

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows

**Describe the problem you are having and steps to reproduce if available**
When searching for any torrents via the pirate bay, if I want to view the torrent details it will output the mirror domain twice, for example "https://thepiratebay0.org/https://thepiratebay0.org/torrents". It is only the second-level, i.e. "https://thepiratebay0.org/" that appears twice in the url. So far I haven't had any issues with any other search engines, so it's likely something to do with the way DuckieTV resolves the URL from mirrors.

**Comment by garfield69** [comment]
Confirmed.  Thanks.
There is a internal setting for the SE that needs to be flipped to stop it adding the base path to the details link.
In the next free period I'll build a new release and post here when I'm done.

**Comment by garfield69** [comment]
https://github.com/DuckieTV/Nightlies/releases/tag/nightly-202209261911
