### ISSUE TITLE
DuckieTV extremely slow and sluggish running on a MacOS

### ISSUE THREAD

**Issue by Infallibleman** [SchizoDuckie/DuckieTV#1368]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
v202209031611

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Nightly

**What is your Operating System (Windows, Mac, Linux, Android)**
MacOS Catalina

**Describe the problem you are having and steps to reproduce if available**
Running on a MACOS VM.  Only the DuckitTV interface is extremely slow and sluggish to respond.  The rest of the VM and apps respond perfectly fine.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
The standalone Dtv is essentially just JavaScript calling chromium API functions, and encapsulated by the NWJS run time environment (https://github.com/nwjs/nw.js)  which provides the chromium headless browser that runs the Dtv JS.
So graphics presentation is managed by chromium and NWJS, and is outside of Dtv control.

NWJS has this https://github.com/nwjs/nw.js/commit/cfc8c12b1a7c667b0b42c7070da53c2bf4146e64
but I don't know if its relevant, and it has not been released yet (nwjs 0.68.?)
Dtv is using nwjs 0.67.1 atm
Once NWJS release the fix I'll upgrade the dtv build to include it and we shall see if it helps.

macos vm. not sure I understand how you are running dtv. 
you are running catalina, and then start a vm of what os, under which you run Dtv?
Can you expand and what the set up is that you run dtv under please? thanks.

**Comment by garfield69** [comment]
it does appear that https://github.com/nwjs/nw.js/issues/7715 matches your findings about macos nwjs being slow to render.
so now we wait for the next release to include https://github.com/nwjs/nw.js/commit/cfc8c12b1a7c667b0b42c7070da53c2bf4146e64 and I'm hopeful things will return to normal when I get to incorporate the new nwjs into the Dtv standalone builds.

**Comment by Infallibleman** [comment]
> macos vm. not sure I understand how you are running dtv.
you are running catalina, and then start a vm of what os, under which you run Dtv?
Can you expand and what the set up is that you run dtv under please? thanks.

I have the Mac OS running as a virtual Machine on an Vmware esxi hypervisor.  So its a virtual Mac OS environment.  

- Apple Mac Pro 2013 (6-CPU Intel Xeon, 32GB RAM) running Vmware Esxi hypervisor OS instead of Mac OS
- Created the MacOS Catalina VM on the hypervisor (4 cores, 6 GB RAM, 200 GB HD)
- Duckie TV, VPN, TorrentBT installed on the VM.  

This is where Duckie TV is the most sluggish.  I don't know if there are any logs I can collect with the click-to-act timers which might help in figuring out what the issue could be.

**Comment by garfield69** [comment]
https://github.com/DuckieTV/Nightlies/releases/tag/nightly-202209301924 is now available
this package includes NWJS 0.69.0 which claims to have the performance fix for macos.
Remember, before running the installer, use your file manager to access the applications folder and drag the DuckieTV to the bin.
Otherwise the installer will silently fail to replace the old Dtv with the new one.
Check the (i) About side panel to confirm on the header that the version is as advertised.
Let me know how it goes.

**Comment by Infallibleman** [comment]
THIS WORKS AMAZING !!!

Thank you so much for this update. Really do appreciate it :)



On Sep 30, 2022, at 1:49 AM, garfield69 ***@***.***> wrote:


https://github.com/DuckieTV/Nightlies/releases/tag/nightly-202209301924 <https://github.com/DuckieTV/Nightlies/releases/tag/nightly-202209301924> is now available
this package includes NWJS 0.69.0 which claims to have the performance fix for macos.
Remember, before running the installer, use your file manager to access the applications folder and drag the DuckieTV to the bin.
Otherwise the installer will silently fail to replace the old Dtv with the new one.
Check the (i) About side panel to confirm on the header that the version is as advertised.
Let me know how it goes.
