### ISSUE TITLE
Duckie TV GUI is not showing up

### ISSUE THREAD

**Issue by Infallibleman** [SchizoDuckie/DuckieTV#1370]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Latest Nightly as of today (Cannot access as GUI is not showing up)

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
nightly (Cannot access as GUI is not showing up)

**What is your Operating System (Windows, Mac, Linux, Android)**
macos High Sierra

**Describe the problem you are having and steps to reproduce if available**
1. launch Duckie TV
2. icon shows up on the dock
3. no icon in the task bar at the top
**4. does not display the duckie tv GUI**

**Attach any DuckieTV statistics or Developer Console logs if available**
Cannot access as GUI is not showing up (screenshot attached)
![DuckieTV_No_GUI](https://user-images.githubusercontent.com/36009107/199259934-c0be5204-8a6b-451c-9e51-4df7ed57018c.jpg)

**Comment by garfield69** [comment]
I am sorry, but the 3rd party product [NWJS](https://nwjs.io/) (which is the run time environment that Dtv Standalone uses to be able to run its JavaScript as a chromium extension) only supports macOSx 10.15 and newer, starting the NWJS 0.64.1
something to do with a node.js v18.0.0  requirement.
refer https://github.com/nwjs/nw.js/issues/7946 and https://github.com/nwjs/nw.js/issues/7874
Dtv currently uses NWJS to 0.69.0 with Chromium 106

the last Dtv nightly that may still be High Sierra compatible would probably be [202205291631](https://github.com/DuckieTV/Nightlies/releases/tag/nightly-202205291631)
