### ISSUE TITLE
EPISODES BEING MISSED BY DUCKIETV

### ISSUE THREAD

**Issue by geordon49** [SchizoDuckie/DuckieTV#1373]
STANDALONE V202206140857 WINDOWS 10

The series Highway Thru Hell has released S11E11 E12 E13 within the last week but they are not showing up in Duckie. I would like to enter them so that they DO NOT run if they do evenutally get listed. I know that if the episode shows I can mark it as being captured but these episodes do not show at all

**Comment by garfield69** [comment]
Refer https://www.reddit.com/r/duckietv/comments/zk52qw/trakttv_is_offline_for_maintenance_which_means/
