### ISSUE TITLE
Unable to search for new shows/ contact TRAKT.TV

### ISSUE THREAD

**Issue by v643179** [SchizoDuckie/DuckieTV#1374]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...Nightly v202104302304

**What is your Operating System (Windows, Mac, Linux, Android)**
...Windows 10 

**Describe the problem you are having and steps to reproduce if available**
...Unable to search for new shows.  I get "THERE WAS AN ERROR CONTACTING TRAKT.TV.  IT MIGHT BE DOWN. PLEASE TRY AGAIN LATER

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by ilike2burnthing** [comment]
https://github.com/SchizoDuckie/DuckieTV/issues/1373
