### ISSUE TITLE
Duckie Tv won't add shows to favorites - Get the Red "Sad Face" Emoji when I click plus

### ISSUE THREAD

**Issue by Infallibleman** [SchizoDuckie/DuckieTV#1375]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Nightly Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...
202209301924

**What is your Operating System (Windows, Mac, Linux, Android)**
...
Mac

**Describe the problem you are having and steps to reproduce if available**
...
When I click on 'Plus" button to add a show, I get the sad face emoji. 

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
https://github.com/SchizoDuckie/DuckieTV/issues/1373
