### ISSUE TITLE
TV SHOW NAME DIFFERENCE

### ISSUE THREAD

**Issue by geordon49** [SchizoDuckie/DuckieTV#1376]
STANDALONE V202206140857 WINDOWS 10

The show is called MARKETPLACE but Duckietv looks for CBC MARKETPLACE therefore it does not ever find it. Would it be possible to have DUCKIETV change its search criteria ??

...

**Comment by garfield69** [comment]
I've updated the sceneNameException table.
Your Dtv should fetch the update within the next 24 hours, after which it should start searching for marketplace without the cbc prefix.
