### ISSUE TITLE
Question about response I just received

### ISSUE THREAD

**Issue by geordon49** [SchizoDuckie/DuckieTV#1377]
I recd reply saying that my PC was not recognized. I have gone thru several requests in the past with
no issue. I dont know where to enter the verification code on the unrecognized device.

**Comment by garfield69** [comment]
I doubt this has anything to do with Dtv or GitHub.
Take a closer look at that reply, where its from and what it is asking you to do.
I suspect that it is Gmail doing a security check, and you will need to access your gmail account to complete the verification.
