### ISSUE TITLE
[github] "nightly" marked as "latest release" instead of as "pre-release"

### ISSUE THREAD

**Issue by core-code** [SchizoDuckie/DuckieTV#1383]
the release "Nightly release for 12-03-2023" should be marked as "pre-release" in GitHub. thanks!

**Comment by garfield69** [comment]
why?

**Comment by core-code** [comment]
a "nightly" is a random prerelease not a stable official release?

**Comment by garfield69** [comment]
As you may know, the author of DuckieTV left the project back in 2017 and there is currently no official DuckieTV publishing mechanism.
The Nightly releases, which was once a fully automated beta release builder no longer generates daily releases.
I keep the lights on in this project by manually publishing a Dtv release via the nightly stream, as this is the only way I have to release  a Dtv Standalone package.
So effectively, my Nightly release is a stable release and not a beta ;-)
