### ISSUE TITLE
auto backup problem in standlone version

### ISSUE THREAD

**Issue by Divyang1304** [SchizoDuckie/DuckieTV#1388]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...
standlone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...
Nightly yyyymmddHHMM

**What is your Operating System (Windows, MacOSx, Linux)**
...
Windows

**Describe the problem you are having and steps to reproduce if available**
...
when I changed the auto backup setting from monthly to weekly, most of my data got wiped out and it not loading any shows.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
Please provide some more info:
- Go to dtv>(i)About DuckieTV 
- and on that side panel scroll down to the **Statistics** section
- Click on that header which should copy the stats to your clipboard
- Open a blank plain text editor and paste and save the file as stats.txt or whatever, 
- then drag/drop the file here.
Avoid pasting the clipboard straight into a comment box here, we've had github lockout users for spamming before.

Thanks.
