### ISSUE TITLE
Marked as trojan

### ISSUE THREAD

**Issue by cajeiri** [SchizoDuckie/DuckieTV#1389]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Latest current nightly (standalone, Windows 64)

**What is your Operating System (Windows, MacOSx, Linux)**
Windows 10

**Describe the problem you are having and steps to reproduce if available**
DuckieTV gets marked as the following Trojan - Win32/Wacatac.B!ml.

**Comment by cajeiri** [comment]
@garfield69 Probably a false positive, but fyi.

**Comment by garfield69** [comment]
Yes, very likely a false positive.
I've loaded DuckieTV-202304280702-windows-x64.zip to virustotal, and only 1 of 62 engines flagged a hit
https://www.virustotal.com/gui/file/20c8f4bd9a3662d72b869dc58408c188cce0683a42fff70481d40411ca8343af
as does the x32 version
https://www.virustotal.com/gui/file/ebe3174a5b1ffc3102023593f515652be2eb002cc25ef40bd4a5cc359f029028
the OSX version passed clean
https://www.virustotal.com/gui/file/76e60f3e3a1b839a215a349704e5eb87006b859e68dd2394b90e660becf78f6d?nocache=1
as does the linux version
https://www.virustotal.com/gui/file/d9fab588aaca4051f54318adb71b633dc5951e562bbdca695954f8254010b621?nocache=1
FYI Dtv is written in JavaScript. Its the platform specific run time environment NWJS that encapsulates the JS to provide the standalone exe that triggers the false hit.
