### ISSUE TITLE
Favorites Not showing

### ISSUE THREAD

**Issue by jriker1** [SchizoDuckie/DuckieTV#1394]
DuckieTV for Windows.  Nightly build and just checked but no updates.  Been a while since this worked but when I click on Favorites it is blank.  I can sometimes get it back again by rebooting but then hours later gone.

Also side issue, adding a new program in this case Celebrity Family Feud, it won't search for shows and if I click on an episode and click to manual download nothing pops up to search.  When I go to another existing one that pops up a search and starts looking for episodes.

**Comment by garfield69** [comment]
Please go to the DTV About page (its the (i) icon near the left hand bottom on main page), scroll to the statistics section, click on the statistics header to copy the stats to your clipboard, and paste it into a plain text file and save. then drag/drop the file here so I can have a look. Thanks.

**Comment by jriker1** [comment]
[duckietv.txt](https://github.com/SchizoDuckie/DuckieTV/files/12059598/duckietv.txt)

**Comment by garfield69** [comment]
Regarding Celebrity Family Feud, the problem there is that the Trakt.tv record does not have a TVDBID, which DTV needs for theXem.info lookups. Easy to fix, because I maintain a table to provide the tvdbid when trakt.tv does not provide one. This will fix the searching failing.  I'll update when I get back.

As for the favourites being blank, can I confirm that by favourites you mean you click on the heart icon and that page is empty?
If that is the case, check the filters at the top of that page. You may have some filters enabled/disabled that are causing no results to be returned.
Let me know what you find.

I've go to go right now, but I will resume working on this when I get back in 4 hours or so.

**Comment by garfield69** [comment]
So assuming that I've read your stats correctly, then in a couple hours from this post your Dtv should be scheduled to refresh its SceneNameTables, after which, if you visit your Celebrity Family Feud series details page and click on it's refresh button, Dtv should then become aware of the tvdbid for that series and searches should start working.
You can confirm that you have the tvdbid when your series details page has a link for **TVDB** present, as in this example
![image](https://github.com/SchizoDuckie/DuckieTV/assets/6933240/5feabba9-3c9d-4283-8d62-fd7fe943d01f)

As for the favourites, check that none of the **Status** and **Genre** filters have been checked.
This is the most common reason for not seeing any series in your favourites.
Let me know how you get on.

**Comment by jriker1** [comment]
Thanks getting better with Celebrity Family Feud.  So now can search.

But odd part if you hover over the search button will show S09E02
![image](https://github.com/SchizoDuckie/DuckieTV/assets/1495536/594c56d5-c8d0-4a35-b077-8dc1bcb0dfc6)

But when I search is searching on S08E02.  So season 8 not season 9.
![image](https://github.com/SchizoDuckie/DuckieTV/assets/1495536/6a9354b9-0585-48a2-9afa-546f706bbc76)

Not that there are any to find yet but still.

**Comment by garfield69** [comment]
Yes. Celebrity Family Feud is one of those series where the TVDB and the torrent scene disagree about what the name of the episode being broadcast should be called.
Dtv uses thexem.info to reconcile these discrepancies. If you look at https://thexem.info/xem/show/4363 you can see the table where season 9 TVDB is mapped to season 8 of the torrents names.

**Comment by garfield69** [comment]
So have you got the favourites page back to normal?

**Comment by jriker1** [comment]
To be honest not sure I get the logic of ever using S08 for these as the show is seemingly on Season 9.  So would assume any torrents that are the right ones to download will be S09 and going after S08E02 will return the second episode from last year.

https://abc.com/shows/celebrity-family-feud

With Favorites, at the moment it's working.  I didn't change anything.

**Comment by garfield69** [comment]
The problem with CFF was that when It started back in 2008 it lasted just one season.
When it was restarted in 2015, TVDB just continued counting seasons by including the 2008 season.
But the people that upload the torrents started afresh with the first season of 2015 as season 1.
This is why the season management of CFF is a mess.
