### ISSUE TITLE
Says downloading but isn't

### ISSUE THREAD

**Issue by jriker1** [SchizoDuckie/DuckieTV#1395]
On Windows DTV stopped downloading but keeps saying it is.  So for example:
![image](https://github.com/SchizoDuckie/DuckieTV/assets/1495536/cfefea06-2395-4c42-b6bf-96140bc0c975)

Not sure if you can see on Saturday.  Says Torrent Launched but there is no indicator on the calendar and in qBittorrent not there.  Same with Star Trek downloading to the left of it.  Said it was downloading but it isn't.  I manually searched in DTV for it and selected one which started the download.

**Comment by garfield69** [comment]
This usually happens when Dtv sends the torrent link provided by the default search engine you have chosen to use for the autodownload to your torrent client, but for some reason the client has not managed to resolve the link or has rejected the link for whatever reason.
Which Jackett indexer are you using?
I will see if I can replicate in on my dev machine to try figure out what might be going on.

**Comment by garfield69** [comment]
Also, press F12 to open the development tools page and click on Console to view the log. See if you can find the torrent info used for the episode that was sent to your client. There may be just a magnet or torrent sent message, or perhaps a error message related to the event.

**Comment by jriker1** [comment]
I have about 15 indexers in Jackett but can't be sure it's using Jackett in a specific download selection vs one that's integrated into DTV.

There is a lot of this in the conole if that matters:

```
t read properties of null (reading 'toString')
    at Object.getEpisodeMapping (app.js:11057:43)
    at Object.getSearchStringForEpisode (app.js:10902:35)
    at Object.findEpisode (app.js:16492:34)
    at $scope.openDialog (app.js:7494:40)
    at deps.js:2470:354
    at e (deps.js:2401:262)
    at m.$eval (deps.js:2358:239)
    at m.$apply (deps.js:2358:482)
    at HTMLAnchorElement.<anonymous> (deps.js:2401:347)
    at og (deps.js:2244:158)
(anonymous) @ deps.js:2331
deps.js:2331 Possibly unhandled rejection: backdrop click
(anonymous) @ deps.js:2331
app.js:4701 [SerieRefresh] [TRAKT_ID=98945] updating Celebrity Family Feud
app.js:11036 Xem has episode s09e02 for Celebrity Family Feud (295604), using mapped format. Object
deps.js:17940 Invalid torrent identifier
parseTorrent @ deps.js:17940
2deps.js:2331 Possibly unhandled rejection: escape key press
(anonymous) @ deps.js:2331
app.js:9133 Uncaught TypeError: Cannot read properties of null (reading 'info')
    at decodeTorrentFile (deps.js:18638:36)
    at parseTorrent (deps.js:17925:32)
    at parseOrThrow (deps.js:17998:45)
    at deps.js:17980:29
    at deps.js:19502:29
    at exports.IncomingMessage.<anonymous> (deps.js:19365:29)
    at exports.IncomingMessage.g (deps.js:11905:34)
    at EventEmitter.emit (deps.js:11833:38)
    at endReadableNT (deps.js:14726:32)
    at afterTickTwo (deps.js:12521:32)
deps.js:2331 Possibly unhandled rejection: backdrop click
(anonymous) @ deps.js:2331
deps.js:17940 Invalid torrent identifier
parseTorrent @ 
```

When I search I see:

    
        
 ```
      GET https://extratorrent.st/search/?search=Celebrity%20Family%20Feud%20s08e02&srt=seeds&order=desc&new=1&x=0&y=0 403
(anonymous) @ app.js:371
s @ deps.js:2312
(anonymous) @ deps.js:2309
(anonymous) @ deps.js:2344
$digest @ deps.js:2355
$apply @ deps.js:2359
(anonymous) @ deps.js:2401
og @ deps.js:2244
d @ deps.js:2244
app.js:371 
        
        
       GET https://idope.se/torrent-list/Celebrity%20Family%20Feud%20s08e02/?&o=-1 403
(anonymous) @ app.js:371
s @ deps.js:2312
(anonymous) @ deps.js:2309
(anonymous) @ deps.js:2344
$digest @ deps.js:2355
$apply @ deps.js:2359
(anonymous) @ deps.js:2401
og @ deps.js:2244
d @ deps.js:2244
tab.html#!/episode/4760:1 <link rel=preload> must have a valid `as` value
tab.html#!/episode/4760:1 <link rel=preload> must have a valid `as` value
```

**Comment by garfield69** [comment]
According to your settings, autodownload uses the default search engine that you have labelled Jackett.
The `Invalid torrent identifier` may be a clue to why the link sent by Dtv to qBt might be no good.
As for the manual Dtv torrent search dialogue, you have chosen to use the Multi-SE dialogue, so you will get a search using all the internal SE plus the default one you set up on Dtv to access Jackett. 
But many of the internal SE ( for instance Idope, EXT) use cloudflare DDoS protection, and Dtv does not have flaresolverr like Jackett, so those SE do not work on Dtv.

can you access the Dtv settings>Jackett and view your SE definition to identify in the URL what JAckett indexer you are actually using?

**Comment by garfield69** [comment]
Can you access your Dtv settings>Jackett and view your Dtv Jackett Search Engine (SE) definition to identify in the URL which Jackett indexer is being used? Just click on *edit* and the URL will look something like 
`http://127.0.0.1:9117/api/v2.0/indexers/<indexernamehere>/results/torznab/`

If you are using the **all** (aggregate indexer) then provide instead a list of the active indexer names in your Jackett dashboard page so I can test each one to see which of them is returning a link that Dtv cannot pass on to your qBt.
