### ISSUE TITLE
The display of DTV it's all wrong

### ISSUE THREAD

**Issue by DirtySkeMe** [SchizoDuckie/DuckieTV#1401]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Chrome Extension Browser Action

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
nightly-3023.8.13.708
**What is your Operating System (Windows, MacOSx, Linux)**
Chromebook

**Describe the problem you are having and steps to reproduce if available**

didn't use it for a few days when i reopen it it's all i can see

https://img001.prntscr.com/file/img001/sXUZOyInTOmLIhKFaMkjRA.png

i didn't try to reinstall it yet

)**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
Press **F12** to open the development tools page and click on the **console** tab to view the log.
Any trak.tv errors or other error messages?

**Comment by DirtySkeMe** [comment]
a css error not found any idea to just add the css without reinstall everything

**Comment by garfield69** [comment]
that is strange. which css in particular?
You could simply unpack the latest Dtv nightly zip file and copy all the files/folders  over the top of your current Dtv folder, then go to the chromium extensions manager and click the refresh for the Dtv extension to reload the files.

**Comment by DirtySkeMe** [comment]
https://ibb.co/YDQqJpc but i can't find the folder of the extension in the chromebook

**Comment by DirtySkeMe** [comment]
Fixed
the folder is the one i use unpacked but i don't understand why that css just disappear

**Comment by garfield69** [comment]
sounds like perhaps you may be experiencing a sdd or hdd file management issue. may pay to run a check-disk or whatever to validate the media.

**Comment by DirtySkeMe** [comment]
happen again don't understand why my css just disappear

**Comment by garfield69** [comment]
if you have a security app then check its quarantine vault, perhaps it thinks the file is suspicious

**Comment by DirtySkeMe** [comment]
no security app it's android Chromebook

**Comment by garfield69** [comment]
well clearly something has changed on your chromebook because dtv was working fine for you for a long time and Dtv has not changed the way it uses css.
but since I'm not a chromebook user I cant offer any suggestions on how to proceed

**Comment by DirtySkeMe** [comment]
so far i just copy the file and thx for the workaround for the websql
