### ISSUE TITLE
please add https://t-rb.org/ to the Torrent Search engines

### ISSUE THREAD

**Issue by thinders1951** [SchizoDuckie/DuckieTV#1405]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...Standalone current

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...Stable 

**What is your Operating System (Windows, MacOSx, Linux)**
...Win 10 and Win 11

**Describe the problem you are having and steps to reproduce if available**
...please add https://t-rb.org/ to the Torrent Search engines

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
Yes, I can add this search engine.

**Comment by garfield69** [comment]
https://github.com/DuckieTV/Nightlies/releases/tag/nightly-202401180913

**Comment by thinders1951** [comment]
Thanks!

**Comment by thinders1951** [comment]
Works great!
