### ISSUE TITLE
1337x SE returning 403 error

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#1409]
1337x have added a 3 letter minimum search limit, and is returning an HTTP 403 when you are using the torrent search dialogue and start typing the first letter of your search.
The Dtv SE will treat the 403 as a genuine error and stops working until you click the engine tag again (for the single torrent search dialogue) or click the search icon (for the multi SE torrent dialogue).
Need to figure out how to handle this.

Dtv currently launches searches as you type, so the simple solve is to stop doing that and only search once the user presses enter or clicks a button.
Or perhaps we handle the 403 for the 1337x SE so that we can get past the first two letter failures.
Needs research.

**Comment by garfield69** [comment]
Hmm. may have mis-diagnosed issue. I have quality 720p enabled, so a manual search of `r 720p` should not have failed. And using the find a torrent button for an episode is also failing. 
So something else is a play here. Maybe Dtv needs to provide a Referer in the http header or something, without which 1337x is just returning a 403 Forbidden.

**Comment by garfield69** [comment]
Bugger. cannot set a Referer header within the http GET sent to 1337x , I get back a `Refused to set unsafe header "Referer"` error. A quick google search shows setting referer in javascript via XHR is not allowed.

**Comment by ilike2burnthing** [comment]
Is it because the *.to domain is now presenting a Cloudflare verification challenge?

I'm seeing the same 403 error for iDope, EXT, and ExtraTorrent. They have never worked for me, and have been using Cloudflare protection ever since I've used DuckieTV, whereas 1337x's *.to domain just started using it a few days ago as a result of being DDoS'd.

**Comment by garfield69** [comment]
Yes, it is looking that way. Since Dtv cannot make use of flaresolverr, the way forward for users that want to use those cloudflare challenged sites will be to define Jackett SE on Dtv and let  Jackett/Flaresolverr do its thing.
