### ISSUE TITLE
[LimeTorrents] warnings in console after search

### ISSUE THREAD

**Issue by ilike2burnthing** [SchizoDuckie/DuckieTV#1410]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
nightly-202402122056

**What is your Operating System (Windows, MacOSx, Linux)**
Windows 10 x64 (confirmed in Windows Sandbox)

**Describe the problem you are having and steps to reproduce if available**
Performing a search with LimeTorrents (as a single SE or part of a multiple SE search) results in the the console warnings below, with the last line repeating every ~3s, even when the search panel is exited. The only way to stop the error replicating is to restart DuckieTV.

**Attach any DuckieTV statistics or Developer Console logs if available**

```text
<link rel=preload> must have a valid `as` value

tab.html#!/episode/59217:1 <link rel=preload> must have a valid `as` value

The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

tab.html#!/episode/59217:1 The resource https://www.limetorrents.lol/static/main-20.css was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```

**Comment by garfield69** [comment]
This message is generated by the NWJS chromium browser in response to performing a search on the limetorrents web site.
So its the web site's HTML that is generating the error.
If you were to use your chrome browser and search on the web site you would also find this, you get two of those messages every time you do a search.
In fact it shows up on a Firefox browser too.
Admittedly the chrome browser log or the FireFox log don't show it repeating in a loop every 3s, so that is peculiar.
May be something to do with either NWJS or AngularJS... needs further research.

**Comment by garfield69** [comment]
I added some console log debugging to the genericTorrentSearchEngine JS to try and see if I could get in front of the first preload error message, but I cannot get to anyplace earlier than the actual http GET that sends the query to LimeTorrents and receives a response.
Once the response is received its already too late, and Dtv cannot get at the content received early enough to do a replace to modify the content to prevent the error.

I think the http GET is at a level lower than AngularJS, happening at the chromium level. Once it happens, the error occurs in cycles as AngularJS performs its html presentation refresh based on triggered events from the templates and $scope.

The only way to stop the error is to drop the LimeTorrents native SE. If I use the Jackett Limetorrents then the problem does not occur.

I don't know how to proceed further, its beyond my knowledge set.

**Comment by garfield69** [comment]
@Js41637  any thoughts on whether anything can be done to suppress this repeating preload message on the logs?
