### ISSUE TITLE
[UI bug] errors in console when exiting search panel

### ISSUE THREAD

**Issue by ilike2burnthing** [SchizoDuckie/DuckieTV#1411]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
nightly-202402122056

**What is your Operating System (Windows, MacOSx, Linux)**
Windows 10 x64 (confirmed in Windows Sandbox)

**Describe the problem you are having and steps to reproduce if available**
When exiting the search panel (either by clicking the background or the exit button) it results in the console errors below.

**Attach any DuckieTV statistics or Developer Console logs if available**

```text
deps.js:2333 Possibly unhandled rejection: backdrop click
(anonymous) @ deps.js:2333
(anonymous) @ deps.js:2304
g @ deps.js:2345
$digest @ deps.js:2357
(anonymous) @ deps.js:2360
Pg.completeTask @ deps.js:2372
(anonymous) @ deps.js:2257
setTimeout (async)
h.defer @ deps.js:2257
$evalAsync @ deps.js:2360
(anonymous) @ deps.js:2343
k @ deps.js:2345
q @ deps.js:2347
m @ deps.js:2347
reject @ deps.js:2344
E.dismiss @ deps.js:2661
i.close @ deps.js:2661
og @ deps.js:2246
d @ deps.js:2246

---

deps.js:2333 Possibly unhandled rejection: Canceled
(anonymous) @ deps.js:2333
(anonymous) @ deps.js:2304
g @ deps.js:2345
$digest @ deps.js:2357
$apply @ deps.js:2361
(anonymous) @ deps.js:2403
og @ deps.js:2246
d @ deps.js:2246
```

**Comment by garfield69** [comment]
Using my source Dtv build (as opposed to the packaged Dtv build), I see
```
angular.js:15535 Possibly unhandled rejection: Canceled
(anonymous) @ angular.js:15535
(anonymous) @ angular.js:11814
processChecks @ angular.js:17945
$digest @ angular.js:19074
$apply @ angular.js:19462
(anonymous) @ angular.js:28814
defaultHandlerWrapper @ angular.js:3804
eventHandler @ angular.js:3792
```
So the message is from AngularJS 
The implication is that the dialogue controllers (for either the single SE torrent dialogue or the multi-SE torrent dialogue) are missing a catch() someplace.
Needs research.

**Comment by garfield69** [comment]
nightly-202402131924

**Comment by garfield69** [comment]
clicktrap: So at the moment the clicktrap directive which was intended to only close sidepanels when you click around the calendar, is (and apparently always has) also cancelling the open dialogues (in particular fastsearch, torrentsearch, subtitlesearch), which I've always found annoying.
I'm going to see if I can stop it doing that, and thus avoid the `Possibly unhandled rejection: backdrop click` messages.

**Comment by garfield69** [comment]
ok so its not clicktrap, so something else. Jeesh, this is why I hate AngularJS, there are so many routines with their fingers in the pie, it as bad as C# which I detest almost as much.

**Comment by garfield69** [comment]
ok, the message comes from D:\DuckieTV-standalone\js\vendor\ui-bootstrap-custom-tpls-2.5.0.min.js
which presumably is used by Dtv to create a  uibModalWindow someplace, although I don't yet know how this is related to the dialogues yet.

**Comment by Js41637** [comment]
It's not an error, it's just when you close modals with a click it rejects the promise and they just aren't caught, it's fine to ignore.
Modals close by default on an outside click, that's part of ui-bootstrap I believe and it's configurable. I don't think it's related to the clicktrap.

**Comment by garfield69** [comment]
OH that's good to know. Thanks.
