### ISSUE TITLE
QBittorrent Data not being saved

### ISSUE THREAD

**Issue by gituser823** [SchizoDuckie/DuckieTV#1415]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**

Chrome Extension Browser Action

Im using it in Chromium Version 121.0.6167.160 (Official Build) for Linux Mint (64-bit)

QBittorrent Version 4.3.8

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**

DuckieTV-202402202001-chrome-browseraction, nightly

**What is your Operating System (Windows, MacOSx, Linux)**

Linux Mint Debian Edition 6

**Describe the problem you are having and steps to reproduce if available**

I can setup my QBittorrent Client just fine (running in docker on another PC) and I was also able to add a Magnet Link to it.

But whenever I leave the Settings the configuration is gone.
Any data I configured in Settings / QBittorrent 3.2+ Integration are gone again and it defaults to the default localhost settings again.

I am using a invalid certificate for my QBittorrent Web Client.
Maybe that is the issue?
Is there some way to disable certificate errors, but still use https?

**Attach any DuckieTV statistics or Developer Console logs if available**

**Comment by garfield69** [comment]
HTTPS connections between Dtv and qBt are not supported https://github.com/SchizoDuckie/DuckieTV/wiki/Setting-up-qBitTorrent-3.2-with-DuckieTV#note2
There is no solve given the current restrictions with the version of AngularJS http functions that Dtv uses, and there are not plans to upgrade to a newer version, as this would necessitate a compete re-write of all the Dtv JS to conform to the newer AngularJS requirements.
