### ISSUE TITLE
Calendar Integration with other calendars

### ISSUE THREAD

**Issue by komoricodrutz** [SchizoDuckie/DuckieTV#1416]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Stable - 202403151918
**What is your Operating System (Windows, MacOSx, Linux)**
Linux Mint 20.3

**Describe the problem you are having and steps to reproduce if available**
Enhancement idea, so no issue

**Attach any DuckieTV statistics or Developer Console logs if available**
N/A

Hi,
It would be nice to have the option of integrating the application's calendar with another calendar, like gnome calendar or a caldav like nextcloud. This would be useful for syncing the events across devices without having to run multiple instances of the application.

Thanks!

**Comment by garfield69** [comment]
Unfortunately the author left the project back in 2017 so all development has been suspended.
I've just enough skill to keep the lights on, but don't have time or interest in adding new features. I just fix bugs so my personal instance of Dtv keeps going, and post the updates here so others can coincidentally benefit too.
