### ISSUE TITLE
DuckieTV as a Browser extension:  WEB SQL is no longer available.

### ISSUE THREAD

**Issue by shellig** [SchizoDuckie/DuckieTV#1417]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...Browser Action

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...3024.4.11.534 (installed after previous version was blank)

**What is your Operating System (Windows, MacOSx, Linux)**
...Windows

**Describe the problem you are having and steps to reproduce if available**
... Previous version (from Feb) browser action was blank (no shows) - usually happens when I need to update :(  So I deleted and uploaded new version - tried to upload backup, nothing, just spins on adding show.  Last time it was the websql setting but that is now deprecated - not sure what to do now.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
All browsers that upgrade to using the Chromium engine version 124 will no longer have support for WEB SQL, the database that DuckieTV uses. (This impacts Chrome, Safari, Opera, Edge, Vivaldi, to name just a few browsers).
It is no longer possible to run DuckieTV as a Browser Extension.
Your only option if you want to continue to use DuckieTV is to switch to the Standalone version.
Installation packages for Windows, Mac OSx and Linux are available at https://github.com/DuckieTV/Nightlies/releases/latest
