### ISSUE TITLE
auto-scroll favorite page

### ISSUE THREAD

**Issue by LinuxGratos** [SchizoDuckie/DuckieTV#1420]
Using standalone, Nightly 202404110853 on Linux

- with many tv shows in the favorite page, when scrolling down the page, it keeps auto-scrolling back when there's a selected tv show (if you click once on it). Even after closing the details pane, it's still selected so the list keeps auto-scrolling.
It doesn't happen the first time to arrive in favorite page as no tv show is selected.

**Comment by garfield69** [comment]
@Js41637  this falls in your area or expertise, I haven't a clue how the favourites scrolling/focus/selection stuff works.

**Comment by Js41637** [comment]
I updated the code a bit, it might be less annoying now?

**Comment by garfield69** [comment]
does it need testing or shall I go straight to build and publish?

**Comment by garfield69** [comment]
seems to work fine for me, I'll publish.

**Comment by garfield69** [comment]
https://github.com/DuckieTV/Nightlies/releases/tag/nightly-202405151726
