### ISSUE TITLE
DuckieTV window being focused at midnight

### ISSUE THREAD

**Issue by LinuxGratos** [SchizoDuckie/DuckieTV#1421]
Using standalone, Nightly 202404110853 on Linux

I don't know what's happening but if I have DuckieTV opened but minimized and doing other things on the computer, once midnight, the DuckieTV window gets restored and focused automatically.

**Comment by garfield69** [comment]
https://github.com/SchizoDuckie/DuckieTV/wiki/FAQ#i-run-dtv-247-how-do-i-stop-dtv-maximising-its-window
