### ISSUE TITLE
[Feature Request] Autobackup without user intervention

### ISSUE THREAD

**Issue by moswain** [SchizoDuckie/DuckieTV#1423]
It would be cool to have DuckieTV auto-backup into a specified folder based on the settings provided.

Backup Timeslots: Daily/Weekly/Monthly
How many backup histories to keep: 3 days/3 weeks/3 months

The dialog box is fine for manual/forced backup. 
But for auto-backups, it just sits there waiting for user interaction.

**Comment by garfield69** [comment]
Closing as a duplicate of @1224
See https://github.com/SchizoDuckie/DuckieTV/issues/1224#issuecomment-551387292
