### ISSUE TITLE
Shows not loading, seems to be network issue?

### ISSUE THREAD

**Issue by marshy1982** [SchizoDuckie/DuckieTV#1424]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone (mac)

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Nightly 202405111132

**What is your Operating System (Windows, MacOSx, Linux)**
MacOSx Sonoma

**Describe the problem you are having and steps to reproduce if available**
All my series have dissapeared, I can't add any new series and I have tried wiping the database and reloading a backup and still not working. When I select my favorites it just says "loading" without ever showing anything. I can search for series to add, but no pictures load (just spinning) and when I try to add the series it just sits there spinning without adding. Also when it tries syncing with traktv it shows 0/1 It seem sto be a network issue, but I have changed nothing at my end. I have tried wipping all backup and setting and loading a backup, but nothing has changed.

**Attach any DuckieTV statistics or Developer Console logs if available**
Not sure how to do this?

**Comment by garfield69** [comment]
Urg. Sounds like your environment settings have been deleted. Without these, Dtv does not know what the format of the database is and cannot read/write to it.
- Shutdown Dtv
- Use your file manager (with the option to view hidden files enabled) and locate the Dtv data folder and delete it. Usually on MacOSx its located at `~/Library/Application Support/DuckieTV-Standalone`
- restart Dtv and wait for the pre-initialisations to complete and then you should be able to access the freshly formatted database.

Let me know how you go.

**Comment by marshy1982** [comment]
You’re a champion! Thanks, that worked. Unfortunately my backup was months old, so have to rebuild a bit of my library,but that’s on me for not backing up more regularly.

Thanks for the support.

**Comment by garfield69** [comment]
\o/
