### ISSUE TITLE
Add StartupWMClass to Desktop file

### ISSUE THREAD

**Issue by jlneder** [SchizoDuckie/DuckieTV#1425]
I am using the standalone version now.
Nightly "202405111132"
Linux

Hi, I made a derivation for nix for my personal use, to use DuckieTV in NixOS, after all the websql deprecation.
I was having a problem with the icon in the dock in gnome. It didn't show unless I added:
`StartupWMClass=DuckieTV-Standalone`
To the desktop file. Or change the name of the desktop file to DuckieTV-Standalone.desktop, but I prefer the first option. 
The wm-class have to be the same as the name of the desktop file for gnome(and i guess maybe all desktops?) to match the icon with the window. Or use the line mentioned above.

I fix it in my "package" but maybe someone else is having the same problem.

**Comment by garfield69** [comment]
Thanks for the info, maybe someone will find it useful.
