### ISSUE TITLE
[Question / Enhancement] Way to identify background poster series

### ISSUE THREAD

**Issue by ilike2burnthing** [SchizoDuckie/DuckieTV#1426]
Is there a way to identify the series of the calendar background poster?

Best I've got at the moment (when it isn't otherwise obvious) is pulling the TMDB URL for the JPEG from the devtools, then reverse image searching it. Is there anything better?

If not, could something be added? Maybe the series title as the HTML `title` attribute for the background image? Not sure how feasible that is, but open to other ideas as well.

**Comment by garfield69** [comment]
https://github.com/DuckieTV/Nightlies/releases/latest

**Comment by ilike2burnthing** [comment]
Thanks @Js41637
