### ISSUE TITLE
 theXem.info update request for The UnXplained: Mysteries of the Universe 2024

### ISSUE THREAD

**Issue by TGAMPinkRabbit** [SchizoDuckie/DuckieTV#1427]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...Standalone nightly-202406120803 (11/06/2024)

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...nightly-202406120803 (11/06/2024)

**What is your Operating System (Windows, MacOSx, Linux)**
... WIndows 11 

**Describe the problem you are having and steps to reproduce if available**
Find a Torrent button redded out with TMDB_ID error for The UnXplained: Mysteries of the Universe 2024

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
I've added the tvdb_id to the sceneNameException tables, and your Dtv should fetch the updated tables within the next 24 hours.
If the find-torrent button on the episodes side-panel is still red after this time, you need to go to the series details side-panel and press the refresh button to force an update.

**Comment by TGAMPinkRabbit** [comment]
Thank you for all your hard work!

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
