### ISSUE TITLE
Torrent search results

### ISSUE THREAD

**Issue by nuowen1** [SchizoDuckie/DuckieTV#1428]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser 
...Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...Nightly

**What is your Operating System (Windows, MacOSx, Linux)** windows
...Windows

**Describe the problem you are having and steps to reproduce if available**
Hi
   When I do a DuckieTV search for a download on my Windows 10 desktop the results are listed under the categories NAME   SIZE  SEED and LEECH but the ENGINE category is missing
Also the list of the engines being used for the search, just below my typed search request,  do not contain either a tick or a cross.
All the other Windows 10 devices on my local network behave as normal.
The desktop is connected to the router by an ethernet cable and the other devices use wireless.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
>When I do a DuckieTV search for a download on my Windows 10 desktop the results are listed under the categories NAME SIZE SEED and LEECH but the ENGINE category is missing

What you are describing is the **Single Search Engine (SE) torrent search dialogue**, which is the default setting when you first install DuckieTV (Dtv).

If you want to use the **Multi SE torrent search dialogue**, then navigate to **Dtv > Settings > Torrent Search Engines > Torrent Dialogue Multiple SE** and press the **Click to Enable** button.

**Comment by nuowen1** [comment]
Thank you so much garfield69 that's just what i needed
