### ISSUE TITLE
Update link to RARBG

### ISSUE THREAD

**Issue by thinders1951** [SchizoDuckie/DuckieTV#1430]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
... current on windows

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...stable

**What is your Operating System (Windows, MacOSx, Linux)**
...win 10 /11

**Describe the problem you are having and steps to reproduce if available**
... please update the link to RARBG to https://rargb.to/

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
No.
See https://torrentfreak.com/dodgy-rarbg-knockoffs-thrive-as-former-users-seek-refuge-230606/
