### ISSUE TITLE
Duckie TV shows page just spins with show names, nothing loads.

### ISSUE THREAD

**Issue by Infallibleman** [SchizoDuckie/DuckieTV#1431]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Nightly 202407251353

**What is your Operating System (Windows, MacOSx, Linux)**
macOS Catalina (10.15.7)

**Describe the problem you are having and steps to reproduce if available**
Duckie TV, when clicking on "+" just spins with show names, nothing loads.  Favorites don't show and calendar is empty

**Attach any DuckieTV statistics or Developer Console logs if available**

Screenshot: https://app.screencast.com/VecQnZyUlKZpE

**Comment by garfield69** [comment]
https://github.com/SchizoDuckie/DuckieTV/wiki/FAQ#i-cant-add-a-series-and-there-is-nothing-in-the-calendar
Let me know if you need further help and I'll re-open the ticket.
