### ISSUE TITLE
Download Issue

### ISSUE THREAD

**Issue by MystikSpiral** [SchizoDuckie/DuckieTV#1432]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...**Standalone** 

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...**V202408221910 (Stable)**
 
**What is your Operating System (Windows, MacOSx, Linux)**
...**Windows**

**Describe the problem you are having and steps to reproduce if available**
...**The 'TVDB_ID' button is red and crossed out.**

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
Please read https://github.com/SchizoDuckie/DuckieTV/wiki/FAQ#why-is-the-episode-find-a-torrent-button-not-working and then identify the series that needs fixing here ;-)

**Comment by MystikSpiral** [comment]
Hi thank you for your reply.

It seems to have just been a single show that was affected or it just took
time for the software to update.

Thanks for your potential help.

How I didn't waste any of your time.

Cheers
