### ISSUE TITLE
DuckieTV not marking downloaded shows as 'downloaded'

### ISSUE THREAD

**Issue by ggervais5** [SchizoDuckie/DuckieTV#1433]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Nightly 202410301030

**What is your Operating System (Windows, MacOSx, Linux)**
Windows 10

**Describe the problem you are having and steps to reproduce if available**
Autodownloads are not being marked as downloaded, causing TV shows to be auto-downloaded again.  Manual downloads are also not being marked as downloaded, though this is a smaller problem.  I am using qBittorrent V5.0.1 and have it connected via the qBittorrent WebUI.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
I have tested qBt 5.0.1 with Dtv Nightly 202410301030 and it is working for me on my win10, so it appears to be a setup issue on your end.
Lets start by taking a look at your Dtv config.
- Please click on the (i) About duckieTV icon near the bottom left of the Dtv page, and scroll down to the Statistics section.
- If you hover on the statistics header it should show a tooltip `copy statistics to clipboard` so click that link.
- open a plain text editor and paste the clipboard and save as statistics.txt
- drag/drop that file here so I can take a look.

**Comment by ggervais5** [comment]
[statistics.txt](https://github.com/user-attachments/files/17622723/statistics.txt)
I've gone over these settings for a while now, and I can't see which one(s) might be the issue.  Before I logged this issue, I found old posts with the same issue that were tied to a particular setting, and confirmed that setting on my system matched.

**Comment by ggervais5** [comment]
That setting is Torrent Parameters, and that is disabled.  I had this issue before, Torrent Parameters was the issue then, but not so now.  I even enabled it, disabled it, and then saved the settings.  DuckieTV has been refreshed since I saved the settings.

**Comment by garfield69** [comment]
Hmm. the only difference I see is that I use qBt on the same machine that is running Dtv, but you appear to be using different machines on your LAN, but that should not cause this issue if Dtv has managed to send the magnet/torrent to qBt.

Lets take a look at the log. 
- So use **CTRL SHIFT J** to view the Dtv console log.
- move your mouse away from the bottom line with the `>` prompt, and over any other blank spot and **right click**.
- if you are on a good spot the options should include a `save as`
- change the filename to `log.txt` and **save**
- **drag/drop** the file here so I can have a look.
Thanks.

**Comment by ggervais5** [comment]
I run qBt on the same machine where Dtv runs, so I'm not sure what you are seeing in the settings that might lead you to that conclusion.  I used to run both on a different machine, and when I migrated them, I migrated them one at a time.  Regardless, here is the log.
[log.txt](redacted for privacy)

**Comment by garfield69** [comment]
I was referring to the qBt 3.2+ integration setting for the address, which if on the same machine is usually [edit] `http://localhost` or `http://127.0.0.1`
whereas `192.168.1.100` is usually a sign the client and host are on the LAN on two different machnes ;-)

OK, the log was clean, but I was hoping to see some episode traffic between Dtv and qBt

So next time after you've had some activity if you provide that log then that may provide a clue ;-)

Also useful, is if on the console page you could click on the settings (cog icon top right next to the three upright dots) , and scroll down to the console **timestamps** and check that box.

[edit] forgot to add the local host address ;-D

**Comment by ggervais5** [comment]
[log2.txt](redacted for privacy)
I captured this log while manually downloading an episode with Dtv.  The issue is happening for auto downloads and manual downloads.

**Comment by garfield69** [comment]
ok, so I see 
`18:55:41.187 app.js:16628 Firing magnet URI!` and 5 minutes later `19:00:13.904 app.js:12098 remote torrent not found, removed magnetHash`

so the question I have is, what happened to the torrent on qBt?
Clearly Dtv thinks the torrent vanished from qBt.
Do you have some qBt automation that stops the magnet and moves the download to a folder and deletes the meta from qBt?

**Comment by ggervais5** [comment]
I only seed for 1 minute, and then Qbt stops seeding and removes the torrent.  Will this work better if I increase the seeding time?  I haven't changed the seeding time for a few years, but this issue just started (or I just noticed it) a few releases ago.On Nov 4, 2024 7:15 p.m., garfield69 ***@***.***> wrote:
ok, so I see
18:55:41.187 app.js:16628 Firing magnet URI! and 5 minutes later 19:00:13.904 app.js:12098 remote torrent not found, removed magnetHash
so the question I have is, what happened to the torrent on qBt?
Clearly Dtv thinks the torrent vanished from qBt.
Do you have some qBt automation that stops the magnet and moves the download to a folder and deleted the meta from qBt?

**Comment by garfield69** [comment]
the normal flow is
```
14:18:55.201 app.js:12219 qBittorrent 3.2+ connected!
14:19:08.515 app.js:11163 Xem does not have series From (401003), using default format.
14:19:15.466 app.js:16628 Firing magnet URI!  magnet:?xt=urn:btih:[redacted] 12237152 null null
14:20:29.353 app.js:11955 Torrent finished. Auto-stopping From.S03E07.1080p.WEB.H264-SuccessfulCrab[TGx]
14:20:29.399 app.js:11992 Episode marked as downloaded in database.  From s03e07 From.S03E07.1080p.WEB.H264-SuccessfulCrab[TGx]
```

In your case, because Dtv does not see the completion event of the torrent reaching 100% downloaded, Dtv does not trigger the auto-stop to take the torrent out of seeding itself, and Dtv does not see the torrent stopped event, so Dtv  does not perform the mark-episode as downloaded.

Instead, Dtv see the torrent vanishing, so Dtv removes its record of the DL and assumes it was cancelled.

**Comment by garfield69** [comment]
Dtv has to poll qBt to get updates, to find out what the status is.
ITs not a case of qBt pushing to dtv the status of updates.
So if between the last time Dtv polled qBt to get 99% completed, and the next poll to get the 100% complete, if qBt removed the torrent, Dtv flags the episode as lost.

**Comment by garfield69** [comment]
Try increasing the seed time by another minute if you can, that may be enough time for Dtv to get an update.
OR turn off the qBt automation.

**Comment by ggervais5** [comment]
That worked.  I downloaded that episode again, and this time the episode was marked downloaded in Dtv.

**Comment by garfield69** [comment]
\o/
