### ISSUE TITLE
Black screen on loading after fresh install. 

### ISSUE THREAD

**Issue by Mushrumski** [SchizoDuckie/DuckieTV#1435]
Installed: DuckieTV-202412031757-ubuntu-x64.deb) on a fresh install of Pop Os 22.04 

Initial start shows the opening screen.  Wait a few moments after starting to import a dB file.  It loads just fine. Everything is showing up and working.   Close the program and come back later and it's a black screen. 

I followed the Wiki, stopped DTV, removed the stand alone folder and started over.  It gives me the same results as the initial install. 

`Registering torrent client: Aria2
app.js:8491 Registering torrent client: BiglyBT
app.js:8491 Registering torrent client: Deluge
app.js:8491 Registering torrent client: qBittorrent 4.1+
app.js:8491 Registering torrent client: Ktorrent
app.js:8491 Registering torrent client: rTorrent
app.js:8491 Registering torrent client: Tixati
app.js:8491 Registering torrent client: Transmission
app.js:8491 Registering torrent client: tTorrent
app.js:8491 Registering torrent client: uTorrent Web UI
app.js:8491 Registering torrent client: Vuze
app.js:8491 Registering torrent client: None
app.js:11562 SettingsService.changeLanguage en_us en_us
app.js:8421 The next autoBackup is scheduled for Mon Dec 23 2024 10:29:50 GMT-0500 (Eastern Standard Time)
app.js:10994 Next SNRT update is due after  Mon Dec 16 2024 10:29:14 GMT-0500 (Eastern Standard Time)
app.js:10995 Fetched SNRT name and date exceptions, and TraktTvdbXref from localStorage.
app.js:11146 Initializing Xross Entity Mapping (https://thexem.info/) service for Scene Name episode format.
app.js:11074 Fetched localstorage Xem series list:  Array(1316)
app.js:11076 Fetched localstorage Xem series alias map: Object

app.js:11983 Uncaught TypeError: Cannot read properties of undefined (reading 'AutoConnect')
    at app.js:11983:34
    at Object.invoke (deps.js:2267:62)
    at deps.js:2269:18
    at r (deps.js:2230:76)
    at fb (deps.js:2268:499)
    at c (deps.js:2244:84)
    at Tc (deps.js:2244:397)
    at xe (deps.js:2243:48)
    at deps.js:2567:241
    at HTMLDocument.b (deps.js:2260:444)`

**Comment by garfield69** [comment]
Ahh.
I have not taken into account restores of backups that were taken when qBt pre-3.2 was the active client integration setting, and this causes an issue with the recent Dtv that supports only qBt 4.1+
To fix do the following:
- on the black screen **right click** and select **inspect**
- click on the **console** tab
- at the command prompt **>** paste the following and press **enter**
`localStorage.setItem('torrenting.client', 'qBittorrent 4.1+')`
- restart Dtv

Let me know if that works for you. 
I shall then update Dtv to auto handle that issue in the next release of Dtv.

**Comment by Mushrumski** [comment]
Thank you for your reply.   This is the output after entering what you asked. 

localStorage.setitem('torrenting.client', 'qBittrent 4.1+')
VM302:1 Uncaught TypeError: localStorage.setitem is not a function
    at <anonymous>:1:14

**Comment by garfield69** [comment]
the command is case sensitive. I've tested it and it works.
side note: I had not realised the new console would not allow you to paste the command by default, so you need to enable pasting.
at the console **>** prompt type 
allow pasting
and press enter.
then copy to your clipboard (select text and CTRL-C) the text below
`localStorage.setItem('torrenting.client', 'qBittorrent 4.1+')`
and CTRL-V the clipboard content to your console command line and press enter.
you should get `undefined` as a response which is ok.

**Comment by Mushrumski** [comment]
That worked.  It's back.   Thank you so very much!
