### ISSUE TITLE
Program won't upgrade on MacOS. 

### ISSUE THREAD

**Issue by lmgutman** [SchizoDuckie/DuckieTV#1436]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
DuckieTV-Standalone 202103142304
NWJS, Chromium 0.51.1 , 88.0.4324.150
**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
UserAgent - DuckieTV-Standalone  Nightly v202103142304 Macintosh; Intel Mac OS X 14_7_1

**What is your Operating System (Windows, MacOSx, Linux)**
MAC

**Describe the problem you are having and steps to reproduce if available**
When I try to upgrade to the latest version it goes through all the steps but the version in the APP never changes. 
I tried running the arm and x86 versions same result. 

**Attach any DuckieTV statistics or Developer Console logs if available**

**Comment by garfield69** [comment]
https://github.com/SchizoDuckie/DuckieTV/wiki/FAQ#why-does-standalone-dtv-installer-for-macos-not-update-the-program
