### ISSUE TITLE
Create a watchlist that's hooked to IMDB.

### ISSUE THREAD

**Issue by SchizoDuckie** [SchizoDuckie/DuckieTV#16]
Add a movie, and add it to the schedule, then schedule checks to some nfodb for a release

**Comment by fppt** [comment]
Hi guys. The auto download feature of DuckieTV is pretty awesome and I was thinking it would be great to have something similar for movies. I.e. select a movie you looking forward to, the quality etc, and then DuckieTV downloads it when it's available but I see this issue (which I think is something similar) got declined. May I ask why? Was it due to a technical difficulty or just a decision made to maintain DuckieTV as series exclusive?

**Comment by zero77** [comment]
@fppt 
You are better of using Radarr for films.
github.com/Radarr/Radarr

**Comment by garfield69** [comment]
It's there in the name :grin:  Duckie**TV** is focused on the TV addict.     
As you can see from the age of this ticket, 18th Feb 2014, the movie angle just never got any traction.

**Comment by fppt** [comment]
@zero77 thanks for the link. I wanted to avoid having another (similar-ish) app installed on my server but oh well.

@garfield69 Movies still show up on **TV** channels 😉, but DuckieSeries or DuckieTVSeries is not as good a name I admit. I was merely curious why it was never put into development and if it was worth forking and trying to do it myself.

**Comment by Js41637** [comment]
It can definitely be done but a project should stay true to what it aims to do which is a TV show tracker. Honestly if I felt the need for this feature I would add it myself except I don't need it and it doesn't take away from what DuckieTV is. If someone where to add it however there would be no problem. This is actually pretty easy to do i mean, this was probably before we used Trakt.TV. Trakt.tv can provide this data and we can just add a movie search and check every so often for when it's released. Only issue with movies is that they are not the same as tv episodes. There isn't a great indicator of when a movie is released. Like released in cinemas or released on DVD or released on BluRay. I think it's something that might be a bit harder than it seems, at least for it to work properly and it doesn't seem worth it if it doesn't work properly.
