### ISSUE TITLE
Allow Creation of Custom Search Engines for Private Trackers

### ISSUE THREAD

**Issue by SchizoDuckie** [SchizoDuckie/DuckieTV#18]
Make it as simple as possible to define a scraper that fetches relevant info

**Comment by SchizoDuckie** [comment]
fixed. see the js/services/TorrentSearchEngines/ folder for implementations.

**Comment by SchizoDuckie** [comment]
todos / braindump:

[ ] allow remote torrents to be fetched and uploaded as file upload to the torrent client (if it supports that)
(because torrents can be behind cookie/login and then sent to a remote)

````javascript
  var xhr = new XMLHttpRequest();
                xhr.open("POST", http+localStorage["host"]+":"+localStorage["port"]+relpath+"?token="+token+"&action=add-file", true, localStorage["login"], localStorage["password"]);
                xhr.onreadystatechange = ut_handleResponse;
                // mostly stolen from https://github.com/igstan/ajax-file-upload/blob/master/complex/uploader.js
                var boundary = "AJAX-----------------------"+(new Date).getTime();
                xhr.setRequestHeader("Content-Type", "multipart/form-data; boundary=" + boundary);
                var message = "--" + boundary + "\r\n";
                   message += "Content-Disposition: form-data; name=\"torrent_file\"; filename=\"file.torrent\"\r\n";
                   message += "Content-Type: application/x-bittorrent\r\n\r\n";
                   message += torrentdata + "\r\n";
                   message += "--" + boundary + "--\r\n";
                
                xhr.sendAsBinary(message);
````

**Comment by SchizoDuckie** [comment]
I just discovered 

https://github.com/zone117x/Jackett/

https://github.com/zone117x/Jackett/commit/abdca8cee88664864b2b521ab6cdc9e20f6b60ef

Note to self: contact these guys when the time comes, see if we can share a common repo with tracker info

**Comment by SchizoDuckie** [comment]
happy to report: This latest commit basically makes the custom search engines work!

Todos:

- [ ] Permanently store the custom searchengine data somewhere properly (database?)
- [ ] Provide a way to export these engines
- [ ] Autoload enabled engines on page load
- [ ] Figure out a way around the ugly confirm dialog. Should notify the user he should login, but not lock the UI
- [ ] Allow the user to edit all the existing genericsearch implementations, show these by default in the customsearch panel
- [ ] make enable/disable buttons work

**Comment by garfield69** [comment]
Looking to understand fixtures...
- Are fixtures basically pre-loaded DB entities in a table?
- They get loaded into the table during the table creation phase?
- How does making subsequent changes to the fixtures definitions get propagated to the existing DB entities previously created (like the nyaa change you made later to the already created nyaa fixures in the prior commit) ?

**Comment by SchizoDuckie** [comment]
> Are fixtures basically pre-loaded DB entities in a table?
Yes.
> They get loaded into the table during the table creation phase?
Correct :)
> How does making subsequent changes to the fixtures definitions get propagated to the existing DB entities previously created (like the nyaa change you made later to the already created nyaa fixures in the prior commit) ?
They don't currently :) While developing this, i'm dropping the database table using
`` 
CRUD.executeQuery('DROP table SearchEngine') `` in the console

**Comment by garfield69** [comment]
replaced by Jackett #899

**Comment by ManoharOfficial** [comment]
So, a fully private tracker like td.af would be able to fully integrate with the chrome extension V.1.1.5?

**Comment by garfield69** [comment]
Yes, Jackett has Torrent Day on it's list of supported sites.

**Comment by ManoharOfficial** [comment]
awesome! can't wait for the stable 1.1.5 release!

**Comment by garfield69** [comment]
You could try it out with the DuckieTV development nightly https://github.com/SchizoDuckie/DuckieTV/wiki/How-to-Install-a-Development-version-of-the-DuckieTV-Chrome-Browser-Extension-NIGHTLY
[edit] oh, you may find this useful https://github.com/SchizoDuckie/DuckieTV/wiki/Using-Jackett-with-DuckieTV

**Comment by ManoharOfficial** [comment]
Awesome! Just got everything setup. Can't wait for the stable release!
[edit] You guys are very through with your guides. I'm surprised that you don't accept donations.
Question : Is DuckieTV out of passion or, as an open source collaboration between various enthusiasts?
