### ISSUE TITLE
tracking local HDD for episodes

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#250]
https://www.reddit.com/r/duckietv/comments/2gsxz5/check_local_hdd_for_episodes/

32nops

> I love DuckieTV and have a suggestion. Is it possible to add an option to check local HDD for each episode? I would love to see which episodes I need to download, as well as which I need to watch.

Schizoduckie

> Parsing and scanning the local filesystem is really not something that I would like to invent.
> Thankfully, The module that Sickbeard uses could be ported from Python to Javascript probably, but it will probably be a hell of a project to set up.
> https://github.com/midgetspy/Sick-Beard/blob/e9cb8983264ca94be53af3c40a650eedef84de0a/sickbeard/name_parser/parser.py and the accompanying regexes
> I'll try to experiment with it when I have some time (still mighty busy currently though), See if I can do a scan on my downloads dir and see try to get this code going.
> It would be a mighty brilliant and powerful idea, nobody can deny that!
> https://github.com/midgetspy/Sick-Beard/blob/e9cb8983264ca94be53af3c40a650eedef84de0a/sickbeard/name_parser/regexes.py

**Comment by SchizoDuckie** [comment]
Closing as wontfix. I really dont want to get into indexing files on the HD.

What will work in the future is marking a .torrent as downloaded after it's done and then being able to find it in a configured video player to link it.
