### ISSUE TITLE
Calendar event dropdown display

### ISSUE THREAD

**Issue by Js41637** [SchizoDuckie/DuckieTV#262]
Ok so the calender-event dropdown thingy that displays all the episode info and schtuff. I am wondering if it would be a good idea to make it so all dropdowns that are on the **last** row show the dropdown **above** the episode instead of below. This would fix the dropdown going outside the page view.

The problem is, not everyone has this issue, people with larger screens or less episodes on the calendar don't run into this issue and would look a bit weird maybe if the bottom row of the calendar loaded the dropdown **above**.

I'm not really sure, it is slightly annoying seeing the dropdowns go outside view and having to scroll but it also isn't a very big deal. It is an easy adjustment to make the dropdown show above.

![image](https://cloud.githubusercontent.com/assets/6258213/4503350/fcc309fc-4ad6-11e4-95f2-6fe6b792a14b.png)

**Comment by SchizoDuckie** [comment]
Marking as obsolete pending the new UI.
