### ISSUE TITLE
Mark as watched button on hover

### ISSUE THREAD

**Issue by Js41637** [SchizoDuckie/DuckieTV#271]
As requested on [Reddit](http://www.reddit.com/r/duckietv/comments/2jgg1y/suggestion_mark_as_watched_button_on_hover/)

**Comment by antynomia** [comment]
why don't you just put checkmark icon as a button on the left side of the title? with two states: unwatched and watched (can be the same green checkmark from "watched episode" state but I would prefer eye icon from dropdown menu). no hover actions, just simplest solutions ;-) 
this way, you still can open dropdown menu with other options by clicking on the title, you are not taking too much space and you get access to "mark as watched" button.

btw I must say - I love, love love duckieTV! it has everything I need and it's super easy to use. I'm recommending it to everyone, even some of my non-tech friends are using duckieTV. thanks you for your work!

**Comment by SchizoDuckie** [comment]
Brainwave: the hover timer can be used to expand a show when hovering on it for a certain time, then  push down the results below the current item and show a 'mark as watched'  and 'download'  quick link.

Targeted for 1.0

**Comment by SchizoDuckie** [comment]
closed as no longer relevant in new UI.
