### ISSUE TITLE
error. Detected remote deletion 

### ISSUE THREAD

**Issue by blackjet69** [SchizoDuckie/DuckieTV#281]
Hi, Duckie TV keeps giving this message
 "Detected remote deletion
DuckieTV detected that the show '########' was deleted on another computer you're logged in on. Do you want to delete it here as well? (If you select no, it will be re-added to the remote computer on next sync)"
I havent done this.

**Comment by SchizoDuckie** [comment]
Closing this as it will be obsolete with the new implementation of the storage sync service.
