### ISSUE TITLE
Settings (Language and sync) aren't saved

### ISSUE THREAD

**Issue by Dadalino** [SchizoDuckie/DuckieTV#285]
Every time I start Chrome and DuckieTV, my settings are changed. 
I'm always asked about a serie which I have deleted in a synced account that does not exist. The only other synced account is trakt, and there I have the serie in my library. So first DuckieTV syncs with a non existing account (but only this one serie) and second it won't remember if I tell DuckieTV to not delete it in my list of series. It stays, but I'm asked again on every start of DuckieTV.
The second thing DuckieTV won't save is the language. I live in germany, so I think it might be a automatic feature to set the language to german but I don't want that. So I change it back to english_us and the next time it is german again. 
In this context I have to say that the translation to german failed miserably. Even for a native speaker, it sometimes might be impossible to understand if the person has no idea what a button or a setting should do. For example is the word "hit" translated to "schlagen" which means "punch" while it should be translated to "drücken". It isn't a big problem since most people will use it in english, but I thought you guys might wanna know.

**Comment by SchizoDuckie** [comment]
Fixed with v0.90
