### ISSUE TITLE
DuckieTV as a standalone app with Node-Webkit

### ISSUE THREAD

**Issue by SchizoDuckie** [SchizoDuckie/DuckieTV#288]
I've just experimented some with node-webkit on Windows, and, with some minor breakages, things seem to work! This means that soon we could deploy standalone packages for windows/max/linux :dancers: 

![image](https://cloud.githubusercontent.com/assets/111710/4877499/09cdadc4-62eb-11e4-86e3-dabf4c445fb0.png)

Notes:
- Settings page is untranslated/borked/broken, something's probably broken with determining the locale
- All available build systems seem to suck by failing to copy some files or something else. I've created a build manually by copying over the the binaries from the %currentuser%\AppData\Roaming\npm\node_modules\nodewebkit\nodewebkit\ folder and basically all assets from the project folder.
- A resource hacker will be required to swap out the regular node-webkit icon for the DuckieTV one in the windows version of node_webkit ( https://github.com/geo8bit/nodebob/blob/master/build.bat#L33 )
- Building DuckieTV standalone with nodebob manually breaks the working of ```DomParser().parseFromString(xhrContent,'text/html')``` silently. (grreaaat)
- Patches required to make DuckieTV work properly in commit https://github.com/SchizoDuckie/DuckieTV/commit/c02f0cf250e2f55d7efe2e78ec7b7ac7427f05f8 (mainly adding file:// urls as allowed in Angular)

Will work on this more later, wanted to prototype some.

Oh yeah, usage:

``` npm install -g nodewebkit ```

run ```nodewebkit``` in the DuckieTV directory

**Comment by garfield69** [comment]
Noticed that on my DuckieTV standalone (webkit 0.10.5 chromium 35) the duck did not flip after the quack.
Happen to find that nw.js was just released last week (node webkit 0.12.0)[http://nwjs.io/] (with chromium 41) the other day and when I tried this the flip was back! :grinning:

**Comment by SchizoDuckie** [comment]
Yea but is the chrome bug with stalling imports already fixed in that build?

**Comment by garfield69** [comment]
Chromium version 41.0.2265.0 was the first with the bug fix and nw.js 0.12.0
has Chromium 41.0.2272.76 so I would think so. 


  _____

**Comment by garfield69** [comment]
suggestions from [Reddit] (https://www.reddit.com/r/duckietv/comments/2yl4xi/ideas_for_ui/) 
>Pivke
>First of all this program is a BEAST, I love it!! This has the majority and the most important functions I need and want. Thank you for this awesome program!
>BUT one great addition that I would also find essential for easier tracking of series is, when you click "VIEW YOUR LOCAL LIBRARY", that you would see a number of how many unseen episodes you have and also that they are filtered to the top for easier access. Example image: Click to see image! When you watch plenty of shows like me it gets a bit tiresome scrolling and searching for episodes that you haven't seen.
>This is maybe a personal preference but i'd love if the link in the "ABOUT" tab would be external links and not internal, after I click a link I cannot go back to the main view, I will have to restart DuckieTv to come back to the main view.
>This is more of a modern ui preference, but get rid of the standard frame with minimize, maximize and close. An example would be... Winamp... Photoshop. Can't remember more programs that has changed it. But this would come at the bottom of the to-do-list.

**Comment by SchizoDuckie** [comment]
I believe most of the issues here have been addressed? @garfield69 will you retask this for the minimize/maximize or can we close this?

**Comment by garfield69** [comment]
Created #395 for the min/max/close buttons within the standalone frame-less window.
As all other issues have been addressed, I am closing this.
