### ISSUE TITLE
qBittorrent and tixati

### ISSUE THREAD

**Issue by whatyouneed** [SchizoDuckie/DuckieTV#302]
qBittorrent not working with DuckieTV.....can you make this posseble thanks

http://www.qbittorrent.org/download.php

**Comment by Js41637** [comment]
Note: Info about qBittorrent WebUI/API here: https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-Documentation

**Comment by SchizoDuckie** [comment]
Todos:

- [x] connect and poll
- [ ] solidify DuckieTorrent abstraction layer
- [ ] create settings for:
    - [ ] port
    - [ ] endpoint / ip address
    - [ ] http authentication
    - [ ] https (cert support?)
- [ ] update torrent remote templates to use generic client selection
- [ ] make sure only one torrent client can be active at the same time
- [ ] implement start/stop/status/progress
- [ ] implement add torrent via magnet/url (POST)

**Comment by garfield69** [comment]
reopen after automated close. Todo list outstanding?

**Comment by SchizoDuckie** [comment]
Same here, just translations as far as i can tell

**Comment by garfield69** [comment]
So are transmission.html, qbittorrent.html, and tixati.html complete and ready for translations, or still a WIP ?
