### ISSUE TITLE
Support Transmission BitTorrent client

### ISSUE THREAD

**Issue by webmaven** [SchizoDuckie/DuckieTV#303]
https://www.transmissionbt.com/

**Comment by garfield69** [comment]
Todos:

- [x] connect and poll
- [ ] handle 'no connection' 
- [ ] perform portscan on first start
- [x] solidify DuckieTorrent abstraction layer
    - [ ] create a setting to switch between uTorrent / qBittorrent
- [ ] create settings for:
    - [ ] port
    - [ ] endpoint / ip address
    - [ ] http authentication
    - [ ] https (cert support?)
- [ ] update torrent remote templates to use generic client selection
- [ ] make sure only one torrent client can be active at the same time
- [ ] implement start/stop/status/progress
- [ ] implement add torrent via magnet/url (POST)
- [ ] complete any outstanding translations

**Comment by SchizoDuckie** [comment]
I'm going to kill the portscan on start by default since most people will probably have it configured for some form of authentication.

**Comment by garfield69** [comment]
reopen after automated close. Todo list outstanding?

**Comment by SchizoDuckie** [comment]
Just trnaslations afaik

**Comment by SchizoDuckie** [comment]
Woohoo! \o/
