### ISSUE TITLE
DB Entries locked up

### ISSUE THREAD

**Issue by Js41637** [SchizoDuckie/DuckieTV#310]
Relevant; e3f7dc6

While adding a serie it will sometimes reach a point where it just freezes and stops for no apparently reason.

Rough Overview; 
* Seems to be limited to chrome
* Affecting Chrome v.41 and other Beta + versions
* Didn't seem happen in previous versions of chrome
* First noted in Canary version of chrome
 
Other:
* Opera seems to be unaffected
* DuckieTV 0.82 works fine on Opera 26.0

**Comment by SchizoDuckie** [comment]
Chrome bug was fixed. now we wait...

I'm gonna flag this as fixed for now, i've seen that in the latest chromium nightly it works.

**Comment by garfield69** [comment]
Version 41.0.2265.0 canary was pushed out today. this fixes our bug.
