### ISSUE TITLE
DuckieTV .082dev import posters list tooltip content double

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#312]
just spotted this while using DuckieTV 0.82dev to do an import. the tooltip containing the series name for all the posters in the import list contains the serie name twice
![image](https://cloud.githubusercontent.com/assets/6933240/5594029/ce2a603a-9299-11e4-954f-37bde6f888c4.png)

**Comment by garfield69** [comment]
Begins with correctly displayed name in tooltip, then as it progresses it displays the name in the tooltip twice.
serieHeader.html
line 21 `<div class="serieheader" ng-if="!noListButton && (!mode || mode == 'poster')" tooltip='{{serie.title}}{{serie.name}}'>`
line 36 `<div class="serieheader" ng-if="noListButton" tooltip='{{serie.title}}{{serie.name}}'>`
to fix it we would need to conditionally load tooltip with just serie.name when both serie.name and serie.title are loaded

**Comment by SchizoDuckie** [comment]
Yeah, I already started it. If we tweak the factory method that returns
trakt's trending result to already pre-map the serie.name we can make it
one interface.
