### ISSUE TITLE
handling timers using current trakt.tv serie name convention 

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#317]
With the current Trakt.tv DB is a state of flux, I am almost hesitant to report this as the serie names may change yet again, but here I go anyway.

Currently, Trakt.tv is no longer distinguishing between some series that are remakes/reinventions (by using the year as part of the name like it used to do). Examples:

In my collection previously, I had Battlestar Galactica, Battlestar Galactica (2003), Mission Impossible, Mission Impossible (1988), Teenage Mutant Ninja Turtles (1987), Teenage Mutant Ninja Turtles (2003).
Now I have 2 each of  Battlestar Galactica, Mission Impossible, Teenage Mutant Ninja Turtles.

This is causing Timers a little trouble.

While the EventSchedule table has entries for each serie, the chrome alarms only has entries for one of each serie of the same name.

Not sure how best to fix this... Incorporate the EventSchedule table ID in the alarm name, or some other nicer method?

**Comment by SchizoDuckie** [comment]
Adding the TVDB_ID would be the most logical option I guess. not sure
indeed what will happen with the remakes. how does that work with seasons?

**Comment by garfield69** [comment]
I think the integrity of the DB is maintained, since we use the Serie_ID to anchor the relationships between serie and season.
The other impact is to the torrent search. Without the year in place, we loose that additional filter on searches that we previously used to have. 
I can only hope that Trakt.TV will re-instate the year as part of the name for serie that are remakes/reinventions.
