### ISSUE TITLE
Mark shows as download/owned

### ISSUE THREAD

**Issue by Js41637** [SchizoDuckie/DuckieTV#320]
As requested on [reddit](http://www.reddit.com/r/duckietv/comments/2s4f9a/feature_requestability_to_mark_a_show_as/)

**Comment by SchizoDuckie** [comment]
I guess we could just fake the '100%' progress bar to keep the UI consistent when marking as downloaded. That'd be neat.

**Comment by SchizoDuckie** [comment]
8680759e712d27fbb3892632db822e814c6815d8 prepares for this by adding a 'downloaded' column to the episodes table.

**Comment by Js41637** [comment]
73e6b7917b180463c3fde6b7cb42ad379229b10c also prepares for this

**Comment by garfield69** [comment]
calendar with downloaded items
![image](https://cloud.githubusercontent.com/assets/6933240/7213564/fbd352d6-e5d6-11e4-92f2-4c5767e3a4d6.png)
episode list with downloaded items
![image](https://cloud.githubusercontent.com/assets/6933240/7213567/14c08386-e5d7-11e4-86e5-dbdbef8aa3a6.png)

**Comment by garfield69** [comment]
todo:
-[ ] amend backup / restore to include downloaded=1 data
-[ ] option in settings to ignore downloaded status (do not display on calendar and hide buttons) TBC

**Comment by SchizoDuckie** [comment]
I've been thinking we could also use the green downloading progress bar (at
100%) that torrent clients use when a download is complete to show that
it's completed in favour of an icon. Any opinions?

**Comment by Js41637** [comment]
Yeah the original idea was just reusing the 100% from the download progress because it's the same thing as marked and it will keep everything consistent instead of having two indicators of downloaded. Also i'm not in favour of adding another icon to the calendar event making the name space smaller.

**Comment by garfield69** [comment]
using 100% progress bar
![image](https://cloud.githubusercontent.com/assets/6933240/7220467/29ac90a0-e71c-11e4-85c0-a8d30dde52d1.png)

**Comment by SchizoDuckie** [comment]
yeah something like that :) i'd just use the progressbar directive thats
used inside the torrentminiremoteprogress. that gives nice striping too

**Comment by garfield69** [comment]
like this?
![image](https://cloud.githubusercontent.com/assets/6933240/7220622/ed81ed12-e722-11e4-95b9-0d2cbd22f6c4.png)

**Comment by SchizoDuckie** [comment]
Yes! excellent!

**Comment by garfield69** [comment]
@schizoduckie So do we want to offer a settings option to show/hide the downloaded status, and if we do, which should be the default?
- [ ] no options, everyone gets the downloaded status display and related features
- [ ] show/hide in settings, default to showing downloaded status and related featuers
- [ ] show/hide in settings, default to hiding the downloaded status and related features
- [ ] I can't decide my brain is melting, let someone else make a decision :-b

**Comment by Js41637** [comment]
This might require some reworking of the current HTML logic but at the moment a progress bar is displayed if the torrent is still in the client and is seeding or finished if ProgressBar (and torrenting) is enabled. Disabling Progress bar obviously stops from showing the progress which will hide this method too, I assume, if it works how I imagine. What we need is to display the progress bar if Torrent Download Progress or Show Downloaded is enabled. Although that would be kind of a pointless setting, just have an option to enable marking episodes as downloaded which will just remove the buttons and the progressbar if TorrentProgress bar is also disabled.

**Comment by garfield69** [comment]
@js41637 Ah no, I don't think there will be a conflict.
The downloaded bar in the calendar is strictly a **fake** progress bar, and
is only tied to the state of the downloaded entity in the episodes CRUD
table.
It does not impact on any of the torrenting components.
I envision that the show/hide downloading setting (assuming it gets the go
ahead from Schizoduckie) will simply show/hide the fake bar on the calendar,
and show/hide the buttons on the sidepanels that the user clicks on to
change the downloaded state manually.
Hope this clarifies things and not muddy the waters :-)


  _____

**Comment by Js41637** [comment]
So why was the option of enabling marking shows as downloaded reverted?

**Comment by garfield69** [comment]
The marking shows as downloaded remains.
What was removed was the settings option to make the status of downloaded files invisible. It was decided by Schizoduckie that that setting was unnecessary.

**Comment by Js41637** [comment]
I just think maybe not all people want a green calendar.

**Comment by garfield69** [comment]
Yeah well, if Schizoduckie should change his mind then I'll happily put it
back in.


  _____

**Comment by SchizoDuckie** [comment]
Yeah, I don't want to create a million gazillion options in settings. *we*
should decide on sensible defaults. If we make everything optional we'll
end up with an unmaintainable behemoth. Same with that setting for tweaking
some padding. It's useless imo.

We'll see if people complain. Until then, it' s our program.

**Comment by Js41637** [comment]
Fair enough for less settings however I do think an option do remove the highlighting of downloaded episodes to be deserving of a setting considering at the moment if you download a show it will auto be marked as downloaded with no way to prevent that and will require unmarking episodes as downloaded to remove it and if you restore from backup (and trakt I assume) it auto marks all watched episodes as downloaded as well. I've never left my DuckieTV open while downloading or leave my shows seeding so I never really see the green progress bars and they don't remain on my calendar so i've always had the clear calendar and I prefer it over something such as this; 
![image](https://cloud.githubusercontent.com/assets/6258213/7452686/2c6bb1fc-f2a4-11e4-8493-2ee9e735238b.png)
