### ISSUE TITLE
Automagic tests using Karma and Protractor, Continuous integration using Travis CI

### ISSUE THREAD

**Issue by SchizoDuckie** [SchizoDuckie/DuckieTV#321]
As you may have noticed, i've worked this weekend to make sure that the new FavoritesService and Trakt v2 API will be both unit-testable and end-to-end testable, and today I got the Karma tests running automagically on Travis-CI so that now we have this sexy image we can link to: [![Build Status](https://travis-ci.org/SchizoDuckie/DuckieTV.svg?branch=trakt-api-v2)](https://travis-ci.org/SchizoDuckie/DuckieTV)

There's a whole lot of reading up to do if you want to get into it, but i've summarized it in the tests directory (see the trakt-api-v2 branch)

https://github.com/SchizoDuckie/DuckieTV/blob/trakt-api-v2/tests/readme.md

If you have any questions, shoot here :)

**Comment by Js41637** [comment]
Man i've always wanted a Travis-CI. You've done some great work with that testing thing and the docs which I almost understand. :grinning:

**Comment by garfield69** [comment]
Holy Guacamole! :astonished:
I won't pretend to understand how any of this works, and its just as well one of us knows what he's doing, and that man ain't me! :wink:

**Comment by SchizoDuckie** [comment]
Here's another cool service I added:

[![Code Climate](https://codeclimate.com/github/SchizoDuckie/DuckieTV/badges/gpa.svg)](https://codeclimate.com/github/SchizoDuckie/DuckieTV)

**Comment by garfield69** [comment]
Um, what's it mean? :confused:

**Comment by SchizoDuckie** [comment]
It's checking if the code is nicely formatted, finds obvious errors and sees if doesn't contain too many weird structres :+1: 

If you're trying to figure out how to run a test or how to debug a test:
- run ``karma start`` from the command line so that a chrome window pops up
- click the 'debug' button in the toolbar, a karma debug window opens
- open the webkit inspector here, now you have a window directly into running tests and you can set breakpoints :sunglasses: 
![image](https://cloud.githubusercontent.com/assets/111710/5731001/4b275b5e-9b7f-11e4-803d-5ef13dc7f167.png)
