### ISSUE TITLE
episode without tvdb_id due to trakt.tv broken v1 API 

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#322]
After the trakt.tv v1 API debacle, my local db's on all my systems are littered with episodes whose TVDB_ID is null. These are effectively duplicate records without identity.
As part of the next release with v2 API active, I recommend these records be deleted, perhaps as part of the upgrade install script.

**Comment by SchizoDuckie** [comment]
Agreed. I have had the same problem here.

There will be big migration script in the next release as i'm also planning
some database changes for the next version.
Could you upload your database somewhere and attach it to this ticket ?

I've also noticed that the refactoring of timers leaves duplicates (the
named ones)
We should probably just remove them all together and rework it to grab only
the updates from the new API with a single call.

I'll see if I can create some proper test scenario's for all this.

**Comment by garfield69** [comment]
https://www.dropbox.com/s/h36gyuru9sxsazb/18?dl=0
I'd already performed a clean up of all my DB's, but this one still has one series with the problem I raised. `Dollhouse` `ID_Series=76` `ID_Episode=11851 through to 11864`

**Comment by SchizoDuckie** [comment]
Please confirm that the latest database migration fixes this.
Series without TVDB_ID are silently dropped during the database upgrade

**Comment by garfield69** [comment]
So I took the DB 18 from my dropbox, and let the latest DuckieTV 0.83b perform a DB upgrade over it of the episodes entities from v9 to v10 and then examined the results under SqLiteBrowser3..
I was expecting to see all the duplicate episodes from dollhouse (ID_Series=76) that have a NULL TVDB_ID to be gone, but that is not the case.
BEFORE
 
![uploads/354d24d0-0490-4467-9b94-360105d7b8c1/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F354d24d0-0490-4467-9b94-360105d7b8c1%2Fblob)
AFTER

![uploads/ef3e70e8-3f34-4300-91b0-e43ba2c336de/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fef3e70e8-3f34-4300-91b0-e43ba2c336de%2Fblob)
Did I misunderstand the instructions or something?

**Comment by SchizoDuckie** [comment]
Nah it doesn't work correctly yet i think.

**Comment by garfield69** [comment]
Analysis of Dollhouse and AHS TVDB_ID null issue.
I've taken a closer look at the records. Dollhouse Season two has two sets of episode records for each of the 13 s2 eps. One set are the original records from **v1 API**, distinguished by `http://slurm.trakt.us/images/episodes/*` *filename*, and populated *TVDB_ID*.
The other set came from the **v2 API**, distinguished by `https://walter.trakt.us/images/episodes/*` *filename* and with a null *TVDB_ID*.
The only other records I have with a null *TVDB_ID* are the special eps for American Horror Story.
in this case I don't have any **v1 API** records for AHS, and the **v2 API** records *filename* and *TVDB_ID* are both null.
These are the only two series out of 172 that I have, which have null TVDB_ID provided by the **v2 API**.
Until the **v2 API** starts delivering valid data for these two series, I don't think there is any point trying to code a clean up fix.
