### ISSUE TITLE
Change the calendar zoomout to be more dynamic

### ISSUE THREAD

**Issue by Js41637** [SchizoDuckie/DuckieTV#323]
Instead of using set resolutions with `@media`, figure out a way to just have the calendar resize to auto fit the screen.

Experimental version using `width: calc(100% - sidepanel` was made in commit 9d410e1f59c52a00456740ae53980bcbbd407de7, however this version only changes the width of the calendar and will only work up to a certain size before it gets ugleh.

The ideal method would be to continue to use the transform but with what SchizoDuckie suggested `transform: scale(calc(1 * (100%-345px)))` however there is a bug with Chrome that prevents percentages being used inside a calc inside a css function.

Only other solution would be to use a directive and calculate the stuff 'manually'. Otherwise we can just keep the current method.

**Comment by Js41637** [comment]
Changes made by SchizoDuckie have done this. However SchizoDuckie mentioned about making the calendar and sidepanel a little more friendly on very small resolutions. There isn't really much that that be done with the sidebar being a fixed 400 or 800px wide. Possible solutions could just setting a minimum width required for 'normal' operation of the sidebar and if it doesn't meet the minimum have a more minifyed version of the sidepanel which could require some work and testing.

**Comment by SchizoDuckie** [comment]
Todo: re-implement directive that monitors window.onresize

**Comment by SchizoDuckie** [comment]
le properly fixed with object.observe and the SidePanelState monitor
