### ISSUE TITLE
While calendar is zoomed out, borders flicker on re-rendering DOM. tooltips need disabling

### ISSUE THREAD

**Issue by Js41637** [SchizoDuckie/DuckieTV#324]
While the calendar is zoomed out, hovering over events opens tooltips which cause the calendar borders to flash. Doesn't look very nice.

SchizoDuckie was saying that the tooltips loading cause reflow or relayout and the solution would be to render the tooltips outside the dom [of the calendar?]

**Comment by Js41637** [comment]
Latest commit by SchizoDuckie seems to fix the border flashing issue. Should also be noted that now while zoomed out some of the borders just seem to disappear but I don't think it's a problem.
![image](https://cloud.githubusercontent.com/assets/6258213/5772504/bd5b9ea4-9da7-11e4-85e4-9f5225abc901.png)

**Comment by SchizoDuckie** [comment]
I think it's related to sub-pixel rendering. We can probably fix this by
making sure that the zoom factor fraction is either an even or an odd
number always

**Comment by Js41637** [comment]
Yeah certain sizes remove different borders but there are some points where they all display correctly.

**Comment by SchizoDuckie** [comment]
Disappearing borders are a chrome bug. We do need to figure out how we can disable the tooltips when the calendar is zoomed out to prevent dom reflows
