### ISSUE TITLE
Torrents not downloading

### ISSUE THREAD

**Issue by kuriakosesaju** [SchizoDuckie/DuckieTV#326]
Whenever I try to download the latest episode of any of the shows Im tracking, I get redirected to a page that says Webpage not available. I checked the same torrents at Kickass and Torrentz's main sites and downloading directly from these sites works just fine.

**Comment by garfield69** [comment]
Please check DuckieTV's About page, Statistics section, and tell us what `Torrenting URL`  is set as. Thanks.

**Comment by kuriakosesaju** [comment]
Kickass.so

**Comment by kuriakosesaju** [comment]
This is on a Windows machine 8.1

**Comment by garfield69** [comment]
Sorry, I should have asked for `Torrenting Search Provider` also, but It should say **KickAssTorrents** ?
Can you give me an example of the show you are trying to download, and if you can, upload an screen shot of the DuckieTV torrent Dialogue before you press the download button?

**Comment by kuriakosesaju** [comment]
![duckietv screen2](https://cloud.githubusercontent.com/assets/10556577/5771592/66359daa-9d66-11e4-9fd4-9c2c4cc397b7.jpg)
![duckietv screen1](https://cloud.githubusercontent.com/assets/10556577/5771593/663c6108-9d66-11e4-8623-bc18642a2f9c.jpg)

No particular dialog pops up as such. Earlier, when I'd click download, the torrent would just download. The funny thing is if I click Torrent details, it redirects me just as it should to the torrent page. And this is happening with all my shows. ALL OF THEM! :(

**Comment by garfield69** [comment]
It appears http://torcache.net/ is down.
We will do some research and see if there is anything we can do.

**Comment by garfield69** [comment]
Have you tried using magnet links?

**Comment by kuriakosesaju** [comment]
Magnet links are working! Thank you!!!

Have you tried using magnet links?

—
Reply to this email directly or view it on GitHub
<https://github.com/SchizoDuckie/DuckieTV/issues/326#issuecomment-70207453>.

**Comment by garfield69** [comment]
@schizoduckie I'll keep an eye out to see if torcache.net comes back up, but if it remains down by the time we are ready to push out a DuckieTV release, then obviously we should look into replacing the service ;-)

**Comment by kuriakosesaju** [comment]
Sounds good! You guys should also work on a standalone app. This is good
work, guys! Keep it up! #duckietvforever

**Comment by SchizoDuckie** [comment]
There is already a standalone app version in the releases section here on gh
