### ISSUE TITLE
Serie Sidepanel - Left - Episode Details

### ISSUE THREAD

**Issue by Js41637** [SchizoDuckie/DuckieTV#327]
# Serie Sidepanel - Left - Episode Overview

## Overview
Github tracker for the first left sidepanel displaying episode overview, this pretty much replicates the event dropdown with some extra functionality and sexiness :smirk:

When clicking on an episode event in the calendar, opens the sidepanel on the right with the episode overview, clicking either Series Details or Episodes will expand the sidepanel and display relevant details on the second [right] panel. Selecting another episode event from the calendar while this is open will close the second [right] panel and update the existing [left] panel with the new episode details. 

## Current Layout:
* Episode Screenshot
* Serie Name ExxSxx
* Episode Title
* Episode Summary
* Buttons
  * Serie Details | Episodes
  * Mark as Watched
  * Search for a Torrent | Quick Download
  * Torrent Control
  * Torrent Progress

Torrenting buttons displayed depends on level of torrent enabled.

## Schtuff Todo / Checklist
- [x] Form a basic template idea 
- [x] Create basic layout as per template with buttons and relevant JS functions
- [x] Apply CSS to each element as per the the [mockup](http://i.imgur.com/ughGeui.jpg) design
- [x] Redesign the torrent UI with SchizoDuckies layout
- [x] Fix up TorrentCtrl JS
- [x] Properly style SchizoDuckies torrent layout
- [x] Final CSS & JS Tweaks
- [x] Completely done

## Notes
Seeing as this was made late the first [left] sidepanel is pretty much done I think, we've spent quite a bit of time on it and I think it looks and functions great. Should be further mentioned that this is just the Episode Overview layout, there was plans to be able to select series as well which would replace the overview with Serie Overview however we will likely just copy the Serie Overview that will be made the the second [right] sidepanel or something. Oh and here is the [full sized mockup](http://i.imgur.com/SokyrMz.jpg) I made.

**Comment by Js41637** [comment]
Due to a recent incident, the most recent changes to the sidebar test branch have been reverted and gone. The only stuff that went were SchizoDuckie's changes to the TorrentUI, Calendar Zoom, Sidebar JS overhaul, and some torrent ctrl changes.

**Comment by garfield69** [comment]
I take it the recovery that Schizoduckie did for sidebartest which got
stored under your js41637/sidebartest repo is not up-to-date?


  _____

**Comment by Js41637** [comment]
Nah my fork of this repo is never up to date cause I never update it :( which I think I might start doing now :)
