### ISSUE TITLE
Todos before next release (v0.90)

### ISSUE THREAD

**Issue by SchizoDuckie** [SchizoDuckie/DuckieTV#329]
- [x] Fix background loader 
- [x] Fix timers by removing them all together
- [x] Create a new TraktTVUpdateService that's called in the background (or foreground, for standalone) that updates what's needed based on a query to trakt's [updated shows api](http://docs.trakt.apiary.io/#reference/shows/updates/get-recently-updated-shows)
- [x] Fix the episode entities to add raw Trakt.tv airdate with timezone info 
- [x] handle series that have been removed from thetvdb
- Implement the last TraktTV v2 fixes
  - [x] Trakt.tv importing
  - [x] Trakt.tv mark as watched
  - [x] Create an update workflow 
  - [x] delete eventSchedule table from DB on install
  - [x] do a chrome.alarms.clearAll on install 
  - [x] Fix the series list
  - [x] Create a nice dialog for the update explaining everything that's changed
- [x] Fix AutoDownloads (timerless)
- [x] Fix delete flow from series / episode page
- [x] fix the horrible dutch translation
- [x] Test an upgrade migration (abuse girlfriend's laptop/dataset)

**Comment by SchizoDuckie** [comment]
If you want to test the new update mechanism repeatedly:

  localStorage.setItem('trakttv.lastupdated', new Date('2015-01-15').getTime())
  CRUD.EntityManager.getAdapter().db.execute("update series set lastupdated = '2015-01-05'").then(function(result) { console.log(result); })
// or even 
// CRUD.EntityManager.getAdapter().db.execute("delete from episodes where 1").then(function(result) { console.log(result); })
// reload page

**Comment by SchizoDuckie** [comment]
chrome.alarms.clearAll won't be needed and possible since we remove the alarms permission in the next release.

**Comment by garfield69** [comment]
What about all the active alarms in chrome (remnants of the timers that were active in 0.82) that will kick off and presumably fail after the 0.90 update is pushed out? 
My thought was to just issue an chrome.alarms.clearAll() in the one time upgrade script to remove the last vestiges of these alarms from chrome rather that wait for them to expire of their own volition.
  ----- Original Message -----

**Comment by SchizoDuckie** [comment]
That's what I meant, there will be no alarms, since we remove the permission within package.json, therefore there's no cleanup needed there except for the drop table statements :+1:

**Comment by garfield69** [comment]
Oh, I get it now. :-)
  ----- Original Message -----

**Comment by SchizoDuckie** [comment]
If you guys have any additions for the templates/update.html dialog, please feel free to add them. We've done so much that I may have forgotten something.

**Comment by garfield69** [comment]
Are we done with any major template change for 0.90, can I start working on required translations ?
  ----- Original Message -----

**Comment by SchizoDuckie** [comment]
Yeah I guess so :)

**Comment by SchizoDuckie** [comment]
I've decided to leave out the trakt sync (push all local stuff to trakt) in this release.

The trakt API docs state that you can no longer just push everything, but need to be careful not to mark stuff watched twice, which would break current workflow. Better to do this in a next release when i have time to finish the new generic storage sync engine.
