### ISSUE TITLE
0.83 [adding shows] search completed still has the spinner icon remaining

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#331]
when using the adding show panel, and using the search box, after all search results are displayed, the spinner remains active.
![image](https://cloud.githubusercontent.com/assets/6933240/5791342/916490e2-9f34-11e4-8a9c-4164ced6dafe.png)

**Comment by Js41637** [comment]
Ah yeah that reminds me, the spinner has been acting weird. Umm lemme see.

* Spinner remains displayed while the 'trakt might be down' error comes up
* Spinner 'start typing' text remains while you are typing or searching for a serie
* Spinner text/img remains once results have been returned
* Spinner 'start typing' text and img remain when no series have been returned
* No error comes up for when the query returned no series

I think that's it.

**Comment by SchizoDuckie** [comment]
Yeah that whole thing needs an overhaul in the version after 0.90

**Comment by SchizoDuckie** [comment]
I haven't seen this happen anymore, anyone have a reproducable scenario?

**Comment by garfield69** [comment]
Nah.
since https://github.com/SchizoDuckie/DuckieTV/commit/29874f8282327d31206025e8078ad07955a05278 I haven't seen it happen again.
  ----- Original Message -----

**Comment by SchizoDuckie** [comment]
awesome
