### ISSUE TITLE
403 during image loadings

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#333]
getting lots of  `https://walter.trakt.us/images/shows/000/033/706/fanarts/original/0340a6df61.jpg?1420260618 Failed to load resource: the server responded with a status of 403 (Forbidden)` recently.
According to the APIary a 403 is `Forbidden - invalid API key`.
Examining the developer tool Network panel, it appear that maybe 1 in 4 image loads fail in this manner.
Is it a legit issue or just Trakt.TV throwing a tantrum for no reason (faulty load balancer perhaps)?

**Comment by SchizoDuckie** [comment]
https://plus.google.com/112139764751082726312/posts/XLGDdY1AknR

It's a bug in trakt's api. Popcorntime devs have already flagged it there
