### ISSUE TITLE
Serie Sidepanel - Right - Serie Overview

### ISSUE THREAD

**Issue by Js41637** [SchizoDuckie/DuckieTV#334]
# Serie Sidepanel - Right - Serie Overview

## Overview
Github tracker for the second right sidepanel displaying serie overview, this pretty much replicates the basic serie details template that displays the serie poster and the relevant meta data.

When clicking on the Serie Details buttons in the LEFT Episode Details panel it expands the sidepanel to the right with the serie overview. As mentioned above, just displays basic serie information and will likely have buttons to view other serie details such as episodes and seasons and stuff. The actual workings of this module are still in the planning stages.

## Template Layout:
* Serie Name
* Serie Poster
* Serie Metadata
  * Links
  * Currently Airs on
  * First Aired on
  * Genres
  * Content Rating
  * Country
  * Network
  * Rating
  * Runtime
  * Status
  * Actors

Basic template replicating the serie details, likely will have buttons at the bottom, unsure how actors are going to work as they can be quite large.

## Schtuff Todo / Checklist
- [x] Create mock up design
- [x] Create basic template in HTML
- [x] Add any basic JS required for operation
- [x] Style HTML with CSS to match mock up design
- [x] Fix episode ratings
- [x] Find suitable style for buttons
- [x] Final CSS & JS Tweaks
- [x] add JS routines to support sidepanel/episodes.html `auto download all` button.
- [x] add JS routines to support sidepanel/episodes.html `mark all watched` button.
- [x] Completely done

## Notes
Mock up design is about 75% done.

**Comment by garfield69** [comment]
Just tried starting my standalone 0.95, but it is choking on the side-panel w.i.p.
On start-up the side-panel is open and black and locked. Anyone else?

**Comment by garfield69** [comment]
The refresh button in the sidepanel\serie-overview.html only works if you've got there from the favorites list.
If you have used the seasons or episodes buttons to bring up the right side panel, the refresh button on the series-overview does not work.
Something to do with the listener for 'serie:updating' residing in SerieListCtrl which is not active at this time perhaps?
