### ISSUE TITLE
after the store upgraded prod duckie 0.82 to 0.90 there was no data refresh

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#335]
I was expecting the migration script to initiate a full database refresh once the DB had completed its revamp of the tables. But that does not appear to have happened?
![image](https://cloud.githubusercontent.com/assets/6933240/5894144/61f94a4e-a562-11e4-80a6-3ca7eef7390e.png)
I could backup and import, but I thought the plan was for it to all happen during the upgrade process?

**Comment by SchizoDuckie** [comment]
Hmm it has done that for me (i've seen it happen). the code is here.
https://github.com/SchizoDuckie/DuckieTV/blob/angular/js/services/MigrationService.js#L27

**Comment by garfield69** [comment]
I blew away the local storage entries for 0.9migration and 0.9updateallshows
and restarted my Prod 0.90 DuckieTV and it is doing it now.
Don't understand what could have happened. I guess if it occurs with other
users we shall soon hear about it ;-)


  _____

**Comment by garfield69** [comment]
closing. Not had a replication on my other Prod machine, nor on my 0.90 Standalone build.

**Comment by garfield69** [comment]
got another instance of the data refresh not happening during the 0.82 to 0.90 migration on a production version of duckietv.
This time I've capture a promise rejection which may be related.
![image](https://cloud.githubusercontent.com/assets/6933240/5905247/cbe6c530-a5f3-11e4-9f12-e19c8b6514e9.png)

**Comment by SchizoDuckie** [comment]
Line 983 resolves to CRUD.js
''                     CRUD.log('SQL Error in FIND : ', sqlError,
resultSet, what, this, query, [query.split(' VALUES (')[0], (s =
JSON.stringify(valueBindings)).substr(1, s.length - 2)].join(' VALUES (') +
')');''

**Comment by Js41637** [comment]
Yeah I've seen that error a few times, only seems to happen with the migration thingy.

**Comment by garfield69** [comment]
OK. This is what I think might be happening here. We don't all have super computers like you Schizoduckie ;-) One of mine is a single core CPU, the other a dual core CPU.

There is a small window in which the installation-upgrade-migration script performing an update-from-trakt-TV has clashed with the CRUD performing a Series and Episodes table upgrade.

While the Series and Episodes tables are being rebuilt, the check to ensure at least one trakt.TV update occurs fails.
The instance of a promise failing is probably a direct result of the CRUD's Series and Episodes table upgrade being in progress, while other tasks are trying to update/lookup Series and Episodes data.

I think if we delay the installation script for a little bit, the CRUD can finish it's tables upgrades, and that should solve the problem.

**Comment by SchizoDuckie** [comment]
Possible fix for this in 384833df0df3a1e24a7bc4b1b17d42effcc05bf9

**Comment by garfield69** [comment]
The new timings do appear to have helped. I two migrations runs I performed, both times the refresh-database-from-trakt.TV have kicked off.
Am still seeing one failed promise near the start of the log.
https://cloud.githubusercontent.com/assets/6933240/5932613/351b1c9a-a716-11e4-83dc-fa662c00c3fb.png

**Comment by SchizoDuckie** [comment]
Thanks for the log. I'll have to see where that error creating table comes from

**Comment by SchizoDuckie** [comment]
Going to close this as no users reported errors relating to this so far.
