### ISSUE TITLE
Trakt Import - Merge the collection list and watchlist into a single list

### ISSUE THREAD

**Issue by Js41637** [SchizoDuckie/DuckieTV#336]
Currently when you import from trakt, you receive your collection, shows in your library and your watchlist, what episodes you've watched in shows. These two are seperate lists and display seperately resulting in double serie posters, one for collection, one containing watched episodes. SchizoDuckie said it should be possible to merge them.

**Comment by garfield69** [comment]
I don't believe that merging the collected and watched show lists is necessary to solve the double series posters reported in this ticket.

As we fetch the watched shows from trakt.tv, we push the series to the TraktTVSeries array. This array is used by the trakt-import html to display the series poster with the progress-ear-mark and completed-ear-mark.

When we then fetch the collected shows, we are currently doing a push to traktTVSeries again, resulting in the duplication of the posters as originally reported in this ticket's first comment.

The solution is to only push to TraktTVSeries if the show is not already there.

I think this will be a simple matter of just moving one statement down a line in the TraktTVCtrl.js but first I'll need to set a Trakt development test account and some working shows to proof the change.

**Comment by garfield69** [comment]
Heck. As usual, what appears simple on the surface is more complicated underneath. It appears that the localSeries array is not being populated, leading to all series fetched from Trakt.TV to have a poster displayed leasing to duplicate posters when the collected list has series that were already processed in the watched list, or the other way around. Also, collected fetches appear to be processed before watched, despite the promise-then-then sequence supposedly performing watched before collected... I am getting a headache already. %-/
