### ISSUE TITLE
Empty serie events on calendar after import.

### ISSUE THREAD

**Issue by Js41637** [SchizoDuckie/DuckieTV#337]
I mentioned this in commit 2254e0900176d160fe85d0d8cd8aa51946b83472 , after I import from trakt and return to the calendar, there are several empty serie events, (the grey boxes with text in them but this time have no text in them and are thin), I don't have an image on me but, from what I gathered with the HoverTimer thing I 'fixed' these events have no data at all in them which caused the hover timer to spam errors when you hover over the events.

Reloading the page fixes the issue however and the events that were empty have text in them again. No idea what the cause, maybe lacking a calendar update after import has finished or after a serie has been added.

**Comment by SchizoDuckie** [comment]
Could you post your backup so that i can try to reproduce this?

**Comment by Js41637** [comment]
I have not been able to reproduce this again, closing.
