### ISSUE TITLE
EVENTS.md update

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#340]
I am in the process of updating the EVENTS.md listeners and publishers.
I am going to list any Cross references that are missing, which may require code clean up.

1. `favoritesservice:checkforupdates`
- [x] delete item 1
- [ ] do not delete item 1  
listener FavoritesService.js line 315
```javascript
    $rootScope.$on('favoritesservice:checkforupdates', function(evt, data) {
        TraktTVv2.resolveTVDBID(data.TVDB_ID).then(function(searchResult) {
            return TraktTVv2.serie(searchResult.slug_id);
        }).then(service.addFavorite);
    });
```
but no one is broadcasting.
2. `sync:processremoteupdate`
- [ ] delete item 2
- [x] do not delete item 2  
listener SyncManager.js line 106
```javascript
    $rootScope.$on('sync:processremoteupdate', function(event, progress) {
        console.log("Process storagesync remote updates!", progress);

        FavoritesService.restore(); // message the favoritesservice something has changed and it needs to refresh.
        //service.checkSyncProgress(progress);
    });
```
but no one is broadcasting.
3. `watchlist:check`
- [x] delete item 3
- [ ] do not delete item 3  
listener WatchlistCheckerService.js line 18
```javascript
            $rootScope.$on('watchlist:check', function(episode) {
                // fetch services that check for aired episode releases
                // fetch config for quality
                // resolve provider to check for download
                // cancel alarm when needed

            });
```
but no one is broadcasting.
However, this is clearly an unfinished module, so should probably be left alone.
4. Listeners and Publishers survey completed.

**Comment by garfield69** [comment]
@SchizoDuckie  could you review my previous post and tick any of the ones you are ok with me deleting. Thanks.

**Comment by SchizoDuckie** [comment]
Will do over the weekend. thanks.

**Comment by SchizoDuckie** [comment]
Sorry for the delay. You are awesome for making it this way :+1:

**Comment by Js41637** [comment]
Sorry, didn't mean to close :/
