### ISSUE TITLE
Custom Right Click Context Menus

### ISSUE THREAD

**Issue by Js41637** [SchizoDuckie/DuckieTV#343]
So while hovering over serie posters in the serieslist and the refresh data and delete buttons move in, I wondered if there was another way, I was thinking about how the old trakt.tv you'd click on posters and buttons would fade in over it, and thought that would be cool here but we can't do that because the posters need to be clicked but then I wondered about right click which opens the browsers context menu which isn't required at all in DuckieTV and maybe using it to add likes like Delete Serie, Refresh Data, ect. 

Anyway, did some googling, making your own context menu seems too much work but there is an angular module that does exactly this, [ng-context-menu](http://ianwalter.github.io/ng-context-menu/), doing a quick look at the repo however a user mentioned that it doesn't keep the scope of the element you click which isn't good but I don't know if there are other ways to pass scope data along.

Just an idea. Maybe it would just be better to do what was suggested before and add a little settings icon on the poster on mousehover that opens a small dropdown.

**Comment by SchizoDuckie** [comment]
I'm not really in favour of adding right-click actions, i think we could do better. The settings icon with a regular popup menu as you suggested would probably suffice

Some things that i'd like to see in there:

- Hide special episodes
- Hide from calendar
- Download all individual episodes (which would just launch a barrage of torrents if there's no <season> torrents available

**Comment by SchizoDuckie** [comment]
wont fix, new UI.
