### ISSUE TITLE
Next/previous Series buttons for the Series page

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#344]
As I am going through the whole database checking that watched episodes flags have survived the upgrade, I find myself flicking between the Library page and the Series page.
Jumping out to the library page and scrolling down to the next series is getting tedious.
It occurs to me that it would be eminently useful if while on the Series page, I could navigate directly to the next or previous series, via a couple little buttons, maybe on either side of the top row somewhere. Much faster that way.

**Comment by Js41637** [comment]
Sorry you've lost me, so in the serie details page you want like a button that goes to the next serie in the list (alphabetically)?

**Comment by SchizoDuckie** [comment]
that sounds illogical and very specific to your current workflow. may i
suggest a ctrl+click on a series poster to open the link in a new tab?

**Comment by garfield69** [comment]
@Js41637  yes, exactly.
@SchizoDuckie Oh, didn't know you could do that. That would work I guess, although I'm going to have 172 open tabs on chrome as I flick through each series in the library.

**Comment by SchizoDuckie** [comment]
What do you want to check then? Isn't it more reasonable to do this with an sql query or something?
