### ISSUE TITLE
v0.90 migration broke some people's watched indicators

### ISSUE THREAD

**Issue by SchizoDuckie** [SchizoDuckie/DuckieTV#345]
watchedAt still available, so I provided a migration. 

@garfield69  please test :) I also tweaked the timeouts to allow your souped up calculator some more breathing time :laughing:

**Comment by SchizoDuckie** [comment]
Commit: 384833df0df3a1e24a7bc4b1b17d42effcc05bf9

**Comment by garfield69** [comment]
Bugger. Not the result I was looking for. :disappointed: 

I started with a 0.82 DB that had all the episodes with valid WatchedAt/Watched pairs.

I can't tell by looking at the log when the DB Tables upgrade/migrations were done.
But the 0.91 migration-to-fix-WachedAt ran first, then the check-series-do-at-least-one-update last.
After the dust settled, I took a look at the DB.
Nearly all the Watched flags are set to 0, excepting just a few series/episodes.

Does this suggests that the error is happening during the Update from Trakt.TV process?

[0.82 database before]
https://www.dropbox.com/s/3qjygbbsz6d28on/DB082?dl=0
[0.91 database after]
https://www.dropbox.com/s/oe0xu5phvqnrnsp/DB091?dl=0
[local storage]
![image](https://cloud.githubusercontent.com/assets/6933240/5932652/0ae0a26e-a717-11e4-8e1b-585740745d58.png)
[Log]
![image](https://cloud.githubusercontent.com/assets/6933240/5932613/351b1c9a-a716-11e4-83dc-fa662c00c3fb.png)
![image](https://cloud.githubusercontent.com/assets/6933240/5932614/419ae25c-a716-11e4-9c5a-f1173ac9ebfb.png)
![image](https://cloud.githubusercontent.com/assets/6933240/5932615/4797d7aa-a716-11e4-9b1c-512069a22605.png)
![image](https://cloud.githubusercontent.com/assets/6933240/5932620/73ddd562-a716-11e4-9290-bedb1be081cf.png)

My brain hurts.

**Comment by garfield69** [comment]
confirmed.  Its the Trakt.TV update that's faulty.

On another machine I had the DB already up to the 0.90 migration done a couple days ago, and had all its WatchedAt/Watched pairs manually fixed.

Today I upgraded the code to 0.91 before starting it up.

 It ran the 0.91fixWatchedAt script, then it performed a scheduled daily trackt.TV update of 26 out of the 172 series.
Every one of the 26 series now has all watched flags set to 0.

**Comment by SchizoDuckie** [comment]
@garfield69 you're a fucking rockstar.
