### ISSUE TITLE
Trakt update service.

### ISSUE THREAD

**Issue by Js41637** [SchizoDuckie/DuckieTV#348]

**Comment by Js41637** [comment]
The response trakt gives either changed or something weird is happening but something is currently broken.

One of the problems is an easy fix which is changing `out.remote_updated = show.refreshed_at;` to reflect what is actually returned by trakt which is `out.remote_updated = show.updated_at;` [link](https://github.com/SchizoDuckie/DuckieTV/blob/angular/js/services/TraktTVv2.js#L106)

But I also have a question, been doing loads more tests and either i've completly missed something or something is wrong.

I am confused about [favorite.lastupdated & res.remote_updated](https://github.com/SchizoDuckie/DuckieTV/blob/angular/js/services/TraktTVUpdateService.js#L33). favourite.lastupdated is meant to be the same as res.remote_updated so when the remote is updated, they're different but when I log the dates, they are both always the same as my system date. Is that normal? and then when I deliberately set a date in the database to null, it logs it as null AND being the same, http://puu.sh/fmSst/e4c804a302.png

**Comment by garfield69** [comment]
@Js41637  For what its worth, I am just noting that I have not had any problems with the update cycle on any of my production or development versions. 
Perhaps you should consider doing a complete reset?
Perform a DuckieTV show Backup, a Chrome extensions Trash, a clean install of the DuckieTV extension and a show Import.

**Comment by Js41637** [comment]
I know, that's why I said something is weird, when I tested on Canary the update seemed to work fine which doesn't make sense considering the code references `show.refreshed_at` which doesn't exist but my normal chrome version refused to update and I set the dates back to make it check but it just didn't and in the end I just edited the database and set all the lastupdated on the series to null which then updated correctly when I set the trakttv.lastupdated to a few days prior.

**Comment by garfield69** [comment]
@js41637 you are correct about the refreshed_at -> updated_at. They must have changed the API v2 returns after Schizoduckie coded the solution.

**Comment by garfield69** [comment]
Man, Cloudflare is not delivering for Trakt.TV today. I have been inundated with server errors, from 500 Internal Server Error, 502 Bad Gateway, 504 Gateway Time-out, 520 Origin Error. Bah!

**Comment by Js41637** [comment]
Yeah I noticed when I was gonna do some testing, earlier, had heaps of errors.

**Comment by SchizoDuckie** [comment]
Let me know if the new API endpoint helps.

**Comment by garfield69** [comment]
Looking good. No server errors since I changed it last night.
  ----- Original Message -----

**Comment by garfield69** [comment]
@Js41637  So can we close this, or is there something you want to follow up ?

**Comment by Js41637** [comment]
I've been meaning to do some proper tests but, I don't see why it shouldn't work properly now that the change was applied.

**Comment by garfield69** [comment]
Spoke too soon :disappointed: the new API URL just now served up heaps of 504 (Gateway Time-out), 520 Origin Error,  and 503 (Service Unavailable: Back-end server is at capacity).
Must just be that time of day. Darn. Time to go to the beach! \o/
