### ISSUE TITLE
adding character names against the list of actors

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#351]
I am thinking of adding to the list of actors the names of the characters they play.
Mock-up below
![image](https://cloud.githubusercontent.com/assets/6933240/6086594/05bddbd8-aea8-11e4-9650-4f6d40007803.png)
value your opinion: is it too cluttered, useless info, go for it?

**Comment by SchizoDuckie** [comment]
I would probably remove the "as" in favor of the characters they play
behind the name in between ( )

This also removes the need to translate the phrase

**Comment by garfield69** [comment]
like this?
![image](https://cloud.githubusercontent.com/assets/6933240/6087449/66d6ecae-aeb0-11e4-8ac3-9bd338252439.png)

**Comment by SchizoDuckie** [comment]
Yea sweet! Are actors clickable as well?

**Comment by garfield69** [comment]
a click doing what?

**Comment by SchizoDuckie** [comment]
oh nevermind, i thought trakt.tv had actors links as well to detailed info,
they don't :)
