### ISSUE TITLE
TraktTV update service for users on GMT date ahead of the traktTV server

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#353]
I think there may be an issue for users whose local time zone is ahead of the date that the TraktTV server runs on.
I am going to try to lay out my reasoning, please validate and point out any errors.
Taking NZT as an example:
when a user on NZT starts up DuckieTV during the first 12 hours of the day, the TraktTV server's date is still (from the point of view of the user) 12 hours behind, yesterdays date.
In this example, NZT is 13-02-2015 and TraktTV is 12-02-2015.
So the TraktTVUpdateService code performs an update check, but does not get any updates since the request sent to TraktTV was for  updates since  NZT 13-02-2015 of which there are none on the TraktTV 12-02-2015 servers.
However, the TraktTVUpdateService now saves the local storage trakttv.lastupdate date as NZT 13-02-2015.
This means that for that user, there will not be any updates for the remainder of the NZT day since the traktTVUpdateService code will no longer run update checks during NZT 13-02-2015.
The only time this user can get a successful update is if the check runs after lunch on NZT 13-02-2015.

Maybe we need to save whether or not an update check fetched any updates, and only save trakttv.lastupdate if updates were fetched ?

**Comment by SchizoDuckie** [comment]
May I suggest parsing the remote time using moment.js? (in the same way that the scenenameresolver does
