### ISSUE TITLE
sort episodes in calendar

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#354]
Was thinking to have the episodes in each of the calendar's day boxes be sorted by episode title, episode number.

**Comment by SchizoDuckie** [comment]
They're sorted by starttime. By title would make very little sense

**Comment by garfield69** [comment]
Okely Dokely.

**Comment by garfield69** [comment]
Dang boy,
there you were moaning about having so many issues on your plate, and in the space of an hour you go add another 14 :-b There's a word for that, escapes my mind right now ;-)

**Comment by SchizoDuckie** [comment]
lol yea needed to do a little braindump after visiting NG-NL (Dutch angular
conference)
