### ISSUE TITLE
Look into webpack for building

### ISSUE THREAD

**Issue by SchizoDuckie** [SchizoDuckie/DuckieTV#355]
http://webpack.github.io/

**Comment by garfield69** [comment]
complete with the deployment of https://github.com/DuckieTV/duckietv-builder and the successful publishing of DuckieTV 1.1.4 to all supported platforms.

**Comment by garfield69** [comment]
Oh, bugger, wrong issue, sorry.

**Comment by SchizoDuckie** [comment]
quite happy with how it currently works. scratching this.
