### ISSUE TITLE
Observation: downloading .torrent generates a log entry

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#369]
I don't recall when this started, but any time I use the menu to download a .torrent, a message from Chrome  shows up in the log
```
Resource interpreted as Document but transferred with MIME type application/octet-stream: "http://torcache.gs/torrent/<name>.torrent".
```
It is not an error message, and it does not impact operations.

**Comment by Js41637** [comment]
Not an expert. But this could be a server-side issue, server says it is sending a document but actually sends `application/octet-stream` which I think is a binary file.

**Comment by SchizoDuckie** [comment]
THis is a warning issued by chrome when it sends a mime-type that's not
what the client expects. Nothing we can do here afaik.
