### ISSUE TITLE
Support for indirect Trakt.TV login via twitter,facebook or google+

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#370]
as raised by this [Reddit](https://www.reddit.com/r/duckietv/comments/2vlc2g/announcement_v094_released_should_be_more_stable/), look into supporting sign in to trakt.tv via facebook, twitter or google+ assuming the Trakt.TV v2 API allows for it.
![image](https://cloud.githubusercontent.com/assets/6933240/6224322/fdb4fb6c-b6de-11e4-8349-0f571378f605.png)

**Comment by Js41637** [comment]
Hmm, doesn't seem to be any mention of logging in regarding third party login services.

**Comment by Js41637** [comment]
Ok so apparently if a user registers to trakt with a third-party, they need to set a password on their trakt account or something. Either way, the token system that we use currently doesn't support logging in with third parties yet.

**Comment by SchizoDuckie** [comment]
note on this: there is a new PIN auth method with trakt.tv's staging api that should help resolving this

**Comment by SchizoDuckie** [comment]
Apparently this is also the way to fix the 'watched/history' sync bug. The method now lists 'oAuth required' at the spec on Trakt.

**Comment by Js41637** [comment]
Ok but I tested the current method we use on their API test page and it still responded it worked and was fine.

**Comment by SchizoDuckie** [comment]
Thanks. I will compare the requests.

**Comment by SchizoDuckie** [comment]
Fixed with the pin auth
