### ISSUE TITLE
Some active magnets not showing on calendar

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#372]
Possible bug as raised on [Reddit](https://www.reddit.com/r/duckietv/comments/2w6krb/%C2%B5torrent_progress_bar/)
>schizoduckie
>Were you instantiating the downloads from the show/season/series page and then they were not updating on the calendar? that could be a bug where the reference to the torrent was not saved on the episode in the database.

>Traspen 
>I initiate the download directly from the calendar. I click on the link, select "Search for a .torrent/magnet" and then select the magnet icon for the item I want to download. I do this for each episode and some of them show the progress bar and some don't.
>I go to the DuckieTorrent area to see if they're in there, and sure enough they are. I re-pair to µTorrent and authorize it but they (the ones that didn't have a progress bar) still have no progress bar. The ones that did, still do...

**Comment by SchizoDuckie** [comment]
My gf also reports that this has been happening. I'll rework the monitoring logic to run through the new TorrentMonitor

**Comment by SchizoDuckie** [comment]
Hmm nice one.

Observations:
TorrentMonitor needs a hook to some load event in DuckieTorrent to know that all the torrent data has been received, so that we can monitor if a magnet hash actually still exists in the torrent client before launching it again.

**Comment by SchizoDuckie** [comment]
Showing the user an indicator now when the torrent was added (until there is a progress %) 
![image](https://cloud.githubusercontent.com/assets/111710/6276720/2a5e7642-b889-11e4-8af8-d357fcf75054.png)
