### ISSUE TITLE
Zoom option for standalone

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#374]
as raised in [Reddit](https://www.reddit.com/r/duckietv/comments/2wc0bg/duckietv_is_loading_last_weeks_episodes_to/),
> tvisionary
>how about allowing a user to use the "control +" and "control -" ability to size the text for easier reading.

Also add navigation arrows and/or history so users can return back to previous pages, since clicking a link replaces current page instead of opening a new one
 OR
fix standalone ignoring target="_blank" directive.

**Comment by SchizoDuckie** [comment]
It looks like we want to target some options here: (zoomLevel) 

https://github.com/nwjs/nw.js/wiki/Window

Also, could be sweet and transparent if we actually implement a target="_blank" directive for when in node_webkit

**Comment by garfield69** [comment]
relevant function is  zoomLevel.
example
```    win.zoomLevel = 1.2;
```

**Comment by garfield69** [comment]
@schizoduckie, how would I introduce a reference to SettingsService in app.standalone so I can use SettingsService.get() and SettingsService.set() ? Thanks.

**Comment by garfield69** [comment]
@schizoduckie never mind, figured it out, used a duckietv.run :-)
