### ISSUE TITLE
add EZTV.ch  and RARBG as search providers

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#375]
as raised on [Reddit](), add EZTV.ch as a search provider.
>tvisionary
>Since this is a TV application, why not allow loading from eztv.ch as well as kickass and piratebay?

**Comment by SchizoDuckie** [comment]
note to self: Implement generic search provider, filter results to match season and episodenumber. optionally refactor generictorrentdialog interface to accept a serie/episode to move the logic there

**Comment by garfield69** [comment]
changed .it to .ch
note: the .it domain was released by the domain service and snapped up by scammers who have cloned the old eztv site and are duping unsuspecting eztv users into downloading malware.
the .ch domain is the official eztv address for now.

**Comment by SchizoDuckie** [comment]
EZTV is not currently scrapeable.

I did some experiments and they're using some funky cloudflare protection that says content-length is 54 and then serve a full page. It trhows off XHR requests completely, will probably only be possible in the node-webkit version, so iḿ closing this for now.
