### ISSUE TITLE
serieslist.adding cache doesn't get flushed when a serie is deleted

### ISSUE THREAD

**Issue by SchizoDuckie** [SchizoDuckie/DuckieTV#376]
resulting in deleting and re-adding a show -> showing the 'added' checkmark even when it's deleted.

**Comment by garfield69** [comment]
- [ ] move serieslist.adding to FavouriteService as documented in line 12 of js\controllers\serieslist\SeriesListCtrl.js as a todo comment
- [ ] also impacted are the $scope.isAdding and $scope.isAdded routines in js\controllers\settings\BackupCtrl.js
- [ ] and js\controllers\sidepanel\TraktTVCtrl.js
