### ISSUE TITLE
popup below screen

### ISSUE THREAD

**Issue by Geneocide** [SchizoDuckie/DuckieTV#379]
My calendar is extended because of many shows on the same day, so this might not happen in all cases. For me, though, for some shows towards the bottom of the list on days in the last week of the month, if I click on them and get the popup for episode details, mark as watched, etc. Some of the options are unreachable. Sometimes they're invisible, and sometimes clicking on them registers as a click on the "View Your Local Library" bar at the bottom.

A possible solution would be to have the popup display above instead of below the clicked episode in cases when it would display below the bar.

Hopefully the image below makes clear what I'm talking about.

![image](https://cloud.githubusercontent.com/assets/1274287/6375452/6b2cd0a2-bcd4-11e4-9ff4-952da3350ef9.png)

**Comment by SchizoDuckie** [comment]
Thanks for reporting, this will be resolved with the next few builds as
we'll do away with the popup menus in the calendar completely :)
https://www.youtube.com/watch?v=fhgmgi5N5ZY <-- here's what we're up to

**Comment by Geneocide** [comment]
Ah, looks like. Thanks.

**Comment by garfield69** [comment]
In the mean time, while you wait for the next release, you could access those calendar events by switching the calendar to week mode. This would give you more real estate to access the popups.
