### ISSUE TITLE
Any questions on the refactoring? Drop 'em here

### ISSUE THREAD

**Issue by SchizoDuckie** [SchizoDuckie/DuckieTV#380]
So yeah, quite the bomb i dropped on you guys this weekend with the big ui-router refactoring and the cleanup of app.js and applying some more of angular's best practices that i've learned.

I remember when I first saw the style and was pretty confused, but I think it's much more self explanatory what's happening now if you understand these things:

UI-Router
=======
Awesome introduction into UI-Router and the differences with angular's native $route that we were using before here: http://slides.com/timkindberg/ui-router#/

Injections
=======
A controller preferrably gets it's state variables injected. You can see this happening best with the [SidepanelEpisodeCtrl.js](https://github.com/SchizoDuckie/DuckieTV/blob/angular/js/controllers/sidepanel/SidepanelEpisodeCtrl.js#L1). Amongst the other dependencies like SceneNameResolver and TorrentDialog you'll see that an injection of variables named serie, episode and season is expected.

These are resolved by the 'resolve' part of [js/app.routes.js](https://github.com/SchizoDuckie/DuckieTV/blob/angular/js/app.routes.js#L167). For every variable name that you require you can return a promise that will fetch it.

States
=====
Read all about states [here](https://github.com/angular-ui/ui-router/wiki/Nested-States-%26-Nested-Views) 
I'm using nested states for for instance the [serie.season.episode  state](https://github.com/SchizoDuckie/DuckieTV/blob/angular/js/app.routes.js#L268) here for instance. These are nested in the way that first the serie state is resolved (plus it's dependencies), then the serie.season state and it's dependencies and then the episode state. So when it lands at tab.html#/series/118/season/720/episode/17562 all of these variables will be resolved and can be declared as a dependency for the controller. Super powerful.

Sticky states
==========
This is an awesome UI-Router plugin: [UI-Router extras.sticky](http://christopherthielen.github.io/ui-router-extras/#/sticky) It basically makes sure that you can change the url of the page (the state) and that the DOM rendered by the previous state doesn't get cleaned up, all by flagging it as 'sticky'. So now you can switch between tab.html#/series/118/season/720/episode/17562 and tab.html#/settings/utorrent in the addressbar, and the serieslist panel will stay open while the utorrent settings are shown on the right.

Finally some notes on the rest of the cleanup / refactoring
============================================
As you may have noticed there's no more controller dependency hell inside app.js because i'm using one global variable to refer to the [DuckieTV angular.app instance](https://github.com/SchizoDuckie/DuckieTV/blob/angular/js/app.js#L4) instead of making sure that every single module was loaded before declaring the angular.app. It's a different way of thinking that I couln't yet wrap my head around when I first started angular. I think you'll understand what's happening without any problems.

This also allowed me to move all of the initialization code and config blocks away from app.js and into their own files. All because you can create multiple .run() blocks, something i've known before but never used, and it's [brilliant in it's simplicity](https://github.com/SchizoDuckie/DuckieTV/blob/angular/js/services/TorrentMonitor.js#L32) because a module can now do it's thing completely separated from the rest of the app.

If you have any questions, or see dead code that still needs cleaning up or removing, please feel free to shoot them here, or tag commits with this issue number, i'm trying to work through all of it to make things more pleasurable, hope you guys learned something too  :+1:

**Comment by garfield69** [comment]
I see lots of reading in my horizon ;-)
