### ISSUE TITLE
Regular database updates due to ratings being renewed.

### ISSUE THREAD

**Issue by SchizoDuckie** [SchizoDuckie/DuckieTV#383]
It's starting to annoy me a bit, and i'm thinking about not updating the ratings count unless they have changed by a treshold like 100.

Any objections?

**Comment by garfield69** [comment]
sounds like a good idea. I get about 90 series updated every day that take about 4 minutes to complete, so anything to speed that up by dropping micro-updates is fine by me.

**Comment by garfield69** [comment]
note: out of my 11737 episodes only 4235 have a ratings count above 100.
additional stats:
7143 eps with count gt 25
6009 >50
5125 >75
2719 >200
1394 >500
626 >1000
Perhaps a threshold of 100 is to high?
Suggest starting with 25, and bump it up +25 until we reach a happy place?

**Comment by SchizoDuckie** [comment]
sounds good to me

**Comment by SchizoDuckie** [comment]
Works great so far. closing this.
