### ISSUE TITLE
DuckieTV DEV 0.95 Marvel's Daredevil sidepanel issue

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#385]
Having added Marvel's Daredevil to the library, when I go to view serie or episode details I am presented with a blank side-panel.
![image](https://cloud.githubusercontent.com/assets/6933240/6705819/3688de28-cdbd-11e4-9638-2cdf586abb07.png)

Research shows that of the 180 serie I have in the database, this is the only one that causes such a reaction.
Loading Marvel's Daredevil on DuckieTV PROD 0.94 does not cause any presentation issues.
Examining the Database I cannot find any data details that would explain the reaction.
Before I spend more time digging into this deeper, could either of you load this serie on your 0.95 to confirm the same reaction?
Thanks.

**Comment by SchizoDuckie** [comment]
Something is very borked here.

![image](https://cloud.githubusercontent.com/assets/111710/6705869/3a4b88da-cd59-11e4-8115-5d35ef18db07.png)

**Comment by Js41637** [comment]
Am getting the error on TypeError: this.getLatestSeason is not a function while trying to open Marvel's Daredevil

**Comment by Js41637** [comment]
Can't really find anything weird getting returned from trakt
![image](https://cloud.githubusercontent.com/assets/6258213/6706399/3cf17812-cdb1-11e4-8d3e-4ce8e83d50db.png)
Season doesn't have any tvdb id although that wouldn't be an issue would it? Also I can't see how it can't have a tvdb id considering it is synced from tvdb

**Comment by SchizoDuckie** [comment]
I see exactly what's going wrong. It has no tvdb_id.

**Comment by Js41637** [comment]
It relies on season TVDB Ids? And 0.94 doesn't?
