### ISSUE TITLE
Compile Instructions

### ISSUE THREAD

**Issue by Noclip21** [SchizoDuckie/DuckieTV#387]
I cant seem to find the compile instructions for its standalone version. When will these instructions be available so we can port the program to our machines?

**Comment by SchizoDuckie** [comment]
Thx for addressing this :)

Compilation currently involves running web2exe and manually loading the project.

But, if you want to run the standalone yourself, the process is really simple:

- Clone the repo
- Download [nw.js](http://nwjs.io/) for your platform
- Extract all files to the DuckieTV repository
- run ``nw.exe``  or  ``./nw`` 

Now you can just work in the directory and pull repo updates with git if you want to run the latest version always :+1:  Enjoy!
