### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Noclip21** [SchizoDuckie/DuckieTV#388]
What's the program's license? Does it respect our 4 essential freedoms?

**Comment by SchizoDuckie** [comment]
Hi :) 
I haven't really thought about a license before, but I think this would be about it:

*You have*:

- [x] The freedom to run the program as you wish, for any purpose (freedom 0).
- [x] The freedom to study how the program works, and change it so it does your computing as you wish (freedom 1). Access to the source code is a precondition for this.
- [x] The freedom to redistribute copies so you can help your neighbor (freedom 2).
- [x] The freedom to distribute copies of your modified versions to others (freedom 3). By doing this you can give the whole community a chance to benefit from your changes. Access to the source code is a precondition for this.

*You do not*:
- [ ] Have permission to ask money for DuckieTV, in any shape, way or form, by wrapping it in an ad-installer or adding ads to the program ever.
