### ISSUE TITLE
add strike (getstrike.net) as a search provider

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#389]
as raised on [Reddit](https://www.reddit.com/r/duckietv/comments/300q1l/have_you_seen_this_strike_torrent_search/) add strike as a search provider.
even has an [API](https://getstrike.net/api/)

**Comment by Js41637** [comment]
Well API doesn't help cause our current Torrent System uses Dom Prasers, quickly had a play arrow, clicking and searching doesn't update the URL but I found adding `/q=query` will search for what you want however not sure what the url parameter for Sorting by seeders is. Gotta go but I imagine there would be one.

**Comment by Js41637** [comment]
Already sorts by seeders which is good however a problem is the magnet link is on the torrent details page and not immediately available by DomPrasing.

Also I quickly mocked up the code for it but it doesn't seem to work, I think it has to do with the way it handles url parameters or how it dynamically loads, simply searching will return a page with results not yet loaded. 

API might be the only way to go.

**Comment by Codeusa** [comment]
I've updated the API, a lot of end points have changed/new ones are being offered and your cerns like the magnet link not being available are fixed on the API end

https://getstrike.net/api/v2/torrents/search/?phrase=Slackware%2014.1%20x86_64%20DVD%20ISO

https://getstrike.net/api/v2/torrents/search/?phrase=windows&category=Applications&subcategory=Windows

check the API page for more documentation 

https://getstrike.net/api/

**Comment by SchizoDuckie** [comment]
Super sweet! Thanks! <3

**Comment by garfield69** [comment]
@js41637 good job adding Strike to Duckietv :+1: 

However, a problem (apparently carried over from Dtv prod 0.94) is impacting on dev 0.95 torrent searching with either Strike or ShowRSS.info.

test conditions: set either Strike or showRSS.info as the default search provider.

test1:
any torrent search results results in **not found**.
![image](https://cloud.githubusercontent.com/assets/6933240/6861980/41622d8e-d4a4-11e4-9246-281378916482.png)
test2: select KAT and get results, then select Strike (or showRSS.info) and apparently get *exactly* the same results as KAT
![image](https://cloud.githubusercontent.com/assets/6933240/6861998/9be4a8fe-d4a4-11e4-9202-00c6804a2fe4.png)
![image](https://cloud.githubusercontent.com/assets/6933240/6862004/c1fda9dc-d4a4-11e4-9dac-44193c8c4f66.png)
test3: pick torrentz.eu then pick ShowRSS.info and get *exactly* the same results as torrentz.eu.
![image](https://cloud.githubusercontent.com/assets/6933240/6862012/f5686000-d4a4-11e4-8a91-fccaec50d2d1.png)
![image](https://cloud.githubusercontent.com/assets/6933240/6862018/0b59deb6-d4a5-11e4-8f87-8375854aedc5.png)

**Comment by garfield69** [comment]
@js41637 good job adding Strike to Duckietv :+1:
Apologies. the issue I had with Strike and ShowRSS.info is due to my Chrome/WinXP.
I am getting `net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH` for these as well as OPB and TPB.
The only search providers that work for me are KAT and torrentz.eu.
Once again, sorry about the bug miss-information.

**Comment by Js41637** [comment]
Yeah the current TorrentDialogue system needs smarter error handling, I think some of the providers return something when nothing is searched and whenever you change providers or a 404 is returned while searching, it will display what was already there instead of displaying like 'Nothing found'. 'Nothing found' does show up sometimes but only if a search or something hasn't already returned results.

**Comment by Codeusa** [comment]
Chrome on xp doesn't support modern SSL, thus your connection is blocked,
switch to firefox

**Comment by garfield69** [comment]
Thanks for the suggestion, however DuckieTV (either as the Chrome extension
or under the Node Webkit Standalone) depends on WebSQL which FireFox does
not support, so no joy there. :-(

  _____

**Comment by Codeusa** [comment]
Just wanted to quickly update that strike should work fine in xp and chrome now

**Comment by garfield69** [comment]
confirmed.
 Thank you.
  ----- Original Message -----

**Comment by SchizoDuckie** [comment]
Awesomeness! Thanks!
