### ISSUE TITLE
First letter in search bar gets eaten when adding new shows

### ISSUE THREAD

**Issue by bkd69** [SchizoDuckie/DuckieTV#390]
When I go to the 'Add New Shows' screen, the first letter I type in the search bar will vanish if I don't type a second letter fast enough. Chrome on Win 8.1.

**Comment by Js41637** [comment]
Yeah can confirm, probably a side affect but for a search to execute it requires 2 letters or more. Just going to have to type a bit faster. This is fixed in next version anyway.

**Comment by garfield69** [comment]
This applies to v0.94 and is resolved in the next release which uses a re-written UI.
