### ISSUE TITLE
custom scheduling for historical seasons and binge dump shows

### ISSUE THREAD

**Issue by bkd69** [SchizoDuckie/DuckieTV#391]
I should like to have the option to customize the calendar scheduling of any given show, as well as setting an arbitrary season+episode start point, for catching up with historical seasons. This would also work for binge dumps of stream service shows, where all the episodes get posted on a single day.

For example, Person of Interest is in its third season, but since I want to catch up on it, so I should be able to tell DuckieTV to start with S1E05, and schedule it for every Tuesday and Thursday until we're all caught up. Likewise for a binge dump, like The Unbreakable Kimmy Schmidt, I could tell it to just schedule it for every Sunday, and it would start at episode 1, and increment it from there.

**Comment by Js41637** [comment]
Was just talking to someone about what you said, honestly I am not sure what to make of it, it would require quite a lot of changes to make something like this work. Cause it is a calendar of when shows air. You're requesting a personal calendar that you can add shows on when you want to watch them. It's actually a neat idea but i'm not sure if it's worth perusing.

**Comment by bkd69** [comment]
We start by adding a field to our store of show titles, called 'scheduling', with values of either 'network' or 'local'. At present, all shows are network scheduled, which is to say, Duckie calls out to trakt.tv with the show title, and the date range of interest, and trakt.tv returns(*) the title, SxEy number, date of air, and episode title+synopsis, for each scheduled occurence in the requested time frame, which Duckie then dutifully records on the calendar.

With custom scheduling added, what happens when we add a show, is that we're then asked whether we want to use a custom schedule, at which point we're prompted  for the starting season and episode, and presented with a 7 day checklist to select which days we want to schedule the program for.

If we select the custom option, DuckieTV then sets the scheduling field to 'local', and records the weekdays that the program is scheduled for, maybe having a string of digits with 1 for Sunday and 7 for saturday, so a Mon-Fri schedule would be '23456', or as a binary setting of 00111110, or whatever's most convenient for the date function used in the code. This is followed by DuckieTV checking the dates of the future days of the week, and recording incremented SxEy numbers followed by the appropriate dates, for either 7 or 30 days out, depending on how things are already set. Now when the calendar writing occurs, DuckieTV is still going to have to pull the title and synopsis info for the given episode from trakt.tv, which gives a chance for some error checking, in regards to the season turnover. See, when trakt.tv returns a null value for S1E23, or E24, or E25, or whichever episode, that will be the indication that the season has to be incremented, so it now checks for S2E01, and starts incrementing the episode numbers from there.

*: More or less. I'm just basing this on DuckieTV's behavior, so there might be some minor differences in the details, but nothing significant

**Comment by SchizoDuckie** [comment]
While I applaud the significant amount of time you put into thinking out this feature, I really don't see why you would torture yourself by rescheduling a tv show for an arbitrairy date. It sounds like *a lot* of work and conditionals for your personal use case.

I cannot see myself using it like this
