### ISSUE TITLE
Fix Torrent Custom Client Inject

### ISSUE THREAD

**Issue by Js41637** [SchizoDuckie/DuckieTV#392]
Memo for SchizoDuckie to ^

Basically custom clients (ShowRSS & Strike) are manually 'hacked' in because there isn't proper support for them yet.

**Comment by SchizoDuckie** [comment]
Note to self: rework this so that they register themselves in the run block the same way the DuckieTorrent clients do

**Comment by garfield69** [comment]
this ticket may be the reason why you cannot select Strike or ShowRSS as a default search provider.

In settings/torrent_search_engines, only the regular providers show up
![image](https://cloud.githubusercontent.com/assets/6933240/6862110/d781e900-d4a7-11e4-89a9-bd0d91d39982.png)
but once you have used a search with Strike or ShowRSS then the settings subsequently shows them.
![image](https://cloud.githubusercontent.com/assets/6933240/6862124/070e05b4-d4a8-11e4-9cfc-df220a5a0343.png)
However, if you then set either Strike or ShowRSS as a default provider, and restart DuckieTV the log shows `GenericTorrentSearch.js:133 Invalid search provider detected:  Strike  defaulting to  ThePirateBay`

**Comment by Js41637** [comment]
Yeah this is the reason, because they are 'hacked' in only when the TorrentDialogue is opened, it adds them to the list however because they're not on the actual list of torrent providers, DuckieTV defaults to TPB.

**Comment by SchizoDuckie** [comment]
Todos:

[ ] refactor call in settings
[ ] do some detection on registering a search client on if it's an instance of a custom client (that provides at least a search and a cancelsearch method) or if it's a set of specs for GenericSearch to  use
[ ] make torrentDialog directive fetch list and implementation from TorrentDialog service
[ ] rename TorrentDialog service to TorrentSearchEngines service
