### ISSUE TITLE
Highlighted date not updating

### ISSUE THREAD

**Issue by robertcrew** [SchizoDuckie/DuckieTV#393]
Hello,  I've noticed the highlighted date doesn't change overnight if I leave DuckieTV running.  I have to exit the program and relaunch it to update the highlighted date.
![duckietv_date_issue](https://cloud.githubusercontent.com/assets/11747550/6934021/ef890106-d875-11e4-8dec-a5231e13d08e.png)

**Comment by Js41637** [comment]
Yep we are aware of this issue, a ticket has already been raised #378

**Comment by garfield69** [comment]
Great find!
So which windows OS are you running the x32 Standalone DuckieTV on?
  ----- Original Message ----- 
  From: robertcrew 
  To: SchizoDuckie/DuckieTV 
  Sent: Wednesday, April 01, 2015 4:20 PM
  Subject: [DuckieTV] Highlighted date not updating (#393)


  Hello, I've noticed the highlighted date doesn't change overnight if I leave DuckieTV running. I have to exit the program and relaunch it to update the highlighted date.

**Comment by Js41637** [comment]
Looks windows 8-y

**Comment by robertcrew** [comment]
Yes, sorry, Windows 8.1  I did look through the previous issues, but must
have missed that one.

I love the program by the way, I've told all my friends to stop using the
eztv shows page and use DuckieTV as well as Pimp My uTorrent.

Regards,

Robert Crew
