### ISSUE TITLE
DuckieTV DEV 0.95 calendar week view problem

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#394]
The right-most calendar day box in WEEK view remains empty.
Only occurs with DuckieTV DEV 0.95, in prior versions it appears to work as designed.
Can anyone else confirm?
MONTH view showing good data
![image](https://cloud.githubusercontent.com/assets/6933240/6986573/faa3930e-da9a-11e4-83de-47c8a11bee10.png)

WEEK view showing missing data
![image](https://cloud.githubusercontent.com/assets/6933240/6986609/4751c00e-da9b-11e4-81b1-cdebcef6b2df.png)

SUN-MON mode not relevant, nor is the SHOW-HIDE specials or the SHOW-HIDE serie settings.

**Comment by garfield69** [comment]
narrowing it down a little bit. if the event has been watched, it shows up.

**Comment by garfield69** [comment]
oops, no sorry. prior comment about watched events does not hold true in all WEEK view circumstances.

**Comment by SchizoDuckie** [comment]
Could boil down to the select that fetches the event for the daterange,
that code has been refactored for the new release, possibly a < where it
should have been <= ?

**Comment by SchizoDuckie** [comment]
Hero
