### ISSUE TITLE
auto-download does not always pick the correct episode for download

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#396]
as described in this [Reddit](https://www.reddit.com/r/duckietv/comments/32464z/chrome_extension_downloads_wrong_episode/)

inkedfusion
>I don't realize till the episodes are downloaded but it keeps downloading the previous weeks episodes on most shows. For example, Last night I received a magnet link automatically for Big Bang Theory Episode 19. But the calendar says this week is episode 20. I end up having to search and redownload the episode manually or click on the show on that calendar date and get the episode from there (which works correctly)

schizoduckie
>Yeah i've noticed the same. There is a trend in the torrent search engines where they actually ignore the search string you enter and return some different results. I guess the autodownload will have to do some more rigorous checks to verify if it actually has the correct result. Will look into that!

**Comment by Js41637** [comment]
Yeah if a torrent is up yet it will return other results for serie ordered by seeders which is usually previous episode.

**Comment by garfield69** [comment]
7bf44230b1acbfd8194f107715d14096c615571e only patched the torrentDialog and not the AutoDownloadedService.
