### ISSUE TITLE
DuckieTV 0.95 MONTH calendar view not hiding serie or specials

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#397]
related to work for #381
the MONTH calendar view is not applying the "hide series" or the "hide specials" options.

**Comment by SchizoDuckie** [comment]
dammit. it also broke my nice integration between the calendar and series / episodes list.
torrent magnet matching is broken, delete serie and refresh calendar too.

**Comment by garfield69** [comment]
has my update for replacing hideSpecials with filterSpecials fixed the
torrent magnet matching?
delete / refresh appears to be working for me now.


  _____

**Comment by SchizoDuckie** [comment]
delete refresh works indeed and torrent magnet matching too. my bad.
hide specials on calendar currently hides my complete doctor who (also the non-special episode)

also, i noticed that the nw.js version has a different zoom scale in comparision to the chrome extension:
(we need to tweak the default zoom scale i think)

**Comment by garfield69** [comment]
that's odd. I don't have any issues with my 'doctor who' specials/series
show/hide.
 
show specials on doctor who

hide specials on doctor who


I'll puts about with the standalone scale and see if I can find a matching
formula.

  
  _____

**Comment by SchizoDuckie** [comment]
okay, it's time for bed for me. all works fine now.
