### ISSUE TITLE
Torrent getProgress() rounding halts torrent auto-stop before 100%

### ISSUE THREAD

**Issue by SchizoDuckie** [SchizoDuckie/DuckieTV#402]
At least on my local Transmission.

Fix: Round to one decimal, straighten out the interface for this.

**Comment by SchizoDuckie** [comment]
related: autodownload should not run when episode.downloaded = 1

**Comment by garfield69** [comment]
Huh. I did not even notice that the getProgress function was in there twice!
  ----- Original Message -----
