### ISSUE TITLE
remove Cast from DuckieTV

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#403]
as per [Reddit](https://www.reddit.com/r/duckietv/comments/33mj9k/announcement_for_those_of_you_awaiting_chromecast/).

Task list:
- [x] delete img\chromecast_issue.png
- [x] delete img\chromecast_off.png
- [x] delete img\chromecast_on.png
- [x] delete img\utorrentconfig.png
- [x] delete js\controllers\sidepanel\CastCtrl.js
- [x] delete js\services\ChromeCast.js
- [x] delete js\vendor\cast_sender.js
- [x] delete templates\chromecast.html
- [x] edit \css\main.css 
- [x] edit gulpfile.js
- [x] edit js\app.routes.js
- [x] edit js\controllers\sidepanel\AboutCtrl.js
- [x] edit js\controllers\sidepanel\TorrentCtrl.js
- [x] edit js\directives\torrentRemoteControl.js
- [x] edit js\services\SettingsService.js
- [x] edit tab.html
- [x] edit templates\sidepanel\torrent-details.html
- [x] edit templates\torrentRemoteControl.html
- [x] edit _locales\de_de.json
- [x] edit _locales\en_us.json
- [x] edit _locales\es_es.json
- [x] edit _locales\fr_fr.json
- [x] edit _locales\it_it.json
- [x] edit _locales\ja_jp.json
- [x] edit _locales\ko_kr.json
- [x] edit _locales\nl_nl.json 
- [x] edit _locales\pt_pt.json
- [x] edit _locales\ru_ru.json
- [x] edit _locales\sv_se.json
- [x] edit _locales\zh_cn.json
- [x] edit events.md
- [x] edit readme.md
- [x] edit gh-pages/_posts/2015-01-01-screenshots.md

**Comment by SchizoDuckie** [comment]
Great work!
