### ISSUE TITLE
Double episode on the same day

### ISSUE THREAD

**Issue by lamaresh** [SchizoDuckie/DuckieTV#405]
I'm having an issue with some series of mine: for grimm and agent of shield i see the episode repeated 2 times in the same day. For grey's anatomy, instead, i see 2 episodes on the same day, for example 17th and 18th, and the next week i have 18th and 19th, and so on with every episode repeated 2 times. It's related to many TBAs in series episode list.

**Comment by garfield69** [comment]
If you are using the DuckieTV 0.94 production version, then it sounds like you have come afoul of the episode-clean up bug, which cc4b5296bc21b7c082eaadc8dd88c0cfa675ab13 fixes.
This will be included in the next upcoming release of DuckieTV.

The problem stems from Trakt.TV having periods of time where an episode changed its tvdb_id, a unique identification number. Without the clean-up fix in place, the obsolete duplicate episodes ar e not removed by DuckieTV during a subsequent Trakt.TV update cycle.

**Comment by garfield69** [comment]
If you are desperate for a solution before the next DuckieTV release, there is a method whereby you can clean-up your database, but it is fairly laborious.
It involves performing a DuckieTV settings backup, followed by a deletion of the database, and then a Import.

**Comment by bytehead-** [comment]
I've figured this, since I believe I saw something earlier about it.  And I thought .95 was going to be released 4/15? :stuck_out_tongue:  Or was it 4/1? :smile: I think I'll just deal with it until the .95 release, myself. :wink:

**Comment by lamaresh** [comment]
Thank you all! :)
