### ISSUE TITLE
DuckieTV v1.00 Dev SyntaxError: Unexpected end of input(anonymous function) @ js/services/TraktTVv2.js:190

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#406]
getting this error recently
![image](https://cloud.githubusercontent.com/assets/6933240/7361837/329bb0a8-edb4-11e4-94dc-e5e105151a88.png)
IDK.WTF.IGO!

**Comment by garfield69** [comment]
Its working now, so clearly I was getting some sort of error condition from Trakt.TV which traktTVv2.js was not handling.
I note in passing that 
```javascript
                    throw "Error " + err.status + ":" + err.statusText;
```
at line 191 returned `Error undefined:undefined`. This is due to the fact that err only has .message and .stack and not .status and .statusText

**Comment by SchizoDuckie** [comment]
Hmm yeah, so trakt.tv was not serving JSON content, which made the whole parser throw up. Could use some global http exception handler to notify the user

**Comment by SchizoDuckie** [comment]
Closing as we can't use global http exception handlers since many different apis and responses. Local services need to handle errors.
