### ISSUE TITLE
writing to db

### ISSUE THREAD

**Issue by lazania** [SchizoDuckie/DuckieTV#407]
Hey!
So I've had this problem for a while.. every time I enter DuckieTV, which is on a daily basis, I get a green load bar with "writing to db" on it. Now if it would've happened once/twice a week that would be cool, but when it happens twice a day, for a few months now, it becomes a bit troublesome. 
Is that normal? is there a way to lower the frequency of these auto-updates, as I'm sure nothing critical is changing that much over a day..

**Comment by garfield69** [comment]
Thank you for your report. You are right, 0.94 is doing updates way too frequently.
The next release of DuckieTV will improve updates by including 3d7efaaf2e3e211842254fff7f1df079ffa8fd08 which restricts updates to just once a day, and  22dde5a2b01f0c12d35887862d0b928a56b73a7b which limits the ratings updates until there have been at least 25 more.
