### ISSUE TITLE
Option to toggle calendar size

### ISSUE THREAD

**Issue by Js41637** [SchizoDuckie/DuckieTV#409]
Had an idea to toggle the size of the calendar events. Making them smaller to free up a lot more space for people will smaller resolutions and if we have a lot of shows. This is obviously for Month View, it just makes the events a little smaller which really helps with a full calendar

**Comment by Js41637** [comment]
http://puu.sh/hzKe9/fd65d9ac9d.gif

**Comment by garfield69** [comment]
Lovely. :+1:

**Comment by Js41637** [comment]
Shizoduckie wasn't completly sold on the idea of having a setting and thinks we should maybe just make the normal event height slightly smaller. I think over the recent changes the size of the events have gotten larger. Like to the size the download bar use to be. I actually rather like the current size it works well with the mark as downloaded green but not all people have a small screen or a lot of shows so I think making this a setting is better.

**Comment by garfield69** [comment]
I prefer the condensed look. :+1: 
I don't mind if the setting goes as long as the condensed look stays.

Until a decision is made here I will hold off creating the translations for this, obviously.
