### ISSUE TITLE
centralise searchString replacement/stripping

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#410]
There are currently 5 different places where a episode's name string gets stripped of non-alphabetic characters for use in torrent-searches.
```
Search "replace(/\'/g, '')" (1 hit in 1 file)
  js\services\TorrentSearchEngines\GenericTorrentSearchEngine.js (1 hit)
	Line 103:         what = what.replace(/\'/g, '');
Search ".replace(/\(([1" (4 hits in 4 files)
  js\controllers\sidepanel\SidepanelEpisodeCtrl.js (1 hit)
	Line 16:         return serieName.replace(/\(([12][09][0-9]{2})\)/, '').replace(' and ', ' ') + ' ' + SceneNameResolver.getSearchStringForEpisode(serie, episode);
  js\controllers\sidepanel\SidepanelSeasonCtrl.js (1 hit)
	Line 57:         return serieName.replace(/\(([12][09][0-9]{2})\)/, '').replace(' and ', ' ') + ' ' + SceneNameResolver.getSearchStringForEpisode(serie, episode);
  js\services\EpisodeAiredService.js (1 hit)
	Line 61:                 var searchString = name.replace(/\(([12][09][0-9]{2})\)/, '').replace('!', '').replace(' and ', ' ') + ' ' + episode.getFormattedEpisode() + ' ' + $rootScope.getSetting('torrenting.searchquality');
  js\services\SceneNameResolver.js (1 hit)
	Line 459:                     return (tvdbID in exceptions) ? exceptions[tvdbID].replace(/\(([12][09][0-9]{2})\)/, '').replace(' and ', ' ') : false;
```
Since all these routines perform the same function (correct me if I'm wrong), I propose centralising them into one common routine called by the others.
The benefit would be that there is just one place to maintain name search stripping code, and thus all search routines benefit from any updates.

**Comment by SchizoDuckie** [comment]
mmm they're doing different things in different cases though (except for the sidepanel triggers)

It'll not be logical to refactor this into one as far as i can see now

**Comment by garfield69** [comment]
Ah, but they are doing different things only because they go out of sync with each other...
they all should be stripping the !, and the quote, and the AND, and whatever.
no?

**Comment by SchizoDuckie** [comment]
I think the generictorrentsearchengine should be the only exception (Since there you want to actually search for exactly what you type) The rest is indeed all the same :)
