### ISSUE TITLE
Speed up WebSQL operations using UNION.

### ISSUE THREAD

**Issue by SchizoDuckie** [SchizoDuckie/DuckieTV#411]
http://stackoverflow.com/questions/1609637/is-it-possible-to-insert-multiple-rows-at-a-time-in-an-sqlite-database

sweet trick. could save *a lot* of time with a minimal patch.

Train of thought:

have CRUD.SqliteAdapter.Persist() queue up operations in an array with the query and a promise. Return the promise. Fire a setTimeout at a delay that grabs X queued queries off the stack and unions them. execute them at all at once and resolve the promises. 

Mental note: what about insert ids? Works only for update queries?

Return a minimal promise that just resolves the Persist() for each CRUD object when a union is done.

Max limit: 500 queries at once.

**Comment by SchizoDuckie** [comment]
Unfortunately, this doesnt work. Closing and forgetting about this.

**Comment by Js41637** [comment]
:(
