### ISSUE TITLE
Support for Deluge torrent client

### ISSUE THREAD

**Issue by Aerodynam1c** [SchizoDuckie/DuckieTV#412]
People recommend Deluge along with qBT, Transmission and Tixati as an alternative to uTorrent/BitTorrent so it was a bit strange that no one suggested it here, so I guess I'm doing it :)
http://dev.deluge-torrent.org/wiki/About

**Comment by garfield69** [comment]
http://deluge-torrent.org/docs/master/modules/ui/web/json_api.html may be relevant.

**Comment by Beaupedia** [comment]
Can't wait for Deluge integration!

**Comment by SchizoDuckie** [comment]
Deluge is working like a charm.
