### ISSUE TITLE
DuckieTV 0.94 angular-translate v2.4.2 error retrieving session key

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#414]
as reported in [Reddit](https://www.reddit.com/r/duckietv/comments/35ktk4/problems_with_display/)

Acki01:
>I've set the preferred locale to "en_uk English (United Kingdom)" to override the default browser language, since I prefer English to my native Swedish (translations are never really that good). But I keep having to reset this maybe every 4 times I open DuckieTV, because all of a sudden the language is Swedish again. Can you help?

[console.log](http://imgur.com/5VuusSI)
[ABOUT stats](http://imgur.com/BB9kq4h)

Since DuckieTV 1.00 is due out soon with angular-translate v2.6 I proposed asking OP to check after the upgrade.

**Comment by garfield69** [comment]
from [Reddit](https://www.reddit.com/r/duckietv/comments/35ktk4/problems_with_display/)
Acki01:
>I've been using the updated version for a week or so, and the original problem (DuckieTV reverts to the Swedish default version) has unfortunately worsened. Now, several times within the same session of working with DuckieTV, it switches languages, making me reset it several times a day, compared to several times a week as was before. Have you figured out was is wrong?

garfield69:
>this looks (judging by the description alone) like a duplicate of issue 433 which I just closed. The fix will be included in the next release of DuckieTV. I will keep your issue 414 open in case 433 does not solve your problem.

**Comment by garfield69** [comment]
I've just finished testing fix 433 against my sandbox xp windows set up for Svenska (Sverige) default language/locale.
I am pleased to report that 433 appears to fix this issue as well.

**Comment by SchizoDuckie** [comment]
Awesome!
