### ISSUE TITLE
1.0 upgrade. Calendar doesn't populate.

### ISSUE THREAD

**Issue by Js41637** [SchizoDuckie/DuckieTV#418]
Cannot read property 'title' of undefined at https://github.com/SchizoDuckie/DuckieTV/blob/angular/js/services/CalendarEvents.js#L58

**Comment by Js41637** [comment]
Actually only 1 serie gets added to calendar

**Comment by SchizoDuckie** [comment]
Can you elaborate on what happened?

**Comment by Js41637** [comment]
It just auto updated. Notification shows up. 1 show only appears on calendar. And that error in console. Pausing on caught exceptions doesn't show much but a null serie or something is being sent for var a but var b has a serie which is the one added to the calendar.

**Comment by Js41637** [comment]
Ok so what actually happened. It adds 4 episodes and then errors. Something must be wrong with the 5th that causes the error and stops the adding and I changed the month back to April and the calendar loaded normally however going back to May loads more episodes and then on a similar error however this time it's an 'Uncaught (in promise) TypeError: Cannot read property 'title' of undefined'

**Comment by SchizoDuckie** [comment]
That's strange. can you grab me your database ?

**Comment by garfield69** [comment]
This looks to me like a trakt.tv update was in progress just  after the upgrade, and one of the episodes sent by trakt.tv had an null title. This in turn would cause the calendar event sort routine to fail.
We should probably do a little data validation in FavouritesService to reject incomplete records that trakt.tv may occasionally send us.
Or perhaps the sort routine in CalendarEvents could be hardened by handling a null parmeter.
Or do both these things :-)

**Comment by garfield69** [comment]
195e127544a43e84a9a2fbacbc30e490372d9755 amends c0cd58ea367519c51399ea7d01f3dabeebe5dfaf
