### ISSUE TITLE
Densify Torrent controls

### ISSUE THREAD

**Issue by Js41637** [SchizoDuckie/DuckieTV#419]
Is there something that can be done about the torrent controls after an episode has been downloaded or its no longer being seeded. With the addition of a subtitle button and long show descriptions. The torrent controls can take up a lot of unneeded space and remain on any episode that has been downloaded.

**Comment by garfield69** [comment]
Am thinking that the long show descriptions could be contained in a fixed size box and scroll bar, to manage it?

**Comment by SchizoDuckie** [comment]
Yeah we can add a max-height there. But we can also probably densify the controls a bit, since more will probably be added in the future (custom setting for show title torrent search, don't autodownload, etc)

**Comment by garfield69** [comment]
reason for closure?

**Comment by Js41637** [comment]
Well @SchizoDuckie was doing a lot of changes to the TorrentClient so this isn't really relevant. Should probably make a new ticket to track the new TorrentClient changes.
