### ISSUE TITLE
Fix the migration process for DuckieTV (TAB) Chrome Extension change-log.

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#420]
While browsing the Chrome Web Store I spotted that the change-log for the TAB version only lists v0.75 and older. 
It seems the migration progress has left out updating the TAB change-log on the web store since that release.
The ACTION version on the Chrome Store is up to date.

Chrome Store for DuckieTV TAB. notice the change-log is at v 0.75 :-(
![image](https://cloud.githubusercontent.com/assets/6933240/7636527/de101bcc-fabb-11e4-8b4f-aa1175dc8dcb.png)

Chrome Store for DuckieTV ACTION. the change-log is at v 1.0 \o/ 
 ![image](https://cloud.githubusercontent.com/assets/6933240/7636572/24b109d8-fabc-11e4-929d-8275c70eb54f.png)

**Comment by SchizoDuckie** [comment]
yeah this is a messy manual thing I still do. and need to do for every fricking language we support...

Todo: automate...

**Comment by SchizoDuckie** [comment]
Updated the 1.0.1 changelog.
