### ISSUE TITLE
Drop support for DuckieTV extension on Opera

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#421]
With the decision taken @ #413 to drop support for the DuckieTV extension on Opera, we should not 
leave the 0.55 extension wallowing in the Opera Store, since with the pending demise of the Trakt v1 API, the extension is not working properly as  it is.

this ticket tracks the removal and clean up.

- [x] remove DuckieTV 0.55 from the Opera Store
- [x] update README.md
- [x] delete manifest-opera.json
- [x] update gulpfile.js
- [x] update gh-pages _posts/2014-01-01-landing.md
- [x] delete gh-pages _posts/.2015-01-04-opera.md-
- [x] ~~anything else?~~

**Comment by SchizoDuckie** [comment]
![image](https://cloud.githubusercontent.com/assets/111710/7643656/aa795bf4-fa9b-11e4-8fb1-f6bb9a01aeba.png)

Thx for the reminder :+1:
