### ISSUE TITLE
qBittorrent 3.2.0 broke new web api compatibility

### ISSUE THREAD

**Issue by SchizoDuckie** [SchizoDuckie/DuckieTV#423]
grrreat. 

https://gist.github.com/pmzqla/7e5733dbecfc50ee4ecd

need some sort automagic version detection switching and a switch in settings. 

- [x] Figure out a way to switch between apis (new qBittorrent32plus client)
- [x] Implement login method for qBittorrent > 3.2.0 
- [x] Store cookie on login success
- [x] Test new methods with cookie.

**Comment by garfield69** [comment]
Tipical!  Timing is everything ;-)

**Comment by SchizoDuckie** [comment]
- [ ] Figure out a way to switch between apis (currently just thinking a special qBittorrent < 3.2.0 and a 
- [ ] Implement login method
qBittorrent > 3.2.0 js file
- [ ] Store cookie on login success
- [ ] Test new methods with cookie.

**Comment by SchizoDuckie** [comment]
Hmm according to my test, it already works on standalone too. Dr Diagnostic: Can you verify that in Chrome, it won't work without granting the permission, but in node-webkit it works out of the box?

**Comment by garfield69** [comment]
Trouble.
- Node-Webkit. 
after connecting the TorrentClient with qBitTorrent 3.2 and then launching a magnet I got the following on the console log.
![image](https://cloud.githubusercontent.com/assets/6933240/7717595/411a23b2-fef8-11e4-8249-018d97454e28.png)
- Chrome Standard.
As for Chrome, after connecting the TorrentClient with qBitTorrent and pressing the `grant duckietv permission to read qbittorrent's cookie` button the `permission denied` alert popped up, and the following in the console log.
![chrome cookie denied](https://cloud.githubusercontent.com/assets/6933240/7717642/caa3a022-fef8-11e4-8781-ff5388bf0143.png)

**Comment by garfield69** [comment]
re: [chrome cookies](https://developer.chrome.com/extensions/cookies)
```javascript
Manifest
To use the cookies API, you must declare the "cookies" permission in your manifest, along with host permissions for any hosts whose cookies you want to access. For example:

      {
        "name": "My extension",
        ...
        "permissions": [
          "cookies",
          "*://*.google.com"
        ],
        ...
      }
```

**Comment by SchizoDuckie** [comment]
Sorry,  i forgot to mention: you will need to use the "reload extension" button on chrome://extensions to make the chrome patch work!

**Comment by garfield69** [comment]
I did, in order to reload the manifest. no joy.

**Comment by garfield69** [comment]
I know the manifest was loaded because I changed to manifest version number to 1.0.2
Also turned off my security extension and https anywhere.

**Comment by SchizoDuckie** [comment]
Allright, great. Back to the drawing board then :( gawd I hate cookie juggling in javascript

**Comment by garfield69** [comment]
do you want me to try it on chrome canary?

**Comment by SchizoDuckie** [comment]
shouldn't really matter. I'll do some more testing today.

**Comment by garfield69** [comment]
can confirm that 249cfab69ae238760a77302a13df3bc44ccda39e has fixed the cookie denied issue on my chrome stable 43.
Am getting `Refused to set unsafe header "Cookie"` anytime a torrentclient button is pressed, but this does not seem to prevent the function being actioned on qBitTorrent.

**Comment by SchizoDuckie** [comment]
Yeah that's some leftover code where i try to inject th ecookie manually.
cleaning that up will fix this \o/

**Comment by garfield69** [comment]
Q: when using TorrentClients, is any method of launching a magnet valid?
That is to say, can I use the magnet icon in any search TorrentDialog, or only the auto-download icon for an episode?

**Comment by SchizoDuckie** [comment]
I'm not really clear if I understand correctly, but from a coding perspective the preferred way of launching a magnet link is via TorrentSearchEngines.launchMagnet(magnetHash, [TVDB_ID]). this checks if there is a torrent client connected, and adds it via the TorrentClient's addMagnet function.
This function also broadcasts the message magnet:select:<TVDB_ID>, where TVDB_ID can be an empty string too (this is used in the autoStop feature for instance)

the API could use some love and docs, but I hope that answers your question

**Comment by garfield69** [comment]
Ah good. Q answered. Thanks.
so let me know when you want me to begin a 2nd round of testing for this on standalone and Chrome.

**Comment by SchizoDuckie** [comment]
This one is ready to test at will

**Comment by garfield69** [comment]
testing qBitTorrent 3.2 (winXP and Chrome Ext.) checklist:
- [ ] integration
      - [x] connect using authentication
      - [ ] connect without authentication
      - [x] using without granting Dtv cookie permission
      - [ ] using with granted Dtv cookie permission
- [ ] launch a magnet from sidepanel episode list
- [ ] auto-download
- [ ] using sidepanel Dedicated Torrent Client interface
      - [ ] tbd
- [ ] using sidepanel Episode Torrent Client interface
      - [ ] tbd
- [ ] anything else?

**Comment by garfield69** [comment]
having connected with qBitTorrent 3.2 (after previously having failed because of incorrect password),
the ActionBar status indicates connected (green dot), but the sidepanel Dedicated Torrent Client Interface is showing `Connecting please wait`.

**Comment by garfield69** [comment]
![image](https://cloud.githubusercontent.com/assets/6933240/8216753/9ab617b4-158c-11e5-9e26-d9277087c3b6.png)

**Comment by garfield69** [comment]
was expecting the torrent autostop to kick in once the dl was complete but this did not occur.
![image](https://cloud.githubusercontent.com/assets/6933240/8220722/5e048df0-15aa-11e5-828b-52a5b3b5528a.png)
![image](https://cloud.githubusercontent.com/assets/6933240/8220747/a33fcb3c-15aa-11e5-91c7-49cd1d4ee83c.png)

**Comment by garfield69** [comment]
For this test I trashed my previous chrome Dtv ext. and installed a fresh developement ext. 
I have not granted cookie auth, nor was I challenged by chrome to do so, so perhaps this is not required after all?
OR
chrome has persisted the authorisation I may have done in the past. Perhaps I need to create a fresh Chrome ID to be certain cookie auth is not required?

**Comment by SchizoDuckie** [comment]
The cookie auth thing is handled now, by bypassing the mechanism all
together and switching to http auth (username/password in url)

this way, chrome manages all that cookie stuff internally. (I did add an
extra permission to make that work)

**Comment by garfield69** [comment]
so we can remove the cookie auth button from the template then?

**Comment by SchizoDuckie** [comment]
I'll try to verify that tomorrow on a clean profile.

**Comment by garfield69** [comment]
having downloaded an episode via the client interface, should I have expected to see that episode marked as downloaded in the episode list?
