### ISSUE TITLE
Enable/Disable auto-download for selected series.

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#424]
As raised in [this Reddit](https://www.reddit.com/r/duckietv/comments/360qd8/disable_autodownload_for_certain_shows/)
Beaupedia:
>Hey all, is there a way to disable or enable auto-download for only certain shows? I have some shows on here that I'm many seasons behind on and catching up, and I don't want it to download every new episode.

Schizoduckie:
>Let's put it on the list :) It's a nice addition to the 'Watch on Netflix' and well, maybe you watch certain shows on TV instead

**Comment by Beaupedia** [comment]
Thanks for creating the ticket!
