### ISSUE TITLE
calendar mouse wheel scrolling

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#431]
On my displays I generally have the calendar overflowing a little past the bottom of the screen and I use the mouse-wheel to scroll to/from that area if I need to.
But currently that function is overtaken by the prev/next month mouse-wheel-scrolling just recently introduced.

Would it be possible to restrict the activity of the mouse wheel scrolling to only scroll prev/next when hovering over the month-year header of the calendar ?

If it is not possible, then how about I add an option in settings/calendar to turn on/off the month mouse-wheel-scrolling on the calendar?

**Comment by SchizoDuckie** [comment]
Ah yeah, I just tested this shortly but it didn't appear for me since i don't have scrollbars everywhere.

I think the right addition to this would be verifying if the event.target of the mousewheel event is actually the calendar.

**Comment by mertenhanisch** [comment]
Oh, I didn't think of that! Since it is implemented as a directive, we can just move it to the <tr> that holds the month-year header.
