### ISSUE TITLE
Magnet links don't work

### ISSUE THREAD

**Issue by bytehead-** [SchizoDuckie/DuckieTV#432]
If I search for a torrent, when I click on the magnet icon, the right shows that I have started a torrent.  But utorrent does not pop up, and it seems that I actually haven't downloaded the magnet link.  If I click on the options, and select the .torrent download, it brings up utorrent, and it works like it should.  I just don't understand why the magnet link doesn't do anything.  It used to quite well.

Current Date and Time	Sun, 17 May 2015 22:37:16 GMT
DuckieTV	1.0.1
UserAgent	Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.152 Safari/537.36
Platform	Win32
Vendor	Google Inc.
Determined Locale	en_us
Active Locale	en_us
Active Language	en_us
Screen (width x height)	1920 x 1200
Torrenting Enabled	true
Torrenting Search Provider	KickAss
Torrenting URL	https://kat.cr
Torrenting Client	uTorrent
Torrenting Auto-Download Active	false
TraktTV Sync Enabled	true
Storage Sync Enabled	false
Last checked TraktTV for DB updates on	Sun, 17 May 2015 22:26:37 GMT
DB Series	60
DB Series Hidden From Calendar	0
DB Seasons	242
DB Episodes	3051

**Comment by bytehead-** [comment]
Playing with it, I see if I chose the magnet link from the Options, it works. :/

**Comment by SchizoDuckie** [comment]
are you using the uTorrent integration? If not, I can recommend going to the torrent panel and clicking the 'clear utorrent authorization' button. Then refresh DuckieTV, see if that helps :)

**Comment by bytehead-** [comment]
Yes, I am.  Although I run utorrent Beta, and it hasn't really worked out with the integration that I've seen.  And no, no torrent is started.  I have double checked.  I will clear the authorization, and try it again.

**Comment by bytehead-** [comment]
OK, I cleared the authorization, and refreshed DuckieTV.  The magnet icon works as it used to.  And since the integration never worked for me (beta version I suspect, but who knows... I'm not going to miss it), I'm going to close this.
