### ISSUE TITLE
Update rarbg api

### ISSUE THREAD

**Issue by rarbg** [SchizoDuckie/DuckieTV#435]
@SchizoDuckie @garfield69 
Guys please update RarBG.js 
https://github.com/SchizoDuckie/DuckieTV/blob/angular/js/services/TorrentSearchEngines/RarBG.js#L13
To use format=json_extended
This will return you the needed data for 

                        size: "N/A",
                        seeders: "N/A",
                        leechers: "N/A"

**Comment by garfield69** [comment]
@rarbg  thanks for the info.

**Comment by SchizoDuckie** [comment]
How in the world could I have missed that.. thx!

**Comment by rarbg** [comment]
@SchizoDuckie you didnt :D i made it 7 hours ago

**Comment by SchizoDuckie** [comment]
:heart:  thanks! :laughing:

**Comment by rarbg** [comment]
np
