### ISSUE TITLE
Torrent auto-stop: Create a settings flag to run auto-stop for torrents not initiated by DuckieTV

### ISSUE THREAD

**Issue by SchizoDuckie** [SchizoDuckie/DuckieTV#436]
![image](https://cloud.githubusercontent.com/assets/111710/7675969/44a4e446-fd3f-11e4-8ddd-26e5f3e0ca2c.png)

**Comment by fracguy** [comment]
I've got this issue too - Torrents downloaded elsewhere (not via DuckieTV) are being stopped when completed, preventing me from seeding to meet quota for a private tracker. The only way to prevent this is to disable the Auto-stop feature for now.

**Comment by garfield69** [comment]
todo:
- [ ] add autostopAll to the settings menu (torrent.html)
- [ ] add autostopAll controls (SettingsService, SettingsTorrentCtrl)
- [ ] add autostopAll function support code (TorrentMonitor)

**Comment by garfield69** [comment]
Oops. @SchizoDuckie  your additions to the todo list got wiped by a clash in github while I was adding stuff. Could you please add them back? thanks.

**Comment by SchizoDuckie** [comment]
voila :)

**Comment by garfield69** [comment]
Can I just dump each torrent hash as a local storage key with no value  `localStorage.setItem(torrent.hash)`
 or
 should I first store all the hashes in an array and do a `localStorage.setItem('torrenting.hashes',JSON.stringify(listOfHashesArray))`
?
