### ISSUE TITLE
Make clicktrap more versatile

### ISSUE THREAD

**Issue by mertenhanisch** [SchizoDuckie/DuckieTV#438]
At the moment the clicktrap directive can only be used to move to the calendar state, thus it cannot be used in the local library view to close the sidepanel of a selected show. Would it be useful if we added an attribute to the clicktrap directive, that allows you to set the state to go to?

**Comment by SchizoDuckie** [comment]
Hmm I'm not sure I see the usefulness of this. Can you elaborate a bit on how you would see this used from a user interaction perspective?

**Comment by mertenhanisch** [comment]
After I have given it more thought, I think you're right. This is unnecessary at the moment.

**Comment by SchizoDuckie** [comment]
Thanks for thinking along though! keep 'em coming!
