### ISSUE TITLE
Shows marked as watched in DuckieTV fails to be marked as watched in Trakt.tv

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#440]
as raised in [Reddit]( https://www.reddit.com/r/duckietv/comments/34yd53/shows_marked_as_watched_in_duckietv_fails_to_be/)

Acki01:
>I noticed yesterday that shows that have marked as watched in DuckieTV failed to be marked as such in Trakt.tv. It seems to have been this way for over a month, according by the history function on Trakt.tv. This seems to be unrelated to the update that trakt.tv went through at the beginning of the year, since the sync worked fine when the latest release of DuckieTV came out. The problem seems to have arisen about a month or so ago.

Schizoduckie:
>I've looked into this today and it seems that trakt has definitely broken something (getting actual errors from trakt)
I've opened a support request with them, and hope to fix this before the 1.0 release :)

>The method now lists 'oAuth required' at the spec on Trakt.

**Comment by Js41637** [comment]
Yeah we've spoken to trakt about this. Trakt doesn't seem to think anything is wrong so we're not sure why trakt is returning errors when we try and mark a show as watched.

**Comment by SchizoDuckie** [comment]
I'm quite sure that it's due to the oAuth ( or lack thereof within DuckieTV )

I'll look into properly adopting oAuth as it'll save a heck of a lot of problems.
