### ISSUE TITLE
While side-panel open, add scroll bar to calendar when required.

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#444]
As raised in [Reddit]()
xstrike9999:
>Another flaw I've noticed is with the month view selected and a whole ton of shows added.
When you click on a show, the side bar pops up but the view scrolls to the top of the calendar and you have to exit the side bar to scroll back down to the week you were looking at.

Garfield69
>Good spotting. Ticket 444 raised, to ask for a scroll bar to be added when the calendar overflows while the side-panel is open. This way you can scroll the calendar independently of the side-panel content.

**Comment by SchizoDuckie** [comment]
Unfortunately this is not easy because of the way the whole mechanism works and really an edge case. I suggest the browser zoom for when you really need to navigate those while zoomed, or switching to week mode.
