### ISSUE TITLE
the standalone 1.0.1 mac x64 cannot be opened

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#445]
according to a comment in this [Reddit](https://www.reddit.com/r/duckietv/comments/35xney/announcement_duckietv_v10_is_here_o/) post,  the standalone 64 bit mac version cannot be opened.
jonahan: 21 may 2015
>1.0.1 still saying can't open on the 64-bit version. Tryin 32 now.
>Edit: 32-bit works.

Just the one report so far despite the Github Release Tracker count being 23.

I suggest that for the next release the mac x64 version package be tested if at all possible.

**Comment by Js41637** [comment]
Yeah brb buying a mac

**Comment by SchizoDuckie** [comment]
![image](https://cloud.githubusercontent.com/assets/111710/7783185/edf4550c-0138-11e5-92ad-0c016c632399.png)

**Comment by SchizoDuckie** [comment]
I made the mistake of installing 32 bit ubuntu so i'll have to reinstall my laptop before I can proplery verify installs on x64

**Comment by peulberg** [comment]
Same bug here, 64 bit Yosemite.
Can not be opened. Not a security issue.

**Comment by SchizoDuckie** [comment]
I'm going to remove the x64 builds for all platforms for the next release for the sake of simplicity.
