### ISSUE TITLE
trending with search filter shows only title,poster and overview 

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#446]
When viewing the trending page, the preview sidepanel is fully populated.
But when filtering by using the name search box, the preview sidepanel only shows the title, poster and overview. The rest of the preview data is missing.
Assuming both pages have access to the same data from the trending cache, is this a bug?

**Comment by SchizoDuckie** [comment]
The search box uses a different api than tending and is request-response
