### ISSUE TITLE
Import a backup

### ISSUE THREAD

**Issue by dainis29** [SchizoDuckie/DuckieTV#450]
Made a backup from chrome browser and tried to load in standalone app... Takes forever to finish.
Does it even work?

**Comment by SchizoDuckie** [comment]
It should :) Depending on bandwidth and how busy trakt is, it can take quite a while though.

If you're worried things are failing, you can always press F12 and check the network tab to see how things are going.

**Comment by SchizoDuckie** [comment]
Hmm it looks like importing a backup in a fresh install from the favorites list is not working properly. works from the settings panel though

**Comment by garfield69** [comment]
I did not have any problems with my import tests started from the library list, using DuckieTV 1.0.1 freshly installed from the Chrome store.
Seems more likely that the problem has more to do with how we are handling unexpected events from TraktTV.
Is there an import file we can test with that reliably fails to load?

**Comment by SchizoDuckie** [comment]
closing as it looks stable now
