### ISSUE TITLE
look into adding linux Ktorrent and rtorrent clients to DuckieTV

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#452]
ad requested in this [Reddit](https://www.reddit.com/r/linux/comments/37tzi2/duckietv_tv_show_tracking_calendar_that_connects/)

xxczxx
>Nice, but there is no Linux torrent clients integration - just uTorrent and the like. Ktorrent and rtorrent would be a nice addition.

schizoduckie
>I've actively tested on ubuntu over the past couple of weeks and qBittorrent, Tixati, Vuze and Transmission all work on their actual linux builds. I'll check into the web api possibilities for ktorrent and rtorrent!

[unable to find any docs for Ktorrent](http://ktorrent.org/wiki/)
wikipedia indicates Ktorrent has a Web interface plugin with default port number 8080
[linux rtorrent XMLRPC docs](https://github.com/rakshasa/rtorrent/wiki/RPC-Setup-XMLRPC)

**Comment by garfield69** [comment]
preliminary research:
rTorrent is a console based BitTorrent client that runs on linux (and possibly osx) systems.
There is also a web-server based front end called ruTorrent, that uses rTorrent's built-in XML-RPC server to communicate with it.

So from what I have found so far, rTorrent is not a candidate for the existing DuckieTV WEBUI Client model, as it does not appear to have HTTP WEBUI support.

rTorrent official site: [https://rakshasa.github.io/rtorrent](https://rakshasa.github.io/rtorrent)

**Comment by garfield69** [comment]
are you done with the whole rTorrent torrentClient, or is there still some tidy ups / testing to perform?

**Comment by garfield69** [comment]
@SchizoDuckie  before I get started in translations for base_path, a question:
do you think it likely that the base_path of /RPC2 is changeable (are we attempting to cater for seedboxes for instance) or its it more like a hard-coded endpoint?

**Comment by SchizoDuckie** [comment]
The base path can be changed yes. (it's just http server config that pipes the port and handles the cgi interface)

  
On that subject, i'd like to remove the term 'Seedbox' in DuckieTV as a whole favour of a more generic 'Base Path' term.

The term 'Seedbox' makes no sense imo. it's just webserver configuration.

**Comment by SchizoDuckie** [comment]
Some people are currently testing. I hope to hear soon on if this completes the feature.

**Comment by garfield69** [comment]
ok.
I have also installed rtorrent on my linux sandbox but have not configured it yet. Huge learning curve with this cli based app. The intention eventually is to be able to create a wiki for DuckieTV/rTorrent integration.

So I will start on the translation for base_path for the torrentClientSettings form.

I will also adjust the transmission integration panel to swap out transmission.key with transmission.path and work on any panels and wiki pages to swap out the term seedbox with base path.

**Comment by SchizoDuckie** [comment]
excellent. thanks! 

I cheated and installed RuTorrent to check if everything works. It's an interface for rTorrent that looks like the uTorrent WebUI, runs on PHP.

After installing rtorrent, make sure you have mod-scgi for apache (assumig you're on linux: `sudo apt-get install libapache2-mod-scgi` and then add `SCGIMount /RPC2 localhost:5000` to apache2.conf or httpd.conf, depending on your dist/version

**Comment by garfield69** [comment]
Well, I got DuckieTV to connect to rTorrent \o/
so I've started on the wiki https://github.com/SchizoDuckie/DuckieTV/wiki/Setting-up-rTorrent-with-DuckieTV .

But the DuckieTV rTorrentClient is making magnets and .torrents vanish down a big black hole.
Since I can't make ruTorrent connect with rTorrent (although I can xmlrpc commands to rTorrent via a shell) I cannot rule out a problem with my sandbox config, so I'll work on this next before spending any time attempting to debug what might be going on between DuckieTV and rTorrent.

**Comment by garfield69** [comment]
figured out my vanishing torrents problem. turns out that rTorrent will not accept magnet URI without at least one tracker on it.  Modified the zooqle search engine to append a default tracker to the magnet URI to solve the problem.
Proceeding with testing of all the torrent features using rTorrent.

**Comment by garfield69** [comment]
rTorrentClient test checklist
- [x] submit a torrent from zooqle search engine using torrentDialog by clicking at the torrent name
- [x] track torrent activity (download speed, progress)
- [x] use start, pause, stop and remove commands
- [x] show files
- [x] wait for torrent completion and test torrent-auto-stop
- [x] wait for torrent completion and test completion mark-as-downloaded
- [ ] test torrent submissions of all torrent varieties
    - [x] addMagnet (TPB se)
    - [x] addTorrentByURL (zooqle se)
    - [x] addTorrentByUpload (extraTorrent se)

**Comment by garfield69** [comment]
I'm working on building a Ktorrent Client.

**Comment by garfield69** [comment]
Ktorrent Client test checklist
- [ ] submit a torrent from zooqle search engine using torrentDialog by clicking at the torrent name
- [ ] track torrent activity (download speed, progress)
- [ ] use start, pause, stop and remove commands
- [ ] show files
- [ ] wait for torrent completion and test torrent-auto-stop
- [ ] wait for torrent completion and test completion mark-as-downloaded
- [ ] test torrent submissions of all torrent varieties
    - [ ] addMagnet (TPB se)
    - [ ] addTorrentByURL (zooqle se)

**Comment by garfield69** [comment]
\o/

**Comment by SchizoDuckie** [comment]
You fucking rockstar.

Looks glorious man.
