### ISSUE TITLE
DuckieTV 1.0.2 Dev : torrent details using invalid url path

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#453]
selecting the Torrent Details option from the torrent-dialog yields invalid url paths resulting in page-not -found errors.

examples: for KickAss and Torrentz, *SUPERNATURAL S10E20*, yields `chrome-extension://hdcancfhajcdihdlmahimignbkodgdmn/supernatural-s10e20-hdtv-x264-lol-ettv-t10580280.html`
works for Strike `https://getstrike.net/torrents/5A807C4C0B81587D6848CED09B6D96AB2335521C`
I can't test the others as they all use Extended SSL which does not work on my Chrome XP.

**Comment by SchizoDuckie** [comment]
Thanks. I'm re-jigging thetorrentclient output to either include the base domain (or not) by default. Still reworking them as part of my effort to implement the possible switch to .torrent files instead of magnets
