### ISSUE TITLE
[Request / Non-issue] Add ability to "Find a torrent" before the show as aired.

### ISSUE THREAD

**Issue by kevinlekiller** [SchizoDuckie/DuckieTV#456]
Hi, it would be great if we could click the "FIND A TORRENT" button before the show airs, sometimes a torrent is available hours before the "Currently Airs on" time.

If this is technically impossible or too complicated to implement, feel free to close, it's a minor inconvenience.

Thanks!

**Comment by SchizoDuckie** [comment]
Ah yes, A valid use case that I've encountered myself too, but just solved by using a manual search.

There really is no solid mechanism to attach to this i fear. How long before the episode airs should we 'unlock' it? A day? Some hours?

**Comment by garfield69** [comment]
@kevinlekiller  Two ways you can do this.
1. use the `search for any download` icon and type in you search parameters, using the button circled in red below
![image](https://cloud.githubusercontent.com/assets/6933240/7997014/0cb632ac-0b7b-11e5-9f1c-8f9ab2db7536.png)
or
2. my favourite way when I've had the need, click on the `search for a download for xxx` of the previous episode on the season episode page (large red ellipse), and then over-type and bump the number up one in the search box (small red ellipse).
![image](https://cloud.githubusercontent.com/assets/6933240/7997115/54ccf6e2-0b7c-11e5-87c9-e5ae452826dd.png)

**Comment by kevinlekiller** [comment]
@garfield69 Wasn't aware of those, that will work. Thanks.
