### ISSUE TITLE
SceneNameResolver and search with date strings

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#458]
as reported in this [Reddit](https://www.reddit.com/r/duckietv/comments/38snir/a_couple_issues/)
TWFH:
>None of the episodes of "The Daily Show with Jon Stewart" format correctly and thus cannot be downloaded

Looks like the first_aired ISO date string provided by Trakt.TV is presented as UTC.
we then save this value as episode.firstaired_iso.
example: The Daily Show with Jon Stewart - S20E114 Steve Buscemi
broadcast date: 04 June 2015 23:00 America/New_York
data.first_aired = 2015-06-05T03:00:00.000Z

quoting [Trakt.TV API](http://docs.trakt.apiary.io/#reference/episodes)
>All date and times are in UTC and were calculated using the episode's air_date and show's country and air_time.

This means that when SceneNameResolver does a  `return moment.parseZone(episode.firstaired_iso).format(episodesWithDateFormat[serie.TVDB_ID]); `
we get `The Daily Show 2015.06.05`

We need to adjust episode.firstaired_iso to the original broadcast date so we can present `The Daily Show 2015.06.04`

I propose installing and using the moment-timezone plugin, which can parse and display dates in any timezone.

SceneNameResolver would then do `return moment.tz(episode.firstaired_iso,serie.timezone).format(episodesWithDateFormat[serie.TVDB_ID]);` yielding `The Daily Show 2015.06.04`

**Comment by garfield69** [comment]
[moment docs](http://momentjs.com/docs/)
[moment-timezone docs](http://momentjs.com/timezone/docs/)

@schizoduckie I cannot figure out how to resolve
`moment-timezone-with-data.min.js:6 Uncaught TypeError: Cannot read property 'tz' of undefined`
when running Standalone.

**Comment by garfield69** [comment]
related #396

**Comment by SchizoDuckie** [comment]
Fucking good man. I hope this is finally it!
