### ISSUE TITLE
Number of unwatched episodes badge over library posters

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#460]
as requested in this [Reddit](https://www.reddit.com/r/duckietv/comments/39896t/sync_and_unwatched_episodes/)
submitted 4 hours ago by Pivke
>Hey, I asked in a previous post if adding unwatched episodes was possible for easier tracking. Will this be implemented?
[suggested mockup](https://i.imgur.com/F51Rirq.png)

So the idea is that the library page would have a badge over the posters that has a count of unwatched episodes.

**Comment by Js41637** [comment]
While I can see the use in the idea i'm not exactly in favour of clogging up the posters with big icons. Perhaps something like this would be better. Although the problem with this stuff as we know is it's hard to accurately know how many episodes haven't been watched and if a whole season has without doing too many intensive db operations.

![image](https://cloud.githubusercontent.com/assets/6258213/8074950/8b92e912-0f7c-11e5-90b9-351487b7c7f8.png)

**Comment by garfield69** [comment]
True, but I think the count is already there in the calculation we make to determine series-all-watched. I will explore that code and see if we can tap into it without adding additional processing cycles.

**Comment by garfield69** [comment]
@Js41637  I could use a hand taming the season posters notwatchedCount badge please.
It will not go to the top right corner like it does for the library poster. %-/
Also feel free to beautify it and the library poster badges too. Thanks. ;-)

**Comment by SchizoDuckie** [comment]
Did some minor tweaks to the display with the last couple of commits. tell me what you think, roll back at will.

**Comment by garfield69** [comment]
Dropping the open-eye from the posters helps make the remaining badges stand out more, so that is a big improvement.
But I would prefer to see `All episodes watched` (translation key: SERIEHEADER/all-watched/tooltip) in the poster title tooltip instead of `(0 Episodes to watch)`.
Also, tooltip-html-unsafe has been deprecated so we should avoid using it.

**Comment by SchizoDuckie** [comment]
Yeah we'll need to figure out how to use those tooltip html templates here. haven't had the time to look into those yet.

**Comment by garfield69** [comment]
I'll putz around with it and see what I come up with.
  ----- Original Message -----
