### ISSUE TITLE
Building DuckieTV

### ISSUE THREAD

**Issue by lightglitch** [SchizoDuckie/DuckieTV#464]
Hi,

I was trying to build this for what I can see you are using gulp, maybe we should update the devDependencies in package.json because it's grunt in there.

And when I do a "build-standalone" the compilation binaries folders are very different from your releases and it runs but shows an empty application that is missing resources.

I'm missing something in my configuration?

**Comment by SchizoDuckie** [comment]
Nah, there's not much wrong with your configuration, I just didn't update it.

The project is in such a state in git that you basically can just download node-webkit and extract it in DuckieTV's root dir. This way you can just run nw.exe and get going without any external dependencies or running any scripts.

Same for chrome extension mode, just clone the project, and point a new chrome dev mode extension to the git dir.

I will do some work on the build process in the near future to straighten this out though. Thanks for reporting.

**Comment by SchizoDuckie** [comment]
I've just released v1.1.1 to the webstore (after a failed v1.1.0 :( ) and will make it a first priority to get an automated build working for deploying the binaries.
