### ISSUE TITLE
handle opensubtitles unavailable condition

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#467]
Was trying to fetch a subtitle, but no matter what search parameter I used I kept seeing `no results found for <search>`.
Using the browser I then connected to the web site directly and was presented with this message:
`Site will be online soon. We are doing some necessary backups and upgrades. Thanks for understanding.`

It would be nice if DuckieTV could handle this condition and show it in the subtitles dialogue.
[edit] sorry, didn't think to capture the error condition via debugger till just now, and the site is back up so I missed the window :-(

**Comment by garfield69** [comment]
I even forgot to capture the console.log, but I recall it had to do with 
```javascript
xmlrpc.callMethod('LogIn', ['', '', 'en', 'DuckieTV v1.00']).then(function(result) {
                self.token = result.token;
```
at line 43 of OpenSubtitles.js, and the fact that .token could not be found from a null result.

**Comment by Js41637** [comment]
So we're assuming the site was actually returning an error which is should if they do this kind of maintenance otherwise the requests don't get told it's down.

**Comment by garfield69** [comment]
Yeah.
The OpenSubtitles.js script does have a section where it configures xmlrpc with error code handlers.

It sets up handles for 401, 404 and 500, but at the moment they just post a console.log message. 
Since I did not think to save the duckietv console log, I don't know if it was one of those codes or another.

What I don't know is what xmlrpc does if we get any other code than the three we look out for.

But it would not surprise me in the least to discover that the site did not return a code, but simply posted that page as a reply, causing xmlrpc to return a null result.

So we may need to handle the null result at the login routine, and additionally, expand the error code handlers to also post the code to the dialog so the user gets better informed of the problem.
We may need to add additional error codes to that xmlrpc config section s well.
