### ISSUE TITLE
Too much requests?

### ISSUE THREAD

**Issue by lightglitch** [SchizoDuckie/DuckieTV#470]
When I do a refresh of a show I get 9 search request o to Trakt api getting the show info. 
I think it's doing one request per season.

The event ''serie:updating'' is executed several times and that calls "TraktTVv2.resolveTVDBID".

**Comment by garfield69** [comment]
I'm using DuckieTV 1.0.2 DEV.
Performing a refresh for `Mr. Robot` yields the following requests from Trakt.TV
```
Tue Jun 23 2015 08:00:18 GMT+1200 (New Zealand Standard Time) TrakTVv2 url= https://api-v2launch.trakt.tv/search?id_type=tvdb&id=289590
TraktTVv2.js:168 Tue Jun 23 2015 08:00:18 GMT+1200 (New Zealand Standard Time) TrakTVv2 url= https://api-v2launch.trakt.tv/shows/mr-robot?extended=full,images
TraktTVv2.js:168 Tue Jun 23 2015 08:00:18 GMT+1200 (New Zealand Standard Time) TrakTVv2 url= https://api-v2launch.trakt.tv/shows/mr-robot/people
TraktTVv2.js:168 Tue Jun 23 2015 08:00:18 GMT+1200 (New Zealand Standard Time) TrakTVv2 url= https://api-v2launch.trakt.tv/shows/mr-robot/seasons?extended=full,images
TraktTVv2.js:168 Tue Jun 23 2015 08:00:18 GMT+1200 (New Zealand Standard Time) TrakTVv2 url= https://api-v2launch.trakt.tv/shows/mr-robot/seasons/1/episodes?extended=full,images
```
This is the required number of request needed to fetch all the necessary data to populate the Mr. robot series. 
I don't believe there is any redundant requests in this sequence... do you disagree?

**Comment by lightglitch** [comment]
I tested on node webkit with another show ( one with more than one season), where did you test it?

**Comment by garfield69** [comment]
specify the show and I will list my console.debug output for you here.
I'm using chrome ext. for my dev work, but the code is exactly the same source as used in DuckieTV nwjs version.

**Comment by lightglitch** [comment]
I was able to replicate, every time I open and close the favorites tab it executes the button bind again.
So just click on the favorites button several times (open and closing), than open any show and do a refresh.

**Comment by garfield69** [comment]
@lightglitch  Fantastic!!!. Well spotted.
@SchizoDuckie  for every use of the library show/hide, a subsequent refresh request for a series yields multiple refresh calls.
example: clicked on show/hide library 3 times, then selected `Game of Thrones` and pressed the refresh button.
Using DuckieTV nwjs 1.0.2 DEV.
The following is the console.debug url list of the TraktTVv2 calls from promiseRequest L165
![image](https://cloud.githubusercontent.com/assets/6933240/8292530/50003df2-1984-11e5-8bd6-f3720efac4fe.png)

**Comment by lightglitch** [comment]
Could happen with other actions also...

**Comment by garfield69** [comment]
Yeah. This one is for Schizoduckie to sort out. Way past my understanding of templates loading, binding and what not.

**Comment by SchizoDuckie** [comment]
Very nice thanks for reporting @lightglitch and figuring this out @garfield69 :+1: 

There was indeed an unnecessary $rootScope.$on in the controller, that, when the controller gets recreated, does the same action again. Refactored it a bit, problem solved! (didnt check for other potential problems though as it's near bedtime)
