### ISSUE TITLE
Can't hover serie while searching in add mode

### ISSUE THREAD

**Issue by Js41637** [SchizoDuckie/DuckieTV#475]
@SchizoDuckie fixed the trakt-serie route for the trending pages however forgot about search.

It currently still tries to go to `trakt-serie` which is no longer a valid route however swapping it to the new method in the TraktTVTrendingCtrl causes the seriesList to exit search mode whenever you hover a serie.

**Comment by garfield69** [comment]
additional finding. Spinner during trending import is off kilter.
![image](https://cloud.githubusercontent.com/assets/6933240/8374090/7ef0e3cc-1c46-11e5-942e-ea2c7b0367f7.png)
