### ISSUE TITLE
Add a open/play episode button

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#477]
as raised out of ticket #476 

shadycady:

> Would it be hard to add a button to open/play episode from DuckieTV.

Schizoduckie

> For the standalone version that wouldn't be too hard now any more now that we have the proper files listing per torrent. I Could just launch it on the default system player. However, I would like to create a generic method so that it can also launch videos to for instance Video Stream for Chrome. We should probably flesh this out in a new ticket

**Comment by hyankov** [comment]
No progress on this? Really? For the last 2 years you have planned to add a 'play' button to the application but couldn't get around to it? Maybe I am missing the whole point of DuckieTV then, if not having a method to launch the downloaded file is not a prio.

**Comment by SchizoDuckie** [comment]
and you are entitled to anything because? keep it up with the snarky
comments and I'll lock and limit the whole repo.

fucking ungrateful twat
