### ISSUE TITLE
add a current-setting-in-text section to all the setting pages

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#480]
as initiated by ac8ca71597a5e2c4caeadcf38e8d5d2b0849909d
ToDo list:
- [x] ~~backup-import.html~~
- [x] ~~backup.html~~
- [x] calendar.html
- [x] ~~custom-search.html~~
- [x] ~~deluge.html~~
- [x] display.html
- [x] ~~language.html~~
- [x] ~~qbittorrent.html~~
- [x] ~~qbittorrent32plus.html~~
- [x] ~~subtitles.html~~
- [x] ~~sync.html~~ (out of service.)
- [x] ~~tixati.html~~
- [x] torrent-search.html
- [x] torrent.html
- [x] trakt-import.html
- [x] ~~trakttv.html~~
- [x] ~~transmission.html~~
- [x] utorrent.html
- [x] ~~utorrentwebui.html~~
- [x] ~~vuze.html~~

note: ~~crossed off~~ are templates that do not require a current-setting-in-text section.

**Comment by SchizoDuckie** [comment]
You are a rockstar! Thanks for doing this and making the release! I'll do the publish step somewhere tonight or tomorrow!
