### ISSUE TITLE
Add an autobackup feature

### ISSUE THREAD

**Issue by SchizoDuckie** [SchizoDuckie/DuckieTV#481]
Making backups sucks, but something will probably mess up one time.

Idea: present the user a one-click-backup download dialog, every month or so (and ofcourse, add an option to be able to turn it off)

**Comment by garfield69** [comment]
I think we could also just do a `silent` backup as part of any DuckieTV upgrade, maybe posting a `backup saved to <location>` line as part of the UpgradeNotificationService dialog.

**Comment by garfield69** [comment]
Auto-backup feature proposal:
---------------------------------------

- Settings option to schedule a backup on a Daily, Weekly, Monthly or Never interval.
- A Dialog pops up when the interval expires, prompting user to save the backup.

settings screencap:
![image](https://cloud.githubusercontent.com/assets/6933240/14482275/176b7332-018f-11e6-850b-c84048f074fc.png)

dialog screencap:
![image](https://cloud.githubusercontent.com/assets/6933240/14482229/b5de0008-018e-11e6-9b5f-f42ec870957d.png)
the floppy disk spins.
