### ISSUE TITLE
Loading onto SeriesList and then switching to Calendar doesn't load events

### ISSUE THREAD

**Issue by Js41637** [SchizoDuckie/DuckieTV#483]
Switching month loads them and loading onto calendar loads them normally.

**Comment by SchizoDuckie** [comment]
Please elaborate. with full testcase. 
I just tried to reproduced this but cannot.

**Comment by Js41637** [comment]
Loading the page onto the serieslist and closing it to the calendar shows this for me
![image](https://cloud.githubusercontent.com/assets/6258213/8586003/291d1d44-262d-11e5-9f47-af778e42d689.png)

**Comment by garfield69** [comment]
@Js41637  ... and I take it there is no related error message in to console log to explain it?

**Comment by garfield69** [comment]
Confirmed. If you display the library page by clicking on the heart , then do a browser refresh, then click on either the duck, the calendar, or the heart, you are presented with an empty calendar page.

**Comment by Js41637** [comment]
Looked into this some more as it always happen, the cause of this is the FavoritesService resolve in the favorites state
```
FavoritesService: function(FavoritesService) {
    return FavoritesService.waitForInitialization().then(function() {
        return FavoritesService;
    });
},
```
this somehow prevents the calendar from being able to load its stuff. Removing the code doesn't seem to affect the loading of the series-list either, I don't remember if it did I believe it was added because it loaded before the favorites service but this doesn't seem to be the case anymore? Anyway, i'm sure a solution can be found.
