### ISSUE TITLE
custom search string for series

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#484]
Schizoduckie has already added the customSearchString entity to the Serie table via 35587025c179f5d7ea8dec5209f31e5a377593f8, but this ticket tracks progress on implementing the rest of this feature.

**Comment by SchizoDuckie** [comment]
Related to this: A request to allow setting custom search quality preferences per show (this will integrate nicely into the same field)

**Comment by garfield69** [comment]
pending translations.
