### ISSUE TITLE
DuckieTV 1.1.1 none of the new torrent client interfaces are working

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#485]
as reported [in this Reddit post](https://www.reddit.com/r/duckietv/comments/3c9peu/duckietv_11_for_chrome_is_available/)
none of the new torrent client interfaces are working. 
Clearly a module got left out of the package :-(
![image](https://cloud.githubusercontent.com/assets/6933240/8529084/de6870a4-246b-11e5-948a-a6baa72c01d6.png)
![image](https://cloud.githubusercontent.com/assets/6933240/8529098/f43c5738-246b-11e5-8af6-6f49efa48085.png)

**Comment by SchizoDuckie** [comment]
Fixed with e9d1fd46fbbf9a28b8564879a225d291c015cb31
