### ISSUE TITLE
No changelog for 1.1.1

### ISSUE THREAD

**Issue by webmaven** [SchizoDuckie/DuckieTV#486]
https://github.com/SchizoDuckie/DuckieTV/releases/tag/1.1.1
https://github.com/SchizoDuckie/DuckieTV/releases

And yet: https://github.com/SchizoDuckie/DuckieTV/compare/1.1.0...1.1.1

**Comment by SchizoDuckie** [comment]
Yeah it was a version bump in a hurry for the chrome webstore to deploy a new version because 1.1.0 was broken. I will fix that to reflect it when i've got the build system fixed

**Comment by garfield69** [comment]
1.1.1 has been withdrawn. 1.1.2 released.
