### ISSUE TITLE
gh-pages (https://schizoduckie.github.io/DuckieTV/) looking for cast_sender?

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#488]
Just happened to look at the console log while using the gh-pages homepage @ https://schizoduckie.github.io/DuckieTV/ and noticed that it appeared to be searching for cast_sender, except a quick look at the gh-pages source code does not yield any hits? puzzled.
![image](https://cloud.githubusercontent.com/assets/6933240/8536333/b8531f8a-24a3-11e5-9930-ad4e5313e2ba.png)

**Comment by Js41637** [comment]
Yeah this is chrome not the site. Chrome will attempt to find cast_sender.js on pages that have Youtube content as it sees media that can be streamed and because it can't find it it's just the usual not found error.

**Comment by garfield69** [comment]
Ah, I see. Cheers.
