### ISSUE TITLE
DuckieTV 1.1.1 fresh install Uncaught (in promise) TypeError: entity.getType is not a function

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#489]
Testing a fresh install from the chrome store of DuckieTV 1.1.1
Found  `Uncaught (in promise) TypeError: entity.getType is not a function` error message in the console log, which ends up preventing the empty-serie dialogue popping up.
Backtracking Deps.js line 712 equates to `js\vendor\CRUD.SqliteAdapter.js` line 83.
![image](https://cloud.githubusercontent.com/assets/6933240/8540859/88ee4f8c-24dd-11e5-8f48-870f6b98e590.png)
![image](https://cloud.githubusercontent.com/assets/6933240/8540869/9d2bb750-24dd-11e5-8cd1-b042e6c5467e.png)
could not get into the library (clicking on the heart did not work). a Browser refresh cleared the problem.
[edit] line 89 threw up the same error `CRUD.log("Table created and fixtures inserted for ", entity.getType());` when I commented out line 83 to bypass problem.
Its likely lines 86 and 87 may also become issues when they get executed in this routine.

**Comment by mapx-** [comment]
I'm using "browser action" mode extension, version 1.1.1 and still not working

see errors in console:
http://pastebin.com/ZvdKz6Us

**Comment by mapx-** [comment]
it should be some setting which break all.
I saved the database, I removed duckietv and reinstalled duckietv, then replace the empty database with that saved before. It works. But ... what breaks the extension ?

**Comment by Js41637** [comment]
Something with the Torrent code is breaking during the upgrade. If you know where the database is saved, back it up it and reinstall DuckieTV and put your database file in it, it should work fine.

**Comment by mapx-** [comment]
I already did it (see above), but it could be useful for you to find the reason

**Comment by SchizoDuckie** [comment]
We have the reason and the solution. Just postponing the release a tiny bit
more so we can fix things properly. Thanks for you patience!

**Comment by mapx-** [comment]
ok, great !
