### ISSUE TITLE
Closing SeriesList doesn't change the state from 'favorites'

### ISSUE THREAD

**Issue by Js41637** [SchizoDuckie/DuckieTV#490]
Not sure how long this has been an issue cause i'm preeeetty sure it didn't use to do this but if you close the favorites it stil remains on the `favorites` state so when you reload the page it will automatically open the favourites list.

I thought a simple fix would be putting a $state.go('calendar') in there somewhere however this doesn't work. Attempting to switch to the calendar state changes it for a second before switching back to favorites for some reason.

**Comment by Js41637** [comment]
Was this fixed by commit 74dd600bae8ed3da85b175a36515fabc8b3e4cae?

**Comment by SchizoDuckie** [comment]
Correct. thanks for spotting.
