### ISSUE TITLE
wrong watched / downloaded episode

### ISSUE THREAD

**Issue by mapx-** [SchizoDuckie/DuckieTV#491]
I have in my library "under the dome" show. The next episode will be number 4 (season 3) and will be aired friday. Today I opened duckieTV and ... it started some updating (even if I disabled the rating stuff, however could be some other thing). After that:
-an episode from the past week was "cleaned" (not anymore watched / downloaded) and ... the episode number 4 was signed as watched / downloaded.

(To recover from this issue I closed duckieTV and I modified the database using some SQLite manager the episode, replacing 1 by 0 for watched / downloaded fields)

**Comment by garfield69** [comment]
It is a problem that DuckieTV regularly come across. :-(
The data that DuckieTV uses is fetched from the Trakt.TV database, which in turn is an aggregate of data fetched from a multitude of TV databases in the Web, with records from TheTVDB given preferred weight. 
As humans/bots update theTVDB records it is not uncommon for episodes in a series to have their TVDB_ID changed from one update to the next.
This causes DuckieTV to have to clean up its own DB as best it can.

In your instance, it seems likely that the title for dome's ep4 and one of the other 3 earlier eps was switched around on Trakt.TV.

Little we can do about this unfortunately.

Incidentally, you could have chosen to wait until ep4 had 'aired' and then you could have used the mark-downloaded and marked-watched buttons to correct the status, without resorting to direct DB editing... ;-)

**Comment by mapx-** [comment]
I see ... However if you add some condition like:
if aired date or episode date > date-of-the-day ==> no updating of those fields (watched / downloaded)

**Comment by garfield69** [comment]
Ah no, because as far as DuckeTV was concerned, it was not the download/watched status that changed, but the title.

**Comment by garfield69** [comment]
although I suppose we could add a similar clause to set the non-aired eps back to unwatched... I'll work on it.

**Comment by mapx-** [comment]
great ! thanks a lot :)

**Comment by garfield69** [comment]
You are welcome. Thanks for raising the issue.

**Comment by SchizoDuckie** [comment]
hmm. this new logic will potential conflict with leaked episodes. I guess we should add a 'leaked' indicator to the episodes table so that when that flag is toggled, we don't reset these
