### ISSUE TITLE
align spinner on posters correctly

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#492]
When adding serie from the trending page, the spinner is out of position, as shown below
![image](https://cloud.githubusercontent.com/assets/6933240/8579937/aa3a7934-260b-11e5-823c-ca38dcb98ce9.png)

**Comment by SchizoDuckie** [comment]
Addition to this: the check mark doesn't show on my win 10 vm. just a "utf
char not available" white box outline. We need some other char for this.

**Comment by garfield69** [comment]
suggest replacing the `&check;` with `glyphicon glyphicon-ok`

**Comment by SchizoDuckie** [comment]
All for that!

**Comment by SchizoDuckie** [comment]
I just reproduced the issue. It's on the search page.
