### ISSUE TITLE
standalone win32 1.1.2 error with torrent client integration

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#495]
problem with the torrent clients while testing standalone win 32 1.1.2
![image](https://cloud.githubusercontent.com/assets/6933240/8584743/e058ff32-262d-11e5-9692-9ae3994d6373.png)

**Comment by SchizoDuckie** [comment]
dammit.
okay. tomorrow then.

**Comment by SchizoDuckie** [comment]
are you sure you're not looking at an old version?I just tested standalone linux again andit works. vms have some trouble booting right now.

**Comment by garfield69** [comment]
I just fetched (3 minutes ago)  the latest zip of the win32 from the releases page, and installed it and ran it just now.
Could GitHub be caching the old copy still?

**Comment by garfield69** [comment]
confirming that `DuckieTV-1.1.2-windows-x32.zip`  at `https://github.com/SchizoDuckie/DuckieTV/releases` is an outdated 1.1.2 build.
This means users downloading it from `http://schizoduckie.github.io/DuckieTV/` will not get a working windows version until you refresh it, tomorrow with your latest local 1.1.2 build.
No worries, sleep, you've earned it. See you tomorrow. :-)

**Comment by Gonenb** [comment]
There is no Windows 1.1.2 in http://schizoduckie.github.io/DuckieTV/  , pressing it doesn't work

**Comment by garfield69** [comment]
So what happened then... did your latest re-build yesterday not overwrite the Github zip files or something?

**Comment by SchizoDuckie** [comment]
I think so. Performing some final tweaks on the installer and verifying verything works.

**Comment by SchizoDuckie** [comment]
Confirmed. Everything works. 

I do have some improvements for a new release, where the page automatically reloads after selecting a new torrent client and successfully testing it. That's needed to make duckietorrent work.

**Comment by garfield69** [comment]
Downloaded and tested the win32 package.  Briefly tested most functions, all appears to be working nicely, no errors in the console logs either. \o/
