### ISSUE TITLE
Add a download-a-season button like v0.94 used to have

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#498]
as reported/requested in this [Reddit](https://www.reddit.com/r/duckietv/comments/3ctdrx/download_season/), DuckieTV 0.94 used to have an option to donwload a whole season. Clicking the button would generate a `<serie name> SEASON <season number>` search string in a torrent search dialogue.
![image](https://cloud.githubusercontent.com/assets/6933240/8625744/c2c44856-2794-11e5-9041-bfd0c124ddfa.png)
![image](https://cloud.githubusercontent.com/assets/6933240/8625751/d2019148-2794-11e5-92ad-1909ad410a04.png)

**Comment by garfield69** [comment]
propose to split to season-sidepanel's `auto download all` button in a similar style to that in the sidepanel-episode-details.
**auto download all**
![image](https://cloud.githubusercontent.com/assets/6933240/8632602/9bd2046a-27f6-11e5-8c05-2bce5a53acd8.png)
**search for a season's torrent**
![image](https://cloud.githubusercontent.com/assets/6933240/8632674/900e3bbe-27f9-11e5-92db-c2a0ae5260ad.png)

**Comment by SchizoDuckie** [comment]
Love it!
