### ISSUE TITLE
DuckieTV 1.1.2 settings/language - default_locale button enabled when language is not available

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#500]
as raised in this [Reddit](https://www.reddit.com/r/duckietv/comments/3co2zm/no_text_on_buttons/)
 some default system languages are causing problems until the user manually picks a language from the settings/language menu.
[example](http://gyazo.com/c95fa2d8ce878a54a47e29b229cde3dd)
[Statistics:](http://gyazo.com/faa49c7306241396dce439455b17ead7) 
in this instance, the system language code is `cs`

**Comment by DuckieTV** [comment]
Is this a bug in angular-translate I thought it had to fallback to english on default?

**Comment by garfield69** [comment]
I recall making changes to the set-up a while back to fix a different problem, I may have caused this instead. I'll look into it.

**Comment by garfield69** [comment]
**research:** playing with my sandbox. set chrome up with Czech (Cesitna), and loaded DuckieTV 1.1.2
**results:** determined that the angular-translation code is operating as we intended, which is that if the determined language does not match any of our configured languages, then en_us is set as the preferred language.
![image](https://cloud.githubusercontent.com/assets/6933240/8629962/ac84a6a6-27b4-11e5-95dc-4366f8e68c20.png)

what we have not anticipated however, was that the user would choose to select the browser default_locale as displayed in the language menu :open_mouth:  which yields, you guessed it, no translation :grinning: 
![image](https://cloud.githubusercontent.com/assets/6933240/8630012/0851d1c0-27b5-11e5-8e07-e25571a6a2ee.png)

**solution:** we need to ghost the settings/language browser default_locale option when that option is not one of the configured languages we support.
