### ISSUE TITLE
DuckieTV 1.1.3 DEV cpu loop or lockout situation after clicking on add-a-show

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#502]
A recent commit is causing my DEV 1.1.3 version of DuckieTV (both standalone and chrome ext.) to go into a never ending wait when I click on the add-a-show button on the library page.
My CPU hits 53% and DuckieTV appears to freeze.
I've screen captured the call stack after pausing the debugger, hoping this helps narrow down the problem.
![image](https://cloud.githubusercontent.com/assets/6933240/8640816/b8018d72-2959-11e5-81c7-0cec02bb5853.png)

**Comment by garfield69** [comment]
12a81905044741bfed1c730b30e364f4db5abe31 was the last update to js\directives\seriesList.js recalculate function.

**Comment by Js41637** [comment]
I did some tests, mine stays around the 10% range before and after

**Comment by garfield69** [comment]
Yeah, well mine is a old dual-code 32bit cpu, so we are tying up one engine. On my media PC which is a single core AMD its stuck on 100%. ;-)
The point is that it seems we get into some kind of loop when clicking on add-a-show, and all processing of other DuckieTV functions is suspended.

**Comment by SchizoDuckie** [comment]
@Js41637 Please remove the setStyle code from that recalculate function. It's probably triggering the infinite loop.

I was already wondering why android locked up as well. most likely because of this.

**Comment by garfield69** [comment]
confirmed. I'll attempt to explain, excuse me if my terminology is incorrect.
function MutationObserver is called whenever the DOM changes.
```javascript
var observer = new MutationObserver(function(mutations) {
  recalculate();
});
```
it in turns calls the recalculate procedure, which alters el.style.height
```javascript
function recalculate() {
  var isMini = el.classList.contains('miniposter');
  var maxPosters = container.getAttribute('max-posters') ? parseInt(container.getAttribute('max-posters')) : 0;
  posterWidth = isMini ? 139 : 169; // Includes 1 9px padding-left
  posterHeight = isMini ? 206 : 251; // Includes 11px padding-bottom
  oldClientWidth = el.clientWidth;
  postersPerRow = Math.floor(el.clientWidth / posterWidth);
  centeringOffset = (el.clientWidth - (postersPerRow * posterWidth)) / 2;
  if (maxPosters != 0) {
    el.style.height = (Math.ceil(maxPosters / postersPerRow) * posterHeight)+'px';
  }
  $scope.$applyAsync();
  scrollToActive();
}
```
which in turns changes the DOM and so the MutationObserver is called again.
equals infinite loop. :-)

**Comment by Js41637** [comment]
Ahh yeah, obvious, well the recent changes I have made make this an easy fix anyway.
