### ISSUE TITLE
some minor calendar scrolling and tooltip blocking issues

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#503]
As reported in this [Rediit](https://www.reddit.com/r/duckietv/comments/3cm6dj/announcement_duckietv_v112_for_chrome_linux/)
xstrike9999:
>Few bugs I've noticed.
> - [x] With the month view selected and a whole ton of shows added, when you click on a show, the side bar pops up but the view scrolls to the top of the calendar and you have to exit the side bar to scroll back down to the week you were looking at.
> - [ ] Also, the episode number that pops up shows at the very left of the calendar is hidden behind the edge of the window. It is rectified only if you click the week the show is in.
> - [x] The "more" button in add shows does not scroll down but stays at its starting position when you scroll down.

**Comment by Js41637** [comment]
Last one wasn't a bug but because of how the seriesList worked with the new changes, wasn't possible to have it at the bottom but that is fixed now.

**Comment by garfield69** [comment]
- [ ] I would like to see the torrent dialogue's options menu styled the same way as the main torrent dialogue. Shown below, the green circle highlights the style that I think should be applied to the red circled area.
![image](https://cloud.githubusercontent.com/assets/6933240/8656495/00f5b2dc-29ec-11e5-8965-0b8d26d4af8a.png)

**Comment by SchizoDuckie** [comment]
@garfield69 : d8eb769834bc693af42019dccb70c9d174fe0d61 how about that? :)

Fixed 'unable to scroll huge calendar with' 4cf432dd16c027094a0aa4c7501359c37f52c77f

The tooltip dropoff will have to be fixed probably with a tooltip template with a simple <br> between the formattedEpisode and the time, since moving around the tooltip is not really an option.

**Comment by garfield69** [comment]
re: d8eb769834bc693af42019dccb70c9d174fe0d61 \o/ thanks.
