### ISSUE TITLE
add code to recognise DEMO, DEV or PROD mode and disable/enable relevant features

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#504]
as raised in #497 

SchizoDuckie:

> re: I18n template strings untranslated in the online version
> I just fixed this by pushing the cordova compatible version :) I also added this to the build script so that this happens automagically from now on.
> One Warning though: DO NOT connect your torrent client or enter any credentials on the online hosted version because all data will be proxied!

Garfield69:

> Wondering if it is worth adding code to recognise we are in DEMO mode and disable the torrent client connections or trackt.tv logins?

SchizoDuckie:

> That could be a good idea :) We can just hide those UI components with with a special getSetting key

so:
- [x]  add css class to hide GUI that should not be used in demo mode
  css/hide-demo.css

``` javascript
/*
* this class is included in the demo builds
* and is used to hide GUI that is not suitable for on-line use
* and to hide Development GUI that is not ready for release
*/
hide-demo {
    display:none !important;
}

.hide-demo {
    display:none !important;
}

hide-prod {
    display:none !important;
}

.hide-prod {
    display:none !important;
}
```
- [x] identify templates that require to have features disabled and add the `disabled` keyword to them
  - [x] all torrent integration panels in settings (deluge, qbt, qbt+, transmission, tixati, vuze, utorrent webui, utorrent api)
    - hide test and save button
  - [x] trakt.tv panel in settings
    - hide authorise and login buttons
- [ ] amend demo build script to include the css/hide-demo.css to the tab.html style list

**Comment by garfield69** [comment]
re: determining DEV vs. PROD.
a method for this would be to create an empty file called DEVELOPMENT which does not get shipped with the PROD builds, on which we perform a $http.get. But this would produce an 404 error in the logs in PROD ever time its used, so i am not inclined to favour this method.

Can anyone think of other ways to determine if code is running as DEV or PROD, that does not require the user to manually set a hidden settings flag ?

**Comment by Js41637** [comment]
Well actually you could include the file in the git repo with like `dev=false` and gitignore it then all we need to do is just set it to true for our clones.

**Comment by garfield69** [comment]
Interesting idea, but IMO its still another example of a user manually setting an option.
In order for anyone to use the development functions, they would need to change the file accordingly.
It may be that this type of method is the only way forward, but my idea solution would be some form of automated recognition.

**Comment by Js41637** [comment]
How many people would need to change the file though for PROD and if you're not using a Dev (or beta?) version of Chrome you can't edit extensions files anyway and anyone who does use a Dev version of DuckieTV from Github would just edit the file once.

Also I dunno how the building works if it builds a seperate online version you could take this a step further and have 3 seperate files, one for dev, prod and online and just use the build process to use the relevant file for the different builds.

Anyway, it doesnt need to be overly complex to fix an issue that really isn't that major.

**Comment by garfield69** [comment]
@SchizoDuckie   I could use your guidance with methods on this one.

**Comment by SchizoDuckie** [comment]
I would say we add a css class 'hide-production' to the elements we want to hide, and append a separate   css file that adds a display:none to the production builds. that way nothing has to change for the dev setup. The online build could have something similar.

I don believe we have to really prevent any code from being loaded do we? We should just hide some elements and make the ui inaccessible
