### ISSUE TITLE
DuckieTV Standalone 1.1.3 DEV  Uncaught No language key specified for loading.

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#505]
When I use the latest GitHub source on my standalone win32 nwjs the main page breaks. Enabling the toolbar=true yielded this in the console log. `Uncaught No language key specified for loading.`
![image](https://cloud.githubusercontent.com/assets/6933240/8711999/19f44882-2bab-11e5-829a-12d5dbbc9cc7.png) 

[edit] checking the DEV  chrome extension the log shows `client determined locale proposed: undefined set: en_us configured: en_nz` so clearly we are not determining locales successfully any more.

**Comment by garfield69** [comment]
screen capture of DuckieTV 1.1.3 DEV chrome_ext, showing det-locale as en_us when it should have been en_nz
![image](https://cloud.githubusercontent.com/assets/6933240/8718734/b2d827ae-2bfa-11e5-92e1-0873404a5825.png)

**Comment by SchizoDuckie** [comment]
auto detection works, but overriding now no longer works on mobile. timeout needs to be added back?

**Comment by SchizoDuckie** [comment]
overriding works, just needs a full app restart. good enough.
