### ISSUE TITLE
Possible uTorrent 3.4.3 Beta (Build 40538)  session key issue

### ISSUE THREAD

**Issue by siperwrx** [SchizoDuckie/DuckieTV#507]
Magnet links don't load from the episode list. I have to click the Download icon, THEN click the Magnet link. A minor inconvenience, but now it takes 3 clicks to download a magnet vs. 1 click on the old interface.
![doesn twork](https://cloud.githubusercontent.com/assets/13387920/8759170/7364a724-2ca3-11e5-9c7f-2bfbf1591fe9.JPG)
![works](https://cloud.githubusercontent.com/assets/13387920/8759169/73622a3a-2ca3-11e5-8e25-415effde9c58.JPG)

**Comment by garfield69** [comment]
are you talking about the are circle in red ?
![image](https://cloud.githubusercontent.com/assets/6933240/8760019/a19445fc-2d5a-11e5-8536-b1845ea71d0a.png)
because if so, then we can easily add a magnet link that that area.

or are you talking about the torrent dialogue ?
because then we are way ahead of you :-) as the next release will include all option in-line.
![image](https://cloud.githubusercontent.com/assets/6933240/8760026/1257460e-2d5b-11e5-9ad4-ddaefa9cf112.png)

**Comment by SchizoDuckie** [comment]
Quick sidenote on this: the launch-a-magnet feature *should* still work
with the same button for both when you have connected utorrent to DuckieTV
and when you've not connected anything at all.

To clarify: It should push it directly to your torrent client when
connected, otherwise it launches the magnet link. The magnet link for
copying should only have to be used when you're using other integration
tools outside of DuckieTV
Op 18 jul. 2015 04:42 schreef "garfield69" <notifications@github.com>:

**Comment by SchizoDuckie** [comment]
@siperwrx could you clarify if you're using the DuckieTV torrent client integration? Or do you want access to the magnet link itself?

**Comment by siperwrx** [comment]
Hey, sorry for the delay. I was on vacation.

@garfield69 - yes, the 2nd image is correct. That circled magnet link doesn't do anything. I have to click the Download icon, THEN the magnet icon and it will then work.

@SchizoDuckie - Yes, I'm connected to uTorrent/using the DuckieTV Chrome plugin.

**Comment by garfield69** [comment]
Ah, I understand now. Thanks for the clarification.

I have done some tests, and believe that the use of the alternate magnet button on the option menu is in fact a red herring :-)

and here is what I think is happening.

When you first start up DuckieTV, you do not have an active link with uTorrent.
(Check this by looking at the uTorrent icon on the left hand side of the main DuckieTV page. It should have a green dot, I bet yours is red).

In this state, the first magnet link you click on, establishes a uTorrent connection, but does not pass the magnet on.
The second time you click a magnet button (and here is the point, it does not matter if you click on the main magnet button on the torrent dialogue, or use the magnet button on the options menu of the torrent dialogue), send the magnet to uTorrent to action.

The test of this theory is as follows: 
When you start up DuckieTV, first click on the torrent Icon on the main DuckieTV page and establish a connection. (The icon should have a green dot to indicate it is connected).
Now do your searches, and click on the magnet you want in your torrent dialogue. 
It should work, let me know how you go :-)

**Comment by siperwrx** [comment]
Negative. I have the green dot upon startup and it still does not work. I
wish I could record my screen but I don't have any good software for that.
I'm happy to do it if you have any recommendations though!

**Comment by garfield69** [comment]
well that is a bit odd.
I would like you to start up uTorrent,  then start up DuckieTV.  click on a magnet button, then
press the `F12` key to access the development tools page, click on the `console` tab, and post a screen dump (print screen key), and Ctrl-v in the next box here) so I can take a look at the log. Thanks.
A screen capture of the DuckieTV statistics section would be useful too (click on the (i) icon on the main DuckieTV page, scroll to the bottom. Cheers.

**Comment by garfield69** [comment]
Also, question: do you normally leave uTorret up, and start and shut down DuckieTV as you need it, or what do you usually do? ;-)

**Comment by siperwrx** [comment]
Registering torrent search engine: ShowRSS
app.js:12035 Registering torrent search engine: Strike
app.js:12035 Registering torrent search engine: ThePirateBay
app.js:12035 Registering torrent search engine: Torrentz
app.js:10447 Ping result on port Object
app.js:10352 Retreived session key! invalid request
deps.js:1614 unauthorized(anonymous function) @ deps.js:1614
app.js:5515 Initializing episode aired checker service!
app.js:8143 Not performing trakttv update check. already done today.
app.js:8155 Not performing trakttv trending update check. last done Mon Jul
27 2015 19:03:03 GMT-0700 (Pacific Daylight Time)
app.js:4753 Magnet selected!
magnet:?xt=urn:btih:6F80A125F2128C6587E4BBFD09D2AC36B4D73D88&dn=ballers+2015+s01e06+hdtv+x264+killers+ettv&tr=udp%3A%2F%
2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337
app.js:12073 Firing magnet URI!
 magnet:?xt=urn:btih:6F80A125F2128C6587E4BBFD09D2AC36B4D73D88&dn=ballers+2015+s01e06+hdtv+x264+killers+ettv&tr=udp%3A%2F%
2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337
5232457
app.js:12077 Adding via TorrentClient.addMagnet API!
 magnet:?xt=urn:btih:6F80A125F2128C6587E4BBFD09D2AC36B4D73D88&dn=ballers+2015+s01e06+hdtv+x264+killers+ettv&tr=udp%3A%2F%
2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337
5232457
deps.js:1614 TypeError: Cannot read property 'torrent' of undefined
    at Object.methods.addMagnet (app.js:10574)
    at Object.service.launchMagnet (app.js:12078)
    at magnetSelect (app.js:4757)
    at n.$scope.select (app.js:4782)
    at deps.js:1711
    at f (deps.js:1728)
    at n.$eval (deps.js:1638)
    at n.$apply (deps.js:1638)
    at HTMLAnchorElement.<anonymous> (deps.js:1728)
    at HTMLAnchorElement.c (deps.js:1544)(anonymous function) @ deps.js:1614

**Comment by siperwrx** [comment]
I usually leave uTorrent up all the time and I have DuckieTV start with
Chrome so I'm always opening and closing it.

**Comment by garfield69** [comment]
Cheers for that.
Hmmm. I don't like lines 6 and 7 in the log. And the last set too. I don't think your connection between DuckieTV and uTorrent is established 100%.
What version (and build) of uTorrent are you on ?  (uTorrent Help menu, About submenu).

**Comment by garfield69** [comment]
Assuming that you are using at least version 3.4.2 build 38397, then I think we should try renewing the session key.

So at your convenience, access the DuckieTV settings (cog icon) page, click on the `uTorrent Integration` button, then click on the `clear uTorrent authorisation` button.

Then shut down both DuckieTV and uTorrent. (Don't use the uTorrent window X button, but the File menu, Exit submenu, OR uTorrent's icon on the System Task bar's Exit menu, to properly shut it down).

Start up uTorrent, start up DuckieTV. Visit DuckieTV's settings, uTorrent Integration, and click on the `connect to uTorrent` button. 
Click `Yes` on the uTorrent's pop up 'do you want to allow access'.

Now try your magnets and see if we have made a difference or not. :-)

**Comment by siperwrx** [comment]
Nope. No change. Using 3.4.3 Beta (Build 40538)

**Comment by garfield69** [comment]
Ah that is a shame.
So did you check the logs, are you still getting those errors 
```
app.js:10352 Retreived session key! invalid request
deps.js:1614 unauthorized(anonymous function) @ deps.js:1614
and
deps.js:1614 TypeError: Cannot read property 'torrent' of undefined
    at Object.methods.addMagnet (app.js:10574)
    at Object.service.launchMagnet (app.js:12078)
    at magnetSelect (app.js:4757)
    at n.$scope.select (app.js:4782)
    at deps.js:1711
    at f (deps.js:1728)
    at n.$eval (deps.js:1638)
    at n.$apply (deps.js:1638)
    at HTMLAnchorElement.<anonymous> (deps.js:1728)
    at HTMLAnchorElement.c (deps.js:1544)(anonymous function) @ deps.js:1614
```
?

It is looking like we have some king of incompatibility with your version of uTorrent. 
I will raise this ticket to *bug* status, and hopefully @SchizoDuckie  can cook up something.

**Comment by SchizoDuckie** [comment]
Hmm interesting. It looks like the torrent cannot be found somehow. Will do some testing with the beta.

**Comment by garfield69** [comment]
I have had a recent [issue on Reddit](https://www.reddit.com/r/duckietv/comments/3ily4z/updated_from_beta_to_112_nothing_downloads/)  with a user who was using uTorrent 3.4.4 with DuckieTV 1.1.2 and was not getting magnets to work.

The log was showing the same 'unauthorised' errors during the connection as are recorded in this ticket earlier.

I got the user to click on the uTorrent Icon on the left of the main DuckieTV page, and then click on the 'Clear Authorisation' button. 
Once he replied YES to the 'Allow DuckieTV access to Utorrent' prompt that his uTorrent client produced, he was able to fully use all the magnets from within DuckieTV again.

@siperwrx  are you still having issues using magnets with DuckieTV?
if so, please try what I described just above and let us know the outcome. Thanks.

**Comment by SchizoDuckie** [comment]
Going to close this as fixed since no response from @siperwrx and just tested latest utorrent beta and duckietv beta on windows -> works like a charm
