### ISSUE TITLE
mark all shows watched for a day

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#511]
As raised in this [Reddit post](https://www.reddit.com/r/duckietv/comments/3ebqa2/is_there_a_way_to_mark_all_shows_watched_for_a_day/), add an enhancement to mark all shows watched for a day.
I expect it would be just a matter of navigating the days events and marking watched any shows whose broadcast time is older than current time...?

**Comment by SchizoDuckie** [comment]
Yeah. The quest is though: how are we going to do this User-Interface wise. 

I'm open to ideas, because I have none

**Comment by SchizoDuckie** [comment]
Allright, one idea.

.markdaywatched {
font-size: 9px;
  position: absolute;
  bottom: -20px;
  left: 0px;
  margin-top: 0px;
  width: 100%;
  background-color: #3a3a3a;
  display: block;
  text-align: center;
  font-weight: normal;
  text-decoration: none;
  font-style: normal;
  padding: 0px;
  height: 20px;
  line-height: 19px;
}

(an <em> embedded inside the <em> with the day number in the calendar)

Which translates to this.

![image](https://cloud.githubusercontent.com/assets/111710/8858345/3ab4b5ee-3177-11e5-8b33-3773d1d414d9.png)

Opinions?

**Comment by garfield69** [comment]
That is brilliant!

 

  _____
