### ISSUE TITLE
Standalone (win 1.1.3 DEV) type error in binge-watching code

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#517]
I have just noticed that the binge-watching code is not working on the Standalone 1.1.3 DEV version, where as it does work on the Chrome Extension 1.1.3 DEV version.

On the Standalone the code yields a type error
```javascript
TypeError: Cannot read property 'minutes' of undefined {stack: "TypeError: Cannot read property 'minutes' of undef…controllers/sidepanel/SidepanelSerieCtrl.js:23:51", message: "Cannot read property 'minutes' of undefined"}message: "Cannot read property 'minutes' of undefined"stack: "TypeError: Cannot read property 'minutes' of undefined↵    at file:///C:/temp/DuckieTV/js/controllers/sidepanel/SidepanelSerieCtrl.js:23:51"get stack: function () { [native code] }set stack: function () { [native code] }__proto__: ErrorSidepanelSerieCtrl.js:23 (anonymous function)
```
![image](https://cloud.githubusercontent.com/assets/6933240/8949761/af665b66-360b-11e5-8a06-1b350b67548b.png)
![image](https://cloud.githubusercontent.com/assets/6933240/8949774/cd620674-360b-11e5-9796-677ba4b6cf80.png)

which on the Chrome Extension works perfectly fine?
![image](https://cloud.githubusercontent.com/assets/6933240/8949823/82bba07a-360c-11e5-963e-52606036bc40.png)
![image](https://cloud.githubusercontent.com/assets/6933240/8949826/8cb862a2-360c-11e5-926b-16812dc9ed0d.png)

**Comment by garfield69** [comment]
I added a `console.debug(result.rs);`  so I could see the result from the select.
standalone:
![image](https://cloud.githubusercontent.com/assets/6933240/9014063/0dc2ee36-3814-11e5-806f-9fa0f790c4ce.png)
chrome extension:
![image](https://cloud.githubusercontent.com/assets/6933240/9014100/525d56da-3814-11e5-9de5-fa7d345273d8.png)

**Comment by SchizoDuckie** [comment]
Hmm that's a nice one. I need a new test for that probably. Thanks for doing the grunt-work!
