### ISSUE TITLE
<Show files> Button for torrents doesn't show files

### ISSUE THREAD

**Issue by lamaresh** [SchizoDuckie/DuckieTV#518]
This is my bar for an episode in download:
![image](https://cloud.githubusercontent.com/assets/3250975/8981761/19abf922-36bb-11e5-9c47-7c9f4091c04b.png)

and this is after i click the "show files" button:
![image](https://cloud.githubusercontent.com/assets/3250975/8981770/2ed3003e-36bb-11e5-8199-85f310641df2.png)

**Comment by Js41637** [comment]
Yeah we are aware of this issue and has since been fixed. It will be in the next release :)
