### ISSUE TITLE
Handling when Torrent/Client not detected in torrentRemoteControl

### ISSUE THREAD

**Issue by Js41637** [SchizoDuckie/DuckieTV#519]
Alright guys so atm there is a still a line of text in the [torrentRemoteControl](https://github.com/SchizoDuckie/DuckieTV/blob/angular/templates/sidepanel/torrentRemoteControl.html#L41) about when a torrent/client isn't detected. This was just a placeholder and wasn't sure if it should be expanded or removed. `remote.torrent` is null while there is no active torrent client and/or if the torrent no longer exists in the client.

So we could make it a bit smarter and have it say either "Torrent client not detected" and "Torrent not detected in client" and maybe add a button to remove the magnetHash from db if the torrent isn't found anymore (or make this an automatic thing).

Either way, if it's fine as-is then it can be translated or we can remove it or expand on its functionality.

**Comment by SchizoDuckie** [comment]
Yeah, a typical backlog feature with low prio. I've got some more plans for the torrentremote to improve int the future, this should indeed be part of it.
