### ISSUE TITLE
DuckieTV 1.1.3 DEV season posters badge gone walk about

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#521]
The yet-to-watch badge on the posters of the season side-panel have all wondered off to the top right corner of the screen :grinning: 
@Js41637  one of yours?
![image](https://cloud.githubusercontent.com/assets/6933240/9024516/a3a08814-3927-11e5-9ed8-4dcbd3114544.png)

**Comment by Js41637** [comment]
ma bad
