### ISSUE TITLE
"Episodes" button in serie tab

### ISSUE THREAD

**Issue by lamaresh** [SchizoDuckie/DuckieTV#522]
The "Episode" button open the episode list of the last season, I propose it to open the episode list of the last non-seen season of the series.
 I think it could be more useful this way.

Edit: without showing special episodes, of course

**Comment by SchizoDuckie** [comment]
Sounds like an idea, but that would somewhat force you to use the mark as watched and keep up with it, not everybody does that in my experience.

I'm open to more suggestions though, we can maybe make a toggle for this behavior?

**Comment by lamaresh** [comment]
seems great!
