### ISSUE TITLE
Spelling of "series" is written as "serie"

### ISSUE THREAD

**Issue by achal1995** [SchizoDuckie/DuckieTV#523]
![capture](https://cloud.githubusercontent.com/assets/13637776/9055154/9f0898f8-3aa5-11e5-95f4-f1db38f677f8.JPG)
I have highlighted the spelling error in the above image.I think it should be "series" instead of "serie".
And by the way this is one of the best software i have ever used.
Thank You.
With Regards,
Achal Pathak.

**Comment by Js41637** [comment]
While I don't think Serie is technically an English word, i think of Series more as a plural as in more than 1 show and a Serie as just 1 even though a Series can be 1 show as well.

**Comment by SchizoDuckie** [comment]
how about we change serie to show?
Op 4 aug. 2015 09:22 schreef "Js41637 ftw" <notifications@github.com>:

**Comment by garfield69** [comment]
I will correct the spelling mistake in my next translation update. Series is
both singular and plural, one of the few English words of that type.

'Serie' is not a word and clearly a typo on my part some time in the past.

 

I'd rather not use 'show', the Google  translator regularly gives me the
wrong interpretation when I do the multi-language conversions with 'show' in
the sentence.

 

There are a few other labels I intend to correct while I am at it, just to
bring consistency to how we name things throughout the different DuckieTV
pages. 

 

  _____

**Comment by lamaresh** [comment]
Series is both a singular and a plural form. When it has the singular sense of "one set," it takes a singular verb, even when series is followed by of and a plural noun: A series of lectures is scheduled. When it has the plural sense of "two or more sets," it takes a plural verb: Two series of lectures are scheduled: one for experts and one for laypeople. [http://www.thefreedictionary.com/series]

**Comment by Js41637** [comment]
Yeah to be honest though Serie should be a word, unlike other words that are both Singular and Plural Serie and Series make sense. Unlike other ones like like `News` where the singular would be `New` lol.

**Comment by lamaresh** [comment]
it's because in italian serie has the same form in sigunal and plural. We say "1 serie" and "2 serie" but I think in English it has been imported as a "false" plural as series ;)

**Comment by achal1995** [comment]
Thanks to all for ur valuable comments. I think "Series" or "Show" should be more appropriate than "Serie".
