### ISSUE TITLE
[feature request] display season and episode on calendar

### ISSUE THREAD

**Issue by SchizoDuckie** [SchizoDuckie/DuckieTV#526]
as reported on tweakers.net

**Comment by garfield69** [comment]
more details please?

**Comment by SchizoDuckie** [comment]
Something like this
![image](https://cloud.githubusercontent.com/assets/111710/9183728/6009e39e-3fb1-11e5-8ad9-4dbf46fc60b5.png)

todo: 
- [ ] default setting in SettingsService
- [ ] settings toggle in settings/display
- [ ] translations

**Comment by garfield69** [comment]
will the default for showing S/E on the calendar be enabled, or disabled?

**Comment by SchizoDuckie** [comment]
I would say disabled. We'd only want to show this (imo) for people that have wide screens
