### ISSUE TITLE
DuckieTV 1.1.3 DEV ABOUT page no longer displaying correctly.

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#532]
Has there been a behind the scene CSS change that has impacted the ABOUT page on the current development version of DuckieTV?
previously:
![image](https://cloud.githubusercontent.com/assets/6933240/9286531/d3bff29c-4349-11e5-8a4c-046ebadab75d.png)
![image](https://cloud.githubusercontent.com/assets/6933240/9286535/e06f6fe0-4349-11e5-9832-c7553d20f884.png)
and now:
![image](https://cloud.githubusercontent.com/assets/6933240/9286541/fff0677a-4349-11e5-8dfd-4d392beff03f.png)
![image](https://cloud.githubusercontent.com/assets/6933240/9286542/09f628f4-434a-11e5-8049-3176798a2ced.png)

**Comment by Js41637** [comment]
Ok i've gone back like 35 commits so far and strange shit is still going on for me.

**Comment by garfield69** [comment]
Should not need to go further back than 16 days ago.

The fix below is the last time I am confident the ABOUT page and statistics
section was still being presented properly.



 

  _____

**Comment by Js41637** [comment]
I almost found it but then I broke my repo and I need to clone it again lol, it was about 16-18 days ago though, yes. Somewhere after your [ignore win7 folder icon cache](https://github.com/SchizoDuckie/DuckieTV/commit/5f74e27e328cc8b76286264c2ebfcab745376485) commit.

**Comment by Js41637** [comment]
Interesting, commit b56efa7 appears to be the issue

**Comment by Js41637** [comment]
Ok guies, i've found the problem, this is caused by the Local Storage and is happening because of the `xem.mappings` which is all stored in local storage, I assume becauses its one massive long arrow with no gaps by default, it doesn't break any of the lines. Adding `word-break: break-word` to the local storage column will fix the issue.

**Comment by Js41637** [comment]
Or just not including the xem.mappings in the dump.

**Comment by garfield69** [comment]
Brilliant debugging work, mate. Cheers. :+1:
