### ISSUE TITLE
Option to sort favourites' order of shows

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#533]
as raised in this [Reddit](https://www.reddit.com/r/duckietv/comments/3hfr0e/feature_request_option_to_sort_order_of_shows/)
TomTom131313:
>Hi,
>Would it be possible to add an option to sort the Shows in the local library by date added as well as the current alphabetical ?
>It would be much easier to find newly added shows that was, especially after importing new shows from Trak for example.

**Comment by Js41637** [comment]
I thought about this but do we even store when the serie was added.

**Comment by garfield69** [comment]
The `Series` table has a currently unused entity called `added` of type `DATE` which we could use. So the first order of business would be to save the date when `Null` in the fillSerie routine of FavoritesService.js

**Comment by garfield69** [comment]
Intend to add to the favorites panel a sort menu of the following Series elements: name, added, first aired, not-watched count, with reversing tags on repeat selection.
![image](https://cloud.githubusercontent.com/assets/6933240/13530442/4a9deb0e-e286-11e5-94b6-fe501b10e16a.png)
