### ISSUE TITLE
request to use AniList API to resolve broadcast times for anime

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#534]
Received this PM on Reddit:
 alexandermatteo:
>Hey, I've noticed two shows that I watch (Gangsta. and Aoharu x Machinegun) are listed properly on thetvdb.com (Gangsta comes out Sunday, Aoharu is Friday) but they're still listed wrong in Duckietv - Gangsta is listed Monday 6am (Timezone Athens) and Aoharu is listed Thursday at 7:46PM. It doesn't make sense to be a timezone problem, since one is listed ahead of its timeslot and the other behind it.
>For a future release, one option would be to get just the timeslots from the AniList API (https://anilist.co/), you can find the documentation here - http://anilist-api.readthedocs.org/en/latest/
>I realize this may be a lot of unneeded work, so don't mind me if it is. There just seems to be a weird schedule problem with thetvdb updates for animes.

Looking at the Trakt.TV data for these two series, Gangsta is a mess.
It is incorrectly loaded on Trakt.TV as being broadcast from London Sun 23:00 instead of Tokyo Sun 23:00, and in addition, the episodes themselves have a UTC timestamp of Mon 03:00, which is neither London or Tokyo time adjusted back to UTC+0, so no wonder that displays incorrectly by the time we adjust to Athens local time (UTC+3).

Aoharu on Trakt.TV is listed as being broadcast from Tokyo Fri 01:46, and the episodes are loaded correctly. Tokyo Fri 01:46 is Athens Thu 19:46. Whether Tokyo Fri 01:46 is the correct broadcast time to begin with, is up for debate.

Anyway, the question asked is: can we fetch the broadcast times for Anime from AniList API?

Right now I don't think we can even distinguish what series is an Anime from any other Series in our DB, so that would be the first hurdle to overcome.

The second question is: do we want to get into supporting Anime as a special case distinct from other series in the DB?

@SchizoDuckie Opinion?

**Comment by SchizoDuckie** [comment]
In my opinion this stuff should be fixed in thetvdb, it will then work properly in duckietv as well. I would not like to treat anime a whole lot different from the rest if we can get by with trakt

**Comment by Js41637** [comment]
Yeah I think there is only so much we can do, we can't keep trying to work around all the issues that are out of our control.

**Comment by garfield69** [comment]
ticket [664](https://github.com/SchizoDuckie/DuckieTV/issues/664) looks into how we could support some Anime titles by using thexem.de database, which we already plug in to for scene name support.

**Comment by SchizoDuckie** [comment]
Still a nope on implementing another source of time data though. In my opinion that should still be fixed in thetvdb
