### ISSUE TITLE
FastSearch Directive

### ISSUE THREAD

**Issue by Js41637** [SchizoDuckie/DuckieTV#537]
Github issue for tracking Fast Search Directive introduced in commit 358c9989845575924c4755972fc976574d2417c6

Todo:
- [x] Fix tooltips being yellow, caused by `.modal-content strong` css
- [x] Searching for something and then clearing input doesn't clear the current 'model' (posters still visible)
- [x] Modal close button
- [x] Torrent Search?
- [x] Better loading indicators for different searches
- [x] Handle when trakt search returns error
- [x] Debounce search update

**Comment by garfield69** [comment]
note: before this goes live, we need to prevent the fast directive responding to the easter egg sequence... confuses the user when looking to activate the top10 and also gets presented the fast search results for the last two keystrokes ;-)

**Comment by garfield69** [comment]
I think fast search is now complete.

**Comment by garfield69** [comment]
OK. I'm going round seeding `$scope.$emit('fastsearch: clear');` where ever there's an input box.
There must be a better way.
What would be really neat is for fastsearch to somehow ignore key-codes when they are used from any input box other than its own... I would welcome suggestions on how to do this.

**Comment by SchizoDuckie** [comment]
You can try to filter on event.target in the keypress event.
- If there is no input[type=text] in event.target -> append to fastsearch
cache
- If there is an input[type=text] in event.target -> event.stop() and do
not append to fastsearch cache
- If there is an input[type=text] for the fastsearch -> process event
