### ISSUE TITLE
DuckieTV 1.1.3 DEV  ReferenceError: addEventListenerFn is not defined

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#538]
started seeing this in the DEV logs today when I tried testing uTorrent 3.4.2 for research on a Reddit user problem.
Seems to have broken my uTorrent link.
![image](https://cloud.githubusercontent.com/assets/6933240/9486265/249419d2-4c19-11e5-8262-6a721d1890a2.png)

**Comment by SchizoDuckie** [comment]
oh damn. looks like i forgot something in my copying methods into the new $httpBackend. thanks!
