### ISSUE TITLE
individual quality setting for each series ove-riding global settings default

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#540]
As detailed in this [Reddit](https://www.reddit.com/r/duckietv/comments/3ihc3v/feature_request_custom_quality_per_show/)

nukewales:
>Could you maybe add quality setting in the show description, so that we could set junkfood to 480p and gems of television to 720p? "Torrent Episode Downloader" (R.I.P.) did this and it turned out to be really handy. And as an added Bonus, could then the download Popup jump directly to the right quality tab?

schizoduckie:
>We may need to build a dedicated quality selector (and a property on the series entity to store this) to implement this specific request though, as this specific request would conflict with the default search quality (if set)
>The second request, for jumping to the right quality tab, will require some additional patching on top of that, but shouldn't be hard either.

**Comment by Js41637** [comment]
I think the custom search string option should just have an option to completely override the normal one and include the quality buttons that are on the torrent dialog.

**Comment by garfield69** [comment]
So for this, we add a ignore-global-quality flag to the series table, and make it toggle-able on the series customSearchString panel. 
The user is then free to add what ever quality search string to the series customSearchString they see fit.
