### ISSUE TITLE
DuckieTV 1.1.2 possible bug with certain torrent search engine results versus magnets

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#543]
a Reddit user has discovered [some issues](https://www.reddit.com/r/duckietv/comments/3ily4z/updated_from_beta_to_112_nothing_downloads/) with using magnets with certain torrent search results.

Droyk
>This error comes when we click magnet icon on kickass torrents [http://i.imgur.com/mNZcaYg.png](http://i.imgur.com/mNZcaYg.png)
And this error comes when we click magnet icon on get strike torrents [http://i.imgur.com/oZeaQcy.png](http://i.imgur.com/oZeaQcy.png)

issue is pending additional information to be supplied by user before I delve into researching this problem.

**Comment by SchizoDuckie** [comment]
Shouldn't be too much of a problem. It's trying to deregister a possible previous listener for that specificmagnet hash. The trace is helpful :+1:

**Comment by garfield69** [comment]
Performed some tests on DuckieTV 1.1.2 PROD, and can confirm that using the strike search engine and clicking on a magnet causes the documented error.
Repeated similar tests on DuckieTV 1.2.0 DEV, and confirmed that the error no longer occurs.
The best fit the the commit resposible in resolving this error since DuckieTV 1.1.2 was published is 1f29b01f284e651c79735c3f39e0b30943e21330,Fixed noMagnet not defined in config of custom engines
Despite its title, a change to js/directives/torrentDialog.js impacts all search engines not just the custom ones :-)
