### ISSUE TITLE
DuckieTV Standalone 1.1.3 DEV: auto download duplicate when episodes are 1 day apart

### ISSUE THREAD

**Issue by patrickacollier** [SchizoDuckie/DuckieTV#545]
Logging for review. I'll try to clear db entry and see if it replicates. 
Issue: episode 9 (8/30) and episode 10 (8/31) both start auto downloading ep9 and show same % progress. Only 1 file is downloaded however ep10 is now logged as downloaded.

**Comment by garfield69** [comment]
what is the name of the series?

**Comment by patrickacollier** [comment]
Bachelor in Paradise ....wife not me :)
Since ep10 hasn't been loaded to a tracker yet so this could be the case.  Same scenario happens Wed/Thur with Big Brother so I'll see what happens then.

**Comment by garfield69** [comment]
can you (if you haven't shut down the standalone yet) press F12, click on the console TAB, and screen capture a few screen dumps of the console logs for us. It may show the magnets used, and log some useful activity traces. (use Print screen key) and Ctrl-v straight into the next open box here. Cheers.

**Comment by patrickacollier** [comment]
Well...I just did a db dump and reload without those episodes to see if it does it again. Mainly because there was an incorrect auto download of The Whispers s1ep13 (ep12 downloaded) even though js logic is working in the "find torrent " ie. It doesn't show ep13 available

**Comment by garfield69** [comment]
Ah. Oh well, next time then :-)
BTW, thanks for reporting.

**Comment by patrickacollier** [comment]
I haven't gotten the autodownload again, but it does appear the logic for checking the torrent name before grabbing it is intermittent. Below is today's Big Brother, Magnet captured is ep30 and ep31 is the target.
![image](https://cloud.githubusercontent.com/assets/14065117/9648875/56b3b38a-51bb-11e5-9e47-f19f91399898.png)

**Comment by garfield69** [comment]
Interesting.
It also appears that the same magnet is being fired twice
![image](https://cloud.githubusercontent.com/assets/6933240/9649792/f255fbda-524d-11e5-984d-a82672719d16.png)
which I don't think should be happening either.

**Comment by patrickacollier** [comment]
I thought that was odd. I'm new to this repository so i'm def stumbling around. I found my way to the filterbyscore but got lost in the dialogs, to much for 1 night. So i'll try to read through the MD files tomorrow to see if I can start to understand. BUT debugging is a whole lot easier than trying create all this on my own. So, big thanks for putting this out there!

**Comment by patrickacollier** [comment]
did it again on Mr Robot (should be ep10) auto downloaded ep08
Then I got these errors, that I've never seen before.
I'll pick back up tomorrow.
![image](https://cloud.githubusercontent.com/assets/14065117/9649974/7c8a963c-51ca-11e5-9269-ba9f1be8f0a3.png)

**Comment by garfield69** [comment]
You may ignore the `failed to load resource: file:///*.js.map` messages. They are just the chrome debugger moaning that we have not provided debugging maps for vendor provided scripts. That is of no consequence.
If I get time tonight I'll take a deeper look at this, and perhaps provide you with some commands you can use to repair your data so you dont have to clear/reload like you did in your first post.

**Comment by garfield69** [comment]
OK. I have had time to examine the logs you provided in more detail, and what I see there is that when the auto-download searches for the latest episode, it is fetching one of the previous episodes instead.

Now this is not supposed to be happening any more, as issue #396 (auto-download does not always pick the correct episode for download)  was fixed by commit 7bf44230b1acbfd8194f107715d14096c615571e (fixed #396 by adding a strict word filter).

However examining this commit I see that the patch only applies to the torrentDialog.js, and it should also  have been applied to the AutoDownloadService.js

So I shall re-open #396, and work on applying the patch there as well.

**Comment by garfield69** [comment]
OK. So I patched the autoDownloadService to include the strict word filter.
If you are willing to be an ALPHA tester, fetch the latest development version from GitHub and try it out.
I have not exhaustively tested the patch, but the few debug runs I did seemed to go ok.

**Comment by patrickacollier** [comment]
great work! That would make since why the manual search would filter but not the auto service. I'll pull the changed autoDownloadService and retest. Did you say there was a way to clear the db of the matched info? If not i can just wait until this evening.

**Comment by garfield69** [comment]
>Did you say there was a way to clear the db of the matched info?

Right. Make sure you fetch the latest DuckieTV  Development version. It includes the magnet reset code.
To clear an episode that has been incorrectly marked as downloaded, all you have to do is:
- click on the offending episode on the calendar
![image](https://cloud.githubusercontent.com/assets/6933240/9667580/adefa2b0-52d0-11e5-9e4b-568057ac75dd.png)
- click on the `marked as downloaded` button.
![image](https://cloud.githubusercontent.com/assets/6933240/9667710/8f874b9c-52d1-11e5-8e40-31b1855ce591.png)
- this will change state to indicate the episode has not been downloaded.
![image](https://cloud.githubusercontent.com/assets/6933240/9667730/af6bcf46-52d1-11e5-8cfb-db71926830db.png)
- if you need to reset an episode whose broadcast date is in the future, just click on the `click here if the episode has leaked online` link , to make the buttons available.
![image](https://cloud.githubusercontent.com/assets/6933240/9667678/50a7fd72-52d1-11e5-9091-0e35b04df038.png)

**Comment by patrickacollier** [comment]
Nice! That's an elegant way of doing it and less real estate needed.Thanks!

**Comment by patrickacollier** [comment]
I pulled the latest changes and let it run and still got a mismatch. ep30 downloaded for ep31.
just to add its only doing it on same day episodes that a correct match hasn't been uploaded.
![image](https://cloud.githubusercontent.com/assets/14065117/9676032/b7c635d4-5293-11e5-89d6-696d743ac930.png)

**Comment by garfield69** [comment]
That is odd. Are you pulling individual commits are fetching the complete GitHub archive?
I ask, because I see you are still getting `episode air check fired` messages, that you would not be getting if you were using the latest code.
Can I suggest you download this [archive](https://github.com/SchizoDuckie/DuckieTV/archive/angular.zip) and replace your complete folder with its unpacked contents.

**Comment by patrickacollier** [comment]
hmmm. I zipped the current repository and overwrote the old 1.1.3 dev that i had. I verified that the AutoDownloadService.js had the new changes. I have the prod release in a completely seperate folder and not running, do you think i should remove it for some reason it could be using the wrong paths? long shot but figured i'd check.

**Comment by patrickacollier** [comment]
I will try the archive though.

**Comment by garfield69** [comment]
You should not need to remove the prod version.
If you have replaced the correct folder, the next most likely explanation is that nwjs was not actually shut down.
If (for instance) it was minimized, then launching the program again would simply maximise the existing instance of the programs window again.
So close the program, and check with task manager that it is actually shut down before launching it again.

**Comment by patrickacollier** [comment]
I promise I downloaded the newest archive and I'm still getting the "episode air check fired" and the incorrect magnet downloaded for auto. this time It immediately showed as 100% I assume because that episode was already downloaded. (ep10 downloaded for ep11)
![image](https://cloud.githubusercontent.com/assets/14065117/9708135/76673440-54e5-11e5-9a14-52e9d00e4968.png)

**Comment by garfield69** [comment]
In that case, I see two possibilities:
1. the nwjs you are running has not been shut down properly and is still running the old code from memory 
OR
2. the nwjs you started is getting it's source from a different folder than the one you replaced with the GitHub archive.

How are you launching the program? Describe what you click on, what it is called, where it is, so I can try to understand what is going on here.

Edit the file called VERSION with a plain text editor and change it to 1.1.4. 
Launch nwjs and then go to the DuckieTV ABOUT page [ (i) icon on bottom left). 
The top of the ABOUT page should now read ABOUT DUCKIETV V1.1.4
scroll down to the statistics section at the bottom of the ABOUT page, and screen dump it and paste it here for us to take a look at.

**Comment by patrickacollier** [comment]
Damn. It was with Windows 10 extract and replace. The files weren't being replaced. Only when I extracted first and then copy/replace was it actually overwriting the old files. Sorry for the trouble. I'll see how it goes from here.

**Comment by patrickacollier** [comment]
ok, now that i'm acutally on alpha your autodownloadservice fix is working. so far 5 days and no issues.

**Comment by garfield69** [comment]
Excellent. Thank you for reporting back. Cheers.
