### ISSUE TITLE
Powder Player support

### ISSUE THREAD

**Issue by jaruba** [SchizoDuckie/DuckieTV#546]
Would you be interested in support for Powder Player too?

http://powder.media/
https://github.com/jaruba/PowderPlayer

It would stream torrents with videos directly, find subtitles automatically (and auto-selects them), etc.

If you are interested in integrating it in DuckieTV, I would be glad to make all the necessary changes required for it to be fully compatible (maybe even an `agent` parameter so you can set the DuckyTV logo to show on the videos you start). :)

**Comment by SchizoDuckie** [comment]
That would be *super* awesome! Do you already have an API available that I could hook onto the generic DuckieTV TorrentClient API ?

**Comment by jaruba** [comment]
Great! Our apps really look like 2 sides of the same coin. :))

I've made [powder-remote](https://github.com/jaruba/powder-remote/wiki/JavaScript-API) a while back, but I still need to remove the dependency on `deasync` in order to finish it.

This is the current JS API for it: https://github.com/jaruba/powder-remote/wiki/JavaScript-API

Just tell me what else you would need in the API.

There's one thing I'm curious about though, DuckieTV has pre-downloading of episodes, this is not needed for Powder Player as it streams the videos, and prebuffering is usually super fast. How do you think this should be handled?

> do you guys have chromecast support planned?

Chromecast is planned (i even bought one) and should not be necessarily complicated, Airplay will be more difficult though as I can't seem to find a good testing environment for it.

**Comment by SchizoDuckie** [comment]
Let's get on twitter, skype or hangouts so we can have a little chat
tonight. we should be able to work something out :)

**Comment by jaruba** [comment]
I PM'ed you on Gitter. :)

**Comment by shadycady** [comment]
Liking where this talk is heading. 
I remember asking for an 'open/play episode button' earlier : )   This sounds good too tho ;)  
"To Stream or Download my TV shows, That is the Question."

**Comment by SchizoDuckie** [comment]
ping @jaruba make it work babeh
![https://i.imgur.com/mqMmSSI.gif](ohboyohboyohboy)

**Comment by jaruba** [comment]
@SchizoDuckie 

![tumblr_mcszfznt7a1rk89p8o1_500](https://cloud.githubusercontent.com/assets/1777923/16606858/45116106-4344-11e6-8b29-faabd872c50b.gif)

**Comment by SchizoDuckie** [comment]
@jaruba any status on the api?

**Comment by jaruba** [comment]
Omg, his alive!

**Comment by SchizoDuckie** [comment]
add me on skype brah

**Comment by jaruba** [comment]
gimme your skype id then
