### ISSUE TITLE
Database <-> torrent naming conventions is mostly wrong with content like Anime.

### ISSUE THREAD

**Issue by GenuineSounds** [SchizoDuckie/DuckieTV#547]
Latest Chrome, latest extention.

Most anime are not named via a tv show naming scheme 'Show S##E##' but rather by a sequential number 'Show ###'.

Due to this you're not likely to get any auto downloads to work with them. There isn't an easy fix either. There really is no database that maps TV show format to Anime format.

I'll leave a specific example here so you can actually test it yourself:
Dragon Ball Super S01E08 would be Dragon Ball Super 008 in the anime world.

= Here's my REAL problem though =
I couldn't even make a manual search for 'Dragon Ball Super 008'. I have no idea what it's actually searching for but it's not showing anything in the results.

I couldn't find a log for the extension anyway, otherwise I would have brought you some information rather than this issue.

**Comment by garfield69** [comment]
I've no trouble searching for `dragon ball super 008`
![image](https://cloud.githubusercontent.com/assets/6933240/9655145/36defe48-5283-11e5-8b76-e8d365597166.png)
get to the log by pressing the F12 key, and clicking on the `console` tab.

**Comment by garfield69** [comment]
@GenuineSounds  So did you get the search working?
if not, take a screen shot of the statistics section at the bottom of the DuckieTV About page using the (i) icon on the left hand side of the main DuckieTV page, and of the console log (F12, console tab) so we can take a look.

**Comment by GenuineSounds** [comment]
@garfield69 The search did start working, I'm not sure what the problem was but it seems to have fixed itself. It might have been that TPB (which is the search engine I have selected) was being stupid at the time. We can go ahead and close this issue for now.

**Comment by garfield69** [comment]
ticket [664](https://github.com/SchizoDuckie/DuckieTV/issues/664) looks into how we could support some Anime titles by using thexem.de database, which we already plug in to for scene name support.
