### ISSUE TITLE
Autodownload Exclude Keywords

### ISSUE THREAD

**Issue by Js41637** [SchizoDuckie/DuckieTV#548]
A list of excluded words to ignore the torrent for autodownloading. Things like quality or release groups. For me I never download anything in 720p so if I were to AutoDownload a whole show, excluding torrents with 720p would be noice.

**Comment by SchizoDuckie** [comment]
cool idea

**Comment by garfield69** [comment]
Will the exclude list be a per-series list, in the same manner as the customeSearchString element of the Series table, 
or
is the exclude list going to be a global list, which we store in the settings and applies to all searches?

**Comment by 51appy** [comment]
This would be great.  I sometimes get Spanish episodes if that is all KAT has vice excluding them and going to the next site.
