### ISSUE TITLE
implement Dialgauge and other features on DuckieTorrent sidepanel

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#549]
Trying magnets with uTorrent for the first time. :-)
and while the calendar and file details page show activity...
![image](https://cloud.githubusercontent.com/assets/6933240/9720607/acb9775c-55e3-11e5-8f44-d0088d707c62.png)
the dialgauge  on the Duckietorrent uTorrent client page is not. (progress bar is working though).
![image](https://cloud.githubusercontent.com/assets/6933240/9720661/65104704-55e4-11e5-9850-f15ad172dcd2.png)

Note: I recently upgraded dialgauge to 0.1.5 e3f4b60bf419a97268853fd6e9ec3fa99276d813 to stop a TypeError, so its possible this is broken.

**Comment by garfield69** [comment]
progress. got the 2nd dial working (at least with uTorrent Web UI, but not with uTorrent API yet).
![image](https://cloud.githubusercontent.com/assets/6933240/9721863/1bf86142-55f7-11e5-8822-9b6e3f4d429c.png)
May work on it some more after the tennis, if no one has resolved it before then ;-)

**Comment by SchizoDuckie** [comment]
Yeah the first gauge hasn't been inmplemented yet. this panel is mostly still a mockup. I do want to put the video controls and stuff in here too

**Comment by garfield69** [comment]
Switching ticket from bug to enhancement tracker.

**Comment by garfield69** [comment]
I will work on getting the first dial going, by implementing a getTransferSpeed() method across all the torrent clients.

**Comment by garfield69** [comment]
test checklist.
- [ ] deluge
- [ ] qBitTorrent
- [ ] qBitTorrentPlus
- [ ] Tixati
- [ ] Transmission / Vuze
- [ ] uTorrentAPI
- [ ] uTorrent WEBUI

**Comment by garfield69** [comment]
\o/ successfully implemented download Speed retrieval for all torrent clients, and implemented working gauges for the torrentClient sidepanel.

**Comment by SchizoDuckie** [comment]
You are a hero!

**Comment by SchizoDuckie** [comment]
It looks glorious and works awesome. Marking this as fixed!
