### ISSUE TITLE
DuckieTV 1.1.3 (patch) release to do list.

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#550]
Recall seeing Schizoduckie suggesting on [Reddit](https://www.reddit.com/r/duckietv/comments/3k5225/torrent_integration_not_working_mac_utorrent_or/) that we should release an interim (pre 1.2.0) patched version.
schizoduckie:
>I'll try to finish up some of the patches real soon, disable some unused functionality and get some of the fixes that were already built released asap so that the experience for first-timers improves!

So this is the preliminary to do list (add or subtract as required):
- [x] prep the version to 1.1.3 as required (VERSION, MANIFEST, PACKAGE, etc).
- [x] hide any w.i.p. pages or features using some html tricks
  - [x] #549
  templates/torrentClient.details.html line 6
  ```javascript
<hide-prod>
<div class="dg">
  <ng-dial-gauge id="gauge1"
               scaleMin="0"
               scaleMax="100"
               borderWidth="0"
               ng-model="vm.transferSpeed"
               trackColor="white"
               barColor="lime"
               barWidth="10"
               units="kb/s"
               angle="180"
               border-color="white"
               rotate="-180"
               lineCap="square"
               style="fill:white;font-weight:100;height:450px;">
  </ng-dial-gauge>
  <ng-dial-gauge id="gauge2"
               scaleMin="0"
               scaleMax="100"
               borderWidth="0"
               ng-model="vm.progress"
               trackColor="white"
               barColor="lime"
               barWidth="10"
               units="% completed"
               angle="180"
               borderColor="white"
               rotate="-180"
               lineCap="square"
               style="fill:white;font-weight:100;height:450px;">
  </ng-dial-gauge>
</div>
</hide-prod>
  ```
  - [ ] #537
   fast search directive. the hide-prod method does not work on the 
  ```javascript
<fast-search></fast-search>
  ```
  - [x] #463
  tab.html line 69
  ```javascript
          <li class="hide-prod" id="actionbar_switch" ui-sref-active="active">
            <a ng-click="setSetting('main.viewmode', getSetting('main.viewmode') == 'calendar' ? 'todo' : 'calendar')" class="glyphicon glyphicon-check" tooltip="Switch between calendar and todo mode" tooltip-placement="right"></a>
          </li>
  ```
  - [x] #18 
  templates/sidepanel/settings.html line 105
  ```javascript
    <tr class="hide-prod" ui-sref-active='active' ui-sref=".tab({tab: 'custom-search'})" ng-if="getSetting('torrenting.enabled')">
      <td colspan="2">
          <a href="#/settings/custom-search">
              <i class="glyphicon glyphicon-search"></i><strong>My Custom Search Engines</strong>
          </a>
      </td>
    </tr>
  ```
  - [x] #569
  templates/about.html line 69
  ```javascript
    <!-- #569 test -->
    <tr class="hide-prod">
      <td>
        <h1>Mac reload systray test</h1>
        <p>This option tests if a reload, while in systray mode, causes multiple trays to be created on Mac systems.</p>
        <p>Enabling it causes the reload timer to be set to 1 minute. minimize to systray and watch for new ducks to show up on systray every minute.</p>
        <p>Disable to return timer back to default setting. Restart DuckieTV to clear systray of duck clones.</p>
        <p><strong  translate-once="COMMON/current-setting/hdr"></strong>
        {{ macTestEnabled ? 'COMMON/enabled/lbl' : 'COMMON/disabled/lbl'|translate}}</p>
        <button class='btn' ng-class="{'btn-danger': !macTestEnabled, 'btn-success': macTestEnabled}" ng-click="toggleMacTest()">{{ macTestEnabled ? 'COMMON/disable/btn' : 'COMMON/enable/btn'|translate}}
        <span>Mac Reload Test</span></button>
      </td>
    </tr>
    <!-- end #569 test -->
  ```
- [x] fix any outstanding urgent bugs
  - [x] #513
  - [x] #507

- [x] if XEM is going live with this release, then activate the process that regularly updates the XEM GitHub cache
- [x] prep the changelog
- [x] ~~prep the migrationService if required~~(not required)
- [x] prep the upgradeNotificationService
- [x] amend production build scripts to include css/hide-prod.css to the tab.html style list
- [x] tag and draft a new GitHub release
- [x] prep the build suite
- [x] generate the standalones
- [x] push to chrome store
- [x] update the gh-pages
- [x] post an announcement on Reddit and Facebook
- [ ] have a beer

**Comment by garfield69** [comment]
@SchizoDuckie  I believe this is ready now for final peer review and testing. Then its up to you to action the rest when you want to.

**Comment by SchizoDuckie** [comment]
Excellent. The only blocker I still have here is the nightly build system and automating the shit out of the deployment procedure so that we can continuously verify that the new releases built are working properly. 

- [x] Windows
- [ ] OSX
- [ ] Linux
- [x] Android
- [ ] Chrome Browser Action
- [ ] Chrome New Tab

I'd love to get some form of permanent storage sorted in so that people can test out the first draft of the custom search engines as well (Should probably end up in the database) but since I sold my house and need to move out i'm not sure of how much time i'll have for that this week.

**Comment by Js41637** [comment]
Instead of commenting out wip features, what about like an ng-if="dev" and save some dev parameter in localStorage

**Comment by garfield69** [comment]
>Instead of commenting out wip features, what about like an ng-if="dev" and save some dev parameter in localStorage

Good idea if it can be done. I've expanded the scope of #504 to track it.

**Comment by garfield69** [comment]
Guys, I am still looking for a css controlled method to disable the fast-search directive in PROD and not DEV.
is there a way to prevent the tab.html `<fast-search></fast-search>` from invoking the fast-search directive by using css included in the hide-prod.css ?

**Comment by Js41637** [comment]
Tbh the fast directive already works pretty well.

**Comment by garfield69** [comment]
>Tbh the fast directive already works pretty well.

Huh? the fast search is WIP, and has a few little glitches still ;-)
 it often reports that I have a series, and at the same time that I don't have that same series
![image](https://cloud.githubusercontent.com/assets/6933240/10408818/7eb81476-6f65-11e5-9de5-f9c3d97e7b16.png)
The click to add does not work, bringing up a empty loading side-panel instead of the add-a-series page
and finally, I think clicking in the episode list should take you to that episode's details page, but only the download and cloud buttons work.

Regardless, since most users are used to using the mouse to navigate DuckieTV PROD, they may not stumble onto the fast-search since that required using the keyboard. So it will probably stay hidden until the WIP is complete.

But if there is a nice css way of preventing it activating then I'd like to have it in place, if only to stop the inevitable it-does-not-work posts in Reddit/GitHub when users do stumble on it. :-)

**Comment by SchizoDuckie** [comment]
All done but the beer!!
