### ISSUE TITLE
Season Navigation

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#551]
As raised in this [Reddit](https://www.reddit.com/r/duckietv/comments/3l3c0g/feature_request_improved_season_navigation/)

call_da_ambalampss:
>I'd like to request a minor improvement for navigating seasons for a particular show. When we navigate today, we have to click back on the "Seasons" tab, and then into the next season I want to see episodes for.
>I wanted to suggest a new way to go through the different seasons for a particular show. By simply adding navigation buttons to the top of the episode section. Ive created a very simple mock up to show my request.
http://i.imgur.com/CEI2sCc.png?1

**Comment by Js41637** [comment]
Ahh yeah good idea.
![image](https://cloud.githubusercontent.com/assets/6258213/9894834/da3268ae-5c6b-11e5-8845-c0cdc61cb95e.png)

**Comment by garfield69** [comment]
testing completed. Good work :+1:

**Comment by Js41637** [comment]
Ironically turned out to be harder than I thought initially because I was over complicating it but then I realised the simpler approach.
