### ISSUE TITLE
Cannot Get an Torrent client to link on Mac

### ISSUE THREAD

**Issue by steveches** [SchizoDuckie/DuckieTV#553]
having found the software this morning, which is great by the way. i am unble to get anything to work on the mac. it does on windows, but not on my main mac. i have tried all the torrent clients listed, and none work. the only one that shows as connected is utorrent, but then still tries to connect through the software itself. and fails.  it may just be me being new to it, but i would like to be able to get it working.

**Comment by garfield69** [comment]
Ah. Yes, sorry about that. :-(
DuckieTV 1.1.2 on the Mac does indeed have an problem with the torrent client interfaces.
Issue #513 has been resolved, so the next release of DuckieTV should return full torrent functionality to the Mac.
We plan to release a patched version of DuckieTV #550, but I don't have an ETA for you.

If you are keen to try out a working Mac version, you could have a go installing the development version of DuckieTV.
Instructions are available on our wiki, [https://github.com/SchizoDuckie/DuckieTV/wiki/How-to-install-development-versions-of-DuckieTV](https://github.com/SchizoDuckie/DuckieTV/wiki/How-to-install-development-versions-of-DuckieTV), and [https://github.com/SchizoDuckie/DuckieTV/wiki/Setting%20up%20Torrent%20Clients%20for%20DuckieTV%201.1.2](https://github.com/SchizoDuckie/DuckieTV/wiki/Setting%20up%20Torrent%20Clients%20for%20DuckieTV%201.1.2).
