### ISSUE TITLE
Wrong flags associated with subtitle languages 

### ISSUE THREAD

**Issue by najob** [SchizoDuckie/DuckieTV#554]
As title says, I have noticed several wrongfully associated flags with languages.
Yes, I am little bit interested in vexillology! :smile: 

[Screenshot](https://i.imgur.com/CUyzRwD.png)
[Statistics](https://i.imgur.com/rQ2rMB3.png)

So, here we go (linking to Wikipedia):

Language | Current flag | Suggested flag
------------- | --------------- | -------------------
Arabic | [Flag of Argentina](https://en.wikipedia.org/wiki/Flag_of_Argentina) | [Flag of the Arab League](https://en.wikipedia.org/wiki/Flag_of_the_Arab_League)*
Estonian | [Flag of Ethiopia](https://en.wikipedia.org/wiki/Flag_of_Ethiopia) | [Flag of Estonia](https://en.wikipedia.org/wiki/Flag_of_Estonia)
Indonesian | [Flag of India](https://en.wikipedia.org/wiki/Flag_of_India)| [Flag of Indonesia](https://en.wikipedia.org/wiki/Flag_of_Indonesia)
Khmer | [Flag of the Comoros](https://en.wikipedia.org/wiki/Flag_of_the_Comoros) | [Flag of Cambodia] (https://en.wikipedia.org/wiki/Flag_of_Cambodia)
Malay | [Flag of Montserrat](https://en.wikipedia.org/wiki/Flag_of_Montserrat) | [Flag of Malaysia] (https://en.wikipedia.org/wiki/Flag_of_Malaysia)
Serbian | [Flag of Suriname](https://en.wikipedia.org/wiki/Flag_of_Suriname) | [Flag of Serbia](https://en.wikipedia.org/wiki/Flag_of_Serbia)
Slovenian | [Flag of Sierra Leone](https://en.wikipedia.org/wiki/Flag_of_Sierra_Leone) | [Flag of Slovenia](https://en.wikipedia.org/wiki/Flag_of_Slovenia)
Swedish | [Flag of El Salvador](https://en.wikipedia.org/wiki/Flag_of_El_Salvador) | [Flag of Sweden](https://en.wikipedia.org/wiki/Flag_of_Sweden)
Tagalog | [Flag of East Timor](https://en.wikipedia.org/wiki/Flag_of_East_Timor) | [Flag of the Philippines] (https://en.wikipedia.org/wiki/Flag_of_the_Philippines)

*Less common used (on internet) [Flag of the Arab Revolt](https://en.wikipedia.org/wiki/Flag_of_the_Arab_Revolt).

I think these are not wrong (except Galician), but I am not expert in international relations, and I understand that this could be tricky for some people so maybe leave it as it is?

Language | Current flag | Suggested flag
------------- | --------------- | -------------------
Basque | [Flag of Spain](https://en.wikipedia.org/wiki/Flag_of_Spain) | [Ikurriña](https://en.wikipedia.org/wiki/Ikurri%C3%B1a)
Catalan | [Flag of Spain](https://en.wikipedia.org/wiki/Flag_of_Spain) | [Senyera](https://en.wikipedia.org/wiki/Senyera)
Galician | [Flag of Greenland](https://en.wikipedia.org/wiki/Flag_of_Greenland) | [Flag of Galicia](https://en.wikipedia.org/wiki/Flag_of_Galicia)

And the last thing, maybe Chinese(simplified) and Chinese(traditional) could be little closer.

**Comment by garfield69** [comment]
@najob Thank you for spotting this.

It looks like out cross-matching tables of languages versus shortCodes has been incorrectly loaded.
For reference, here are the two current tables:
```javascript
        var languages = {
            alb: 'Albanian',
            ara: 'Arabic',
            baq: 'Basque',
            bul: 'Bulgarian',
            cat: 'Catalan',
            chi: 'Chinese (simplified)',
            cze: 'Czech',
            dan: 'Danish',
            dut: 'Dutch',
            eng: 'English',
            est: 'Estonian',
            fin: 'Finnish',
            fre: 'French',
            geo: 'Georgian',
            ger: 'German',
            glg: 'Galician',
            ell: 'Greek',
            heb: 'Hebrew',
            hin: 'Hindi',
            hrv: 'Croatian',
            hun: 'Hungarian',
            ice: 'Icelandic',
            ind: 'Indonesian',
            ita: 'Italian',
            jpn: 'Japanese',
            khm: 'Khmer',
            kor: 'Korean',
            mac: 'Macedonian',
            may: 'Malay',
            nor: 'Norwegian',
            per: 'Persian',
            pol: 'Polish',
            por: 'Portuguese',
            rus: 'Russian',
            scc: 'Serbian',
            sin: 'Sinhalese',
            slo: 'Slovak',
            slv: 'Slovenian',
            spa: 'Spanish',
            swe: 'Swedish',
            tgl: 'Tagalog',
            tha: 'Thai',
            tur: 'Turkish',
            ukr: 'Ukrainian',
            vie: 'Vietnamese',
            rum: 'Romanian',
            pob: 'Brazilian',
            zht: 'Chinese (traditional)'
        };

        var shortCodes = {
            alb: "al",
            ara: "ar",
            bul: "bg",
            baq: "es",
            cat: "es",
            cze: "cz",
            dan: "dk",
            dut: "nl",
            eng: "gb",
            epo: "eo",
            est: "et",
            fin: "fi",
            fre: "fr",
            geo: "ge",
            ger: "de",
            glg: "gl",
            ell: "gr",
            heb: "il",
            hin: "in",
            hrv: "hr",
            hun: "hu",
            ice: "is",
            ind: "in",
            ita: "it",
            jpn: "jp",
            kor: "kr",
            khm: "km",
            mac: "mk",
            may: "ms",
            nor: "no",
            per: "ir",
            pob: "br",
            pol: "pl",
            por: "pt",
            rus: "ru",
            scc: "sr",
            slo: "sk",
            sin: "lk",
            slv: "sl",
            spa: "es",
            swe: "sv",
            tgl: "tl",
            tha: "th",
            tur: "tr",
            ukr: "ua",
            vie: "vn",
            rum: "ro",
            zht: "cn",
            chi: "cn"
        };
```
The shortCodes table is supposed to be loaded with the ISO 3166-1 alpha-2 formatted Country codes, but clearly that data has been incorrectly loaded.
for example, language ara (Arabic) has been incorrectly matched with country code ar (Argentina), which explains why the flags end up as they currently do.

Should be a simple matter to correct.

**Comment by najob** [comment]
I am glad if I could help. I just naively looked at [DuckieTV/img/flags.png](https://github.com/SchizoDuckie/DuckieTV/blob/34d703ecf837dc8edcdc07a4481309c46eacb2c2/img/flags.png) and assumed that maybe is just added wrong set of flags in flags.png because there are not any of them mentioned in my previous comment.

**Comment by garfield69** [comment]
note: we are restricted to using flags available on https://www.flag-sprites.com/en_US/ which means we don't have access to the Arab League.  Have flags for the 21 members of the league, but which one to pick as a representative?

**Comment by garfield69** [comment]
I'm going to leave Basque and Catalan with the flag of Spain, and add Galician to that list.
Since Egypt has the largest population of Arab speaking citizens, I will use that flag.
I've corrected the remaining miss matches.

**Comment by najob** [comment]
It could be flag of Saudi Arabia, as well, but I am really going to leave you that decision. From mine standpoint everything that you previously said seems fine and understandable.
Here are discussions on that topic, on [Qoura](https://www.quora.com/Which-flag-represents-the-Arabic-language) and [StackExchange](http://ux.stackexchange.com/questions/63198/what-would-be-an-appropriate-visualization-for-the-arabic-language). 

And finally thank you for your response, making this great application even better.
