### ISSUE TITLE
Setting up DuckieTV with Transmission

### ISSUE THREAD

**Issue by johnfair** [SchizoDuckie/DuckieTV#557]
I am running Mac OS X Yosemite 10.10.5 on a MBP. I have Transmission 2.84 with DuckieTV 1.1.2. I have followed the directions to have it connect with Transmission but it doesn't see Transmission. When I select Transmission Integration, all I see in the right side is the Transmission logo. 

I have also tried both apps on the Mac running 10.9.5 and have the same result.

**Comment by lonelyfairie** [comment]
Issue was reported already under #513.

Sent from my Windows Phone
________________________________

**Comment by garfield69** [comment]
@johnfair  Thank you for reporting. The torrent integration is broken on DuckieTV 1.1.2 on the Mac platform. A Fix has already been made and will be included in the next release of DuckieTV.

If you do not want to wait until the next release, you might consider using the development version of DuckieTV, which has the fix applied. 

This wiki [How to Install Development versions of DuckieTV](https://github.com/SchizoDuckie/DuckieTV/wiki/How-to-install-development-versions-of-DuckieTV)  should guide you, and this wiki [Setting up Torrent Clients for DuckieTV](https://github.com/SchizoDuckie/DuckieTV/wiki/Setting%20up%20Torrent%20Clients%20for%20DuckieTV%201.1.2) should be of use if you have further problems hooking up Transmission with DuckieTV DEV.

**Comment by johnfair** [comment]
Thanks!!!
