### ISSUE TITLE
Using the Dev 1.1.3 unable to select find a torrent in a few shows

### ISSUE THREAD

**Issue by shadycady** [SchizoDuckie/DuckieTV#559]
I am unable to click find a torrent for The Late Show for Stephen Colbert.... Still auto downloads tho
20/20 is the same way however it very rarely finds the episode anyways

Love, love that KAT is no longer pulling up incorrect info especially cause torrentz is gone 

Is the streaming feature supposed to show up or is that still work in progress?

Is there anything specific that you need help testing- 
I use everyday and with more shows than i think the average user may.

**Comment by garfield69** [comment]
>I am unable to click find a torrent for The Late Show for Stephen Colbert

please provide some more detail...which page are you on, which button you are pressing, and what happens next. Screencaptures would help (Print Screen keyboard button, CTRL-v straight into the empty box below). Also please check the log for errors (F12 button, console tab, entries with a red cross icon next to them). Screencapture those as well. 

>Love, love that KAT is no longer pulling up incorrect info especially cause torrentz is gone

Huh? I am still getting Torrentz results...checked the log for errors?

>Is the streaming feature supposed to show up or is that still work in progress?

I can't keep up with all the WIP that Schizoduckie has juggling ;-) Can you screencapture the page you are referring to? I can probably then backtrack the status but looking over the relevant code.
Odds are very good its WIP, and not complete or reliable.

**Comment by garfield69** [comment]
Ha. Strange that the email of the original post has more text than what is posted by GitHub.

>Is there a new auto search timing option ie once every hour or twice an hour setting or...

the auto-download has been altered from a 2hour cycle to once every 15 minutes.

 re: The Late Show for Stephen Colbert
never mind the screendumps, I've just tried it myself and I see there is a problem.
getting
```javascript
TypeError: undefined is not a function
    at Object.service.findEpisode (TorrentSearchEngines.js:75)
    at Scope.$scope.openDialog (torrentDialog.js:149)
    at angular.js:13686
    at callback (angular.js:23298)
    at Scope.$eval (angular.js:15846)
    at Scope.$apply (angular.js:15945)
    at HTMLAnchorElement.<anonymous> (angular.js:23303)
    at HTMLAnchorElement.eventHandler (angular.js:3271)
```
ticket [555](https://github.com/SchizoDuckie/DuckieTV/issues/555) was raised by bionikspoon to replace TLSfSC search string ... maybe related, I shall investigate.

**Comment by shadycady** [comment]
Yeah tried to hide that question shown on your email. Hate when people
don't at least make an attempt at looking.
I found it after reading though Github
That is a great add on.

It's weird just figured torrentz was down past couple days only to find out
from you and my phones 4G that it is not down. However I cannot get to it
from my network anymore :-(

**Comment by garfield69** [comment]
Oops, not complete yet, still some permutations that return errors.
