### ISSUE TITLE
avoid sending (') to torrent search

### ISSUE THREAD

**Issue by shadycady** [SchizoDuckie/DuckieTV#560]
is there a way to avoid sending the  (')  to the torrent search

now the kickass search is 'tighter' 

for instance ~~"Somebody's Got to do it S03E01"~~ [edit] "Somebody's Gotta do it S03E01" gets no results but without (') it pulls results
I couldn`t think of another series off hand to check but imagine it would fix more than it breaks if anything.

I'm using the Dev of the standalone 1.1.3 Really Running Great ! 

Anyone noticed that some torrents stay at 0 seeds for a long time sometimes days before being listed with seeds/leaches in +0, even though forced with # of seeds set to 0 it will grab the torrent with plenty of seeds. Not a DuckieTV problem but kat and pb issue or they are doing something different maybe. Only matters if you are the type that wants it NOW.

Anyways....
DuckieTV + uTorrent + FileBot + Plex = So Damn Happy, just about can't stand it!

**Comment by garfield69** [comment]
Hmm. That's odd, because we're supposed to already be stripping the single quotes from the search strings, so something is not working as it should any more... needs investigation.
