### ISSUE TITLE
Avoid searching torrents with "()" on the names.

### ISSUE THREAD

**Issue by lonelyfairie** [SchizoDuckie/DuckieTV#561]
Eg. Masterchef (US) returns no results but Masterchef US does. 
Shows that have some part of the title that uses parenthesis are not found, usually series like Masterchef that have shows per country do this.

Thanks in advance!

**Comment by garfield69** [comment]
@lonelyfairie  Thanks for reporting.

**Comment by lonelyfairie** [comment]
Tested it on the latest angular version and it is working correctly, thanks for the quick fix :)
