### ISSUE TITLE
Clicking find torrent coes up with wrong info

### ISSUE THREAD

**Issue by shadycady** [SchizoDuckie/DuckieTV#562]
Fast n' loud s07e05 clicking find a torrent brings up a search for Fast n' loud s06e04.

Also if I click download all in any series instead of downloading individually it brings up a search for 'series name' 'season' #.

Using Dev 1.1.3

**Comment by Js41637** [comment]
Depending on the torrent search your using old episodes can be returned if none are found, this is very common for new episodes if they're not out yet.

**Comment by Js41637** [comment]
-Removed-

**Comment by garfield69** [comment]
>Fast n' loud s07e05 clicking find a torrent brings up a search for Fast n' loud s06e04.

According to the XEM db (which DuckieTV taps into to reconcile differences between tvdb episode names and torrent names ion the scene), fast 'n loud s7e5 on tvdb is actually s6e4 on the scene.
XEM is usually pretty good at reconciling tvdb and scene cross-referencing. Are you confident this is a mistake in XEM's db?
@SchizoDuckie thoughts on what to do if anything?

>Also if I click download all in any series instead of downloading individually it brings up a search for 'series name' 'season' #.

I'll investigate this, might be similar to what I found when looking into #559

**Comment by garfield69** [comment]
>Also if I click download all in any series instead of downloading individually it brings up a search for 'series name' 'season' #.

@shadycady  I'm not seeing this. Are you on the very latest refresh of the DEV?
IF you are, can you upload a screen shot of the page you are on showing the problem so I can check I'm using the same button you are taking about? Thanks.

**Comment by Js41637** [comment]
I just quickly tested, pressing the Autodownload All on the serie episodes page opens the torrent dialog the same as the search for a download for this season button.

**Comment by Js41637** [comment]
And is searching for 'series name' 'season' # so, Doctor Who Season 8 for some reason.

**Comment by garfield69** [comment]
![image](https://cloud.githubusercontent.com/assets/6933240/10155295/e46f1f74-66cf-11e5-9c08-158075498b53.png)
Oh, so you are saying that both buttons circled above are performing the same function?
The right button is supposed to search for the season torrent manually (and is working as designed), but the left button is supposed to kick off individual torrent fetched for each episode in the season using the auto-download code. Some prior commit seems to have F'ed up this feature.

**Comment by Js41637** [comment]
Yeah they do the same thing although I only quickly looked over the code but auto download all looked to go through the proper stuff, I'm not sure what's happening.
