### ISSUE TITLE
can not download torrents using TorrentZ SE and Deluge TC 

### ISSUE THREAD

**Issue by henkoe** [SchizoDuckie/DuckieTV#563]
https://snapr.pw/i/3dff1f7d12.png
when i try to download a serie the torrent those not show up in my torrent client

here is the console output
Registering torrent search engine: Torrentz
app.js:9124 Auth result:  true
app.js:8971 Deluge check result:  true
app.js:8893 Deluge connected!
app.js:7880 Torrent finished. marking as downloaded The.Strain.S02E06.HDTV.x264-KILLERS[ettv]
app.js:7880 Torrent finished. marking as downloaded Continuum.S04E04.720p.HDTV.x264-KILLERS[EtHD]
app.js:7880 Torrent finished. marking as downloaded The.Strain.S02E05.HDTV.x264-KILLERS[ettv]
app.js:7880 Torrent finished. marking as downloaded The.Strain.S01E06.HDTV.x264-2HD.mp4
app.js:7880 Torrent finished. marking as downloaded The.Player.2015.S01E01.HDTV.x264-LOL[ettv]
app.js:7880 Torrent finished. marking as downloaded The.Strain.S02E08.HDTV.x264-BATV[ettv]
app.js:7880 Torrent finished. marking as downloaded The Strain S01E03 HDTV x264-KILLERS[ettv]
app.js:7880 Torrent finished. marking as downloaded The Strain S01E11 WEB-DL x264-FUM[ettv]
app.js:7880 Torrent finished. marking as downloaded Ray.Donovan.S03E12.720p.HDTV.X264-DIMENSION[EtHD]
app.js:7880 Torrent finished. marking as downloaded The.Strain.S02E10.HDTV.x264-BATV[ettv]
app.js:7880 Torrent finished. marking as downloaded The.Strain.S02E11.HDTV.x264-BATV[ettv]
app.js:7880 Torrent finished. marking as downloaded The Strain S02E09 HDTV XviD-FUM[ettv]
app.js:7880 Torrent finished. marking as downloaded The Strain S01E10 WEB-DL x264-FUM[ettv]
app.js:7880 Torrent finished. marking as downloaded The.Strain.S01E07.HDTV.x264-KILLERS.mp4
app.js:5515 Initializing episode aired checker service!
app.js:8143 Not performing trakttv update check. already done today.
app.js:8155 Not performing trakttv trending update check. last done Mon Sep 28 2015 15:17:46 GMT+0200 (W. Europe Daylight Time)
app.js:5441 Deluge connected:  DelugeRemote
app.js:4753 Magnet selected! magnet:?xt=urn:sha1:88009716c7a75bc310fd2b513376137854980ce3
app.js:12073 Firing magnet URI!  magnet:?xt=urn:sha1:88009716c7a75bc310fd2b513376137854980ce3 5321797
app.js:12077 Adding via TorrentClient.addMagnet API!  magnet:?xt=urn:sha1:88009716c7a75bc310fd2b513376137854980ce3 5321797
app.js:4753 Magnet selected! magnet:?xt=urn:sha1:d9b4ce26e46ecf6daa4b2c5cc4cb0b99c7aa13c3
app.js:12073 Firing magnet URI!  magnet:?xt=urn:sha1:d9b4ce26e46ecf6daa4b2c5cc4cb0b99c7aa13c3 5303520
app.js:12077 Adding via TorrentClient.addMagnet API!  magnet:?xt=urn:sha1:d9b4ce26e46ecf6daa4b2c5cc4cb0b99c7aa13c3 5303520

**Comment by henkoe** [comment]
found one error in the console 

TypeError: Cannot read property 'torrents' of null
    at dist/app.js:9136
    at dist/deps.js:1624
    at n.$eval (dist/deps.js:1638)
    at n.$digest (dist/deps.js:1635)
    at n.$apply (dist/deps.js:1638)
    at l (dist/deps.js:1593)
    at M (dist/deps.js:1597)
    at XMLHttpRequest.F.onload (dist/deps.js:1598)(anonymous function) @ dist/deps.js:1614
dist/deps.js:1614 Error executing Deluge getTorrents(anonymous function) @ dist/deps.js:1614
dist/app.js:4753 Magnet selected! magnet:?xt=urn:sha1:6a5703976f4989d7b71bc5b6eadd946a06c57da4

**Comment by SchizoDuckie** [comment]
Thanks! thatś very helpful.
What version are you running?

**Comment by garfield69** [comment]
can you upload a PrintScreen of the DuckieTV page showing an example of the series you are having trouble downloading. Also let us know which button are you using so I can test. Thanks.

**Comment by henkoe** [comment]
i am using the browser-action Chrome version DuckieTV v1.1.2
deluge 1.3.11

**Comment by henkoe** [comment]
i think i found the problem 

it seems that only torrents from the Torrentz Search engine are not working

**Comment by garfield69** [comment]
well that narrows it down considerably. Good job, thanks.

**Comment by garfield69** [comment]
I cannot replicate your problem when using DuckieTV DEV and searching TorrentZ using a selection of my fav series.
Can you supply 1 or 2 series titles that are causing you problems when searching for them with torrentz? 
Even better, a particular episode that does not work. Note which line of the search result you are clicking the magnet icon on. Thanks.

**Comment by henkoe** [comment]
for me all my serie that dont wok 
https://snapr.pw/i/0e95377e85.png
i always just click on the top one  just on the name not on anything else

**Comment by henkoe** [comment]
Torrentz not working
Magnet selected! magnet:?xt=urn:sha1:88009716c7a75bc310fd2b513376137854980ce3
app.js:12073 Firing magnet URI!  magnet:?xt=urn:sha1:88009716c7a75bc310fd2b513376137854980ce3 5321797
app.js:12077 Adding via TorrentClient.addMagnet API!  magnet:?xt=urn:sha1:88009716c7a75bc310fd2b513376137854980ce3 5321797

 
ThePiratebay working
Magnet selected! magnet:?xt=urn:btih:88009716c7a75bc310fd2b513376137854980ce3&dn=Gotham.S02E02.HDTV.x264-LOL%5Bettv%5D&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Fexodus.desync.com%3A6969
app.js:12073 Firing magnet URI!  magnet:?xt=urn:btih:88009716c7a75bc310fd2b513376137854980ce3&dn=Gotham.S02E02.HDTV.x264-LOL%5Bettv%5D&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Fexodus.desync.com%3A6969 5321797
app.js:12077 Adding via TorrentClient.addMagnet API!  magnet:?xt=urn:btih:88009716c7a75bc310fd2b513376137854980ce3&dn=Gotham.S02E02.HDTV.x264-LOL%5Bettv%5D&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Fexodus.desync.com%3A6969 5321797

**Comment by garfield69** [comment]
Oh, I see now what is going on.
First a little background, feel free to skip to next paragraph if you know this.
Magnet url can support a variety of parameters. the oldest is the sha1 parm, which describes the base32 magnet hash. This has been subsequently superseded by the btih parm (BitTorrent Info Hash), which actually still uses the same sha1 hash, but supports additional co-parameters.
Anyway, long story short, torrent clients are supposed to have backward compatibility with the sha1 magnet parm. 

But Deluge does not support sha1 magnet parms.
Fortunately I have tested all the torrent clients that DuckieTV supports, and they all handle btih.
So the fix is easy, I'll change the TorrentZ search engine to post a btih instead of sha1.

**Comment by henkoe** [comment]
no problem glad i could help keep up the good work guys
