### ISSUE TITLE
Minimize to taskbar instead of tray?

### ISSUE THREAD

**Issue by SushiLover** [SchizoDuckie/DuckieTV#564]
Wow DuckieTV is absolutely an amazing program (just installed the Windows version). I wish I had found this sooner! One thing I don't care for though is that when it's minimized it has to go to the system tray. I prefer to see what's running by using my taskbar, is there any way to add an option to select minimize to the taskbar OR the system tray?

**Comment by SchizoDuckie** [comment]
Thanks :sunglasses: 

sounds like a simple tweak, will put this on the todo list :+1: 

Todo:

- [ ] Create setting under display
- [ ] Store setting in localStorage so that it can be accessed early
- [ ] Patch app.standalone.js to act on check
- [ ] Add translations

**Comment by SushiLover** [comment]
Awesome, thanks for the fast reply!
