### ISSUE TITLE
Mark all watched, confirmation dialog?

### ISSUE THREAD

**Issue by hexjelly** [SchizoDuckie/DuckieTV#570]
While you can argue it's a user error to do this, it also seems very easy to press the "mark all watched" buttons by mistake, both in the series information view and the season view. It'd be nice not having to go back and manually mark episodes you haven't watched after accidentally pressing this button. Maybe there could be a confirmation dialog before marking every episode of a series as watched; possibly as a optional setting?

**Comment by garfield69** [comment]
perhaps we could set the mark-all-watched as a toggled button that flips to mark-all-not-watched when used and visa-versa.

**Comment by garfield69** [comment]
on reflection, the toggled button idea is not useful. scratch that.

**Comment by Js41637** [comment]
While I too would put this down to user error it would definitely be a pain to fix if you pressed by accident it would just be annoying if you had to mark a lot of shows watched (not that one would often have too) and had to confirm everytime. Perhaps a 'do not ask again' for session storage as well would be ideal.

**Comment by garfield69** [comment]
How about an UNDO option? When the user presses the mark-all-watched button, we track which episodes are marked and offer a one-time immediate undo button that pops up and stays until the user leaves the page.

**Comment by hexjelly** [comment]
I personally prefer the idea of a setting for an optional confirmation dialog, but either feature would be great nonetheless. I imagine it would be slightly easier to implement as well?

**Comment by SchizoDuckie** [comment]
We can make a 2-click button maybe?  One that transforms from "mark all
watched into "sure?" That way you don't even have to move your mouse
Op 9 okt. 2015 00:47 schreef "Hexjelly" <notifications@github.com>:

**Comment by hexjelly** [comment]
Sounds like a good idea as well. The only potential caveat with that method would be whether or not it's clear enough that you need to press it twice, but perhaps there are limits to how much you can handhold users. E.g. someone might click it once, not notice the button changed and assume everything was marked, then go on about their business and click elsewhere, then wonder why it wasn't updated later.

**Comment by SchizoDuckie** [comment]
That's what UI transitions are for :) We can make a nice flip transition or
something, so that it rotates around the Y axis and shows the back of the
button

**Comment by garfield69** [comment]
for the serie-overview and seasons panels, I am going to implement the confirmation dialogue like this:

panel prior to clicking mark-all-watched
![image](https://cloud.githubusercontent.com/assets/6933240/14264044/1ff961f4-fb12-11e5-8eb2-b78bb5bb6e2f.png)

panel after clicking mark-all-watched
![image](https://cloud.githubusercontent.com/assets/6933240/14264071/4538c6f8-fb12-11e5-96cb-1320b3fdb2ef.png)
note that the question-mark glyphicon is a spinner.
