### ISSUE TITLE
auto-download using episode.getFormattedEpisode() instead of SceneNameResolver.getSearchStringForEpisode

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#572]
as raised in this [Reddit]()
DazzFX:
>Hello. I'm running the Windows Standalone version of DuckieTV, Oct.9th build, but have had this issue with all previous versions I've used. I've added The Late Show With Stephen Colbert to my favorites, but it will not seem to auto-download. I thought it may be because the torrents don't typically use the same SxxExx naming convention as most series, instead opting for a date. However, if I go to Find A Torrent, it finds the show without issue. I have confirmed auto-download is turned on and I'm using KA as primary search. All of my other series downloads seem to be working without issue. Any thoughts on where I may be going wrong here?

I've looked into this and found that the autoDownload is doing
```javascript
            autoDownload: function(serie, episode, episodeIndex) {
                // Fetch the Scene Name for the series and compile the search string for the episode with the quality requirement.
                var q = SceneNameResolver.getSceneName(serie.TVDB_ID, serie.name) + ' ' + episode.getFormattedEpisode();
                var searchString = q + ' ' + $rootScope.getSetting('torrenting.searchquality');
                console.debug("Auto download!", searchString);
```
the call for episode.getFormattedEpisode() will always return SxxExx.
 it should be using SceneNameResolver.getSearchStringForEpisode so that shows requiring date search strings are catered for.

**Comment by Js41637** [comment]
This is the problem with not having a centralised function that does all this, why do all our different download sections have various parts modifying the query. We should make it just send everything to SceneName and let it do everything and it just returns the query in full.

**Comment by garfield69** [comment]
@Js41637  you are absolutely right!
While in order to restore service asap for this ticket I will just fix the incorrect call, I will raise a new ticket to perform the centralisation of this common search function as you stated.

**Comment by SchizoDuckie** [comment]
@Js41637 
![image](https://cloud.githubusercontent.com/assets/111710/10412783/0e924050-6f91-11e5-81c1-f63f7fc02ed0.png)

**Comment by garfield69** [comment]
When I first looked into this I thought it was going to be a relatively easy replace one call with another fix.
But having spent a day trying to get this working I am in a mental rut and I just don't understand what I am doing wrong.
So I invite someone else to do the fix because I need a break from this before I have a melt down.

**Comment by SchizoDuckie** [comment]
Yeah it's a bit of a maze currently, absolutely true. Please open a new ticket so we can sketch out what needs to be done and how we should go at it.

I'm currently in the middle of moving out of my house so I won't have much time probably, but I'll try to get some of my insights on why it's working as it currently is in there asap

**Comment by garfield69** [comment]
https://github.com/SchizoDuckie/DuckieTV/issues/573 resolves.
