### ISSUE TITLE
can a magnet link via DuckieTorrent client always invoke uTorrent add-new-torrent window?

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#574]
this from [Reddit](https://www.reddit.com/r/duckietv/comments/3ogx0m/suggestionmagnet_link_open_with_utorrent/)
 sitram:
>As soon as I connect uTorrent client trough DuckieTv extension in Chrome, every time I click on a magnet link it automatically adds the torrent to the default download directory. Normally when I click on a magnet link from a website, uTorrent is open and I get a window asking me where to download the torrent, choose a label and priority.
>I like this because it gives me the option to choose the download location and organize my torrents with labels before starting their download.
>Is it possible add an option in the Settings section to switch on/off this behavior?

a little testing with DuckieTV 1.1.3 standalone DEV and uTorrent 3.4.4 with magnets reveals that the first time I click on a magnet link from DuckieTV, uTorrent does pop up a add-new-torrent window:
![image](https://cloud.githubusercontent.com/assets/6933240/10435572/4e2e7560-717d-11e5-8094-fae2ec39c3b8.png)

but subsequent clicking on any other magnet results in the add-new-torrent window being bypassed, and the torrent using defaults settings to add the torrent to the uTorrent tasklist
![image](https://cloud.githubusercontent.com/assets/6933240/10435875/4970337c-717f-11e5-882e-1fd34fed829b.png)

Also, occasionally I get a `$Apply already in progress` which seems to prevent magnets being passed to the torrent client until a restart. Most likely to occur if DuckieTV is already busy doing a fetch-updates-from-trakt.TV as the same time.
![image](https://cloud.githubusercontent.com/assets/6933240/10435774/7ed99c52-717e-11e5-8e8f-f7e0a76c78fa.png)

**Comment by SitramSoft** [comment]
This is exactly the behavior I experienced.

**Comment by SchizoDuckie** [comment]
This is because the first time you launch a magnet, it also launched uTorrent (because that's your default torrent client). The first time, there was no active DuckieTV -> uTorrent connection, therefore your default behavior pops up.

The second time you click a magnet, DuckieTV is already connected and adds the magnet silently via the API.

**Comment by SitramSoft** [comment]
Does the uTorrent API offers a way to trigger the default behavior when adding a new magnet?

**Comment by garfield69** [comment]
that is what this ticket was raised to find out. We will research the API and explore options.

**Comment by SitramSoft** [comment]
Got it! :)

Thanks for clarification.

**Comment by garfield69** [comment]
Research leads me to believe that it does not appear to be possible to invoke the add-a-new-torrent window through the uTorrent API.
While the API can set all the torrent parameters you could wish for, DuckieTV would first have to fetch those parms from the user via its own window template and then use the API to set those torrent parms when doing a torrent addition.
IMO its a lot of work to duplicate a function that already exists.

So instead, what we could do is add an option in the *settings,torrent* sidepanel, which if the user  enables, would tell torrentSearchEngines.js to always launch magnets via the chromium method instead of using the API when connected.

This would effectively always invoke the add-a-new-torrent process, and achieve this ticket's goal.

Unless I get objections, I shall implement this option in the near future.

**Comment by garfield69** [comment]
tested on chrome browser (win7 32bit): discovered that 48.0.2564.116m does not support multi torrent launches via chromium. (only the first generates a popup, rest are lost?)  **Must remember to check 49.+**
In the mean time, enabled launch_via_chromium on standalone only.

tested on standalone (win7 32bit):
- [x] uTorrent API direct
- [x] uTorrent API via chromium
- [x] uTorrent WEBUI direct
- [x] uTorrent WEBUI via chromium
- [x] deluge direct
- [x] deluge via chromium
- [x] vuze direct
- [x] vuze via chromium
- [x] transmission-qt direct
- [x] transmission-qt via chromium
- [x] qBitTorrent 3.2+ direct
- [x] qBitTorrent 3.2+ via chromium
- [x] tixati direct
- [x] tixati via chromium (note: tixati (win7 32bit) does not have a new-torrent popup)
