### ISSUE TITLE
Can we get a global setting to add a string to torrent searches.

### ISSUE THREAD

**Issue by vampyrex13** [SchizoDuckie/DuckieTV#577]
I only download x264 shows. It would make life a ton easier if I could just add x264 to the search string in one place for all my shows in conjunction with the individual settings you already have in the Dev builds.

**Comment by SchizoDuckie** [comment]
We should just make an extra free-text option in the torrent settings where you can now choose between hdtv,720p, etc.

**Comment by garfield69** [comment]
duplicate of #609 which is in currently WIP.
