### ISSUE TITLE
rockaproxy.com is no longer delivering any valid proxies for kat 

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#579]
as part of the testing I was doing for #575, I enabled debugging to view the pages being returned by KATmirrorResolver during the hunt for proxies.
All 50 proxies returned either:
- status 504
- were not kat mirrors but lists to other proxies
- have had their domain names released and are for sale: refer [https://torrentfreak.com/thousands-of-torrent-site-proxies-disappear-151013/](https://torrentfreak.com/thousands-of-torrent-site-proxies-disappear-151013/)

we may need to look for a replacement proxie provider if this service does not update its list with valid proxies any time soon.

**Comment by garfield69** [comment]
update: rockaproxy.com is nbg returning 'Tango Down! it was fun while it lasted :)' so replacement is required.

**Comment by KsaRedFx** [comment]
https://kastatus.com/ lists valid proxies.

**Comment by SchizoDuckie** [comment]
yeah but those are most likely blocked on national blocklists. the thing i
liked about rockaproxy was that it had multiple mirrors.

we can just remove this implementation for now and convert it to manually
entering a proxy i guess.
