### ISSUE TITLE
add support for Norwegian language

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#581]
check list:
- [x] merge pull #580
- [x] cross check and add/delete keys to bring it up to date
- [x] create locales/angular-locale_nb_no.js
- [x] create locales/nb/messages.json
- [x] update language list js\app.translate.js
- [x] update language controller js\controllers\settings\LanguageCtrl.js
- [x] update css/flags.css
- [x] add the SETTINGS/DISPLAY/locale/nb_no key in all the language files
- [x] update changelog
- [x] update credits list on about page 
- [x] update credits list wiki

**Comment by Js41637** [comment]
Did you update the gh-pages as well?

**Comment by garfield69** [comment]
nope. Decided not to update the gh-pages until **after** 1.1.3 is pushed out.

**Comment by Js41637** [comment]
Fair enuf.
