### ISSUE TITLE
Trakt bidirection sync mark watched 

### ISSUE THREAD

**Issue by fadeldamen** [SchizoDuckie/DuckieTV#583]
If mark in site trakt.tv some episode with watched not represent in duckietv without resync all series in trakt.tv with trakt.tv import button.

**Comment by Js41637** [comment]
Yes DuckieTV currently only supports 1-Way Trakt sync for the time being. We might add Two-Way syncing in the future but for the time being Two-Way syncing can cause a lot of problems and will require a lot of work to implement.
