### ISSUE TITLE
First time use, connect to trakt.tv

### ISSUE THREAD

**Issue by miglrodri** [SchizoDuckie/DuckieTV#584]
First time use, i clicked on the alert on the first page and the alert colapsed to backwards of all the show titles and media.

Try to replicate it.

Regards

**Comment by Js41637** [comment]
I'm sorry I don't quite understand.

**Comment by miglrodri** [comment]
http://pasteboard.co/1tSCJeS3.png

**Comment by Js41637** [comment]
Ahh yeah, that bug has already been fixed and will be in the next version.

**Comment by miglrodri** [comment]
another issue, that it's no quite an issue.

but if i have zero favorites, if i go to favorites i have the text "your favorite series. click one to view details".

well, there's none to click to view details, so i was expecting to go to some kind of populate my favorites, like the "homepage".

regards

**Comment by Js41637** [comment]
DuckieTV will automatically go to the Adding Menu if you have no series on start up however, if you navigate away from the page and go back to it, you will need to click 'Add a show'. Perhaps it should do this automatically but we'll see.
