### ISSUE TITLE
If i click the calendar, the item disappear

### ISSUE THREAD

**Issue by miglrodri** [SchizoDuckie/DuckieTV#585]
i launch duckie, and then click on calendar

the icon disappear, dont know if its normal behavior

http://pasteboard.co/1tSNjTPW.png

regards

**Comment by Js41637** [comment]
Yes it's meant to be because you can't go to the calendar again once you're already on it.

**Comment by miglrodri** [comment]
ok, i was expecting something like the behavior of the other menu items, like settings or info. (you click, they become highlighted)

on issue i run into, dont know if you can replicate.

if you click on favorites, and click back on favorites to hide it. you go to calendar page, and in that case youre in calendar page but the calendar item on menu is present.

**Comment by miglrodri** [comment]
i think its a bug, because if i go to that scenario, and be at calendar page, the duck menu item does not work.

**Comment by Js41637** [comment]
Navigating from the favourites to the calendar and it not updating the buttons was a bug but it has also already been fixed. 
The duck icon button is also the same as the calendar button with the except that if you change the current month view, say you changed it to September, it will reset it back to the current date.
