### ISSUE TITLE
Export / Import database

### ISSUE THREAD

**Issue by Awea** [SchizoDuckie/DuckieTV#587]
Hey there I'm using DuckieTV but I doesn't find anything in the issues about the the database location. Any solution to export / import on the stand alone version ?

**Comment by SchizoDuckie** [comment]
Check out the settings screen under backup/import :)

**Comment by Awea** [comment]
Rofl, my eyes... @SchizoDuckie thanks :D

![capture du 2015-10-29 08 48 33](https://cloud.githubusercontent.com/assets/630023/10812789/f7994dca-7e19-11e5-9b11-d42540d94af2.png)

**Comment by SchizoDuckie** [comment]
You're welcome :)
