### ISSUE TITLE
Run DuckieTV as a service

### ISSUE THREAD

**Issue by 51appy** [SchizoDuckie/DuckieTV#589]
I really like DuckieTV, but my kids keep closing it by mistake.  Is there any way to run DuckieTV  as a windows service, or run it on my linux plex server and just connect to it from the windows box (the Wife does not use linux). I am not sure what is the best way but I was thinking of a Client app and Server service.  Then everyone could choose to run the DuckieTV server on the same computer or on media server.  this will allow them to login to DuckieTV  from any computer in the house.

**Comment by Js41637** [comment]
Are you talking about Standalone? It could be made to minimize to tray on close but Chrome Apps will run in the background if the option is enabled in chrome (by default it is)

**Comment by 51appy** [comment]
I am using the standalone app. I will look at the Chrome App.

**Comment by garfield69** [comment]
@51appy, you are not going to find DuckieTV as a Chrome **App**, that flavour does not exist. For Chrome browsers DuckieTV comes a Chrome **Extension**, which is different.

While we could fairly easily make DuckieTV Standalone's close button optionally minimize to systray, I'll leave the decision to go ahead and add yet another option in settings to @SchizoDuckie.

As to whether or not DuckieTV will ever be available as a Chrome App, schizoduckie may choose to comment on.

**Comment by SchizoDuckie** [comment]
May I suggest a simpler solution?

http://windows.microsoft.com/en-au/windows/schedule-task#1TC=windows-7

Just schedule a task.
It won't run a task again if it's already running, so you could just schedule DuckieTV.exe to run every hour.

**Comment by garfield69** [comment]
Nice one :+1:

**Comment by 51appy** [comment]
my mistake.  I just installed the extension.  works good but the calendar is not loading the shows like the standalone version.  even with the extension working I think a server/client would be great.

Thanks for your help

**Comment by Js41637** [comment]
With regards to the taskbar/closing thing. I say we make it simpler and just have 1 setting. Have an option to make the close button exit the app of close to the tray. And the minimize button can just remain it's default behaviour of minimizing to the taskbar.

**Comment by 51appy** [comment]
that would work.  making it like uTorrent where you have to select exit from the menu or right click on task bar.

I still think the server/client would work best but I understand this stuff does not write itself.
Thanks for a great program.

**Comment by Js41637** [comment]
I mean DuckieTV could theoretically run like a gui-less service if all you want is just the auto-downloading stuff but I think there is better alternatives that are more designed for that. DuckieTV at the moment, I don't think, is reliable enough to properly operate on it's own.

**Comment by SchizoDuckie** [comment]
How do you mean that?
Op 30 okt. 2015 14:37 schreef "Js41637 ftw" <notifications@github.com>:

**Comment by Js41637** [comment]
Theoretically as in it's already mostly automatic, with a few adjustments it could just run by itself when its setup and have it auto-download and schtuff.

**Comment by jriker1** [comment]
This ever get any traction?  Stupid question but even though a service would be preferable, with a client that connects to it or web gui, why can't we have this thing auto start on login or something like uTorrent has?

**Comment by Js41637** [comment]
It's a neat idea but it's just not what DuckieTV was designed for, DuckieTV is no longer in active development, the only things getting worked on being bug fixes and new search engines/torrent clients. I doubt anyone will be willing to work on this.

**Comment by jriker1** [comment]
Thanks for the reply.  Guess I'll add it to my scheduled tasks, but don't think development has stopped. Just talked with the dev on some issues and it clearly sounds like they are enhancing things.

**Comment by Js41637** [comment]
> the only things getting worked on being bug fixes and new search engines/torrent clients.

**Comment by garfield69** [comment]
I'm still occasionally working on the multi-SE for ADS, but its not going to be ready for a long while yet.

**Comment by garfield69** [comment]
the bug fixes and question/help-me are taking up most of my free time currently.
