### ISSUE TITLE
Documentation Update (4+1 Model)

### ISSUE THREAD

**Issue by RevTut** [SchizoDuckie/DuckieTV#591]
Hey Schizo!

We have made some updates on documentation of DuckieTV!
This week is all about the 4+1 software architecture model :)
You may find it here https://github.com/Nutil/DuckieTV/blob/documentation/ESOF-docs/Design%20Architecture.md

Regards,

**Comment by SchizoDuckie** [comment]
Super cool guys!

Some minor notes:

- The api is called Trakt.tv,  not Tracktv
- In one of the UML dialogs you have a direct line from adding a show to
torrent, the graph doesn't reflect the fact that the torrents are a bolt-on
system that's optional to use (a very real use case is to ignore all the
torrent functionality and use DuckieTV purely as a show calendar :) )
Op 10 nov. 2015 18:19 schreef "João Silva" <notifications@github.com>:

**Comment by Nutil** [comment]
Alright, thanks for the corrections! 
We're currently under alot of pressure from other classes, but as soon as we get a break, we'll correct the diagrams :)
