### ISSUE TITLE
hide uTorrent API feature on non-windows platforms

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#592]
from this [Reddit](https://www.reddit.com/r/duckietv/comments/3cm6dj/announcement_duckietv_v112_for_chrome_linux/) the following

rwgordon:
>Running DuckieTV on my Mac, says it needs uTorrent for Windows and fails to sync to uTorrent for Mac?

garfield69:
>uTorrent for windows supports a direct API which allows DuckieTV on windows to connect to that client interface directly. Unfortunately, uTorrent for Mac does not support that interface.

rwgordon:
>I assumed Duckie for Mac could just not reference uTorrent for Windows. Seems like common sense. 

Should we hide the uTorrent API feature on non-windows platforms, given it only works for uTorrent on windows ?

**Comment by garfield69** [comment]
using something like
```javascript
if (navigator.platform.toLowerCase().indexOf('win') !== -1) {
// set utorrent api feature available to true
} else {
// set to false
};
```
perhaps?

**Comment by Js41637** [comment]
Seems like most problems here are caused by Macs
