### ISSUE TITLE
DuckieTV only searching my preferred torrent search provider

### ISSUE THREAD

**Issue by 51appy** [SchizoDuckie/DuckieTV#595]
If I select Kat as default but no torrents are found for my show Duckie won't download anything, But if I look at RARBG on Duckie I find it no problem.  So the only thing I can figure out is Duckie is not auto-switching to other search providers when the show is not found in the default.  This is something I have noticed with the last two versions of Duckie.  So I don't know if it is just because I am totally dafted or what.

Please help!

Windows 7 SP1
DuckieTV Standalone 1.1.2

**Comment by Js41637** [comment]
DuckieTV currently doesn't search other providers if no results are returned.
