### ISSUE TITLE
Statistics Panel

### ISSUE THREAD

**Issue by debdyuti9** [SchizoDuckie/DuckieTV#596]
![screenshot_2015-11-21-01-57-47_com battlelancer seriesguide](https://cloud.githubusercontent.com/assets/15952641/11316936/af276e08-9040-11e5-9a92-f77c6bf39fcf.png)

Hello,
First of all thanks for creating such a wonderful app. Its too good and the auto torrent download feature is awesome. I'm in love with this app. I just have 1 suggestion. Can you add a statistics panel to see how many time I spent by watching all of the episodes (Like the Screenshot, It is taken from an android app "Series Guide") . That'd be cool. 
Thanks

**Comment by RevTut** [comment]
Hi!

We are going to try and do it by the end of the next week!
Stay tuned ;)
