### ISSUE TITLE
linux standalone window does not minimize properly

### ISSUE THREAD

**Issue by crash369** [SchizoDuckie/DuckieTV#597]
Similar to issue mentioned in #569 on macs, multiple systrays are appearing for me in standalone linux (Mint) in Duckie 1.1.2.

Opening and closing the window from systray occasionally spawns a new duckie icon.  I have not been abble to determine the exact sequence of events to cause a new spawn.

![duckie_systray](https://cloud.githubusercontent.com/assets/15957402/11319172/cc179e5e-902a-11e5-9ed9-520f043e210e.png)

On an unrelated note, I just noticed in the screen grab that the tool-tip for systray says Duckie 1.1.0, when I am (theoretically) running 1.1.2.

**Comment by crash369** [comment]
Just tried the nightly from 12/10.  I think there may be a regression.  There is now no tray icon created when minimizing.  The tray icon shows up only if "always show tray icon" is checked in settings.

**Comment by garfield69** [comment]
Have you tried the 'minimize button minimizes DuckieTV  to tray' check box ?

Turn off the 'always show tray icon' check box.

Let us know what happens, thanks.

 

  _____

**Comment by crash369** [comment]
Yes.  Windows disappears.  No tray icon.  Duckie continues running.

**Comment by garfield69** [comment]
OK. Would you upload a screenshot of your duckietv/setting/ window page?

And also duckietv/about page (may take several screenshots to cover it all).

Thanks a bunch.

 

  _____

**Comment by crash369** [comment]
Tested again.  Minimize hides window; no systray; and processes keep running

![screenshot from 2015-12-10 18 59 39](https://cloud.githubusercontent.com/assets/15957402/11734107/1d0ee542-9f71-11e5-90f4-7184af7e77f6.png)
![screenshot from 2015-12-10 19 02 12](https://cloud.githubusercontent.com/assets/15957402/11734108/1d1e23cc-9f71-11e5-8eaf-8588f9793ea1.png)

**Comment by garfield69** [comment]
@crash369  thank you for the captures. I'll take a closer look at the code and see what's what.

**Comment by garfield69** [comment]
@SchizoDuckie  it makes no sense.
I'm using nightly 20151210 (win32) with the same settings as crash369 using linux 20151210, yet I get the systray and he does not.
![image](https://cloud.githubusercontent.com/assets/6933240/11735484/83f5480e-a026-11e5-8131-eb12366f69ad.png)
![image](https://cloud.githubusercontent.com/assets/6933240/11735462/63e6cf10-a026-11e5-80b7-31cd07cf3799.png)

is there something iffy going on with the linux build?

**Comment by Js41637** [comment]
No, node-webkit just runs horribly on Mac and Linux, or mac and linux just have archaic tray management systems. Either way. Looks like it would just be easier to disable these newer options for Mac and Linux as fixing these bugs seem impossible.

**Comment by SchizoDuckie** [comment]
Erm... my tray in Linux worked perfectly on release. Mac is botcing. Please
dont make statements like that.
Op 11 dec. 2015 05:52 schreef "Js41637 ftw" <notifications@github.com>:

**Comment by Js41637** [comment]
Yeah but they're likes how many different versions of linux and mac.

**Comment by garfield69** [comment]
back to the problem at hand.
the point is that crash369 said that if he turns on the 'always show tray icon' he does get the systray. but if it is no checked, the systray does not appear even when the 'minimize to systray' check box is enabled.
I've compared the localStorage settings, and tested the exact settings on my win32.
To me that suggests that the linux x64 build is not using the same angular source code that I am using.
So I thought it prudent to first ask if the linux build were still correctly including the latest angular source code.
One way to confirm this would be to add a console.log to the systray.js and see in the next nightly for linux issues that to the console.

**Comment by Js41637** [comment]
He is properly restarting the app right? always show icon requires a full restart

**Comment by crash369** [comment]
He is. That's how he knows that the tray icon CAN show up, but only with "always show".

**Comment by garfield69** [comment]
@crash369  Firstly, thank you for your help in trying to get to the bottom of this little mystery.

when you have the time, I would like you to perform a test on your Linux for me using the 
nightly release build for 13-10-2015, once it is available.

Startup DuckieTV standalone, press the F12 key to open the development tools page, click on the console tab, then click on the filter icon and the debug button.
This will isolate the logs to just debug messages, which makes screen captures are little useful for this test. (see the picture below, I've circled in red the filter icon and debug button that appears once the filter is active).

Perform your minimize to systray, then upload a screen capture of the debug log.
Here is what it should look like if it is performing as expected:
![image](https://cloud.githubusercontent.com/assets/6933240/11753482/308773fc-a0aa-11e5-92ca-3b24f413382c.png)
the log above shows me minimizing to systray, then restoring to full screen again on my development standalone win32 duckietv.
Cheers.

**Comment by crash369** [comment]
Sorry for the delay.  This is from the Dec14 nightly.

Log looks the same; no tray icon; duckie running.

![screen](https://cloud.githubusercontent.com/assets/15957402/11798751/d71d8986-a28a-11e5-93ba-548ece3a89aa.png)

**Comment by garfield69** [comment]
OK, well that's good, we have eliminated the theory that the linux builds were not picking up the latest source code ( I never had any doubts Schizoduckie ;-b ).

@crash369  Um, just curious, how are you able to access the restore when you don't have a systray icon to click on, or to select the Show DuckieTV menu item?

**Comment by garfield69** [comment]
@crash369  can you set the 'always show tray icon', restart DuckieTV and then perform the same sequence above and show us the same screen capture you gave us please?
Give us a contrasting successful run on your linux to compare. Thanks.

**Comment by crash369** [comment]
Same nightly, started with "always show" yesterday.  Also, of note, there are now 2 duckies in systray (started with one yesterday)

![screen](https://cloud.githubusercontent.com/assets/15957402/11832084/0342bb84-a372-11e5-8e0f-00643957279f.png)

**Comment by garfield69** [comment]
@crash369  Yeah, if you leave your standalone active overnight, you'll find an additional systray in the morning. Its a know bug we have yet to code a solution for.
Would really like to see a snapshot of the systray. And also an answer to my previous question during the Always-show-tray=No, Minimize-to-tray=Yes test:
> how are you able to access the restore when you don't have a systray icon to click on, or to select the Show DuckieTV menu item?

Thanks.

**Comment by crash369** [comment]
Screen of console with always-show-tray enabled.  To answer your previous question, I can't restore duckie without the tray icon.  I have to kill the process.

![screenshot from 2015-12-19 09 46 53](https://cloud.githubusercontent.com/assets/15957402/11914177/cabadbfe-a635-11e5-905c-bd8316fac0ff.png)

**Comment by garfield69** [comment]
@crash369  OK, I think I have an found something.
you recall the first test you did, which was to minimize to systray, without using the 'always show tray' option.
you loaded this screenshot:
![screen](https://cloud.githubusercontent.com/assets/15957402/11798751/d71d8986-a28a-11e5-93ba-548ece3a89aa.png)
and reported that this test resulted in the systray not appearing.

The reason I asked you about how you could restore in this situation is because the log shows a restore was performed (see the last two lines of the log).
But if you dont get the systray, and you have to kill the process, then how did those two lines in the log come about ?

If somehow the restore code is being invoked but the main page is not being displayed, that would explain why the systray disappears.


What I would like you to do, is to please test minimizing to systray while the console is open, and confirm that the logs show a restore being performed but that you dont get a maximized screen.
Cheers.

**Comment by crash369** [comment]
confirmed - no systray, no window, "on restore, on restore: tray removed" in log

**Comment by garfield69** [comment]
Ahh. now we are getting some place. OK, thanks. I need to think about this and do some research.

**Comment by garfield69** [comment]
I have installed Ubuntu 15.10 on a spare HDD and installed linux nwjs 0.12.3 along with the latest DuckieTV development code. Yay!

So I have independently confirmed that on linux, when I minimize the standalone DuckieTV, the 'restore' event is triggered by something as yet undetermined, causing the just minimized window to be restored immediately!

This does not occur on my win7 DuckieTV standalone using the same js development code.

bah!

**Comment by crash369** [comment]
Very odd.  If it helps, this never happened in the last stable release, so it's been introduced since then. :)

**Comment by garfield69** [comment]
@crash369  at your convenience,  please download the next nightly build 01-15-2016 when it becomes available tomorrow, and test that the minimize and restore are working your flavour or linux.

If it is not working then please load a screen capture of the log to show the debug traces.

And if it is working, let me know so I can clean up the debugs and close the ticket.

Thanks.

**Comment by garfield69** [comment]
rename this ticket to reflect work on the minimize/restore for linux.

the multy-systray issue is within ticket #569  which affects both mac and linux.

**Comment by crash369** [comment]
1/17 Nightly seems to be working.

**Comment by garfield69** [comment]
\o/

**Comment by crash369** [comment]
\o/ :)
