### ISSUE TITLE
Starting / running DuckieTV turns on secondary gpu?

### ISSUE THREAD

**Issue by shadycady** [SchizoDuckie/DuckieTV#599]
I have a multiple gpu setup and when duckietv starts it turns on my secondary gpu, as soon as I quit duckietv the second gpu goes back into power save mode.  

Any insight is greatly appreciated

**Comment by SchizoDuckie** [comment]
Oh lord, you people with your funky setups.

I heard something about another dev fiddling with this and finding a seemingly completely unrelated solution. I'll get back to you!

**Comment by shadycady** [comment]
were you able to find any insight or the unrelated solution?

funky setup? its a 295x2 two gpu one card, picked it up for $145... why not ;-)

**Comment by SchizoDuckie** [comment]
Sorry, I don't really have any solution to this. You can try to hack it yourself by disabling gpu usage and fiddling with nw.js/chromium startup flags inside package.json yourself, but I don't knwo if you re up for that
