### ISSUE TITLE
Watch statistics

### ISSUE THREAD

**Issue by luisrpfigueiredo** [SchizoDuckie/DuckieTV#601]
Hey again,

We thought we'd implement a feature to allow the user to get statistics regarding how much time they've spent watching series at duckieTV, how many series they've watched, etc....

It's something really simple. We already created the queries, but we can't seem to be able to compile DuckieTV :( we've really tried everything we know.

Could you please try and compile our branch "statistics" and see if the raw output of the query is working? We assume they work because we tested them outside of the code, but you can never be too sure.

Regards,

**Comment by SchizoDuckie** [comment]
Hey guys i'll check it out somewhere this weekend

for easy development I really suggest you guys just use the 'chrome extension' method!

- go to chrome://extensions
- enable 'developer mode'
- click 'load unpacked extension'
- point it to a DuckieTV git directory
- profit!

now open a new tab, and you'll see DuckieTV.
If you want the browser action mode you'll have to rename manifest-app.json to manifest.json, that'll give you a DuckieTV button in Chrome.

For developing on nw.js, just download a nw.js v0.12.* version and extract into the DuckieTV root, then run NW.js. Don't worry about the compilation process!

**Comment by Nutil** [comment]
Alright, cool :)

We've managed to create a new panel on the menu and opened a panel to the right side (just like the about panel) but we're having issues calling the queries to print them out :( It really is the last part we're missing.

**Comment by SchizoDuckie** [comment]
As the sql part is all promise based, make sure you return stuff in the
.then () so that the next block of code can handle it. Please link to
specific code you have problems with because i see loads of commits :)
Op 9 dec. 2015 11:52 schreef "Nutil" <notifications@github.com>:

**Comment by Nutil** [comment]
https://github.com/Nutil/DuckieTV/commit/b671a3654166bcf0a8e797e37dd047544a8d1cb3

This is the last version we're trying to work with. The statistic.html is where we're printing the query results and the statisticCtrl.js file is where we define the queries. We're having trouble following the call order to reach these functions.

**Comment by Nutil** [comment]
Oh, we managed to call the function :D https://github.com/Nutil/DuckieTV/commit/0a48d0f592f96be19049cc6af13e0dff1140f61b

the console.log is showing up.

**Comment by SchizoDuckie** [comment]
Good work :) 

https://github.com/SchizoDuckie/DuckieTV/blob/angular/js/controllers/sidepanel/SidepanelSerieCtrl.js 

Maybe the stats calc from here will help you as well.

**Comment by Nutil** [comment]
We figured out that chrome doesn't access the correct database. How do we access the database that is running when we're using the chrome extension? Other than that, everything is working :)

**Comment by SchizoDuckie** [comment]
How do you mean "the correct database"? Are you trying to access the
duckietv standalone db from a chrome extension?  (This is impossible)
Op 9 dec. 2015 12:32 schreef "Nutil" <notifications@github.com>:

**Comment by jpedroteles** [comment]
We know that but we are having a problem with our queries on chrome. They work because we already tested them, but on chrome when we call them they return 0.

**Comment by Nutil** [comment]
If that is impossible, then the feature is complete :) It should work for the standalone version, but it wouldn't be bad to manually test it.

What are your opinions on it? We'd love it if the feature would be added to the core app.
