### ISSUE TITLE
Wrong epidosde auto-download

### ISSUE THREAD

**Issue by crash369** [SchizoDuckie/DuckieTV#602]
Standalone Duckie 1.1.2 (on linux)

Duckie consistently downloads the previous episode.

Example: The Knick for Dec 4, 2015.  When hovering over show name in calendar displays the correct episode (S02E08).  However, the episode fetched is S02E07.  This happens fairly consistently.

When manually using "Find A Torrent", the list of results is for the correct episode.

**Comment by SchizoDuckie** [comment]
Can you try downloading a nightly version and see if the problem persists? This could be an issue with one of the search engines trying to be smart and including the wrong episodes in the search results, for which whe have implemented fixes
