### ISSUE TITLE
Keeps downloading wrong episode

### ISSUE THREAD

**Issue by SushiLover** [SchizoDuckie/DuckieTV#604]
I have an issue where DuckieTV keeps downloading the wrong episodes for a lot of the shows I have on the schedule. An example is overnight it downloaded Rent a Cop S01E04 instead of E07. It also downloaded Fast N' Loud S06E06 instead of E07 and Chopped S26E06 instead of E07 (which doesn't even seem to have a torrent out yet). The same torrents it downloaded were already marked as such, why would it grab them again?

**Comment by garfield69** [comment]
@SushiLover  which platform and version of DuckieTV are you using please?
examples: chrome extension newtab or browseraction 1.1.3, 
standalone 1.1.3 for win-ia32, linux-ia32, osx-ia32, win-x64, linux-x64, osx-x64, android.
or a nightly version 12-10-2015 for one of the above platforms.

You can find the version on the DuckieTV about page [ the (i) icon on the bottom left of the main duckieTV page ], even better, upload a screen-capture of that page here (Print screen key, followed by ctrl-v in an empty box below).

Thanks.

**Comment by SushiLover** [comment]
I'm using DuckieTV Standalone v1.1.0; didn't know there was a v1.1.3. Guess I should update?

**Comment by garfield69** [comment]
Absolutely :-)

1.1.3 contains fixes that should take care of the problem you reported.

 

  _____

**Comment by SushiLover** [comment]
Downloaded and installed; we shall see what happens : )

Thanks for the prompt replies!
