### ISSUE TITLE
Can't mark all torrents as downloaded if they're not available yet

### ISSUE THREAD

**Issue by SushiLover** [SchizoDuckie/DuckieTV#607]
Sometimes a series, like Flesh & Bone, has all of it's episodes aired at once. I download all 8 episodes about 2 weeks ago, but DuckieTV only sees the first 6 as available. so I can't mark them all as downloaded. When that happens DuckieTV continues to download the new torrents once they're available (like it did yesterday with E06). Is there a better way to handle this other than unchecking auto-download for this series? I'd like to see a way to truly mark all of the episodes as downloaded, and if some torrents aren't available yet maybe DuckieTV can display a confirmation prompt.

**Comment by Js41637** [comment]
This isn't DuckieTV's fault but the tracker we use is indicting that the shows air every week and not that it has all aired at once Maybe it only aired them all in a certain area? Either way, this isn't something we can fix however I believe you can mark an episode as 'leaked' which will allow you to mark it as watched. When selecting an episode you can 'Click here if the episode has leaked online...'. This might be able to fix your problem.

**Comment by SushiLover** [comment]
Thanks, I didn't see that option until you pointed it out. I've marked the remaining ones as downloaded and reset the series to auto for next season.
