### ISSUE TITLE
Autodownload Include keywords

### ISSUE THREAD

**Issue by bionikspoon** [SchizoDuckie/DuckieTV#609]
Ref #548 (Autodownload Exclude keywords)

I want to mirror this sentiment for include keywords.

A case from personal preference: I'd like autodownload to only download from reputable vendors, like rarbg or ettv (and a few others) in my preferred resolution 720p. Or 1080p if it's available.

**Comment by rarbg** [comment]
Why dont you just switch to the rarbg API within DuckieTV ?
