### ISSUE TITLE
Latest version constantly hangs or becomes unresponsive

### ISSUE THREAD

**Issue by SushiLover** [SchizoDuckie/DuckieTV#610]
Since updating to the latest standalone Windows version, I find DuckieTV constantly becomes unresponsive. Not sure what kind of info you need, but what happens is that DuckieTV won't respond to mouse clicks when I try to click a show on the calendar or it won't display the GUI when I try to restore from being minimized. The only solution is to launch Task Manager and kill the application, then relaunch it. Please let me know what else I can provide to help diagnose the issue.

**Comment by garfield69** [comment]
Please start by providing a screen capture of the DuckieTV statistics section, which you will find near the bottom of the DuckieTV About page. Accessed via the (i) icon on the bottom left of the main DuckieTV page.
Use the Print Screen key, and ctrl-v straight into an empty box below.

This will give us the basics version, platform and other details.

I use the win32 standalone DEV version on a daily basis , and never come across this so far...wonder whats going on with yours.
Thanks.

**Comment by SushiLover** [comment]
Thanks, how far down should I copy?

**Comment by garfield69** [comment]
from the statistics header down to the opt-in header.

The next time you get this issue, take a look at the task manager and look to see if DuckieTV is consuming excessive CPU or IO.
Also useful is a screen capture of the console log. Assuming it responds to pressing of the F12 key to open the development tools page, click on the console tab, and Print Screen away the console log.

Also useful are details you remember about what you were doing with DuckieTV before it stopped responding. At this stage we're just trying to get an overview of activity. Once I take a look at the stats I may have additional questions regarding settings and options that are enabled/disabled.
Cheers.

**Comment by SushiLover** [comment]
I think the issue might be in the minimize behavior. I didn't realize it, but mine was set to start minimized. When it was set to that, Duckie would launch but in an "invisible" window (I could see the icon in the taskbar but Firefox was still visible on the screen). If I hovered over the icon Aero Peek showed just a blank mini-window named Duckie. If I then clicked the icon in the tool tray, Duckie would open it's window correctly. I think at some point Duckie forgets that it's already running, as when I would leave it open but then change to another program and go back to Duckie, it would again open but in the "invisible" window. I since changed the startup to run normalized and it hasn't acted up since then. I hope that all made sense!

**Comment by garfield69** [comment]
OK. FYI: Standalone DuckieTV uses an internal chromium browser to display the calendar and other DuckieTV pages.
It does not have any dependencies on your default system's browser for generating DuckieTV windows.

The exception is when you navigate to links to wiki, IMDB, or RottenTomatoes from within the standalone. These links are sent to your default browser for viewing.

So we can close this ticket then?

**Comment by SushiLover** [comment]
You don't consider this a bug? I only mentioned Firefox because that just happened to be what was on the screen when I tried to switch back to Duckie.

**Comment by garfield69** [comment]
The default to minimize the standalone at start-up for 1.1.3 was a coding
logic error that was fixed with commit
https://github.com/SchizoDuckie/DuckieTV/commit/f6fa6d673802970d0f2b6b6166df
c26c32c2b503, and will be included in the next release of DuckieTV. :-)

 

  _____

**Comment by SushiLover** [comment]
Okay, I'll close this and see how things work when the next release is out.
