### ISSUE TITLE
switching to mixed case instead of all upper case words

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#612]
as raised in this [Reddit ](https://www.reddit.com/r/duckietv/comments/3y5hsq/duckietv_font_case/)

> Great app - Thanks! I use DTV from about four meters away. Upper case fonts are difficult to read from that distance compared to lower case fonts. If you are uncertain about this then you might like to go to Google maps and ride along a freeway until you get to a sign. You will see that lower case fonts are used as they can more easily be seen from far away. I think DTV would benefit from a greater use of lower case fonts. Thank you for your considering this request to review this issue!

**Comment by Js41637** [comment]
I dunno about this, it would require a different font in most cases as Bebas is only capitals and then to have to make a setting to change capitalization (which can be easily done with css) we'd also have to change bebas font. Can be done though.

**Comment by garfield69** [comment]
Assuming that we want to provide the user the option to switch between bebasregular and helvetica, rather than just ditch bebasregular altogether, I've been exploring ways to globally set the font-family with the least template coding effort and the least cpu cost / best performance.    

So currently the main.css has `  font-family: 'bebasregular';` for *h1,h2,h3*, *strong*, *inline checkbox label*, *sidepanel .buttons .torrent-mini-remote-control*, *.settings .buttons .btn*. 

Would swapping the entire main.css stylesheet for an alternate that does not have the bebasregular font-face using something like:

tab.html
```javascript
[...]
  <link id="mainStyleSheet" rel="stylesheet" href="css/main.css">
[...]
```
app.js
```javascript
[...]
.run(['SettingsService', function(SettingsService) {
    function init() {
        document.getElementById("mainStyleSheet").setAttribute("href", SettingsService.get('mainstylesheet'));
    }
    window.onload = init;
}])
[...]
```
settings.js
```javascript
[...]
            defaults: {
[...]
                'mainstylesheet': 'css/main_2.css',
[...]
```
 
is there a better way?

**Comment by garfield69** [comment]
or maybe just insert a sheetstyle *main_2.css* at the bottom of the document.head, overriding the elements of *main.css* that have a font-face of bebasregular:    

css/main_2.css
```javascript
h1, h2, h3 {
  font-family: helvetica, sans-serif;
}

strong {
  font-family:helvetica;
  letter-spacing: normal;
  font-weight: bold;
}

.inline-checkbox label {
  width: calc(100% - 45px);
  font-family: helvetica, sans-serif;
  font-size: 30px;
  font-weight: normal;
  padding-left: 45px;
  line-height: normal;
}

sidepanel .buttons .torrent-mini-remote-control> span {
  /* Replicate of the strong tag */
  font-size: 18px;
  letter-spacing: normal;
  font-weight: normal;
  color: white;
  font-family: helvetica;
  display: block;
  margin-bottom: 4px;
}

.settings .buttons .btn {
  font-family: helvetica;
  font-size: 18px;
  font-weight: normal;
}

sidepanel .buttons strong {
  font-size: 18px;
  letter-spacing: normal;
  font-weight: normal;
  color: white;
}
```
app.js
```javascript
[...]
.run(['SettingsService', function(SettingsService) {
    if (SettingsService.get('displaymixedcase')) {
        function init() {
            //document.getElementById("mainStyleSheet").setAttribute("href", SettingsService.get('mainstylesheet'));
            var x = document.createElement("link");
            var y= document.createAttribute("rel");
            y.value = "stylesheet";
            x.setAttributeNode(y);
            var z = document.createAttribute("href");
            z.value = "css/main_2.css";
            x.setAttributeNode(z);
            document.head.appendChild(x);
        }
        window.onload = init;
    }
}])
[...]
```
SettingsService.js
```javascript
[...]
            defaults: {
[...]
                'displaymixedcase': true,
[...]
```

**Comment by garfield69** [comment]
@SchizoDuckie  my implementation of this mixed-case font feature, by providing a css main_2 stylesheet that gets dynamically added to the tab.html if enabled, does not work for standalone packages currently, because the buildbot does not include such a file.     
Can you review the way I've implemented this ticket, and if you determine that this is the correct (only?) way to implement this feature, would you then please amend the buildbot scripts to include the css/main_2.css file to the build? Thanks.

**Comment by SchizoDuckie** [comment]
Meh. I'm not really a fan of the whole idea of adding a complete extra setting and stylesheet and assets for one very specific edge use case. DuckieTV is not a billboard, it's a calendar app. How many calendars do you use from 4 meters away?

**Comment by Js41637** [comment]
i do and i find this offensive
