### ISSUE TITLE
Auto download mode downloads previous episodes

### ISSUE THREAD

**Issue by elvisP** [SchizoDuckie/DuckieTV#614]
When an episode of a tv show is automatically downloaded, DuckieTV always downloads the previous episode.
For instance: The calendar tells me that Supergirl S01E09 will be downloaded on January 1st, but on that date Supergirl S01E08 is dowloaded.
This happens with every show, every time, so I have to download the correct episode manually.

Hope this helps

Marc

**Comment by garfield69** [comment]
What version of DuckieTV are you on?
you can find this info in the *about* page by clicking the **(i)** icon on the bottom left of the main DuckieTV page.
In fact, it would be very helpful if you could screen dump the whole **statistics** section which you can find near the bottom of the DuckieTV *about* page.... use the **Print Screen** key and then **ctrl v** into an empty box below. Cheers.

**Comment by elvisP** [comment]
Hi,

I’m on a Mac, I don’t have a print screen option
But I managed to take a picture of the stats screen
As you can see, I have version 1.1.2

Marc

**Comment by garfield69** [comment]
Excellent. You don't appear to have managed to paste a copy of your picture here but never mind.

You might like to upgrade to 1.1.3 which contains fixes that will resolve the issue you have raised :-)
Grab the latest mac standalone version [here](http://schizoduckie.github.io/DuckieTV/) or [here](https://github.com/SchizoDuckie/DuckieTV/releases)

**Comment by elvisP** [comment]
Tnx,

I just did.
The picture link is now in the entry
Let you know if the problem is solved

Marc
