### ISSUE TITLE
Windows standalone version does not maximize correctly on multiple screens

### ISSUE THREAD

**Issue by Sunabubus** [SchizoDuckie/DuckieTV#615]
When I click on maximize window, part of the window goes through to the other monitor's screen. It's a narrow grey line. (I have 2 different size screens.)

**Comment by Js41637** [comment]
It's highly unlikely this is a DuckieTV issue, likely an issue with Node-webkit which is out of our control. 

I have a different node-webkit app that doesn't experience this issue, it maximizes correctly with dual screens on Windows 10, x64. What OS are you running?

**Comment by Sunabubus** [comment]
Win10 x64.
http://i.imgur.com/bGa729u.jpg 
Here's how it looks like. The red line is the end of my right screen, which is smaller than my left, and that grey line is the problem. :)

**Comment by Js41637** [comment]
Ok yeah, this is a node webkit bug but I might be able to fix it, i'll look into it

**Comment by Sunabubus** [comment]
Nice, thanks!
