### ISSUE TITLE
Allow specifying a search engine to use per show

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#619]
Can you add the ability to change the default search provider and resolution like 1080p etcetera for an individual show instead of using the standard default search settings but if it hasn’t been changed it will just use the default settings.

**Comment by Js41637** [comment]
You can already add custom search engine strings to series by selecting the serie and clicking the settings icon next to find a torrent.
![](http://puu.sh/mxL7K/efcbd0abdc.jpg)

and then you add either 720p or 1080p or a specific release group and it willl automatically add this to the url when you search

**Comment by Js41637** [comment]
Specifying search engines per show is something that could be added though.

**Comment by zero77** [comment]
Thanks I missed that, and yes that would be a handy thing to have.
