### ISSUE TITLE
Auto Download Not Working

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#623]
The automatic torrent download is not working it either doesn’t come back with any results when in reality there are results or it just doesn’t download at all. This is the same for every torrent site you use it works at first but then stops working after a while.

**Comment by garfield69** [comment]
To start figuring out why your auto downloads are not working we are going to need some basic info. 

Please go the the DuckieTV *about* page (click on the (i) icon at the bottom left of the main duckietv page), and then scroll down to the *statistics* section.
Use the **Print Screen** key to capture and **ctrl v** to paste into a box below the whole statistics section. Use as many screen dumps as it takes to get it all please. thanks.

**Comment by zero77** [comment]
I am currently trying the nightly release I will try the above if it still doesn’t work in the nightly release.

**Comment by zero77** [comment]
The nightly release didn’t seem to make any difference so I have taken the screen dumps like you asked. I wasn’t able to upload the image hear so I posted a link to them.

https://s21.postimg.org/qob0h0u07/Untitled1.png

https://s28.postimg.org/lg5kvl3xp/Untitled2.png

**Comment by garfield69** [comment]
OK then. So while we are figuring out what is going on, if you make any changes to the DuckieTV settings, then please let us know so we can keep track of things.

We are going to step through the auto download process, so we can check and cross off all the different things that need to be working for an auto download to proceed. 

The DuckieTV Torrent interface works best with uTorrent 3.4.x.
Please provide the version and build number of uTorrent you are using: find it on uTorrent Help, About uTorrent. example: uTorrent 3.4.5 (build 41162) (32-bit).

Second, auto-download will not initialise until DuckieTV and uTorrent have a valid connection.

Shut-down DuckieTV and start-up uTorrent, if it's not already started. When you start DuckieTV, check the status of the DuckieTV-uTorrent connection by hovering your pointer over the uTorrent Icon on the left of the main DuckieTV page.

If there is a red dot and the tooltip is *Torrent Client Offline* then click on the Icon and wait for the tooltip to go *Torrent Client Connected* and the dot to go green.

Next, we need to take a look at the logs. So press the **F12** key to open the *developers tools panel*, and click on the **console** tab to view the logs.
Take a screen capture of the complete logs so far and paste upload them here for us to take a look.

**Comment by zero77** [comment]
Ok thanks and I am using uTorrent 3.4.5 build 41628 32-bit and the small dot next to the uTorrent icon is green currently although sometimes it has changed to red I then click on it and it goes green after a couple of seconds.

https://postimg.org/image/syo49ryv5/

https://postimg.org/image/rvts2qu3z/

**Comment by garfield69** [comment]
OK good. well so far everything seems to be looking good.

so the auto download (once it has initialized successfully) launches every 15 minutes, and checks for any episodes that have been aired, going as far back (according to your current settings) as one day from current local time.
if that episode not already been marked as downloaded,  has not been marked as watched, has not already had a magnet-hash fetched previously, and the seeds is greater or equal to (according to your settings) 1, then we fetch that magnet and send it to uTorrent for processing.

So when you next perceive there is a problem, first look at the log for any errors. Post the screen captures here for review. 

If there are no errors, but you perceive there is a problem, then the next step would be for us to turn on some debug tracings, and try to diagnose what's is going on from that.

**Comment by zero77** [comment]
Ok thanks and is there a problem if that dot sometimes goes red and is there a way to change the time from 15 min and a way to change when it starts to check for that episode.

**Comment by garfield69** [comment]
> is there a problem if that dot sometimes goes red

uTorrent needs to be running and in connection with DuckieTV in order for DTV to manage episode magnets and track download progress.
So if the dot is red then that connection is offline and DTV cannot talk to uTorrent.
Once the connection goes green, monitoring should resume (unless that torrent magnet has been deleted from uTorrent before DTV had a chance to mark the episode as downloaded).
Once the episode has been marked as downloaded, you can delete the torrent from uTorrent (DTV cannot do this itself presently, I don't think the API supports this command).

> is there a way to change the time from 15 min and a way to change when it starts to check for that episode.

The 15 minute auto download check is hard coded. We see no need to make this timer configurable.

**Comment by garfield69** [comment]
If for some reason you need to launch an auto download for an episode manually, then from the episode details page, you can click the auto download button, which will pass that request to the auto-download manager for processing.
