### ISSUE TITLE
Nightly Change Log broken

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#624]
Can you update the change log for each nightly release not just the main release.

**Comment by Js41637** [comment]
Not the actual changelog, no. The nightlys themselves are meant to include a changelog of what has changed but the script to do this keeps breaking.

**Comment by zero77** [comment]
so there is currently only a changelog for the main releases and not the nightly as the script that dues this is faulty. I am guessing there in no other info on what has been changed other than on the release page. Is this the same for android as well.

**Comment by SchizoDuckie** [comment]
Correct. There is some serious [bash-fu](https://github.com/DuckieTV/BuildBot/blob/master/deploy-nightly.sh#L9) going on in the nightly-release script to fetch the list of git-commits between the last deployed nightly or last tag and the current HEAD, which is less than stable. I'll try to look into it when i have some time

**Comment by garfield69** [comment]
from Js41637:
>The build bot (or the nightly part at least) is going to be remade in NodeJS hopefully sooooooonish and it will be a lot easier and better.

**Comment by Js41637** [comment]
Some work on this has been done https://github.com/DuckieTV/Deploy-Nightly

**Comment by Js41637** [comment]
It's turnin' out pretty noice.
![image](https://cloud.githubusercontent.com/assets/6258213/14315906/583048c6-fc43-11e5-9546-8171a5bc9024.png)

**Comment by garfield69** [comment]
https://github.com/DuckieTV/BuildBot/commit/b04f78b0637ae95a0c485d6b9555e7b0585647e2 resolves this ticket.

**Comment by zero77** [comment]
Thanks, this looks really good although, Windows executables are sometimes missing.
