### ISSUE TITLE
Disable hijacking of last visited sites not present

### ISSUE THREAD

**Issue by geekgarage** [SchizoDuckie/DuckieTV#628]
Disable hijacking of last visited sites not present. this needs to be FIXED ASAP. it's really annoying that you can't disable that without disabling the whole plugin.... i just need the button to open it up when i need to look at it, not every freaking time i open a new tab

**Comment by SchizoDuckie** [comment]
This is not the way to request anything on any open source project. Please come back when you have vented your frustrations elsewhere. This request specific request will not be addressed any further.
