### ISSUE TITLE
Cloudflare DDOS Protection HTTP error 503

### ISSUE THREAD

**Issue by sajattack** [SchizoDuckie/DuckieTV#630]
When adding a torrent tracker protected by Cloudflare's DDOS protection (BTN in this example), the server returns a 503 error.
```
https://broadcasthe.net/login.php Failed to load resource: the server responded with a status of 503 (Service Temporarily Unavailable)
deps.js:14081 Page not found undefined
2deps.js:14081 TypeError: Cannot read property 'length' of undefined
    at getTestClient (app.js:1832)
    at test (app.js:1857)
    at deps.js:15437
    at callback (deps.js:25049)
    at Scope.$eval (deps.js:17597)
    at Scope.$apply (deps.js:17696)
    at HTMLButtonElement.<anonymous> (deps.js:25054)
    at HTMLButtonElement.eventHandler (deps.js:5022)
```

**Comment by SchizoDuckie** [comment]
A 503 Service Unavailable does not indicate a problem with the DuckieTV code, rather with the CDN's edge server not being able to reach the actual server :)

**Comment by sajattack** [comment]
I believe the 503 is a result of Cloudflare thinking DuckieTV is not a proper web browser and blocking it.

**Comment by SchizoDuckie** [comment]
You should be able to verify this by hitting F12 inside duckietv and inspecting the request to login.php.

 if it *is* couldflare, there is not much i can do unfortunately.

**Comment by sajattack** [comment]
I believe some kind of User-agent/cookie setup could fix this issue. I'll work on it. See here for another example of this problem. http://superuser.com/questions/888507/problems-with-wget-to-a-cloudflare-hosted-site-503-service-unavailable

**Comment by sajattack** [comment]
https://github.com/nwjs/nw.js/wiki/manifest-format#user-agent

**Comment by SchizoDuckie** [comment]
Yeah I know of that option and also use it to identify with opensubtitles.

The trick here would be to set it using that specific xmlhttprequest that's used for scraping the custom search enigines. Are you able tot test if you can fetch anything from that site with a generic xmlhttpreq at all?

**Comment by sajattack** [comment]
I'm in class right now but I'll probably do some testing tonight.

**Comment by SchizoDuckie** [comment]
Cool thx :)

Just paste some raw xmlhttp req code into duckietv's dev console to bypass cross-domain limitations!
Thanks for this, i' m off to bed!

**Comment by sajattack** [comment]
So basically the way it works is it loads the cloudflare ddos page with status code 503, does it's checks and gives you a cf_clearance cookie, then redirects to the proper page. I think we need to ignore the 503 and capture the cookie. Not sure how to do that with xhr.

**Comment by Js41637** [comment]
Did you try changing the useragent in the package.json? did it do anything?

**Comment by sajattack** [comment]
I'm running the standalone windows nightly. How would I change the package.json?

**Comment by garfield69** [comment]
@sajattack  if you are keen, you could install the standalone / development source combo rather than the nightly.
This would give you access to the source code to play with.
Instructions available at this [wiki](https://github.com/SchizoDuckie/DuckieTV/wiki/How-to-Install-a-Development-version-of-the-Windows-DuckieTV-Standalone).
Follow option 1 in the guide.

**Comment by Js41637** [comment]
I'm no expert in cloudflare-ology but bypassing their 5 second redirect seems impossible with normal angular xhrs, also their redirect protection requires javascript enabled on the page which is a problem for xhrs. Aside from the possibility of trying to use an iframe, dis gonna be a hard problem to fix. And changing the useragent has no effect. This problem affects both standalone and chrome

**Comment by sajattack** [comment]
Details on xhr redirects http://stackoverflow.com/questions/16386148/why-browser-do-not-follow-redirects-using-xmlhttprequest-and-cors

**Comment by sajattack** [comment]
This guy found a way to modify redirects in rails http://softwareas.com/the-weirdness-of-ajax-redirects-some-workarounds/

**Comment by SchizoDuckie** [comment]
Yea, that's nice and all but the browser context can't manipulate responses :)

**Comment by SchizoDuckie** [comment]
Going to flag this as a wontfix because we won't be able to handle xhr redirect trickery, sorry :)
