### ISSUE TITLE
Linux setup not working

### ISSUE THREAD

**Issue by hotice** [SchizoDuckie/DuckieTV#632]
The Linux setup script is not working. Everywhere in the script, the application is called "PKGNAME", so it tries to actually install "PKGNAME", not DukieTV, and obviously, it fails.

The .desktop file is also called "PKGNAME" (PKGNAME.desktop) and its contents refer to the app as "PKGNAME" instead of DukieTV.

And finally, the .desktop file points to an icon but there's no icon available in the DukieTV Linux downloads.

**Comment by garfield69** [comment]
Thanks.
This [Reddit](https://www.reddit.com/r/duckietv/comments/3y49gx/deb_installer_for_duckietv/) indicates that Schizoduckie may replace the current linux installer.
