### ISSUE TITLE
single click to mark as watched

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#633]
from [Reddit](https://www.reddit.com/r/duckietv/comments/43f3je/single_click_to_mark_as_watched/)

b8dm0j0:
>would be awesome if it were possible to single click the area which the "tick" normally appears (when a episode is marked watched) to mark an episode as watched.

**Comment by garfield69** [comment]
![image](https://cloud.githubusercontent.com/assets/6933240/12698231/53d25128-c7fc-11e5-8516-41bc51a5d9ab.png)

**Comment by SchizoDuckie** [comment]
I love it. brilliant.
