### ISSUE TITLE
Mark All Watched doesn't sync to trakt?

### ISSUE THREAD

**Issue by Js41637** [SchizoDuckie/DuckieTV#634]
I haven't been able to really test this at the moment but I recently got my syncing working again and I marked a season as all watched and nothing changed on trakt. Are batch marking as watched still working correctly?

**Comment by garfield69** [comment]
Confirming that using Seasons mark-all-watched does not push to Trakt.TV history.
And neither does Series mark-all-watched.
Only Episode mark-as-watched does a push to Trakt.TV history.
I will look into this.
