### ISSUE TITLE
auto download status sidepanel

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#636]
When the time is near for my favourite episodes to become available, I recently find myself trolling through the console logs looking for clues to what the auto download is doing.

Instead of flooding the log with auto download progress messages, I thought it would be nice to have a sidepanel that users could see what the auto download service has been up to in the last 15 minute cycle.

This is what I've come up with:
![image](https://cloud.githubusercontent.com/assets/6933240/12787961/72aa6db2-cafc-11e5-8b3a-19befc31643f.png)

**Comment by Js41637** [comment]
Looks very cool

**Comment by SchizoDuckie** [comment]
excellent
