### ISSUE TITLE
DuckieTV and NWJS 0.14.x upgrade

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#638]
upgrade issues for NWJS 0.14.x

_current docs:_
[http://docs.nwjs.io/en/latest/](http://docs.nwjs.io/en/latest/)
_current known issues:_
[http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/#known-issues](http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/#known-issues)
_migration from 0.12 to 0.13+_
[http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/](http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/)
_what's new in 0.13+_
[http://nwjs.io/blog/whats-new-in-0.13/](http://nwjs.io/blog/whats-new-in-0.13/)
**findings so far:** 
- nwjs Error Message: "Package is invalid. Details: 'Localization used, but default_locale wasn't specified in the manifest.'.

add to package.json  

``` javascript
  "snapshot": "",
  "default_locale": "en"
```
- nwjs Error Message: "Invalid value for 'app.urls[0]': Missing scheme separator."

removed from package.json

``` javascript
  "node-remote": "",
```

could probably be changed to `"node-remote": "http://localhost"`?
The format of node-remote is changed to array of match patterns used by [Chrome extension](https://developer.chrome.com/extensions/match_patterns)
related to: [https://github.com/nwjs/nw.js/issues/3571](https://github.com/nwjs/nw.js/issues/3571) 
- Duckietv console error: "Uncaught TypeError: win.emit is not a function"

You get the above if you use any of the systray functions, or the window minimize/maximize/restore buttons.

Window is not inherited from EventEmitter anymore, but the methods on(), once(), removeListener() and removeAllListeners() are still supported.
this means win.emit is not longer supported. Changes to app.standalone.systray.js, app.standalone.zoom.js and app.standalone.windowdressing.js will be required. Will need to bring them back under angularjs so that `$rootScope.$emit` can be used instead.
Also controllers/ActionBarCtrl.js.
- All NW.js APIs are loaded in **nw** object globally and can be used directly in JavaScript files.

The legacy way of loading NW.js APIs using require('nw.gui') is also supported. It returns the same nw object. This will be deprecated in 0.14 or later.

[edit] See branch [nwjs0.14.x](https://github.com/SchizoDuckie/DuckieTV/tree/nwjs0.14.x) for all the relevant changes so far.

Also, now that NWJS runs under chromium, the location of the database and localStorage is different. 
[edit] But NWJS automatic migrations of local storage and websql from 0.12.3 to 0.14.x should be available soon.

note: For access the development tools, the build bots will need to fetch the SDK version of nwjs 0.14.x

[edit] https://github.com/nwjs/nw.js/issues/4853 tracks progress with nwjs data migration from 0.12.3 to 0.14.x (localstorage and indexdb). despite being closed the ticket is still active. Need to check support for WEBSQL migration.
[edit2] I raised ticket 5018 with nwjs to fix websql migration, this has now been closed.

**Comment by SchizoDuckie** [comment]
wow. excellent work man, i love you <3

**Comment by Js41637** [comment]
So i've been looking at nw.js, so the latest stable versions are v0.15 with the LTS release being v0.14.6, should we move to supporting v0.14.6 LTS or the go to the latest with more features.

**Comment by Js41637** [comment]
I think we should work on updating our nw.js to at least the LTS release which is v0.14.6 which uses v50 of Chrome, the current being v51 that v0.15 of nw.js runs on. 
Chrome v49+ has 90% support for ES6, if we don't need to support v48 (which only has 65% support) I think we should start using ES6 and take advantage of the latest features.

**Comment by garfield69** [comment]
I think that given how rare DuckieTV releases are these days (one a year seems the average recently), we might as well go straight to the latest stable nwjs 0.15 and save some intermediate updates along the way.

**Comment by SchizoDuckie** [comment]
The data dir migration and possibility of users losing all their data and having to backup and restore is a bit of a no-go for me. I read something in the docs about that though, some patch to prevent data loss. If we can prevent this from happening i'm still inclined to say we go for the LTS version though. we don't need to be on the cutting edge, unless there are things we *really* need in 0.15.

second half of the year is probably going to know a couple of releases, once i've got my new battlestation set up and the house finished :tired_face:

**Comment by Js41637** [comment]
I think its any 0.13+ though that requires the migrations, I dunno I only skimmed through the docs.

**Comment by garfield69** [comment]
new branch [nwjs0.14.6](https://github.com/SchizoDuckie/DuckieTV/tree/nwjs0.14.6) contains all the current nwjs support changes on to of the current angular code.

branch NWJS013+ jas been deleted.

**Comment by Js41637** [comment]
Ok so just gotta update the docs and should be that simple.

So does v0.14.6 require any actual changes?

**Comment by garfield69** [comment]
Yes. We still need to create the migration process to clone the DB and
settings across to the new folder location.

I've been sidetracked by the calendar not switching to a new day for
standalone users or nwjs 0.12.3 (nightly) that leave Dtv up 24/7

But plan to research the migration stuff. Happy for you to do the research
if you want to take it on.

 

  _____

**Comment by garfield69** [comment]
checklist

- [ ] build migration for DB and settings from local 0.12.3 folder to 0.14.6 folder
- [ ] fix #675 
- [ ] prepare nightly buildbot to suck 0.14.6 nwjs 
- [ ] merge nwjs0.14.6 branch into angular
- [ ] update release builder to suck 0.14.6 nwjs
- [ ] bound to be other steps , add as you discover them

**Comment by Js41637** [comment]
Ok so 0.14.6. the `toolbar` option is deprecated so I assume you cant show the toolbar anymore which we don't really need anyway but when using the 'normal' version, I was unable to open the dev tools, they would pop up but not load. I did some searching and someone said that in order to use the dev tools the SDK of nw.js has to be used.

**Comment by garfield69** [comment]
Oh yea, sorry, forgot to mention that. You need the SDK build of nwjs if you want to have access to the development tools ;-)

**Comment by garfield69** [comment]
progress of sorts. NWJS 0.15.3 (and we are told 0.14.7 whenever its is released) can now automatically migrate the local storage folder.
I have tested 0.15.3 migration again 0.12.3 in my sandbox and can confirm that the local storage has been migrated successfully.
However, the file in the database (our WEBSQL DB) has not.
I think I will raise a ticket on github nwjs if I cant find one there already.

**Comment by garfield69** [comment]
Excellent . I have just tested nwjs 0.15.4 from their nightly builds, and can confirm that the migration from 0.12.3 to 0.15.4 now works for local storage and websql. \o/
Now we just have to wait for the fixes to trickle their way to the 0.14.x channel, and to all the other platforms flavours...I noticed that so far all the migration fixes seemed focused on OS_WIN, and have asked about MacOSX, Linux and Android. Awaiting reply.

**Comment by garfield69** [comment]
Latest news regarding roll out of nw.js 0.14.7 which should include all the 0.12.3 migration fixes:
>From: Roger Wang [mailto:wenrui@gmail.com] 
>Sent: Wednesday, 20 July 2016 15:10
>To: nw.js
>Cc: garfield69dtvdev@gmail.com
>Subject: Re: NW.js 14.7 eta?

>We'll work on the release of 0.14.7 after 0.16.0 release, which will happen soon this week. 0.14.7 would >be released in 1-2 days after 0.16.0. 

>btw, you could try the latest 0.14.7 build here: http://dl1.nwjs.io/live-build/06-25-2016/nw14-c61038e-64fe72c-2a9e6e1-66f8f40/v0.14.7/

**Comment by garfield69** [comment]
\o/  nw.js for 0.14.7 is available. details at http://nwjs.io/blog/v0.14.7/
all that is required now is to decide when we are going to roll out standalones using the nw.js 0.14.7 builds, and update the check list further up this ticket with more detailed pre-reqs etc.

**Comment by SchizoDuckie** [comment]
I've merged this into angular and i'm currently running v0.18.6 locally. It solves a lot of problems that were present in 0.14.x and all @garfield69's patches look to work flawlessly

**Comment by garfield69** [comment]
8410dae1a5970015681c5874a6c349b3bd94713c  completes this ticket.
