### ISSUE TITLE
Won't stay minimized

### ISSUE THREAD

**Issue by SushiLover** [SchizoDuckie/DuckieTV#639]
Unless I'm checking the calendar, Duckie is always minimized to the taskbar. Yet every morning when I turn the monitor on, Duckie has maximized itself, whether a torrent has been downloaded or not. Maybe not so much an issue, but it sure is annoying. Duckie is running on a fresh install of W8.1 64bit.

**Comment by garfield69** [comment]
every night, at 1 minute past midnight, DuckieTV does a reload, in order to refresh the new date-time across all its services, and to update the calendar for the new day's events.
The reload is effectively a re-launch of DuckieTV.

So if you want DuckieTV to start up mimnimized, go the the DuckieTV **settings,window** sidepanel,
and set the *window on start-up* option to **minimized**.

**Comment by SushiLover** [comment]
Thanks, but I tried that setting last night before I made this post and Duckie still maximized itself. Also, I don't recall this happening when I ran Duckie on W10.

**Comment by SushiLover** [comment]
Changing the setting to minimize didn't fix the issue; today Duckie was again maximized.

**Comment by garfield69** [comment]
I should have asked before , but which version of DuckieTV are you running?

**Comment by SushiLover** [comment]
And I should have said ;) DuckieTV Standalone v1.1.3

**Comment by garfield69** [comment]
I've just performed some midnight crossovers tests on my win7 platform, and 1.1.3 stays minimized during the crossover on that platform.

To test I just shutdown DuckieTV using the exit menu on the systray, set the clock back to yesterday 23:59, startup DuckieTV in minimized mode, and watch what happens. The DuckieTV internal reload happens 1 second after midnight (not 1 minute as I stated earlier).

So it appears to me that its something to do with 8.1 :-(  I don't have an 8.1 to test on, sorry.

The only other thing I can offer, is trying a DuckieTV development nightly. The latest development version had had changes to the way we do the reload, to fix issues with the systray on macs and linux, and that may also have benefits for win 8.1 (perhaps).

If you want to try, you can find the nightly downloads [here](https://github.com/DuckieTV/Nightlies/releases) and if you need it, the wiki to help with the installation [here](https://github.com/SchizoDuckie/DuckieTV/wiki/How-to-Install-a-Development-version-of-the-Windows-DuckieTV-Standalone). (follow option 2 in the wiki guide for installing nightlys).

**Comment by SushiLover** [comment]
Thanks for the tip on trying a nightly. I downloaded the latest one but for now will just keep re-minimizing DuckieTV.
