### ISSUE TITLE
xem cache is not up to date

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#645]
DuckieTV/xem-cache for mythbusters is not up to date (last update 17 hours ago).
the cache last entry is for **s2015e14** 
[https://github.com/DuckieTV/xem-cache/blob/gh-pages/73388.json](https://github.com/DuckieTV/xem-cache/blob/gh-pages/73388.json)
however xem (fetched 10 minutes ago, last updated 4th jan 2016) has last entry as **s2016e11**
[http://thexem.de/map/all?id=73388&origin=tvdb&destination=scene](http://thexem.de/map/all?id=73388&origin=tvdb&destination=scene)

I have not checked if other DuckieTV/xem-cache's are out of date.

is there a problem with the xem update scripts?

**Comment by garfield69** [comment]
I don't have a clue from where and which scripts are kicked off.
Also difficult for me to diagnose, as I can't find any docs or logs that I can access to review these processes.

It appears to me that the **Nightlies/build/gulp/xem.js** script should be running every so often some place as this seems to be the script that updates the content of the xem maps, but I have not proof for  this.

I believe that the **Nightlies/build/push-xem.sh** (or a clone of it from some other place) is running since i can see the commits from  `git commit -m "XEM Cache update"`  issued to the files in the **DuckieTV/xem-cache** repo, but as this script only copies the **deploy/xem** files to the DuckieTV/xem-cache repo, it does not actually update the contents of the xem maps themselves.

It looks like only @SchizoDuckie  has access to, and a clue as to how, it all really works.

**Comment by garfield69** [comment]
additional series that need upt o date xem tables:
American Dad! 
Ace of Diamond
World Trigger

**Comment by SchizoDuckie** [comment]
I believe I just fixed this. The trigger is a daily crontab on the buildbot, which wasn't aware enough of it's environment. Stripped some of the crap as well.

**Comment by garfield69** [comment]
I can confirm that the xem-cache has the latest up to date information
