### ISSUE TITLE
[Feature Request] add isohunt.to search engine

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#647]
Can you add https://isohunt.to as another torrent search engine.
Can you also add the ability for DuckieTV to check the other search engines if it doesn’t find the tv show in the default search engine first.

**Comment by garfield69** [comment]
>Can you also add the ability for DuckieTV to check the other search engines if it doesn’t find the tv show in the default search engine first.

you already asked for this in #618 

BTW, please only put one request per ticket. When it comes time to implementing/declining features, it is simpler to manage tickets if they focus on just one feature. Thanks.

**Comment by zero77** [comment]
Sorry I forgot I already posted that and ok will do.
