### ISSUE TITLE
Http to https Amend

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#649]
DuckieTV connects to lots of different websites like https://deluge.readthedocs.org some of the websites like https://deluge.readthedocs.org are set to use http in DuckieTVs source code but they support SSL. 
So can you update the websites to use https instead of http if they support it.

**Comment by garfield69** [comment]
Um, DuckieTV does **not** connect to deluge.readthedocs.org ... what you spotted there is a **comment** in the source of `DuckieTV/js/services/TorrentClients/Deluge.js` for use by developers when wanting to lookup the API docs for deluge.
```javascript
/**
 * Deluge web client implementation
 *
 * API Docs:
 * http://deluge.readthedocs.org/en/develop/modules/deluge.ui.web.html
 *
 * - Supports setting download directory
 */
```

So do you have another example of DuckieTV actually using http some place?

**Comment by zero77** [comment]
I have seen lots of links throughout the source code, but I haven’t checked to see if they support SSL. If I spot any links, I will change them but is there a quicker way to check.
That was just an example as you put http when https is supported sorry I didn’t specify that.

**Comment by garfield69** [comment]
**list of http:// links in DuckieTV source.**
note: excludes the vendor folder, and any that are comments (prefixed with `//` or `*`)

  - js\app.requestinterceptors.js
    `Line 39:                     if (config.url.indexOf('http://duckietv.herokuapp.com/') == -1) config.url = 'http://duckietv.herokuapp.com/?t=' + new Date().getTime() + '&u=' + config.url;`
  - js\controllers\settings\customSearchEngineCtrl.js
    `Line 15:                 mirror: 'http://torrentleech.org', // http://yoursite.com',`
  - js\controllers\sidepanel\SidepanelEpisodeCtrl.js
    `Line 55:                 window.open('http://www.netflix.com/Login');`
  - js\CRUD.entities.js
    `Line 513:         mirror: 'http://torrentleech.org',`
    `Line 536:         mirror: 'https://kat.cr', // http://yoursite.com',`
    `Line 579:         mirror: 'http://www.nyaa.se',`
  - js\services\IMDB.js
    `Line 10:         search: 'http://www.imdb.com/find?q=%s&s=all',`
    `Line 11:         details: 'http://www.imdb.com/title/%s'`
  - js\services\Netflix.js
    `Line 5:                 return $http.get('http://www.netflix.com/api/desktop/search/instantsearch?esn=www&term=' + title).then(function(result) {`
    `Line 10:                 return $http.get('http://www.netflix.com/WiMovie/' + serieID).then(function(result) {`
    `Line 21:                 return $http.get('http://www.netflix.com/YourAccount').then(function(result) {
  - js\services\OpenSubtitles.js`
    `Line 10:             hostName: "http://api.opensubtitles.org", // Default is empty`
  - js\services\SettingsService.js
    `Line 104:                 'qbittorrent.server': 'http://localhost',`
    `Line 109:                 'qbittorrent32plus.server': 'http://localhost',`
    `Line 118:                 'tixati.server': 'http://localhost',`
    `Line 140:                 'vuze.server': 'http://localhost',`
    `Line 145:                 'transmission.server': 'http://localhost',`
    `Line 153:                 'utorrentwebui.server': 'http://localhost',`
    `Line 158:                 'deluge.server': 'http://localhost',`
  - js\services\TorrentClients\uTorrent.js
    `Line 35:         pair: 'http://localhost:%s/gui/pair',`
    `Line 36:         version: 'http://localhost:%s/version/',`
    `Line 37:         ping: 'http://localhost:%s/gui/pingimg',`
    `Line 38:         api: 'http://localhost:%s/btapp/',`
  - js\services\TorrentFreak.js
    `Line 7:         top10rss: 'http://torrentfreak.com/category/dvdrip/feed/'`
  - js\services\TorrentSearchEngines\GenericTorrentSearchEngine.js
    `Line 107:                     out.torrent = 'http://torcache.gs/torrent/' + magnetHash[0].toUpperCase() + '.torrent?title=' + encodeURIComponent(out.releasename.trim());`
  - js\services\TorrentSearchEngines\KickassMirrorResolver.js
    `Line 10:                 kickasstorrents: 'http://www.rockaproxy.com/allTorrentLinksPage.php'`
  - js\services\TorrentSearchEngines\Nyaa.js
    `Line 5:                 mirror: 'http://www.nyaa.se',`
  - js\services\TorrentSearchEngines\RarBG.js
    `Line 40:                         out.torrent = 'http://torcache.gs/torrent/' + magnetHash[0].toUpperCase() + '.torrent?title=' + encodeURIComponent(out.releasename.trim());`
  - js\services\TorrentSearchEngines\ShowRSS.js
    `Line 56:                         out.torrent = 'http://torcache.gs/torrent/' + magnetHash[0].toUpperCase() + '.torrent?title=' + encodeURIComponent(out.releasename.trim());`
  - js\services\TorrentSearchEngines\ThePirateBayMirrorResolver.js
    `Line 11:                 thepiratebay: 'http://www.piratebayproxylist.co/'`
  - js\services\UpgradeNotificationService.js
    `Line 12:         var dlgLinks = '<h2>Questions? Suggestions? Bugs? Kudo\'s?</h2>Find DuckieTV on <a href="http://reddit.com/r/DuckieTV" target="_blank">Reddit</a> or <a href="http://facebook.com/DuckieTV/" target="_blank">Facebook</a>.<br>If you find a bug, please report it on <a href="http://github.com/SchizoDuckie/DuckieTV/issues">Github</a></em>';`
  - js\utility.js
    `Line 87: console.log("%cDuckieTV", "color:transparent; font-size: 16pt; line-height: 125px; padding:25px; padding-top:30px; padding-bottom:60px; background-image:url(http://duckietv.github.io/DuckieTV/img/logo/icon128.png); background-repeat:no-repeat; ", "quack!\n\n\n\n\n\n");`
  - templates\chrome-top-sites.html
    `Line 20:         <img lazy-background="http://chromeutils.appspot.com/t/?url={{::site.url}}">`
  - templates\settings\language.html
    `Line 11:     <a href="http://www.reddit.com/r/duckietv/comments/28wtr5/announcement_want_to_have_duckietv_in_your_native/" style='border:0; display:inline; padding:0; margin:0; text-decoration:underline' target='_blank' translate-once="SETTINGS/LANGUAGE/desc3">  </a>`
  - templates\settings\utorrent.html
    `Line 51:   <a target="_blank" href="http://schizoduckie.github.io/PimpMyuTorrent/?from=DuckieTV#" class="btn btn-success" translate-once="COMMON/remove-ads/btn"></a>`
  - templates\settings\utorrentwebui.html
    `Line 28:     <a target="_blank" href="http://schizoduckie.github.io/PimpMyuTorrent/?from=DuckieTV#" class="btn btn-success" translate-once="COMMON/remove-ads/btn"></a>`
  - templates\sidepanel\about.html
    `Line 8:         <p><span translate-once="ABOUT/help/p1"></span><a href='http://reddit.com/r/duckietv' target='_blank'>Reddit/r/DuckieTV</a></p>`
    `Line 11:         <p><span translate-once="ABOUT/bugs/p1"></span><a href="http://github.com/SchizoDuckie/DuckieTV/issues" target='_blank'>Github</a><span  translate-once="ABOUT/bugs/p2"></span></p>`
    `Line 13:         <p><span translate-once="ABOUT/tvinfo/p1"></span><a href='http://thetvdb.com' target='_blank' translate-once="ABOUT/tvinfo-tvdb/link"></a><span translate-once="ABOUT/tvinfo/p2"></span><a href='http://www.thetvdb.com/wiki/index.php/Main_Page' target='_blank' translate-once="ABOUT/tvinfo-tvdbwiki/link"></a></p>`
    `Line 26:           <li><a href='http://TheTVDB.com' target='_blank'>TheTVDB.com</a><span translate-once="ABOUT/credits/li1"></span></li>`
    `Line 27:           <li><a href='http://Trakt.tv' target='_blank'>Trakt.TV</a><span translate-once="ABOUT/credits/li2"></span></li>`
    `Line 28:           <li><a href='http://angularjs.org' target='_blank'>Angular.js</a><span translate-once="ABOUT/credits/li3"></span></li>`
    `Line 29:           <li><a href='http://Github.com' target='_blank'>Github</a><span translate-once="ABOUT/credits/li4"></span></li>`
    `Line 30:           <li><a href='http://reddit.com' target='_blank'>Reddit</a><span translate-once="ABOUT/credits/li5"></span></li>`
    `Line 31:           <li><a href='http://angular-translate.github.io' target='_blank'>Angular-translate.js</a><span translate-once="ABOUT/credits/li7"></span></li>`
    `Line 32:           <li><a href='http://angular-formly.com' target='_blank'>Angular-formly.js</a><span translate-once="ABOUT/credits/li8"></span></li>`
    `Line 37:           <strong translate-once="ABOUT/dtvlinks-github/lbl"></strong> <a href='http://duckie.tv' target='_blank'>http://duckie.tv</a></p>`
  - templates\sidepanel\serie-details.html
    `Line 14:           <td><a style="text-decoration: underline" ng-href="http://www.google.com/search?q={{::sidepanel.serie.name}} (TV series)+Wikipedia&btnI=745" target="_blank">Wikipedia</a> <a style="text-decoration: underline" ng-href="http://www.imdb.com/title/{{::sidepanel.serie.IMDB_ID}}" ng-hide="serie.IMDB_ID < 1" target="_blank">IMDB</a></td>`
  - templates\torrentClient.html
    `Line 19:     <div class="alert alert-info" style="margin:10px" ng-if="client.getTorrentClientName()  == 'uTorrent'"><button class='btn btn-small btn-warning' style='float:right' ng-click='client.removeToken()' translate-once="TORRENTCLIENT/clear-authority/btn"></button><strong><span translate-once="TORRENTCLIENT/desc/p1"></span><a style="color: #428bca" href='http://www.utorrent.com/downloads/complete/os/win/track/alpha'>v3.4.1+</a><span translate-once="TORRENTCLIENT/desc/p2"></span></strong><span translate-once="TORRENTCLIENT/desc/p3"></span></div>`

**Comment by Js41637** [comment]
I dunno about `localhost` most of the Netflix ones redirect to `https` anyway. I guess it doesn't really make a difference but I would only care about using HTTPS when we are actually _sending_ data. Links to things like reddit or github would make no difference.

**Comment by Js41637** [comment]
And also, not everything supports https meaning you would need to check all the urls before switching them.

**Comment by zero77** [comment]
I have looked through and changed all the URLs that support SSL except for the localhost as I couldn’t check if they all support SSL.

Some don’t support SSL like IMDB they only use SSL on their Pro website (secure.imdb.com) and opensubs don’t either and some use SSL but their certificate isn’t widely accepted.

**Comment by garfield69** [comment]
**test and confirm:**
- [ ] js/CRUD.entities.js
- [ ] js/app.requestinterceptors.js
- [ ] js/controllers/settings/customSearchEngineCtrl.js
- [ ] js/controllers/sidepanel/SidepanelEpisodeCtrl.js
- [ ] js/services/Netflix.js
- [ ] js/services/TorrentFreak.js
- [ ] js/services/TorrentSearchEngines/Nyaa.js
- [ ] js/services/UpgradeNotificationService.js
- [ ] js/utility.js
- [ ] templates/chrome-top-sites.html
- [ ] templates/settings/language.html
- [ ] templates/settings/utorrent.html
- [ ] templates/settings/utorrentwebui.html
- [ ] templates/sidepanel/about.html
- [ ] templates/sidepanel/serie-details.html

**Comment by garfield69** [comment]
@SchizoDuckie 
the CORSInterceptor has been changed from using `'http://duckietv.herokuapp.com/` to https.
Q1: ok to keep or reverse?
Q2. if OK, should the `config.url.indexOf('http') == 0` below be also changed to https?
```javascript
.factory('CORSInterceptor', ['$q', '$injector',
    function($q, $injector) {
        return {
            request: function(config) {
                if (document.domain != 'localhost' && config.url.indexOf('http') == 0 && config.url.indexOf('localhost') === -1) {
                    config.headers['X-Proxy-Url'] = config.url;
                    if (config.url.indexOf('https://duckietv.herokuapp.com/') == -1) config.url = 'https://duckietv.herokuapp.com/?t=' + new Date().getTime() + '&u=' + config.url;
                }
                return config;
            },
            'responseError': function(rejection) {
                if ('recovered' in rejection.config) {
                    return rejection;
                }
                rejection.config.recovered = true;
                var $http = $injector.get('$http');
                return $http(rejection.config);
            }

        };
    }
])
```

**Comment by SchizoDuckie** [comment]
Not sure. If you access the demo over non-https the request interceptor
will bork due to mixed content errors
Op 20 mrt. 2016 23:45 schreef "garfield69" <notifications@github.com>:
