### ISSUE TITLE
'Object.observe' is deprecated and will be removed in M50, around April 2016.

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#650]
Warning on DuckieTV console log from chromium 49:

>'Object.observe' is deprecated and will be removed in M50, around April 2016.
>See https://www.chromestatus.com/features/6147094632988672 for more details.

impacted code:
```javascript
js\controllers\serieslist\SeriesListCtrl.js (1 hit)
	Line 53:         Object.observe(SeriesListState.state, function(newValue) {
js\directives\calendar.js (1 hit)
	Line 36:             Object.observe(SidePanelState.state, function(newValue) {
js\directives\queryMonitor.js (1 hit)
	Line 18:                 Object.observe(CRUD.stats, function() {
js\directives\sidePanel.js (1 hit)
	Line 51:             Object.observe(SidePanelState.state, function(newValue) {
js\vendor\object-observe.min.js (4 hits)
	Line 1: Object.observe||function(f,C,v){var k,l,H="add update delete reconfigure setPrototype preventExtensions".split(" "),I=v.Node?function(a){return a&&a instanceof v.Node}:function(a){return a&&"object"===typeof a&&"number"===typeof a.nodeType&&"string"===typeof a.nodeName},J=C.isArray||function(a){return function(c){return"[object Array]"===a.call(c)}}(f.prototype.toString),t=C.prototype.indexOf?function(a,c,b){return c.indexOf(a,b)}:function(a,c,b){for(b=b||0;b<c.length;b++)if(c[b]===a)return b;return-1},
	Line 9: e||l.set(b,e={observed:x(),changeRecords:[]});e.observed.set(a,{acceptList:d.slice(),data:c});c.handlers.set(b,e)},r=function(a,c,b,d){c.handlers.forEach(function(c){var f=c.observed.get(a).acceptList;("string"!==typeof d||-1===t(d,f))&&-1<t(b.type,f)&&c.changeRecords.push(b)})};k=x();l=x();f.observe=function(a,c,b){if(null===a||"object"!==typeof a&&"function"!==typeof a)throw new TypeError("Object.observe cannot observe non-object");if("function"!==typeof c)throw new TypeError("Object.observe cannot deliver to non-function");
	Line 9: e||l.set(b,e={observed:x(),changeRecords:[]});e.observed.set(a,{acceptList:d.slice(),data:c});c.handlers.set(b,e)},r=function(a,c,b,d){c.handlers.forEach(function(c){var f=c.observed.get(a).acceptList;("string"!==typeof d||-1===t(d,f))&&-1<t(b.type,f)&&c.changeRecords.push(b)})};k=x();l=x();f.observe=function(a,c,b){if(null===a||"object"!==typeof a&&"function"!==typeof a)throw new TypeError("Object.observe cannot observe non-object");if("function"!==typeof c)throw new TypeError("Object.observe cannot deliver to non-function");
	Line 10: if(f.isFrozen&&f.isFrozen(c))throw new TypeError("Object.observe cannot deliver to a frozen function object");J(b)||(b=H);var d=k.get(a);if(d)G(a,d,c,b);else{var d=void 0,e=I(a)?[]:D(a),h=[],l,g=0,d={handlers:x(),frozen:f.isFrozen?f.isFrozen(a):!1,extensible:f.isExtensible?f.isExtensible(a):!0,proto:y&&y(a),properties:e,values:h,notifier:F(a,d)};if(u)for(l=d.descriptors=[];g<e.length;)l[g]=u(a,e[g]),h[g]=a[e[g++]];else for(;g<e.length;)h[g]=a[e[g++]];k.set(a,d);G(a,d,c,b);1===k.size&&A(E)}return a};
js\app.standalone.systray.js (1 hit)
**[NOTE: this one is actually not in use, its part of a commented proposal]**
	Line 212:             Object.observe(CRUD.stats, function() {
```

It seems we need to replace Object.observe [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/observe](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/observe) with proxy
[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) although its not a 1:1 replacement.

**Comment by garfield69** [comment]
An option would be to add a Object.observe polyfill, such as this one [https://github.com/MaxArt2501/object-observe](https://github.com/MaxArt2501/object-observe) or this one [https://github.com/jdarling/Object.observe](https://github.com/jdarling/Object.observe) although there  is bound be be some increased cost in CPU and memory usage.

**Comment by garfield69** [comment]
Oh, hang on.
Schizoduckie has already implemented this with js\vendor\object-observe.min.js way back in March 2015
Duh! :-)

**Comment by garfield69** [comment]
Additional:
looks like we are using [https://github.com/MaxArt2501/object-observe](https://github.com/MaxArt2501/object-observe) version 0.2.2. It provides O.o only when it is not already available in chrome (nice), but it means that the code has not really gotten used on most of our supported platforms (read: untested on DuckieTV except perhaps on ipads?).
I am going to update to version 0.2.6 (has lots of bug fixes), for when O.o does disappears from chrome 50 and we actually have to start relying on the polyfill.

**Comment by SchizoDuckie** [comment]
Great find :) I targeted ipad compatibility with it indeed. The polyfill
seems to work fine and it's only needed for the serieslist anyway so i'm
all good with that :)
