### ISSUE TITLE
Current month incomplete every time I open Chrome 

### ISSUE THREAD

**Issue by Nebulalurker** [SchizoDuckie/DuckieTV#652]
Every time I open DuckieTV for the first time in Chrome, only a few entries show up in the calendar for the current month. The prior and next month are okay. I am forced to do a refresh to fill out the calendar for the current month. Then weirdly all is okay except than March 13 shows no entries.

This happens on a cold start. No windows/tabs open. Chrome not running in background.
Latest Chrome 64 version 49.0.2623.87
Latest DuckieTV version 1.1.3
Windows 10 Pro Build 10586 with all updates current as of March 11 2016
This is a repeatable error
First image is after refresh. Second is before.

![duckietv-error-current month after refresh](https://cloud.githubusercontent.com/assets/6885136/13715598/08e525b2-e793-11e5-8625-889835f9c67f.PNG)
![duckietv-error-current month before refresh](https://cloud.githubusercontent.com/assets/6885136/13715602/122eacc4-e793-11e5-83c5-68815ebedc14.PNG)

**Comment by garfield69** [comment]
Very strange.  There might be something in the logs that could be useful.
So, after loading for first time, and before doing your refresh, can you press the **F12** key to open the development tools window, click on the **console** tab to view the log, and take some snap shoots of the whole log here for us to take a look. (**PrintScreen** key and **Ctrl-v** to paste directly into body of open ticket here, repeated as many time as it takes to get the whole log). Thanks.

**Comment by garfield69** [comment]
Unable to replicate. Likely therefore to be a local issue on OP's machine.
Closing ticket. Will re-open should OP ever reply to my last post requesting further information.
