### ISSUE TITLE
Magnet links not working

### ISSUE THREAD

**Issue by vishalpatel84** [SchizoDuckie/DuckieTV#660]
Moving the conversation to Github about my issue with magnet links.

Chrome: 49.0.2623.87 (64-bit)
OSX: 10.10.4
DuckieTV - 'Browser Action' mode	1.1.3

![screen shot 2016-03-16 at 3 23 25 pm](https://cloud.githubusercontent.com/assets/17011207/13830621/1fec2f3e-eb8b-11e5-9166-8d6b5e28f4f3.png)
![screen shot 2016-03-16 at 3 24 53 pm](https://cloud.githubusercontent.com/assets/17011207/13830647/43b659f8-eb8b-11e5-8f90-d4a402105dd0.png)

**Comment by garfield69** [comment]
Interesting.
On my win7 dev system, I have also, since the update to chrome 49, have had the magnet link fail consistently during one DuckieTV 1.1..3 session.
But on shutting down chrome and starting it up again, the problem mysteriously disappears.
I'm thinking there is a bug in chrome 49...

have you tried closing down the chrome browser completely, and starting up a fresh one ?
Have a go and see if that helps. Let me know the results. Thanks.

**Comment by vishalpatel84** [comment]
Since i had the issue last night, that was the first thing i did. That and restart my entire machine to see if that would fix it. But unfortunately it did not. I will try again in a second to see if it remedies the situation.

**Comment by garfield69** [comment]
Its tricky. I cant reliably recreate the problem now that its working for me at the moment. And I have not figured out what triggers the failure yet.

If the chrome restart makes no difference, perhaps disabling/enabling DuckieTV might help.
Visit the extensions page chrome://extensions/ and untick the *enabled* checkbox.
restart chrome.
back to extensions and tick the enable checkbox one more.
![image](https://cloud.githubusercontent.com/assets/6933240/13831983/96bd45e2-ec3c-11e5-925d-94d688d9f3b8.png)

**Comment by vishalpatel84** [comment]
i tried both options and it didn't seem to work. it is totally weird why it is not working. I may try removing it from chrome completely and adding the extension again (this time i will take a db backup, last time i did this i forgot to back up and had to start from scratch all over again).

**Comment by garfield69** [comment]
OK. That was going to be my next suggestion :-) Good luck.

**Comment by vishalpatel84** [comment]
uninstall didn't work, issue still persists. the weird this is that it stopped all of a sudden. last time i updated the browser was last week.

**Comment by garfield69** [comment]
Darn.
Yeah, I agree, the timing seems to coincide with the Google's Chrome upgrade to 49m.

In this case, perhaps you should switch to using the standalone version of DuckieTV.
To get started use this [wiki](https://github.com/SchizoDuckie/DuckieTV/wiki/How-can-I-get-the-DuckieTV-app%3F)

**Comment by vishalpatel84** [comment]
stand alone version works great! thanks for the tip

**Comment by garfield69** [comment]
you are welcome.
