### ISSUE TITLE
Add VPN support 

### ISSUE THREAD

**Issue by Gabri3l** [SchizoDuckie/DuckieTV#662]
I know it would probably take a lot of work, but it would be nice to also add a VPN activation through the app (which would require the user to have a subscription to a VPN service). I remember Popcorntime doing something like this, and I think it would be great to have it integrated it somehow. I wish I could provide more help about this but I thought it could be a nice addition to this great project.

**Comment by SchizoDuckie** [comment]
Sorry no. DuckieTV has nothing to do with vpns or the way you connect to the internet. I really don't want to get into that.

The PopcornTime forks did it mostly to make money. Stuff like that will never make it into DuckieTV.

**Comment by jaruba** [comment]
The way this issue was discussed:

![tumblr_mrpj3z2our1sywarso1_500](https://cloud.githubusercontent.com/assets/1777923/13845388/5b7986ba-ec48-11e5-84bf-e400b1357f79.gif)

:))))

**Comment by Gabri3l** [comment]
I understand absolutely. I didn't mean for this project to build a VPN service where people subscribe and pay for it just 'simply' an interface integrated with the app to just activate your VPN. 

What i meant was that i wouldn't want to open a software to connect to a VPN and then open DuckieTV, it would have been nice to be able to do it through the app.

I know I explained myself poorly and I understand not wanting to get into that.

**Comment by lonelyfairie** [comment]
Out of curiosity... why would you need to log in to a vpn using duckie tv?
I don't see the purpose of such a thing since duckie uses whatever your connection is, if you have a need to use a VPN service you would just connect to that service using that vpn provider website or software directly. 
Maybe if you state the purpose of doing so someone could tell you directly if there is way of doing what your end purpose is or why it would be needed or not by duckie tv.

**Comment by Gabri3l** [comment]
It was just an idea to make it more comprehensive. I figured one could activate the VPN through DuckieTV instead of using some other software making it easier for the user. The app allows to start the download of a tv show through your torrent client automatically, but some people don't want to be tracked while doing so.

I was mentioning PopcornTime because I remember they had an integrated VPN activation (forget about the money making part or else), that feature would be just as nice here. A little option to allow to activate your VPN whichever it is, maybe (just like it's done for the torrent clients) adding a list of supported VPNs that could be activated through the app.

I would want to skip the part where one needs to "connect to that service using that vpn provider website or software directly" and just do it with DuckieTV automatically before starting any download (after setting up the proper config).  I hope I explained myself better this time.

**Comment by lonelyfairie** [comment]
Thanks for clarifying, but if your idea of having a VPN is not to be tracked then I would assume said VPN would be on at all times? So if you just leave duckie tv open that would effectively be the case, the vpn would be on all the time? 

I am in no way affiliated with the app developers but I would assume that the work needed to make this happen would totally out weight the benefit of having said feature on the app.

**Comment by Gabri3l** [comment]
Your assumption is not completely correct. I will try to give you an example, first of all a VPN no matter how good it is may affect the quality of your connection so you might not want it on all the time when randomly browsing or gaming online (just giving you a couple examples). But you might want it on when downloading torrents, so whenever DuckieTV autodownloads a show it would make sure your VPN is active and notify you about it before starting a download or automatically activate it for you when and only when it's downloading.

I know you could actually set it up on your own torrent client directly (and this would solve the problem right away), but not everyone knows how to do it or even is aware of what a VPN is. This feature would not only make it easier to set everything up but also provide some awareness about VPNs.

I know it might require quite some work and I understand the developers point of view, but I though it was worth at least mentioning it.

**Comment by jaruba** [comment]
> I know you could actually set it up on your own torrent client directly (and this would solve the problem right away), but not everyone knows how to do it or even is aware of what a VPN is.

Well.. they'll have to learn, because DuckieTV is not only a local application, it uses the exact same code for the DuckieTV browser plugin too, as interfacing with VPN tech can't be done from a browser plugin, it therefore can't be done by DuckieTV either.

**Comment by Gabri3l** [comment]
I see, makes total sense. Case closed =D
