### ISSUE TITLE
Torrent Search Engines 

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#665]
Can you add some more torrent search engines like:

https://1337x.to
https://www.torrentdownloads.me
https://eztv.ag
https://extratorrent.cc
https://www.limetorrents.cc
http://bitsnoop.com
https://torrenthound.unblockme.al

**Comment by garfield69** [comment]
When #18 is complete you will be able to add your own search engines to DuckieTV, and we will probably provide templates to the most popular ones so you can activate them easily.

However, until ticket 18 is done, we are not planning to make additional *default* search engines available.

Also, a search engine is only useful to most users if the results page that lists the torrents also contains a *magnet* link. This allows the Auto-download feature to operate for instance.

Most of the providers you listed require the user to drill down into the a torrent's details to find the magnet link, and DuckieTV does not currently have a feature to automatically do this (although this may be provided in the future).
