### ISSUE TITLE
Bug appear updating to version 1.1.3

### ISSUE THREAD

**Issue by al3xds** [SchizoDuckie/DuckieTV#667]
Hi, I just updated Duckie tv to this new version. Then I noticed that my favorites series turned to -No favorites-, I reloaded the tab and just two of them reappear, no idea with the other become erased.
![favoritesbug](https://cloud.githubusercontent.com/assets/18041359/14006340/a3cfa358-f16c-11e5-9c37-603eac5f9aef.png)

**Comment by garfield69** [comment]
Wow, thats a weird one.
What version were you on before?
If you click on the (i) icon to bring the *About* page up, and scroll down to the statistics, what are the series, seasons and episodes counts ?

**Comment by garfield69** [comment]
Closing ticket. Will re-open if OP ever replies to my prior post requesting further information.
