### ISSUE TITLE
option on torrent dialogue to change sort order

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#668]
as discussed in this [Reddit](https://www.reddit.com/r/duckietv/comments/4bnu7h/feature_request_timestamps/) thread:

the idea is that some user might like to be able to change the sort order of torrents on the torrent dialogue.

the default for most searchProviders is peers-count but others may not have a sort capability.

so based on the searchProvider knowing if sort is supported, enable a sort menu to re-arrange the torrent results.

**Comment by SchizoDuckie** [comment]
This will be quite a lot of work since you need to have a sort order asc and desc for each search engine * for each torrent client.

While it would definitely be a nice enhancement, i think it will be fragile.

**Comment by roshavagarga** [comment]
@SchizoDuckie - I think a asc/desc would be too much and fragile also. As I mentioned in the reddit thread, the cleanest way to do it is to just tell the current search script to check from a different default link:

kat: adding "age:xxxx" limits the search. The xxxx can be filled only with hour, 24h, week, month and year as parameters. This is directly added to either the search string or as a part of the link you provided after %s.
nyaa: removing the sort=2 in the default search link gives an output based on last upload, while the current sort=2 gives an output based on most seeders.
tpb: current link sorts based on seeders, if 0/7/0 in that link is changed to 0/3/0 it will be sorted by upload time.

So, with an on/off switch in settings, if these 3 links are exchanged with the added input, the torrent search script will get the html from those torrent providers in order of last upload.

**Comment by garfield69** [comment]
OK, I will implement a sort option on the torrent dialogue panel, but with the following restrictions:

reference:
 WebSP = WEB Search Poviders (IsoHunt, KAT, Nyaa, TPB, and torrentz).
 ApiSP = API Search Providers (RarBG, ShowRSS).

* the sort menu will only be supported for WebSP for now.  The ApiSP require special coding I'm not going to get into for now.

* Only the sort orders that are available on **all** the WebSP will be included in the sort menu (*Age*, *Leechers*, *Seeders*, and *Size*).   This provides menu consistency across WebSP and reduces support overhead.

* Only sort list in *Descending* order will be supported, since only a few WebSP have *Ascending* order capability anyway.  This means *Age* will be in newest to oldest order, and *Size*, *Leechers* and *Seeders* will be many to few order.  

Example of W.I.P.
![image](https://cloud.githubusercontent.com/assets/6933240/14133831/017d6692-f6af-11e5-9a3c-ab63d0e750f4.png)

**Comment by SchizoDuckie** [comment]
Excellent. One tip : Instead of the menu you could make the column headers
clickable!
Op 30 mrt. 2016 09:03 schreef "garfield69" <notifications@github.com>:

**Comment by garfield69** [comment]
Only problem with that, is that currently the **Age** sort order is not displayed on the results... we are not manipulating the results we scraped, but are re-issuing the url with the appropriate sort commands included.

I will take a look at all the WebSP to see if they all have the Age data available, and if they do, I can try to make room in the search results table for it, so that we can then use your click-column-headers idea.

I'll update later with the findings.

**Comment by garfield69** [comment]
ok, findings:
nyaa		- age not on first screen
kat		- 1 year, 15 days, etc (plus tooltip = dd mmm yyyy, HH.mm)
tpb		- mm-dd yyyy
isoHunt	- 1 year, 15 days, etc.
torrentz 	- 1year, 15 days, etc (plus tooltip = ddd, dd mmm yyyy hh:mm:ss)
ShowRSS- n/a
RarBG 	- yyyy-mm-dd hh:mm:ss +zzzz

options: @schizoduckie please tick one

- [ ] leave **age off** the torrent dialog results, **keep** the sort menu, **don't** link existing size/seeders/leechers

- [ ] leave **age off** the torrent dialog results, **keep** the sort menu, **link** existing size/seeders/leechers to sort

- [ ] **add age** to search results, modifies as best it fits with either 1 year/1 day display, or date, or n/a, **link all** headers to sort, **keep** sort menu

- [ ] **add age** to search results, modifies as best it fits with either 1 year/1 day display, or date, or n/a, **link all** headers to sort, **Drop** sort menu

- [ ] something else, you need to specify.

**Comment by garfield69** [comment]
To help you decide, here are some screen shots of the torrent dialogue with **un-sanitised**  *Age* data:

**kat**
![image](https://cloud.githubusercontent.com/assets/6933240/14136882/ae720f3a-f6c1-11e5-9253-048130c38c60.png)

**tpb**
![image](https://cloud.githubusercontent.com/assets/6933240/14136850/8b2625ca-f6c1-11e5-8b4d-0adbdb01b2c8.png)

**nyaa**
![image](https://cloud.githubusercontent.com/assets/6933240/14136926/daf96f6c-f6c1-11e5-9007-db426e4ae607.png)

**isoHunt**
![image](https://cloud.githubusercontent.com/assets/6933240/14136870/a47b6ec2-f6c1-11e5-9ad3-a0e02ac97819.png)

**torrentz**
![image](https://cloud.githubusercontent.com/assets/6933240/14136859/99403aa6-f6c1-11e5-84d9-1d424390bf76.png)

**RarBG**
![image](https://cloud.githubusercontent.com/assets/6933240/14136895/bebfc1f2-f6c1-11e5-879e-d66ca84a4844.png)

**Comment by SchizoDuckie** [comment]
I would drop the age. ( It will be a bitch to parse and format, especially with translations, timezone offsets etc) and link the sorting to the column headers :)

That keeps the whole thing generic, consistent and simple. Just add a sorting indicator to the specific column.
