### ISSUE TITLE
[Feature Request] Saving Searches

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#669]
Can you add the option to save manual torrent searches that don’t come back with a result so that DuckieTV will auto download them when they are available.

**Comment by SchizoDuckie** [comment]
DuckieTV torrent integration will only check for search results for shows in your database. It's not a generic torrent downloader.

**Comment by zero77** [comment]
Is there a way you can get it to do that for instance if you want to watch one show in a series rather than the whole series so that you don’t have to add the whole series to your calendar if you just want one episode but the episode isn’t out until next week as an example.

**Comment by SchizoDuckie** [comment]
I can hardly read your sentences, please be more clear on the exact use case.
