### ISSUE TITLE
[Feature Request] Refresh Button

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#671]
Can you add a refresh button to the torrent details page so that if you have downloaded a torrent manually after you click the refresh button it will update the calendar or can you get to automatically do this in the background instead of a refresh button.

**Comment by SchizoDuckie** [comment]
This sounds like something that we don't want to implement, because that's not really how any of this works. 

Can you elaborate on what you expect this to do and why?

**Comment by zero77** [comment]
What I mean is when you download torrents using magnets DuckieTV updates automatically and shows the download progress on the calendar and when it has finished. Although when you download a torrent file it doesn’t seem to do this, is their a way you can get it to do this automatically like when using magnets.

**Comment by SchizoDuckie** [comment]
At the moment that's impossible because duckietv does not know what show to add a new torrent to, or if it even needs to add it to a show, or if it even belongs to a show at all.

**Comment by zero77** [comment]
So DuckieTV only updates the calendar and database automatically, if the TV show is downloaded using the auto download option which only uses magnets. Is this correct.

**Comment by SchizoDuckie** [comment]
Once again I try to understand what you are trying to say but i cannot, so i'll try to answer what i think you're asking.

The auto download function does not only support magnets, but also .torrent files, which it will use when the torrent search engine does not support them, and upload those to your torrent client when needed. If that is what you mean.

**Comment by zero77** [comment]
No it’s not sorry if I’m not making myself clear enough.

But what I’m trying to say is. If I manually download a torrent for instance if the default search engine is RARBG but the torrent is only with KickAss when I manually download it from KickAss. Once it has finished downloading a new torrent it does not update in the calendar or database as downloaded.

**Comment by SchizoDuckie** [comment]
That depends on what you define 'manually download' as.

If you go to an episode and use 'find torrent for this episode' it will work (because then it can attach the torrent to a tvdb_id)

if you open the torrent dialog manually on the left, it will never know what serie or episode the torrent to, that will never work.

**Comment by zero77** [comment]
If the torrent does not automatically download. I select the episode from the calendar and go to find a torrent. Then I select the search engine the torrent is listed in and then I click the magnet link button to the left of the TV show. But when the torrent has finished downloading it does not update in the calendar. This is what I’m defining as manual download.

**Comment by SchizoDuckie** [comment]
Okay. Now i get it.

Next time don't click the magnet button. click the show title in the same
row. That will solve your problem.
The magnet link is there so you could easily copy/paste it to a remote
thing if you have it.

**Comment by zero77** [comment]
Ok thanks I will try that next time.
