### ISSUE TITLE
Download speed graph in torrent client borked

### ISSUE THREAD

**Issue by SchizoDuckie** [SchizoDuckie/DuckieTV#672]
I just noticed this after pulling the latest version:

![image](https://cloud.githubusercontent.com/assets/111710/14053052/0ceb71d8-f2cf-11e5-9698-dc89545195a1.png)

It must have something to do with the offset tweak, because when it stops it does show some progress

![image](https://cloud.githubusercontent.com/assets/111710/14053074/2bfa5508-f2cf-11e5-84a3-7fa04f5346b1.png)

**Comment by garfield69** [comment]
Yeah, that occurs when the current value exceed max-scale.

The DL-speed max-scale is currently set to 1000. 

The dial-gauge vendor code is supposed to handle this, by setting
current-value to equal max-scale when its exceeded.

but clearly that does not work. I'll take a closer look at the vendor code
and see if there is a fix hack I can make.

 

  _____

**Comment by SchizoDuckie** [comment]
Max-scale 1000? :D

dude you are not used to european bandwidth eh?

**Comment by garfield69** [comment]
:-b
I'm not only stuck on low traffic speed, but have a data cap to boot!

**Comment by SchizoDuckie** [comment]
I feel sorry for ya :P

I think we should cap it at about 10MB/s, and after that just max the graph at 100% probably and just use the label for visual speed indication

**Comment by SchizoDuckie** [comment]
Superb! You should send him a p.r. for this
Op 26 mrt. 2016 01:00 schreef "garfield69" <notifications@github.com>:
