### ISSUE TITLE
add-to-favorites panel using return does NOT add first search result

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#674]
when you use the _add-to-favourites_ panel, and type a search query, pressing the **return** key is supposed to add the first search result to the favorites library.
This does _not_ happen.
![image](https://cloud.githubusercontent.com/assets/6933240/14068523/460e33be-f4e2-11e5-8ef6-24d613288fa2.png)

the console shows a _typeError_
![image](https://cloud.githubusercontent.com/assets/6933240/14068530/6570c974-f4e2-11e5-9d1a-00be7a230291.png)

Its a pile of spaghetti. At any one time there appears to be two or three controllers in charge of the panel, referenced under 3 different aliases, _serieslist_, _traktSearch_ and _search_.

_templates/serieslist/tools/adding.html_ contains the ng-submit for the form, calling  _serieslist.selectFirstResult()_.
the _app.routes_ has the controller for _adding.html_ as a built-in one under the alias _search_.

_serieslist_ is the alias for controller _seriesListCtrl_ in charge of _templates/seriesList.html_, but function _serieslist.selectFirstResult()_ references _this.results[0]_. 
_results_ is **not** defined in _seriesListCtrl_.

However, _results_ is defined in the _traktTvSearchCtrl_ controller in charge of _templates/serieslist/trakt-searching.html_ under the alias _traktSearch_.

I tried shifting the _selectFirstResult()_ routine to _traktSearchCtrl_, and changing _serieslist.selectFirstResult()_ to _traktSearch.selectFirstResult()_ in _adding.html_, but this did not appear to work.

Don't know how to proceed from here.

**Comment by SchizoDuckie** [comment]
I agree this thing is a mess.
We'll adress it after this release.

**Comment by SchizoDuckie** [comment]
braindump: 

`document.querySelectorAll("serieheader")[0].click();`
