### ISSUE TITLE
trakt.tv episodes with duplicate tvdb_id are causing problems

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#675]
Unfortunately, Trakt.TV's database is currently riddled with episodes that contain the same _tvdb_id_.
example:
![image](https://cloud.githubusercontent.com/assets/6933240/14089469/8f1834f6-f591-11e5-8e1b-51cedb47b1f3.png)

This causes DuckieTV, while attempting to save these episodes into its database, to reject them with _insert-query-errors_ because we (correctly) set up the Episodes table to have _UNIQUE tvdb_id_ elements.

Fine and good, that's working as designed.

The problem is that the _js/controllers/settings/TraktTVCtrl_ import, the _js/controllers/settings/BackupCtrl_ Import, and the _js/services/TraktTVUpdateService_ daily updates, are all reliant on cascades of promises, and these insert-errors appear to cause disruption in the _.then_ flows, such that the last .then is left pending.

This results, for example, in the Trakt.TV daily update not posting a 'x shows updated' message and not updating the trakttv.lastupdated timestamp.
Also seems to prevent the Trakt.TV import from posting the series:recount:watched broadcast, amoung other things that get left out.

So we need to revisit how we process these Trakt.TV episodes with a view to handling the errors better such that the remainder of the work gets completed.

**Comment by SchizoDuckie** [comment]
I think the best course of action here is to adopt the trakt_id and remove the unique key on the tvdb_id, along with the rest of the app navigation that relies on it being unique, that's the only possibility I see for now

**Comment by garfield69** [comment]
this [Reddit](https://www.reddit.com/r/duckietv/comments/4re9sk/certain_shows_fetching_episodes/) is an example of the duplicate tvdb_id problem. For this user, it seems something happened in the past that caused *Face Off* and *The Bastard Executioner* episode records to be un-linked from their series records. Now whenever a *Refresh* or a *Remove* & *Add Show* is done for these two series, the updates failed because the orphaned episodes records prevent the series from accepting episode updates (due to episode duplicate tvdb_id).    

While the permanent solution would be to adopt the trakt_id and remove the unique key on the tvdb_id, rewriting the code is a large project that will need doing at some point.    

In the mean time, a temporary circumvention will be to add to the migrationService a clean up step to delete orphaned episodes, in a similar way to what is already there for orphaned seasons.

**Comment by garfield69** [comment]
**phase1:**
- [x] add trakt id to series and episodes for crud entities
- [x] correct series imdb id from integer to varchar(20)
- [x] drop unique from tvdb id in series and episodes.
- [x] add trakt id to series and seasons data update in FavouritesService
- [x] populate trakt id by doing a refresh from migration services
- [x] bring trakttv2 endpoints 'search' and tvdb_id' in line with current api syntax
- [x] add trakttv2 endpoint trakt_id (to be used in phase2)


**phase2:** 
will probably need to occur in the release after 1.1.4, because trakt id is a dependant and I dont want to have to code `if trakt id is not null use tbdb id` all over the place.
- [ ] amend trakttv2 and FavoritesService to start using trakt id for searches and updates
- [ ] amend backup to add trakt id to saved data
- [ ] amend import of backup to handle trakt id, or tvdb id if former is not found (in old backups)
- [ ] there is bound to be more gotchas yet to be discovered

**Comment by SchizoDuckie** [comment]
I think we need some form of dual-mode for the transition, or carefully plan the updates not to be left with a whole lot of duplicate data.

since updateEpisodes relies on a key/value map of tvdb_id's and we only add the field in the current migration these will all be null, resulting in possibly loads of duplicates.
![image](https://cloud.githubusercontent.com/assets/111710/16902971/8847c584-4c70-11e6-8d74-d1eedbab34bb.png)

**Comment by garfield69** [comment]
Yes. If you review my previous post in this ticket (the p1,p2 checklist) you will see that I have gone for the phase1 (1.1.4) and phase2 (1.1.5) approach, because I think this might be the more fail-safe approach to adopt.
So phase1 add the trakt_id fields to the tables and populates them by continuing to use the tvdb_id keys, because of the catch22 situation (cant update series/season/episodes using a a trakt_id filed that has not yet been populated)!
In phase2, when the trakt_id data is available in the database, we switch to using trakt_id for everything.

**Comment by SchizoDuckie** [comment]
I don't think we can work that way. You can't say if a user has upgraded to the version we're going to release for phase one, or if they skipped a (or some) versions.

**Comment by garfield69** [comment]
Oh.
So dual mode method it is then.
We check to see if localStorage key 1.1.4refresh exists, and if it does we use the trakt_id for everything, and if it does not exist, we continue using the exisitng processes.

**Comment by SchizoDuckie** [comment]
Seems to be working fine, closing as fixed.
