### ISSUE TITLE
adjust transmission torrent client to support seed-box flavours

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#680]
as raised in this [Reddit](https://www.reddit.com/r/duckietv/comments/4e5ua9/torrent_client_alternative/)

>Hey DuckieDevs, I've just been playing around with justseed.it and was wondering if it could be integrated into DTV alongside the other standard clients.
>There is an API for this type of thing info at justseed.it/api it's over my head, but I'm sure it'd make sense to you guys!!
>it has already been configured to be usable by the android app Transdroid, which is great for one off downloads but I've become somewhat dependent on DuckieTV's automation and trakt integration!
>As an added bonus it has an integrated VPN too.

[API docs](http://justseed.it/api/index.csp)
documentation for the XML output for each call is not yet available, the docs state it will be provided soon.

**Comment by tristenator** [comment]
@garfield69 we (justseed.it) can currently integrate with couchpotato and sonarr using transmission.

however when i configure duckietv to point to the transmission url on justseed.it there is a problem:

address: https://api.justseed.it/transmission/api_key
port: 443

results in duckietv trying to connect to:

https://api.justseed.it/transmission/api_key:443/transmission/rpc

which fails. i would suggest (like couchpotato and sonarr) you add a "folder" or "path" field, which allows the user to optionally specify a custom path, ie:

address: https://api.justseed.it
port: 443
folder/path/whatever: /transmission/api_key

would result in duckietv making requests to:

https://api.justseed.it:443/transmission/api_key

this would make duckietv compatible with transmission-based seedboxes everywhere.

**Comment by garfield69** [comment]
@tristenator  thank you for the info so far.   
Some additional confirmations/corrections,  if you would not mind...

So the justseed.it **api_key** replaces the **rpc** in the standard transmission url?
example:
*url for transmission 2.8.4*
`http://localhost:9091/transmission/rpc`
*url for justseed.it*
`https://api.justseed.it:443/transmission/api_key`   

And because the api_key is unique and private to the account owner, we don't need to enable authorisation headers with a username and password?

So our transmission 2.8.4 set up panel which currently has
```
address
port
username
password
```
would become for justseed.it
```
address
port
api_key
```

Do I have that right?   
Thanks for your feedback.

**Comment by tristenator** [comment]
hey @garfield69 thanks for getting back to me. you are 100% correct, but (and there's always a but with the internets) there are non-justseed.it seedbox considerations to be made as well.

1. i would suggest you 100% preserve your current behaviour if the user does not specify a path, ie: implicitly use /transmission/rpc in the url.

2. but if the user specifies a path then take no implicit action with the url and simply plonk in whatever they specified as the path after the host:port. it is assumed the user knows what they're doing if they specify the path.

3. and independent of all that ^^^ only do the whole authorisation-headers-thing if the user specified the username/password.

some background: seedboxes have many users sharing the same box, so typically the "paths" are specific to a user. and the "paths" can vary between vendors - there is no standard. so if you follow my advice above (based upon how sonarr and cp do it) then you'll cover all the possible bases.

so yeah, on justseed.it the api_key does the all the authentication we need. but other seedbox providers may not only have custom paths specific to each user, but may also require the username/password headers as well.

i hope that makes sense!

ps: oh and just to be clear: i'm not sure how all the other torrent clients behave, this is solely for transmission. but there are many shared seedboxes out there that have to do the custom path thing for all sorts of torrent clients. if you score a copy of sonarr or couchpotato you'll see what they're doing to cater for them.

**Comment by garfield69** [comment]
testing check-list
- [x] connect to a remote windows transmission host and do some torrent activity
- [ ] connect to a transmission seed box and do some torrent activity (justseed.it for example)

todo
- [ ] amend transmission client set up docs to include advanced settings, with example of a typical set up for justseed.it
- [ ] language translations

**Comment by garfield69** [comment]
DuckieTV's transmission client is ready for testing for seed box use. The changes should be included in the next DuckieTV nightly build **04-11-2016** available [here[(https://github.com/DuckieTV/Nightlies/releases) later today.

**Comment by tristenator** [comment]
good job, it works!
