### ISSUE TITLE
Additional space in search causes Masterchef Canada not to be found by autodownload process.

### ISSUE THREAD

**Issue by lonelyfairie** [SchizoDuckie/DuckieTV#681]
I saw this a while back and forgot to report it, for the show Masterchef Canada the autodownload process is searching for Master Chef Canada instead, due to the break in the word "masterchef" it fails to download the available torrents. It is shown correctly on the calendar so I am not sure where that space is coming from. If you search for torrents it will not find any, except if you eliminate the extra space, then it finds the torrents correctly.

**Comment by garfield69** [comment]
Thanks. Your DuckieTV should pick up the correction when it does a SceneName update within the next 24 hours or so.
