### ISSUE TITLE
Ignore Global Quality setting not working on torrent dialogue

### ISSUE THREAD

**Issue by lonelyfairie** [SchizoDuckie/DuckieTV#682]
I have set Masterchef Canada to ignore the Global Quality setting, yet when manually searching it tries to pull 720 torrents. Is this normal?
Does it only work for autodownload torrents?

**Comment by garfield69** [comment]
Well spotted. The manual search does not currently process the series custom *Ignore* flags.   

I will look into having the manual search use the Ignore-flags when the dialogue is first opened, but allow the user to option to *ignore* the Ignore-flags if they want to subsequently.
