### ISSUE TITLE
rarbg search engine does not deliver results in a timely manner as the rarbg.com web site

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#685]
as raised in this [Reddit](https://www.reddit.com/r/duckietv/comments/4efgav/autodownload_append/) stream, it seems that the DuckieTV rarbg search engine does no get given results in the same timely manner that browsing the rarbg.com web site does.

Will do some research (as and when I have the time) to look into this and see what I can find.

**Comment by garfield69** [comment]
screen shots of the discrepancy.
[auto download status](http://i.imgur.com/9dBaO3E.png)   
[rarbg web page](http://i.imgur.com/LSHQwIM.png)

**Comment by garfield69** [comment]
## preliminary research notes:   
The RarBG searchProvider is different from most of the other searchProvders in that is is not a web page scraper (like KAT or PTB), but an API.   
The API server is at https://torrentapi.org.   

### side note:   
DuckieTV does not use a web scraper on rarBG.com, probably because the site employs a check-you-are-not-a-bot which requires users to enter a captcha to prove they are human.   

### terms:   
RarBGAPI = the DuckieTV RarBG searchPRovider service   
RarBGWEB = the RarBG Web site search page   
APIServer = https://torrentapi.org.   

## RarBGAPI documentation:   
The source does not currently have a pointer to any API docs, but I managed to find  http://torrentapi.org/apidocs_v2.txt after a few Googles.   

## preliminary analysis:   
To use the API you first need to get a Token. RarBGAPI saves the token and uses this for the duration of the DuckieTV session.   
In his initial report,  IceMaNTICORE reported that RarBGAPI searches that came up _nothing found_ would continue to stay that way even after the RarBGWEB started showing results. Only by restarting DuckieTV was the RarBGAPI also showing results.   

The docs show that the Token expires after 15 minutes.   
This suggests that RarBGAPI should be doing a get_Token before every search request, rather than only once at the DuckieTV start up.

**Comment by garfield69** [comment]
Found the problem.
Testing with some tracing enabled reveals that when RarBGAPI uses an expired Token to do a search, the response is **result data error Invalid token. Use get_token for a new one!**

**Comment by rarbg** [comment]
you shouldnt set ranked=0 if you have no idea what it will do. i would revert if i were you - noone is moderating the ranked 0 torrents.

**Comment by garfield69** [comment]
according to the docs (assuming that I fond the correct ones at http://torrentapi.org/apidocs_v2.txt)
>By default the api will return only ranked torrents ( internal ) , scene releases + -rarbg releases + -rartv releases.
>If you want other groups included in the results use the ranked parameter with a value of 0 to get them included.
>mode=search&search_imdb=tt123456&ranked=0&token=xxxx

But I admit I did not consider that this meant the results would also include unverified torrents as well.
@rarbg Is there a rank that returns verified torrents from all groups?

If not, then it does not matter for us. The other search providers that DuckieTV plugs into also return a mixture of verified and unverified torrents, so ranked=0 just brings the rarbg search provider into line with the rest.

**Comment by rarbg** [comment]
@garfield69 
your logic seems flawed.
since May 2015 DuckieTV works this way with torrentapi , suddenly you decide to switch it. a lot of users using the rarbg plugin will get disappointed by the switch.

**Comment by garfield69** [comment]
@SchizoDuckie  Do you agree with this assessment?   Do you want me to restore our rarbg searchProvider plugin to only present moderated rarbg+rartv group torrents?

**Comment by SchizoDuckie** [comment]
A  bit late to the party, but yes i'd agree with @rarbg. to prevent unmoderated results we should show only ranked results
