### ISSUE TITLE
Items not marked downloaded for justseed.it transmission client

### ISSUE THREAD

**Issue by ShedDweller** [SchizoDuckie/DuckieTV#689]
not an urgent bug by any means.....

i was using qbitorrent and have switched to the justeedit api connection and both are the same, using nightly updated a few days ago

when downloads finish and are marked 100% they do not get marked as downloaded. once a torrent is complete and stopped duckie loses it's 100% listing on the calendar and shows a spinning magnet icon to show it's found a torrent but it's not downloading 

also if you remove the torrent from the client (it being finished) duckie will actually download it again when it's restarted as it was not marked as downloaded

if you manually mark an episode as downloaded it stays downloaded (green) and duckie does not look for it any more.

Shows completed download - http://imgur.com/gKkDGnN
the next day after restart - http://imgur.com/f6UTWJr - the 3 previously downloaded are now spinning magnets

PS.as you see in the picture the blue seeding bar goes off the screen too and lists as 10000% though that may be the justseedit transmission connection as i never got it using qbittorrent

**Comment by garfield69** [comment]
research:
the transmission client assumes the progress is returned by the transmission host as value needing conversion to a percentage
```javascript
    getProgress: function() {
        return this.round(this.percentDone * 100, 1);
    },
 ```
but it appears that the justseedit transmission host is already returning the value we want, so we anre now multiplying it by 100! throwing off the completed status.

we need to identify which transmission host we are connected to and adjust the progress value accordingly.

**Comment by garfield69** [comment]
as I don't have a justseedit account I cannot readily test this. I hope you will be willing to perform a test or two.   
I have provided a possible fix, which will be available in tomorrows nightly 04-16-2016 (having just missed today's nightly build).   
If you could test this with one torrent, and if it works let me know so I can remove the debug tracing.   
if it does not work, could you press the **F12** key to open the developer tools page, click on the **console** tab to view the log, and report back on what the progress tracing says.   I just need one of them, as long as its greater than zero. They will look something like this:
```
progress before and after 0.0282 2.8 Transmission.js:36
```

Thanks.

**Comment by ShedDweller** [comment]
Sorry, still not permanently marked as downloaded once complete.

FYI the Start, Pause/Stop, Remove torrent controls in duckie work fine.

While downloading the blue still runs off the screen to 10000% You can use the Pause/Stop control but there is no indicator to show it is paused/stopped it still shows blue and runs of the screen.

When finished it goes brown while seeding and lists 100% correctly. BUT do not get marked as downloaded. 

If you Stop the torrent, it goes green and lists correctly at 100% BUT does not get marked as downloaded. 

If you use the Remove torrent button, the torrent is deleted from the client correctly, but when you restart Duckie it re-downloads it that episode.


The progress line reads like this:
progress before and after 52.11818804422268 5211.8
progress before and after 100 100
it does not mention transmission

**Comment by ShedDweller** [comment]
http://imgur.com/VYUS4Ys - shows the 3 states, (blue off the screen, brown, green)

http://imgur.com/LIjLEns - when you remove a torrent form the client (elementry) It should stay listed as downloaded, but it disappears, and gets re-downloaded.

http://imgur.com/fywgFIF - log does not show transmission just the progress

**Comment by garfield69** [comment]
Excellent feedback thank you.
I see now that my handling of the progress value is faulty.
Once that value is handled correctly, all the other functions will start working too.

So regular transmission sends progress as a value between 0.00 and 1.00, but justseedit's transmission sends progress as a value between 0.00 and 100.00.
I just need to correctly identify which transmission version we are connected to and handle the value appropriately.
I'll  mull it over a bit and see what I can come up with.

**Comment by garfield69** [comment]
OK. the next nightly 04-18-2016 should contain a possible fix to try out.
I am still interested in seeing the log, which should have entries similar to this
```
isSeedBox=[false], progress before=[0.3027], after=[30.2]
isSeedBox=[true], progress before=[30.27], after=[30.2]
```

BTW, if during this testing the episode is still not being marked as downloaded automatically, you can do so manually if you want to, by clicking on the episode to bring up the episode-details side-panel, and using the mark-as-downloaded button.

Thanks.

**Comment by ShedDweller** [comment]
SORTED! Awesome work!

http://imgur.com/L9EzquC
 - All those green with (100%) listed are new downloads, nice and neat!
 - The 3 without (100%) have survived being removed from the client AND the same 3 remain marked as downloaded even after restarting Duckie.

http://imgur.com/wgN2aLH
 - AND you have successfully tamed the wild blue downloading bar!!! 
 - also, logs EXACTLY as predicted!

Seriously dude, Fucking awesome work!

**Comment by garfield69** [comment]
@knowair  are you still using transmission and justseed.it ?      
if you are, would you be willing to perform a little fact finding mission for me please?      
I'm looking for what the rpc-version that your seedbox is using. For this I would need you to use your chrome web browser to connect to your transmission server, then press the **F12** button to access the *Development Tools* page, click on the *Network* tab, and examine one of the *rpc* events that crop up regularly as the web browser polls the server.      
Check that the method is for a *session-get* by clicking on the *header* tab and scrolling to the bottom
![image](https://user-images.githubusercontent.com/6933240/29761356-0789ffc8-8c1d-11e7-99c5-26036f5abc6f.png)
If it is not, find another *rpc* event.      
IF found, then click on the *response* tab, select the output and *copy* it to your clipboard. Then *paste* it below.
![image](https://user-images.githubusercontent.com/6933240/29761514-81936ae8-8c1d-11e7-834d-b0ec2a4d5c5b.png)

Thank you.

**Comment by knowair** [comment]
sure i'll take a look later today
ok to do this from the windows standalone version?

**Comment by garfield69** [comment]
>ok to do this from the windows standalone version?      

As long as the standalone version is a *Nightly*. You will not be able to access the *Development Tools* panel using *Standalone 1.1.4*.

**Comment by knowair** [comment]
ok 
this can from dtv new tab

{"arguments":{"torrents":[{"downloadDir":"\/home\/","error":0,"errorString":"","eta":714966,"files":[{"bytesCompleted":111648938,"length":260514190,"name":"only.connect.s13e04.720p.hdtv-norite.mkv"},{"bytesCompleted":0,"length":1544,"name":"only.connect.s13e04.720p.hdtv-norite.nfo"}],"hashString":"ff163defa8b4123d4c1eac5deaa70664b65cd7bc","id":3225,"isFinished":false,"isStalled":false,"leftUntilDone":147269526,"metadataPercentComplete":1,"name":"Only.Connect.S13E04.720p.HDTV.x264-NORiTE","percentDone":42.857142857142854,"rateDownload":0,"rateUpload":0,"sizeWhenDone":260515734,"status":4},{"downloadDir":"\/home\/","error":0,"errorString":"","eta":-1,"files":[{"bytesCompleted":990875137,"length":990875137,"name":"New Blood S01E01 Case 1 Part 1 720p HD.mp4"},{"bytesCompleted":1012633755,"length":1012633755,"name":"New Blood S01E02 Case 1 Part 2 720p HD.mp4"},{"bytesCompleted":1007390644,"length":1007390644,"name":"New Blood S01E03 Case 1 Part 3 720p HD.mp4"},{"bytesCompleted":1050862656,"length":1050862656,"name":"New Blood S01E04 Case 2 Part 1 720p HD.mp4"},{"bytesCompleted":1042389324,"length":1042389324,"name":"New Blood S01E05 Case 2 Part 2 720p HD.mp4"},{"bytesCompleted":1022296326,"length":1022296326,"name":"New Blood S01E06 Case 3 Part 1 720p HD.mp4"},{"bytesCompleted":1029704099,"length":1029704099,"name":"New Blood S01E07 Case 3 Part 2 720p HD.mp4"}],"hashString":"4384620da42449d4be526aef2cd7f31ffca40142","id":3231,"isFinished":true,"isStalled":false,"leftUntilDone":0,"metadataPercentComplete":1,"name":"New Blood - Series 1 (2016) 720p HD mp4","percentDone":100,"rateDownload":0,"rateUpload":0,"sizeWhenDone":7156151941,"status":6},{"downloadDir":"\/home\/","error":0,"errorString":"","eta":552650,"files":[{"bytesCompleted":41719047,"length":142887738,"name":"Only.Connect.S13E04.720p.HEVC.x265-MeGusta.mkv"},{"bytesCompleted":0,"length":1174,"name":"Only.Connect.S13E04.720p.HEVC.x265-MeGusta.nfo"},{"bytesCompleted":0,"length":927678,"name":"Screens\/screen0001.png"},{"bytesCompleted":0,"length":977600,"name":"Screens\/screen0002.png"},{"bytesCompleted":0,"length":616064,"name":"Screens\/screen0003.png"},{"bytesCompleted":0,"length":746391,"name":"Screens\/screen0004.png"},{"bytesCompleted":0,"length":84,"name":"Torrent Downloaded From WWW.TORRENTING.COM.txt"}],"hashString":"bb27bdbf3d734115918fa0ff341117fddae7377e","id":3236,"isFinished":false,"isStalled":false,"leftUntilDone":104213689,"metadataPercentComplete":1,"name":"www.Torrenting.com - Only.Connect.S13E04.720p.HEVC.x265-MeGusta","percentDone":28.571428571428569,"rateDownload":0,"rateUpload":0,"sizeWhenDone":146156729,"status":4}]},"result":"success"}

**Comment by knowair** [comment]
Looks a little different to your screenshots, but i hope its what you need

![dtv1](https://user-images.githubusercontent.com/9417645/29798867-b1cb4098-8c57-11e7-8611-8b337a6d455f.png)

**Comment by garfield69** [comment]
Nearly. but the method you have is "torrent-get" and I am looking for "session-get".      
Try looking at some of the other ones on that list, you are bound to find one.      
Thanks.

**Comment by knowair** [comment]
Spent a little while looking earlier today and again just now and it only ever shows torrent-get for me. 

Could it be because it uses the unique api key rather than user/pw?

my transmission setup

address: https://api.justseed.it
port: 443
path: /transmission/api_key
use authentication: UNchecked

**Comment by garfield69** [comment]
OK. Thanks for taking time on this.      
It is likely that the "session-get" only happens once, during the time a connection between DuckieTV and your seedbox is established.       

So, if you are willing to have one more go, here is what I would like you to try please:      
Using the *settings* panel, click on the *torrent* button to open the *torrent functionality* side panel, then click on the *uTorrent* button.     
Then, open the *Development Tools* page with the *F12* key, and click on the *Network* tab to prepare it for recording.     
Now back at the *settings, torrent* side panel, click on the *Transmission* button, and wait for DuckieTV to auto-connect to your seedbox.      
If you look at the *Network* entries now, you should start seeing those serial-number entries appearing.     
Scroll back to the first one and look for the "session-get". It should be the first or second entry.     
If you cannot find it, then never mind, thanks for trying.

**Comment by knowair** [comment]
Yep that did it! hope tis helps. If you need anything else I'm always happy to help if i can...

![dtv2](https://user-images.githubusercontent.com/9417645/29840164-ef434a14-8cf8-11e7-99e0-aa3ad5564e19.png)

COPIED TEXT FROM Network>Session-get>Response tab.

{"arguments":{"alt-speed-down":50,"alt-speed-enabled":false,"alt-speed-time-begin":540,"alt-speed-time-day":127,"alt-speed-time-enabled":false,"alt-speed-time-end":1020,"alt-speed-up":50,"blocklist-enabled":false,"blocklist-size":0,"blocklist-url":"http:\/\/www.example.com\/blocklist","cache-size-mb":4,"config-dir":"\/home\/.config\/transmission","dht-enabled":true,"download-dir":"\/home\/","download-dir-free-space":71384023040,"download-queue-enabled":true,"download-queue-size":5,"encryption":"preferred","idle-seeding-limit":30,"idle-seeding-limit-enabled":false,"incomplete-dir":"\/home","incomplete-dir-enabled":false,"lpd-enabled":false,"peer-limit-global":200,"peer-limit-per-torrent":50,"peer-port":51413,"peer-port-random-on-start":false,"pex-enabled":true,"port-forwarding-enabled":true,"queue-stalled-enabled":true,"queue-stalled-minutes":30,"rename-partial-files":true,"rpc-version":15,"rpc-version-minimum":1,"script-torrent-done-enabled":false,"script-torrent-done-filename":"\/home","seed-queue-enabled":false,"seed-queue-size":10,"seedRatioLimit":2,"seedRatioLimited":false,"speed-limit-down":100,"speed-limit-down-enabled":false,"speed-limit-up":100,"speed-limit-up-enabled":false,"start-added-torrents":true,"trash-original-torrent-files":false,"units":{"memory-bytes":1024,"memory_units":["KiB","MiB","GiB","TiB"],"size-bytes":1000,"size-units":["kB","MB","GB","TB"],"speed-bytes":1000,"speed-units":["kB\/s","MB\/s","GB\/s","TB\/s"]},"utp-enabled":true,"version":"2.84 (14307)"},"result":"success"}

**Comment by garfield69** [comment]
Fantastic. Thank you.

**Comment by garfield69** [comment]
@knowair  So a heads up notice for you ;-)      
If (when) you ever upgrade to *DuckieTV 1.1.5* or to a *Nightly* after today, you will want to visit the *Transmission Integration* side-panel in *Settings, Torrent*, and scroll down to a new check-box labelled *%x100*. It should be ticked by default, but because you are using *justseed.it*, you will want to un-check it and *Save & Test*.      
This will restore the progress bar back to *0 to 100%* instead of *0 to 10000%* if you leave it ticked ;-)

**Comment by knowair** [comment]
thanks for the heads up!
