### ISSUE TITLE
disconnect the downloaded from watched coupling

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#693]
As raised in this [Reddit](https://www.reddit.com/r/duckietv/comments/4d06g2/marking_a_video_viewed_but_not_downloaded/),
examine what dependencies there are for the current pairing of the downloaded and watched states.   

Right now, if you mark-as-watched, the mark-as-downloaded is also set.   
And if you mark-as-not-downloaded then the mark-as-not-watched is set.   

The request is for the two states to not be paired.   

Examine the source and see if uncoupling will break anything. If it doesn't then remove the coupling.

**Comment by zero77** [comment]
Instead of removing coupling completely can you add the option to turn it on or off.
As it can be quite useful.
