### ISSUE TITLE
Series name inexplicably turned russian

### ISSUE THREAD

**Issue by baliame** [SchizoDuckie/DuckieTV#694]
I just opened DuckieTV and this happened. I have no idea what to do with this.

![screen shot 2016-04-24 at 13 55 32](https://cloud.githubusercontent.com/assets/2102965/14767406/6091cf6e-0a24-11e6-85ee-e8d670216441.png)
![screen shot 2016-04-24 at 13 56 02](https://cloud.githubusercontent.com/assets/2102965/14767407/60a1bf28-0a24-11e6-95ae-e54ca4d5654f.png)

Only these two options are selected in the Language settings.

**Comment by Js41637** [comment]
Yeah I hate it when it does that, this is an issue with Trakt.tv, someone fucked up the data and series names can change language even though it's not meant to, luckily DuckieTV can handle this without a problem but you will have to wait for someone to fix it and then when DuckieTV auto updates with Trakt.tv again, it should be fixed but it might be a day or too.
It is unfortunate this happens but there isn't anything we can about it.
