### ISSUE TITLE
Not "Tracking Tv Show" on Calender

### ISSUE THREAD

**Issue by ShenLun** [SchizoDuckie/DuckieTV#695]
HI

First of all Awesome Program. This is my first real issue.

We have both Topgear US and The Musketeers. Both are known shows and are coming up on track.tv However They are not coming up in DuckieTV (BrowserAction mode).

I just found The Musketeers on a nother site and I have come across it for download (episode 3 today). Topgear US Airs Today and it hasn't (as of this moment picked it up at all on the calendar). Is their also a viewing mode which will allow me to "fit the calendar to screen?" (not essential just curious). . Is their away I can fix this? ie email track.tv  etc
![duckie calender](https://cloud.githubusercontent.com/assets/14035355/14806428/34263512-0bb6-11e6-98a1-47eca9db777a.jpg)

Kind Regards
ShenLun

**Comment by garfield69** [comment]
OMG  I've just now discovered this ticket! Sorry no one from the team has replied to you before now!       
You may find this [wiki](https://github.com/SchizoDuckie/DuckieTV/wiki/How-to-make-corrections-to-shows-on-DuckieTV) useful.     
If you still have questions about this then please ask, I promise a quicker reply next time :grin:
