### ISSUE TITLE
uTorrent managing issues [Win10]

### ISSUE THREAD

**Issue by KonradDeskiewicz** [SchizoDuckie/DuckieTV#699]
Hi,

After pairing with DuckieTV I cant start any of my torrents. All are set in stop mode and no matter if I try to start seeding in uTorrent or in DuckieTV after 2 secs it's stopped again.
Using latest stable DuckieTV & uTorrent.

**Comment by garfield69** [comment]
Go to the DuckieTV *Settings,Torrent* sidepanel, and click on the *Disable Auto-Stop*
![image](https://cloud.githubusercontent.com/assets/6933240/15520615/57f9fc2e-225b-11e6-8344-bd209dd025f1.png)
This will prevent DuckieTV from automatically preventing seeding :-)

**Comment by garfield69** [comment]
Closing ticket on the assumption that disabling the torrent-auto-stop was the solution the the problem reported by the OP. If the OP reports otherwise we can reopen the ticket.
