### ISSUE TITLE
Torrent Settings for Show not respecting terms

### ISSUE THREAD

**Issue by Zxurian** [SchizoDuckie/DuckieTV#700]
Under "Torrent Settings for <show>" I have `1080p web-dl h.264`
however it grabbed the the torrents of `<show>.S05E07.1080p.HDTV.X264-DIMENSION[rarbg]` instead of the also available `<show> S05E07 1080p WEB-DL DD5 1 H264-RARBG`

**Comment by garfield69** [comment]
If you are using DuckieTV 1.1.3 then you may wish to upgrade to the development Nightly which you can download from [here](https://github.com/DuckieTV/Nightlies/releases), which includes fixes in the torrent search code.
Let us know if you are still having problems on the latest DuckieTV nightly, and we will look into this further.
Thanks.

**Comment by Zxurian** [comment]
roger, i'll update and let you know

**Comment by garfield69** [comment]
closing ticket with the assumption that switching to a nightly resolved this issue for the 
OP. If the OP should report otherwise we can reopen the ticket.

**Comment by Zxurian** [comment]
sorry, downloading the new nightly did find torrents with the proper global terms now
