### ISSUE TITLE
Duckie keeps making new instances of its icon in the top OS X title bar.

### ISSUE THREAD

**Issue by TheTestingGuys** [SchizoDuckie/DuckieTV#701]
Once you launch DuckieTV on a Mac (OS X El Capitan for me) it will appear in the top title bar, (the little duck icon on the right) to notify you it's running and you can right click on it to get the menu, etc.

As DuckieTV runs, it will continuously generate more and more icons in the top bar.  All of them working.  Only one instance if DuckieTV is running though, so if you choose quit on any of the icons it closes the app.  It needs to not keep generating new icons.  

Note - I think this partially has to do with minimizing the app.

![duckietv bug](https://cloud.githubusercontent.com/assets/1189281/15548455/4e7858b0-225d-11e6-9e77-fc990a0fd17a.png)

**Comment by garfield69** [comment]
If you are using DuckieTV 1.1.3 you may wish to upgrade to the latest development nightly by downloading from [here](https://github.com/DuckieTV/Nightlies/releases), which contains fixes for the system tray code on max and linux.
If you are still seeing duplicate systray icons with the latest DuckieTV nightly then please let us know so we can look into this further.
Thanks.

**Comment by TheTestingGuys** [comment]
Thank you very much!
  
  
  

  
  
>

**Comment by garfield69** [comment]
closing on the assumption that switching to nightly resolved the duplicate systray icons that the OP reported. If OP should reply that it is still happening then we can reopen the ticket.
