### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by arbel** [SchizoDuckie/DuckieTV#702]
Hello,

I"m a UX designer, and i've spotted a number of issues with duckieTv, I love the app but I feel it could be better. Are you open to a redesign?

**Comment by Js41637** [comment]
You're free to submit pull requests, would probably help if you could elaborate a bit more?

**Comment by arbel** [comment]
we'll I would like to provide you with a new visual design (not coded) and
hope you would work with me on it to give the product a facelift, my main
question is are you interested in an updated design and will be willing to
implement it. Assuming you like it =)

**Comment by Js41637** [comment]
I'm not too sure, as you can probably tell development on DuckieTV is currently non-existant apart from the work garfield69 is doing here and there. Me and SchizoDuckie have kinda taken some time off with SchizoDuckie being very busy of late with other projects and IRL. However we are planning on coming back soon.

Personally I've been thinking that when we come back from hibernation that we should do a lot of refactoring of code and touch up the UI however I am keen to see what you are suggesting.

**Comment by SchizoDuckie** [comment]
I'm not really looking for a complete redesign to be honest, as that usually has serious implications and large amounts of work to redo things that the design does not take into account.

However, as @Js41637 says, touch ups and refinements and ideas and general inspiration and pointers are very welcome.

Bear in mind though, the current DuckieTV UI works the same on all platforms, and has no features hidden in rightclick/long-press menus, whether it's touch or Desktop. That's not an easy feat to incorporate into a design, but I'd like very much to keep it that way.
