### ISSUE TITLE
qbitorrent 3.2+ error

### ISSUE THREAD

**Issue by arismac** [SchizoDuckie/DuckieTV#703]
Hi, on the left of duckie the icon is green but when i press to see whats happening it says connection fails and it retries every 5 min to no avail. can u help?

**Comment by garfield69** [comment]
Please have a look at this [wiki](https://github.com/SchizoDuckie/DuckieTV/wiki/Setting-up-qBitTorrent-3.2-with-DuckieTV-1.1.2) which should guide you to setting up pairing of qBitTorrent with DuckieTV.

If you have followed this guide, and are still unable to get a connection, then we are going to need some diagnostic information from you to proceed further.

From the main DuckieTV page press the **F12** key to open the development tools panel, click on the **console** tab to view the log, and look for messages related to qBitTorrent.
If you are on a windows system, press the **Print Screen** to take a snapshot of the console window, and use **Ctrl v** to paste the picture into the empty box below here. 
Then from the main DuckieTV page click on the **(i) icon** on near the bottom left, to open the *About* page, scroll down to the statistics section, and print-screen that section too.
Thanks.

**Comment by garfield69** [comment]
Closing ticket on the assumption that the OP took a second look at the wiki and resolved the problem. Should the OP ever reply in the contrary then we can reopen the ticket.
