### ISSUE TITLE
pass the series title as a label on torrent/magnet loading to torrent host

### ISSUE THREAD

**Issue by fa7ad** [SchizoDuckie/DuckieTV#705]
Is it possible to make the Show's name a label when auto-downloading a torrent. I use labels to put different shows in different directories, I think there are more people than just me that do this.

**Comment by garfield69** [comment]
Requirements:
- [ ] Flag torrent clients that support this feature
  - [ ] deluge
  - [ ] Ktorrent
  - [ ] qBittorrent 3.2+
    - API6 Pre 3.3.1
    - API7 3.3.1+
  - [ ] qBittorrent pre3.2
  - [ ] rTorrent
  - [ ] Tixati
  - [ ] Transmission / Vuze
  - [ ] uTorent API
  - [ ] uTorrent WEBUI
- [ ] Create an isLabelSupported function in base torrentclient that's false
- [ ] add 'torrenting.label' setting in SettingsService, default to false 
- [ ] Implement option in *Settings,Torrent* that sets if a Serie's title should be passed as a Label to clients that support it
- [ ] Implement setting label for each client API that supports it, when torrenting.label is true
  - [ ] deluge
  - [ ] Ktorrent
  - [ ] qBittorrent 3.2+
    - API6 Pre 3.3.1
    - API7 3.3.1+
  - [ ] qBittorrent pre3.2
  - [ ] rTorrent
  - [ ] Tixati
  - [ ] Transmission / Vuze
  - [ ] uTorent API
  - [ ] uTorrent WEBUI
- [ ] Overwrite isLabelSupported for clients that support it (as indicated above)
- [ ] add translation support for settings

**Comment by garfield69** [comment]
@fa7ad  If you are interested in trying out this feature, download the latest nightly when it becomes available in about 14 hours or so from the time of this post at https://github.com/DuckieTV/Nightlies/releases/tag/nightly-10262016.
You will find the switch in the DuckieTV *Settings, Torrent* side panel, under the *Torrent Label* section, assuming that you are using qBittorrent with API7 (which became available with version 3.3.1 onward).

**Comment by garfield69** [comment]
complete.
