### ISSUE TITLE
DuckieTV grabbed multiple torrents for same episode

### ISSUE THREAD

**Issue by Zxurian** [SchizoDuckie/DuckieTV#706]
running v20160525
Series set to 
![img](http://i.imgur.com/Ci0GKsx.png)

found it grabbed the same episode multiple times
![img](http://i.imgur.com/bVHDjDG.png)

**Comment by garfield69** [comment]
Hmm. Odd problem that I cannot replicate with uTorrent on my win7 platform.
What torrent host are you using, which platform are you running on?
can you also check that the episode in question has been marked as downloaded?
(If it has not been, you can manually mark it as downloaded, this will stop AD from downloading it again).
and finally, I could use a look at your statistics section. So could you click on the DuckieTV *About* icon (i), scroll down the sidepanel till you hit the statistics section, and screen capture (**Print Screen** key on windows) and the **Ctrl v** (paste) into the empty box below. Thanks.

**Comment by garfield69** [comment]
additional questions: has it done this for any other series or episodes, or just this one time for that particular episode?

**Comment by garfield69** [comment]
OK, the duplicate downloads of GoT are a result of the problem reported in ticket #707.
When a download completes, and the episodes is not marked as downloaded automatically by DuckieTV, then the next time DuckieTV is started, (or reset at midnight for the calendar roll over), then if the episodes falls within the new auto-download period it will be submitted for download again. And if the torrent chosen is different from the original, (Or if transmission's original torrent has already been deleted), then transmission will effectively download the episode again.
