### ISSUE TITLE
Not marking a title as downloaded when torrent finishes

### ISSUE THREAD

**Issue by Zxurian** [SchizoDuckie/DuckieTV#707]
Calendar shows as such
![img](http://i.imgur.com/S7pJnyW.png)

I've confirmed that Person of Interest S05E09 & S05E10 were grabbed by DuckieTV, and passwd to my Transmission box. They downloaded successfully, however they're still marked as not having been downloaded.

I do have sickbeard running processing on the transmission download folder, not sure if that will affect it or not.

Side Note: is there a reason the 26 is in yellow?

**Comment by garfield69** [comment]
OK. so we appear to have a problem with DuckieTV recognising that Transmission on your other box has completed a download. 
While I do some research, you are going to want to manually mark the episodes as downloaded in order to stop the auto-download from retrying and potrentially causing what you reported in ticket #706.

>I do have sickbeard running processing on the transmission download folder, not sure if that will affect it or not.

I don't think this should be a problem, as long as sickbeard is not deleting the torrent in Transmission before DuckieTV gets a chance to receive the 100% complete data packet from Transmission.

>Side Note: is there a reason the 26 is in yellow?

Well that's odd. The current day is shown in yellow on the calendar. 
So assuming that your PC has the correct date and it is not the 26th on may, then that implies that DuckieTV has not gone through a midnight reset yet. That is not a good sign.

can you show me a snapshot of your DuckieTV settings,transmission integration sidepanel.
Also, what platform is the box you are running transmission on, and what version of transmission are you running?

**Comment by garfield69** [comment]
Also, I am interested in whether there might be long periods of time when DuckieTV is up but Transmission is not.
 What is the up-time of the DuckieTV PC and the MediaBox with Transmission? Are they both up all the time with DuckieTV and Transmission running all the time, or are there periods when Transmission or the MediaBox is down while DuckieTV is up and running? If so, how long might that period of disconnection be?
How often do you shutdown DuckieTV, or the PC it is running on?

**Comment by Zxurian** [comment]
> can you show me a snapshot of your DuckieTV settings,transmission integration sidepanel.
Also, what platform is the box you are running transmission on, and what version of transmission are you running?

same snapshot as provided here: https://github.com/SchizoDuckie/DuckieTV/issues/706#issuecomment-222889614


> Also, I am interested in whether there might be long periods of time when DuckieTV is up but Transmission is not.
What is the up-time of the DuckieTV PC and the MediaBox with Transmission? Are they both up all the time with DuckieTV and Transmission running all the time, or are there periods when Transmission or the MediaBox is down while DuckieTV is up and running? If so, how long might that period of disconnection be?
How often do you shutdown DuckieTV, or the PC it is running on?

Transmission Client is running on a Synology NAS (been using this for over a year, no issues with it acting as a torrent client). DuckieTV is running on a Windows 10 Pro box that acts as a server. Both are up 24/7.

**Comment by garfield69** [comment]
OK, thanks for the info so far.

The focus at the moment is on determining why DuckieTV is not automatically setting the downloaded flag when transmission completes a download. 

BTW, what is the version of Transmission that is running on the NAS? (eg 2.92 for windows)

It would be useful if you could make some observations of an episode when it is being downloaded.
If you click on an episode in the DuckieTV calendar, you get a side-panel that shows episode details, and if the episode is being downloaded by Transmission via a DuckieTV auto-download request, then you will see a colour coded progress bar.
![image](https://cloud.githubusercontent.com/assets/6933240/15722569/7bff0ab4-2892-11e6-8a02-a220ee9a8dfe.png)
it should be:
**red** for !remote.torrent.isStarted() && remote.torrent.getProgress() < 100 *[paused or stopped]*
**blue** for remote.torrent.isStarted() && remote.torrent.getProgress() < 100 *[downloading]*
**green** for !remote.torrent.isStarted() && remote.torrent.getProgress() == 100 *[download completed]*
**orange** for remote.torrent.isStarted() && remote.torrent.getProgress() == 100 *[seeding]*
**green** for remote.isDownloaded [finished]*

Does an episode ever go green for you after a download is complete?

When the download is complete the *mark as ?* button's icon should turn green
![image](https://cloud.githubusercontent.com/assets/6933240/15722690/fe2e5878-2892-11e6-9dd9-cec71ae3e6fc.png)
do you get this?

**Comment by Zxurian** [comment]
> BTW, what is the version of Transmission that is running on the NAS? (eg 2.92 for windows)

2.9.2 (14714). It's provided by the Synology Package Manager, but that runs off of a linux core (I can look up the exact distro if need be), so it's linux version.

So I clicked on Find a Torrent, then clicked on the Magnet con.
The torrent was added to Transmission, and it started right away, however this is what DuckieTV showed
![img](http://i.imgur.com/6KRqyd5.png)
Also, if I click on the Transmission icon in the left nav bar, the right shows "Torrrents found: 0", even though there are multiple torrents within Transmission.

**Comment by Zxurian** [comment]
so I decided to mark this as another comment. On a Whim, I quit DuckieTV, restarted server box, reran duckieTV, and it seems it's identity issues are taken care of. yellow number moved to current date (June 1), and it can now see all torrents from Transmission, as well as properly marking torrents as downloaded.

Edge case where it didn't line up?

I'd say for now to mark it as closed, and if it pops up again, I'll add a comment to this issue.

**Comment by garfield69** [comment]
Oh wow. OK then. Good job!

Closing ticket, pending re-occurrence, at which time we will probably need to enable some deep debugging traces to figure out where it got pear shaped during first-time initialisation/setup.

**Comment by Zxurian** [comment]
so... just logged into DuckieTV today, and it's got the same issue where the date isn't reflecting current date. ie, 1 is yellow instead of 4. think it's related, or should I create a new issue?

**Comment by garfield69** [comment]
new issue please.
