### ISSUE TITLE
adding a global search string option.

### ISSUE THREAD

**Issue by Zxurian** [SchizoDuckie/DuckieTV#708]
![img](http://i.imgur.com/9V9fQxI.png)
Global includes have `web-dl` in it however it's finding torrents that don't have that in it resulting in false positives

**Comment by garfield69** [comment]
The global includes list acts as an OR list.
so the list reads (1080p OR web-dl OR h264).
If you want a AND list, then use the series specific search string. words in that list reads (word1 AND word2 AND etc).
Also, any words in the global Exclude list are overridden if they are in the series specific search string.

**Comment by Zxurian** [comment]
Is that actually said anywhere in the program? (I could have missed it), as that didn't occur to me at all when using the interface.
This may be opinion, but I think that's a little disingenuous to what users expect. You have a global include list (and "include list" implies that all terms are "included", at least to me), and then you have individual series include list. There's _also_ a setting within each show settings to Ignore global include list, which implies that the global include is always in use unless explicitly stated in the series details.

If you've got multiple shows, all following the same format, ie, `1080p web-dl h264`, then you're saying that you'd have to go into each show individually and set that search string, which defeats the purpose of the global include list and wouldn't make DuckieTV as nearly as streamlined as it's meant to be.

It would make more sense (granted, still opinion), to have the global include list at as a master include, adding in individual series includes where specified. Something similar to `allFilters = (!seriesSkipGlobal() ? globalFilters : []) + seriesFilters`

**Comment by garfield69** [comment]
>Is that actually said anywhere in the program?

The Global description in settings:
![image](https://cloud.githubusercontent.com/assets/6933240/15720362/275bb2f0-2888-11e6-94bb-2a7e100a50a1.png)
may not explicitly give an example with OR and AND, but I assumed that the phrase *restrict your torrent search results to those titles that include* **any of the words** *you enter below* implied the list acted as an OR list.

We could change *any of the words* to *any* **one** *of the words* to make that clearer perhaps.

>and then you have individual series include list.

Ah no, we have a individual series custom search string. I don't think we refer to it as a series include list anyplace.
I thought the use of *list* would be enough to distinguish its purpose as opposed to *string*.

Feedback is always welcome, and I accept that there is ambiguity, and there is always plenty of room for improvement.

**Comment by Zxurian** [comment]
boo on me for not reading the specifics, (granted, this is still opinion) I would suggest a wording or title change, and I hope more people chime in so it's not just me, but "Global Include List" to me means include everything (AND). While reading the sentence below changes that, since the sentence does imply (OR), the title implies the opposite and it might be a little confusing.
For clarity, the Global Exclude List would be an (OR) 

(coming from a programming background), So using my example of wanting to have all shows use the same "custom search string" as it's called. I can't see any easy way to have multiple shows all use the same search string without individually going into each shows settings and copy/pasting. Maybe it needs to be a separate "global search string" variable?

I can see use cases of the Global Exclude List, like `eztv` if you wanted to avoid all releases by them, but I can't see any use case for a Global Include List that is an OR comparison. Does anyone have an example where you'd want to auto search for listings that include <term1> or <term2>?

**Comment by garfield69** [comment]
Here is my personal search configuration, just as an example:
GIL=(ettv rartv rarbg killers rmteam shaanig sharpysword condo qman proper internal repack byteshare)
GEL=(xvid 480p 720p 1080p dvdscr preair fleet trailer)
Series_Search_String=(720p x265)

**Comment by Zxurian** [comment]
this could be a case of YMMV then, as the majority of mine use the same, and only a few are different.

Looking at your example, it looks like you'd have to go back and add another entry GEL each time a false positive came through, which seems inefficient to me. If there was a global "must have all these" option, instead of a global "don't include any of these", then you'd remove that need, and not have to worry about any false positives.

**Comment by garfield69** [comment]
A variation on this theme, is that instead of adding another separate *global search string* option, we just add a switch next to the GIL settings, that changes the behaviour of the GIL list.
This way, the default could remain an OR list, and for those that prefer it, the list could act as an AND list.

An additional improvement I am considering, is that with the GIL in OR mode, we assign to each torrent in the search results the number of words found in the GIL, and sort the results so that the torrent with the most hits rises to the top.

**Comment by Zxurian** [comment]
I like that idea. Puts the choice into the user whether they want to OR or
AND.

Also the torrent weighting is also a nice touch.
