### ISSUE TITLE
"Trending Shows on Trakt.TV Click a show to add it to your favorites" never loads

### ISSUE THREAD

**Issue by shellig** [SchizoDuckie/DuckieTV#713]
"Trending Shows on Trakt.TV Click a show to add it to your favorites" never loads

**Comment by SchizoDuckie** [comment]
![image](https://cloud.githubusercontent.com/assets/111710/16098599/23a6c0ec-3354-11e6-8d6f-926e5e11af6f.png)
Fixed by trakt soon as well.
