### ISSUE TITLE
uTorrent connect button (after clear authorisation) not working [settings, utorrent integration panel)

### ISSUE THREAD

**Issue by shellig** [SchizoDuckie/DuckieTV#714]
Magnet link not working, tried clearing authorization, no dialog box to pair. Utorrent 3.4.7

**Comment by shellig** [comment]
Actually, I have a green dot next to the icon.  Just not letting me download in DuckieTV or download magnet.  Confused.

**Comment by garfield69** [comment]
press the **F12** key to open the development tools page, and click on the **console** tab to view the log. any error messages ?
First thing you can try is exiting DuckieTV and starting it up again.

**Comment by garfield69** [comment]
FYI. The green dot represents a connection. A bit like you having successfully rung someone on the phone and the other end has picked up. It does not mean however, that DuckieTV and uTorrent are communicating. Much like you may say something on the phone, but the other chap is not replying.

**Comment by shellig** [comment]
Object Failed to load resource: http://localhost:10000/gui/pair?name=DuckieTV&callback=angular.callbacks._1 the server responded with a status of 401 (Unauthorized)

**Comment by garfield69** [comment]
Definitely need a new token then.
I know you have tried this before, but I am going to have try an alternate way of creating a new token.
Please go to the DuckieTV **Settings,uTorrent Integration** panel, and click on the **Clear uTorrent Authorization** button.
![image](https://cloud.githubusercontent.com/assets/6933240/15877729/c30de5ca-2d69-11e6-85f6-6a805c86b03d.png)
Then shutdown and restart DuckieTV.
You should then get the uTorrent Host pop up asking you *do you want to allow access?**. 
![image](https://cloud.githubusercontent.com/assets/6933240/15877850/91ec120e-2d6a-11e6-9373-8bcaf6c3ee9d.png)

Let me know how that goes for you.

Meanwhile,  I will work on a fix to the **Connect to uTorrent** button which does not seem to me to be working as intended.

**Comment by shellig** [comment]
I do not get that option.  I click this button and nothing seems to happen.  I have never seen the host pop-up.  I wonder if there is a setting blocking that in Chrome? 
![image](https://cloud.githubusercontent.com/assets/19787673/15879062/8c2ad200-2cee-11e6-8be0-12bf1e600df4.png)

**Comment by garfield69** [comment]
Time for some basic info gathering. 

What version of DuckieTV are you using, and for what platform ?

 

  _____

**Comment by shellig** [comment]
So I had edited my entry with some of that but I can be more specific. Google Chrome Version 51.0.2704.84 m, uTorrent 3.4.7 build 42330, DuckieTV 1.1.3.  I had downloaded a Dev version DuckieTV yesterday or the day before because of the Trakt.TV issue but am not using it now.

**Comment by garfield69** [comment]
OK. The previous instructions were for the DuckieTV standalone version. Disregard.

I am was using chrome browser version **51.0.2704.79 m** and I also am seeing the problem you have reported. 
However, I then when to the chrome hamburger icon and selected **Help, About Google Chrome** and updated to version **51.0.2704.84 m**.

then I started the DuckieTV chrome extension, and clicked on the utorrent icon on the left of the main DuckieTV page.
When I clicked on the **Clear uTorrent Authorisation** this time, I got the uTorrent **do you want to allow access?** pop up.
![image](https://cloud.githubusercontent.com/assets/6933240/15879406/0cb0ff7e-2d78-11e6-877e-81259767664e.png)

Also, for me, the pop up did not appear on top, I had to click the uTorrent Host on the task bar which was flashing, to make it bring the pop up to the front.

so try this and let me know how you go.

**Comment by shellig** [comment]
Updated chrome closed everything started again, and no luck.  No pop up.  Cleared browsing data and tried again, still no luck.  I had even allowed pop-ups in case that was blocking something but no. (The magnet links are working again, though).

**Comment by shellig** [comment]
![image](https://cloud.githubusercontent.com/assets/19787673/15879963/e4aa2d9c-2cf6-11e6-92ca-25a08a55c528.png)

**Comment by garfield69** [comment]
Hmmm. curious.
OK, so the only difference between me and you is that I am on win7 and you are on win10.
We both use the same uTorrent version, and the same chrome version.

Alright then, let approach this from another angle. There is an alternate way to access uTorrent, using the WEB UI interface instead of the API.
It has the same functions, but does cost a little more CPU to use.

take a read of this wiki https://github.com/SchizoDuckie/DuckieTV/wiki/Setting-up-uTorrent-3.4.2-Web-UI-with-DuckieTV-1.1.2 and have a go at that.

This should at the very least restore you access to uTorrent via DuckieTV.

**Comment by shellig** [comment]
No idea what is going on.  Same behavior there. 
![image](https://cloud.githubusercontent.com/assets/19787673/15881084/357d6536-2d01-11e6-9817-cbcfeb0107f6.png)

**Comment by shellig** [comment]
Oh. I did not follow directions.  Let me try the actual WebUI instructions :(

**Comment by shellig** [comment]
Sigh - did not work in Chrome. 
![image](https://cloud.githubusercontent.com/assets/19787673/15881248/7d2ba798-2d02-11e6-937a-4571f4fb221f.png) or in stand-alone application.  
![image](https://cloud.githubusercontent.com/assets/19787673/15881278/add82bd2-2d02-11e6-8d7a-cc0b0d12e3a2.png)

**Comment by shellig** [comment]
closed and reopened DuckieTV multiple times and it finally successfully connected with the WebUI in Chrome (and in the standalone).  One issue, especially if we post the log, it has the username:password embedded in the error message for the localhost query.  I did not want to paste what mine are here and could not get it to error again when I changed to "username" and "password" to show you.

**Comment by shellig** [comment]
![image](https://cloud.githubusercontent.com/assets/19787673/15881608/50ef0776-2d05-11e6-8b7c-626243003030.png)

**Comment by garfield69** [comment]
So to confirm where you are at then.
You are back on the DuckieTV 1.1.3 chrome extension, and have successfully connected to uTorrent using the WEB UI client, and it all working now?

**Comment by shellig** [comment]
yes :)  I just included that last screenshot so you knew there might be a security issue if people share screenshots with error messages when they are at that point :)  Thanks for your help!

**Comment by garfield69** [comment]
\o/
Thanks for the heads up, I'll take a look at what can be done about that error message content.
And well done to you for patiently sticking with it till you got it going. Most other would have given up.
