### ISSUE TITLE
Mac OS X bug in app

### ISSUE THREAD

**Issue by recoi1er** [SchizoDuckie/DuckieTV#716]
Scheduled many releases but they never auto add to my client, transmission which is all setup.

![screen shot 2016-06-07 at 7 57 59 pm](https://cloud.githubusercontent.com/assets/19810634/15881375/55c72ad2-2cea-11e6-90dc-a4a4aeffcdef.jpg)
![screen shot 2016-06-07 at 7 59 00 pm](https://cloud.githubusercontent.com/assets/19810634/15881385/619aa622-2cea-11e6-82f3-528914a0839b.jpg)
![screen shot 2016-06-07 at 7 58 33 pm](https://cloud.githubusercontent.com/assets/19810634/15881382/61960374-2cea-11e6-96aa-894b1779fefe.jpg)
![screen shot 2016-06-07 at 7 58 11 pm](https://cloud.githubusercontent.com/assets/19810634/15881384/61978172-2cea-11e6-8f78-db1a5791ccf7.jpg)
![screen shot 2016-06-07 at 7 58 06 pm](https://cloud.githubusercontent.com/assets/19810634/15881383/61964532-2cea-11e6-9369-08dee68d258b.jpg)

**Comment by garfield69** [comment]
Can we wait first to see what happens when you upgrade to a nightly as per your #715 ?
If you still have issue after, then let us know and we can start digging deeper into this for you.
And if it solves your problem let us know so we can close the ticket.
Thanks.

**Comment by garfield69** [comment]
Closing on the assumption that upgrading to a nightly fixed the OP's problem.
Should the OP ever reply to the contrary we can re-open the ticket and investigate further.
