### ISSUE TITLE
masking error messages that contain passwords

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#717]
example (redacted)
![image](https://cloud.githubusercontent.com/assets/19787673/15881608/50ef0776-2d05-11e6-8b7c-626243003030.png)

since generally these sorts of errors lead to help-me tickets, and pasting logs here will therefore break privacy.

Perhaps find some way so that the username and password are in a pull-down in the message, so that the user can still see content for validation purposes in the active duckietv logs, but a screenshot would show the general error message without revealing privacy.

**Comment by SchizoDuckie** [comment]
Imposible unfortunately, this is a a feature of the devtools that we have no control over.
