### ISSUE TITLE
DuckieTV 1.1.4 distribution check list

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#721]
to do list (add or subtract as required):

**pre-release work**    
- [x] prep/check the version to 1.1.4 as required (VERSION, MANIFEST, PACKAGE, etc).
- [x] hide any w.i.p. pages or features using some html tricks
  - [x] #463
    tab.html
  
  ``` javascript
          <li class="hide-prod" id="actionbar_switch" ui-sref-active="active">
            <a ng-click="setSetting('main.viewmode', getSetting('main.viewmode') == 'calendar' ? 'todo' : 'calendar')" class="glyphicon glyphicon-check" tooltip="Switch between calendar and todo mode" tooltip-placement="right"></a>
          </li>
  ```
  - [x] #18 
    templates/sidepanel/settings.html
  
  ``` javascript
    <tr class="hide-prod" ui-sref-active='active' ui-sref=".tab({tab: 'custom-search'})" ng-if="getSetting('torrenting.enabled')">
      <td colspan="2">
          <a href="#/settings/custom-search">
              <i class="glyphicon glyphicon-search"></i><strong>My Custom Search Engines</strong>
          </a>
      </td>
    </tr>
  ```
- [x] fix any outstanding urgent bugs
- [x] prep/check the changelog
- [x] prep/check the migrationService
- [x] prep/check the upgradeNotificationService

**testing as @ 8-aug-2016**    
- [x] test upgrade from 1.1.2 to 1.1.4 (standalone 20160807 nwjs0.12.3)
- [x] test upgrade from 1.1.3 to 1.1.4 (standalone 20160807 nwjs0.12.3)

**release check list**    
- [x] tag and draft a new GitHub release
- [x] prep the build suite
- [x] generate the standalones
- [x] push to chrome store
- [x] update the gh-pages
- [x] post an announcement on Reddit and Facebook
- [x] have a beer

**Comment by danpe** [comment]
👍  When is this version planned to be released?

**Comment by Js41637** [comment]
We're waiting for @SchizoDuckie to finish up updating the build bot and stuff I think, the newer standalone versions need a different version of nw.js and the build had to change.

**Comment by SchizoDuckie** [comment]
Do we have any more important stuff that needs to happen before we do this?
I'm going to patch the last couple of lines on the builder tomorrow and then I think we should be good.

Feel free to place the tag 1.1.4 tag at will when it's done, I will make the build process so that it checks out exactly that tag and builds it, and auto-creates a release on it.

**Comment by garfield69** [comment]
>Do we have any more important stuff that needs to happen before we do this?     

Be nice to sort out the https://github.com/DuckieTV/xem-cache repo update/refresh, and the https://github.com/DuckieTV/DuckieTV repo daily refresh before publishing the stable 1.1.4 release.
But there is nothing DuckieTV source code related, so I say full steam ahead!

**Comment by SchizoDuckie** [comment]
I think that concludes my last polish round. I'll start working on the production release code tonight.

**Comment by garfield69** [comment]
Could you complete the xem repo updates first please?

**Comment by SchizoDuckie** [comment]
Almost forgot about that one! https://github.com/DuckieTV/duckietv-builder/commit/90eebb8379ecd1c19aa8172838d90358e7984881 There you go :+1: 
(installed on buildbot crontab too)

**Comment by garfield69** [comment]
OMG you published already!     

um, did you build 1.1.4 without the SDK version of NWJS? Because F12 opens a window but it does not contain the Development Tools, just blank... intentional?      
Also, does the 1.1.4 build incorporate the css mods for class=hideprod, because I was not expecting to see the custom-search-engines in settings, but they show up?

**Comment by SchizoDuckie** [comment]
The prod builds do not include the SDK, correct.

I think I did forget to do the class="hideprod" thingie (they were checked already in the list, so I figured it wasn't necessary)

If we do require the SDK builds for production as well, we could switch them to the SDK build too, but I'd rather not ship debug code to prod anymore because of the huge increase in filesize (and memory usage)

**Comment by garfield69** [comment]
the class=hideprod is in the html, but the old buildbot included the hide-prod.css into the build.... and the new buildbot needed to do the same if we want support hiding code from production.     
Just remember that without SDK there is no console log, so supporting problems with diagnostics becomes that much harder...

**Comment by Js41637** [comment]
could just make your own log viewer, bind the console.log methods, store it in array, make it viewable in About.

**Comment by SchizoDuckie** [comment]
Whenever somebody has problems we should ask them to try on a nightly anyway, plus we ourselves use debug builds.

While I do recognize that this may complicate things for those that need more advanced technical support, I do think that not including the whole SDK by default makes sense from a user perspective.

I'll build new binaries with hide-prod included. (only 16 downloads so far)

**Comment by garfield69** [comment]
Okely Dokely. Guess we try it like this for a while. We can always do a review some time later and see how pans out. :-)
Exciting times ahead!

**Comment by garfield69** [comment]
I must remember to update the wiki tonight to reflect the changes to the *Reporting a problem* sections. ;-)

**Comment by mw3demo** [comment]
Well done guys! Epic amount of time and love you have all put into this release. Thank you @garfield69 @SchizoDuckie @Js41637
