### ISSUE TITLE
Wrong URL when searching in KAT

### ISSUE THREAD

**Issue by dabrugge** [SchizoDuckie/DuckieTV#723]
Searching KickAss for torrents doens't work.
That for example the new Top Gear episode. DuckieTV tries to find it at: https://kat.cr//usearch/Top%20Gear%20S23E04%20/?field=seeders&sorder=desc
That should be at: https://kat.cr/usearch/Top%20Gear%20S23E04/

**Comment by garfield69** [comment]
Huh?
if I click on both the links you provided I am presented with the same page with the same results list.

https://kat.cr//usearch/Top%20Gear%20S23E04%20/?field=seeders&sorder=desc
![image](https://cloud.githubusercontent.com/assets/6933240/16205266/18d84fec-3777-11e6-927c-19e37a08a778.png)

https://kat.cr/usearch/Top%20Gear%20S23E04/
![image](https://cloud.githubusercontent.com/assets/6933240/16205233/f1e71b52-3776-11e6-94f7-1128189a9587.png)

Do you get something different?

**Comment by dabrugge** [comment]
Yes, I get this:
![screenshot](https://cloud.githubusercontent.com/assets/20047136/16205897/46e4e586-3726-11e6-93b7-b49397099571.png)
I see you do not have the double // in your screenshot. That's the difference.

**Comment by garfield69** [comment]
what version of DuckieTV are you using and for which platform?
You can get these details by clicking on the *About* (i) icon near the bottom left of the main DuckieTV page.
![image](https://cloud.githubusercontent.com/assets/6933240/16206304/e26d8e0e-377b-11e6-9a27-c8224c13ea8a.png)

**Comment by dabrugge** [comment]
![screenshot 2](https://cloud.githubusercontent.com/assets/20047136/16206626/8c470516-3729-11e6-9c1a-e7d4cddc5a06.png)

**Comment by garfield69** [comment]
Thanks. I can see the problem. your KickAssTorrents.mirror" key is set to "https://kat.cr/" which I now recall was a bug we squashed a while ago, and will be included in the next release of DuckieTV.  It should be "https://kat.cr".

Meantime, we can try fixing that setting.
For the first attempt, try going to the DuckieTV *Settings* page (Cog icon), click on the *Torrent Search Engines* button, scroll down that side panel till you get to the *KICKASSTORRENTS* section, remove the trailing */* (forward slash), and click on the *Validate and Save* button.
![image](https://cloud.githubusercontent.com/assets/6933240/16206841/6957a5e2-377e-11e6-9c08-3543a42844ef.png)

if successful, you should see a *saved!* confirmation.
![image](https://cloud.githubusercontent.com/assets/6933240/16206886/a859757c-377e-11e6-8c1a-5609b0d783e1.png)

If it does not work then we will have to override it manually.
Let me know how it goes.

**Comment by dabrugge** [comment]
D'oh. F***, I should've seen that.
Thanks

**Comment by garfield69** [comment]
I take it you have fixed the problem then ?

**Comment by dabrugge** [comment]
yes, removing the / in the settings does the trick

**Comment by garfield69** [comment]
excellent. Ticket closed.
