### ISSUE TITLE
When adding new shows hovering over a show opens details and can't be closed

### ISSUE THREAD

**Issue by lonelyfairie** [SchizoDuckie/DuckieTV#728]
Not a mayor issue bit I noticed that when going to add shows if you hover over one of the trending shows the details panel opens on the right and can't be closed, it will only change to a new show as you hover over it but it is stuck there and taking space from the list of shows.
Would love it if either clicking on a show was required for the panel to open up or/and an X be added to the panel to close it?

**Comment by garfield69** [comment]
I will add a close button.
Also adding a half second poster hover delay before opening the details side-panel. This should allow you to scroll the trending list without triggering the side-panel, and prevent most accidental side-panel openings for posters you did not intend to view the details of.
