### ISSUE TITLE
Request: Filter trakt.tv trending shows so shows that are already added are not shown

### ISSUE THREAD

**Issue by lonelyfairie** [SchizoDuckie/DuckieTV#729]
If the list wouldn't show the shows I am already following it would probably be more useful when looking for new shows to watch.

**Comment by SchizoDuckie** [comment]
Good idea. done.

(thinking about removing the existing shows from the 'add favorites' as welll, by the way.

**Comment by lonelyfairie** [comment]
I just tested this and I am not seeing any shows at all,  attaching screenshots of all categories and Comedy selected. 

I know I watch a lot of shows but I am sure some of the one from trending I am not currently watching. 
![screen shot 2016-07-29 at 22 49 25](https://cloud.githubusercontent.com/assets/13501166/17267432/a4fc8034-55df-11e6-84a3-5eba16ed0a94.png)
![screen shot 2016-07-29 at 22 50 46](https://cloud.githubusercontent.com/assets/13501166/17267433/a5ae0bec-55df-11e6-80b8-2f5764859014.png)

**Comment by garfield69** [comment]
DuckieTV refreshes its local copy of the Trakt.TV trending list once a week to a cache stored in your local storage.    
It's possible your trending cache got trashed yesterday when Trakt.TV were performing a database upgrade that took about 6 hours to sort out. During that period there were times when Trakt.TV was responding to connections but not delivering data.    
Anyway, lets try the following:    
Press **F12** to open the *Developers Tools* panel, and click on the **console** tab to view the *log*.
at the **>** prompt paste the following from below and press **enter**.
```javascript
localStorage.removeItem('trakttv.lastupdated.trending');localStorage.removeItem('trakttv.trending.cache');
```
Now shutdown and start up DuckieTV.    
Has the trending shows re-appeared?

**Comment by lonelyfairie** [comment]
Thanks Garfield! That did it and now I see trending shows :)
