### ISSUE TITLE
[Feature Request] Automatic VLC Tracker

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#733]
Can you add support for DuckieTV to automatically tell what you're watching on VLC if you have enabled it in settings.

It has already been done hear but with track tv instead: https://github.com/XaF/TraktForVLC

**Comment by SchizoDuckie** [comment]
I suggest you use tracktforvlc then instead. Since DuckieTV syncs with trakt anyway.

It looks like a load of work for a very specific usecase.

**Comment by zero77** [comment]
Ok thanks I will do that, although I thought it would be a nice option to have built in for users who don’t use track tv.
