### ISSUE TITLE
[Feature Request] Filter Downloads

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#735]
Can you get DuckieTV to prevent info, txt, folders and other unnecessary things from being downloaded, just the tv show file for instance mkv, avi and mp4 files.

Novaroma has this option: https://github.com/novaroma-project/novaroma

**Comment by SchizoDuckie** [comment]
I'm downvoting this as too much work for very little profit. Like to hear what the others have to say about it.

**Comment by garfield69** [comment]
The additional files that sometimes accompany a torrent's episode are usually small and don't add anything to overall traffic cost.
Personally I use FileBot to auto-delete these files, and auto-rename the episode to my naming scheme and move it to its final destination.
So I am in agreement with schizoduckie.

**Comment by zero77** [comment]
Ok thanks, I didn’t realise it was possible to do all that with filebot.
