### ISSUE TITLE
Update links

### ISSUE THREAD

**Issue by jnieurzyla** [SchizoDuckie/DuckieTV#736]
Both Pirate and Kickass have changed their locations, and need updating pls.

**Comment by garfield69** [comment]
you can change TPB by going to the DuckieTV **Settings, Torrent Search Engines, The Pirate Bay Main Mirror**, and entering the **Address** and pressing the **Validate and Save** button.
![image](https://cloud.githubusercontent.com/assets/6933240/17011358/5b0d9a64-4f61-11e6-99fd-3935ff170332.png)

KAT however is down, probably permanently. see https://torrentfreak.com/feds-seize-kickasstorrents-domains-charge-owner-160720/ for full details.

**Comment by jnieurzyla** [comment]
Kick ass is temporarly using this url as its new address

http://dxtorrent.com/

John

**Comment by jnieurzyla** [comment]
Thank you for your help :)

**Comment by garfield69** [comment]
you should be able to change the KAT address in a similar way to TPB in settings.
I suspect dxtorrent is a proxy, so you may not see any new torrents from this point on. (unverified opinion)
