### ISSUE TITLE
Help For Testing DuckieTV

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#738]
https-EveryWhere use this to test changes to their addon, would it help with testing for DuckieTV.
https://travis-ci.org

**Comment by garfield69** [comment]
We have been using Travis since 15 Jan 2015

**Comment by Js41637** [comment]
Well, we use to use it but, because of the ever changing nature of the code we weren't updating our tests as we go which made it keep erroring so we disabled it lol

**Comment by garfield69** [comment]
Huh? the last travis run was 18 hours ago!
I accept the bit about the test probably been useless though. I personally never got involved in creating or amending any of the test parameters, never spent any time understanding how to use it.

**Comment by Js41637** [comment]
It still runs but its not really doing anything
