### ISSUE TITLE
Torrent Downloading is confusing

### ISSUE THREAD

**Issue by Js41637** [SchizoDuckie/DuckieTV#739]
TPB torrent download uses a service that generates a torrent download link that downloads directly in the browser and is stored as `torrent` on the item property. In the code it implies that a torrent can't have both a `.torrent` and `.torrentUrl` as it will create two download buttons. `.torrentUrl` gets sent off to a function that handles how the torrent file should be handled in [torrentDialog.js#266](https://github.com/SchizoDuckie/DuckieTV/blob/angular/js/directives/torrentDialog.js#L266)

I assume it tries to add it to the torrent client directly if its available and then download it however this does not seem to work as it just keeps trying to `launchTorrentByUpload` which doesn't seem to do anything for me on my end both with uTorrent open and closed. Both resulting in nothing happening.

I think if we have a torrentUrl it should just download it, I don't see why anyone would select a .torrent download if they're not intending to download it.

**Comment by garfield69** [comment]
just to add to the confusion :-b, I don't have any problems using the .torrent download button on my torrentDialog with either _any_ of the search engines. So what ever is happening, it may be a local issue at js4137's end.

**Comment by Js41637** [comment]
:(

**Comment by garfield69** [comment]
Are you using standalone (if so which nwjs version) , or the chrome extension in developer mode (is so which chrome version) ?

**Comment by Js41637** [comment]
Also, I assume CRUD.Debug mode is on but I'm getting massive console spam whenever I add a show and it keeps spamming it every few seconds.

**Comment by garfield69** [comment]
yeah, I turned off crud.entities debug for myself, schizoduckie has it on for his searchengines dialog wip

**Comment by Js41637** [comment]
Using browser, I was using Canary but I am getting the issue on Stable version of chrome as well which is 52 i think.

**Comment by Js41637** [comment]
Just to clarify though, `launchTorrentByUpload` is meant to add the .torrent file into the torrent client directly? Cause if it is lets just assume that my uTorrent is broken even though it still tries to do it when uTorrent isnt running. I think the point still stands that if we have a torrentUrl, just add it as a direct download like TPB does.

**Comment by garfield69** [comment]
this is what I get using chrome stable 51.0.2704.106 m with DuckieTV extension in developer mode, and uTorrent host running.
For ExtraTorrent the 'save torrent as' dialog is generated from chrome
![image](https://cloud.githubusercontent.com/assets/6933240/17082509/f96059de-51d4-11e6-8772-d1957bf290c6.png)

for tpb
![image](https://cloud.githubusercontent.com/assets/6933240/17082522/78e0ae2a-51d5-11e6-93bb-bd46ff32b438.png)

I note however, that there can be a huge delay for before the save-as-dialog comes up. Tpb varies between 1 second and 10 seconds, presumably becuase http://itorrents.org takes a while to convert the magnet to torrent. ExtraTorrent is a little quicker, within 2 seconds most of the time.

>Just to clarify though, launchTorrentByUpload is meant to add the .torrent file into the torrent client directly?  

not for me.
I get a save-as-dialogs from chromium popping up. uTorrent does not get loaded with the .torrent (unless you have uTorrent set to scan a torrent folder and auto-uploads the .torrent file from there).

**Comment by Js41637** [comment]
I suppose you could save as for the TPB one it is a link but clicking it in Chrome just downloads it
![image](https://cloud.githubusercontent.com/assets/6258213/17082607/34d33188-51c8-11e6-8e6e-cb648b74f19c.png)
Clicking the one on extra torrent does nothing (as it isnt a url) it fires the `launchTorrentByUpload()` function and nufin happens.

**Comment by garfield69** [comment]
Figured out why mine behaves differently. I had *settings,torrent,torrent parameters* enabled.
with this option disabled, I now get exactly what you describe.
Sorry about that.
So now we know it is not just you, and we can work on debugging the problem.

So recapping, we want to try and get the extraTorrent to behave the same way as TPB when selecting the `download .torrent` icon in the torrentDialog?

**Comment by Js41637** [comment]
huh weird. I would say make it an option but if one of them downloads and another doesn't, there are some inconsistencies in what the buttons do, I think we should just make it download the .torrent file.

**Comment by SchizoDuckie** [comment]
With all this noise I can't really  get a grip on what the exact problem is you're having, but I'll try to clarify the ideas behind the whole architecture in a graph somewhere this week.

The launchTorrentByUpload is meant to:

- download the .torrent file from the torrent search engine (hence the promise wrapper)
- pipe that download into a torrentClient's 'upload' function

Then in the torrentDialog there's also a 'download .torrent' function, which directly serves the .torrent to the user, without uploading it to a torrent client.

That download .torrent function is also piped to handle the case where torrent search engines don't actually serve a .torrent but only magnets, in which case it goes through the (now defunct) torcache, and grabs the .torrent form the infoHash alone.

The third workflow is where you actually just click the link in a torrentdialog and want to download the item and send it to your torrent client, independent of:

- does the search engine serve magnets?
- or does it only serve torrents? 
- does the torrentclient accept magnets?
- is the torrentclient configured to handle only .torrent uploads? (a must-have for seedboxes and private trackers, which auto-implies downloading the .torrent and uploading it to the client)

Hope that clarifies things.

**Comment by garfield69** [comment]
description of the primary problem as far as I can make out:   
- DuckieTV is connected to the uTorrent Host using the API client.   
- user has the torrentDialog open, and using the ExtraTorrent search engine (which only supports .torrent via a direct hyperlink, no magnets)   
- when the user clicks the TorrentDialog's *download .torrent* icon, all the users sees is that the torrentDialog is closed,  but the .torrent is:
   1.  *NOT* piped to uTorrent via the API successfully (there are no error messages in the log)   
and    
   2. the .torrent is **NOT** served to the user as a download.

I think this is a problem with the uTorrent API addTorrentByURL function, which appears broken.

Additionally, the user is looking for consistency in functions connected to the TorrentDialog icons.
Currently the torrentDialog presents the same set of icons and tooltips, but depending on the search engine and torrent client combinations, this leads to different results, which is confusing.

We could improve this by making the torrentDialog do a little pre-checking of the search engine settings, and torrentClient services, and show icons and tooltips that represent exactly what the intended result is expected to be.

**Comment by SchizoDuckie** [comment]
Huh? where are the functionalities different then?

**Comment by garfield69** [comment]
the icon for *download .torrent* delivers different results depending on:
- the search engine has a direct *download .torrent* hyperlink **or** DuckieTV has to generate the .torrent via the magnet2torrent service
- the torrent client supports piping the .torrent directly **or** the .torernt is served to the user as a download

**Comment by SchizoDuckie** [comment]
Oh, that's indeed not be how I intended it to work. the download .torrent
link should always serve the .torrent to the user. The text link title
should pipe it to the torrent client.

**Comment by garfield69** [comment]
check list
- [ ] adjust and confirm for all search engines that the torrentDialog's *download .torrent* icon performs a user download of the .torrent file, regardless of it coming from a direct href (url) or from duckietv generated magnet2torrent conversion via itorrents.org
   - [ ] ExtraTorrents
   - [ ] IsoHunt
   - [ ] Nyaa
   - [ ] RarBG
   - [ ] ShowRSS
   - [ ] TPB
   - [ ] Torrentz
   - [ ] Zooqle
- [ ] look into why uTorrent API is not performing an uploadTorrentByURL and confirm that it works for all other torrentClients
    - [ ] uTorrent API
    - [ ] uTorrent WebUi
    - [ ] uTorrent WebUi
    - [ ] uTorrent WebUi
