### ISSUE TITLE
Being able to use Broadcasthe.net as a search engine

### ISSUE THREAD

**Issue by sqyral** [SchizoDuckie/DuckieTV#742]
Hey guys,

I'm completely new to this and I was wondering, if possible, am I able to add Broadcasthe.net as a search engine in Duckietv? It's really the only torrent site I use and it would be good if I could pull my torrents from that site.

I had a look at creating a custom search engine, however I very quickly got confused and was unsure as the what I was doing.

Any help or feedback would be awesome!

Cheers,

Sqyral.

**Comment by garfield69** [comment]
The custom search engine is still in development and not ready for use quite yet.    
As it happens, the current version in development is broken, returning `TypeError: self.model.getFreshInstance is not a function` errors when I tried to create a new SE just now :-(    

But once it is completed and released, we will most likely create a support wiki, with an example of how to fill in the various fields, and there will be ready-made SE profiles that you can download, which would give you a starting point for developing your own SE for Broadcasthe.net if one is not already available for downloading.

My suggestion is that for now, you sit back and wait for the CSE to be finished.    
I invite @SchizoDuckie  to add any additional info and/or corrections. :-)

**Comment by sqyral** [comment]
Hi, and thanks for your quick response!

I had a feeling that was going to be the answer, going by some of the other forums I had seen. I look forward to it being added and working. I love the idea behind DuckieTV, but since all my torrents come from BTN, it makes it a bit hard to use it for now.

Cheers for the info. :)

**Comment by garfield69** [comment]
You should now be able to access any of the open/semi-private/private trackers that the Jackett proxy has available, as a DuckieTV Search Engine, starting with the latest Nightly 31-05-2017 01:55:49 at https://github.com/DuckieTV/Nightlies/releases
See wiki https://github.com/SchizoDuckie/DuckieTV/wiki/Using-Jackett-with-DuckieTV for details on setting up Jackett with DuckieTV.
Jackett will be included in the next Stable Release of DuckieTV 1.1.5 whenever that gets published.
