### ISSUE TITLE
Proxys

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#743]
Can you add proxy support for zooqle in particular as its not working for me, and for the other torrent search engines, you can get proxies for all the search engines, with regular updates when they are blocked at proxybunker.co.uk.

**Comment by garfield69** [comment]
I expect that once the custom-search-engine feature has been completed, users can override the SE URL with what ever URL works for them.

**Comment by zero77** [comment]
Ok that's a good point, although in the meantime can you add proxy support for zooqle as its blocked for me.

**Comment by garfield69** [comment]
Researching and coding proxy support is as much work as completing the custom-search-engine code, so no, I don't think it's worth our time to do this. @SchizoDuckie  chime in if you have an opinion, please.    

If you desperately need to get zooqle working, then switch to using the source development build of duckietv. That way you can edit the zooqle SE and amend the mirror field to the URL you need.    

This wiki for standalone source development should get you started https://github.com/SchizoDuckie/DuckieTV/wiki/How-to-Install-a-Development-version-of-the-Windows-DuckieTV-Standalone-SOURCE    
or     
this wiki for the chrome extension source https://github.com/SchizoDuckie/DuckieTV/wiki/How-to-Install-a-Development-version-of-the-DuckieTV-Chrome-Browser-Extension-SOURCE
