### ISSUE TITLE
Includes and Excludes

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#744]
Can you add support for local includes and excludes and also min and max sizes alongside the global option.

**Comment by garfield69** [comment]
By local, do you mean options for a specific series? Because that is available from the series details panel, if you are using a development nightly.    
![image](https://cloud.githubusercontent.com/assets/6933240/17528330/23253032-5ec3-11e6-9c0f-85e6e443cb44.png)

**Comment by zero77** [comment]
Thanks I forgot about that, and yes that’s what I mean by local, although I cannot see an exclude option there.

**Comment by garfield69** [comment]
You should not need it. You set the ignore global includes to true,  then load the custom search string with the words that must be in the torrent name to be accepted. These will over-ride any words in the global exclude list. That should be enough to pass the filter. Or you can set the ignore global excludes to true, if you need to. But I've never come across a situation yet where you need to code custom exclude list.
