### ISSUE TITLE
TV Show Posters Support

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#745]
Can you add support for tv show posters when searching for torrents, exactly like the rarbg website has when you hover your mouse over the torrent name.

**Comment by garfield69** [comment]
Personally I detest how part of the screen gets covered by a poster that appears as you hover over a torrent link, seems like that feature does not add anything of value to the user. Any one else care to venture an option?

**Comment by SchizoDuckie** [comment]
Not a fan of this. This doesn't add anything imo and is way too specific an implementation
