### ISSUE TITLE
Close Button 

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#747]
Can you add a close button to all the popup menus that appear on the right hand side, like the options menu.

**Comment by zero77** [comment]
Thanks, this is much better now, although can you change the colour of the close button to something easier to see, also can you stop the close button in the favorites page taking you back to the main page.

**Comment by garfield69** [comment]
yeah, don't bug me, it's *work in progress*. when this tickets label changes from (working* to *Done* then you can critique :-b

**Comment by zero77** [comment]
O ok sorry
