### ISSUE TITLE
Improve Tracked TV Updating

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#748]
Can you improve trakt tv updating by, importing and pushing tv shows to trakt tv at the same time as the update period, and also by removing tv series from trakt tv that have been removed from DuckieTV.

**Comment by SchizoDuckie** [comment]
The sync back to trakt.tv is an explicit separate process for all of DuckieTV since we do not have a mandatory login to trakt.tv.

The sync back to trakt.tv will  be addressed in the future with issue #32

**Comment by zero77** [comment]
What I mean is if you have logged into trakt tv, when duckietv checks for the latest episodes from trakt tv can it also import any newly watched episodes to duckie tv and can it also push newly watched episodes to trakt tv, so both trakt tv and duckie tv are kept up to date.

**Comment by garfield69** [comment]
There are two distinct processes when dealing with Trakt.TV, and perhaps a short description of the two will provide a little clarity for you zero77.    

The first process deals with keeping DuckieTV's calendar up to date with the latest episode release dates, and other show information. This is managed by DuckieTV's Trakt.TV update process, and runs regularly at least twice a day, or more depending on your settings.    

The second process deals with keeping a users Trakt.TV account in sync with DuckieTV. This is a separate process, which only runs if the user has used DuckieTV to login in to their Trakt.TV user account.    

And as you have stated zero77, DuckieTV does not currently provide a complete two way sync of Trakt.TV user account shows/episodes with DuckieTV.     
And as Schizoduckie has stated earlier, this will be resolved with we sort out #32 as its related to that type of activity.    
I am closing this ticket as a duplicate.

**Comment by zero77** [comment]
ok, thanks for explaining.
