### ISSUE TITLE
verified search fails to return results, vuze integration problems, and nitpicking

### ISSUE THREAD

**Issue by biotoxin** [SchizoDuckie/DuckieTV#751]
TPB I've verified the link working and mirrors, yet none are returning results.

Also the favorites list no longer returns to title position when expanding side menus and instead returns to the top, I know this was working before yet has since stopped, not sure if it's just me or everyone.

I'll include screenshots of as much relevant information as possible

auto-download isn't exactly behaving either, which is now compounded by vuze web remote not connecting anymore when it setup just fine at first,

 though I believe that might be more the problem of a vuze update or something else on my network. Test and Save of vuze integration though doesn't appear to show any kind of result either success or failure so it's hard to say.

I've changed web remote from default port and made sure it's verifiably forwarded, I've tried with and without unpnp and made sure all firewalls were properly forwarded, dmz'd, or disabled during various tests, and while vuze reports not being accessible outside my local network which is really only a problem for my phone and laptop when I want to manage my main system, I have verified the webUI works within the local network on various machines. 

while I continue to try and work on vuze though TPB is hopefully easier to fix and I can update again once I have vuze properly working for outside access.

![screenshot_1](https://cloud.githubusercontent.com/assets/4185690/17680932/bfbc0af0-6310-11e6-8a61-4b57fd833033.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/4185690/17680931/bfbbca18-6310-11e6-907e-027e2fc4bb3e.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/4185690/17680934/bfbe738a-6310-11e6-8abf-5bd0a1936042.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/4185690/17680933/bfbc55aa-6310-11e6-9b8f-f2e3020fb505.png)
![screenshot_5](https://cloud.githubusercontent.com/assets/4185690/17681065/6f1b48ee-6311-11e6-8001-29741d120c59.png)

**Comment by garfield69** [comment]
- [ ] Vuze connection o DuckieTV nightly.    
The Vuze connecting problem is probably related to a recent development nightly release that stuffed up the setting for the vuze.path.     
Should be able to fix that by:     
- downloading the latest nightly    
- going to the development tools panel by pressing **F12** and then clicking on the **Resource** tab (chrome 51 or earlier) or the **Application** tab (chrome 52 or later)    
- click on the arrow next the **local storage** to expand it and click on the item that appeared underneath, to view your local storage table    
- scroll till you find the key **1.1.4updateTransmissionPath** and click on it once to highlight the whole row    
- press the **del** key to delete that row     
- restart duckietv.  This will rerun the migration step for transmission/vuze, and should rebuild the vuze.path setting.     

- [ ] Also the favorites list no longer returns to title position when expanding side menus and instead returns to the top     
I think this broke after https://github.com/SchizoDuckie/DuckieTV/commit/446d9b55c576fc8bde839b8024a0fe77251cca12
@SchizoDuckie will probably need to look into this, or @Js41637 . its out of my area of knowledge.     

- [ ] auto-download not working     
related to vuze not connecting. ADL will not start of there is no torrent host connected.     

- [ ] TPB not working     
will require more data. It's working for me. However I note that I am getting lots of 523 and 50x errors from TPB recently, it might be suffering from overload with the return of a lot of traffic sinze kat and torrentz vanished. Check the DuckieTV **log** for errors after you get a sad face from a search to see if there is an explanation.


as you confirm you have resolved (or accepted) each item, tick the check box so we can track progress.

**Comment by garfield69** [comment]
Oh wait, just spotted whats wrong with your TPB SE. Schizoduckie's custom-search-engine WIP has overridden the default SE. 
- go to *Settings, My Custom Search Engines* and click on the **disable** buttons of all the testing SE that are there. 
- Restart DuckieTV to reload the default search engines and try TPB again.

**Comment by biotoxin** [comment]
tick boxes not working..?

deleting the transPath worked to get it cleared/primed for new connection, though I ended up still having to uninstall and reinstall web remote on vuze to get it to finally kick, as such back to default port
it was giving me some not authorized error in spite of correct new name and passwords, works now though so great stuff

auto download started the second it connected, I'll monitor it for a day or two still though as it only started 6 downloads and I know there should be more in the queue.

TPB you were right, and I'd noticed the error in log but couldn't figure out where to go to fix it so that worked like a charm

Only thing left is the nitpicking favorites return position, which honestly I can live with especially now that auto download looks like it should be working.

**Comment by biotoxin** [comment]
![screenshot_6](https://cloud.githubusercontent.com/assets/4185690/17682945/2d725c78-631d-11e6-8991-e3676e1327fa.png)

**Comment by garfield69** [comment]
The auto download has a setting to look back a certain number of days for torrents that have not been downloaded.     
The default I think is 1 day.     
If you are wanting to catch up, then change this setting in DuckieTV's *Setting, Torrent, Auto-Download Period*. Max is 21  days I think. For older torrents you are going to have to manually search.

**Comment by biotoxin** [comment]
I noticed that, and I can catch up manual as I finish working my way through the favorites list to tell it what I have in database and whats been actually watched, but just yesterday the 14th here's the list, downloaded items highlighted in green, I'm checking to see if maybe no torrents were available or do not download settings etc
![screenshot_7](https://cloud.githubusercontent.com/assets/4185690/17683217/15ddc500-631f-11e6-800d-1bfe974bd0e1.png)

**Comment by biotoxin** [comment]
I noticed the option, which I'll grab what I'm missing manually as I work my way through the favorites list to tell it what's downloaded in database and what's actually been watched

though I'm looking at the downloaded items highlighted in green and the ones not highlighted on the same day, checking now for if they're do not download settings, or if torrents are even available, etc

I noticed a couple like walking dead had "specials / previews" that make sense to not be highlighted / auto downloaded, so if it's actually something I'll make mention of it, right now I'm just observing the auto system so I see what it's doing and how it's doing it.

it's going to take me a while to properly configure preferences per show on quality, size, release group

**Comment by Js41637** [comment]
Mm i'll look into the posters positioning, it needs some work.
