### ISSUE TITLE
notes on day boxes in the calendar

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#753]
As raised in this [Reddit](https://www.reddit.com/r/duckietv/comments/4yiyg1/feature_request_add_a_note/)     
Traspen:
>Is there any way to add a note to a date on the calendar? I'd like to add a note to the first day of every Month to remind me to look for the "new" shows premiering in the upcoming month.    
>Just a thought.    

If accepted, how would we best implement it? Date indexed array kept in localStorage or entity in DB? With a tag in the corner of a day box if present? Opinions anyone?

**Comment by SchizoDuckie** [comment]
Hmmm. I can see the appeal, but you really should do notes in google calendar or the likes. 

Turning the calendar view into an actual reminder calendar will create a whole lot of noise that has nothing to do with tv show tracking imo.

**Comment by garfield69** [comment]
Agreed. I'll decline the request.
