### ISSUE TITLE
enhancement request

### ISSUE THREAD

**Issue by Dhop84** [SchizoDuckie/DuckieTV#757]
Hi I'm new to all this so forgive any of my mistakes, I've only just found this great programme a couple of days ago so I don't no if it's been mentioned before but to make it more user friendly (for the wife) my wife uses http://www.tvguide.co.uk to check what's on the tele daily, so you have the option in tv guide to add a show to your calendar to tell you when something you want to watch is on, is there a way of incorporating that into duckie? So the shows you have added to your calendar via tv guide or whatever you use can get added straight to your "favourite" shows and then normal service resumes and duckie finds when a torrent has been uploaded and then maybe you get notified when it's been downloaded or sumn, for my wife to use this daily it would make it so much easier if all she had to do was check the TV guide and then add the shows she wants to the calender.

**Comment by SchizoDuckie** [comment]
Sorry i'm going to decline this as impossible.

This would mean making a new tv schedule based on local timezone and locale info for every new country/tv show website and maintaining them.

We work with the Trakt.TV data, and I'm not going to add external datasources on top of that, as that's asking for a whole lot of pain.

**Comment by Dhop84** [comment]
Thanks for looking at the request anyway, keep up the good work
