### ISSUE TITLE
debian package for linux

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#758]
as raised in this [Reddit](https://www.reddit.com/r/duckietv/comments/3y49gx/deb_installer_for_duckietv/), integrate provided debian builder for linux installs.     

https://github.com/brbsix/DuckieTV-installer

**Comment by SchizoDuckie** [comment]
Awesome. I will work this into the buildbot when i'm refactoring it

**Comment by garfield69** [comment]
b95b2c84150e625e20ecfa6325283073146e3045 completes this ticket
