### ISSUE TITLE
[Trakt Sync] Add newly added shows to users collection

### ISSUE THREAD

**Issue by Js41637** [SchizoDuckie/DuckieTV#762]
When Trakt Sync is enabled, when a user adds a show to their DuckieTV library it should also add it to their Trakt.TV collection. 

Possibly make it a separate option to watched sync.

**Comment by garfield69** [comment]
>When Trakt Sync is enabled, when a user adds a show to their DuckieTV library it should also add it to their Trakt.TV collection.      

Trakt's definition of a *collected* item is that the item *is available to be watched* digitally or from physical media (see http://docs.trakt.apiary.io/#reference/sync/get-collection/add-items-to-collection).     
In other words, it is the equivalent of setting an episode as *downloaded* on DuckieTV.     
Ticket #933 (import Trakt 'collected' mark as 'downloaded') was implemented with this in mind.     

So when we ask Trakt to add a show to its collection, Trakt will automatically add all episodes for the show as collected (see http://docs.trakt.apiary.io/#reference/sync/add-to-collection/add-items-to-collection).      
However, if you are adding a show to DuckieTV, you will not have yet marked any episodes as downloaded (collected), so I do not think we should be telling Trakt that the show has been *collected*.
