### ISSUE TITLE
xdg-open required dependency

### ISSUE THREAD

**Issue by LapplandsCohan** [SchizoDuckie/DuckieTV#764]
Trakt.TV integration does not work if `xdg-open` is missing on a Linux system. At least on Debian this is part of the `xdg-utils` package.
This should be added to the depencency checks when installing DuckieTV.

**Comment by Js41637** [comment]
I'm hoping @SchizoDuckie knows something about linux.

**Comment by LapplandsCohan** [comment]
Someone knows enough to have included an install script that does dependency checking, so that already existing script should just be updated to also check for `xdg-open` or `xdg-utils` (don't know which you should check for).

**Comment by SchizoDuckie** [comment]
Thanks @LapplandsCohan, fixed with my next push.
