### ISSUE TITLE
Smooth scroll to series is broken

### ISSUE THREAD

**Issue by Js41637** [SchizoDuckie/DuckieTV#765]
When the sidepanel opens it should smoothly scroll to the selected serie however because we switched to using transforms the calculations no longer work. I've had a look at the code and nothing I tried seem to work properly or it didn't work in all cases.

You might be able to use [`getBoundingClientRect()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect) to get it's position?

**Comment by garfield69** [comment]
fixed by 68d47aab9fd340575ab9e28230b9d73479e142f9

**Comment by garfield69** [comment]
Urg. Heads up. Since your recent change, the trending page is broken, with all the posters overlaying each other in one top-left location.

**Comment by Js41637** [comment]
ohlol

**Comment by garfield69** [comment]
fixed :-)
