### ISSUE TITLE
Tray icon not truly useful on w10.

### ISSUE THREAD

**Issue by vamartid** [SchizoDuckie/DuckieTV#770]
Consider changing the tray icon on windows 10,
since they come with black as the default taskbar color,
A black icon does not realy help the user.
<img src="http://image.prntscr.com/image/52cdda52943649b3be65422e8098726f.png" alt="duckieTv tray icon is really invisible">
I for example just see a black thing whith a white dot an know it is duckyTv.
I 'd like the icon to be visible.
You could put the white icon or if you do not want this,
just add some white stroke or something.

**Comment by garfield69** [comment]
This is already being looked into by https://github.com/SchizoDuckie/DuckieTV/issues/768.
So I'm going to close this as a duplicate.
