### ISSUE TITLE
Auto-download status settings

### ISSUE THREAD

**Issue by forumguy** [SchizoDuckie/DuckieTV#773]
Are these setting configurable and how?

![autodownloadsetting](https://cloud.githubusercontent.com/assets/22416260/18820643/6fb00dae-836d-11e6-8aa9-86cf09f3eded.jpg)

**Comment by garfield69** [comment]
do you see the two cogs, one of the left, the other on the right, just under the main header of the snap shot you provided above?    
they will take you to the two settings side panels that contain all the relevant settings to impact how the auto download behaves.

**Comment by forumguy** [comment]
Thanks for that. 

Is there a 'Next Run' configuration I missed? or is this system controlled?

**Comment by garfield69** [comment]
Once Auto download has been enabled in settings, then it is activated the moment a connection is established by the torrent client to the host. Once active, it runs every 15 minutes. This is not configurable.

**Comment by forumguy** [comment]
Thanks as always.
