### ISSUE TITLE
Autodownload criteria

### ISSUE THREAD

**Issue by forumguy** [SchizoDuckie/DuckieTV#774]
Why is the show (with the arrow) below not being downloaded automatically? but, i can download it manually:

![downloadstatus](https://cloud.githubusercontent.com/assets/22416260/18821621/e1c11854-8375-11e6-9f46-d57829700dc4.jpg)
![downloadstatus 1](https://cloud.githubusercontent.com/assets/22416260/18821623/e36cc3d8-8375-11e6-93b0-69e2c38cbe13.jpg)

**Comment by garfield69** [comment]
no idea. worked for me.
![image](https://cloud.githubusercontent.com/assets/6933240/18821980/5f23a5b4-8407-11e6-842e-eb21d5b93076.png)
see if it gets picked up in the next cycle.

**Comment by forumguy** [comment]
I restarted Duckie and the magnet links were picked up right away. 

I will monitor this behavior.

**Comment by SushiLover** [comment]
Does it only happen with this program? I have the same thing happen if my VPN gets reset. When that happens, none of my auto-downloads work until I restart Duckie.

**Comment by forumguy** [comment]
Try the latest beta version, it's been working like a charm.
