### ISSUE TITLE
Cosmetic Defect - System bar in Mac shows full DuckieTV name and version

### ISSUE THREAD

**Issue by lonelyfairie** [SchizoDuckie/DuckieTV#775]
When you minimize duckie on Mac it now shows the Duckie icon plus it says DuckieTv Standalone v1.1.4 which seems a bit much as it takes quite the space up there.
See screenshot.

![screen shot 2016-10-03 at 9 52 03 am](https://cloud.githubusercontent.com/assets/13501166/19037896/1bc9f69a-894f-11e6-8a3f-c1bfd0417ce7.png)

**Comment by garfield69** [comment]
I'm going to drop the tray.title for the systray since according to http://docs.nwjs.io/en/latest/References/Tray/#traytitle    
>On Mac OS X title will be showed on status bar along with its icon, but it doesn’t have effects on GTK and Windows, since the latter two platforms only support tray to be showed as icons.
