### ISSUE TITLE
Can't Add 'Atlanta' 

### ISSUE THREAD

**Issue by Porphyry** [SchizoDuckie/DuckieTV#778]
I've been trying for weeks to add the FX show "Atlanta," to my favourites without success. Four different versions of the show come up. The only one that contains info is impossible to add.

**Comment by garfield69** [comment]
Are you using DuckieTV 1.1.3 by any chance?   
I can recommend upgrading to the latest development Nightly version which can tell the different *Atlanta* records on Trakt.TV apart.    
You can find the latest nightly at https://github.com/DuckieTV/Nightlies/releases and a guide for installing a nightly (should you need it) can be found at https://github.com/SchizoDuckie/DuckieTV/wiki/How-to-install-development-versions-of-DuckieTV   

Let me know how you go.

**Comment by Porphyry** [comment]
It worked! There was a second there where I feared I had deleted my show library, but the instructions on how to import a backup were super clear. Thanks so much Garfield.
