### ISSUE TITLE
"view posters" mode to the calendar page

### ISSUE THREAD

**Issue by alexwyrick** [SchizoDuckie/DuckieTV#779]
I'd make a $ donation to the creators of this wonderful app if...

...you could add a "view posters" mode to the calendar page!

**Comment by Js41637** [comment]
What do you mean by view posters? 

Also thank you for the offer but we cannot accept donations.

**Comment by alexwyrick** [comment]
I'd like to see the calendar page look like the favorites page, showing the tv show posters instead of the tv show names.

**Comment by Js41637** [comment]
Well to be honest I'm not sure how that would work and I can't really even imagine it. A list of series [posters] that are currently airing this month or a calendar layout but posters in each day for when it airs? How would you know what episode it was or when it aired. It would also take up a lot of space.

**Comment by alexwyrick** [comment]
Each poster would be arranged vertically under the day of the week that show airs...not difficult to imagine.

**Comment by Js41637** [comment]
Well it's not easy to imagine when you don't provide any details.

![image](https://cloud.githubusercontent.com/assets/6258213/19210716/d63ddb88-8d76-11e6-859a-9fc28b8a65d5.png)

Hmm, I don't think it would work too well.

**Comment by alexwyrick** [comment]
It works just fine if u view only 1 week at a time...most people don't wanna see the entire month.  Also, most people only watch 3-4 shows per day, which saves vertical space & keeps the page short enough.  C'mon dude, ur a coder...put ur thinking cap on.  Lots of people need this enhancement cuz they're using the program on a big screen TV.  If u don't wanna do it, then at least increase the font size on the calendar page.

**Comment by garfield69** [comment]
@alexwyrick :
>increase the font size on the calendar page.      

Did you know that you can use zoom on DuckieTV in the same way you can in a Chrome browser?    
The keys are: **Ctrl -** to *zoom out, **Ctrl =** to zoom in, and **Ctrl 0** to reset back to 100%.     
The zoom scale is the same one used on the Chrome browser.

**Comment by 2635599** [comment]
i can't see changing anything about the main view. if he wants to have posters then he can change the view by clicking the box with the checkmark on the bottom left.

**Comment by SchizoDuckie** [comment]
Closing this issue as @alexwyrick is being a pedantic prick.

Not cool man. People are pouring their free time into this program for you to enjoy for free ánd providing support. 

If you want something really bad, either send a pull request or change how your language reads to something more pleasant.

**Comment by alexwyrick** [comment]
Dude.  I offered to PAY for this change, but apparently you guys don’t wanna make money…so don’t act like I expect shit for free, douche.

A

**Comment by SchizoDuckie** [comment]
As said, we are not taking money.
And even if we did, we're not your bitch.
