### ISSUE TITLE
TraktAPI will no longer be serving images

### ISSUE THREAD

**Issue by Js41637** [SchizoDuckie/DuckieTV#780]
> TLDR; Images will no longer be served from the API starting October 31, 2016 due to greatly increased hosting costs. All other API functions will remain the same.
> https://apiblog.trakt.tv/trakt-api-images-56b43c356427#.qnbq8scbn

TraktTV gets all its series, seasons and episode posters/images and fanart from TMDB (or TVDB if none found), if we are to use TMDB to get images, we'll need to create an API for it to fetch the images. I am unsure about TMDBs caching policy meaning I don't know if the URLs change on a semi regular basis like trakt.tvs do so it might need an auto updater every once in a while.

**Comment by garfield69** [comment]
Should it become necessary, here are API docs links to the sites that Trakt.TV references.     
*theMovieDB* (TMDB) API https://www.themoviedb.org/documentation/api    
*theTVDB* API (TVDB) https://thetvdb.com/wiki/index.php?title=Programmers_API    
*fanart.TV* API (fanart) http://docs.fanarttv.apiary.io/#     
*omdb* API (OMDB) http://omdbapi.com/    
*imdb* API (IMDB) ?whatapi?

**Comment by Js41637** [comment]
The only real problem I see is live searches, I don't think it's ideal to request a poster for every result that is returned for a search

**Comment by Js41637** [comment]
I think the MovieDB has the best API and images, it's what trakt uses, it even supports custom languages with fallbacks which we might be able to use as well. It does however require configuration apparently the URLs can change and the images API doesn't return the full URLs only the IDs of the image, you need to specify the size you want

>Some elements of the API require some knowledge of this configuration data. The purpose of this is to try and keep the actual API responses as light as possible. It is recommended you cache this data within your application and check for updates every few days.

>To build an image URL, you will need 3 pieces of data. The base_url, size and file_path. Simply combine them all and you will have a fully qualified URL.
https://developers.themoviedb.org/3/configuration/get-api-configuration

**Comment by Js41637** [comment]
Also another important thing I forgot to mention is it will be hard to find an API that we wouldn't get banned from, seeing as the app is client side meaning we'd have to use a global API key, I'm sure there are rate limits in place that would prevent it from working

**Comment by Js41637** [comment]
TMDB has 40 requests every 10 seconds per IP address so it probably won't work
Fanart.tv doesn't seem to have any mention about it's limits
TVDB doesn't seem to have any mentions about it's limits, there was a comment from 2012 saying they didn't have any.

**Comment by Js41637** [comment]
We might want to considering lowering the amount returned from trending or possibly cache the most popular images for the trending list, even if we use TMDB, its only 40reqs every 10 seconds, we might need to bring back the only loading when in view code.

**Comment by garfield69** [comment]
>Note: We're currently in talks with people who might be able to offer a solution.    

@Js41637 do you have any info you can share?
@SchizoDuckie are you involved with this?

**Comment by Js41637** [comment]
I'm afraid I have no new information to provide at this time.

**Comment by Js41637** [comment]
In a day or two we should know more, if we are unable to get the details worked out about a possibly easier solution, we will be using TMDB for our images. Schizoduckie plans we can hopefully get a release out by the end of the month.

**Comment by Js41637** [comment]
Another issue we have is we're going to need to update all series in the DB before the new TMDB Image API will work as we don't store the TMDB ID for series, we store every other ID apart from it. So we will need to add this to the 1.1.4 update, you might as well delete all existing images urls in the DB

Speaking of images, TMDB does not support banners so, can probably keep the banner mode but it will be  flock of ducks.

**Comment by Js41637** [comment]
We will still keep the fields, we can just clear them all as the old URLs won't work anymore so might as well remove them so if they haven't updated it won't keep trying the invalid URLs. 

One thing i'm not sure about is whether we just store the image IDs or the whole URL, TMDB has stated that its URLs and sizes can change though it is pretty rare and the best method is to store the ID and fetch the latest config which includes the latest URLs and image sizes. I already added some quick code to fetch the latest URL and Sizes and store it in localStorage and update it every 7 days. If we store the whole URL and they change we'd have to update every URL, if we store the ID we'd have to generate the URL as it is needed.

**Comment by garfield69** [comment]
ok good. so If you sync github, you'll see I've updated the tables and nulled any image elements. Added the tmdb elements to series,seasons and episodes for you. Also made a few corrections.  update the migration to refresh all ids. Tested it on my sandbox (once i bypassed the tmdb service, so i could check my code was good).        
So once you've settled on a working mechanism, i'd like to see an option to cache the images locally if that is possible and if it worth while? (optional becuase not everyone has the storage for it, like android devs and so forth).

**Comment by Js41637** [comment]
It's impossible to cache images with the chrome extension as chrome extensions have no access to the filesystem. Short of converting them to base64 and storing them that way, there is no way. It is definitely possible for standalone though.

**Comment by garfield69** [comment]
observation: when using the TMDB_ID from Series and Season you will get the occasional null element (which is to be expected). However for Episodes, you will find also come across **0**!! You will need to handle this when building your urls.

**Comment by Js41637** [comment]
Well as long as it's an int, we can just do `if (id)`, 0 and null will both return false though easy enough to check for. Also for episode images, we will not be fetching them as we add them as it will chew though the rate limit, we're going to try and only load an episode image if it is requested (sidepanel), they aren't viewed _that_ much anyway so.

**Comment by garfield69** [comment]
Yes. The only time episodes posters get used in a bunch is with the TODO monthly calendar view.

**Comment by Js41637** [comment]
hope they like looking at loading spinners

**Comment by garfield69** [comment]
Any news on the official TMDB API key for DuckieTV?     
I am averse to giving out personal details just to have a temporary development key I'll never use again after this conversion project is finished :-/     

Also on the subject of keys, are we really expecting DuckieTV users to register and use their own personal api keys for DuckieTV? Shall I create a settings section in Miscellaneous to save that key in settings?

**Comment by Js41637** [comment]
Well seeing as the API is rate limited per IP not API Key, theres no reason we cant just register one for DuckieTV. I added code to pull one from SettingsService just in case one might need to change it?

**Comment by garfield69** [comment]
@SchizoDuckie  Once you have provided a TMDB API key for DuckieTV, I could devote some time debugging and improving the TMDB service that js41637 has begun, if that is what you want me to do.

**Comment by Js41637** [comment]
Well he had been sick these past few days and I'm sure after seeing the
quick code I made he might be sick again for a few more days

**Comment by Js41637** [comment]
Just going to put it out there but there are definitely ways of caching images using latest browser features should we choose to make use of them.

**Comment by Js41637** [comment]
We will also need to clear the `trakttv.trending.cache` and lastupdate for the trending list as well for the updat.e

**Comment by garfield69** [comment]
>We will also need to clear the trakttv.trending.cache and lastupdate for the trending list as well for the update.     

Already in place, DuckieTV/js/services/MigrationService.js#92

**Comment by SchizoDuckie** [comment]
Alright, sorry guys for the delay in me joining this, life has been crazy.

I've been looking into fanart.tv and this looks like a great option.
All images are hosted on cloudflare with great caching settings, and it also just supports the tvdb_id we already have (ignoring that annoying duplicate id thingie they have there)

We can then execute a request like : 

http://webservice.fanart.tv/v3/tv/75682?api_key=bea26258e1e07e9032e99742bc051f3f
to fetch a full list of images like we currently have, should be easily glued into the trakt updater.

If we then append the images into the precached cached trakt data on github we can at provide a seamless load like we currently have, and have the users only request the data they need

There are also small preview versions of each image by swapping out /fanart/ for /preview/ :

http://assets.fanart.tv/fanart/tv/75682/tvposter/bones-52deb10f82d0f.jpg
 
http://assets.fanart.tv/preview/tv/75682/tvposter/bones-52deb10f82d0f.jpg

**Comment by Js41637** [comment]
Fanart has no episode thumbs, unless you're planning to get rid of them or use another API for episode images, I guess you could use it if you want, TMDBs performance has been pretty great and images load very last, they use Cloudflare as well, have the Business edition so it can handle image loading and have stated they have no problems with people hot linking their images.

All the code for TMDB is already there, you can change it all to fanart.tv if you want.

**Comment by SchizoDuckie** [comment]
say no more. I'm creating a tmdb api key.

**Comment by Js41637** [comment]
Although by that logic TMDB also has no banners which kinda defeats the purpose of the list mode.

**Comment by garfield69** [comment]
TODO checklist:
- [x] add TMDB service - https://github.com/SchizoDuckie/DuckieTV/tree/tmdb
- [ ] register DuckieTV TMDB API key
- [x] add TMDB_ID to Series Table in CRUD.entities and null trakt.tv image urls for all tables
- [x] add migrationService refresh to populate tables
- [x] add migrationService refresh for trending
- [ ] plug in TMDB service for the following image support
  - [x] series posters on favourites page
  - [x] series posters on details panel
  - [ ] series banners on favourites (not supported by TMDB, add FanartService or drop altogether?
  - [x] season posters on season panel
  - [ ] episode posters on episode details panel
  - [ ] episode posters on TODO calendar view
  - [x] series background images
  - [x] series posters on trending page
  - [ ] series poster on trending search
- [ ] anything else?

**Comment by SchizoDuckie** [comment]
It looks like tmdb has some annoying issues when requesting an api key that disallow us from using it for our project.

tmdb is out, fanart.tv is it.

**Comment by Js41637** [comment]
glhf

**Comment by garfield69** [comment]
TODO checklist:
- [x] add FanArtTVv3 service - https://github.com/SchizoDuckie/DuckieTV/tree/FanArtTVv3
- [x] null trakt.tv image urls for all tables
- [x] add migrationService refresh for trending
- [ ] plug in TMDB service for the following image support
  - [x] series posters on favourites page
  - [x] series posters on details panel
  - [x] series banners on favourites
  - [x] season posters on season panel
  - [x] episode posters on episode details panel
  - [x] episode posters on TODO calendar view
  - [x] series background images
  - [x] series posters on trending page
  - [x] series poster on trending search
- [ ] anything else?
- [ ] test, review, improve, have at it!

**Comment by SchizoDuckie** [comment]
oh lol. i think i missed some emails while i started this

**Comment by garfield69** [comment]
Ha!

I'd gotten so used to you dropping a line and then disappearing for months
that I had a go myself.

But please continue, your implementation is bound to be more efficient than
mine :-)

 

  _____

**Comment by SchizoDuckie** [comment]
Yea sorry for that abscence man, life is crazy.
I have some neat stuff in store for you though and i'm working on a way to make sure we can push releases more easily

**Comment by garfield69** [comment]
Cool. So, shall I assign this one to you, and you can finish off your wip?

**Comment by SchizoDuckie** [comment]
sure

**Comment by SchizoDuckie** [comment]
I believe most of it works.

I've built-in this cache so that we can deliver the whole cache blob with the next release. Then we won't have to have all our users hit the update server for data that we have and is fairly recent, and it'll only hit the api for shows that are unknown in the cache.

If we then also patch the trakt-trending-500 with some posters from the /preview route I think all will be smooth

**Comment by garfield69** [comment]
@Js41637  Do you have any idea why the lazy-background directive is not displaying this picture in the sidepanel.episode ? if I paste the url into my browser http://assets.fanart.tv/fanart/tv/78901/tvthumb/S_78901 (1).jpg i get a picture.
It's not like DuckieTV got a 404 and loaded a duck, it's just a clear transparent image?!?!

**Comment by garfield69** [comment]
oops, forgot the example:
http://i.imgur.com/3isSm4s.png

**Comment by SchizoDuckie** [comment]
Looks like that url just needs to be urlencoded. it has spaces in it

**Comment by garfield69** [comment]
@SchizoDuckie  that is what i thought at first, but this still fails
![image](https://cloud.githubusercontent.com/assets/6933240/20208117/c6b1a90c-a850-11e6-934f-9fe85babb349.png)
its beyond my understanding.

**Comment by Js41637** [comment]
I dunno, I did a quick test and it loads fine for other series but they don't display for Supernatural.
Although it doesn't load actual episode thumbs? It's just an artwork in the size of a thumb which doesn't seem very useful? What's the point of having them if its just an artwork?

Side note: these images load a lot slower than TMDB 🙁

**Comment by garfield69** [comment]
@SchizoDuckie  A reminder to sync before you start to do more work on #780, I've made some fixes, minor enhancements, and added a fanart seed-file for first time installs.

**Comment by SchizoDuckie** [comment]
@garfield69 I decided to remove the immediate fetch of fanart inside the trakttvv2.js sine it basically creates an n^2 delay before returning results.

Instead I cahged the serieheader directive so that it can load fanart asynchronously from thedb

**Comment by SchizoDuckie** [comment]
@garfield69 I think it's done with this. give it a good kicking please

**Comment by garfield69** [comment]
latest Nightly 20161113 (with https://github.com/DuckieTV/Nightlies/commit/525ba8064fde829f72383ea9b4924fbac4d1df98) Failed to load resource: net::ERR_FILE_NOT_FOUND file:///C:/Users/<username>/AppData/Local/Temp/nw2460_22335/fanart.cache.json
- [ ] add fanart.cache.json to build scripts

**Comment by SchizoDuckie** [comment]
@garfield69 how is xem-mappings.js used? I don't see it referenced anywhere. (also, why is it not a .json file and we have the online xem-cache.json right)?

**Comment by garfield69** [comment]
Your are quite right. I included it because I saw it in the main folder which looking at the name for the fanart cache file, and it had data in it, but I just did a searched of source, and I can not find  xem-mappings.js referenced anyplace. It must be an artefact of an early xem prototype that has not been clean up. I shall delete it.

**Comment by garfield69** [comment]
testing check list:    
- [x] for each test, check that posters are available in favourites, trending and trending search, and examine the log for any problems.    

(using the standalone nightly 20161113 without the fanart.cache.json seed file is not going to test _all_ of the fanartService, but it does test nearly everything else).    
- [x] 1.1.2 standalone with DB data -> nightly 20161113    
- [x] 1.1.3 standalone with DB data -> nightly 20161113    

(Using the dev source enables testing of the fanart.cache.json seeding)    
- [x] 1.1.2 with DB data (dev source) -> latest duckietv dev source    
- [x] 1.1.3 with DB data (dev source) -> latest duckietv dev source    
- [x] latest duckietv dev source -> import using a 1.1.3 backup    

- [x] had some problems with the dev source runs, with the fanart initialisation trying to preload before the CRUD had finished creating the fanart table.     
   -[x] Solved it by holding off on the migrationService 114refresh by a couple more seconds.     
   
All tests completed successfully.    

- [ ] once the next standalone nightly 20161114 is available, test that against  a 1.1.3 standalone with DB data.

**Comment by SchizoDuckie** [comment]
Closing this as fixed, works smooth on all situations i tested, both new and existing instances in standalone as well as web.
