### ISSUE TITLE
auto-download 

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#781]
as raised in this Reddit https://www.reddit.com/r/duckietv/comments/56y1dc/autodownload_options/

lotn2635599:
>was wondering if there is a way to customize the auto-download. i like the fact that it will use the global options, but as for poling every 15 minutes not so much. i'd like to be able to tell it exactly when to do search for a show. when a show is on by dtv at 1700 there is no reason to start searching for it before 1815, cause most times it's not going to be found till at least 10 minutes after it finished airing. for dtv to start poling for the show as soon as it starts airing or 15 minutes into it airing is simply a waste of bandwidth. also would like a per show option for using auto-download. this would solve a problem with shows like "the fall" that show being aired earlier in the week and actually don't hit the torrent sites till later in the week. we can set shows like this to auto-download at a certain time and date so we don't accidentally forget about it, and leave other shows to manually download.

**Comment by 2635599** [comment]
closed all i saw for the autodownload delay was for minutes. was hoping to get days as well. really useful for shows like the fall and ripper street.

**Comment by 2635599** [comment]
unless you changed something in today's build which i haven't downloaded

**Comment by garfield69** [comment]
While the amount you enter may be in minutes, the maximum you can use is governed by the number of days you have set your auto-download scan period to.     
So, for example, if you set auto-download to scan back for 7 days, then you can set the delay on the global settings and the custom settings for each series to 10080 minutes.

**Comment by 2635599** [comment]
scan back? i figured i'd be able to click a show, choose autodownload, and set a day and time, not calculate minutes

**Comment by garfield69** [comment]
but the series custom delay period applies to all episodes in the series, so a date in this context does not make sense.

**Comment by garfield69** [comment]
oh I see. you said day, not date. my bad. i'll look into the input form and see what can be done.

**Comment by 2635599** [comment]
i'm assuming from the time above that i want to wait and download the nightly for tomorrow?

**Comment by garfield69** [comment]
Nope. The last change went in 2 days ago, and the ticket was set to 'ready for testing' at that time.
so this morning's build should have all the latest changes for this ticket. I've completed my testing, hence the closure of this ticket.     
It pays not to rely on the email notifications, but to look at the ticket live on github web to see the activity.

**Comment by 2635599** [comment]
i did check here and at the time it said the ticket closed 27 minutes ago. github bust have a delay between your request to close and actually closing it. i'll download and check it out. thanks
