### ISSUE TITLE
DuckieTV no longer searches piratebay

### ISSUE THREAD

**Issue by Taurick** [SchizoDuckie/DuckieTV#785]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmdd)**
Stable 1.1.3

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 7

**Describe the problem you are having and steps to reproduce if available**
Cannot currently search piratebay. Figured the site was down again and browsed to it to check it out, site is up but now does some sort of 'browser check' as a measure to prevent DDoS.  I can only assume the DuckieTV client doesn't pass this check for some reason.

To reproduce: Search any torrent on piratebay. Search will then get stuck on 'Searching the piratebay, please wait''

**Attach any DuckieTV statistics or Developer Console logs if available**

N/A

**Comment by garfield69** [comment]
Yeah, TPB has been under attack the last several days, and they have turned on DDoS protection to get some relief.      

However this effectively disables access by DuckieTV via the *thepiratebay.org* or *thepiratebay.se* addresses.      

But there are some TPB proxies that work for DuckieTV to will restore access to TPB for you.     

I've successfully been using *https://pirateproxy.se* to do my DuckieTV searches in the last hour.     

To set your DuckieTV to use this proxy,  visit the *Settings, Torrent Search Engines* side panel, and scroll down to the *The Pirate Bay* section.    
In the *PirateBay Main Mirror:* input box, replace *https://thepiratebay.org* with *https://pirateproxy.se* and press the *Validate And Save* button.      
If successful you should see a *Saved!* in the log box underneath.     

If unsuccessful, you can try the *Find a Random Mirror* button. Each click looks up 3 random mirrors and tries them out in turn. Just keep clicking and with a bit of luck you are bound to find a mirror that works in your local region.

**Comment by garfield69** [comment]
Assuming no news is good news I'm closing this ticket. If the OP still has a problem we can always reopen the ticket.
