### ISSUE TITLE
1337x Magnet torrents not working

### ISSUE THREAD

**Issue by lonelyfairie** [SchizoDuckie/DuckieTV#786]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone 

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmdd)**
latest github release, Latest commit 0066fbe

**What is your Operating System (Windows, Mac, Linux, Android)**
Mac OS X Sierra

**Describe the problem you are having and steps to reproduce if available**
Magnet links are not working for 1337x from within duckie, it says torrent not found on client and it is never added to utorrent. I tested the magnet links on their website and the first click doesn't add the torrent, the second time you click it does (it might be some kind of add loading thing being blocked by adblock)

**Comment by garfield69** [comment]
Hah. I think I found the problem.    
I bet you are using the DuckieTV uTorrent WEB UI client interface, aren't you?     
In my testing I discovered that the problem disappears if I use either the uTorrent API, or another client like qBittorrent.    
I looks like the uTorrent WebUI client interface is needlessly doing an additional encodeURIComponent on the command channel. I don't think it need to do that all.    
Need to keep an eye out for any downstream impact on other uTorrent webui commands. Testing so far has not shown any issues.

**Comment by lonelyfairie** [comment]
Yes, I am in fact using the utorrent webUI sorry I forgot to mention that bit of info.
Thanks for working on this :)

Have a great weekend!

**Comment by garfield69** [comment]
@lonelyfairie  I had not spotted this earlier during testing, but all the magnets being submitted to uTorrent WEBUI since c6a6af2 are missing their trackers!!.
I've just fixed this, so you may want to sync your github so you can get the latest fix (and also independently confirm all is working as it should ;-)

**Comment by lonelyfairie** [comment]
@garfield69 I just synced with github, I didn't realize this either, since I normally use rarbg for all torrents except some reality shows that aren't available there but on 1337x, when I tested the magnets I already had those shows downloaded so I only tested that the magnet worked I didn't actually download the files. I will keep an eye out for the trackers :)

**Comment by lonelyfairie** [comment]
@garfield69 It seems that the latest commit broke the fix, I am again unable to use magnet links for 1337x :( I tested and was able to download the same torrent via magnet link using ExtraTorrent instead.

**Comment by garfield69** [comment]
Well that is unexpected. Obviously required more investigation.

**Comment by garfield69** [comment]
@lonelyfairie  ok, came up with an alternate solution, lets see if this works better. Let me know how it goes.

**Comment by lonelyfairie** [comment]
@garfield69 That worked :) Magnets go correctly to utorrent with all trackers included.
