### ISSUE TITLE
make min-seeders a global settings to that it can be used by torrent search dialogues

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#787]
as suggested by this Reddit https://www.reddit.com/r/duckietv/comments/59u0q6/feature_request_move_global_settings/d9bx4nj/    

> the minimum seeds under autodownload is great, but only applies to shows you have set to autodownload. what i'd to be able to do is go into global settings and set minimum seeds for shows that i manually click on and choose find torrent. this way every time i click on find torrent only torrents with that minimum seed count will show.     

I'm going to suggest a variation on this request, to conform to the existing use of global settings:  
We move the min-seeders out of the auto-download settings side panel, place it in the torrent-search-engines as a global min-seeders, and add a checkbox to the torrent-dialogues advanced-settings drop-down menu so that the user can choose to use the min-seeders as a filter.

**Comment by 2635599** [comment]
i've had a rethink about this and believe that min seeders should be under global not the autodownload settings. so instead of adding another min seeder to global i suggest completely moving it from auto to global. now for auto i'd like to make the suggestion that we get a search so we can do auto for individual shows right from there.

**Comment by 2635599** [comment]
any news on this?

**Comment by SchizoDuckie** [comment]
I think the combination of your and garfield69's suggestion makes sense, to move it into the torrent dialog and make the settings global like the require and ignore keywords. 

That makes everything more logically structured.

**Comment by 2635599** [comment]
nice will give a run. thanks
