### ISSUE TITLE
Please don't download WMV

### ISSUE THREAD

**Issue by giantmike** [SchizoDuckie/DuckieTV#789]
The auto downloader grabbed a WMV file. On the Mac, that is pretty silly. Alex cannot read it. Even VLC cannot read it.

Please add an option to not download that type of file.

**Comment by garfield69** [comment]
When the auto-download examines the torrent search list, it has only the *Torrent Name* to work with.    
DuckieTV does not have access to the *content* of the torrent itself, so cannot choose to exclude that torrent from being downloaded by examining the torrent *file list* within the torrent itself.     

If the torrent *name* does not include *WMV*, there the is not much that can be done, sorry.     

If you are on DuckieTV **1.1.3** then normally I would recommend you upgrade to **1.1.4**, but I don't have a release date for you at this stage, so I would suggest you upgrade to the latest DuckieTV Development Nightly, which is essentially 1.1.4 Work In Progress.

So if torrent name does have *WMV* in its *name*, then the latest version can exclude that torrent using the *Global Exclude List*, once of many new features introduced after 1.1.3, that you can configure in DuckieTV's settings.     

You can grab the latest release at https://github.com/DuckieTV/Nightlies/releases, and if you need help installing a nightly, you can find the wiki guide at https://github.com/SchizoDuckie/DuckieTV/wiki/How-to-install-development-versions-of-DuckieTV.

**Comment by 2635599** [comment]
i'll be blunt it's a RARE instance when something is in wmv format just deal with replacing manually
