### ISSUE TITLE
American Dad Season 13/14

### ISSUE THREAD

**Issue by lonelyfairie** [SchizoDuckie/DuckieTV#792]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone
**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmdd)**
commit c227a3d

**What is your Operating System (Windows, Mac, Linux, Android)**
Mac

**Describe the problem you are having and steps to reproduce if available**

There was a change in the season numbering some time ago for American Dad which tvdb refuses to correct (already been discussed there) which is basically that they are listing the latest season as 14 and releases from torrents are using the new numbering which will put the season as 13. 

This is messed up in the tv database as well as imdb which also lists the current season as 12 for example, this is the episode that aired yesterday called Father's Daze:

http://www.imdb.com/title/tt5527362/?ref_=ttep_ep1 > Listed as **12**
http://thetvdb.com/?tab=episode&seriesid=73141&seasonid=673132&id=5670286&lid=7 > Listed season **14**
https://showrss.info/browse/271 > Listed as season **13**

I know this is something unusual for a show and the thing is as of now American Dad is not being able to be downloaded by Duckie because of this, I have to manually search for each episode and change the season number on the search box. 
Is there any fix you could implement for this?

This actually started happening last season but at the moment I didn't have time to report it sorry.

**Comment by Js41637** [comment]
Well we're definitely not going to manually code in a fix for shows. We do use XEM which might be able to fix this, tbh I don't really know how it works. @garfield69 will be here soonish and should know more.

**Comment by garfield69** [comment]
Yup. *American Dad* is covered by thexem.de, and the season 14 cross references for the first 7 episodes were only added on 2016-11-08 02:57:05 UTC.     
I think that SchizoDuckie's buildbot runs daily to update the github DuckieTV/xem-cache repository ( @SchizoDuckie could you confirm please? ), which is what the DuckieTV app works with to resolve the cross referencing.    
The buildbot last ran its update at 2016-11-08 02:30:00 UTC, so it missed out by 27 minutes from picking up the latest *American Dad* xem update!     

So assuming I'm right about the daily updates, the cache should be updated again within the next 9 hours or so, after which the DuckieTV app should be able to correctly build the s14e01 search string as s13e01

**Comment by SchizoDuckie** [comment]
Correct. Xem cache update runs around at the same time as the nightly
builds themselves

Op 8 nov. 2016 7:04 p.m. schreef "garfield69" <notifications@github.com>:

**Comment by garfield69** [comment]
@SchizoDuckie  the buildbot has just updated the duckietv/xem-cache repository, however the *American Dad* cache 73141 is still not reflecting what I can fetch manually using http://thexem.de/map/all?id=73141&origin=tvdb&destination=scene    
Could you take a look please?

**Comment by lonelyfairie** [comment]
It still isn't picking up this show even after a week.

**Comment by garfield69** [comment]
https://github.com/DuckieTV/duckietv-builder/commit/90eebb8379ecd1c19aa8172838d90358e7984881 resolves this issue

**Comment by lonelyfairie** [comment]
Just to confirm it is working correctly, now it searches as American Dad S13E07 instead of 14. Thanks Garfield!
