### ISSUE TITLE
"i'm done adding shows" tooltip is still annoying

### ISSUE THREAD

**Issue by SchizoDuckie** [SchizoDuckie/DuckieTV#795]
![image](https://cloud.githubusercontent.com/assets/111710/20284041/cb9660ee-aabb-11e6-8f0c-fdcf362b0c33.png)
This tooltip on this thing still keeps borking the interactions on hover. should we drop it all together?

**Comment by Js41637** [comment]
Yeah I don't know why it's always broken

**Comment by SchizoDuckie** [comment]
It must be some relative/absolute/relative positioning thing

**Comment by garfield69** [comment]
re-opening in order to test if ccb5564885f9f2efa38342a0b1fab2c8bd1f2c05 works for this.
