### ISSUE TITLE
Allow self sign certificates in standalone version

### ISSUE THREAD

**Issue by lightglitch** [SchizoDuckie/DuckieTV#799]
When you connect to a torrent client using https with self sign certificate doesn't connect, gives:

net::ERR_INSECURE_RESPONSE

error.

**Comment by lightglitch** [comment]
Using "chromium-args": "--ignore-certificate-errors" in package.json is a possible solution.

**Comment by SchizoDuckie** [comment]
Sorry, there is nothing we can do about this, this is too deep inside
chromium to even think about touching.

I suggest you swap out your self signed cert for one provided by let's
encrypt, this way you should be okay.

Op 18 nov. 2016 6:19 p.m. schreef "Mário Franco" <notifications@github.com>:

**Comment by SchizoDuckie** [comment]
Ignoring certificate errors is a really bad thing to do, I do not recommend
this and this will never be a solution that we will implement.

Op 18 nov. 2016 6:21 p.m. schreef "Jelle Ursem" <schizoduckie@gmail.com>:

**Comment by SchizoDuckie** [comment]
Closing as wontfix
