### ISSUE TITLE
Scene Name Exception - "The Ultimate Fighter Live SxxExx" -> "The Ultimate Fighter SxxExx"

### ISSUE THREAD

**Issue by macst34** [SchizoDuckie/DuckieTV#800]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Chrome Ex

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmdd)**
... v1.1.3

**What is your Operating System (Windows, Mac, Linux, Android)**
win 10

**Describe the problem you are having and steps to reproduce if available**
scene name.

previous  "The Ultimate Fighter Live SxxExx" 
should be "The Ultimate Fighter SxxExx"

**Attach any DuckieTV statistics or Developer Console logs if available**
n/a

**Comment by garfield69** [comment]
b3b398b80370c05d2308a708df6d7d6e844abf95
