### ISSUE TITLE
Linux 64bit version won't install

### ISSUE THREAD

**Issue by sd5445** [SchizoDuckie/DuckieTV#801]
First of all, I'd like to thank you for all the work you've put into this great app. It's difficult to find a Trakt compatible standalone app for Linux. This is exactly what I was looking for.

**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmdd)**
...Stable 1.1.3

**What is your Operating System (Windows, Mac, Linux, Android)**
...Linux Mint 18 64bit

**Describe the problem you are having and steps to reproduce if available**
...The setup file won't install the app. I had a look into the setup file. I think you forgot to change PKGNAME to DuckieTV everywhere in the setup file as well as in all the other files (launcher, menu shortcut, etc). The pixmap folder with the pixmap image is also missing from the share folder.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by SchizoDuckie** [comment]
I've just fixed the .deb builds for nightlies and will re-enable those somewhere this weekend. That should make installation a breeze!

**Comment by garfield69** [comment]
@sd5445  please try the latest x64 debian nightly package at https://github.com/DuckieTV/Nightlies/releases and let us know how the installer goes for you. Thanks.

**Comment by sd5445** [comment]
I have a linux Mint 18.1 64bit os. The 
"DuckieTV-01122017-ubuntu-x64.deb" nightly build installed flawlessly.

Thanks again for this great app. I couldn't image life without it, now.
