### ISSUE TITLE
Trakt.TV stopped serving images

### ISSUE THREAD

**Issue by gillthunder** [SchizoDuckie/DuckieTV#802]
has the Trakt.TV stopping to serve images problem been fixed yet?

**Comment by garfield69** [comment]
>has the Trakt.TV stopping to serve images problem been fixed yet?

yes it has. We have found an alternate image source and have build the required plugin for DuckieTV.  Schizoduckie is busy upgrading the build tools, after which he should be able to work on the next DucckieTV release, but I don't have a release date for you yet, sorry.    
If may wish to upgrade to a DuckieTV Development nightly, which is essentially DuckieTV 1.1.4 Work In Progress. This has the new working image service going.    
Located at https://github.com/DuckieTV/Nightlies/releases/tag/nightly-11132016    
Wiki on installing a Nightly (should you need it) can be found at https://github.com/SchizoDuckie/DuckieTV/wiki/How-to-install-development-versions-of-DuckieTV
