### ISSUE TITLE
Tracker suggestion: IPTorrents.com

### ISSUE THREAD

**Issue by tapplz** [SchizoDuckie/DuckieTV#803]
**What build of DuckieTV are you using (Standalone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmdd)**
UserAgent	DuckieTV Standalone 20161113
Platform, Vendor	Win32, Google Inc.

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 10 64bit

I don't know if this was addresses previously (searches on the forum didn't produce anything), but could IPTorrents.com be added as a tracker? I tried added it manually but couldn't figure out what DuckieTV was asking for. I can supply an invite to the dev's via pm for this purpose.

**Comment by garfield69** [comment]
@tapplz , as you may know, the *Custom Search Engines* project https://github.com/SchizoDuckie/DuckieTV/issues/18 is still a work in progress and not yet complete. But once finished we will revisit this request. I don't have an ETA on the release date.

**Comment by garfield69** [comment]
You should now be able to access any of the open/semi-private/private trackers that the Jackett proxy has available, as a DuckieTV Search Engine, starting with the latest Nightly 31-05-2017 01:55:49 at https://github.com/DuckieTV/Nightlies/releases       
See wiki https://github.com/SchizoDuckie/DuckieTV/wiki/Using-Jackett-with-DuckieTV for details on setting up Jackett with DuckieTV.       
Jackett will be included in the next Stable Release of DuckieTV 1.1.5 whenever that gets published.
