### ISSUE TITLE
Autodownload: Search by date, add show to exception list

### ISSUE THREAD

**Issue by tapplz** [SchizoDuckie/DuckieTV#804]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone, UserAgent	DuckieTV Standalone 20161113 Platform, Vendor	Win32, Google Inc.

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 10 64bit

**Describe the problem you are having and steps to reproduce if available**
Naked News searches by episode number but results are found only by YYYY-MM-DD format

I've seen on reddit in the past this was handled by an exception list, but I've checked the repo and this appears to handled differently now. Figured this was the best way to have this exception added.

**Comment by garfield69** [comment]
>Naked News searches by episode number but results are found only by YYYY-MM-DD format
>I've seen on reddit in the past this was handled by an exception list, but I've checked the repo and this appears to handled differently now. Figured this was the best way to have this exception added.    

The exception lists reside at https://github.com/DuckieTV/SceneNameExceptions, in this way the app can keep up to date by fetching those lists every 24 hours.    
I have added *Naked News* to the date exceptions list. Cheers.
