### ISSUE TITLE
Thumbnails aren't showing

### ISSUE THREAD

**Issue by hgshoush** [SchizoDuckie/DuckieTV#805]
Chrome Extension / Browser Action
v1.1.3
Windows

None of my show's thumbnails are showing. All I can see is the duck icon.

**Comment by garfield69** [comment]
the provider we used with duckietv 1.1.3 has discontinued their image service.   
we have found an alternate supplier, and are putting the final touches to duckietv 1.1.4 which we will release once we are done.
