### ISSUE TITLE
Wrong Air Date for TV Show "NCIS: New Orleans"

### ISSUE THREAD

**Issue by gngs0419** [SchizoDuckie/DuckieTV#807]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmdd)**
Stable 1.1.3

**What is your Operating System (Windows, Mac, Linux, Android)**
Linux

**Describe the problem you are having and steps to reproduce if available**
TV Show "NCIS: New Orleans" is showing on the wrong air date - Tuesday instead of Monday (the actual air date), as a result it downloads the next day.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
https://github.com/SchizoDuckie/DuckieTV/wiki/How-to-make-corrections-to-shows-on-DuckieTV
