### ISSUE TITLE
Not sure about using logos or clearart for posters when there is none

### ISSUE THREAD

**Issue by Js41637** [SchizoDuckie/DuckieTV#809]
While a smart idea, the current CSS is designed for posters and as such does not work at all with png logos, not to mentioned they are stretched to fit a poster size. I think we should just stick with the duck.

![image](https://cloud.githubusercontent.com/assets/6258213/21467254/163f4748-ca3b-11e6-8bda-7e8c7b7813e3.png)

And these two actually don't look too bad but I have some others in my list that look really bad.
![image](https://cloud.githubusercontent.com/assets/6258213/21467270/3cc8dd0c-ca3b-11e6-850c-81e6ec16d586.png)

**Comment by garfield69** [comment]
Since I prefer a logo (even a warped one) over a page full of duckie stand-ins for missing posters, I am going to implement a setting to allow users to decide which stand-in to use.

**Comment by SchizoDuckie** [comment]
Please, no setting for this. Rather try to scale it properly using
background-size cover. If we keep turning tiny stuff that nobody wants to
even think about into settings people will get totally u lost imo.

Oh and. Merry Xmas y'all!

Op 25 dec. 2016 7:49 p.m. schreef "garfield69" <notifications@github.com>:

**Comment by Js41637** [comment]
It will be impossible to style as you cannot tell if it has a poster or not, if you add more checks you will just be ruining performance.

**Comment by SchizoDuckie** [comment]
![image](https://cloud.githubusercontent.com/assets/111710/21780460/efe9e4f4-d6ab-11e6-90a2-cdc6f647fb1c.png)
I'd say that's the behavior we want :sweat_smile:

**Comment by Js41637** [comment]
Should note that making specific changes to poster CSS will require updating the rest of poster CSS as now the sizes do not line up or the hover effects.
![image](https://cloud.githubusercontent.com/assets/6258213/21896010/e2ad2b68-d938-11e6-8b5e-8d1a286e2231.png)
Ideally also find a way to fix the hover effect for logos 
![image](https://cloud.githubusercontent.com/assets/6258213/21896033/fa03a666-d938-11e6-9236-f8444afe3337.png)

**Comment by SchizoDuckie** [comment]
I think we should change the hover effect to just a border instead of a
background or something, that'd fjx a lot

Op 12 jan. 2017 4:35 p.m. schreef "Js41637 ftw" <notifications@github.com>:

**Comment by Js41637** [comment]
:/ yeah well, you still have to fix everything else as they still aren't aligned. 
![image](https://cloud.githubusercontent.com/assets/6258213/21896270/e890d27c-d939-11e6-8109-879a61a51d1d.png)
