### ISSUE TITLE
DuckieTV-01052017-ubuntu-x32.deb install on ubuntu 15 generates warning popup

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#811]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmdd)**
Nightly 20170105

**What is your Operating System (Windows, Mac, Linux, Android)**
ubuntu 15.10 x32

**Describe the problem you are having and steps to reproduce if available**
the debian install package DuckieTV-01052017-ubuntu-x32.deb generated the following popup during the installation on my ubuntu 15.10 sandbox
![image](https://cloud.githubusercontent.com/assets/6933240/21728841/264946a8-d4ad-11e6-923c-f32bde9e7cf1.png)
I clicked on the *Ignore and Install* in order to continue the installation, which completed successfully.   
~~I note however that I cannot find any menu entry or icons on the desktop related to DuckieTV.    
I was able to find the program in the `usr/bin/` folder and start the program from there, so the install of the binaries and dependants appears to have been completed.~~ [edit] found the icon when I used the *search your computer* and was able to launch the program.

Is it possible that this debian package is not compatible with ubuntu 15, that is, it is built for newer ubuntu versions?

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
BTW, the nightly build for 02052017 appears to have crashed during the ubuntu-x32 build, the .deb is only a few K big, and many other builds are missing.
![image](https://cloud.githubusercontent.com/assets/6933240/21739813/37e9e562-d50b-11e6-897a-bcad70b7b285.png)

**Comment by garfield69** [comment]
Urg. My Ubuntu 15 woes continue...  Tried to install DuckieTV-20170205-ubuntu-ia32.deb and got this:
![image](https://cloud.githubusercontent.com/assets/6933240/22677395/03ad6580-ed57-11e6-843e-e7f602bf6fdd.png)

**Comment by SchizoDuckie** [comment]
Thanks. I will look into it tonight.

**Comment by SchizoDuckie** [comment]
Fixing dis is so ez now <3 
https://github.com/DuckieTV/duckietv-builder/commit/5c642aacc2679a39828c8dbf6f628e959276992a

**Comment by SchizoDuckie** [comment]
Let me know if it works (rescheduled the builder for 0:00 ) and close this at-will

**Comment by garfield69** [comment]
x32 does not work either.
![image](https://cloud.githubusercontent.com/assets/6933240/22717091/fddf9d24-edfd-11e6-8a14-57fe2a5b76fb.png)
maybe my Ubuntu 15.10 is stuffed... it's probably time I upgraded to Ubuntu 16.x?

**Comment by garfield69** [comment]
Oh wait. if nwjs are only building Intel Architechture 32 bit versions, then I see the problem now....
![image](https://cloud.githubusercontent.com/assets/6933240/22720074/a013b2e2-ee0d-11e6-892d-71f7de2ecd1e.png)

**Comment by garfield69** [comment]
suggest reverting x32 back to ia32 if you like.    
I've got an intel dual core motherboard cpu and memory sitting on a shelf, its about time i retired the old amd64 and rebuild my sandbox pc. Upgrade to Ubuntu 16 while I'm at it.

**Comment by SchizoDuckie** [comment]
I dont understand. An x32 platform should support an x32 build...

**Comment by garfield69** [comment]
>An x32 platform should support an x32 build...     

You are absolutely right.    
I can only conclude that I have some how borked (to use your favourite fubar phase) by lib32 libraries somehow. I was farting around with everything a while back when I was trying to get the rTorrent working.      
Which is why I'm keep to reset and load Ubuntu 16. Then at least I'll have a place to start from, and I can then, if the duckietv nightly installs still don't work, point the blame back at your builds :-b

**Comment by garfield69** [comment]
@SchizoDuckie  Progress!!.    
I grabbed Ubuntu 16.10 and did a side-along install on my sandbox.    
Then I tried installing https://github.com/DuckieTV/Nightlies/releases/download/nightly-20170210/DuckieTV-20170210-ubuntu-x32.deb, but I still got the *Wrong Architecture x32* error, but this time Ubuntu 16 helpfully told me that this could be fixed with *dpkg --add-architecture*.     
So I opened a terminal, and did a `sudo dpkg --add-architecture x32` and afterwards I was able to install the DuckieTV Nightly debian package without any warnings, errors or popups \o/      
I repeated the dpkg command on my Ubuntu 15.10 and I was able to install it there too (Good to know by Ubuntu 15 is not *borked* after all) \o/ \o/     
 
But when I used the DuckieTV Icon to start it, it pulsed white five or six times and then nothing was launched. Same on Ubuntu 16.     
So back at the terminal I changed dir to /usr/bin/ and started DuckieTV and got this message `/opt/DuckieTV/DuckieTV: line 7: /opt/DuckieTV/duckietv-bin: No such file or directory`    
Looking at the content of the /opt/DuckieTV folder I find DuckieTV-bin.     
So it seems to me that we need to either:    
-  change line 7 in https://github.com/DuckieTV/duckietv-builder/blob/master/platforms/debian/opt/DuckieTV/DuckieTV (and https://github.com/DuckieTV/duckietv-builder/blob/master/platforms/linux/DuckieTV/DuckieTV) to `exec -a "$0" "$HERE/DuckieTV-bin" "$@"`     
OR     
- change line 49 in https://github.com/DuckieTV/duckietv-builder/blob/master/platforms/debian.js (and https://github.com/DuckieTV/duckietv-builder/blob/master/platforms/linux.js) to `mv(ARCH_BUILD_DIR + "/nw", ARCH_BUILD_DIR + "/duckietv-bin");`     

I don't know which is better or if it make a problem for your x64 builds, so I leave this up to you. :-)
