### ISSUE TITLE
Logos disappeared

### ISSUE THREAD

**Issue by guisudbra** [SchizoDuckie/DuckieTV#812]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
... Browser Action

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmdd)**
... 1.1.3

**What is your Operating System (Windows, Mac, Linux, Android)**
... Windows

**Describe the problem you are having and steps to reproduce if available**
... All the logos of all my series disappeared, only the duck tv logo is used instead.

**Attach any DuckieTV statistics or Developer Console logs if available**
...
![error](https://cloud.githubusercontent.com/assets/24985141/21747959/999f295e-d545-11e6-8c3b-7705ff53d1be.png)

**Comment by garfield69** [comment]
the provider we used with duckietv 1.1.3 has discontinued their image service.
we have found an alternate supplier, and are putting the final touches to duckietv 1.1.4 which we will release once we are done.     
For further details, read https://www.reddit.com/r/duckietv/comments/5adliq/trakttv_stops_serving_images_1st_nov_2016/     

At this stage you ave two choices:     
1. You can wait for *DuckieTV 1.1.4* to be released, which will have the updated support for the new KAT. However, I don't have a release date for you at this time, sorry.     
2. OR you can grab the latest *DuckieTV Nightly*. This is Development DuckieTV, essentially 1.1.4 Work in Progress. It has a working version of the new KAT Search Engine.     
However, unlike DuckieTV Standalone, the Nightly Chrome Extension package is not as straight forward to install, so you may first want to read this Nightly Installation Wiki https://github.com/SchizoDuckie/DuckieTV/wiki/How-to-Install-a-Development-version-of-the-DuckieTV-Chrome-Browser-Extension-NIGHTLY before proceeding.    
If you decide to go ahead, then you can find the latest Nightly download at https://github.com/DuckieTV/Nightlies/releases/tag/nightly-01052017
