### ISSUE TITLE
Season 10 - The Big Bang Theory

### ISSUE THREAD

**Issue by millilla** [SchizoDuckie/DuckieTV#813]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standlone
...

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmdd)**
sobre DuckieTV v1.1.3
...

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 10 Pro
...

**Describe the problem you are having and steps to reproduce if available**
The Big Bang Theory Season 10 aren't updated. Now they are playing S10E12 and in the DuckieTv are in 10x01
...

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
You can try to refresh *The Big Bang Theory* series on DuckieTV by using the **Refresh** button on the *Series Details Panel*    
![image](https://cloud.githubusercontent.com/assets/6933240/21755029/f47c4b64-d670-11e6-9655-cf97e5f5314c.png)
Let me know if it fixes your problem or not.

**Comment by garfield69** [comment]
Closing this ticket on the assumption that the OP followed my suggestion and resolved the issue.     
If the OP ever replies to the contrary we can always re-open the ticket.
