### ISSUE TITLE
QNAP QTS 4.3.2 Beta

### ISSUE THREAD

**Issue by gemstar2k** [SchizoDuckie/DuckieTV#814]
Request QNAP NAS build for QTS 4.3.2 beta x86_64.  The current x86_64 QTS build is restricted by the version of HD Station running on the system.

**Comment by SchizoDuckie** [comment]
I have no idea what this means. Please enlighten me.

**Comment by gemstar2k** [comment]
Ah.  It would appear that someone has compiled the source for QNAP NAS here: http://www.qnapclub.eu/index.php?act=detail&qpkg_id=360

I mistakenly thought it came directly from your project.

Absolutely love DuckieTV but prefer to have it running as a web service on a local (NAS) server for optimum automation.

Thanks for your quick response.

**Comment by gemstar2k** [comment]
Sorry, correct URL: http://www.qnapclub.eu/index.php?act=detail&qpkg_id=347
