### ISSUE TITLE
Cannot connect DuckieTV nightly 20170105 with uTorrent API

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#815]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmdd)**
Nightly 20170105

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows

**Describe the problem you are having and steps to reproduce if available**
As per this Reddit https://www.reddit.com/r/duckietv/comments/5mr29m/nightly_20170105_win_x64_standalone_broke_my/     
>attempted multiple times to reauth utorrent to no avail. Utorrent is receiving the request and the authorization pop is working, but even after hitting yes and restarting duckietv, it still does not communicate with utorrent.

**Attach any DuckieTV statistics or Developer Console logs if available**
I have tested this with the latest github source running with nwjs 19 and I also cannot connect via the uTorrent API. Will set up some debugging and see if I can figure out what is going on.

**Comment by SchizoDuckie** [comment]
Windows firewall?

Op 8 jan. 2017 6:38 p.m. schreef "garfield69" <notifications@github.com>:

**Comment by garfield69** [comment]
the problem is caused by commit e2a8ab1146ae8dc1f3c45c3576b15b7deb07e714 which upgraded angular from 1.5.6 to 1.5.10     
The quick solution is to reverse this commit, which solves this problem when testing in my sandbox .     

I think the problem is that our customised copy of the $httpBackend  in app.authHttpBackend.js is no longer compatible with angular's 1.5.10 version anymore, causing the callback id to return NAN and thus loosing the reference to the returned uTorrent token id that we get back from the authorisation request we make to uTorrent.    
![image](https://cloud.githubusercontent.com/assets/6933240/21753464/d94d194a-d652-11e6-8e22-f2be2ad0f413.png)

I am going to try to apply schizoduckie's authorisation patch on top of the new angular's $httpBackend code and see if I can make it work again.
