### ISSUE TITLE
How to install nightlies

### ISSUE THREAD

**Issue by rcthorne** [SchizoDuckie/DuckieTV#819]
I'm currently on the latest Non beta release. I'm using MacOS. I'm trying to install the latest nightlies like I used to, but now it downloads  nw.js and I have no idea how to proceed.   Please help!!!

**Comment by garfield69** [comment]
Ah. You caught us in the middle of updating the buildBot that creates the distribution packages for the Nightly. It is my understanding that the osx nightly builds are currently broken.     
@SchizoDuckie  is working on the buildbot, I don't have an ETA for you sorry.

**Comment by rcthorne** [comment]
Ok thanks. Thought I was doing something wrong.  I'll stand by.

**Comment by SchizoDuckie** [comment]
I have just published a fresh prerelease OSX nightly to the latest one available: https://github.com/DuckieTV/Nightlies/releases/tag/nightly-01122017 

Please check it out if you have the time and let us know if you find any problems :+1:
