### ISSUE TITLE
Scene Name Exception -3% ->3.percent

### ISSUE THREAD

**Issue by macst34** [SchizoDuckie/DuckieTV#821]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
chrome ex

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmdd)**
v1.1.3

**What is your Operating System (Windows, Mac, Linux, Android)**
win10

**Describe the problem you are having and steps to reproduce if available**
scene name.

previous "The Ultimate Fighter Live SxxExx"
should be "The Ultimate Fighter SxxExx"

**Attach any DuckieTV statistics or Developer Console logs if available**
scene name.

previous "3%"
should be "3.percent"

**Comment by garfield69** [comment]
added *3 percent* to the scene name exceptions list. Your DuckieTV should pick up the update within then next 24 hours.     

Are you referring to http://thetvdb.com/index.php?tab=series&id=75382&lid=7 ?    
The series *The Ultimate Fighter* does not appear to require any scene name exception.

**Comment by garfield69** [comment]
Thinking about *The Ultimate Fighter*, its possible that the series was originally *The Ultimate Fighter Live* on *Trakt.TV* when you added it to your Duckietv *Favourites*,  and that it has been subsequently changed to *The Ultimate Fighter*.     
You can try to **refresh** the series on DuckieTV by using the *Refresh button* on the *Series Details Panel*    
![image](https://cloud.githubusercontent.com/assets/6933240/21755029/f47c4b64-d670-11e6-9655-cf97e5f5314c.png)     
Let me know if that helps.
