### ISSUE TITLE
Auto Update Issue - Solved

### ISSUE THREAD

**Issue by Gecko33312** [SchizoDuckie/DuckieTV#823]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
... Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmdd)**
...Nightly 20170112

**What is your Operating System (Windows, Mac, Linux, Android)**
...
Windows 64
**Describe the problem you are having and steps to reproduce if available**
...auto download is stuck saying last run Jan 14, 2017 5:30:17PM and Next Run Jan 14, 2017 5:45:17 PM it's now Jan 17th...
<img width="1475" alt="screenshot 2017-01-17 12 59 54" src="https://cloud.githubusercontent.com/assets/15131511/22033056/f17a1122-dcb4-11e6-8563-423c4076da7b.png">
<img width="1477" alt="screenshot 2017-01-17 13 00 10" src="https://cloud.githubusercontent.com/assets/15131511/22033057/f1890b6e-dcb4-11e6-899d-4cd0ab5fcecf.png">

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by Gecko33312** [comment]
SOLVED - I had to un authorize utorrent and re-authorize!

**Comment by garfield69** [comment]
Well done! :+1:
