### ISSUE TITLE
Daily download all button

### ISSUE THREAD

**Issue by lightglitch** [SchizoDuckie/DuckieTV#827]
Just like you have the "Mark all downloaded" and "Mark all watched" would be nice to have a "Download all" that downloads the episodes of that day, similar to auto download all in episodes.

**Comment by garfield69** [comment]
Are you aware that DuckieTV already has a daily auto-download feature?    
The service checks every 15 minutes with the default Search Engine for any episode torrents that fit the criteria that you specify in your DuckieTV settings, and it fetches that torrent magnet and passes it to your torrent host. Once your torrent host has downlaoded the episode, DuckieTV then marks that episode as downloaded.     
On DuckieTV 1.1.3 you will find the option the the *Settings, Torrent, Auto-Download* section
![image](https://cloud.githubusercontent.com/assets/6933240/22118734/ca233a74-dedd-11e6-86e7-ffb5ccbb4862.png)
This feature would seem to make your *download all daily* button redundant.... agreed?

**Comment by lightglitch** [comment]
Didn't know that but only downloads episodes from the last 24 hours and because sometimes I don't open ducky in several days (use standalone version) then I have to download them one by one.

**Comment by garfield69** [comment]
If you look closer at the settings picture, you will see that you can adjust the period that the auto-download operates under (second red circle). You can set it to look back up to 21 days, so any episodes that are not already marked as downloaded are checked for available torrents.
