### ISSUE TITLE
Torrent Details Page Improvement

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#828]
Can you add information on the amount of seeders/leeches the torrent has alongside the speed and down percentage.
Thanks

**Comment by garfield69** [comment]
DuckieTV Team, is displaying the seeders and leechers information on the torrent client download monitor useful in any way to the user?    
IMO, the torrent download is already in progress, and the only thing on a user's mind would be ... how much longer before the download is complete. I don't think showing the current seeders and leechers during a download adds anything useful, and only burns a little more resources.     
Opinions?

**Comment by Js41637** [comment]
I don't use the auto download features so my opinion is void.

**Comment by SchizoDuckie** [comment]
Meh, I don't think it'll be really useful either.
