### ISSUE TITLE
DuckieTV wiki Request

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#829]
Can you add a tutorial to the wiki that shows how to compile the nightly source code to the supported executables (EXE, apk, deb, et cetera) or suggest a compiler that can be used.

**Comment by SchizoDuckie** [comment]
I'm currently working on a new build tool that makes that posssible. It is
currently a hacky mess of shell scripts and dependencies.

Op 22 jan. 2017 6:08 p.m. schreef "zero77" <notifications@github.com>:

**Comment by zero77** [comment]
Oh I see, sorry, I didn't realize this would be related to #819 and #798 #822

**Comment by SchizoDuckie** [comment]
Buildbot is done, see http://github.com/DuckieTV/Nightlies/duckietv-builder/ for docs.

**Comment by zero77** [comment]
Thanks
