### ISSUE TITLE
latest release

### ISSUE THREAD

**Issue by gillthunder** [SchizoDuckie/DuckieTV#830]
I was using https://github.com/DuckieTV/Nightlies/releases/tag/nightly-11132016 which is v1.1.4 and it was really amazing but there was a problem and I thought I'd fix it by uninstalling.
After doing that I didn't find the installer on my pc so I searched for it online but all I can find is v1.1.3 and the link above doesn't work anymore and I'm really used to v1.1.4 with all its cool features so how can I download it again.

**Comment by garfield69** [comment]
The buildbot that creates the nightly packages is currently broken. Schizoduckie is taking this opportunity to upgrade the whole enchilada, but i don't have an ETA for you at this time.    

Use https://github.com/DuckieTV/Nightlies/releases/tag/nightly-01122017 which is the latest good nightly build before the buildbot broke.
