### ISSUE TITLE
No artwork anywhere

### ISSUE THREAD

**Issue by DJDale** [SchizoDuckie/DuckieTV#831]
I am using the Chrome extension version of DuckieTV (browser action mode)
Stable version 1.1.3
Running Windows 7 Ultimate 64bit with all the latest Windows updates

I just found out about this extension yesterday and added it to my Chrome. Well, ever since I set it up and added my TV shows I get NO ARTWORK anywhere. It all just looks generic. I really hope there is a fix for this otherwise I think I can live without the DuckieTV extension. Any help would be greatly appreciated.
![myscreen](https://cloud.githubusercontent.com/assets/25324163/22250450/86a9aa62-e20c-11e6-97b2-1ab50139b32f.jpg)

**Comment by garfield69** [comment]
The Image service provider that DuckieTV 1.1.3 is using discontinued their service. (see  https://apiblog.trakt.tv/trakt-api-images-56b43c356427 for details).     
DuckieTV 1.1.4 when it is released will source images from another provider.     
However Schizoduckie (the author) is in the middle or reworking the package distribution system and I don't have an ETA for you yet.     
At this stage you have several options:     

* wait for DuckieTV 1.1.4 to be released, OR     
* try a canary release of the development DuckieTV (called a Nightly). The latest good Nightly is  https://github.com/DuckieTV/Nightlies/releases/tag/nightly-01122017 and a guide for installing a Nightly can be found here https://github.com/SchizoDuckie/DuckieTV/wiki/How-to-Install-a-Development-version-of-the-DuckieTV-Chrome-Browser-Extension

**Comment by DJDale** [comment]
Thank you garfield69. That took care of the issue. The instructions were clear and concise. Now maybe I can play a bit with it and see what it's all about. Cheers !!!

**Comment by rmvz3** [comment]
Hi. I've just updated to 1.1.4 and the images are still missing. I'm the only one with this issue?

**Comment by garfield69** [comment]
Probably.    
Try going to the DuckeiTV *Settings, Backup* panel, scrolling down to the *Refresh all Series* section and clicking on the *Refresh all Series Now* button.     
Then wait for all the activity to finish, which could take some time depending on how many series you have.     
If you are still not seeing images that you expect, provide a screenshot so we can compare.
Let us know how you go.

**Comment by rmvz3** [comment]
Wow! Easy. This is embarrassing ^_^U

Thank you very much for your help.

**Comment by garfield69** [comment]
glad it worked for you.
