### ISSUE TITLE
Transmission connection not stable

### ISSUE THREAD

**Issue by SchizoDuckie** [SchizoDuckie/DuckieTV#832]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
New tab

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmdd)**
Nightly today

**What is your Operating System (Windows, Mac, Linux, Android)**
Ubuntu

**Describe the problem you are having and steps to reproduce if available**
I have noticed a couple of times now that the connection to Transmission doen't seem stable. E.g. torrents don't display any progress while downloading has already progressed much further.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

![image](https://cloud.githubusercontent.com/assets/111710/22404016/8ab36066-e627-11e6-97c2-3b5f8e04dc36.png)

I did spot an 'ERR_INTERNET_DISCONNECTED'  in the response, maybe this is somehow releated. The problem is most likely session token that needs to be refreshed.

**Comment by garfield69** [comment]
Yeah, this is part of the token expiry/refresh that transmission does.     
From the [transmission rpc-spec](https://trac.transmissionbt.com/browser/trunk/extras/rpc-spec.txt):     
```2.3.1.  CSRF Protection
58	   Most Transmission RPC servers require a X-Transmission-Session-Id
59	   header to be sent with requests, to prevent CSRF attacks.
60	
61	   When your request has the wrong id -- such as when you send your first
62	   request, or when the server expires the CSRF token -- the
63	   Transmission RPC server will return an HTTP 409 error with the
64	   right X-Transmission-Session-Id in its own headers.
65	
66	   So, the correct way to handle a 409 response is to update your
67	   X-Transmission-Session-Id and to resend the previous request.
```

So we already handle a 409 as shown in the following transmission.js torrentclient code snippet:    
```javascript
            rpc: function(method, params, options) {
                var self = this,
                    request = {
                        'method': method
                    },
                    headers = {
                        'X-Transmission-Session-Id': self.sessionID
                    };

                for (var i in params) {
                    request[i] = params[i];
                }

                if (this.config.use_auth) {
                    headers.Authorization = [this.config.username, this.config.password];
                }
                return $http.post(this.getUrl('rpc'), request, {
                    headers: headers
                }).then(function(response) {
                    return response.data;
                }, function(e, f) {
                    self.sessionID = e.headers('X-Transmission-Session-Id');
                    if (e.status === 409) {
                        return self.rpc(method, request, options);
                    }
                });
            },
```

I'm not sure that there is anything more we can do, other than somehow suppressing the errors from showing in the log...     
@SchizoDuckie I don't know how prevent a 409 from showing in the log... would  a try-catch do the trick or is there some other method?

**Comment by garfield69** [comment]
Thinking about this some more, it's clear that we already handle the 409, and retry the rpc request after we have loaded the new session id we received from the x-transmission-session-id header from the error response.    

the real culprit is the **err_internet_disconnected**, which is occurring on your ubuntu platform. This is an error that we are not trapping, because it is unexpected. Hence we return *undefined* and the getTorrents process falls over, causing the display progress failure you reported.     

I don't get these err_internet_disconnected failures when testing transmission on my win7 sandbox, even when I see the 409 messages posted regularly.    

So I don't think this is a DuckieTV issue. I suggest that the problem may be some sort of configuration problem with either ubuntu http, or ubuntu transmission? Some sort of timing/response/error-limit-per-millisecond setting that can be tweaked?

**Comment by garfield69** [comment]
Additionally it would be useful if you turned on the console timestamps so you could see just how closely (or not) the disconnected errors are to the 409s.     
Could the connection problem that DuckieTV is reporting, be a result of some kind of resourcing issue... such as wifi (or ethernet / broadband) overload, or high cpu or i/o, such that transmission or DuckieTV are not able to process the http traffic between themselves... just throwing ideas into the wind ;-)

**Comment by SchizoDuckie** [comment]
I will try some trickery with this. Probably we just have to listen for the browser internet connected / disconnected events, and re-init the torrent client when that happens.

**Comment by SchizoDuckie** [comment]
I haven't really observed this behavior anymore. closing this issue.
