### ISSUE TITLE
standalone Nightly: systray dead after an app.reload (nwjs 0.20+)

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#836]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmdd)**
GitHub Desktop cloned DuckieTV source with nwjs 0.20.1

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 7

**Describe the problem you are having and steps to reproduce if available**
There has been a change with nwjs 0.20 with what happens with the systray (and possibly with eventListeners) after a window.location.reload().    
After a reload, the systray menu still appears after a right-click, but  selecting on any of the menu items **does not** result in any action. There has been some kind of internal disconnect.     
We previously had a problem with multiple systrays being created on linux and mac, necessitating a fix for https://github.com/SchizoDuckie/DuckieTV/issues/569, so its possible this is now causing problems.
Will have to do some research and testing :-(

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by SchizoDuckie** [comment]
Just built a fresh 0.20.1 setup for this, window.location.reload() now works as expected.
