### ISSUE TITLE
Can't revisit the same calendar episode details without first clicking on another.

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#838]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
latest GitHub Desktop source
**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmdd)**
1.1.4
**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 7
**Describe the problem you are having and steps to reproduce if available**
Prior to the latest changes to the navigation system, if you clicked on a calendar episode to view the details side panel, then did any activity which closed that panel (view about, ADstatus, Torrents, etc), you could click on that same calendar episode and open the details side panel again.
Now, that does not work. The only way to view the details panel a second time is to first select any other episode on the calendar to view.

**Attach any DuckieTV statistics or Developer Console logs if available**
n/a

**Comment by SchizoDuckie** [comment]
Ah, nice find

This must have something to do with the sticky. I believe we can safely remove them again from the serie / episode nav

**Comment by SchizoDuckie** [comment]
Other than that, what do you think of the navigation changes?

**Comment by garfield69** [comment]
>Other than that, what do you think of the navigation changes?     

Great improvement. It's a keeper :+1:
