### ISSUE TITLE
[Feature Request] MyAnimeList account syncing

### ISSUE THREAD

**Issue by vavavr00m** [SchizoDuckie/DuckieTV#841]
What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))
...Chrome Extension Browser Action

What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmdd)
...Nightly v3017.2.14.11

What is your Operating System (Windows, Mac, Linux, Android)
...Windows

Describe the problem you are having and steps to reproduce if available
...I regularly update MAL. Syncing with my MAL account would be nice so that I don't have to manually re-add all the Anime shows.

Attach any DuckieTV statistics or Developer Console logs if available
...N/A

**Comment by Js41637** [comment]
I doubt we will add this, I think it would require too much work for a feature that only a few people would use. Ultimately the decision remains with @SchizoDuckie
