### ISSUE TITLE
Duplicates after trakt update

### ISSUE THREAD

**Issue by SchizoDuckie** [SchizoDuckie/DuckieTV#843]
After my last patches on the deleteDuplicates for the calendar and removeDeleted somehow the trakt update puts duplicate rows on the calendar again.

Cant properly replicate it until there's an actual update from trakt apparently, looking for a replicateable test case.

**Comment by garfield69** [comment]
How about forcing a Trakt.tv update using this on the console:
```javascript
localStorage.setItem('trakttv.lastupdated', new Date('2017-02-10').getTime());
CRUD.executeQuery("update series set lastupdated = '2015-02-10'").then(function(result) { console.log(result); });
window.location.reload();
```

**Comment by garfield69** [comment]
related to the latest version of the calendar, hidden series are showing. what's going on?

**Comment by SchizoDuckie** [comment]
Idunno. But  I'm sick of it breaking. I'm preparing some tests to lock this
down.

Op 14 feb. 2017 8:39 p.m. schreef "garfield69" <notifications@github.com>:

**Comment by SchizoDuckie** [comment]
So, this isn't enough yet. 
After running your force example it looks like the update procedure empties out the CalendarEvents private variable `calendarEvents`.

I cannot yet explain why, or reproduce it with a test.

**Comment by SchizoDuckie** [comment]
For completeness: These are my tests

https://github.com/SchizoDuckie/DuckieTV/blob/angular/tests/CalendarEvents.test.js#L96

And this is the output on travis
https://travis-ci.org/SchizoDuckie/DuckieTV/jobs/202074337#L527

(You can run tests yourself by first doingan `npm install`, and run `nmp run test` for a one-time testsuite or `npm run test-watch` while developing tests to have them auto-refresh)

**Comment by Js41637** [comment]
It wouldn't have anything to do with one way bindings would it?

**Comment by SchizoDuckie** [comment]
hmmm.. It shouldn't, I think.
But it could. One way bindings are outside of the service scope and inside angular's view layer... Very hard to predict how that affects this

**Comment by Js41637** [comment]
Well I would imagine anything with a `::` would not be updated if it were removed from the data. I'm just speculating. I dont think the calendar events are one way data binded tho?

**Comment by SchizoDuckie** [comment]
Correct. the calendar events are an indexed array that's monitored from the CalendarEvents service (if that would have one way binding, none of the calendar functionality would work like progress bars, mark watched, etc)

**Comment by SchizoDuckie** [comment]
My next test target for tomorrow will be the filtering and sorting functions

**Comment by garfield69** [comment]
Perhaps the place to focus on is the following code in js/services/CalendarEvents.js Line17
```javascript
        $rootScope.$on("storage:update", function() {
            console.log("Calendar detected that storage was updated removing deleted.");
            removeDeleted();
        }.bind(this))
```
With this code in place, the monthly calendar presents duplicate events after a Trakt.tv update, and the weekly calendar presents no events at all.
Without this code, both calendars display correctly.

**Comment by Js41637** [comment]
Partially off topic but, quick test showed whenever the calendar data updates it seems to stuff up the todo view, all events disappear, you need to reset the calendar or reload to get them back.

**Comment by garfield69** [comment]
> whenever the calendar data updates it seems to stuff up the todo view, all events disappear, you need to reset the calendar or reload to get them back.       

removing js/services/CalendarEvents.js Line17
```javascript
        $rootScope.$on("storage:update", function() {
            console.log("Calendar detected that storage was updated removing deleted.");
            removeDeleted();
        }.bind(this))
}
```
fixes the todo view as well.

**Comment by SchizoDuckie** [comment]
Whoah that makes no sense to me at all. Thanks for the investigative work


Op 16 feb. 2017 7:15 a.m. schreef "garfield69" <notifications@github.com>:
