### ISSUE TITLE
Backupservice pops up after database wipe and first reload

### ISSUE THREAD

**Issue by SchizoDuckie** [SchizoDuckie/DuckieTV#847]
Kind of annoying in this workflow:

- wipe database
- add a couple of shows
- select a torrent client
- page reloads
- backupservice pops up.

Should we introduce a new minimum time elapsed before popping this up?

**Comment by garfield69** [comment]
Yes, good idea.     
The auto-backup should wait at least a few minutes before launching _any_ backup, to give time for all the startup activity to be completed.    
This includes First time installation migration and series refresh, (including fanart link updates) which can take at least a couple minutes.    
As well as the regular startup, where the trakt.tv update and trending cycles kick off.

**Comment by garfield69** [comment]
I propose the following:
- For first time DuckieTV installs (or as a result of a wipe), delay the first auto-backup run by a day. We don't need to do a backup as soon as DuckieTV has been installed, and it gives the user a chance to build their favourites.    
- When DuckieTV is started, if an auto-backup is scheduled to run, delay the launching for a minute. This allows for the regular startup processes to complete, such as the trakt.tv and fanart daily updates.   It should allow for things to settle down before doing a backup, and ensures the backup has the latest DB to work with.

**Comment by SchizoDuckie** [comment]
Sounds solid. We may also need to take importing backups into account

Op 20 feb. 2017 6:40 p.m. schreef "garfield69" <notifications@github.com>:
