### ISSUE TITLE
None of my shows appear in the calender

### ISSUE THREAD

**Issue by Maxenboy** [SchizoDuckie/DuckieTV#849]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...Chrome Extension (New Tab)

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...1.1.4

**What is your Operating System (Windows, Mac, Linux, Android)**
...Mac OSX Yosemite 10.10.5

**Describe the problem you are having and steps to reproduce if available**
...None of my saved/favorite shows are loaded in the calander. The extension upgraded of itself and deleted all my history and shows, unfortunately I was stupid enough to not have a backup.
Added all my favorite shows and nothing happens, when browsing series and clicking for info it only says `Loading`, it's been like this for 2 full days now.

**Attach any DuckieTV statistics or Developer Console logs if available**
...
Tracking-ID: fbb148bd-8e29-d5ca-b179-b6da1fcefa7a
User preferences on Local Storage:
 ```{
  "topSites.enabled": false,
  "torrenting.enabled": true,
  "thepiratebay.mirror": "http://pirateshit.com/",
  "series.displaymode": "poster",
  "torrenting.searchprovider": "RarBG",
  "calendar.large": true,
  "client.determinedlocale": "en_us",
  "application.language": "sv_se",
  "application.locale": "sv_se",
  "sync.progress": null,
  "lastSync": 1414443408864,
  "torrenting.autodownload": true,
  "torrenting.searchquality": "720p",
  "kickasstorrents.mirror": "https://kickass.to",
  "torrenting.genericClients": {
    "KickAssTorrents": {
      "mirror": "https://kickass.so",
      "mirrorResolver": null,
      "endpoints": {
        "search": "/usearch/%s/?field=seeders&sorder=desc",
        "details": "/torrent/%s"
      },
      "selectors": {
        "resultContainer": "table.data tr[id^=torrent]",
        "releasename": [
          "div.torrentname a.cellMainLink",
          "innerText"
        ],
        "magneturl": [
          "a[title=\"Torrent magnet link\"]",
          "href"
        ],
        "size": [
          "td:nth-child(2)",
          "innerText"
        ],
        "seeders": [
          "td:nth-child(5)",
          "innerHTML"
        ],
        "leechers": [
          "td:nth-child(6)",
          "innerHTML"
        ],
        "detailUrl": [
          "div.torrentname a.cellMainLink",
          "href"
        ]
      }
    },
    "Torrentz.eu": {
      "mirror": "https://torrentz.eu",
      "mirrorResolver": null,
      "endpoints": {
        "search": "/search?f=%s",
        "details": "/%s"
      },
      "selectors": {
        "resultContainer": "div.results dl",
        "releasename": [
          "dt a",
          "innerText"
        ],
        "magneturl": [
          "dt a",
          "href",
          null
        ],
        "size": [
          "dd span.s",
          "innerText"
        ],
        "seeders": [
          "dd span.u",
          "innerText"
        ],
        "leechers": [
          "dd span.d",
          "innerText"
        ],
        "detailUrl": [
          "dt a",
          "href"
        ]
      }
    },
    "OldPirateBay": {
      "mirror": "https://oldpiratebay.org",
      "mirrorResolver": null,
      "endpoints": {
        "search": "/search.php?q=%s&Torrent_sort=seeders.desc",
        "details": "/%s"
      },
      "selectors": {
        "resultContainer": "table.table-torrents tbody tr",
        "releasename": [
          "td.title-row a span",
          "innerText"
        ],
        "magneturl": [
          "td.title-row a[title=\"MAGNET LINK\"]",
          "href"
        ],
        "size": [
          "td.size-row",
          "innerText"
        ],
        "seeders": [
          "td.seeders-row",
          "innerText"
        ],
        "leechers": [
          "td.leechers-row",
          "innerText"
        ],
        "detailUrl": [
          "td.title-row > a",
          "href"
        ]
      }
    }
  },
  "Chrome.Sync": true,
  "calendar.startSunday": true,
  "autodownload.lastrun": 1487614562734,
  "torrenting.client": "uTorrent Web UI",
  "utorrentwebui.server": "http://localhost",
  "utorrentwebui.port": 8080,
  "utorrentwebui.username": "admin",
  "utorrentwebui.password": "*****",
  "utorrentwebui.use_auth": true,
  "library.smallposters": true,
  "ThePirateBay.mirror": "https://thepirateproxybay.xyz/",
  "deluge.use_auth": true,
  "transmission.path": "/transmission/rpc",
  "vuze.path": "/transmission/rpc",
  "autodownload.multiSE": {
    "ThePirateBay": true,
    "1337x": true,
    "IsoHunt": true,
    "KATcr": true,
    "Nyaa": true,
    "RarBG": true,
    "ShowRSS": true,
    "TorrentDownloads": true,
    "TorrentZ2": true,
    "Zooqle": true,
    "EzTV.ag": true,
    "Idope": true,
    "LimeTorrents": true,
    "SkyTorrents": true,
    "KickAss": true
  },
  "main.viewmode": "calendar",
  "calendar.show-episode-numbers": true
}
```
Other significant Local Storage keys: 
```{
  "0.42.orphancheck": "done",
  "0.4migration": "done",
  "0.5.firetimers": "done",
  "0.53.createtimers": "true",
  "0.54.createtimers": "done",
  "0.91fixoldpiratebay": "true",
  "0.91migration": "Thu Jan 29 2015 10:46:37 GMT+0100 (W. Europe Standard Time)",
  "0.9migration": "Mon Jan 26 2015 11:04:19 GMT+0100 (W. Europe Standard Time)",
  "0.9updateallshows": "true",
  "1.0migration": "Thu May 14 2015 21:15:48 GMT+0200 (W. Europe Daylight Time)",
  "1.1.4TorrentHashListCleanup": "Sun Feb 19 2017 12:05:12 GMT+0100 (CET)",
  "1.1.4cleanupOrphanedEpisodes": "Sun Feb 19 2017 12:05:10 GMT+0100 (CET)",
  "1.1.4cleanupOrphanedSeasons": "Sun Feb 19 2017 12:05:11 GMT+0100 (CET)",
  "1.1.4qBittorrentPre32": "Sun Feb 19 2017 12:05:02 GMT+0100 (CET)",
  "1.1.4refresh": "Sun Feb 19 2017 12:05:17 GMT+0100 (CET)",
  "1.1.4refreshTrendingCache": "Sun Feb 19 2017 12:05:02 GMT+0100 (CET)",
  "1.1.4updateDelugeAuth": "Sun Feb 19 2017 12:05:02 GMT+0100 (CET)",
  "1.1.4updateTransmissionPath": "Sun Feb 19 2017 12:05:02 GMT+0100 (CET)",
  "1.1migration": "Thu Jul 09 2015 09:06:12 GMT+0200 (W. Europe Daylight Time)",
  "autobackup.lastrun": "1487502848754",
  "database.version.Episodes": "13",
  "database.version.Fanart": "1",
  "database.version.SearchEngines": "2",
  "database.version.Seasons": "6",
  "database.version.Series": "15",
  "database.version.WatchList": "1",
  "database.version.WatchListObject": "1",
  "fanart.bootstrapped": "1",
  "install.notify": "1.1.4",
  "optin_error_reporting": "true",
  "optin_error_reporting.start_time": "1487504605274",
  "runtime.event": "{\"previousVersion\":\"1.1.3\",\"reason\":\"update\"}",
  "snr.lastFetched": "1487494398573",
  "torrenting.client": "uTorrent Web UI",
  "trakttv.lastupdated": "1487498354913",
  "trakttv.lastupdated.trending": "1487502852010",
  "uniqueId": "fbb148bd-8e29-d5ca-b179-b6da1fcefa7a",
  "upgrade.notify": "1.1.4",
  "utorrent.port": "10000",
  "xem.lastFetched": "1487494398579"
}
```

**Comment by SchizoDuckie** [comment]
:cry: sorry for that. Any chance you interrupted the upgrade procedure by forcefully closing the tab?

Could attach your  DuckieTV database file from ~/Library/Application Support/Google/Chrome/Default/databases/hkbamkappmgfjjahmnlngibomenmbbdf/ to this issue so we can investigate?

I will make sure that for the next release database migrations will happen only in the background so this is a problem that will be in the past forever

**Comment by SchizoDuckie** [comment]
According to the logs:

- All migrations have run
- Fanart was initialized

**Comment by Maxenboy** [comment]
There's no `Default` directory in my Chrome path so I either don't have the database or it's somewhere else @SchizoDuckie 
I don't think I interrupted the upgrade procedure

**Comment by SchizoDuckie** [comment]
I'll have a look on my osx vm. hold on.

**Comment by SchizoDuckie** [comment]
Sorry, took a little while to upgrade chrome on my osx vm.

The full path is `~/Library/Application Support/Google/Chrome/Default/databases/chrome-extension_hkbamkappmgfjjahmnlngibomenmbbdf_0/
There is a file without an extension in this folder. copy that to somewhere else and rename it maxenboy.sqlite, and we should be good to go.

**Comment by Maxenboy** [comment]
<img width="497" alt="screen shot 2017-02-20 at 20 48 01" src="https://cloud.githubusercontent.com/assets/1564080/23139679/ec138c0e-f7ad-11e6-867b-7ea91255b961.png">

Sorry no `Default` directory in Google directory

**Comment by Maxenboy** [comment]
Maybe that's the problem then

**Comment by SchizoDuckie** [comment]
please include the `~/` at the beginning of the command.
*edit*
hmm.. you're already there.

Can you list the directories in that folder for me? are you using a named user profile?

**Comment by Maxenboy** [comment]
<img width="563" alt="screen shot 2017-02-20 at 20 52 29" src="https://cloud.githubusercontent.com/assets/1564080/23139797/894a2442-f7ae-11e6-8533-6eb8e2231547.png">
No difference :(

**Comment by SchizoDuckie** [comment]
Is there a `Profile 1` directory there?

**Comment by Maxenboy** [comment]
Ok I've copied it, how can I send it to you?

**Comment by SchizoDuckie** [comment]
Can you attach it to this issue? (you may have to zip it first)

**Comment by Maxenboy** [comment]
[maxenboy.sqlite.zip](https://github.com/SchizoDuckie/DuckieTV/files/788412/maxenboy.sqlite.zip)

**Comment by SchizoDuckie** [comment]
Thank you. I will investigate and report a.s.a.p.

**Comment by Maxenboy** [comment]
Thank you, and thanks for the help ;)

**Comment by SchizoDuckie** [comment]
I see that the upgrade of the series table has not finished, and the episodes table is empty.

That's very odd.

I'll try to craft an update statement for you and will check further.

**Comment by SchizoDuckie** [comment]
In the meantime I'm also RDP'ing to my dad who also seems to have a similar issue. It looks like the Fanart Updater is making a mess of things by running immediately while other queries are still processing.

![image](https://cloud.githubusercontent.com/assets/111710/23140367/73f5b450-f7b1-11e6-8992-06c20fd484f4.png)

**Comment by Maxenboy** [comment]
<img width="1280" alt="screen shot 2017-02-20 at 21 16 51" src="https://cloud.githubusercontent.com/assets/1564080/23140443/ed31bbde-f7b1-11e6-9b60-d9e4a68e88df.png">

I don't get the SQL error mostly `Loggr is not defined` and `Uncaught Error: [$rootScope:inprog]`
And when I think of it I've never seen the loading bar appear with `Writing to db` since the upgrade

**Comment by SchizoDuckie** [comment]
After that, the migration cleanup comes in, which finds orphaned episodes...
In your case this must have gone wrong, explaining why the episodes table is empty.

![image](https://cloud.githubusercontent.com/assets/111710/23140403/af49d770-f7b1-11e6-8fea-689a3a20913b.png)

The SQL errors make it sothat to db dialog does not hide.
![image](https://cloud.githubusercontent.com/assets/111710/23140462/1133630c-f7b2-11e6-84ba-040e8837261b.png)

**Comment by Maxenboy** [comment]
<img width="630" alt="screen shot 2017-02-20 at 21 22 35" src="https://cloud.githubusercontent.com/assets/1564080/23140582/be0e998e-f7b2-11e6-95a8-8ccdb20bf43f.png">

Nothing happens after this :( Can I enforce the migration cleanup somehow?

**Comment by SchizoDuckie** [comment]
That must have happened unbeknownst to you, I will try to check if I can
resume the upgrade manually or if it fails. I'll also look into the loggr
thingie. We'll have you up and running again tonight!

Op 20 feb. 2017 9:19 p.m. schreef "Max Åberg" <notifications@github.com>:

**Comment by Maxenboy** [comment]
Awesome
Dank je wel

**Comment by SchizoDuckie** [comment]
Please execute the following statements: (Just copy/paste the whole thing into the input field at the bottom of the screen in the 'console' tab of the devtools.


```
window.location.hash = "#/settings/backup";
CRUD.executeQuery('ALTER TABLE Series RENAME TO Series_bak_2').then(function() {
	return CRUD.executeQuery('CREATE TABLE Series (ID_Serie INTEGER PRIMARY KEY NOT NULL, name VARCHAR(250) DEFAULT(NULL), banner VARCHAR(1024) DEFAULT(NULL), overview TEXT DEFAULT(NULL), TVDB_ID INTEGER DEFAULT(NULL), IMDB_ID VARCHAR(20) DEFAULT(NULL), TVRage_ID INTEGER DEFAULT(NULL), actors VARCHAR(1024) DEFAULT(NULL), airs_dayofweek VARCHAR(10) DEFAULT(NULL), airs_time VARCHAR(15) DEFAULT(NULL), timezone VARCHAR(30) DEFAULT(NULL), contentrating VARCHAR(20) DEFAULT(NULL), firstaired DATE DEFAULT(NULL), genre VARCHAR(50) DEFAULT(NULL), country VARCHAR(50) DEFAULT(NULL), language VARCHAR(50) DEFAULT(NULL), network VARCHAR(50) DEFAULT(NULL), rating INTEGER DEFAULT(NULL), ratingcount INTEGER DEFAULT(NULL), runtime INTEGER DEFAULT(NULL), status VARCHAR(50) DEFAULT(NULL), added DATE DEFAULT(NULL), addedby VARCHAR(50) DEFAULT(NULL), fanart VARCHAR(150) DEFAULT(NULL), poster VARCHAR(150) DEFAULT(NULL), lastupdated TIMESTAMP DEFAULT (NULL), lastfetched TIMESTAMP DEFAULT (NULL), nextupdate TIMESTAMP DEFAULT (NULL), displaycalendar TINYINT DEFAULT(1), autoDownload TINYINT DEFAULT(1), customSearchString VARCHAR(150) DEFAULT(NULL), watched TINYINT DEFAULT(0), notWatchedCount INTEGER DEFAULT(0), ignoreGlobalQuality TINYINT DEFAULT(0), ignoreGlobalIncludes TINYINT DEFAULT(0), ignoreGlobalExcludes TINYINT DEFAULT(0), searchProvider VARCHAR(20) DEFAULT(NULL), ignoreHideSpecials TINYINT DEFAULT(0), customSearchSizeMin INTEGER DEFAULT(NULL), customSearchSizeMax INTEGER DEFAULT(NULL), TRAKT_ID INTEGER DEFAULT(NULL), dlPath TEXT DEFAULT(NULL), customDelay INTEGER DEFAULT(NULL) )')
}).then(function() {
	return CRUD.executeQuery('INSERT OR IGNORE INTO Series (ID_Serie, name, banner, overview, TVDB_ID, IMDB_ID, TVRage_ID, actors, airs_dayofweek, airs_time, timezone, contentrating, firstaired, genre, country, language, network, rating, ratingcount, runtime, status, added, addedby, fanart, poster, lastupdated, lastfetched, nextupdate, displaycalendar, autoDownload, customSearchString, watched, notWatchedCount, ignoreGlobalQuality, ignoreGlobalIncludes, ignoreGlobalExcludes, searchProvider, ignoreHideSpecials, customSearchSizeMin, customSearchSizeMax, TRAKT_ID, dlPath) select ID_Serie, name, banner, overview, TVDB_ID, IMDB_ID, TVRage_ID, actors, airs_dayofweek, airs_time, timezone, contentrating, firstaired, genre, country, language, network, rating, ratingcount, runtime, status, added, addedby, fanart, poster, lastupdated, lastfetched, nextupdate, displaycalendar, autoDownload, customSearchString, watched, notWatchedCount, ignoreGlobalQuality, ignoreGlobalIncludes, ignoreGlobalExcludes, searchProvider, ignoreHideSpecials, customSearchSizeMin, customSearchSizeMax, TRAKT_ID, dlPath from Series_bak_2')	
}).then(function() {
	document.querySelectorAll(".rightpanel.settings .btn.btn-danger")[1].click();
        console.log("Updating your episodes, please wait");
});

```

**Comment by Maxenboy** [comment]
<img width="1276" alt="screen shot 2017-02-20 at 21 55 39" src="https://cloud.githubusercontent.com/assets/1564080/23141496/63c248d6-f7b7-11e6-8b2d-de69bc1bda4b.png">

**Comment by SchizoDuckie** [comment]
You just executed it twice.

**Comment by SchizoDuckie** [comment]
There is no other reason that a Series_bak_2 table can exist. No worries, it should be updating now.

**Comment by Maxenboy** [comment]
Yea sorry, I got a rejection in the promise so I wanted to double check that the same error happened again, my bad

**Comment by SchizoDuckie** [comment]
Can you  screenshot me the other rejection just to be sure?

**Comment by Maxenboy** [comment]
I don't have it :( I accidentally refreshed the tab since that. My bad

**Comment by SchizoDuckie** [comment]
Okay, you may want to go into the settings/backup screen again, and click the bottom 'refresh all series now' button.

Then, please, wait until it's done and you should be all good!

**Comment by Maxenboy** [comment]
<img width="1280" alt="screen shot 2017-02-20 at 22 05 24" src="https://cloud.githubusercontent.com/assets/1564080/23141771/b6bc4216-f7b8-11e6-9e1f-c63a50b583e4.png">
Something seems off

**Comment by SchizoDuckie** [comment]
Uhh whot the hell.

What does a full page refresh do now? Can you show me the console?

**Comment by Maxenboy** [comment]
Should I refresh first or give you the console output before refreshing

**Comment by SchizoDuckie** [comment]
Please refresh first. (better yet, close the tab and open a new one)

**Comment by Maxenboy** [comment]
<img width="626" alt="screen shot 2017-02-20 at 22 11 08" src="https://cloud.githubusercontent.com/assets/1564080/23141937/843e879e-f7b9-11e6-9897-131c207e385f.png">

**Comment by Maxenboy** [comment]
<img width="1280" alt="screen shot 2017-02-20 at 22 11 39" src="https://cloud.githubusercontent.com/assets/1564080/23141948/941b5f5c-f7b9-11e6-81f6-be7c4bc4cad1.png">
When clicking on settings in left column
It just stays like that

**Comment by SchizoDuckie** [comment]
I cannot explain this. If you click around in other screens, does anything happen?

Would you be willing to setup a teamviewer instance with me so I can look at what's happening?

**Comment by Maxenboy** [comment]
Nothing happens at the moment, I would love to but need to get some rest right now. Early day tomorrow. Can we resume this tomorrow evening? is that OK?

**Comment by SchizoDuckie** [comment]
sure, no problem. Thank you for your patience!

**Comment by Maxenboy** [comment]
Thank you! I'll ping you in here tomorrow evening then

**Comment by SchizoDuckie** [comment]
If you're up for it, you could still :

- close your browser completely
- replace the database in the chrome databases directory  with the backup file maxenboy.sqlite you made for me (overwrite it)
- re-execute the code I pasted above
- sit back and don't touch :laughing:

**Comment by Maxenboy** [comment]
<img width="635" alt="screen shot 2017-02-20 at 22 30 13" src="https://cloud.githubusercontent.com/assets/1564080/23142435/34200762-f7bc-11e6-9627-8163f8497e41.png">

**Comment by Maxenboy** [comment]
Seems to me that the button for refreshing is not available

**Comment by Maxenboy** [comment]
so the promise rejects

**Comment by SchizoDuckie** [comment]
okay well, that just leaves the 'auto refresh'  part of the script not working (Could be a simple timing issue)

Your backup panel in settings should now be open. Does it break again if you click that?

**Comment by Maxenboy** [comment]
Yea it's the same, it's just loading

**Comment by SchizoDuckie** [comment]
Strange. We'll look into it further tomorrow. Good night for now!

**Comment by Maxenboy** [comment]
Sure, good night!

**Comment by Emil-G** [comment]
Same setup, same issue. Got tired of it not working, exported a backup. Downloaded the nightly build instead (imported seemingly broken backup from stable release export into nightly). And it worked fine, some settings (hidden shows where gone), but synced all watched episodes from Trakt.tv and was good. 

Cheers,
Emil

**Comment by Maxenboy** [comment]
Sorry for the AFK, have been abroad. I reinstalled the extension and used the backup, lost all my seen/download data but manually fixed it and now it works like a charm. You can close this issue :)

**Comment by SchizoDuckie** [comment]
No problem, thanks for the update
