### ISSUE TITLE
Search results returns empty for PiratesBay

### ISSUE THREAD

**Issue by sajan45** [SchizoDuckie/DuckieTV#850]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Chrome Extension New Tab

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Stable 1.1.4

**What is your Operating System (Windows, Mac, Linux, Android)**
Linux (Ubuntu 16.04)

**Describe the problem you are having and steps to reproduce if available**
Torrent search by clicking on 'Find a torrent' in Episode side panel, returns no result.
Please note that, this happens when using ThePirateBay as torrent provider. I tried some other like 1337x, IsoHunt, Idope etc but not all. In this case, it was returning some results but not empty at least. And I tried with only episode of 2 tv shows which broadcast on Monday

**Attach any DuckieTV statistics or Developer Console logs if available**
Console has no error but only this _Xem does not have series SHOW_NAME (an_id), using default format._ .
But I checked network tab of developer panel. It successfully sent a request to **https://thepiratebay.cr/search/[SHOW_NAME]%20S02E13%20/0/7/0** and get a 200 response, and also it gets the whole PiratesBay Page with show search results in response. So I guess, it fails to parse the html contents. I don't know if PiratesBay changed something thats why scraping fails or anything else.

Please let me know, if any other info needed.

**Comment by SchizoDuckie** [comment]
Thanks. I had noticed this too and traced it to the way thepiratebay handles their file size, which is passed on to the filesize filter function. Should be sorted in the nightlies.

**Comment by sajan45** [comment]
Well then, feel free to close this when fix is released. On a side note, many many Thanks to you guys for making this. This makes my life a lot easier, since I watch 8-9 seasons every week. This is my favourite piece of software because of how much time and hassles it saves for me. I am a PHP and Ruby developer, started with AngularJS 3 months back. I will look for opportunities to contribute to DuckieTV. Thanks Again.
