### ISSUE TITLE
Improper Series names

### ISSUE THREAD

**Issue by christrigg24** [SchizoDuckie/DuckieTV#852]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Nightly 201702210010

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 7 x64

**Describe the problem you are having and steps to reproduce if available**
The following problems happening when trying to find torrents:
Tyler Perry's The Haves and the Have Nots should be The Haves and have nots
The Real World Road Rules Challenge should be "The Challenge"
Dr. Phil search by should be YYYY.MM.D
General Hospital should be searched by Season "space" Episode

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
Done.     
Your DuckieTV will fetch the latest scene exception tables within the next 24 hours, after which it will begin using them for torrent searches.

**Comment by christrigg24** [comment]
-I know Duckie will auto update eventually, is there any way to update manually?

**Comment by christrigg24** [comment]
Thanks for your rapid response!!
