### ISSUE TITLE
[Feature Request] Specify download location

### ISSUE THREAD

**Issue by bassterror** [SchizoDuckie/DuckieTV#854]
Hey guys,

it would be great if we are able to specify the download directory in case we don't want to put all of the DuckieTV downloads in the same default download directory of our torrent client.

- maybe put a label "duckie" or whatever to the torrent and then the torrent client can map directories depending on this label (uTorrent feature. I'm not sure how it is with other clients)

- maybe "push" a directory path (specified somewhere in the Duckie settings) to the torrent client

I'm sorry if my English is not too good. I hope you understand the request.
Cheers! Keep up the great work!

**Comment by garfield69** [comment]
>it would be great if we are able to specify the download directory     

DuckieTV 1.1.4 already has this feature :-)    
The torrent clients that support Download Paths during torrent submissions currently are: Deluge, qBittorrent (3.3.1 and newer), rTorrent, Transmission, and Vuze.    
For those clients, when you go to the series details panel, and click on that series *settings* button, you get the option to specify the full download path to use for all of that series downloads.      
https://github.com/SchizoDuckie/DuckieTV/wiki/FAQ#how-do-i-set-the-download-path-for-a-series
