### ISSUE TITLE
Mac client minimizes to menu bar AND dock

### ISSUE THREAD

**Issue by rmvz3** [SchizoDuckie/DuckieTV#856]
Using Mac client 1.1.4 with Sierra. DuckieTV is still unable to minimize to status menu bar properly. I mean, it appears in the menu bar as expected but it keeps in the dock too!, so… what's the point?

This has been around since I started to use this wonderful app months ago. It doesn't really matters but it drives me crazy. I have to close and reopen the app every time I open the window to avoid having duplicate "minimized" instances. Is there anything I can do to avoid this behavior?

**Comment by garfield69** [comment]
>I mean, it appears in the menu bar as expected but it keeps in the dock too!     

Isn't this the way a Mac Dock is supposed to work?     
from https://support.apple.com/en-us/HT201730     
>Minimizing Windows
>If you minimize a window[...] the window is pulled down into the Dock. It's held there until you click its icon to bring up the window again.

**Comment by rmvz3** [comment]
Well, that's strictly right but I believe every Mac user expects that any app that appears in the menu bar to disappear from the dock. Maybe this should be a feature request for "Closing window sends to menu bar" or so then. :)

**Comment by garfield69** [comment]
Hmm.     
As you may know, DuckieTV uses [NWJS](https://nwjs.io) to provide the standalone run time environment, and it is NWJS that does the actual menu bar interfacting with the OS.      
I'll take a look at the NWJS documentation for Mac and see if there is anything extra we can add to the minimize to menubar that allows for the icon to vanish from the Dock.

**Comment by rmvz3** [comment]
That would be awesome. Thank you very much.

**Comment by garfield69** [comment]
There does not appear to be any Mac options in the NWJS documentation that controls this. Sorry.     
But before I go, can you take a look at your DuckieTV *Settings,Windows* panel, and check what options you have enabled?      
![image](https://cloud.githubusercontent.com/assets/6933240/23390482/37ccd8aa-fdd3-11e6-9a6f-66c3ffba9f66.png)
Are you settings the same as mine?

**Comment by rmvz3** [comment]
I have the "Minimize button minimizes DuckieTV to tray" enabled (and this is achieved correctly). I'd like to have the "Close button minimizes DuckieTV to try" available too because that's exactly what I want but there's only the former in windows settings.

**Comment by garfield69** [comment]
@lonelyfairie :   
What is the normal behaviour on your mac osx regarding minimized windows and Menubar?     
When you minimize an app, the minimized-window shows up on the Dock, yes?    
And apps that are minimized to the Menubar do not show a mininmised window on the Dock, yes?
Does DuckieTV behave the same way as the other apps for you?

**Comment by garfield69** [comment]
@rmvz3 
>I'd like to have the "Close button minimizes DuckieTV to try" available too because that's exactly what I want but there's only the former in windows settings.     

Sorry, the *close to tray* does not work on mac, it's only available on windows and linux platforms.

**Comment by rmvz3** [comment]
Well. The behavior is in fact same as Windows. If you minimizes an app, it will go to the dock. The 'close to tray' option is not really part of the S.O. but many apps offers the option to close the app window and keep the app running showing an icon in the tray (again, just like Windows).
There's a kind of Mac applications that are intended to live in the tray and doesn't show any icon on dock. They are mainly apps that are working continuously which I think will suit very well to DuckieTV.

Another option, would be just behave like most native apps and DON'T close the app when closes the window. So you will close the window and the app will keep working normally (with its icon in the Dock as everyone else). That would be nice too and probably is just a property away (in mac native developing you just need to return true or false to app delegate's applicationShouldTerminateAfterLastWindowClosed method).

**Comment by garfield69** [comment]
OK. I've looked back through DuckieTV's changelog, and see that the *closeToTray* and *AlwaysShowTray* options were disabled on Mac back when we were using NWJS 0.12.3     
There has been a lot of changes to NWJS since then, and we are currently using NWJS 0.20.3     
So I have enabled these options again on Mac with https://github.com/SchizoDuckie/DuckieTV/commit/fa615e9886ed14166b6f81ca8bbfec4a1903c0de so that Mac users of the Nightly Canary can test if these options are still broken or are now working on their platforms.      
@rmvz3  When the next Mac Nightly gets build in about 19 hours or so, download the latest 20170301 release on https://github.com/DuckieTV/Nightlies/releases and test the options as thoroughly as you can.    
If you report all is well, we will include the change in the next Stable release, but if you find any problems, I'll revert the change back out.     
@lonelyfairie Always value your Mac input (Yours is not Sierra correct?) if you have the time to test these options, many thanks.
[Edit] correct release version as 1st of March, not 29th of February Duh!

**Comment by rmvz3** [comment]
Awesome. I'll give it a try and I'll report about it. Thank you.

**Comment by rmvz3** [comment]
Oh, man. It works like a charm now! Thank you very much.   \\(^_^)/

**Comment by lonelyfairie** [comment]
@garfield69  sorry didn't see this earlier, but yes I am using Sierra on my mac as well. I am not seeing the option to not minimize to the dock in the nightly release I have installed, it is the March 6th release I believe.
