### ISSUE TITLE
enhancements to the add-a-show panel: add-button on details panel; + button on trending posters

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#861]
As raised in this Reddit post:
gh-its: https://www.reddit.com/r/duckietv/comments/5uuzmy/duckietv_v114_garfields_glory_is_here/de3xmj5/
>Keep Up the great work guys!
>Only one thing: In the "add a show" display, please disable the automatic add to favorites when a show clicked. It is a bit annoying.

schizoduckie: https://www.reddit.com/r/duckietv/comments/5uuzmy/duckietv_v114_garfields_glory_is_here/de62wzs/
>Good idea. I'll work something out with an add button in the details panel.
>I do like being able to add something directly though, so we'll probably make a '+' button slide into the poster after a little delay for that one-click add

Todo:

- [x] patch trakt custom search templates
- [x] fix trakt custom search logic so things are clickable

**Comment by Js41637** [comment]
seems pretty stupid to me, it's called the "add a show" page for a reason

**Comment by SchizoDuckie** [comment]
Interaction wise you want to see some details about the show and I think it's a valid use case for somebody to click first to see details. (which also fixes the 'there is no such thing as hover on touch' issue, so you can't see show info before adding)

 I'll add an explicit + button on hover to the posters for clarity

**Comment by SchizoDuckie** [comment]
Todo:

- [ ] patch trakt custom search templates
- [ ] fix trakt custom search logic so things are clickable
