### ISSUE TITLE
Torrent Dialogue's quality buttons are not staying on the left below search box

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#862]
As raised in this Reddit https://www.reddit.com/r/duckietv/comments/5wuf3p/torrent_ui_modal_issues/    
call_da_ambalampss:     
>When I launch the modal window to find a torrent file for a tv show, there are two behaviors of the content quality buttons. When I have selected RARBG the quality buttons will appear below the search bar. But when I select EZTV.ag the quality buttons will move to the right of the search. Is there a way to make the quality buttons sticky? possibly leaving them to the right of the search bar?
>[RARBG](http://imgur.com/D7t0MCT)
>[EZTV.ag](http://imgur.com/in5PnuV)
>i am running DuckieTV 1.14 (Browser Action mode) on Chrome Version 56.0.2924.87 (64-bit) on OSX 10.11.13

**Comment by SchizoDuckie** [comment]
For me the whole sort dropdown can go. It's only use is to also introduce sorting by torrent age, which I think is irrelevant. Then the sorting moves back to the table headers, the logical place.

**Comment by SchizoDuckie** [comment]
There is also another bug possibly related to the general sorting patches:

- sorting by size here, the other indicator doesn't hide
- using some string sort instead of numeric sort on the client side?
![image](https://cloud.githubusercontent.com/assets/111710/23479339/6db88878-fec4-11e6-8b74-a7934b9c6432.png)

**Comment by garfield69** [comment]
>For me the whole sort dropdown can go. It's only use is to also introduce sorting by torrent age, which I think is irrelevant. Then the sorting moves back to the table headers, the logical place.     

OK, I'll remove the sort menu option.

>using some string sort instead of numeric sort on the client side?     

That is limetorrents fault. We just provide the url extension for which ever sort the search host provides, and we display what ever the host sort returns, and apply our filters over the results.

>sorting by size here, the other indicator doesn't hide     

I'll look into that. Some hosts provide both asc and desc sorting, but limetorrents does not. I can amend the support code to handle that situation better.
[edit] corrections for markdown
