### ISSUE TITLE
UI being Tiny

### ISSUE THREAD

**Issue by gofirst2220** [SchizoDuckie/DuckieTV#865]
**What build of DuckieTV are you using (Standalone / Chrome Extension (New Tab / Browser Action))**
Android

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Nightly 201603040030

**What is your Operating System (Windows, Mac, Linux, Android)**
Android 7.0

**Describe the problem you are having and steps to reproduce if available**
UI is so tiny on my phone that it's almost unusable.

**Comment by SchizoDuckie** [comment]
Sorry, install DuckieTV on a TV or tablet.

It's not going to scale to phones unless someone sends a pull request.

**Comment by garfield69** [comment]
@SchizoDuckie  are we talking about adding a slider to settings, to replicate the ctrl 0, ctrl - and ctrl + zoom controls, or are we talking something more complicated like adjusting the resolution, like going from 800x600 to 1920x1080 ?

**Comment by SchizoDuckie** [comment]
Font zoom will not be enough. It needs a whole custom responsive style
sheet

Op 4 mrt. 2017 7:47 p.m. schreef "garfield69" <notifications@github.com>:
