### ISSUE TITLE
Not functional when re-open after loading backup

### ISSUE THREAD

**Issue by vamartid** [SchizoDuckie/DuckieTV#869]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standlone DuckieTV-1.1.4-windows-x64

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
DuckieTV-1.1.4-windows-x64 DuckieTV 1.1.4 - "Garfield's Glory"

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 10 x64 

**Describe the problem you are having and steps to reproduce if available**
I do load a backup file.
Load works fine and program is functional
but when I close the program and reopen it,
it is not functional anymore, clicking and pressing anything has no feedback from the program
only thing I can do is move the window of duckietv around(not even minimize).
I tryed terminate and reopen the program stucked again
I had to delete this folder C:\Users\...\AppData\Local\DuckieTV-Standalone\User Data
 and reopen. It became functional again. I loaded a more recent backup still the same.
I tryed uninstall completely and reinstall same thing after loading the backup
<img src="http://i.imgur.com/7jnx9KZ.jpg">
When I open it has that dialog on loading forever:
<img src="http://image.prntscr.com/image/5e45705bc2f149669cc209695758feed.png">
**Attach any DuckieTV statistics or Developer Console logs if available**
here is my backup file
[DuckieTV Mar 11, 2017.zip](https://github.com/SchizoDuckie/DuckieTV/files/836576/DuckieTV.Mar.11.2017.zip)

**Comment by SchizoDuckie** [comment]
Thanks for the full log. I was able to reproduce it.

The new nwjs adheres to the default DOM storage limits of ~2mb, which your backup exceeds.
Upon reloading it crashes with a QUOTA_EXCEEDED limit.

**Comment by SchizoDuckie** [comment]
You can fix this manually for your 1.1.4 release by finding the package.json file for the DuckieTV install and appending `,
    "dom_storage_quota": 50` to the line before the `}` at the end of the file.
Then restart, and you should be good to go. 

If you don't want to do that, i'd suggest waiting for the new nightly that'll be built tonight.
Thanks for reporting!
