### ISSUE TITLE
miss-matching posters for series just added to favourites.

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#871]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
 nightly v201703110130

**What is your Operating System (Windows, Mac, Linux, Android)**
windows x64

**Describe the problem you are having and steps to reproduce if available**
as raised in this reddit https://www.reddit.com/r/duckietv/comments/5z817m/another_artwork_question/
when the OP adds certain new series, the poster displayed in favourites does not seem to belong.  

**Attach any DuckieTV statistics or Developer Console logs if available**
 https://i.imgur.com/hAEUn5m.jpg

I've asked the OP to load his DuckieTV DB to the cloud so we can check if the issue is with the image links stored in the DB or if it is some other poster display issue.

**Comment by SchizoDuckie** [comment]
No need to refer to imgur in github. Just CTRL+V the screenshot here

![image](https://cloud.githubusercontent.com/assets/111710/23896816/fd894bd2-08aa-11e7-8df3-700516caca6d.png)

**Comment by Js41637** [comment]
Note you have to actually copy the image, right click > copy image

**Comment by Js41637** [comment]
or depending on your capture software which usually copies it to clipboard (before it uploads if you use sharex or puush)

**Comment by garfield69** [comment]
db directory and all subfolders/files etc: http://www.filedropper.com/databases

**Comment by garfield69** [comment]
*preliminary analysis of DB*     
The DB is complete, without errors, and every image link is either *NULL* or a valid fanart link.     
There are no old Trakt.tv link in the DB.     
All the *Dirk Gently* series images point to the correct tvdb id 312505 and are the latest images available.    
I've loaded the DB in my sandbox, and my DuckieTV win7 standalone v201703132338 displayed all the correct posters for all 135 series the user has in favourites.    

I think we can eliminate the DB from the list of causes.

**Comment by SchizoDuckie** [comment]
That is .. oddd..
Can we exclude borked browser cache from the list too? (I have not seen this happening myself)

**Comment by garfield69** [comment]
I have never come across this problem so far either.    

Yes, the Standalone data area (with all the temp files and local cache etc) is a good item to eliminate from the checklist.
I will get the user to make a current backup, then blow away the standalone data folder, and on start up do a import of the backup.    
See if that makes any difference.

**Comment by garfield69** [comment]
clearing the local data area did not resolve this users unique problem.    
currently he is seeing the *movie* logo *Happy Gilmor* instead of the poster for series *Dirk Gently Detective Agency*, and the *movie* logo *Men & Chicken* instead of the poster for series *Kevin Can Wait*. !?!     
I'll be interested to see if upgrading to the next nightly (with the fanart cleanup migrationService) will help in any way.     
[edit] actually it the logo text, not the poster image.

**Comment by garfield69** [comment]
work done on #875 seems to have cleared this one up. Any remaining issue will probably be resolved with a series refresh.
