### ISSUE TITLE
Magnet link launched, but Deluge not showing added torrents. Magnets work from browser

### ISSUE THREAD

**Issue by cocokola** [SchizoDuckie/DuckieTV#872]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...
Chrome, browser action
**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...stable 1.1.4

**What is your Operating System (Windows, Mac, Linux, Android)**
...windows 10

**Describe the problem you are having and steps to reproduce if available**
...Followed config doc for Deluge, Deluge is working as is webUI.  config completed successfully, looking at auto-download monitor, shows many matches, and magnet launched" but the torrents are now showing up in deluge. I am running Deluge 1.3.12

**Attach any DuckieTV statistics or Developer Console logs if available**
...Advise if you want me to enable logging, or provide screen shots. 
![capture](https://cloud.githubusercontent.com/assets/9909697/23912582/1dbbc616-08ae-11e7-844f-23ba9c45ac64.JPG)

The capture2 shows torrents I manually added.  The GUI client shows the same.  Nothign is added.  What am I missing?

**Comment by garfield69** [comment]
Hmm, interesting.     
At first glance it would appear that DuckieTV is connected to Deluge via a port that is not accepting torrents any longer.     

I see that you have changed the default Deluge webui port from 8112 to 7514.     
Have you shutdown Deluge and DuckieTV and start them up again after that change was made?      

After the restart, take a look at the DuckieTV Deluge Integration panel and confirm that the status shows **Status: Connected to Deluge Web API @ http://localhost:7514**      

If the restart does not fix your problem let us know and we can start digging deeper into the problem with you.

**Comment by cocokola** [comment]
I spoke too soon.  About ten minutes later, they started queueing in my
Deluge client.  Not sure why there was such a long delay on my lightning
fast system.

thanks for the reply.  I've been chasing an automated way to grab shows for
a while, finally can cut the cable.

**Comment by garfield69** [comment]
Glad it is working now.
