### ISSUE TITLE
wrong episodes returned when using the background DB adapter

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#874]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
standalone 

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
local github repo with latest development source

**What is your Operating System (Windows, Mac, Linux, Android)**
windows 7

**Describe the problem you are having and steps to reproduce if available**
when using the *episode* button from either the *series overview* or from the *episode details*, the episodes list that is present is from the wrong series

If I disable the use of the background DB adapter, the problem is resolved.

**Attach any DuckieTV statistics or Developer Console logs if available**
1. click on *Once Upon a Time* episode s06e12 then 2. click on *episode* button
![image](https://cloud.githubusercontent.com/assets/6933240/23932871/702a2c98-099f-11e7-99d9-439c3cc141b3.png)
Note last episode detail is from some other series. Note season 2 on right belongs to *Dirk Gently*.  then 3. click on episode in season 2's episode list
![image](https://cloud.githubusercontent.com/assets/6933240/23932915/cd5c92de-099f-11e7-9874-33178384e16f.png)
result is episode details from *Dirk Gently* episode s02e01, but with *Once Upon A time'*s episode title %-/
![image](https://cloud.githubusercontent.com/assets/6933240/23933088/01a4eb08-09a1-11e7-88f3-4529824f8976.png)

~~Perhaps of use, is that *Dirk Gently* is currently the last series added to the DB.~~ (red herring)

[edit] corrections, and insertion of missing image.
[edit 2] strike last sentence.

**Comment by SchizoDuckie** [comment]
Oh. Waitwut.

**Comment by SchizoDuckie** [comment]
Allright so:

- I was able to reproduce this easily
- I verified that all INSERT queries are OK. Loaded a full 1.5mb backup through the BackgroundPageAdapter and inspected it from the SQLiteAdapter

Now the hunt can continue on a much smaller set of code

**Comment by garfield69** [comment]
First clue, why when using the *background adaptor* does the series overview *Next Episode* work, but the *Last Episode* not?     

Then I found the answer in the *CRUD entities* routines.     

The *getNextEpisode* and *getLastEpisode* routines are functionally identical, apart from the *filter* in use.    
The *getNextEpisode* routine explicitly contains `Episodes.ID_Serie = ' + this.getID() + ' AND ` in the *filter* while the *getLastEpisode* does not.     
And while this apparently does not impact the queries for the *foreground adaptor*, it apparently makes all the difference to the *background adaptor* queries.     

By adding the additional filter parameter, the query are now working. Rinse and repeat for the *getActiveSeason* and *getNotWatchedSeason* and the problem appears to be solved.
