### ISSUE TITLE
refresh-all causes duplicate records in fanart table

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#875]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
using latest development source from local GitHub Desktop

**What is your Operating System (Windows, Mac, Linux, Android)**
windows 7

**Describe the problem you are having and steps to reproduce if available**
I discovered multiple duplicates in the fanart table, which had grown to over 9000 records.    

so I performed the following test:     
- emptied the fanart table    
- deleted the localStorage key *fanart.boostrapped*     
- restart duckietv     
- noted 648 fanart records     
- performed a refresh-all using the duckietv *settings,backup* panel, *refresh all series* section, *refresh all series now* button.     
- fanart records now 894, growth of 246 (there are 250 series in my db, and 4 do not have fanart images).

**Attach any DuckieTV statistics or Developer Console logs if available**
none.

- [x] need to investigate why fanart records are being added instead of updated.    
- [x] Also will need to devise a migrationService clean up down the line at some point.

**Comment by SchizoDuckie** [comment]
```
1.1.5fanartCleanup done! 2902 items deleted!
// run db refresh
1.1.5fanartCleanup done! 0 items deleted!
```
