### ISSUE TITLE
OffCloud.com torrent integration

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#876]
as requested in this Reddit https://www.reddit.com/r/duckietv/comments/6046zz/integration_request_offcloudcom_torrent/

> by Cyanidediamond3:     
>I have recently discovered offcloud.com and would love for it to be integrated into DuckieTV. API here https://github.com/offcloud/offcloud-api
>Basically it's a cloud based downloader that can link up to cloud storage. So basically you give it a magnet >link and it can download it and automagically upload it into your google drive (or dropbox etc). I am >hoping to use this to download my TV shows and link up Plex Cloud to it.

**Comment by SchizoDuckie** [comment]
I'm not for supporting / endorsing cloud-based services that require a paid account.
