### ISSUE TITLE
Cannot auth Trakt.TV on android

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#878]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Nightly 2017/03/18

**What is your Operating System (Windows, Mac, Linux, Android)**
Android
**Describe the problem you are having and steps to reproduce if available**
@knowair has reported in #877 the following:     
>tried a fresh install on android and cannot auth trakt, duckie opens it's own browser window to get the auth code and when you click back the duckie page re-loads and you cannot enter the code.     

I have split off the Android Trakt.tv issue into this ticket from 877 so it can be tracked, managed and closed independently.

**Attach any DuckieTV statistics or Developer Console logs if available**
...
***
Now that I finally have a Android sandbox to test with (Remix OS running Android Marshmellow) I should be able to do some testing and help trace this problem

**Comment by garfield69** [comment]
I can confirm that this is a problem for Android platforms.    
From the DuckieTV *you don't have any series yet!* page, clicking on the *connect DuckieTV to Trakt.tv account* button extends the page to show the Trakt.tv authorisation set.     
![image](https://cloud.githubusercontent.com/assets/6933240/24185533/74b7a4b8-0f38-11e7-99e6-e34f71983bff.png)     
Note how the PIN input box is disabled.     
When you click on the *Authorise DuckieTV to use your Trakt.tv account* button, you are navigated to the Trakt.TV login page and key presentation page.    
When you use the Android back button to navigate back to the DuckieTV page, you cannot proceed because the PIN input box is still disabled.     

The solution is is to make the PIN input box permanently enabled.

**Comment by knowair** [comment]
Works perfectly.
Nice one.
Cheers.
