### ISSUE TITLE
Deluge 1.3.14 has broken the current DuckieTV Deluge Client Interface.

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#880]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Latest GitHub Desktop clone of the development source

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 7

**Describe the problem you are having and steps to reproduce if available**
After the Deluge Host is upgraded from version 1.3.13 to 1.3.14, the DuckieTV Deluge Client Interface can no longer successfully connect.    
Looking at the Deluge Host changelog, I see the have made two patches to the WEBUI components:     
- #1908: Backport bind interface option for server.    
- Security: Fixed WebUI CSRF Vulnerability.     

**Attach any DuckieTV statistics or Developer Console logs if available**
```
TraktTVStorageSyncTarget.js:45 TraktTV storage sync target initialized!
2017-03-25 12:34:44.332 localhost:7514/json Failed to load resource: the server responded with a status of 500 (Internal Server Error)
2017-03-25 12:34:44.333 angular.js:14195 
Objectconfig: Objectdata: Objectid: 
0method: "auth.check_session"
params: Array(0)length: 0
__proto__: Array(0)
__proto__: Objectheaders: 
ObjectAccept: "application/json, text/plain, */*"Content-Type: "application/json;charset=utf-8"
__proto__: Objectmethod: "POST"
paramSerializer: function ngParamSerializer(params)
transformRequest: Array(1)
0: function (d)
arguments: (...)
caller: [Exception: TypeError: 'caller' and 'arguments' are restricted function properties and cannot be accessed in this context.
    at Function.remoteFunction (<anonymous>:2:14)]
length: 1
name: ""
prototype: Object
__proto__: function ()
[[FunctionLocation]]: angular.js:11023
[[Scopes]]: Scopes[3]
length: 1
__proto__: Array(0)
transformResponse: Array(1
)0: function defaultHttpResponseTransform(data, headers)
length: 1
__proto__: Array(0)
url: "http://localhost:7514/json"
__proto__: Objectdata: ""
headers: function (name)
arguments: (...)
caller: (...)
length: 1
name: ""
prototype: Object
__proto__: function ()
[[FunctionLocation]]: angular.js:10932
[[Scopes]]: Scopes[3]
status: 500
statusText: "Internal Server Error"
__proto__: Object
(anonymous) @ angular.js:14195
2017-03-25 12:34:44.338 angular.js:14195 Deluge Connect call failed.
(anonymous) @ angular.js:14195
2017-03-25 12:34:44.343 BaseTorrentClient.js:215 Unable to connect to Deluge Retry in 15 seconds
```

We will need to provide the required support to the DuckieTV Deluge Client to enable connection to Deluge 1.3.14 as well as backward compatibility to pre 1.3.14 versions.     
I will do some research.

**Comment by garfield69** [comment]
I have compared the *Request Headers* between Deluge 1.3.13 and 1.3.14 when starting a Chrome Browser WEBUI session, and see that the main difference between the two versions is the use of a Cookie that contains a **_session_id**.     
So it looks like we are going to have to change the DuckieTV Deluge Client interface to support the use of a Cookie.      
If memory serves, I recall that the DuckieTV qBitTorrent Client interface was changed for 3.2+ to use a Cookie, so I'll take a look at how that works and see if I can adapt it for use with Deluge 1.3.14

**Comment by garfield69** [comment]
Oh, I see from #423 that Schizoduckie ended up bypassing the need for a login cookie with qBitTorrent 3.2plus by switching to using auth in the header.     
So that's a bust. :-(

**Comment by SchizoDuckie** [comment]
Any way to switch to the authHttpBackend method to pass credentials to $http ?
This should bypass the need for header fiddling.

Base rule of thumb for apps with relaxed XHR permissions is : if $http / XmlHttpRequest can handle cookies and auth automagically, let it.

**Comment by ghost** [comment]
I am facing the same issue in Xubuntu 17.04 OS as well. I am not able to connect to Deluge Web-UI from DuckieTV. 

Kindly suggest a fix.

**Comment by garfield69** [comment]
IF you are on *DuckieTV Stable 1.1.4* then upgrade to the latest *Nightly* https://github.com/DuckieTV/Nightlies/releases which can talk to *Deluge 1.3.14*, or continue to use *DuckieTV 1.1.4* and downgrade your *Deluge* back to *1.3.13*.

**Comment by ghost** [comment]
Will there be any issues if I upgrade to Nightly release?

**Comment by garfield69** [comment]
The Nightly is essentially DuckieTV 1.1.5 Work In Progress, or another term for it would be a CANARY release. As such there is always a risk that there could be a problem. So as a precaution, first take a backup of the DuckieTV data using the *Settings, Backup* panel, just in case.

**Comment by ghost** [comment]
Thanks for the prompt response. I am going to another route by installing some other torrent client. Let me see if it works with it.
