### ISSUE TITLE
Filtered out MS - with no settings in min/max or 0/1000000 for settings.. nothing downloading?

### ISSUE THREAD

**Issue by cocokola** [SchizoDuckie/DuckieTV#883]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...Browser Action Mode

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...

**What is your Operating System (Windows, Mac, Linux, Android)**
...Windows

**Describe the problem you are having and steps to reproduce if available**
...the monitor is only showing two states: not found or filtered by MS, even though I have tried no settings for min/max and 0/10000000  .  
![2capture](https://cloud.githubusercontent.com/assets/9909697/24438115/b8cd1454-140a-11e7-9fd6-1a1c0d52064b.JPG)

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by cocokola** [comment]
Ok, ten minutes later after putzing with this for 15 minutes, it started working as expected.  

so this isn't a total waste, I don't see info on CSM,CSS,IPQ,IRK.,IIK.  They are always "X" - I see pop-up descriptions.. Are these just flag indicators?

**Comment by garfield69** [comment]
>Ok, ten minutes later after putzing with this for 15 minutes, it started working as expected.      

Oh good. Did you change anything or did it just start working with whatever settings you had when you posted that image previously?

>so this isn't a total waste, I don't see info on CSM,CSS,IPQ,IRK.,IIK. They are always "X" - I see pop-up descriptions.. Are these just flag indicators?     

Yes. They are meant to aid you when the auto-download does not pick a torrent you think should have been found. They indicate the presence of series custom overrides.      

I am in the process of updating the wiki to provide more basic info on the flags, which I have not completed, but you may find the following useful (or not) :-)  https://github.com/SchizoDuckie/DuckieTV/wiki/Auto-Download-FAQs
