### ISSUE TITLE
OpenSubtitles alternative

### ISSUE THREAD

**Issue by cajeiri** [SchizoDuckie/DuckieTV#888]
Hello, just wanted to chime in about adding another option for subtitles.

https://subscene.com/ might be an option that's good, sometimes I find subtitles there faster or with better quality for both English and French.

**Comment by gerardo15** [comment]
I would also love to have subscene.

**Comment by tomek1tomek1** [comment]
And those too:
https://www.opensubtitles.org/
http://napisy24.pl/
http://www.napiprojekt.pl/
http://subtitlesbank.com/
http://www.subtitleseeker.com/
https://www.yifysubtitles.com/
https://www.podnapisi.net/
would be fantastic, thank you - just give us alternative - please. Regards

**Comment by cajeiri** [comment]
Closing this as it has been over 2 years.
