### ISSUE TITLE
Mac nightly installer no longer gives the option to delete installer file

### ISSUE THREAD

**Issue by lonelyfairie** [SchizoDuckie/DuckieTV#889]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone
**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
DuckieTV-201704100130-OSX-x64

**What is your Operating System (Windows, Mac, Linux, Android)**
Mac Os X Sierra

**Describe the problem you are having and steps to reproduce if available**
Not a problem, just that previous installers asked if you wished to delete the installer file after it finished installing and the latest one did not.
Not a big issue as you can delete manually but a good feature to have nonetheless :)

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by lonelyfairie** [comment]
April 20th installer did ask if I wanted to delete the installation file. 🎉

**Comment by garfield69** [comment]
@lonelyfairie  FYI, we have not made any changes to the way we build the nightlies since the 5th of April.
