### ISSUE TITLE
Change fallback trackers

### ISSUE THREAD

**Issue by CorralPeltzer** [SchizoDuckie/DuckieTV#890]
From the list of the trackers used in case there is no tracker;

```
http://tracker.trackerfix.com:80/announce
udp://9.rarbg.com:2710/announce
udp://9.rarbg.me:2710/announce
udp://9.rarbg.to:2710/announce
udp://coppersurfer.tk:6969/announce
udp://eddie4.nl:6969/announce
udp://exodus.desync.com:6969
udp://glotorrents.pw:6969/announce
udp://open.demonii.com:1337
udp://p4p.arenabg.ch:1337/announce
udp://p4p.arenabg.com:1337
udp://torrent.gresille.org:80/announce
udp://tracker.aletorrenty.pl:2710/announce
udp://tracker.coppersurfer.tk:6969/announce
udp://tracker.glotorrents.com:6969/announce
udp://tracker.internetwarriors.net:1337
udp://tracker.leechers-paradise.org:6969/announce
udp://tracker.openbittorrent.com:80/announce
udp://tracker.opentrackr.org:1337/announce
udp://tracker.zer0day.to:1337/announce
```
The first one, trackerfix, is not open (only works with RARBG torrents), and half of the others are currently dead, like openbittorrent or demonii.

Maybe it would be better to use another list, like the one in [ngosang/trackerlist](https://github.com/ngosang/trackerslist), or even query the [newTrackon API](https://newtrackon.com/api) for currently active or stable open trackers. (disclaimer: I am the maintainter of [newTrackon](https://newtrackon.com/))

**Comment by garfield69** [comment]
@CorralPeltzer  Thank you for the spotlight.     

@SchizoDuckie  I'm thinking DuckieTV could fetch 20 trackers monthly and save them to localStorage for js/services/TorrentSearchEngines/TorrentSearchEngines.js to use.     
Any preference towards using either one of the two services mentioned?
