### ISSUE TITLE
Nyaa Temporary Stopgap

### ISSUE THREAD

**Issue by cajeiri** [SchizoDuckie/DuckieTV#896]
Hello, since NyaaTorrents is probably gone forever since all of the domains were purposefully removed, I'm going to list off a few alternatives for a temporary replacement. HorribleSubs have confirmed that there will be a NyaaTorrents equivalent created by another group of people, but that will take some time, obviously.

LEGEND: **Recommended** and _Experiencing outages_

Public alternatives:
1. _Nyaa Pantsu_ - a backup website of Nyaa's database featuring a cache of magnet links and torrents, will probably NOT include new torrents. https://nyaa.pantsu.cat/

2. **Horriblesubs**: the magnet links still work, torrents are not hosted anywhere atm. Temporary RSS has been added until a NyaaTorrents equivalent is created. http://horriblesubs.info/

3. _Tokyo Toshokan_ - A torrent tracker that resembles Nyaa in simplicity and in offered torrent diversity. tokyotosho.info

4. AnimeTosho - An automated mirror website for Tokyo Toshokan and Nyaa torrents. https://animetosho.org/

5. Anidex - An anime torrent website, resembles Nyaa up to a point as far as things it covers, not as popular, might be a good alternative if it starts being used. https://anidex.moe/

Private trackers:

1. **Baka.bt**: private anime torrent website. Account might be available IF I can find which email I made it with. https://bakabt.me/

2. **Animebytes**: this is a closed private torrent website. Account is available. https://animebytes.tv/

3. Asian DVD Club - A private torrent tracker for all sorts of Asian DVDs and BluRay rips.  No account is available. http://asiandvdclub.org

4. Animetorrents - A private torrent tracker. No account is available. http://animetorrents.me/

5. AvistaZ - A private ratio-centered torrent tracker. No account is available. https://avistaz.to/

**Comment by SchizoDuckie** [comment]
If there are only private trackers and temporary things available I vote we remove it for now until something stable and public pops up.

**Comment by cajeiri** [comment]
@SchizoDuckie It was already removed 12 hours ago by garfield. I can confirm that HorribleSubs is a long-standing equivalent, but I am not sure whether we can add a search function for it without that temporary RSS feed. I fainly remember garfield mentioning it was hard months ago, but I might be imagining it.

**Comment by amayra** [comment]
@roshavagarga do you have animebytes invite ?

**Comment by SchizoDuckie** [comment]
No invite trading here please.

**Comment by cajeiri** [comment]
@SchizoDuckie @garfield69 Something stable and public has popped up: https://nyaa.si/

This is an updated version of nyaa that's being started up by new people. It is a work-in-progress but it is being promoted by horriblesubs, which is one of the largest websites that could offer it promo, so I'm confident we should look at this as the replacement for the old Nyaa. The website offers RSS, Magnet links and .torrent files.

**Comment by cajeiri** [comment]
I reached out to the developers on their IRC channel and they gave me some basic info on how stuff works:

Sorting by date links:  https://nyaa.si/?s=id&o=desc || https://nyaa.si/?s=id&o=asc
torrent dl: https://nyaa.si/view/<id>/torrent
magnet redirect: https://nyaa.si/view/<id>/magnet

If you need any other info, I can reach out again and acquire it if it would be easier for you guys :)
