### ISSUE TITLE
Autodownload Magnet Links are not opening with integrated QBitTorrent 3.2+ but Transmission

### ISSUE THREAD

**Issue by ghost** [SchizoDuckie/DuckieTV#897]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...Stable 1.4.4

**What is your Operating System (Windows, Mac, Linux, Android)**
...Linux

**Describe the problem you are having and steps to reproduce if available**
...When I use the autodownload feature or search a torrent, the magnet links are getting opened in Transmission instead of the integrated QBitTorrent 3.2+.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
This is a problem with the *linux qBittorrent* installation, which does not set up a *magnet association* with the qBittorrent app during the install/setup.     
To create/overwrite the existing magnet association, open a terminal and paste the following command:
```
gvfs-mime --set x-scheme-handler/magnet qBittorrent.desktop
```
you should see a `Set qBittorrent.desktop as the default for x-scheme-handler/magnet` confirmation.      

This should fix your problem as it did for me on my *ubuntu 16.10* when I installed *qBittorrent 3.3.7* on my sandbox.

Let me know how you go.
