### ISSUE TITLE
Nyaa search improvement

### ISSUE THREAD

**Issue by cajeiri** [SchizoDuckie/DuckieTV#900]
This is not a bug, but an improvement request.

I'm guessing something changed along the way between Nyaa.eu and Nyaa.si (different developers, etc.).
I know for a fact that the new website uses something called elasticsearch, while the old one used a simpler method for searching.

The results in DuckieTV are less than those in Nyaa.si natively. An easy way to check this is by searching for "Fukumenkei" which gives 4 results in DuckieTV and over 10 in Nyaa.si.

I'm not sure if you've set a specific category, but there are more even when I limit it to the English subbed category.

Thanks in advance :)

**Comment by garfield69** [comment]
I cannot replicate your findings.     
If I type *Fukumenkei* in the nyaa.si search box I get 54 results, and if I do the same on my development DuckieTV, I get 54 results.     `https://nyaa.si/?q=Fukumenkei&f=0&c=0_0`     
Nyaa.si is under heavy development, and they are tinkering with their search engine as we speak, as well as all other aspects of their web site.     
Also, DuckieTV does not use categories,we use a general search for all our SE queries.

**Comment by cajeiri** [comment]
@garfield69 I wiped my DuckieTV completely and loaded my backup - still got the same results when searching for Fukumenkei. The version of my DuckieTV Nightly is 3017.5.17.91.

https://pastebin.com/CQe81Lpu - this is a pastebin of my user preferences and other local storage keys. If there is any other way to debug, please tell me how and I'll gladly help you get to the bottom of this :)

**Comment by garfield69** [comment]
lets start by taking a look at your manual search results.     
perform the following sequence and *screen capture* the result and *paste* below
![image](https://cloud.githubusercontent.com/assets/6933240/26192692/cbe5f546-3c06-11e7-8219-230b9c00747e.png)
Note: is step 2 shows *Show Advanced Options* then click so it turns into *Hide Advanced Options*.

**Comment by cajeiri** [comment]
@garfield69 Close the issue, it seems that the "Minimum 50 Seeders" option was turned on and that was what was causing the problems in general. Sorry for wasting your time :)
