### ISSUE TITLE
[Request] Replacement For Fan Art

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#901]
Can you please look at replacing Fan Art with TMDB .
Because, TMDB has a wider range of artwork with regular updates, so artwork is not out of date like the artwork at Fan Art.

https://themoviedb.org/documentation/api

Additionally, I have noticed lots of 404 errors from Fan Art.

Thanks

![capture](https://cloud.githubusercontent.com/assets/16563034/26285046/941c7690-3e3f-11e7-8554-45984b9bfc9f.JPG)

**Comment by garfield69** [comment]
When Trakt.tv stopped serving images, TMDB was the first image server to be evaluated, but @SchizoDuckie  found issues when applying for an api key, so FanArt was chosen instead.     
All the details are in #780.
