### ISSUE TITLE
Duckietv won't connect to qbittorrent anymore

### ISSUE THREAD

**Issue by Lousha1** [SchizoDuckie/DuckieTV#903]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Chrome extension, browser action

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Don't know, added it to Chrome about two weeks ago

**What is your Operating System (Windows, Mac, Linux, Android)**
Win10

**Describe the problem you are having and steps to reproduce if available**
I've been using Duckietv with autodownload and it was working fine. Yesterday I updated my torrent client, qbittorrent to the latest version, keeping every user setting. Since then Duckietv does not "see" the client, even though it's active, the Web UI settings are how they were before. I tried closing both, then I restarted the whole laptop, but didn't help. If I try to connect at just says connecting, please wait, then nothing happens. If I try to do the "test and save" again, nothing happens. Checked the error logs, it says no client is "listening" . Can't find a client.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by Lousha1** [comment]
Problem solved. Reinstalled the previous version of the client and voila, works again, instantly. I found some info on the qBittorrent website mentioning that other apps/programs that require the web UI also don't work since the update so it seems it had nothing to do with Duckietv, it was some bug with the new version of the client. 
Anyhow, thanks to everyone who took the time to read/contribute! -

**Comment by garfield69** [comment]
Thanks for reporting.     
It appears that qBittorrent have implemented CSRF protection with their latest release.      
We will need to add the necessary support to DuckieTV's qBittorrent client interface to support the new qBittorrent releases, as well as continue backward compatibility with older versions.     
I will post an update once the research/work/test is complete.

**Comment by Lousha1** [comment]
Thank you!

**Comment by garfield69** [comment]
So qBitTorrent 3.3.13 introduced Cross-Site Request Forgery protection for their WEBUI API. However, they set the rules too tight, and ended up denying any WEBUI API user except their own internal one.     
Issue https://github.com/qbittorrent/qBittorrent/issues/6882 was raised, and it appears that the next release 3.3.14 will loosen the rules enough to allow other clients access.     
Until then, continue using 3.3.12 with DuckieTV.

**Comment by DennisFaucher** [comment]
Upgraded qBittorrent to 4.1.7 and problem solved
wget https://mirrors.edge.kernel.org/ubuntu/pool/universe/q/qbittorrent/qbittorrent_4.1.7-1_amd64.deb
