### ISSUE TITLE
Need help changing the calendar layout

### ISSUE THREAD

**Issue by ManoharOfficial** [SchizoDuckie/DuckieTV#904]
I updated to the latest version and I cant seem to go to the old calendar week layout for some reason. please help. here's an image of what I have (on top) and what I want to switch back to (bottom)
![5xk16sx](https://user-images.githubusercontent.com/7362543/27005402-af43208e-4e3b-11e7-8a96-d7e0a7907785.jpg)

**Comment by garfield69** [comment]
try clicking on the *switch between Calendar and ToDo mode* button :-)
![image](https://user-images.githubusercontent.com/6933240/27005442-e49a983e-4e72-11e7-83a5-4b826ac5d442.png)

**Comment by ManoharOfficial** [comment]
Wow, that was easy. Should've read the documentation or something. Anyway thanks. You guys are doing great work, keep it going!
