### ISSUE TITLE
Question: Is it possible to use the tracker T411 for autodownload ?

### ISSUE THREAD

**Issue by kevincaradant** [SchizoDuckie/DuckieTV#909]
Hi

I see pirateBay and many others tracker, but I would to know if it was possible to use the tracker T411 or not ? I would to have my tvshows in VOSTFR and I can't find it for the moment

Thank you in advance

Regards

**Comment by garfield69** [comment]
>I see pirateBay and many others tracker, but I would to know if it was possible to use the tracker T411 or not ?      

Not with DuckieTV 1.1.4      
However, in the next release we have added the ability to make use of the Jackett proxy, which will allow DuckieTV to have access to Torrent411 and many other public/semi-private/private sites.       
If you want to try it out you will need to switch to using the latest DuckieTV Nightly at https://github.com/DuckieTV/Nightlies/releases      
Info on Nightly installs can be found at thi wiki https://github.com/SchizoDuckie/DuckieTV/wiki/How-to-install-development-versions-of-DuckieTV, follow the *Nightly* sections.     
And this wiki
 https://github.com/SchizoDuckie/DuckieTV/wiki/Using-Jackett-with-DuckieTV should help you get started with Jackett should you need it.

**Comment by kevincaradant** [comment]
Awesome ! Thank you. It's working perfectly :)
I tried the standalone DuckieTV application, and Jackett on Ubuntu 17.04 64 bits for information ;)

Edit:
Just a little thing, how to force duckie to search the new tvshow episodes ? I can download it manually but It didn't see any news episodes from tractv even if the calendar says a lot of episode not seen yet.
of course autodownload option is activated. And UtorrentWebUi also. I'm running on the nightly bild but even with Duckie1.14 it was the same behavior

Look at this picture, the queue is frozen:
![capture du 2017-06-18 00-03-44](https://user-images.githubusercontent.com/6093175/27256574-b34d801a-53b9-11e7-89e4-88ffd2bd0d96.png)

**Comment by kevincaradant** [comment]
Just a little thing, how to force duckie to search the new tvshow episodes ? I can download it manually but It didn't see any news episodes from tractv even if the calendar says a lot of episode not seen yet

**Comment by garfield69** [comment]
>Just a little thing, how to force duckie to search the new tvshow episodes ?      

Have a read of https://github.com/SchizoDuckie/DuckieTV/wiki/Auto-Download-FAQs and if you still have questions let me know.    

>Play a downloaded video tab doesn't work.     

Correct. You are running a Nightly, which is essentially a CANARY release of DuckieTV. The play button is a W.I.P. that has not been fully implemented yet.

**Comment by kevincaradant** [comment]
Thank you for the documentation.

oh damn it, 

If I understand, disabled NM like you can see on my picture, it's because T411 does not support magnet :( ?

**Comment by garfield69** [comment]
>If I understand, disabled NM like you can see on my picture, it's because T411 does not support magnet :( ?     

That would seem to be the case.      
But if you login to T411 manually, and do a search, and find that their results page shows magnets as well as .torrents listed, then consider contacting the Jackett team to see if they can amend their T411 profile to add a magnet to it.
https://github.com/Jackett/Jackett/issues/new

**Comment by kevincaradant** [comment]
Yep thank you but I just asked on their discussion thread and the answer is NO ....
Do you think that you could use .torrent one day ? I don't understand the link between autodownload and magnet / torrent so maybe it's a dumb question 

Maybe you can use some github projects which transform a .torrent file in .magnet file ?

**Comment by garfield69** [comment]
The problem is that DuckieTV cannot examine the content of the .torrent file in order to extract the hash key that identifies the torrent. Without this the DuckieTV torrent client cannot track the torrent progress on the connected torrent host, or issue commands via the torrent client to manage the torrent, or  auto-mark the download as complete or perform an auto-stop.      
The hash key of a magnet on the other hand is part of the url that makes up the magnet parameters, so ADS can use that to identify the torrent.

**Comment by kevincaradant** [comment]
ok thanks for the explanations.
But when I click on download, I have a list and I take the first. 

> Without this the DuckieTV torrent client cannot track the torrent progress

Maybe you can find a way to do that easily no ? Don't need to read the hash no ? 
The aim is to add this link at utorrent or an other manager of torrent, that's all :)

If ADS can't show the status or progress, It doesn't matter,  you can see that in your utorrent for example

**Comment by kevincaradant** [comment]
By the way, If you see the previous attachment, I think you should say "AUTODL désactivé" and not "AUTODL désactivés", same thing for "Téléchargés en", you should write "Téléchargé en". 
When you add a "s" at the end of preterit (in french), it's because you want say a plural word but in this case , I think you have only one AUTODL and one download so it's singular.

Edit
When I click on the first torrent link that duckie suggest, I get this display:
![img_20170618_123511](https://user-images.githubusercontent.com/6093175/27260353-284eb3dc-542a-11e7-967a-6bd15686685c.jpg)
![img_20170618_123501](https://user-images.githubusercontent.com/6093175/27260357-3b75cf9a-542a-11e7-8722-ace7eab3d97f.jpg)

So it's perfect, for me it's not easy to understand your contraint to start directly the torrent link. 
In this context, I have to create a script, where I will have to parse the calendar html and see which link are not green and before the today date to say that it's not downloaded yet and then I will have to load the page of the épisode via dunkietv and then click on the button search and click on the first item that dunkietv returns.

To avoid that, @garfield69,  I think you can do that easily with your amazing application and this feature could safe a lot of  time at people like me who didnt have french torrent website with a good content  with magnet. T411 is the best in my knowledge but its only torrent unfortunately  :/

**Comment by garfield69** [comment]
>By the way, If you see the previous attachment, I think you should say "AUTODL désactivé" and not "AUTODL désactivés", same thing for "Téléchargés en", you should write "Téléchargé en".
When you add a "s" at the end of preterit (in french), it's because you want say a plural word but in this case , I think you have only one AUTODL and one download so it's singular.     

Feel free to edit https://github.com/SchizoDuckie/DuckieTV/edit/angular/_locales/fr_fr.json and make any corrections you want. Once you have saved your changes, create a pull request and I will gratefully import your change with the master source. Thanks.

**Comment by garfield69** [comment]
I've raised https://github.com/SchizoDuckie/DuckieTV/issues/916 to research using .torrents with ADS

**Comment by kevincaradant** [comment]
OK, Indeed that will be more quick that I do a PR instead of say like that. 
I will do that :)

And thank you to think at a solution about .torrent file

**Comment by kevincaradant** [comment]
@garfield69, I made a PR about the translation. Let me know if something wrong. Travis failed but I don't think it's my fault :)
