### ISSUE TITLE
Integration appears broken with qBittorrent

### ISSUE THREAD

**Issue by paulds8** [SchizoDuckie/DuckieTV#910]
Chrome Extension: New Tab

Duckie 1.1.4
qBittorrent 3.3.13
Linux (Ubuntu)

If I navigate to http://localhost:8080 I can successfully access the API, however the integration is no longer working. It has been working fine for weeks. I am still able to manually search within DuckieTV and click on a magnet link to download... however DuckieTV is not then aware that the file is downloading and the autodownload capability remains broken.

I have: rebooted the machine, changed to a different torrent app and back, changed/disabled/re-enabled the login info.

Any help would be appreciated. The console log isn't super helpful, but I have included it as well.

Log:
app.js:539 GET http://****:****@localhost:8080/version/api 401 (Unauthorized)
deps.js:2229 qBittorrent 3.2+ Connect call failed. No client listening.
app.js:11652 Unable to connect to qBittorrent 3.2+ Retry in 15 seconds

**Comment by garfield69** [comment]
Duplicate of #903      
qBitTorrent 3.3.13 introduced Cross-Site Request Forgery protection for their WEBUI API. However, they set the rules too tight, and ended up denying any WEBUI API user except their own internal one.
Issue qbittorrent/qBittorrent#6882 was raised, and it appears that the next release 3.3.14 will loosen the rules enough to allow other clients access.
Until then, if you want to use qBitTorrent with DuckieTV you will need to use version 3.3.12 .
