### ISSUE TITLE
Question: Any roadmap about watch / download movies ? 

### ISSUE THREAD

**Issue by kevincaradant** [SchizoDuckie/DuckieTV#911]
Hi

It's awesome for the tvshows but one day, can we see the same thing with movies ? TrackTv manage also the movies :) 

Thank you in advance,

Regards

**Comment by garfield69** [comment]
DuckieTV's goal is to take care of TV-Show addicts.      
As far as I know, there are not plans to add Movies to DuckieTV.     
Movies are just not a part of DuckieTV's DNA.

**Comment by kevincaradant** [comment]
OK, if you change your mind about this feature, don't hesitate to open the ticket again :)
