### ISSUE TITLE
Question: Any way to run it on raspberry pi / ARM device ? 

### ISSUE THREAD

**Issue by kevincaradant** [SchizoDuckie/DuckieTV#912]
Hi

I want to install it on my raspberry pi but it's a ARM architecture, and I don't know how to build this application easily ?

In the package json, I didn't see any script allowing to build for dev or prod environment :)

Thank you in advance

**Comment by garfield69** [comment]
The standalone version of DuckieTV is dependant on [NWJS](https://nwjs.io/) to provide the run time environment to execute DuckieTV AngularJS framework javascript.      
NWJS supports Windows, Mac OSX, and Linux.     
But I don't believe there is an ARM build available.      
However, if you can find a recent google chrome browser or chromium browser for your  raspberry pi then you should be able to run the DuckieTV browser extension.

**Comment by kevincaradant** [comment]
Alright, if I choose the chromium option,  the autodownload with the utorrent webUI can work only if google chrome is opened isn't it ? 

I found this: https://github.com/LeonardLaszlo/nw.js-armv7-binaries

So maybe the standalone installation can work :)

**Comment by garfield69** [comment]
>Alright, if I choose the chromium option, the autodownload with the utorrent webUI can work only if google chrome is opened isn't it ?     

correct.

>I found this: https://github.com/LeonardLaszlo/nw.js-armv7-binaries     
>So maybe the standalone installation can work :)       

Awesome.  In which case you may want to have a read of https://github.com/SchizoDuckie/DuckieTV/wiki/How-to-Install-a-Development-version-of-the-Windows-DuckieTV-Standalone-SOURCE so you can set up DuckieTV to run under your ARM version of NWJS.

**Comment by kevincaradant** [comment]
Nice, I will try today or tomorrow. I will say to you if that works ;)

Edit: The compilation is too hard for my raspberrypi, so I tried the build version NW.JS 0.21 but when I start it, I get some errors ...
So for the moment I keep your chromium version nightly build which works well on my raspberry pi ;)
