### ISSUE TITLE
Question: New instance with new tab on chromium-browser ? 

### ISSUE THREAD

**Issue by kevincaradant** [SchizoDuckie/DuckieTV#914]
Hi

I tried the plugin duckieTV on chromium. I set everything like I want on my rapsberry pi. 

Now I want to start duckieTV with chromium instance at the boot of OS.

The only way I found is to start chromium-browser with new tab, so I install the plugin which start duckieTV when you open a new tab but unfortunatly, it's seems 0 data of my previous was keep. It's like it was a new instance without my T411 provider. Without anything about settings and trackTv etc. Is it normal ? 
But if I click at the hand on the other extention whih open duckieTv, I get all my data etc 

Do you see any better solution to start the instance of chromium at the start of OS ? 

Thank you,

Regards

**Comment by kevincaradant** [comment]
OK I think I was wrong on the way to do that.

You can also start a extension of chrome like that:

`chromium-browser chrome-extension://id_of_extention/tab.html`

So we don't need a new tab to open DuckieTv

**Comment by garfield69** [comment]
>when you open a new tab but unfortunatly, it's seems 0 data of my previous was keep. It's like it was a new instance without my T411 provider. Without anything about settings and trackTv etc. Is it normal ?     

Chrome Browser Extension security rules specify that extensions cannot interact. This means that each is given its own data space which other extensions cannot access.     
So in effect, the *Action mode* and *tab mode* are two separate apps.     
You would need to use the DuckieTV *Settings, Backup* on the *Action mode* version and follow that up with a DuckieTV *Settings, Import* on the *tab mode* to copy the settings and data across.

**Comment by kevincaradant** [comment]
Alright thanks for the tip if I need to share between Action and tab version
