### ISSUE TITLE
qbittorrent integration is broken

### ISSUE THREAD

**Issue by Shad-Shad** [SchizoDuckie/DuckieTV#915]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Stable 1.1.4 64 bit

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 10

**Describe the problem you are having and steps to reproduce if available**
The qbittorrent inegration is not working anymore. I have qbittorrent 3.3.13 64 bit. It was working fine on the previous version. I am not sure, but i think the integration broke down after i updated my qbittorrent to the latest version.

I have tried to re-install qbittorrent and duckietv, but did not help.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
Duplicate of #903
qBitTorrent 3.3.13 introduced Cross-Site Request Forgery protection for their WEBUI API. However, they set the rules too tight, and ended up denying any WEBUI API user except their own internal one.
Issue [qbittorrent/qBittorrent#6882](https://github.com/qbittorrent/qBittorrent/issues/6882) was raised, and it appears that the next release 3.3.14 will loosen the rules enough to allow other clients access.
Until then, if you want to use qBitTorrent with DuckieTV you will need to use version 3.3.12 .
