### ISSUE TITLE
CAnnot connecty to qbittorrent-3.3.13

### ISSUE THREAD

**Issue by mar5kid** [SchizoDuckie/DuckieTV#917]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...1.1.4

**What is your Operating System (Windows, Mac, Linux, Android)**
...w10

**Describe the problem you are having and steps to reproduce if available**
...cannot connect to qbittorrent-3.3.13. I previously managed fine with Utorrent 3,2.
--I successfully tested qbittorent remote connection as working using firefox browser.
--I have tried restarting both apps. Resetting password etc but will not connect

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
Duplicate of #903
qBitTorrent 3.3.13 introduced Cross-Site Request Forgery protection for their WEBUI API. However, they set the rules too tight, and ended up denying any WEBUI API user except their own internal one.
Issue qbittorrent/qBittorrent#6882 was raised, and it appears that the next release 3.3.14 will loosen the rules enough to allow other clients access.
Until then, if you want to use qBitTorrent with DuckieTV you will need to use version 3.3.12 .
