### ISSUE TITLE
TYPEERROR: CANNOT READ PROPERTY 'TOUPPERCASE' OF UNDEFINED

### ISSUE THREAD

**Issue by russoedu** [SchizoDuckie/DuckieTV#921]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standlone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
DuckieTV-1.1.4-OSX-x64

**What is your Operating System (Windows, Mac, Linux, Android)**
Mac OS 10.12.5

**Describe the problem you are having and steps to reproduce if available**
When I use the "Auto Download" no show is downloaded. Then, when I try finding a Torrent, the following error is displayed:

`TYPEERROR: CANNOT READ PROPERTY 'TOUPPERCASE' OF UNDEFINED`

![screenshot](https://cl.ly/lG8c/Image%202017-06-22%20at%207.36.43%20AM.png)

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
The error you are seeing can occur when the site you are searching on, responds in an unexpected way.     
From the screen shot you provided, it looks like you are using *TPB* as the default search engine. *TPB* occasionally goes into *Database Maintenance* mode and stops returning search results.     
Another common cause is Cloudflare (the Content Delivery Network that TPB uses) turning on DDOS protection or similar, which interferes with processing search results.     

You have three choices:       
1. Set the default search provider to use another Search Engine, such as *Zooqle* for instance. Visit the *Settings, Torrent Search Engines* panel, and click on *Zooqle* to make that the default Search Engine.
![image](https://user-images.githubusercontent.com/6933240/27454515-4477b26c-57ee-11e7-82eb-f5e95727b340.png)
2. Wait a while and try again later. Or you could try switching to another TPB address. Visit the *Settings, Torrent Search Engines* panel, scroll down the *The Pirate Bay* Section, and change the address to `https://thepiratebay.se` or `https://thepiratebay.org` or perhaps to one of the valid proxies like `piratebay.run` or one of the ones listed at `http://www.piratebayproxylist.co/` or use the *find random mirror* button which tries 3 proxies at a time. There are a lot of inactive, invalid proxies out there, so you may need to keep fishing for a while with the random button.
![image](https://user-images.githubusercontent.com/6933240/27455522-b229b014-57f1-11e7-82d6-0c9c06a9b615.png)
3. You could upgrade to the latest Development DuckieTV and use the Jackett proxy to access TPB.      
Jackett can handle cloudflare DDOS and some forms of Captcha prompts, so stands a better chance of reliably returning search results.
Official Canary DuckieTV https://github.com/DuckieTV/Nightlies/releases      
Wiki that may be useful should you need them:       
https://github.com/SchizoDuckie/DuckieTV/wiki/How-to-Install-a-Development-version-of-the-Windows-DuckieTV-Standalone-NIGHTLY      
https://github.com/SchizoDuckie/DuckieTV/wiki/Using-Jackett-with-DuckieTV

**Comment by russoedu** [comment]
Ok, thanks! I'll try the Nightly builds.
