### ISSUE TITLE
Static URL For Nightly Builds

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#922]
Can you please provide a static direct download URL for the nightly builds executable.
Thanks

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
Yes please! I keep getting Cross-site scripting (XSS) alerts when I try to download any nightly builds. Anyone else?

@SchizoDuckie @DuckieTV

**Comment by SchizoDuckie** [comment]
@L-a-n-g-o-l-i-e-r-s  can you provide a screenshot of that?

The latest nightly can always be found on  https://github.com/duckietv/nightlies/releases/latest

**Comment by zero77** [comment]
Yes but, the file name changes which makes the URL change each time.

**Comment by SchizoDuckie** [comment]
Sorry i'm not going to change that

**Comment by zero77** [comment]
O I see, Thanks

**Comment by SchizoDuckie** [comment]
The whole point of a nightly is that they're versioned with a unique name

**Comment by zero77** [comment]
yes, it says each nightly version under about duckie which differentiates each version, though does each file need to have a different name as well.

**Comment by SchizoDuckie** [comment]
Yes. by convention it does.

I really don't see the root cause for this issue or any argument for me to change it (even when I would it would be a hell of a lot of work breaking tons of stuff). 

It's quite a strange thing to ask from a developer.

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
@SchizoDuckie 
This is what I see every time I download from one of the nightlies:

![ghub](https://user-images.githubusercontent.com/15053742/28177906-4aa0fa7c-67b1-11e7-8593-0d706e4cfc2b.PNG)

Thanks

**Comment by SchizoDuckie** [comment]
@L-a-n-g-o-l-i-e-r-s I suggest you disable noscript (or try a different browser) then. I have no such problems in chrome, curl or otherwise
