### ISSUE TITLE
Something is wrong with require keywords

### ISSUE THREAD

**Issue by Js41637** [SchizoDuckie/DuckieTV#924]
Using **Zooqle**;
 * Searching for `Ghost in the shell x265` returns a load of relevant results
* Searching for `Ghost in the shell` with require keywords `x265` returns no results

**Comment by Js41637** [comment]
Ok I just realised, it only filters the results returned, I was under the impression that it adds your keywords to the query

**Comment by garfield69** [comment]
>Ok I just realised, it only filters the results returned, I was under the impression that it adds your keywords to the query      

Correct, the *require* and *ignore* are filters.     
The only thing that gets added to the query string before posting the search is the quality.     
It's always been like this, and is working as designed :-)
