### ISSUE TITLE
Packaging issue

### ISSUE THREAD

**Issue by Devil505** [SchizoDuckie/DuckieTV#927]
I'm trying to package duckie TV 1.1.5 for Solus but I have some difficulties.

I'm not familiar with nodejs stuff. Files are installed in /usr/lib/node_modules/DuckieTV-Standalone/ with nmp install. Then, how the user can launch the app ?

With 1.1.4 there were a .desktop file and an executable bin.

**Comment by SchizoDuckie** [comment]
Have a look at the https://github.com/DuckieTV/Duckietv-builder repo. DuckieTV itself doesn't
require any npm packages.

**Comment by Devil505** [comment]
Oh you made a separate repo, do you plan to publish a release of duckietv-builder ?

**Comment by garfield69** [comment]
>Oh you made a separate repo, do you plan to publish a release of duckietv-builder ?      

There are no plans to publish the duckietv-builder.     

I think there has been a miss-communication here.      

[DuckieTV 1.1.5](https://github.com/SchizoDuckie/DuckieTV/releases/tag/1.1.5) has not been officially published yet.     
When it does get published, the packages (including the linux.tar and ubuntu.deb) will be available in the usual multi platform bundles just like they are currently available for [DuckieTV 1.1.4](https://github.com/SchizoDuckie/DuckieTV/releases/tag/1.1.4)      
You just caught us in an in-between stage, with the DuckieTV 1.1.5 release tag created, but the packages not yet generated.      

However, if you are truly looking to create your own personal DuckieTV 1.1.5 bundle, then the [duckietv-builder](https://github.com/DuckieTV/duckietv-builder) is the npm tool that schizoduckie uses to generate the DuckieTV packages, as well as the [Nightly](https://github.com/DuckieTV/Nightlies/releases) canary releases.

**Comment by Devil505** [comment]
OK thanks for your help, i'll will build 1.1.4 then :+1:
