### ISSUE TITLE
Qbittorrent not connecting

### ISSUE THREAD

**Issue by teknikel** [SchizoDuckie/DuckieTV#930]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...1.14

**What is your Operating System (Windows, Mac, Linux, Android)**
...Windows

**Describe the problem you are having and steps to reproduce if available**
...Qbittorrent not connecting and when I click Test and Save, nothing happens. Also, can't seem to download 1.15. When I click the Windows link, the page scrolls down a little but nothing starts and there are no other buttons to click

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
DuckieTV 1.1.5 will be available as soon as SchizoDuckie builds and publishes the release packages.     
I do not have an ETA on this,  @SchizoDuckie  do you have an update?

qBitTorrent *3.3.13* introduced Cross-Site Request Forgery protection for their WEBUI API. However, they set the rules too tight, and ended up denying any WEBUI API user except their own internal one.     
Issue qbittorrent/qBittorrent#6882 was raised, and *3.3.14* loosened the rules enough to allow other clients access, but not without additional supporting changes to DuckieTV's own qBt 3.2+ client.     
Commit 7a2bbb9a4ec123f6928c805599e2f69fe352375f resolves the problem and will be included in 1.1.5.     

So at this point you have several choices:      
- Wait for [DuckieTV 1.1.5](https://github.com/SchizoDuckie/DuckieTV/releases) to be published.        
- Grab a [DuckieTV Nightly](https://github.com/DuckieTV/Nightlies/releases) so you can connect to qBt *3.3.14* now.      
    There is a wiki should you need it: [installing a Standalone DuckieTV Nightly](https://github.com/SchizoDuckie/DuckieTV/wiki/How-to-Install-a-Development-version-of-the-Windows-DuckieTV-Standalone-NIGHTLY).    
- Downgrade your [qBitTorrent to 3.3.12](https://sourceforge.net/projects/qbittorrent/files/qbittorrent-win32/qbittorrent-3.3.12/qbittorrent_3.3.12_x64_setup.exe/download) so you can connect with DuckieTV *1.1.4* .     


Closed as a duplicate of #903.
