### ISSUE TITLE
Unable to import Trakt 'collected' status to mark as 'downloaded'

### ISSUE THREAD

**Issue by austempest** [SchizoDuckie/DuckieTV#933]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone x64

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Nightly v201708080130

**What is your Operating System (Windows, Mac, Linux, Android)**
Win10

**Describe the problem you are having and steps to reproduce if available**
Unable to import Trakt 'collected' status to mark as 'downloaded. Essentially, after i've set up DuckyTV and successfully linked my Trakt account everything seems to work fine, apart from marking shows that i have previously downloaded and marked as 'collected' on Trakt, as 'downloaded' on DuckyTV, therefore making them green on the calendar.

Importing all my shows works fine, so does the 'watched' status.

I've tried 'import shows from trakt' button multiple times, with and without the 'only import shows from collection' ticked. I've tried uninstalling and reinstalling twice, and just tried on a completely different computer with the same result.

My calendar from last month shows most shows as undownloaded and unwatched, when they are just unwatched. Only shows that i have watched show as downloaded and watched (assuming they are marked as downloaded as it's linked with watched status, so that's working fine :) )

**Attach any DuckieTV statistics or Developer Console logs if available**
nil yet, but i can collect logs if requested.

**Comment by garfield69** [comment]
Thanks for reporting. We are aware of this bug, discovered during #877.      
I'm going to keep this one open and close 877 as a duplicate, since this is more on topic.

**Comment by garfield69** [comment]
for testing I performed a backup wipe, followed by a trakt import.    
- [x] tested importing from trakt collection only . checked that all episodes were marked as downloaded if collected, and as not-downloaded if newer than collection.     
- [x] tested importing from trakt collection and watched. check that all episodes were either marked as watched or marked as downloaded or left as new.

**Comment by austempest** [comment]
Is there anything I can do to assist testing?

**Comment by garfield69** [comment]
>Is there anything I can do to assist testing?

Thanks.     
My test data comprised my personal collection of about 254 series, 1121 seasons and 15397 episodes. I am satisfied with my test results.      

The fix will be available once https://github.com/DuckieTV/Nightlies/releases/tag/nightly-201708130130 is out in about 20 hours from now. And of course it will be included in the official 1.1.5 release, when ever that gets finally pushed out.

**Comment by austempest** [comment]
Just like to report back and say that it works great now.

Thanks for the swift response.
