### ISSUE TITLE
[Feature Request] Countdown List

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#934]
Hi
Can you please look at adding a countdown list as an option in the favourites section.

That shows the number of days until the next episode of each show, that is airing currently or, that has provided a date for the next upcoming episode, like EZTVs countdown list.

Thanks

P.S. 
Sorry if this is a duplicate but, I couldn’t find it anywhere.

**Comment by Js41637** [comment]
I feel this would be pretty heavy (perf wise) and add a lot of clutter. Personally I don't see the point of a countdown where there is a calendar that tells you when it is coming. Sure it is only for the month (or week) but i see no reason why you'd want to know that there is like 200 days until the next season of Westworld as it's just depressing

**Comment by zero77** [comment]
Yes I see your point, I was just thinking along the lines of a quicker and easier solution to have alongside the calendar.

That would help when episodes or series are munts apart, instead of flicking through the calendar, and something that provides more of an overview than the to do mode.

**Comment by 2635599** [comment]
i don't care about a countdown feature myself, but anyway to pole from someplace like?

http://www.returndates.com/

**Comment by garfield69** [comment]
@2635599 wrote:      

>i don't care about a countdown feature myself, but anyway to pole from someplace like?     
>http://www.returndates.com/    

Complicated.  We would need the TVDB_ID to be certain we had the correct show, and that info is found only after navigating each link to a secondary page.      
That would mean an additional 210 http requests just to scan the complete list.

**Comment by 2635599** [comment]
my suggestion is for zero77 just add the above site to his/her saved sites

**Comment by garfield69** [comment]
I agree. I'm declining this enhancement request.
