### ISSUE TITLE
OffCloud Integration

### ISSUE THREAD

**Issue by dedren** [SchizoDuckie/DuckieTV#936]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Chrome Extension

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
DuckieTV V1.1.4

**What is your Operating System (Windows, Mac, Linux, Android)**
Chrome

**Describe the problem you are having and steps to reproduce if available**
Any way to convince you to support Offcloud ([https://github.com/offcloud/offcloud-api](https://github.com/offcloud/offcloud-api))? It is the only way I have found that is the easiest (but still not easy enough) and automatic (using ShowRSS, IFTTT, Offcloud, and Google Drive) way to get my custom, clean list of shows from ShowRSS to my unlimited Google Drive _without having any of my own hardware_ in the mix. We then use PlexCloud to watch directly from Google Drive (with no slowdowns when 5 or more of us are watching!) It also means my IP address cannot be tracked down and caught up in some copyright trolls mass requests they send to ISPs. If it matters, their support has been one of the best, solving some previously game breaking problems with me (couldn't get IFTTT to properly read the RSS link from ShowRSS.

ShowRSS doesn't support 1080p and that is what I have been trying to find a better answer to.

If you need more info on Offcloud, they were in an article on Cloudwards.net ([https://www.cloudwards.net/best-cloud-torrent/](https://www.cloudwards.net/best-cloud-torrent/))

PLEEEEAASSEE 😄 
...

**Comment by garfield69** [comment]
Sorry, but no. Schizoduckie previously answered this in #876.     
DuckieTV will not be supporting / endorsing cloud-based services that require a paid account.

**Comment by dedren** [comment]
Is there a free way to do this (without buying a PC of course)? Also, you don't have to pay. I pay for support.

**Comment by garfield69** [comment]
I have no idea, I personally have not researched cloud services, as I don't use any.     
I just know that the author of DuckieTV has stated he will not support the idea.
