### ISSUE TITLE
[Feature request] MyAnimeList support (+others)

### ISSUE THREAD

**Issue by cajeiri** [SchizoDuckie/DuckieTV#939]
Hello,

One of the things DuckieTV has been lacking for some time is MyAnimeList support. This is the biggest website for tracking your anime tv series, movies, manga and so on. Their facebook page has a following of 250k+, which would be nice if they decide to share DuckieTV at any moment.
API Information: https://myanimelist.net/modules.php?go=api

The 2nd place contender is AniList.co, which offers the same stuff as MAL, in a different package. Their facebook page is 10 times smaller, but they still have a good reach.
API v1 Information: https://github.com/joshstar/AniList-API-Docs (to be deprecated)
API v2 Information: https://github.com/AniList/ApiV2-GraphQL-Docs (pre-release)

Having these two websites would allow anime fans like myself to fully use duckietv without having to install apps on our phones and so on.

**Comment by garfield69** [comment]
Sorry, but I am not interested in turning DuckieTV into a *Specialised* **Anime** tracking app.     
(If any of the other DuckieTV team-members disagree, speak up now).       
It's just far too much work for me to get involved in.      

DuckieTV's chosen TV data provider is *Trakt.TV*, and we will happily support any Anime features that Trakt.TV provides through their API, such as the recently introduced *Absolute* episode data that is now available (see #664).

**Comment by Js41637** [comment]
Not to mention supporting other data providers would be a massive undertaking. The whole app is designed to get data from a single source [trakt] and everything is based around the data it returns. To allow importing data from another source would cause a lot of problems and require a lot of internal changes. Not to mention there would be a lot of inconsistencies in the data.

I had a quick look at myanimelists api (which is horrible btw) and it would be terrible to work with. Seems to be XML only and requires an account. Also we'd have no way to properly detect updates for them meaning we've probably have to randomly decide to update all animelist shows at a set time.

**Comment by cajeiri** [comment]
@garfield69 @Js41637 If that's your point of view, I'll accept it.

I honestly **do not** want the ability to gather data from MyAnimeList, just the option to update my episodes there, as I will never ever use trakt.tv within this lifetime. It is not a good option for anime, and frankly it never will be. I honestly thought adding this functionality would be "medium" on the "how hard is this to add" scale in my head. Guess I was mistaken :( 

Not having the option to update my anime directly via DuckieTV isn't a deal-breaker for me. Thank you all for the amazing work and dedication you've put into DuckieTV so far :)

**Comment by Js41637** [comment]
Trakt seems to be taking steps to make Anime better. Hopefully in the future they can improve it.
