### ISSUE TITLE
Bug with Test and Save button

### ISSUE THREAD

**Issue by sardodeals** [SchizoDuckie/DuckieTV#940]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...DuckieTV Standalone v1.1.4

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...DuckieTV Standalone v1.1.4

**What is your Operating System (Windows, Mac, Linux, Android)**
...Windows

**Describe the problem you are having and steps to reproduce if available**
...qBittorrent v3.2+ Integration
 unchecking Use Authentication
Click on the Test and Save button
**does not save setting**
Status: Not connected
Using qb v3.3.15
web UI enabled
bypass authentication for localhost is checked
also tried with username and password, same result
also tried with Deluge, same result
tried reinstalling DuckieTV, no change
tried wipe database and settings, no change
each time I check the settings it shows "admin" and a password, but when I set a username this is not it, I am using a different username, these settings are not being saved.

Please assist,
Thanks

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
**qBitTorrent 3.3.13** and **Deluge 1.3.14** introduced *Cross-Site Request Forgery* protection for their WEBUI API. This broke their respective DuckieTV **1.1.4** client interfaces.     

So at this point you have several choices:       
- Wait for [DuckieTV 1.1.5](https://github.com/SchizoDuckie/DuckieTV/releases) to be published which will connect to the latest versions of qBt and Deluge. I don't have a release date for you so this could be a while yet.       
- Grab a [DuckieTV Nightly](https://github.com/DuckieTV/Nightlies/releases/latest) so you can connect to the latest qBt and Deluge now.      
    There is a wiki should you need it: [installing a Standalone DuckieTV Nightly](https://github.com/SchizoDuckie/DuckieTV/wiki/How-to-Install-a-Development-version-of-the-Windows-DuckieTV-Standalone-NIGHTLY).    
- Downgrade your qBitTorrent to 3.3.12 or your Deluge to 1.3.13 so you can connect with DuckieTV *1.1.4* .    


Closed as a duplicate of #903 and #880.

**Comment by sardodeals** [comment]
Thanks, changed to v3.3.12 and it is working great.
Response is much appreciated.
