### ISSUE TITLE
Shows in thetvdb.com not showing up in duckie

### ISSUE THREAD

**Issue by Cowboy1968** [SchizoDuckie/DuckieTV#943]
Hello,
I am not sure why, but for the first time in a year or so of using your amazing program, there are two TV series that do not show up when trying to add them.  One is Haunted Towns (**http://thetvdb.com/?tab=series&id=331882&lid=7**) and the other is Home Town (**http://thetvdb.com/?tab=series&id=325186&lid=7**).  I have double checked the spelling as well as copy and pasted it directly from the TVDB website to be sure with no luck and I cannot figure out why they wont show up. 

I have pasted my Statistics below for your reference.  Please keep up the amazing work it is appreciated.
Tim
[
  {
    "name": "DuckieTV Web Based",
    "data": "201706200130"
  },
  {
    "name": "Current Date and Time",
    "data": "Thu, 24 Aug 2017 05:21:23 GMT"
  },
  {
    "name": "NWJS, Chromium",
    "data": "0.22.3 , 58.0.3029.110"
  },
  {
    "name": "UserAgent",
    "data": "DuckieTV-Standalone  Nightly v201706200130 Macintosh; Intel Mac OS X 10_12_6"
  },
  {
    "name": "Platform, Vendor",
    "data": "MacIntel, Google Inc."
  },
  {
    "name": "Screen (width x height)",
    "data": "1360 x 768"
  },
  {
    "name": "Default Search Engine",
    "data": "ThePirateBay (Enabled)"
  },
  {
    "name": "Default Torrent Client",
    "data": "Transmission (Enabled and Connected to Host)"
  },
  {
    "name": "Auto Download Service",
    "data": "(Disabled)"
  },
  {
    "name": "Last checked TraktTV for DB updates on",
    "data": "Thu, 24 Aug 2017 01:24:37 GMT"
  },
  {
    "name": "User Preferences on Local Storage",
    "data": "{\n  \"KickAssTorrents.mirror\": \"https://kat.cr\",\n  \"ThePirateBay.mirror\": \"https://thepiratebay.SE\",\n  \"application.language\": \"en_ca\",\n  \"application.locale\": \"en_ca\",\n  \"autodownload.minSeeders\": 50,\n  \"autodownload.period\": 1,\n  \"background-rotator.opacity\": \"0.25\",\n  \"calendar.mode\": \"date\",\n  \"calendar.show-specials\": true,\n  \"calendar.show-downloaded\": true,\n  \"calendar.startSunday\": true,\n  \"client.determinedlocale\": \"en_us\",\n  \"download.ratings\": false,\n  \"lastSync\": -1,\n  \"library.smallposters\": false,\n  \"qbittorrent.server\": \"http://localhost\",\n  \"qbittorrent.port\": 8080,\n  \"qbittorrent.use_auth\": true,\n  \"qbittorrent.username\": \"admin\",\n  \"qbittorrent.password\": \"*****\",\n  \"qbittorrent32plus.server\": \"http://localhost\",\n  \"qbittorrent32plus.port\": 8080,\n  \"qbittorrent32plus.use_auth\": true,\n  \"qbittorrent32plus.username\": \"admin\",\n  \"qbittorrent32plus.password\": \"*****\",\n  \"series.displaymode\": \"poster\",\n  \"standalone.startupMinimized\": false,\n  \"standalone.zoomlevel\": 6,\n  \"storage.sync\": false,\n  \"sync.progress\": true,\n  \"tixati.server\": \"http://localhost\",\n  \"tixati.use_auth\": true,\n  \"tixati.port\": 8888,\n  \"tixati.username\": \"admin\",\n  \"tixati.password\": \"*****\",\n  \"topSites.enabled\": false,\n  \"topSites.mode\": \"onclick\",\n  \"torrenting.autodownload\": false,\n  \"torrenting.autostop\": true,\n  \"torrenting.autostop_all\": false,\n  \"torrenting.client\": \"Transmission\",\n  \"torrenting.directory\": true,\n  \"torrenting.enabled\": true,\n  \"torrenting.progress\": true,\n  \"torrenting.searchprovider\": \"ThePirateBay\",\n  \"torrenting.searchquality\": \"\",\n  \"torrenting.streaming\": true,\n  \"vuze.server\": \"http://localhost\",\n  \"vuze.port\": 9091,\n  \"vuze.use_auth\": true,\n  \"vuze.username\": \"vuze\",\n  \"vuze.password\": \"*****\",\n  \"transmission.server\": \"http://localhost\",\n  \"transmission.port\": 9091,\n  \"transmission.use_auth\": true,\n  \"transmission.username\": \"admin\",\n  \"transmission.password\": \"*****\",\n  \"trakttv.passwordHash\": \"*****\",\n  \"trakttv.sync\": false,\n  \"trakttv.username\": null,\n  \"utorrentwebui.server\": \"http://localhost\",\n  \"utorrentwebui.port\": 8080,\n  \"utorrentwebui.username\": \"admin\",\n  \"utorrentwebui.password\": \"*****\",\n  \"utorrentwebui.use_auth\": true,\n  \"deluge.server\": \"http://localhost\",\n  \"deluge.port\": 8112,\n  \"deluge.password\": \"*****\",\n  \"deluge.use_auth\": true,\n  \"subtitles.languages\": [\n    \"eng\"\n  ],\n  \"autodownload.lastrun\": 1496551418755,\n  \"calendar.show-episode-numbers\": true,\n  \"transmission.path\": \"/transmission/rpc\",\n  \"vuze.path\": \"/transmission/rpc\",\n  \"torrenting.min_seeders\": 1,\n  \"main.viewmode\": \"calendar\",\n  \"series.not-watched-eps-btn\": true,\n  \"library.seriesgrid\": true,\n  \"notifications.enabled\": false,\n  \"autodownload.multiSE\": {\n    \"ThePirateBay\": true,\n    \"1337x\": true,\n    \"IsoHunt\": true,\n    \"KATcr\": true,\n    \"Nyaa\": true,\n    \"RarBG\": true,\n    \"ShowRSS\": true,\n    \"TorrentDownloads\": true,\n    \"TorrentZ2\": true,\n    \"Zooqle\": true,\n    \"EzTV.ag\": true,\n    \"Idope\": true,\n    \"LimeTorrents\": true,\n    \"SkyTorrents\": true\n  },\n  \"torrentDialog.2.enabled\": true,\n  \"torrentDialog.2.activeSE\": {\n    \"ThePirateBay\": true,\n    \"1337x\": true,\n    \"IsoHunt\": true,\n    \"KATcr\": true,\n    \"Nyaa\": true,\n    \"RarBG\": true,\n    \"ShowRSS\": true,\n    \"TorrentDownloads\": true,\n    \"TorrentZ2\": true,\n    \"Zooqle\": true,\n    \"EzTV.ag\": true,\n    \"Idope\": true,\n    \"LimeTorrents\": true,\n    \"SkyTorrents\": true\n  }\n}"
  },
  {
    "name": "Other significant Local Storage keys",
    "data": "{\n  \"1.1.4TorrentHashListCleanup\": \"Mon Jun 19 2017 20:42:21 GMT-0700 (PDT)\",\n  \"1.1.4cleanupOrphanedEpisodes\": \"Mon Jun 19 2017 20:39:44 GMT-0700 (PDT)\",\n  \"1.1.4cleanupOrphanedSeasons\": \"Mon Jun 19 2017 20:39:45 GMT-0700 (PDT)\",\n  \"1.1.4qBittorrentPre32\": \"Mon Jun 19 2017 20:39:40 GMT-0700 (PDT)\",\n  \"1.1.4refresh\": \"Mon Jun 19 2017 20:39:50 GMT-0700 (PDT)\",\n  \"1.1.4refreshTrendingCache\": \"Mon Jun 19 2017 20:39:40 GMT-0700 (PDT)\",\n  \"1.1.4updateTransmissionPath\": \"Mon Jun 19 2017 20:39:40 GMT-0700 (PDT)\",\n  \"1.1.5deleteSearchEngines\": \"Mon Jun 19 2017 20:39:40 GMT-0700 (PDT)\",\n  \"1.1.5fanartCleanup\": \"Mon Jun 19 2017 20:42:21 GMT-0700 (PDT)\",\n  \"1.1.5updateDelugeAuth\": \"Mon Jun 19 2017 20:39:40 GMT-0700 (PDT)\",\n  \"1.1.5updateTorrenting.min_seeders\": \"Mon Jun 19 2017 20:39:40 GMT-0700 (PDT)\",\n  \"1.1migration\": \"Fri Aug 07 2015 22:10:11 GMT-0700 (PDT)\",\n  \"autobackup.lastrun\": \"1500531596385\",\n  \"database.version.Episodes\": \"13\",\n  \"database.version.Fanart\": \"1\",\n  \"database.version.Jackett\": \"2\",\n  \"database.version.SearchEngines\": \"1\",\n  \"database.version.Seasons\": \"6\",\n  \"database.version.Series\": \"15\",\n  \"database.version.WatchList\": \"1\",\n  \"database.version.WatchListObject\": \"1\",\n  \"fanart.bootstrapped\": \"1\",\n  \"github.lastupdatecheck\": \"1451606767589\",\n  \"install.notify\": \"201706200130\",\n  \"runtime.event\": \"{\\\"reason\\\":\\\"install\\\"}\",\n  \"snr.lastFetched\": \"1503537871312\",\n  \"standalone.alwaysShowTray\": \"Y\",\n  \"standalone.closeSystray\": \"Y\",\n  \"standalone.minimizeSystray\": \"Y\",\n  \"standalone.position\": \"{\\\"width\\\":1000,\\\"height\\\":741,\\\"x\\\":167,\\\"y\\\":23,\\\"state\\\":\\\"normal\\\"}\",\n  \"standalone.startupMinimized\": \"N\",\n  \"standalone.trayColor\": \"-indigo\",\n  \"standalone.zoomlevel\": \"6\",\n  \"torrenting.client\": \"Transmission\",\n  \"trackers.fallBackList\": \"&tr=udp://tracker.pirateparty.gr:6969/announce&tr=udp://tracker.coppersurfer.tk:6969/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://allesanddro.de:1337/announce&tr=udp://9.rarbg.com:2710/announce&tr=udp://p4p.arenabg.com:1337/announce&tr=http://asnet.pw:2710/announce&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://public.popcorn-tracker.org:6969/announce&tr=http://tracker.opentrackr.org:1337/announce&tr=udp://tracker.internetwarriors.net:1337/announce&tr=udp://tracker1.xku.tv:6969/announce&tr=udp://tracker1.wasabii.com.tw:6969/announce&tr=udp://tracker.zer0day.to:1337/announce&tr=udp://peerfect.org:6969/announce&tr=http://ipv4.tracker.harry.lu:80/announce&tr=http://91.218.230.81:6969/announce&tr=udp://tracker.mg64.net:6969/announce&tr=udp://open.facedatabg.net:6969/announce&tr=udp://mgtracker.org:6969/announce\",\n  \"trackers.lastFetched\": \"1503126002511\",\n  \"trakttv.lastupdated\": \"1503537877709\",\n  \"trakttv.lastupdated.trending\": \"1503126016590\",\n  \"upgrade.notify\": \"1.1.3\",\n  \"xem.lastFetched\": \"1503537871292\"\n}"
  },
  {
    "name": "DB Series",
    "data": 91
  },
  {
    "name": "DB Series Hidden From Calendar",
    "data": 0
  },
  {
    "name": "DB Seasons",
    "data": 414
  },
  {
    "name": "DB Episodes",
    "data": 6019
  },
  {
    "name": "DB Fanart",
    "data": 2263
  },
  {
    "name": "DB Jackett",
    "data": 0
  }
]

**Comment by garfield69** [comment]
When you are on the trending page, and type a title in the search box, we send that request to Trakt.TV. `search/show?extended=full&limit=50&query=<your search text>`      
However, Trakt.TV does a search of all text fields that a media object contains (i.e. title, overview, people, tagline, alias, etc). Results are then ordered by the most relevant score. And with the limit of 50, sometimes this does not return what we expect.     
       
However, you can help Trakt.TV search better by adding double quotes.        
*Haunted Towns*
![image](https://user-images.githubusercontent.com/6933240/29653603-a778aac4-88fe-11e7-91a9-5b48afdefa86.png)

*Home Town*
![image](https://user-images.githubusercontent.com/6933240/29653666-cc442fcc-88fe-11e7-8434-26db8168f5a5.png)

**Comment by garfield69** [comment]
# addendum:
on reviewing the Trakt.TV API, I see now that we have the option to restrict the search to just titles.     
so I've implemented this, which will get included in the next release of DuckieTV, and of course the next Nightly, which is due out in about 17 hours from now.

**Comment by Cowboy1968** [comment]
Hi,

Awesome man thank you so much!  I will try the quotations tonight when I
get home.

Thank you for all your time and effort it is very much appreciated!

Tim
