### ISSUE TITLE
[Feature Request] Auto FTP Backup

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#944]
Can you please introduce an automatic FTP backup option instead of, or as well as saving it to disk.
Thanks

**Comment by garfield69** [comment]
> introduce an automatic FTP backup option    

Chrome JavaScript Extensions (as far as I can tell) do not have access to any native FTP API or permissions.

https://developer.chrome.com/extensions/api_index
https://developer.chrome.com/extensions/declare_permissions

so providing FTP support within DuckieTV would require using an external product... which is unlikely to be free, or compatible with AngularJS.

**Comment by zero77** [comment]
Ok, thanks anyway.
