### ISSUE TITLE
Autodownload not working

### ISSUE THREAD

**Issue by gillsy** [SchizoDuckie/DuckieTV#946]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...
Standalone Mac - latest version as per the check for update
**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...
 latest version as per the check for update
**What is your Operating System (Windows, Mac, Linux, Android)**
...
Mac OS X Sierra
**Describe the problem you are having and steps to reproduce if available**
...
The app use to download with no issues, now it's not.  If I click the "autodown" button it doesnt' do anything, if i use the "find torrent" it does.
**Attach any DuckieTV statistics or Developer Console logs if available**
...
How do I get these?

I'm also using uTorrent,

**Comment by garfield69** [comment]
Just so I can confirm which version you are on, and get an overview of your settings, can you visit the *About* panel, scroll down to the *Statistics* section, and click on that header to copy the data to your clipboard. *Paste* into the box below.      
![image](https://user-images.githubusercontent.com/6933240/29759652-a3c3d85c-8c11-11e7-8cfb-5fff4e646ca0.png)

Are you using the *Auto-Download Service*?
![image](https://user-images.githubusercontent.com/6933240/29759764-8118a0d4-8c12-11e7-960f-8d9a0797e21d.png)

 or are you talking about manually starting auto-downloads for episodes?    
![image](https://user-images.githubusercontent.com/6933240/29759795-bf316fcc-8c12-11e7-837e-f6e40a21dfce.png)

**Comment by gillsy** [comment]
Thanks, I'll get thet stats page for you tonight.  

As for the other comments,

1) Using auto download as per the "AutoDownload Torrents" 
2) I use the second option when the first one doesn't work, but that's not working anymroe either.

This use to work without an issue, then started to become a problem, closing the app and reopening it usually fixed it but doesn't seem to be working anymore either.

I would love to be able to do a schedule reboot of my Mac but DuckieTV stops any command to restart,

**Comment by garfield69** [comment]
There is *no code* within *DuckieTV* that prevents restarts.... But I do not have a Mac so I don't if the Mac OS itself prevents scheduled restarts if there are apps running? It is possible, I suppose.     
However, you should be able to shutdown DuckieTV and then do your Mac restart!      

Also, a screenshot of the DuckieTV *Auto-Download Monitor* will be useful. This may tell you the reason why an episode torrent was not found or failed to submit to uTorrent.     
![image](https://user-images.githubusercontent.com/6933240/29760232-e0b6ee26-8c15-11e7-9109-ad7a80c3d238.png)

**Comment by gillsy** [comment]
Here are the settings, 
Focusing on The Last Ship,

Aired Today,
Auto DL enabled global and show
Stats and DL Service Monitor.

Remember I'm in Aus, so it's already Monday.

![screenshot 2017-08-28 19 54 28](https://user-images.githubusercontent.com/11995367/29768735-c8fc9302-8c2a-11e7-9fee-726cb2c98734.png)
![screenshot 2017-08-28 19 53 48](https://user-images.githubusercontent.com/11995367/29768737-c8ff22e8-8c2a-11e7-8106-0fdaeadf66ff.png)
![screenshot 2017-08-28 19 52 06](https://user-images.githubusercontent.com/11995367/29768734-c8fbbefa-8c2a-11e7-9676-b317659d702c.png)
![screenshot 2017-08-28 19 51 55](https://user-images.githubusercontent.com/11995367/29768736-c8ff3314-8c2a-11e7-8056-fae60cd54f38.png)
![screenshot 2017-08-28 19 51 42](https://user-images.githubusercontent.com/11995367/29768738-c9102110-8c2a-11e7-8184-6bdbc86b82e7.png)

**Comment by garfield69** [comment]
OK. So in you example, *The Last Ship* does not show up in the *Auto-download Monitor* as having been processed by the *Auto-Download Service*. It appears to have been skipped.      

So I did some testing and the issue is that TPB Search Engine you are using `tpbpirate.site` is having a lot of trouble with network issues. I am seeing a lot of 522 CONNECTION TIMED OUT errors.      
Even the official TPB url `thepiratebay.org` is giving me trouble with 337 ERR_SPDY_PROTOCOL_ERROR.     
These types of errors are causing DuckieTV grief.       

So for now, you would be better off using one of the other Search Engines, such as Zooqle for instance.      

Another potential issue to keep in mind if you are in AUS, is the possibility of ISPs blocking access, see https://torrentfreak.com/court-orders-aussie-isps-to-block-dozens-of-pirate-sites-170818/ for details.     
If the network issues don't clear up for you, you may want to trial a VPN to see if this helps.

**Comment by gillsy** [comment]
I'll give the VPN a go, but if it was blocked wouldn't it not show any results.

And yes it doesn't appear in the AutoDL log, that's the issue i'm having.

![screenshot 2017-08-29 10 14 31](https://user-images.githubusercontent.com/11995367/29798858-0aea991c-8ca3-11e7-8fd3-bf2d2578b9ed.png)

**Comment by garfield69** [comment]
In which case, set your default search engine to something other than TPB, or look for a TPB proxy that works better. check out  `http://www.piratebayproxylist.co/`.

**Comment by gillsy** [comment]
I changed it Zoogle and added NordVPN and still not working.  

Any other suggestions.

**Comment by garfield69** [comment]
You could try using any of the other Search engines, like RARBG,  etc. See if any of them work for you.     

Also,          
You could upgrade to the latest Nightly from https://github.com/DuckieTV/Nightlies/releases .     
This way you can open the *Development Tools* page by using the **F12** key, and then by clicking on the *Console* tab you can view the log and look for any errors that might explain what is going on at your location.      

Also, the latest Nightly has the option to connect to the Jackett proxy, which will expand your Search Engine choices exponentially. see this wiki https://github.com/SchizoDuckie/DuckieTV/wiki/Using-Jackett-with-DuckieTV for more details.

**Comment by gillsy** [comment]
Not sure I did the right thing, I installed the nightly the F12 isn't working but I restarted DuckieTV and the auto downloads are working again.

But lets see if it continues, maybe the change of Torrent Search engine.

**Comment by garfield69** [comment]
Apologies, *F12* is for windows and linux.      
*Cmd-Alt-I* on the Mac OSX  !!

**Comment by garfield69** [comment]
Also, don't forget, once the Auto-Download service is started, it is launched only every 15 minutes.    
So if you are changing the *default Service Engine*, then it could be up to 15 minutes before you see the results show up on the Auto-Download Monitor and the ADS is scheduled to run again.      
You can speed this up by either disabling and enabling the Auto-Download service at the *Settings, Auto-Download* sidepanel, or by recycling DuckieTV.

**Comment by garfield69** [comment]
this article https://torrentfreak.com/game-thrones-traffic-surge-slowed-pirate-bay-170830/ may
explain your recent problems at TPB

**Comment by gillsy** [comment]
Thanks but this has been going on for months, I just haven’t had time to post it. 

I’m seeing how the next few auto download shows go.  As I pay 📺 now a lot of them I watch live so will need to wait until next week.
