### ISSUE TITLE
Deluge integration fail. No error output on standalone

### ISSUE THREAD

**Issue by BeachyHeadCode** [SchizoDuckie/DuckieTV#947]
DuckieTV Standlone Stable 1.1.4, Windows

Torrent client Deluge will not connect on deluge integration. I followed the steps to the T. I have checked the login password for the address and port directly on my browser. I tired to connect to it on the chrome tab version of duckietv as well.

deps.js:2229 {data: "", status: 500, config: {…}, statusText: "Internal Server Error", headers: ƒ}
app.js:539 POST http://localhost:8112/json 500 (Internal Server Error)
deps.js:2229 Deluge Connect call failed. No client listening.

http://localhost:8112 opens the deluge web ui fine in the browser.

**Comment by garfield69** [comment]
Deluge 1.3.14 introduced Cross-Site Request Forgery (CSRF) protection. This broke the DuckieTV 1.1.4 Deluge client interface.
You have several choises:
a. revert back to Deluge 1.3.13
b. wait for DuckieTV 1.1.5 which can connect to all versions of Deluge. I don't have an ETA of the release date, so this could be a while yet.
c. Install a Nightly version of DuckieTV. This is essentially DuckieTV 1.1.5 Canary. You can find the latest Nightly at https://github.com/DuckieTV/Nightlies/releases       

duplicate of #880
