### ISSUE TITLE
DuckieTV 1.1.5 publishing check list

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#948]
@Schizoduckie I think that 1.1.5 is ready to be published.    

### Schizoduckie's check list:
- [x] update pre-release title at https://github.com/SchizoDuckie/DuckieTV/releases/tag/1.1.5    
- [x] and remove the pre-release tag check box    
- [x] publish 1.1.5 for all platforms    
- [x] make announcement on Reddit https://www.reddit.com/r/duckietv/    
- [x] make announcement on Facebook https://www.facebook.com/DuckieTV/    

### Garfield69's post publishing check list:
- [x] update changelog in https://github.com/SchizoDuckie/DuckieTV/blob/angular/README.md    
- [x] update changelog in https://github.com/SchizoDuckie/DuckieTV/blob/gh-pages/_posts/2015-01-12-changelog.md    
- [x] bump version to 1.1.6    
    - [x] https://github.com/SchizoDuckie/DuckieTV/blob/angular/VERSION    
    - [x] https://github.com/SchizoDuckie/DuckieTV/blob/angular/package.json    
    - [x] https://github.com/SchizoDuckie/DuckieTV/blob/angular/manifest.json    
    - [x] https://github.com/SchizoDuckie/DuckieTV/blob/angular/manifest-app.json

**Comment by Gonenb** [comment]
looks like Schizoduckie is gone for some time now, maybe someone else can do this?

**Comment by garfield69** [comment]
Schizoduckie is the only one with the chrome web store and phonegap keys to publish the stable releases.

**Comment by SchizoDuckie** [comment]
Sorry people, i've been without broadband for a couple months while switching providers. New build is packaging right now
