### ISSUE TITLE
[Feature Request] Auto Organizer

### ISSUE THREAD

**Issue by mindtricksdev** [SchizoDuckie/DuckieTV#949]
Hello,

When a torrent finishes the download I would like it to be moved in the correct series folder for it to be nicely detected by Plex. 
Basically, the download path should be [DownladRoot]/Series/[SerieName]/[SeasonNumber]/.

Can such dynamic paths be supported? What do you think?

Thanks!

**Comment by garfield69** [comment]
this [wiki](https://github.com/SchizoDuckie/DuckieTV/wiki/FAQ#why-cant-duckietv-automatically-put-shows-in-correct-folders-once-downloaded) should answer your question.     
But if you need additional info don't hesitate to ask ;-)
