### ISSUE TITLE
Future Enhancement: Series notes

### ISSUE THREAD

**Issue by cajeiri** [SchizoDuckie/DuckieTV#951]
Small idea that will probably end up being harder than I think it is.

Is it possible to add notes to tv series, that may be viewable in the right panel menu when you click on an episode and/or in the calendar.

Example for calendar: American Dad! S01E01 (Torrents late by 60 minutes)

I generally would like this feature because some tv series I watch from the UK and Australia tend to air at time X and the torrents tend to be up at time X+3h.

**Comment by garfield69** [comment]
If you use the auto-download service to fetch episodes, then are you aware that you can set a delay for each series before the ADS goes looking? read this [wiki](https://github.com/SchizoDuckie/DuckieTV/wiki/Auto-Download-FAQs#auto-download-delay) for details.

**Comment by cajeiri** [comment]
@garfield69 - Yes, but I don't use the auto-download service, since I'm sharing the internet with other people and I can't download when they're playing games. The notes would have the secondary usefulness of giving me the option to add comments to my calendar, which I often share with other people.

**Comment by Js41637** [comment]
Realistically this is very easy to add. Realistically as well i'm not sure why your wouldn't, in general, wait a few hours after shows air before trying to download. I wait about 7 hours before i even try to find downloads to stuff let alone 60 minutes after their date (which is just over the average length of normal tv shows (sorry cartoons))

**Comment by cajeiri** [comment]
@Js41637 I just need reminders about the average time. Memory's not what it used to be. Some shows I don't try downloading unless a day has passed, others I know the average give or take. Hectic lives lead to a hectic memory I guess :)

**Comment by garfield69** [comment]
Adding notes to the calendar was raised once before in #753 and was declined.      
Schizoduckie wrote:      

>Hmmm. I can see the appeal, but you really should do notes in google calendar or the likes.      

>Turning the calendar view into an actual reminder calendar will create a whole lot of noise that has nothing to do with tv show tracking imo.

**Comment by cajeiri** [comment]
@garfield69 #753 discussed standalone notes, while #951 discusses notes attached to specific series. I do my notes in Google Keep and nowhere else. But why would I keep a note that says "Don't watch this without GF!!!" in Google Keep, instead of where it should be - attached to the name of the TV series, where I will see it clearly as a constant reminder.

I'm sorry, but I'd like this idea to be revisited if possible or at least with more coherent reasons pertaining to my version.

**Comment by garfield69** [comment]
@SchizoDuckie  please review this ticket and provide feedback. Thanks.

**Comment by SchizoDuckie** [comment]
Well, it's making sense for this use case, but how far do you want to take it? will it be on the series or on each episode as well? showing a "this show has notes" icon for each episode of a series on the calendar and then only being able to edit the notes textbox on the series side panel may be a bit odd from a UX perspective , but will be simple to implement. As long as we don't get into reminders and repeating event planning and all that i'm okay with doing this.

**Comment by cajeiri** [comment]
Personally, I think a per series note makes a lot more sense. Thank you both for reconsidering this :)

**Comment by cajeiri** [comment]
Closing this as it has been over a year and a half.
