### ISSUE TITLE
[Question] DuckieTV Synchronisation

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#952]
What is the best way to automatically synchronise settings and tv shows and their activity across multiple platforms, for example Android and Linux or Windows.

**Comment by garfield69** [comment]
As things stand currently, there is no automatic sync across multiple platforms.     
Looking forward, once the Trakt.tv sync feature is fully implemented (currently only dtv-push-to-trakt is automated), then this will probably be the way to go.

**Comment by zero77** [comment]
ok, thanks
