### ISSUE TITLE
Clicking find a torrent doesn't do anything.

### ISSUE THREAD

**Issue by jakeferris13** [SchizoDuckie/DuckieTV#955]
When clicking find a torrent or auto download it doesn't bring up the overlay with the torrents to choose from, I have tried uninstalling and reinstalling but it's still the same. Is there something I can do to troubleshoot this?

**Describe the problem you are having and steps to reproduce if available**
...

**Attach any DuckieTV statistics or Developer Console logs if available**
[
  {
    "name": "DuckieTV Web Based",
    "data": "1.1.5"
  },
  {
    "name": "Current Date and Time",
    "data": "Fri, 22 Sep 2017 14:58:46 GMT"
  },
  {
    "name": "NWJS, Chromium",
    "data": "0.25.0 , 61.0.3163.79"
  },
  {
    "name": "UserAgent",
    "data": "DuckieTV-Standalone  v1.1.5 Windows NT 10.0; Win64; x64"
  },
  {
    "name": "Platform, Vendor",
    "data": "Win32, Google Inc."
  },
  {
    "name": "Screen (width x height)",
    "data": "1920 x 1080"
  },
  {
    "name": "Default Search Engine",
    "data": "ThePirateBay (Enabled)"
  },
  {
    "name": "Default Torrent Client",
    "data": "qBittorrent 3.2+ (Enabled and Connected to Host)"
  },
  {
    "name": "Auto Download Service",
    "data": "(Disabled)"
  },
  {
    "name": "Last checked TraktTV for DB updates on",
    "data": "Fri, 22 Sep 2017 05:59:54 GMT"
  },
  {
    "name": "User Preferences on Local Storage",
    "data": "{\n  \"ThePirateBay.mirror\": \"https://pirateproxy.cam/\",\n  \"application.language\": \"en_us\",\n  \"application.locale\": \"en_us\",\n  \"autobackup.period\": \"monthly\",\n  \"autodownload.delay\": 15,\n  \"autodownload.minSeeders\": 50,\n  \"autodownload.multiSE\": {\n    \"ThePirateBay\": true,\n    \"1337x\": true,\n    \"IsoHunt\": true,\n    \"KATcr\": true,\n    \"Nyaa\": true,\n    \"RarBG\": true,\n    \"ShowRSS\": true,\n    \"TorrentDownloads\": true,\n    \"TorrentZ2\": true,\n    \"Zooqle\": true,\n    \"EzTV.ag\": true,\n    \"Idope\": true,\n    \"LimeTorrents\": true,\n    \"SkyTorrents\": true\n  },\n  \"autodownload.multiSE.enabled\": false,\n  \"autodownload.period\": 1,\n  \"background-rotator.opacity\": \"0.4\",\n  \"calendar.mode\": \"date\",\n  \"calendar.show-downloaded\": true,\n  \"calendar.show-episode-numbers\": false,\n  \"calendar.show-specials\": true,\n  \"calendar.startSunday\": true,\n  \"client.determinedlocale\": \"en_us\",\n  \"deluge.password\": \"*****\",\n  \"deluge.port\": 8112,\n  \"deluge.server\": \"http://localhost\",\n  \"deluge.use_auth\": true,\n  \"download.ratings\": true,\n  \"episode.watched-downloaded.pairing\": true,\n  \"kc.always\": false,\n  \"ktorrent.password\": \"*****\",\n  \"ktorrent.port\": 8080,\n  \"ktorrent.server\": \"http://localhost\",\n  \"ktorrent.use_auth\": true,\n  \"ktorrent.username\": \"ktorrent\",\n  \"lastSync\": -1,\n  \"library.seriesgrid\": true,\n  \"library.smallposters\": false,\n  \"main.viewmode\": \"calendar\",\n  \"qbittorrent.password\": \"*****\",\n  \"qbittorrent.port\": 8080,\n  \"qbittorrent.server\": \"http://localhost\",\n  \"qbittorrent.use_auth\": true,\n  \"qbittorrent.username\": \"admin\",\n  \"qbittorrent32plus.password\": \"*****\",\n  \"qbittorrent32plus.port\": 8080,\n  \"qbittorrent32plus.server\": \"http://localhost\",\n  \"qbittorrent32plus.use_auth\": true,\n  \"qbittorrent32plus.username\": \"jake\",\n  \"rtorrent.path\": \"/RPC2\",\n  \"rtorrent.port\": 80,\n  \"rtorrent.server\": \"http://localhost\",\n  \"rtorrent.use_auth\": false,\n  \"series.displaymode\": \"poster\",\n  \"series.not-watched-eps-btn\": false,\n  \"storage.sync\": false,\n  \"subtitles.languages\": [\n    \"eng\"\n  ],\n  \"sync.progress\": true,\n  \"tixati.password\": \"*****\",\n  \"tixati.port\": 8888,\n  \"tixati.server\": \"http://localhost\",\n  \"tixati.use_auth\": true,\n  \"tixati.username\": \"admin\",\n  \"topSites.enabled\": false,\n  \"topSites.mode\": \"onhover\",\n  \"torrentDialog.2.activeSE\": {\n    \"ThePirateBay\": true,\n    \"1337x\": true,\n    \"IsoHunt\": true,\n    \"KATcr\": true,\n    \"Nyaa\": true,\n    \"RarBG\": true,\n    \"ShowRSS\": true,\n    \"TorrentDownloads\": true,\n    \"TorrentZ2\": true,\n    \"Zooqle\": true\n  },\n  \"torrentDialog.2.enabled\": false,\n  \"torrentDialog.showAdvanced.enabled\": true,\n  \"torrentDialog.sortMenu.enabled\": true,\n  \"torrenting.autodownload\": false,\n  \"torrenting.autostop\": true,\n  \"torrenting.autostop_all\": true,\n  \"torrenting.client\": \"qBittorrent 3.2+\",\n  \"torrenting.directory\": true,\n  \"torrenting.enabled\": true,\n  \"torrenting.ignore_keywords\": \"\",\n  \"torrenting.ignore_keywords_enabled\": true,\n  \"torrenting.require_keywords\": \"\",\n  \"torrenting.require_keywords_mode_or\": true,\n  \"torrenting.require_keywords_enabled\": true,\n  \"torrenting.global_size_max\": null,\n  \"torrenting.global_size_max_enabled\": true,\n  \"torrenting.global_size_min\": null,\n  \"torrenting.global_size_min_enabled\": true,\n  \"torrenting.label\": false,\n  \"torrenting.launch_via_chromium\": false,\n  \"torrenting.progress\": true,\n  \"torrenting.searchprovider\": \"ThePirateBay\",\n  \"torrenting.searchquality\": \"\",\n  \"torrenting.searchqualitylist\": [\n    \"480p\",\n    \"HDTV\",\n    \"720p\",\n    \"1080p\",\n    \"2160p\"\n  ],\n  \"torrenting.streaming\": true,\n  \"trakt-update.period\": 12,\n  \"trakttv.passwordHash\": \"*****\",\n  \"trakttv.sync\": false,\n  \"trakttv.username\": null,\n  \"transmission.password\": \"*****\",\n  \"transmission.path\": \"/transmission/rpc\",\n  \"transmission.port\": 9091,\n  \"transmission.server\": \"http://localhost\",\n  \"transmission.use_auth\": true,\n  \"transmission.username\": \"admin\",\n  \"utorrentwebui.password\": \"*****\",\n  \"utorrentwebui.port\": 8080,\n  \"utorrentwebui.server\": \"http://localhost\",\n  \"utorrentwebui.use_auth\": true,\n  \"utorrentwebui.username\": \"admin\",\n  \"vuze.password\": \"*****\",\n  \"vuze.path\": \"/transmission/rpc\",\n  \"vuze.port\": 9091,\n  \"vuze.server\": \"http://localhost\",\n  \"vuze.use_auth\": true,\n  \"vuze.username\": \"vuze\",\n  \"torrenting.min_seeders\": 2,\n  \"torrenting.min_seeders_enabled\": false,\n  \"proxy.allowUnsafe\": true\n}"
  },
  {
    "name": "Other significant Local Storage keys",
    "data": "{\n  \"1.1.4TorrentHashListCleanup\": \"Tue Apr 04 2017 23:29:49 GMT+1000 (AUS Eastern Standard Time)\",\n  \"1.1.4cleanupOrphanedEpisodes\": \"Tue Apr 04 2017 23:29:48 GMT+1000 (AUS Eastern Standard Time)\",\n  \"1.1.4cleanupOrphanedSeasons\": \"Tue Apr 04 2017 23:29:48 GMT+1000 (AUS Eastern Standard Time)\",\n  \"1.1.4qBittorrentPre32\": \"Tue Apr 04 2017 23:29:43 GMT+1000 (AUS Eastern Standard Time)\",\n  \"1.1.4refresh\": \"Tue Apr 04 2017 23:29:53 GMT+1000 (AUS Eastern Standard Time)\",\n  \"1.1.4refreshTrendingCache\": \"Tue Apr 04 2017 23:29:43 GMT+1000 (AUS Eastern Standard Time)\",\n  \"1.1.4updateDelugeAuth\": \"Tue Apr 04 2017 23:29:43 GMT+1000 (AUS Eastern Standard Time)\",\n  \"1.1.4updateTransmissionPath\": \"Tue Apr 04 2017 23:29:43 GMT+1000 (AUS Eastern Standard Time)\",\n  \"1.1.5FetchFirstXemAliasMap\": \"Sat Sep 02 2017 17:53:08 GMT+1000 (AUS Eastern Standard Time)\",\n  \"1.1.5deleteSearchEngines\": \"Thu Aug 10 2017 21:13:09 GMT+1000 (AUS Eastern Standard Time)\",\n  \"1.1.5fanartCleanup\": \"Thu Aug 10 2017 21:13:25 GMT+1000 (AUS Eastern Standard Time)\",\n  \"1.1.5updateDelugeAuth\": \"Thu Aug 10 2017 21:13:09 GMT+1000 (AUS Eastern Standard Time)\",\n  \"1.1.5updateTorrenting.min_seeders\": \"Thu Aug 10 2017 21:13:09 GMT+1000 (AUS Eastern Standard Time)\",\n  \"1.1migration\": \"Tue Apr 04 2017 23:29:46 GMT+1000 (AUS Eastern Standard Time)\",\n  \"autobackup.lastrun\": \"1503839842378\",\n  \"database.version.Episodes\": \"14\",\n  \"database.version.Fanart\": \"1\",\n  \"database.version.Jackett\": \"2\",\n  \"database.version.SearchEngines\": \"2\",\n  \"database.version.Seasons\": \"6\",\n  \"database.version.Series\": \"16\",\n  \"database.version.WatchList\": \"1\",\n  \"database.version.WatchListObject\": \"1\",\n  \"fanart.bootstrapped\": \"1\",\n  \"github.lastupdatecheck\": \"1491312586468\",\n  \"snr.lastFetched\": \"1503839781243\",\n  \"standalone.position\": \"{\\\"width\\\":1368,\\\"height\\\":730,\\\"x\\\":0,\\\"y\\\":0,\\\"state\\\":\\\"maximized\\\"}\",\n  \"standalone.zoomlevel\": \"6\",\n  \"torrenting.client\": \"qBittorrent 3.2+\",\n  \"trackers.lastFetched\": \"1506059987799\",\n  \"trakttv.lastupdated\": \"1506059994151\",\n  \"trakttv.lastupdated.trending\": \"1506060013749\",\n  \"trakttv.refresh_token\": \"d737e0f0ed8a2ef31ea26f1afb7f70bdc1b750b02af9b1a1d7b8f65a9e95e16e\",\n  \"upgrade.notify\": \"1.1.5\",\n  \"utorrent.port\": \"10000\",\n  \"xem.lastFetched\": \"1504323490564\"\n}"
  },
  {
    "name": "DB Series",
    "data": 23
  },
  {
    "name": "DB Series Hidden From Calendar",
    "data": 0
  },
  {
    "name": "DB Seasons",
    "data": 196
  },
  {
    "name": "DB Episodes",
    "data": 2974
  },
  {
    "name": "DB Fanart",
    "data": 1916
  },
  {
    "name": "DB Jackett",
    "data": 0
  }
]
...
![image](https://user-images.githubusercontent.com/32200745/30750699-818b7c2a-9ffa-11e7-88e2-e1a26e99ebc0.png)

[bandicam 2017-09-23 00-52-33-419.zip](https://github.com/SchizoDuckie/DuckieTV/files/1324932/bandicam.2017-09-23.00-52-33-419.zip)

**Comment by garfield69** [comment]
I think we are going to need access to the *Development Tools* to dig into this one... but DT is not available on the Stable Standalone version.     
So,     
- Could you download and install the latest Development Nightly at https://github.com/DuckieTV/Nightlies/releases , (it installs over the top of the Stable release)     
- and once started, repeat you *find-a-torrent* attempt.      
- Then click on the **F12** key to open the *Development tools* page,     
- and click on the **console** tab to view the log.     
- near the left side of the console right-click to open the sub-menu and select *save as* to dump the log to a text file,     
- and post it here for us to take a look at.     
![image](https://user-images.githubusercontent.com/6933240/30778613-a5c002c2-a136-11e7-83f7-0ec04f69a4da.png)

BTW, thanks for the comprehensive report :smile:

**Comment by garfield69** [comment]
Also, do any of the other pop ups work? for instance:
![image](https://user-images.githubusercontent.com/6933240/30779619-f3a764c4-a151-11e7-81dc-0824fa5420dd.png)
or:
![image](https://user-images.githubusercontent.com/6933240/30779633-3da0aaa4-a152-11e7-981f-9c139232d994.png)
or:
![image](https://user-images.githubusercontent.com/6933240/30779627-163780f0-a152-11e7-9875-f2ee9a324a7a.png)

**Comment by jakeferris13** [comment]
The other popups **do** open but still not find a torrent. I appreciate the help.

[Console Dump and Other popups.zip](https://github.com/SchizoDuckie/DuckieTV/files/1327315/Console.Dump.and.Other.popups.zip)

 I didn't click the settings icon next to find a torrent in the clip but it works as well.

**Comment by garfield69** [comment]
The console.log was useful, as was the output from the *Opt-In error Tracking* you forgot to tell me you had enabled ;-)      
So the problem stems from these error messages:
```
duckietv.github.io/xem-cache/aliasmap.json Failed to load resource: net::ERR_CONNECTION_RESET
duckietv.github.io/SceneNameExceptions/SceneDateExceptions.json Failed to load resource: net::ERR_CONNECTION_RESET
duckietv.github.io/xem-cache/mappings.json Failed to load resource: net::ERR_CONNECTION_RESET
duckietv.github.io/SceneNameExceptions/SceneNameExceptions.json Failed to load resource: net::ERR_CONNECTION_RESET
```
When you click on the *find-a-torrent* from the episodes details page, we pre-load the torrent-search dialogue with the episode name and season/episode number.     
But first we check with the scene-name exceptions table to see if we need to adjust the s/e or even replace it with a dated or absolute number.      
However, in your case all the xem-cache and scene-name-exceptions table were not loaded because of web errors.      

The fix is two fold:     
1. I've got to amend the scene-name service to handle missing exceptions tables, which it assumes is always available.
2. We need to discover why you are unable to fetch the tables from github.io.

Regarding item (2), do have a firewall that is blocking access from DuckieTV to github.io?       
if you were to use your chrome browser to navigate to https://duckietv.github.io/SceneNameExceptions/SceneNameExceptions.json do you get a table in response?

**Comment by garfield69** [comment]
the latest Nightly at https://github.com/DuckieTV/Nightlies/releases should allow you to use the find-a-torrent even if you still cannot get those github.io fetches to work.

**Comment by jakeferris13** [comment]
That link took to a table of shows, I don't think there is a firewall blocking GitHub/DuckieTV as it's my home internet, I'm not sure how to check though. 

The new nightly release works great from what I can tell as the popup works and allows me to download shows.

![image](https://user-images.githubusercontent.com/32200745/30800892-d2501f04-a224-11e7-97ce-ccff8ac26b3b.png)
[Clip of it working + New console dump.zip](https://github.com/SchizoDuckie/DuckieTV/files/1328893/Clip.of.it.working.New.console.dump.zip)
