### ISSUE TITLE
Cannot connect to Vuze

### ISSUE THREAD

**Issue by forumguy** [SchizoDuckie/DuckieTV#957]
I am using Standalone 201704220130 and cannot connect to Vuze.  This started to happen about a week ago.
...

I am using a Mac running the latest version of Sierra
...

**Describe the problem you are having and steps to reproduce if available**
...

{
  "KickAssTorrents.mirror": "https://kat.cr",
  "ThePirateBay.mirror": "https://pirateproxybay.tech/",
  "application.language": "en_us",
  "application.locale": "en_us",
  "autodownload.minSeeders": 1,
  "autodownload.period": 4,
  "background-rotator.opacity": "0.4",
  "main.viewmode": "calendar",
  "calendar.mode": "week",
  "calendar.show-specials": true,
  "calendar.show-downloaded": true,
  "calendar.show-episode-numbers": true,
  "calendar.startSunday": true,
  "client.determinedlocale": "en_us",
  "download.ratings": true,
  "lastSync": -1,
  "library.smallposters": true,
  "library.seriesgrid": true,
  "kc.always": false,
  "qbittorrent.server": "http://localhost",
  "qbittorrent.port": 8080,
  "qbittorrent.use_auth": true,
  "qbittorrent.username": "admin",
  "qbittorrent.password": "*****",
  "qbittorrent32plus.server": "http://localhost",
  "qbittorrent32plus.port": 8181,
  "qbittorrent32plus.use_auth": true,
  "qbittorrent32plus.username": "admin",
  "qbittorrent32plus.password": "*****",
  "series.displaymode": "poster",
  "storage.sync": false,
  "sync.progress": true,
  "tixati.server": "http://localhost",
  "tixati.use_auth": true,
  "tixati.port": 8888,
  "tixati.username": "admin",
  "tixati.password": "*****",
  "topSites.enabled": false,
  "topSites.mode": "onhover",
  "torrenting.autodownload": true,
  "torrenting.autostop": true,
  "torrenting.autostop_all": false,
  "torrenting.client": "Vuze",
  "torrenting.directory": true,
  "torrenting.enabled": true,
  "torrenting.progress": true,
  "torrenting.searchprovider": "TorrentZ2",
  "torrenting.searchquality": "",
  "torrenting.streaming": true,
  "vuze.server": "http://10.55.0.6",
  "vuze.port": 9091,
  "vuze.use_auth": true,
  "vuze.username": "vuze",
  "vuze.password": "*****",
  "transmission.server": "http://localhost",
  "transmission.port": 9091,
  "transmission.use_auth": true,
  "transmission.username": "admin",
  "transmission.password": "*****",
  "trakttv.passwordHash": "*****",
  "trakttv.sync": true,
  "trakttv.username": null,
  "utorrentwebui.server": "http://localhost",
  "utorrentwebui.port": 8080,
  "utorrentwebui.username": "admin",
  "utorrentwebui.password": "*****",
  "utorrentwebui.use_auth": true,
  "deluge.server": "http://localhost",
  "deluge.port": 8112,
  "deluge.password": "*****",
  "deluge.use_auth": false,
  "subtitles.languages": [
    "eng"
  ],
  "trakt-update.period": 1,
  "autodownload.lastrun": 1505673957934,
  "vuze.path": "/transmission/rpc",
  "torrentDialog.showAdvanced.enabled": true,
  "series.not-watched-eps-btn": false,
  "torrenting.global_size_min_enabled": true,
  "autobackup.period": "weekly",
  "torrenting.min_seeders": 1,
  "autodownload.multiSE": {
    "ThePirateBay": true,
    "1337x": true,
    "IsoHunt": true,
    "KATcr": true,
    "Nyaa": true,
    "RarBG": true,
    "ShowRSS": true,
    "TorrentDownloads": true,
    "TorrentZ2": true,
    "Zooqle": true,
    "EzTV.ag": true,
    "Idope": true,
    "LimeTorrents": true,
    "SkyTorrents": true
  },
  "torrenting.global_size_max": 1000,
  "torrenting.global_size_max_enabled": true
}

**Comment by garfield69** [comment]
I've just spotted this!!! Sorry no one has replied :-(
Have you resolved this or have you moved on to something else?

**Comment by garfield69** [comment]
no reply, presumed resolved.
