### ISSUE TITLE
Auto Download no longer working

### ISSUE THREAD

**Issue by mbspencer** [SchizoDuckie/DuckieTV#961]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
3.3.16 Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
v201708070130
**What is your Operating System (Windows, Mac, Linux, Android)**
...Windows 10

**Describe the problem you are having and steps to reproduce if available**
...Auto download no longer works. It worked fine in qtorrent 3.3.15 but after upgrading to 3.3.16 the box pops up like it is going to download, but the file is never added to qtorrent. I can still search for torrent and add that way. I downgraded to 3.3.15 but still have the same issue.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by mbspencer** [comment]
Upgrading to V1.1.5 of Duckie TV fixed my issue.

**Comment by garfield69** [comment]
resolved.
