### ISSUE TITLE
Fonts in Greek Language

### ISSUE THREAD

**Issue by dzogas** [SchizoDuckie/DuckieTV#967]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...Chrome Extension (New Tab)

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...1.1.6

**What is your Operating System (Windows, Mac, Linux, Android)**
... Windows

**Describe the problem you are having and steps to reproduce if available**
... Greek language is not supported with the font used.

As these are HTML/CSS files I will try to fix the problem myself and let you know.

**Comment by dzogas** [comment]
Ok, as I am still looking for the 'perfect' fonts to support Greek Language, I have succesfully fixed it with a couple of 'testing' fonts and some changes in the main.css file locally.
When I finish that, shall I upload the changed main.css file and the fonts in my forked DuckieTV for you to check it?

**Comment by garfield69** [comment]
yes please.     
The topic of fonts is not one I am familiar with, so I am interested in what changes you had to make to allow for proper viewing of your language.      

I don't know what font management processes chrome extensions have available to them, (I will need to do some research), but the ideal scenario is one where the appropriate font is used based on the language selected.     
However, if memory serves, I think that DuckieTV has a hard-coded set of fonts it uses that ignore the language selected (this needs verifying).

I would like to see us progress (if possible) to a more flexible language-vs-font model, and even implement a user setting to allow the user to choose from a select set of fonts.

**Comment by dzogas** [comment]
Doing it in the extention is easy. Just a few changes in the main.css file and you are ready.
In my opinion it is best to use the same google fonts for all languages.

I do not know if this can be implemented in the desktop version as well though...

Yes, it has. 3 different ttf files are used for light, regular and bold.

Will let you know what I find.....

**Comment by garfield69** [comment]
Oh!
And while this is probably far too late, you may want to read this wiki https://github.com/SchizoDuckie/DuckieTV/wiki/Can-I-help-DuckieTV-with-Language-Translations%3F#things-to-keep-in-mind-when-doing-the-translations

**Comment by dzogas** [comment]
Almost everything is ok. Just two thigns to fix.
Will get right on it...

**Comment by dzogas** [comment]
I just noticed that the font you are using is ALL CAPS and but using any greek font it changes everything to small letters. So, the only thing I can do is try to make all translations in capital letters.

**Comment by garfield69** [comment]
Nah, don't do that. 
Many users prefer the legibility of the mixed case font, so I wouldn't go making everything Ucase.

**Comment by Js41637** [comment]
What fonts are you talking about? The Bebas font has limited support but any thing it doesnt have falls back to a generic as defined in css. I dunno if i'm doing it wrong but my computer manages to render greek letters fine? What's the actual issue here?

**Comment by garfield69** [comment]
@Js41637  there is no fallback list for strong https://github.com/SchizoDuckie/DuckieTV/blob/32930a7114e55c3c3605f60a364072adbc3cb1a8/css/main.css#L167 and https://github.com/SchizoDuckie/DuckieTV/blob/32930a7114e55c3c3605f60a364072adbc3cb1a8/css/main.css#L2310 and https://github.com/SchizoDuckie/DuckieTV/blob/32930a7114e55c3c3605f60a364072adbc3cb1a8/css/main.css#L2683
or does the fallback get inherited from elsewhere?

**Comment by Js41637** [comment]
Fonts usually always cascade. There is a `font-family: helvetica, sans-serif;` on the body of the site so it will fallback to that I think. As for actual fonts. I don't know if my computer just has the required fonts but I get no font rending issues.

**Comment by Js41637** [comment]
I mean if we can render Chinese text, it seems doubtful we can't do Greek. Also just noticed the settings menu pages don't translate for me on 1.1.5

**Comment by Js41637** [comment]
Huh weird, the settings menu doesn't translate if you load onto it directly, if you navigate away from it and go back to it they get translated...

**Comment by garfield69** [comment]
I think it will become clearer what if anything needs to be done to the css, once the complete Greek file is integrated.   
For now it's best to wait untill that s done.

**Comment by dzogas** [comment]
@Js41637 Damn!! I am so new to this... I cannot quote to reply.... anyway,  as garfield69 said, the font just falls back to helvetica which it shows a mixed helvetica for greek and the bebas font for the english which it looks bad.

@garfield69 I understand what you say but the users will not get the same gui experience in Greek as in the English and if we change the fonts to support Greek, then the Eglinh will be in lowercase as well...
This is so confusing...

**Comment by Js41637** [comment]
Well we're not changing the main Bebas font. I'm not sure if making it lowercase will matter too much. I dunno how well supported the fonts are when it comes to css but `text-transform: uppercase` should work for Greek as well for the parts in capitals.

**Comment by dzogas** [comment]
![untitled](https://user-images.githubusercontent.com/26818516/31306319-dabf3744-ab55-11e7-82bd-79efa64bf2c6.jpg)

If you are not prepared to change the font, Greek will simply not work (as you can see from the snapshot, greek is helvetica and english is the bebas font) Uppercase will not matter as they are totally different fonts.

Anyway, since I have started to translating DuckieTV in Greek I will finish it and I will just make the necessary changes in my computer.

**Comment by dzogas** [comment]
There is a problem though.. The month names are not correct in Greek and I cannot find where to fix those.

**Comment by garfield69** [comment]
>There is a problem though.. The month names are not correct in Greek and I cannot find where to fix those.

dates are in the _locales/angular-locale_el_gr.js file.

**Comment by dzogas** [comment]
I see the are not UTF-8 though. Is this on purpose?

**Comment by garfield69** [comment]
the file was imported direct from the angular i18n site.     
Feel free to replace anything inside it to suit your requirements. 
Use the English counterpart en_us as a reference if you want to ditch the ascii codes

**Comment by dzogas** [comment]
ok thanx... Will have it ready in 5 minutes

**Comment by garfield69** [comment]
no problems. take your time, there is no rush, there are no completion deadlines to meet. :-)

**Comment by garfield69** [comment]
A reminder that once you are ready, you need to generate a pull request to submit your completed changes for us to merge.    
I will hold off on #972 to avoid generating a clash with your Greek translation file.
After which I will look into ways to resolve your English-Greek on one line in different fonts issue.

**Comment by garfield69** [comment]
resolved with 5acb017ba3f0ce88cc1ca1d1cc99fcc06f246c64

**Comment by dzogas** [comment]
I think I may have forked it sooner that I had to... and I had already finished the translations... damn! anyway... will fork again now and will translate again...
