### ISSUE TITLE
Duckie does not find show that is in trakt.tv.

### ISSUE THREAD

**Issue by Cowboy1968** [SchizoDuckie/DuckieTV#971]
Hi,
I have encountered this issue once before and you gave me a fix that did not work this time.  I want to add the series Haunted USA to duckie, but even with quotations, it does not find it.  I went to Trakt.tv and did a search and it is there, so I am not sure why it does not see it.  I even went so far as to delete the old June version of Duckie and installed the newest nightly (please see info below) but still no luck.
...

DuckieTV Web Based201710100130Current Date and TimeTue, 10 Oct 2017 05:06:08 GMTNWJS, Chromium0.25.0 , 61.0.3163.79UserAgentDuckieTV-Standalone Nightly v201710100130 Macintosh; Intel Mac OS X 10_12_6Platform, VendorMacIntel, Google Inc.Screen (width x height)1360 x 768Default Search EngineThePirateBay (Enabled)Default Torrent ClientTransmission (Enabled but Not Connected to Host)Auto Download Service(Disabled)Last checked TraktTV for DB updates onSat, 07 Oct 2017 04:09:00 GMTUser Preferences on Local Storage{   "KickAssTorrents.mirror": "https://kat.cr",   "ThePirateBay.mirror": "https://thepiratebay.SE",   "application.language": "en_ca",   "application.locale": "en_ca",   "autodownload.minSeeders": 50,   "autodownload.period": 1,   "background-rotator.opacity": "0.75",   "calendar.mode": "date",   "calendar.show-specials": true,   "calendar.show-downloaded": true,   "calendar.startSunday": true,   "client.determinedlocale": "en_us",   "download.ratings": false,   "lastSync": -1,   "library.smallposters": false,   "series.displaymode": "poster",   "standalone.startupMinimized": false,   "standalone.zoomlevel": 6,   "storage.sync": false,   "sync.progress": true,   "topSites.enabled": false,   "topSites.mode": "onclick",   "torrenting.autodownload": false,   "torrenting.autostop": true,   "torrenting.autostop_all": false,   "torrenting.client": "Transmission",   "torrenting.directory": true,   "torrenting.enabled": true,   "torrenting.progress": true,   "torrenting.searchprovider": "ThePirateBay",   "torrenting.searchquality": "",   "torrenting.streaming": true,   "transmission.server": "http://localhost",   "transmission.port": 9091,   "transmission.use_auth": true,   "transmission.username": "admin",   "transmission.password": "*****",   "trakttv.passwordHash": "*****",   "trakttv.sync": false,   "trakttv.username": null,   "subtitles.languages": [     "eng"   ],   "autodownload.lastrun": 1507611375069,   "calendar.show-episode-numbers": true,   "transmission.path": "/transmission/rpc",   "torrenting.min_seeders": 1,   "main.viewmode": "calendar",   "series.not-watched-eps-btn": true,   "library.seriesgrid": true,   "notifications.enabled": true,   "autodownload.multiSE": {     "ThePirateBay": true,     "1337x": true,     "IsoHunt": true,     "KATcr": true,     "Nyaa": true,     "RarBG": true,     "ShowRSS": true,     "TorrentDownloads": true,     "TorrentZ2": true,     "Zooqle": true,     "EzTV.ag": true,     "Idope": true,     "LimeTorrents": true,     "SkyTorrents": true   },   "torrentDialog.2.enabled": true,   "torrentDialog.2.activeSE": {     "ThePirateBay": true,     "1337x": true,     "IsoHunt": true,     "KATcr": true,     "Nyaa": true,     "RarBG": true,     "ShowRSS": true,     "TorrentDownloads": true,     "TorrentZ2": true,     "Zooqle": true,     "EzTV.ag": true,     "Idope": true,     "LimeTorrents": true,     "SkyTorrents": true   } }Other significant Local Storage keys{   "1.1.4TorrentHashListCleanup": "Mon Jun 19 2017 20:42:21 GMT-0700 (PDT)",   "1.1.4cleanupOrphanedEpisodes": "Mon Jun 19 2017 20:39:44 GMT-0700 (PDT)",   "1.1.4cleanupOrphanedSeasons": "Mon Jun 19 2017 20:39:45 GMT-0700 (PDT)",   "1.1.4qBittorrentPre32": "Mon Jun 19 2017 20:39:40 GMT-0700 (PDT)",   "1.1.4refresh": "Mon Jun 19 2017 20:39:50 GMT-0700 (PDT)",   "1.1.4refreshTrendingCache": "Mon Jun 19 2017 20:39:40 GMT-0700 (PDT)",   "1.1.4updateTransmissionPath": "Mon Jun 19 2017 20:39:40 GMT-0700 (PDT)",   "1.1.5FetchFirstXemAliasMap": "Mon Oct 09 2017 21:55:56 GMT-0700 (PDT)",   "1.1.5deleteSearchEngines": "Mon Jun 19 2017 20:39:40 GMT-0700 (PDT)",   "1.1.5fanartCleanup": "Mon Oct 09 2017 21:56:57 GMT-0700 (PDT)",   "1.1.5updateDelugeAuth": "Mon Jun 19 2017 20:39:40 GMT-0700 (PDT)",   "1.1.5updateTorrenting.min_seeders": "Mon Jun 19 2017 20:39:40 GMT-0700 (PDT)",   "1.1.6deleteWatchList": "Mon Oct 09 2017 21:55:56 GMT-0700 (PDT)",   "1.1migration": "Fri Aug 07 2015 22:10:11 GMT-0700 (PDT)",   "autobackup.lastrun": "1507697775000",   "database.version.Episodes": "14",   "database.version.Fanart": "1",   "database.version.Jackett": "2",   "database.version.Seasons": "6",   "database.version.Series": "16",   "fanart.bootstrapped": "1",   "github.lastupdatecheck": "1451606767589",   "install.notify": "201706200130",   "optin_error_reporting": "true",   "optin_error_reporting.start_time": "1507611967527",   "runtime.event": "{\"reason\":\"install\"}",   "snr.lastFetched": "1507273202551",   "standalone.alwaysShowTray": "Y",   "standalone.closeSystray": "Y",   "standalone.minimizeSystray": "Y",   "standalone.position": "{\"width\":1000,\"height\":741,\"x\":75,\"y\":23,\"state\":\"normal\"}",   "standalone.startupMinimized": "N",   "standalone.trayColor": "-indigo",   "standalone.zoomlevel": "6",   "torrenting.client": "Transmission",   "trackers.lastFetched": "1505792867552",   "trakttv.lastupdated": "1507349340302",   "trakttv.lastupdated.trending": "0",   "uniqueId": "42d76d2c-7eb9-1045-ba8f-9342f502e4fd",   "upgrade.notify": "1.1.3",   "xem.lastFetched": "1507273202540" }DB Series105DB Series Hidden From Calendar0DB Seasons461DB Episodes6964DB Fanart1820DB Jackett0 | DuckieTV Web Based | 201710100130 | Current Date and Time | Tue, 10 Oct 2017 05:06:08 GMT | NWJS, Chromium | 0.25.0 , 61.0.3163.79 | UserAgent | DuckieTV-Standalone Nightly v201710100130 Macintosh; Intel Mac OS X 10_12_6 | Platform, Vendor | MacIntel, Google Inc. | Screen (width x height) | 1360 x 768 | Default Search Engine | ThePirateBay (Enabled) | Default Torrent Client | Transmission (Enabled but Not Connected to Host) | Auto Download Service | (Disabled) | Last checked TraktTV for DB updates on | Sat, 07 Oct 2017 04:09:00 GMT | User Preferences on Local Storage | {   "KickAssTorrents.mirror": "https://kat.cr",   "ThePirateBay.mirror": "https://thepiratebay.SE",   "application.language": "en_ca",   "application.locale": "en_ca",   "autodownload.minSeeders": 50,   "autodownload.period": 1,   "background-rotator.opacity": "0.75",   "calendar.mode": "date",   "calendar.show-specials": true,   "calendar.show-downloaded": true,   "calendar.startSunday": true,   "client.determinedlocale": "en_us",   "download.ratings": false,   "lastSync": -1,   "library.smallposters": false,   "series.displaymode": "poster",   "standalone.startupMinimized": false,   "standalone.zoomlevel": 6,   "storage.sync": false,   "sync.progress": true,   "topSites.enabled": false,   "topSites.mode": "onclick",   "torrenting.autodownload": false,   "torrenting.autostop": true,   "torrenting.autostop_all": false,   "torrenting.client": "Transmission",   "torrenting.directory": true,   "torrenting.enabled": true,   "torrenting.progress": true,   "torrenting.searchprovider": "ThePirateBay",   "torrenting.searchquality": "",   "torrenting.streaming": true,   "transmission.server": "http://localhost",   "transmission.port": 9091,   "transmission.use_auth": true,   "transmission.username": "admin",   "transmission.password": "*****",   "trakttv.passwordHash": "*****",   "trakttv.sync": false,   "trakttv.username": null,   "subtitles.languages": [     "eng"   ],   "autodownload.lastrun": 1507611375069,   "calendar.show-episode-numbers": true,   "transmission.path": "/transmission/rpc",   "torrenting.min_seeders": 1,   "main.viewmode": "calendar",   "series.not-watched-eps-btn": true,   "library.seriesgrid": true,   "notifications.enabled": true,   "autodownload.multiSE": {     "ThePirateBay": true,     "1337x": true,     "IsoHunt": true,     "KATcr": true,     "Nyaa": true,     "RarBG": true,     "ShowRSS": true,     "TorrentDownloads": true,     "TorrentZ2": true,     "Zooqle": true,     "EzTV.ag": true,     "Idope": true,     "LimeTorrents": true,     "SkyTorrents": true   },   "torrentDialog.2.enabled": true,   "torrentDialog.2.activeSE": {     "ThePirateBay": true,     "1337x": true,     "IsoHunt": true,     "KATcr": true,     "Nyaa": true,     "RarBG": true,     "ShowRSS": true,     "TorrentDownloads": true,     "TorrentZ2": true,     "Zooqle": true,     "EzTV.ag": true,     "Idope": true,     "LimeTorrents": true,     "SkyTorrents": true   } } | Other significant Local Storage keys | {   "1.1.4TorrentHashListCleanup": "Mon Jun 19 2017 20:42:21 GMT-0700 (PDT)",   "1.1.4cleanupOrphanedEpisodes": "Mon Jun 19 2017 20:39:44 GMT-0700 (PDT)",   "1.1.4cleanupOrphanedSeasons": "Mon Jun 19 2017 20:39:45 GMT-0700 (PDT)",   "1.1.4qBittorrentPre32": "Mon Jun 19 2017 20:39:40 GMT-0700 (PDT)",   "1.1.4refresh": "Mon Jun 19 2017 20:39:50 GMT-0700 (PDT)",   "1.1.4refreshTrendingCache": "Mon Jun 19 2017 20:39:40 GMT-0700 (PDT)",   "1.1.4updateTransmissionPath": "Mon Jun 19 2017 20:39:40 GMT-0700 (PDT)",   "1.1.5FetchFirstXemAliasMap": "Mon Oct 09 2017 21:55:56 GMT-0700 (PDT)",   "1.1.5deleteSearchEngines": "Mon Jun 19 2017 20:39:40 GMT-0700 (PDT)",   "1.1.5fanartCleanup": "Mon Oct 09 2017 21:56:57 GMT-0700 (PDT)",   "1.1.5updateDelugeAuth": "Mon Jun 19 2017 20:39:40 GMT-0700 (PDT)",   "1.1.5updateTorrenting.min_seeders": "Mon Jun 19 2017 20:39:40 GMT-0700 (PDT)",   "1.1.6deleteWatchList": "Mon Oct 09 2017 21:55:56 GMT-0700 (PDT)",   "1.1migration": "Fri Aug 07 2015 22:10:11 GMT-0700 (PDT)",   "autobackup.lastrun": "1507697775000",   "database.version.Episodes": "14",   "database.version.Fanart": "1",   "database.version.Jackett": "2",   "database.version.Seasons": "6",   "database.version.Series": "16",   "fanart.bootstrapped": "1",   "github.lastupdatecheck": "1451606767589",   "install.notify": "201706200130",   "optin_error_reporting": "true",   "optin_error_reporting.start_time": "1507611967527",   "runtime.event": "{\"reason\":\"install\"}",   "snr.lastFetched": "1507273202551",   "standalone.alwaysShowTray": "Y",   "standalone.closeSystray": "Y",   "standalone.minimizeSystray": "Y",   "standalone.position": "{\"width\":1000,\"height\":741,\"x\":75,\"y\":23,\"state\":\"normal\"}",   "standalone.startupMinimized": "N",   "standalone.trayColor": "-indigo",   "standalone.zoomlevel": "6",   "torrenting.client": "Transmission",   "trackers.lastFetched": "1505792867552",   "trakttv.lastupdated": "1507349340302",   "trakttv.lastupdated.trending": "0",   "uniqueId": "42d76d2c-7eb9-1045-ba8f-9342f502e4fd",   "upgrade.notify": "1.1.3",   "xem.lastFetched": "1507273202540" } | DB Series | 105 | DB Series Hidden From Calendar | 0 | DB Seasons | 461 | DB Episodes | 6964 | DB Fanart | 1820 | DB Jackett | 0
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
DuckieTV Web Based | 201710100130
Current Date and Time | Tue, 10 Oct 2017 05:06:08 GMT
NWJS, Chromium | 0.25.0 , 61.0.3163.79
UserAgent | DuckieTV-Standalone Nightly v201710100130 Macintosh; Intel Mac OS X 10_12_6
Platform, Vendor | MacIntel, Google Inc.
Screen (width x height) | 1360 x 768
Default Search Engine | ThePirateBay (Enabled)
Default Torrent Client | Transmission (Enabled but Not Connected to Host)
Auto Download Service | (Disabled)
Last checked TraktTV for DB updates on | Sat, 07 Oct 2017 04:09:00 GMT
User Preferences on Local Storage | {   "KickAssTorrents.mirror": "https://kat.cr",   "ThePirateBay.mirror": "https://thepiratebay.SE",   "application.language": "en_ca",   "application.locale": "en_ca",   "autodownload.minSeeders": 50,   "autodownload.period": 1,   "background-rotator.opacity": "0.75",   "calendar.mode": "date",   "calendar.show-specials": true,   "calendar.show-downloaded": true,   "calendar.startSunday": true,   "client.determinedlocale": "en_us",   "download.ratings": false,   "lastSync": -1,   "library.smallposters": false,   "series.displaymode": "poster",   "standalone.startupMinimized": false,   "standalone.zoomlevel": 6,   "storage.sync": false,   "sync.progress": true,   "topSites.enabled": false,   "topSites.mode": "onclick",   "torrenting.autodownload": false,   "torrenting.autostop": true,   "torrenting.autostop_all": false,   "torrenting.client": "Transmission",   "torrenting.directory": true,   "torrenting.enabled": true,   "torrenting.progress": true,   "torrenting.searchprovider": "ThePirateBay",   "torrenting.searchquality": "",   "torrenting.streaming": true,   "transmission.server": "http://localhost",   "transmission.port": 9091,   "transmission.use_auth": true,   "transmission.username": "admin",   "transmission.password": "*****",   "trakttv.passwordHash": "*****",   "trakttv.sync": false,   "trakttv.username": null,   "subtitles.languages": [     "eng"   ],   "autodownload.lastrun": 1507611375069,   "calendar.show-episode-numbers": true,   "transmission.path": "/transmission/rpc",   "torrenting.min_seeders": 1,   "main.viewmode": "calendar",   "series.not-watched-eps-btn": true,   "library.seriesgrid": true,   "notifications.enabled": true,   "autodownload.multiSE": {     "ThePirateBay": true,     "1337x": true,     "IsoHunt": true,     "KATcr": true,     "Nyaa": true,     "RarBG": true,     "ShowRSS": true,     "TorrentDownloads": true,     "TorrentZ2": true,     "Zooqle": true,     "EzTV.ag": true,     "Idope": true,     "LimeTorrents": true,     "SkyTorrents": true   },   "torrentDialog.2.enabled": true,   "torrentDialog.2.activeSE": {     "ThePirateBay": true,     "1337x": true,     "IsoHunt": true,     "KATcr": true,     "Nyaa": true,     "RarBG": true,     "ShowRSS": true,     "TorrentDownloads": true,     "TorrentZ2": true,     "Zooqle": true,     "EzTV.ag": true,     "Idope": true,     "LimeTorrents": true,     "SkyTorrents": true   } }
Other significant Local Storage keys | {   "1.1.4TorrentHashListCleanup": "Mon Jun 19 2017 20:42:21 GMT-0700 (PDT)",   "1.1.4cleanupOrphanedEpisodes": "Mon Jun 19 2017 20:39:44 GMT-0700 (PDT)",   "1.1.4cleanupOrphanedSeasons": "Mon Jun 19 2017 20:39:45 GMT-0700 (PDT)",   "1.1.4qBittorrentPre32": "Mon Jun 19 2017 20:39:40 GMT-0700 (PDT)",   "1.1.4refresh": "Mon Jun 19 2017 20:39:50 GMT-0700 (PDT)",   "1.1.4refreshTrendingCache": "Mon Jun 19 2017 20:39:40 GMT-0700 (PDT)",   "1.1.4updateTransmissionPath": "Mon Jun 19 2017 20:39:40 GMT-0700 (PDT)",   "1.1.5FetchFirstXemAliasMap": "Mon Oct 09 2017 21:55:56 GMT-0700 (PDT)",   "1.1.5deleteSearchEngines": "Mon Jun 19 2017 20:39:40 GMT-0700 (PDT)",   "1.1.5fanartCleanup": "Mon Oct 09 2017 21:56:57 GMT-0700 (PDT)",   "1.1.5updateDelugeAuth": "Mon Jun 19 2017 20:39:40 GMT-0700 (PDT)",   "1.1.5updateTorrenting.min_seeders": "Mon Jun 19 2017 20:39:40 GMT-0700 (PDT)",   "1.1.6deleteWatchList": "Mon Oct 09 2017 21:55:56 GMT-0700 (PDT)",   "1.1migration": "Fri Aug 07 2015 22:10:11 GMT-0700 (PDT)",   "autobackup.lastrun": "1507697775000",   "database.version.Episodes": "14",   "database.version.Fanart": "1",   "database.version.Jackett": "2",   "database.version.Seasons": "6",   "database.version.Series": "16",   "fanart.bootstrapped": "1",   "github.lastupdatecheck": "1451606767589",   "install.notify": "201706200130",   "optin_error_reporting": "true",   "optin_error_reporting.start_time": "1507611967527",   "runtime.event": "{\"reason\":\"install\"}",   "snr.lastFetched": "1507273202551",   "standalone.alwaysShowTray": "Y",   "standalone.closeSystray": "Y",   "standalone.minimizeSystray": "Y",   "standalone.position": "{\"width\":1000,\"height\":741,\"x\":75,\"y\":23,\"state\":\"normal\"}",   "standalone.startupMinimized": "N",   "standalone.trayColor": "-indigo",   "standalone.zoomlevel": "6",   "torrenting.client": "Transmission",   "trackers.lastFetched": "1505792867552",   "trakttv.lastupdated": "1507349340302",   "trakttv.lastupdated.trending": "0",   "uniqueId": "42d76d2c-7eb9-1045-ba8f-9342f502e4fd",   "upgrade.notify": "1.1.3",   "xem.lastFetched": "1507273202540" }
DB Series | 105
DB Series Hidden From Calendar | 0
DB Seasons | 461
DB Episodes | 6964
DB Fanart | 1820
DB Jackett | 0
Opt-In error TrackingIf you have a problem with DuckieTV, we can ask you to enable this functionality temporarily and repeat the scenario that lead to your error. This will help us get to the core of your problems more easily. Please don't enable this unless asked to. We don't want your data!When you do enable this functionality, please report the Unique Tracking ID to us so we can find your error logs.current setting: EnabledUnique tracking id: 42d76d2c-7eb9-1045-ba8f-9342f502e4fdClick to disable Opt-In error Tracking

**Comment by garfield69** [comment]
how very strange. 
I typed `haunted usa` in the search box and this is what I see:
![image](https://user-images.githubusercontent.com/6933240/31370818-22e1e710-adea-11e7-8b13-8c107bb733fd.png)
so I had no problem adding this show.     
When you do the same what do you get?

**Comment by Cowboy1968** [comment]
Okay very weird here If I type Haunted USA with a capital H, which is how it is spelled in trakt tv I get the Show Most haunted Live USA.  But, if I type it as you did with no capital H and USA in small letters not capitals I get Haunted USA.  I would have never thought to try non capitalization as its not proper English and more importantly does not match how its titled in trakt or the tv database etc.  So I am confused as how it would be found without exactly matching how its listed in Trakt tv, but typing it exactly as it is in Trakt tv does not work?

**Comment by garfield69** [comment]
I have no answer for you. When I used the capitalised version I still get a result:
![image](https://user-images.githubusercontent.com/6933240/31371502-aa3be208-aded-11e7-9004-165b9472e88e.png)
Whatever you type we send to the Trakt.TV API, and it determines what to return to DuckieTV.     
This is the url used for the example search above: `https://api-v2launch.trakt.tv/search/show?extended=full&limit=100&fields=title,aliases&query=Haunted%20USA`
If you copy and paste this into your Chrome Browser address box, do you get a response that contains the two shows?
![image](https://user-images.githubusercontent.com/6933240/31371589-2aa70af8-adee-11e7-85f2-81bb392d3ce9.png)
Anyway the point is, it's out of DuckieTV's control. As you may know, the Trakt.TV API is serviced by multiple servers, which respond to queries within their designated region. It is possible that the servers responding to your queries are not the same ones responding to mine, and maybe they are not configured the same way.... this is just speculation on my part, I have no idea.
Glad you got your show in the end.

**Comment by Cowboy1968** [comment]
Hi,
Sorry I just realized I might have come across as an A--hole in that last reply, I just get frustrated when things don't work logically.  I do appreciate all the time and effort you have put into this so I can have a FREE TV calendar which makes the wife very happy, so Thank You and sorry if I came off unappreciative. 

I tried pasting the link you sent me and I just get the One show (see below).  Oh well now I know to try all different possible ways if a show does not show up the first time.

Thanks :-)
  |  
-- | --
0 |  
type | "show"
score | -3.4028235e+38
show |  
title | "Most Haunted Live USA"
year | 2007
ids |  
trakt | 70883
slug | "most-haunted-live-usa"
tvdb | 85364
imdb | null
tmdb | null
tvrage | null
overview | "Most Haunted Live USA is a spin-off of the paranormal reality television series Most Haunted and was also produced by Antix Productions. The show consists of paranormal investigations broadcast live.These were aired live in the USA only, but would later air in the UK, on Living TV, in a 2 hour edited version, classed as part of the \"Almost Live\" series."
first_aired | "2007-06-01T07:00:00.000Z"
airs |  
day | null
time | null
timezone | "Europe/London"
runtime | 420
certification | null
network | "Travel Channel"
country | null
trailer | null
homepage | null
status | "ended"
rating | 0
votes | 0
updated_at | "2016-09-05T10:38:41.000Z"
language | null
available_translations | []
genres |  
0 | "reality"
aired_episodes | 8

**Comment by garfield69** [comment]
No problem.     
Looking back at one of your previous replies, a point of note that may interest you: 
The servers that Trakt.TV use for presenting their WEB site, (and online searches thereof), are not the same servers that Trakt.TV use to provide data via their API.     
So I am not at all surprised that you get different results using Trakt.tV's web site versus DuckieTV making request via Trakt.TV's API.
