### ISSUE TITLE
Bug: Monday always blurry on hover

### ISSUE THREAD

**Issue by cajeiri** [SchizoDuckie/DuckieTV#975]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Chrome New Tab

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Latest Nightly

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 7 SP1 64bit

**Describe the problem you are having and steps to reproduce if available**
Monday (first day of the week for me)'s text is always a bit blurred when it is enlarged by a hover-over

How should I troubleshoot some data for you to check this out. Might be something gone iffy on my side and not a general problem.

**Comment by garfield69** [comment]
Can you provide a screen shot of a blurry hovered Monday?     
Also what screen resolution does the About page report?

**Comment by cajeiri** [comment]
Resolution 1920x1080, so the native one.
![2](https://user-images.githubusercontent.com/13944976/31457471-88e51fa6-aec5-11e7-845c-44ccd80e216d.jpg)
![1](https://user-images.githubusercontent.com/13944976/31457472-890140aa-aec5-11e7-8cd2-0b7a24a4cda9.jpg)

**Comment by garfield69** [comment]
if you flick to the full month display, do the other Mondays of the month also show up blurry?

**Comment by cajeiri** [comment]
Yes, except for the last one (30th of October).

**Comment by garfield69** [comment]
my eyesight is not as good as it used to be, but I think I see the same thing on my screen as well, so it's clearly an artefact of the presentation, possibly to do with the overlay from the action bar of the left.     
Here are my screen shots to compare:
![image](https://user-images.githubusercontent.com/6933240/31459738-934b15b2-af20-11e7-87a6-0fe68a0d26d6.png)
![image](https://user-images.githubusercontent.com/6933240/31459755-9c829a06-af20-11e7-9759-b315d92046e3.png)

**Comment by cajeiri** [comment]
Yes, I see the same blurriness on your screenshots too. To be honest, it's so minor at first I though my eyesight was just acting up too. Oddly enough they don't seem to show up on the s04e10 (14:00) bubble. (I checked, it's the same for me.) I did consider the sidebar being the culprit, but I'm always liable to suspect I somehow broke it myself instead of it being a problem of its own :)

**Comment by garfield69** [comment]
Update to the latest nightly when it comes out later today, and see if it has improved or not.

**Comment by cajeiri** [comment]
3017.10.12.91 does not seem to fix the bug for me.

**Comment by garfield69** [comment]
thanks. I will keep digging.

**Comment by cajeiri** [comment]
@Js41637 You're a saint. That one's been bugging me since forever <3 Glad you managed to find the culprit.

**Comment by Js41637** [comment]
Have you checked to see if it is fixed for you? It seemed to make it not blurry for me but it's just some weird bug with Chrome's Rendering engine. If this doesn't fix it then there is nothing else we can do but it seemed to fix it for me.
