### ISSUE TITLE
Add torrent client for Android's tTorrent Lite

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#976]
as raised in this [Reddit](https://www.reddit.com/r/duckietv/comments/75fwnh/torrent_client_for_android_duckie/)

Mar5kid wrote:

> TTorrent lite. It's free and offers webui which is quite unique for android torrent app. I think it may also offer API.
>http://www.techovity.com/how-to-use-android-device-as-a-torrent-server/
>https://play.google.com/store/apps/details?id=hu.tagsoft.ttorrent.lite&hl=en

- [x] connect
- [x] login
- [x] get name
- [x] get download speed
- [x] get torrent list
- [x] get progress
- [x] get status
- [x] ~~get files~~ (not supported by tTorrentLite 1.5.12 webui)
- [x] start, stop, pause, remove
- [x] ~~get download dir~~ (not supported by tTorrentLite 1.5.12 webui)
- [x] add magnet
- [x] add torrent by url
- [x] add torrent by upload

**Comment by Pretzel40k** [comment]
I use ttorrent (paid version) on an android tv box as my main downloader so would really appreciate this.'[
![screenshot_20171212-215155](https://user-images.githubusercontent.com/16616224/33910499-d90c0642-df86-11e7-8280-aae20b798b3c.png)
All I know for sure is it allows for login (user and password), SSL, adding magnet links, pausing/resuming, remove torrent (with or without data). I currently manage it remotely (from my phone) with transdrone.
If there's any way I can help (probably not, but i'll try).

**Comment by garfield69** [comment]
@Pretzel40k  FYI, the latest DuckieTV nightly at https://github.com/DuckieTV/Nightlies/releases now has (a still experimental) support for connection to tTorrent (Lite or Pro).
Should handle magnets, but I have not got the .torrent working yet. Test results and feedback welcome.
Wiki should you need it at https://github.com/SchizoDuckie/DuckieTV/wiki/Setting-up-tTorrent-with-DuckieTV

**Comment by Pretzel40k** [comment]
Thanks. I'm trying it now :). Only (minor) issue so far is it won't connect with SSL (https) enabled in tTorrent. Username, password, port and magnets are working perfectly. Brilliant job!
