### ISSUE TITLE
How to resize calendar to fit into one screen?

### ISSUE THREAD

**Issue by syphondog3** [SchizoDuckie/DuckieTV#980]
In 1.1.5, is there a way to shrink the calendar so it fits in one display? That way, I don't have to scroll down to the bottom week at that time.

I know it automatically resizes when the side panel is open, but was wondering if there was another way.

Running 1.1.5 on Chrome. DuckieTV installed for new Tab mode.

Thanks!

**Comment by garfield69** [comment]
1. you can use the zoom commands. https://github.com/SchizoDuckie/DuckieTV/wiki/How-can-I-make-the-fonts-larger-or-smaller%3F
2. or you could switch from month view to week view
![image](https://user-images.githubusercontent.com/6933240/31578429-7776ce08-b17d-11e7-9a2d-b0bf9ff1ce89.png)

**Comment by syphondog3** [comment]
Yeah, I tried the Scroll zoom commands. Was hoping there was a better way, but I think that will have to do for now. 

Thanks for your rapid support, Garfield!
