### ISSUE TITLE
episode button

### ISSUE THREAD

**Issue by lamaresh** [SchizoDuckie/DuckieTV#981]
episodes button shows the first season with non-downloaded episodes but I think it would be better to show the first season with non-watched episodes.
For example: i have season 1 all watched, season 2 all downloaded, season 3 empty. In such setting episodes button link to season 3, imho it should show season 2.

**Comment by garfield69** [comment]
![image](https://user-images.githubusercontent.com/6933240/31581142-936738b8-b1bf-11e7-951c-49e0f1c68310.png)
