### ISSUE TITLE
DuckieTV freezes when Qbittorrent is connected

### ISSUE THREAD

**Issue by snarebyte** [SchizoDuckie/DuckieTV#982]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
... Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
... 1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
... Windows Server 2008 R2

**Describe the problem you are having and steps to reproduce if available**
... After updating Qbittorrent to version 3.3.16 Duckie TV freezes when it and QB are both running. Upon opening DuckieTV it sends an undownloded torrent to QB to download, then freezes after a few seconds. 

**Attach any DuckieTV statistics or Developer Console logs if available**
...
[statistics.txt](https://github.com/SchizoDuckie/DuckieTV/files/1385827/statistics.txt)

**Comment by garfield69** [comment]
The term **freeze** implies that DuckieTV stops responding to clicks on any and all buttons, a total lockup. Is this what you mean?       
Hmm. Unusual.     
We are going to need to look at the logs. But the Standalone 1.1.5 does not include the *Development Tools* SDK pack.      

 So here is what I would like you to do please:      
1. Shutdown Qbt and DuckieTV.
2. Download and install the latest Nightly from https://github.com/DuckieTV/Nightlies/releases
3. Start up DuckieTV (but not Qbt)
4. Press the **F12** key to open the *Development Tools* page, and
5. Click on the **Console** tab to view the log.
6. Configure the *console settings* by clicking on the cog icon, and 
7. Set the timestamps 
8. And preserve logs
9. And click the cog to close the settings.
![image](https://user-images.githubusercontent.com/6933240/31597597-c4e4cbee-b2a5-11e7-80f4-920ab5b9093a.png)
10. Start Qbt, and DuckieTV should connect to it within 20 seconds or so.
11. When you spot that things have *frozen* capture the log by
12. On a clear area near the left had side **right click** your mouse to open the menu 
13. And select the  **Save-As** and save the log file.
 ![image](https://user-images.githubusercontent.com/6933240/31597740-8dfd61b2-b2a6-11e7-8e6f-3a6c61bd64a5.png)
14. Now **zip** the log into an archive and **drag and drop** the archive below, so I can take a look.
Thanks.

**Comment by snarebyte** [comment]
Thanks for the reply. Here is the log file. After it sends the magnet uri, Qbt downloads what it was sent, and Duckie is stuck with a flickering hourglass and no response.
[bagblfnohpiddokbpaacecffdboomafe-1508158033631.log](https://github.com/SchizoDuckie/DuckieTV/files/1387451/bagblfnohpiddokbpaacecffdboomafe-1508158033631.log)

**Comment by garfield69** [comment]
Well the log you provided is surprisingly clean, with no errors.     
Which is frustrating.     
So I've added some debugs in strategic places to hopefully yield some clues.
Could you please do the following:
1. Shutdown Qbt and DuckieTV.
2. Download and install the latest Nightly from https://github.com/DuckieTV/Nightlies/releases
3. Start up DuckieTV (but not Qbt)
4. Press the **F12** key to open the Development Tools page, and
5. Click on the **Console** tab to view the log.
6. Enable *Verbose* logging
![image](https://user-images.githubusercontent.com/6933240/31641127-22e81bbc-b33f-11e7-8ce0-10e1c65b1eb8.png)
7. at the `>` prompt. paste the following command `localStorage.setItem('debug982', 'true')` and press *Enter*
    This will turn on my debug statements
8. Shutdown DuckieTV and Start it up again (so that the debug flag gets activated)
9. Start qBt and watch for the fault.
10. capture the full log and drop it here.

Let's see what if anything that produces ;-) Thanks.
P.S. to turn off the debugging, use this command `localStorage.removeItem('debug982')` and recycle DuckieTV to disable that flag.

**Comment by snarebyte** [comment]
Here you go. Looks pretty much the same, unless I screwed up activating the debug flag.
[bagblfnohpiddokbpaacecffdboomafe-1508264356558.log](https://github.com/SchizoDuckie/DuckieTV/files/1392113/bagblfnohpiddokbpaacecffdboomafe-1508264356558.log)


***edit- I tried to remove and readd the debug flag and saw that it comes back with "undefined" when running that command.**

**Comment by garfield69** [comment]
>Looks pretty much the same, unless I screwed up activating the debug flag.      

You activated the flag. I can see some of the additional logging I was expecting, but not all....

> I tried to remove and readd the debug flag and saw that it comes back with "undefined" when running that command.      

Ignore the *undefined* when issuing the commands, it is not a problem.
If you need to check if the flag is there or not, you can click on the **application** tab, expand the **local storage** on the left hand side navigation tree, and scroll down looking for the *debug982* key.      
It's usually alphabetically sorted, but can be at the bottom of the list if newly defined.
![image](https://user-images.githubusercontent.com/6933240/31683134-97a8e500-b3d8-11e7-9052-651ad756e1dc.png)


Anyway, I can see the login to qBt is successful, and the magnet being sent by DuckieTV to qBt via the HTTP POST, but I cannot see the RESPONSE from qBt that the magnet was accepted.
There should have been a `qBittorrent32plusAPI.addmagnet Ok.`
Yet you reported that qBt starts to download the torrent data, so something appears broken at this point.

It looks as if qBt is not responding to the HTTP POST with a status 200 reply, which might explain the hourglass you are seeing. Presumably, at some point, the pending HTTP POST on the DuckieTV side will timeout with an error... however long that takes. Until then, DuckieTV will not post the Notify, and all sorts of processes will start to pile up behind the wait-for-reply.

Unfortunately all my machines are 32bit, and the 32bit version of qBt 3.3.16 seems to be working fine on my win7 sandbox.
I presume your windows server 2008 is 64bit, and you are using 64bit versions of qBt and DuckieTV standalone, is that correct?

The next lot of debugging are progressively going to be more technical.
If my theory pans out, the long term fix may well end up with us  loading a bug report to the qBt team.

Before starting to debug this further, I am going to need your help, and at this point I should ask: Just how much time do you want to invest on this? Because the quick way out is to go back to using qBt 3.3.15, though this would not be a good long term solution.

**Comment by snarebyte** [comment]
Yes, I'm running 64-bit versions of everything.  I'm willing to work on this as long as you are. It's a great piece of software, and I would love to help make it better.

**Comment by garfield69** [comment]
ok then. 
So we need to look at the network traffic betweek qBt and DuckieTV while a magnet load is going on.
To do this, we need to prepare the Development tools ahead of the DuckieTV auto-download service (ADS) finding a magnet and pushing it to qBt.
To do this, 
1. shut down qBt and start up DuckieTV.
2. open the *Development Tools* page
3. click on the **Network** tab
4. start qBt
5. once a magnet is sent, look on the left panel for a **download** event 

A good download event looks like this:
![image](https://user-images.githubusercontent.com/6933240/31687862-f86509c4-b3e6-11e7-9051-d61c7f037ec7.png)
![image](https://user-images.githubusercontent.com/6933240/31687948-31b9ded4-b3e7-11e7-8e58-02266a1c4cf4.png)
![image](https://user-images.githubusercontent.com/6933240/31688005-618236e8-b3e7-11e7-86a3-37d200b10c03.png)

What does yours look like?
(use the **Ctrl -** key combo to reduce the zoom so you get all the data on screeen and use the **screen print** ket to capture the image, and paste it below so I can have a look. 
I'd like the *Headers, Response,* and *Timing* pages of the event please, like I provided above. Thanks.

**Comment by snarebyte** [comment]
Here are the Headers and Timing panes, preview and Responses are both blank.

![headers](https://user-images.githubusercontent.com/32822775/31688427-51664750-b35a-11e7-8c5b-0ba0b0df7a0a.PNG)
![timing](https://user-images.githubusercontent.com/32822775/31688428-51734554-b35a-11e7-9b85-656e8076fa15.PNG)

**Comment by garfield69** [comment]
Yes, it's *stalled*. Does it ever complete? I wonder what the default timeout value is ....

OK, so now we need to eliminate DuckieTV from the picture, to see if it is something to do with the way DuckietV prepares its request to qBt that is at fault or not.

So, from your Chrome Browser:
1. login to the qBt WEBUI. Looking at your DuckieTV settings, it should be at `localhost:8082`.
2. open the *development tools* page and switch to the *Network* tab (**F12** works the same way here).
3. on the qBt WEBUI click on the *add a torrent link* and 
4. paste the following magnet
```
magnet:?xt=urn:btih:99905df86fbad3698e44d2b7467fab916af3533b&tr=udp://tracker.skyts.net:6969/announce&tr=udp://tracker.safe.moe:6969/announce&tr=udp://tracker.piratepublic.com:1337/announce&tr=udp://tracker.pirateparty.gr:6969/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://tracker.coppersurfer.tk:6969/announce&tr=http://tracker.leechers-paradise.org:80/announce&tr=udp://allesanddro.de:1337/announce&tr=udp://9.rarbg.com:2710/announce&tr=http://p4p.arenabg.com:1337/announce&tr=udp://p4p.arenabg.com:1337/announce&tr=udp://tracker.internetwarriors.net:1337/announce&tr=http://tracker.opentrackr.org:1337/announce&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://public.popcorn-tracker.org:6969/announce&tr=udp://peerfect.org:6969/announce&tr=udp://ipv4.tracker.harry.lu:80/announce&tr=udp://explodie.org:6969/announce&tr=http://mgtracker.org:6969/announce&tr=udp://tracker.vanitycore.co:6969/announce
```
and click on the *download* button.
![image](https://user-images.githubusercontent.com/6933240/31689173-1886dbca-b3eb-11e7-920d-6232da380412.png)

5. now back to the *Network*, look for the *download* event, and let see what that looks like.

**Comment by snarebyte** [comment]
First, I let DuckieTV in the hung state all afternoon and it never cleared itself. 

Here's all the tabs from the download.

![cookies](https://user-images.githubusercontent.com/32822775/31697833-fc32c47e-b387-11e7-83f3-fc96321c9943.PNG)
![headers](https://user-images.githubusercontent.com/32822775/31697834-fc4507ba-b387-11e7-9557-21517eabac22.PNG)
![previews](https://user-images.githubusercontent.com/32822775/31697835-fc588268-b387-11e7-99c4-c8b20d70cdb8.PNG)
![responses](https://user-images.githubusercontent.com/32822775/31697836-fc6884a6-b387-11e7-957f-24f37457be42.PNG)
![timing](https://user-images.githubusercontent.com/32822775/31697837-fc78109c-b387-11e7-83c9-572ae6b1fd3a.PNG)

**Comment by garfield69** [comment]
ok then. So now we know that there is something extra we need to add to our DuckieTV http post to qbt to make it work. Clearly the 64bit version of qBt is choking on a missing header parameter that the 32bit version is happy to do without.
I'll do some research and see if I can find out what that is.

**Comment by snarebyte** [comment]
Awesome, let me know when you have something ready to test.

**Comment by austingillis85** [comment]
First off thank for the work on this project. 
I'm having the same issue with my 64 bit using qbitorrent on hyper-V if you would like another person's setup to look at. I'm not a programmer but am more than happy to help where I can.

**Comment by garfield69** [comment]
I'm going to have to ask the qBt devs for support. But before I raise a ticket with them I should provide them with a qBt log for them to look at. So what we should do next is perform a one-off magnet test so we can generate a clean but complete log.    
Could you do the following please:
1. shutdown qBt and DuckieTV.
2. start DuckieTV, and switch off the auto-download service
![image](https://user-images.githubusercontent.com/6933240/31746996-e1725f9c-b4c6-11e7-9301-4c71e5af6fb4.png)
3. shut DuckieTV down
4. start qBt and access settings
![image](https://user-images.githubusercontent.com/6933240/31747444-635a43ba-b4c9-11e7-9b22-152c3276ed2e.png)
5. scroll to the bottom of the *Behaviour* side panel, and enable log 
6. and location
7. apply and 
8. ok
![image](https://user-images.githubusercontent.com/6933240/31747574-195824d4-b4ca-11e7-8dce-16b2aac01fa4.png)
9. next, make sure all logging classes are ticked
![image](https://user-images.githubusercontent.com/6933240/31747628-5fae5d90-b4ca-11e7-8386-05b7f696e326.png)
10. **stop** any active torrents and shutdown qBt
11. start qBt and DuckieTV
12. find an episode on todays calendar and open the episode-details side panel
13. click on the **find-a-torrent** button and then on the magnet icon for any torrent you like
![image](https://user-images.githubusercontent.com/6933240/31747802-66fb1056-b4cb-11e7-9590-ec6231fadc18.png)
14. wait for the magnet to show up on qBt and for DuckieTV to freeze
15. then shut down DuckieTV and 
16. delete the torrent from qBt if you don't want to keep it
17. shutdown qBt
18. find the qBt log, zip and drag and drop here
Thank you!

**Comment by snarebyte** [comment]
Here you go.
[qbittorrent.log](https://github.com/SchizoDuckie/DuckieTV/files/1396857/qbittorrent.log)

It's a small, sad looking log file...

**Comment by garfield69** [comment]
issue [#7619](https://github.com/qbittorrent/qBittorrent/issues/7619) has been raised with the qBt team

**Comment by garfield69** [comment]
qBt support have provided a [test build](https://github.com/Chocobo1/temp/raw/master/1/qbittorrent.exe) they would like you to try. This will add extra logging when there is invalid headers found, or so they tell me.
After starting, do a test just like last time to generate the qBt log and we shall see if it provides anything useful to them.

**Comment by garfield69** [comment]
Could you also confirm that when DuckieTV does freeze, the magnets sent from DuckieTV do actually still arrive on qBt, and that qBt does successfully download any and all files from those magnets? Thanks.

**Comment by garfield69** [comment]
I'm also interested in what this test version reports in the *About*. When I ran the qbittorrent.exe provided by that link, I got:
![image](https://user-images.githubusercontent.com/6933240/31756863-c7179608-b502-11e7-8490-6cb5bb9e9efb.png)
Do you get the same?

**Comment by austingillis85** [comment]
I know you were talking to snarebyte but when I click on the magnet link it adds it to qbittorrent and downloads but in the meantime it freezes duckie. I also tried this with utorrent and the same situation happens. Just FYI

**Comment by garfield69** [comment]
@austingillis85  Thanks for the feedback.     
Are you able to download the [qbtorrent 3.4.0beta2](https://github.com/Chocobo1/temp/raw/master/1/qbittorrent.exe)  and produce the log requested? (details on setting up the log and in this ticket above someplace.     
Thanks.

The feedback about utorrent is new to me, this suggests that the problem may be with duckietv standalone 64bit ... 
It may be useful to know if the problem exists in the chrome extension version, when run under the chrome browser 64 bit. 
As a test, could you install https://chrome.google.com/webstore/detail/duckietv-browser-action-m/ikhklcamhmfmjbhckdjoabiepglbhaid and test if you get the same issue there?
Cheers.

**Comment by austingillis85** [comment]
Yes I can. I'll do it as soon as I get home tonight.

**Comment by snarebyte** [comment]
Sorry for dropping off the past few days, traveling for work.
I'm getting the same version for the Beta here
![qbt](https://user-images.githubusercontent.com/32822775/31922173-901af1e4-b841-11e7-9f04-ace0a5c5d509.PNG)

Here is the log from the torrent addition in standalone version.
[qbittorrent.log](https://github.com/SchizoDuckie/DuckieTV/files/1409346/qbittorrent.log)

Here is the log from the chrome extension. You are correct in that the Chrome extension does not freeze up when adding a torrent.
[qbittorrent.log](https://github.com/SchizoDuckie/DuckieTV/files/1409362/qbittorrent.log)

**Comment by garfield69** [comment]
@snarebyte  just so I am clear, are you saying that the DuckieTV chrome extension does not freeze when connected to qBt 3.3.16 64bit?
Does DuckieTV Standalone freeze when connected to the qBt 3.4.0b2 32bit program?

**Comment by snarebyte** [comment]
@garfield69 Correct.  The chrome extension operates normally with Qbt 3.3.16 64-bit.
DuckieTV does freeze with the qBt 3.4.0b2 32bit app.

**Comment by snarebyte** [comment]
@garfield69 Any update on this? Based on the interaction between the apps it sounds like the issue is with the DuckieTV standalone client.

**Comment by garfield69** [comment]
nothing yet.
Have you tried running the DuckieTV Standalone 32 bit version?

**Comment by snarebyte** [comment]
I haven't. I've been using the chrome extension.

**Comment by austingillis85** [comment]
Yea I switched to 32 but standalone and it works perfect. I’m running it on qbittorent and hyper v. Love the program. Just a 64 bit issue it looks like
