### ISSUE TITLE
Opening the program issue

### ISSUE THREAD

**Issue by cardcaptorsfan** [SchizoDuckie/DuckieTV#986]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
... standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
... standalone web based 1.1.5 

**What is your Operating System (Windows, Mac, Linux, Android)**
... windows 10

**Describe the problem you are having and steps to reproduce if available**
... a issue with loading it up after clicking on the start menu icon also noticed it open more than one processes 

**Attach any DuckieTV statistics or Developer Console logs if available**
... 972bcc28-f4e8-ac34-9890-11302b4ac7ff
![issue](https://user-images.githubusercontent.com/20249977/32144032-1398d9b4-bc89-11e7-9b92-09b0571a6cf3.png)

**Comment by garfield69** [comment]
Sorry, what is the issue?    
Were you expecting a single process only?    
DuckieTV is a [Chrome Browser Extension](https://chrome.google.com/webstore/category/extensions?hl=en-GB) app, written in *JavaScript* using the [AngularJS](https://angularjs.org/) framework.   
The **standalone** version of DuckieTV is exactly the same code encapsulated by the [nwjs](https://nwjs.io/) run time environment.    
There will be at least 4 processes running, and as many as six from time to time. This is normal.

**Comment by cardcaptorsfan** [comment]
I thought there was supposed to be one process because I thought it was going to slow down my computer
