### ISSUE TITLE
Name for series

### ISSUE THREAD

**Issue by cajeiri** [SchizoDuckie/DuckieTV#987]
Can "The Ancient Magus' Bride" receive an exception naming as "Mahoutsukai no Yome - 04"?

**Comment by garfield69** [comment]
DuckieTV fetches a list of available alias for any series daily from [thexem](http://thexem.de/).
Currently *The Ancient Magus' Bride* has only one alias, *Mahou Tsukai no Yome*.
If you want thexem to make changes, Join #xem on irc.freenode.net and ask them directly :-)

**Comment by cajeiri** [comment]
They added it after I asked them directly :)

**Comment by garfield69** [comment]
excellent.

**Comment by cajeiri** [comment]
Tried today, only difference seems to be it's now "The Ancient Magus Bride", losing the ' symbol. Might I have a cache problem or has it just not updated yet?

**Comment by garfield69** [comment]
Hmm. Our server picked up changes from thexem:
*XEM Cache update 2017-11-01T14:26:30.276Z*
which contained the following alias table changes:
```json
   "316842": [
 -    "Mahou Tsukai no Yome"
 +    "Mahou Tsukai no Yome",
 +    "Mahoutsukai no Yome"
```
So all that remains is a question of timing. As long as your DuckieTV  did its update request after the server did its refresh on the above date, then when you visit the series-detail page for *The Ancient Magus' Bride* and click its settings cog, then the alias pull-down should contain two entries to select from:
![image](https://user-images.githubusercontent.com/6933240/32288258-3d7ce6dc-bf98-11e7-8026-c05c1a516639.png)

**Comment by cajeiri** [comment]
Guess it has yet to update then. I'll give it a try tomorrow again and notify you of the results :)

**Comment by garfield69** [comment]
which version of DuckieTV are you running?

**Comment by cajeiri** [comment]
The nightly new tab version, currently 3017.11.1.91, which is the one from today.

**Comment by garfield69** [comment]
you can force your DuckieTV to do an update if you want:
1. press **F12** to open the *Development Tools* page and 
2. click on the **console** tab to view the log
3. at the `>` prompt paste the following
```javascript
localStorage.removeItem('xem.aliasmap');
localStorage.removeItem('xem.mappings');
localStorage.removeItem('xem.lastFetched');
```
4. and press enter. you'll get a `undefined` response.
5. shutdown DuckieTV and Start it up again.
6. DuckieTV should rebuild the xem tables by fetching them from the server.
The console log should show:
![image](https://user-images.githubusercontent.com/6933240/32289252-1f2fe910-bf9b-11e7-9119-368ec5bd17a6.png)
If you see this instead:
![image](https://user-images.githubusercontent.com/6933240/32289335-52f19582-bf9b-11e7-9185-c8d8c99e1249.png)
then DuckieTV is using its local copy of the tables.
