### ISSUE TITLE
add ettv.tv search engine

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#988]
ETTV, ETHD and DTOne have now joined forces and launched a torrent site of their own, simply named ETTV.tv.
https://torrentfreak.com/extratorrent-uploader-groups-launch-their-own-torrent-site-171031/

**Comment by zero77** [comment]
Thanks, although could you look at adding ettv to Jackett also.

**Comment by garfield69** [comment]
FYI DuckieTV and Jackett are two separate projects.
Post requests for Jackett definitions to https://github.com/Jackett/Jackett.
