### ISSUE TITLE
[enhancement req] add series specific ignore-keywords option

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#989]
As raised by this [reddit](https://www.reddit.com/r/duckietv/comments/7abh87/ignore_keywords_per_series/)     
Requesting support for series specific ignore-keywords.
Probably should also add the include-keywords too, as this is different that the string-append series. 
  Specific option currently supported (the include/ignore keywords deal with single words at a time, the append-string does not).

**Comment by 2635599** [comment]
this is something i asked about awhile back, and you currently have one thread on reddit about removing us from the show title that this would be perfect for.

**Comment by garfield69** [comment]
https://github.com/DuckieTV/Nightlies/releases/tag/nightly-202209031611 
the autodownload service can now use the series custom includes and custom excludes
