### ISSUE TITLE
Auto-download after standby issue

### ISSUE THREAD

**Issue by Mawio** [SchizoDuckie/DuckieTV#992]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
... Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
... Stable 1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
... Windows 10

**Describe the problem you are having and steps to reproduce if available**
... The issue is about auto-download. Usually it works fine, the only problem I have is if I put the computer on standby, when I use the task manager to automatically wake up the pc, the auto-download doesn't work until I restart duckietv ( i leave it open before i put it on standby).

(sorry for bad english)

**Comment by garfield69** [comment]
Sorry, nothing we can do about this. The Auto-download Service is launched every 15 minutes, but it looks like the services that DuckieTV depend on for scheduling the task cannot handle a standby event.
I don't have the resources to investigate further.
Recommend you close DuckieTV before going into standby or continue to just restart DuckietV after wake-up.
