### ISSUE TITLE
Not finding results on TPB

### ISSUE THREAD

**Issue by jandreaucodes** [SchizoDuckie/DuckieTV#993]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Chrome extension New Tab

**What version of DuckieTV are you using (Stable 1.1.x / Nightly 
Current stable

**What is your Operating System (Windows, Mac, Linux, Android)**
Mac 10.12.3

**Describe the problem you are having and steps to reproduce if available**
None of my shows can find anything on Pirate Bay. The manual search just keeps spinning and never gets any results. 

It worked fine for months then suddenly stopped. 

I can get to Pirate Bay manually so it’s not an ISP block. I just get no results from DuckieTv

**Attach any DuckieTV statistics or Developer Console logs if available**
N/A

**Comment by garfield69** [comment]
First, some basic double checking of the settings.
Navigate to the DuckieTV *Settings > Torrent Search Engines* side panel, scroll down to the *The Pirate Bay* section, and double check that the *Main Mirror* is set to `https://thepiratebay.org`.
If it is not, change it and use the *Validate and Save* button to save it.      
Then scroll back up to the top and double check that the *Default Search Provider* is set to *The Pirate Bay*.
Having go those basic checks out of the way, if your searches using TPB on DuckieTV are still not working, then it's time to look at the log and see if there are any error messages that might explain what is going on.
So after the next search fails, press **Cmd-Alt-I** to open the *Development Tools* panel, and click on **Console** to view the log.
Look for any messages to do with TPB.

**Comment by jandreaucodes** [comment]
All set, thanks!

Somehow my proxy was set to thepiratebay.se, not thepiratebay.org. I wonder if I did that back when my ISP was blocking the site.

Working again now, though. Thanks!
