### ISSUE TITLE
DuckieTV Standalone on MacOSX never creates UI and doesn't run

### ISSUE THREAD

**Issue by dashnak** [SchizoDuckie/DuckieTV#995]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone 

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
MacOSX 10.11.6

**Describe the problem you are having and steps to reproduce if available**
When runnnig the app, it doesn't create a UI. It shows the icon in the dock, but the name in the menu bar is nwjs. The user interface is never created, and the menu bar name never changes. I don't know a way to reproduce the error, since it happens all the time. If I run the app under another account in the same computer, it works. I have been unable to locate some custom thing that could be causing the error in my account. I have been using the chrome button version and that one works well.

**Attach any DuckieTV statistics or Developer Console logs if available**
I don't have any acces to logs, since the app never launches.

![captura de pantalla 2017-11-16 12 22 34](https://user-images.githubusercontent.com/389654/32906090-ecec2678-cac9-11e7-9236-d10abb48ea0f.png)

**Comment by garfield69** [comment]
Sounds like something has gone wrong during the install/first time set up on your first account.      
- So firstly, make sure there are no active DuckieTV **processes** still running, kill any using your task manager  (either under DuckieTV or NWJS).      
- then locate the DuckieTV data folder for the first account, usually `~/Library/Application Support/DuckieTV-Standalone` and delete it (or rename it by appending `_old`)     
- Start DuckieTV and see if that fixes the problem

**Comment by dashnak** [comment]
This fixed it, thanks a lot.
