### ISSUE TITLE
Proxy with Utorrent

### ISSUE THREAD

**Issue by Wolivere** [SchizoDuckie/DuckieTV#996]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...
Chrome Extension
**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...
Stable
**What is your Operating System (Windows, Mac, Linux, Android)**
...
Windows 10
**Describe the problem you are having and steps to reproduce if available**
...
I have set up a proxy with Utorrent. When the proxy is active Duckie can not auto download, the integration says it works. But nothing happens.
**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
The uTorrent API that DuckieTV is using only supports same-host connections.
To support remote (or proxy) connections to uTorrent, use the DuckieTV uTorrent **WEBUI** client interface.
Should you need it you can find the Wiki guide [here](https://github.com/SchizoDuckie/DuckieTV/wiki/Setting-up-uTorrent-Web-UI-with-DuckieTV)

**Comment by Wolivere** [comment]
Thank you;

 When I switched to Duckie, I normally use Torrentday, but it did grab some shows from another torrent provider. And within hours I received emails from my ISP about it. So I set up jacket and stuck with Torrentday and set the proxy up. But then of coarse the auto down failed. SO will try this tonight

Thanks for the quick reply.


Charles E Ward Jr.


________________________________
