### ISSUE TITLE
Can no longer connect to deluge

### ISSUE THREAD

**Issue by akrolick** [SchizoDuckie/DuckieTV#998]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
DuckieTV Standalone Nightly v201702250010

**What is your Operating System (Windows, Mac, Linux, Android)**
Mac High Sierra 

Deluge Client: 1.3.15 (libtorrent: 1.0.9.0) - webui installed and I can connect from browser

**Describe the problem you are having and steps to reproduce if available**
I can no longer connect to deluge after updating deluge

**Attach any DuckieTV statistics or Developer Console logs if available**

Unable to connect to Deluge Retry in 15 seconds
app.js:540 POST http://localhost:8112/json 500 (Internal Server Error)
(anonymous) @ app.js:540
n @ deps.js:2212
(anonymous) @ deps.js:2210
(anonymous) @ deps.js:2244
$eval @ deps.js:2259
$digest @ deps.js:2256
$apply @ deps.js:2259
(anonymous) @ deps.js:2393
eg @ deps.js:2149
d @ deps.js:2149
deps.js:2231 Objectconfig: Objectdata: ""headers: (d)status: 500statusText: "Internal Server Error"__proto__: Object
(anonymous) @ deps.js:2231
(anonymous) @ deps.js:2204
(anonymous) @ deps.js:2245
$eval @ deps.js:2259
$digest @ deps.js:2256
$apply @ deps.js:2259
l @ deps.js:2211
completeRequest @ app.js:562
requestLoaded @ app.js:503
deps.js:2231 Deluge Connect call failed. No client listening.
(anonymous) @ deps.js:2231
(anonymous) @ deps.js:2204
(anonymous) @ deps.js:2245
$eval @ deps.js:2259
$digest @ deps.js:2256
$apply @ deps.js:2259
l @ deps.js:2211
completeRequest @ app.js:562
requestLoaded @ app.js:503
app.js:3815 Deluge connect error! Deluge Connect call failed. No client listening.
(anonymous) @ app.js:3815
(anonymous) @ deps.js:2244
$eval @ deps.js:2259
$digest @ deps.js:2256
$apply @ deps.js:2259
l @ deps.js:2211
completeRequest @ app.js:562
requestLoaded @ app.js:503

**Comment by garfield69** [comment]
Upgrade to the latest DuckieTV  Nightly from https://github.com/DuckieTV/Nightlies/releases

Your current Nightly from February 25th cannot connect to Deluge newer than 1.3.13, after they introduced Cross-Site Request Forgery (CSRF) protection in March with 1.3.14. This broke the DuckieTV Deluge client interface. Nightly from about version 20170326xxxx onwards can connect to the latest Deluge.
Duplicate of #880

**Comment by akrolick** [comment]
Fantastic.  Thank you so much; it works now!  I really think your
application is just terrific.  I was pretty upset to think I may have
messed it up.

If you ever set up a donation box I'd be happy to support you all.

Sincere thanks.

Best regards
Alex
