### ISSUE TITLE
No shows, can't backup after update

### ISSUE THREAD

**Issue by shepditch** [SchizoDuckie/DuckieTV#999]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...
Chrome Extension: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...
"Stable" 1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
...
Mac

**Describe the problem you are having and steps to reproduce if available**
...
Opened browser extension yesterday for the first time in a few days, got notification of update to 1.1.5.  No favorite shows visible, unable to restore from backup file (just hangs at loading screen) and can't add new favorites (also hangs at loading screen).  Am able to successfully connect to uTorrent webUI
I cleared all data but that didn't help so I uninstalled the browser extension (browser action mode) and tried to reinstall but the link to the browser action mode download appears to be broken (404).

**Attach any DuckieTV statistics or Developer Console logs if available**
...
Per the developer console, this is the error I get when attempting to add a new favorite:
deps.js:2353 TypeError: Cannot read property 'ID_Serie' of undefined
    at app.js:4679
    at deps.js:2366
    at m.$eval (deps.js:2381)
    at m.$digest (deps.js:2378)
    at m.$apply (deps.js:2381)
    at HTMLAnchorElement.<anonymous> (deps.js:2515)
    at eg (deps.js:2271)
    at HTMLAnchorElement.d (deps.js:2271)
(anonymous) @ deps.js:2353
(anonymous) @ deps.js:2326
(anonymous) @ deps.js:2367
$eval @ deps.js:2381
$digest @ deps.js:2378
$apply @ deps.js:2381
(anonymous) @ deps.js:2515
eg @ deps.js:2271
d @ deps.js:2271
...
I don't get a error message in the console while attempting to backup, but it hangs similar to trying to add a favorite from scratch.

Please Halp.
(tks)

**Comment by garfield69** [comment]
@SchizoDuckie  Please check the Google Webstore, it appears that DuckieTV Action-mode is not available for some reason.     
The NewTab, and Both nightly flavours are available at the webstore, so for some reason Google have suspended/removed the action-mode version?

**Comment by garfield69** [comment]
@shepditch  while we wait to see what @SchizoDuckie  can do about the missing app on the webstore, you may like to try out https://chrome.google.com/webstore/detail/duckietv-browser-action-m/ikhklcamhmfmjbhckdjoabiepglbhaid which is the Nightly (Canary) version of DuckieTV browser action mode app.

**Comment by SchizoDuckie** [comment]
It appears we were taken down, however I did what they asked me to do (add a privacy policy to the webstore profile)

![image](https://user-images.githubusercontent.com/111710/33631188-0de23d28-da0a-11e7-97fd-78c342d1b61e.png)

I'm working to sort this out with them.

**Comment by garfield69** [comment]
@shepditch  FYI action mode duckietv should be available from the google web store again
